import pathlib,subprocess,json,hashlib,os,datetime,time
R=pathlib.Path(subprocess.check_output(['git','rev-parse','--show-toplevel'],text=True).strip());A=R/'projects/chirality-app-dev';V=pathlib.Path(__file__).resolve().parent;O=V/'closeout-01';O.mkdir(exist_ok=False)
keep=['PATH','HOME','TMPDIR','TMP','TEMP','LANG','LC_ALL','SHELL','USER','LOGNAME'];env={k:v for k,v in os.environ.items() if k in keep};env['PYTHONDONTWRITEBYTECODE']='1'
(O/'environment.json').write_text(json.dumps({'effective':env,'other_environment_values_not_inherited':True},indent=2)+'\n');rows=[]
now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat();h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def run(argv,cwd,label):
 start=now();t=time.monotonic();p=subprocess.run(argv,cwd=cwd,env=env,text=True,capture_output=True);(O/(label+'.output.json')).write_text(json.dumps({'stdout':p.stdout,'stderr':p.stderr},indent=2)+'\n');row={'id':label,'argv':argv,'cwd':str(cwd),'start':start,'end':now(),'duration_seconds':time.monotonic()-t,'exit_code':p.returncode};rows.append(row);(O/'commands.json').write_text(json.dumps(rows,indent=2)+'\n');print(json.dumps(row),flush=True)
run(['python3','--version'],R,'python-version');run(['git','rev-parse','HEAD'],R,'head')
paths=subprocess.check_output(['git','ls-files','-z','AGENTS.md','agents','docs','skills','tools','runtime','projects/chirality-app-dev/AGENTS.md','projects/chirality-app-dev/software-workflow.json','projects/chirality-app-dev/loop','projects/chirality-app-dev/execution/_Scripts'],cwd=R).decode().split('\0');inputs={p:h(R/p) for p in sorted(set(paths)) if p and (R/p).is_file()};(O/'input-inventory.json').write_text(json.dumps(inputs,indent=2)+'\n')
a=json.loads((V/'ACTIVATION_PROVISIONAL_v9.json').read_text());freeze=R/a['freeze_path'];assert h(freeze)==a['freeze_sha256'];files=json.loads(freeze.read_text())['files'];assert all(h(R/x['path'])==x['sha256'] for x in files);(O/'scope-source-identity.json').write_text(json.dumps({'source_manifest_path':a['freeze_path'],'source_manifest_sha256':h(freeze),'files':files,'review_acceptance':'separate and pending; no render claim'},indent=2)+'\n')
run(['python3','tools/practitioner_harness/harness.py','self-check'],R,'selfcheck')
run(['python3','-m','pytest','-q','-p','no:cacheprovider','tools/practitioner_harness'],R,'practitioner-pytest')
run(['python3','tools/validation/validate_app_dev_loop_receipts.py','--repo-root','.'],R,'predecessor-receipt-validator')
run(['python3','execution/_Scripts/app_hold.py','scan','--require-register-match'],A,'app-hold-integrity')
run(['python3','execution/_Scripts/app_hold.py','check','--operation','reliance','--entry-path','APP_LOOP_SHELL_2026-09-05:GLOBAL_VALIDATION','--target','DEL-02-03'],A,'app-hold-reliance')
drift=[p for p,s in inputs.items() if not (R/p).is_file() or h(R/p)!=s];source_drift=[x['path'] for x in files if h(R/x['path'])!=x['sha256']];(O/'input-stability.json').write_text(json.dumps({'input_drift':drift,'source_drift':source_drift,'input_count':len(inputs)},indent=2)+'\n');(O/'return.json').write_text(json.dumps({'verdict':'PASS' if not drift and not source_drift and all(x['exit_code']==0 for x in rows) else 'FAIL','final_receipt_after_append':'OWED','full_staged_check':'OWED CHANGE-owned','no_frontend_process_checks':True},indent=2)+'\n');(O/'evidence-sha256.json').write_text(json.dumps({str(p.relative_to(O)):h(p) for p in sorted(O.iterdir()) if p.is_file()},indent=2)+'\n')
