import { afterEach, expect, it, vi } from 'vitest';
import { mkdtemp, realpath, rm, symlink, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { createPlanExportDialogHandler } from '../../../electron/plan-export-dialog';
import { nativePlanText } from '../../lib/harness/native-plan-text';
const roots: string[] = [];
afterEach(async () => { await Promise.all(roots.splice(0).map(root => rm(root, { recursive: true, force: true }))); });
it('projects native markdown without mutating source evidence; retains legacy shapes', () => {
  const revision = { sourceEvent: { plan: { id: 'original', type: 'plan', text: '# Plan\n\n1. Scope' } } };
  const before = JSON.stringify(revision);
  expect(nativePlanText(revision)).toBe('# Plan\n\n1. Scope');
  expect(JSON.stringify(revision)).toBe(before);
  expect(nativePlanText({ sourceEvent: { plan: 'legacy' } })).toBe('legacy');
  expect(nativePlanText({ sourceEvent: { plan: { steps: ['one'] } } })).toContain('steps');
});
it('chooses contained targets, cancels without a target, and denies external or symlink paths', async () => {
  const root = await realpath(await mkdtemp(path.join(tmpdir(), 'plan-dialog-'))); roots.push(root);
  const showSaveDialog = vi.fn().mockResolvedValue({ canceled: true });
  const showMessageBox = vi.fn().mockResolvedValue({ response: 0 });
  const handler = createPlanExportDialogHandler({ authorized: () => true, showSaveDialog, showMessageBox });
  const event = {} as Parameters<typeof handler>[0];
  const request = { projectRoot: root, revision: 2, operation: 'choose' };
  expect(await handler(event, request)).toEqual({ cancelled: true });
  showSaveDialog.mockResolvedValue({ canceled: false, filePath: path.join(root, 'plan.md') });
  expect(await handler(event, request)).toEqual({ cancelled: false, targetRelativePath: 'plan.md' });
  showSaveDialog.mockResolvedValue({ canceled: false, filePath: path.join(root, '..', 'outside.md') });
  expect(await handler(event, request)).toMatchObject({ cancelled: true, error: expect.any(String) });
  await symlink(tmpdir(), path.join(root, 'escape'));
  showSaveDialog.mockResolvedValue({ canceled: false, filePath: path.join(root, 'escape', 'plan.md') });
  expect(await handler(event, request)).toMatchObject({ cancelled: true, error: expect.stringContaining('symbolic') });
  const denied = createPlanExportDialogHandler({ authorized: () => false, showSaveDialog, showMessageBox });
  showSaveDialog.mockClear(); await denied(event, request); expect(showSaveDialog).not.toHaveBeenCalled();
  await writeFile(path.join(root, 'existing.md'), 'original');
  const conflict = { projectRoot: root, operation: 'confirm-overwrite', targetRelativePath: 'existing.md' };
  expect(await handler(event, conflict)).toBe(false);
  showMessageBox.mockResolvedValue({ response: 1 });
  expect(await handler(event, conflict)).toBe(true);
  expect(await handler(event, { ...conflict, targetRelativePath: '../outside.md' })).toBe(false);
});
