#!/bin/zsh
# I67 U7 slice F part 2: collect records into NUM/R/I67/u7_slice_f_01/_run_records (placeholder paths only).
set -eu
T3=WT; REPO=REPO_ROOT; S=$T3/scratch/i67_u6d
NUM=$T3/numerics/projects/chirality-piping/execution/_Coordination/AgentRuns/HELP-HUMAN-PIPING-20260918-UI-IMPLEMENTATION/instances/CONTINUATION_2026-09-24/NUMERICAL_INTEGRITY_T3/RESUME_2026-09-30
R=$NUM/I67/u7_slice_f_01; O=$R/_run_records; mkdir -p $O/oracle $O/suites $O/mutants
san() { sed -e "s|$T3|WT|g" -e "s|$REPO|REPO_ROOT|g" -e "s|SYSTEM_TMP \"']*|SYSTEM_TMP|g" "$@"; }
export GIT_OPTIONAL_LOCKS=0
W=$T3/f2a-u7
cd $W
git rev-parse HEAD > $O/basis.txt
git diff -- projects/chirality-piping | san > $O/candidate_parts_1_and_2.diff
shasum -a 256 $(git diff --name-only -- projects/chirality-piping) | san > $O/changed_files_sha256.txt
git status --short --untracked-files=all -- projects/chirality-piping 2>/dev/null | san > $O/worktree_status.txt || true
# Part 2 alone: I66's part-1 bytes (lane part1 = 12a849a7bd + I66's 12 files, sha256 in r6/part1_sha256.txt) against the final bytes.
{ echo "# I66 part-1 files checked against their part-1 sha256 (r6/part1_sha256.txt):"; shasum -a 256 -c $S/r6/part1_sha256.txt 2>&1 || true; } | san > $O/part1_files_check.txt
: > $O/part2.diff
for f in $(cat $S/tmp/cand_files.txt); do diff -u --label "part1/$f" --label "final/$f" $S/lanes/part1/$f $W/$f >> $O/part2.diff || true; done
san -i '' $O/part2.diff 2>/dev/null || true
grep '^+++ final/' $O/part2.diff | sed 's|^+++ final/||' > $S/tmp/part2_files.txt
shasum -a 256 $(cat $S/tmp/part2_files.txt) | san > $O/part2_files_sha256.txt
# suites
for run in r6/base r6/part1 r7/final; do d=$S/$run; [ -d $d ] || continue; t=${run//\//_}
  san $d/exit.txt > $O/suites/${t}_exit.txt; san $d/node_version.txt > $O/suites/${t}_versions.txt; san $d/tsc.out > $O/suites/${t}_tsc.out
  python3 -c "
import json
d=json.load(open('$d/vitest.json'))
rows=sorted((f['name'].split('/src/',1)[1], a['fullName'], a['status']) for f in d['testResults'] for a in f['assertionResults'])
print(json.dumps({k:d[k] for k in d if k.startswith('num') or k=='success'}))
for r in rows: print('\t'.join(r))
" | san > $O/suites/${t}_outcomes.tsv; done
san $S/records/compare_renamed.py > $O/suites/compare_renamed.py
python3 $S/records/compare_renamed.py $S/r6/base/vitest.json $S/r7/final/vitest.json | san > $O/suites/compare_base_vs_final.txt
python3 $S/records/compare_renamed.py $S/r6/part1/vitest.json $S/r7/final/vitest.json | san > $O/suites/compare_part1_vs_final.txt
for f in run_suite.sh r6_base.sh r7_final.sh collect_f.sh; do [ -f $S/$f ] && san $S/$f > $O/$f; done
for f in run_py.sh cargo_run.sh chain_py_rs.sh; do san $S/r7/$f > $O/suites/$f; done
grep -E "passed|failed|error" $S/r7/logs/py_retained.log | tail -3 | san > $O/suites/py_retained_summary.txt
grep -E "^(PASSED|FAILED|ERROR) " $S/r7/logs/py_retained.log | sort | san > $O/suites/py_retained_outcomes.txt
san $S/r7/logs/cand_re.outcomes > $O/suites/result_export_final.outcomes
I66R=$NUM/I66/u7_slice_f_01/_run_records/suites
{ echo "result_export, I67 final (one-line scope extension in tests/retained_precision_carriers.rs) vs I66's cand_re_final.outcomes:"; diff $I66R/cand_re_final.outcomes $S/r7/logs/cand_re.outcomes && echo "identical outcomes"; echo "counts: $(grep -c ' ok$' $S/r7/logs/cand_re.outcomes) ok, $(grep -c 'FAILED$' $S/r7/logs/cand_re.outcomes) failed, $(grep -c 'ignored$' $S/r7/logs/cand_re.outcomes) ignored"; } | san > $O/suites/result_export_compare.txt || true
# oracle
for f in zzI67U7fOracle.test.ts compare_ts_oracle.py run_dump.sh ts_oracle_diff.txt ts_base.json ts_cand.json ts_base.json.log ts_cand.json.log; do san $S/oracle7/$f > $O/oracle/$f; done
shasum -a 256 $S/oracle7/inputs.json | san > $O/oracle/inputs_sha256.txt
echo "inputs.json not copied (50 MB): regenerated by I66's gen_inputs.py from the candidate lane; sha256 equals I66's inputs_sha256.txt" >> $O/oracle/inputs_sha256.txt
# mutants
for f in mutants_f.py mutants_f.json mutants_f.log pyrs_mutants.py pyrs_mutants.json pyrs_mutants.log; do [ -f $S/mut/$f ] && san $S/mut/$f > $O/mutants/$f; done
{ echo "mutant lane WT/scratch/i67_u6d/lanes/mut6 vs the worktree (changed files):"; for f in $(cat $S/tmp/cand_files.txt); do cmp -s $S/lanes/mut6/$f $W/$f && echo "same $f" || echo "DIFF $f"; done; } > $O/mutants/lane_mut6_vs_worktree.txt
{ echo "Python/Rust mutant lane WT/scratch/i67_u6d/lanes/pyrsmut vs the worktree (non-app changed files):"; for f in $(grep -v apps/ $S/tmp/cand_files.txt); do cmp -s $S/lanes/pyrsmut/$f $W/$f && echo "same $f" || echo "DIFF $f"; done; } > $O/mutants/lane_pyrsmut_vs_worktree.txt
# runtime
{ echo "worktree: WT/f2a-u7 at $(cat $O/basis.txt | cut -c1-10) (codex/piping-f2a-u7-20261004), uncommitted parts 1 and 2"
  echo "node_modules: the existing untracked symlink WT/f2a-u7/projects/chirality-piping/node_modules (lanes link the same target); no install"
  echo "WASM: no build. The worktree's ignored public/{wasm-engine,self-weight-engine} prebuilt files were already present; lanes carry byte copies (hashes below)"
  (cd $W/projects/chirality-piping/apps/desktop && shasum -a 256 public/wasm-engine/* public/self-weight-engine/*)
  for L in base6 part1 cand7 mut6; do (cd $S/lanes/$L/projects/chirality-piping/apps/desktop && shasum -a 256 public/wasm-engine/* public/self-weight-engine/* | sed "s|^|$L: |"); done
  echo "lanes: base6 = git archive 12a849a7bd; part1 = base6 + I66's 12 part-1 files; cand7 = part1 + the final changed files (= the worktree's 18); mut6 = cand7 (TS mutants); pyrsmut = cand7 without apps/ (Python/Rust scope mutants)"
  echo "TMPDIR=WT/scratch/i67_u6d/tmp; cargo target dirs WT/targets/i67-u7f/{re-cand,re-mut}"
  cat $S/r7/final/node_version.txt; } | san > $O/runtime.txt
grep -rlE "/Us[e]rs/|/priv[a]te/" $O && { echo LEAK; exit 1; } || echo collected
