//! K2a: checked formation (T3 D1 revision 5a.2 section 4.7, formation range,
//! step 1; the K2a row of section 6; mutation 18 of section 7.3).
//!
//! `local_stiffness` forms every coefficient with the same binary64
//! operations as before, and checks every intermediate product and quotient.
//! A zero, subnormal or non-finite intermediate of nonzero finite operands is
//! `FrameKernelError::NumericalRange { name }`, naming the coefficient and the
//! intermediate. Every behavioural assertion on a refusal first shows the
//! silent or loud path on the unchecked formation (today's formula, computed
//! here operation for operation), so the paths are known to differ.
//!
//! Invented inputs only. The RF-RANGE members are R1's frozen references
//! (`tests/k2a/rf_range_models.rs`, generated by the run record
//! `k2a_models.py`); the section is formed as PP `derive_pipe_section` forms
//! it. The K-D5 interaction uses V1's F122 and F345 models as K-D5's adapter
//! tests carry them (`nonlinear_integration/src/structural_adapter/kd5_models.rs`).
use open_pipe_stress_frame_kernel::structural::{
    solve_formation_checked_structural_dense, transform_roundoff, FormationCheckReason,
    FormationSource, SolveQuality, StructuralSystem, SymmetryEvidence,
};
use open_pipe_stress_frame_kernel::{
    assemble_global_stiffness, element_dof_map, local_stiffness, transform_global_stiffness,
    FrameElement, FrameKernelError, FrameNode, FrameProperties, FrameSection, Matrix12,
    DOF_PER_NODE, ELEMENT_DOF, RX, RY, RZ, UX, UY, UZ,
};
use std::f64::consts::PI;

#[path = "k2a/rf_range_models.rs"]
mod models;
use models::*;

// ---------------------------------------------------------------- helpers

/// Today's coefficients, operation for operation (FK `local_stiffness` at
/// 5ae22926e): axial, torsion, then 12, 6, 4, 2 for y, then for z.
fn unchecked_coefficients(p: &FrameProperties) -> [f64; 10] {
    let s = p.section;
    let (e, g, area, iy, iz, j) = (
        s.elastic_modulus,
        s.shear_modulus,
        s.area,
        s.second_moment_y,
        s.second_moment_z,
        s.torsion_constant,
    );
    let length = p.length;
    let length2 = length * length;
    let length3 = length2 * length;
    [
        e * area / length,
        g * j / length,
        12.0 * e * iy / length3,
        6.0 * e * iy / length2,
        4.0 * e * iy / length,
        2.0 * e * iy / length,
        12.0 * e * iz / length3,
        6.0 * e * iz / length2,
        4.0 * e * iz / length,
        2.0 * e * iz / length,
    ]
}
const AXIAL: usize = 0;
const TORSION: usize = 1;
const BY12: usize = 2;
const BY6: usize = 3;
const BY4: usize = 4;
const BY2: usize = 5;
const BZ12: usize = 6;

/// Today's matrix layout (FK `local_stiffness`, `set_symmetric`,
/// `add_bending_z`, `add_bending_y` and `add_terms` at 5ae22926e), without
/// the final finiteness check, from the unchecked coefficients.
fn unchecked_local(p: &FrameProperties) -> Matrix12 {
    let c = unchecked_coefficients(p);
    let mut k = [[0.0; ELEMENT_DOF]; ELEMENT_DOF];
    let sym = |k: &mut Matrix12, r: usize, col: usize, v: f64| {
        k[r][col] = v;
        k[col][r] = v;
    };
    sym(&mut k, UX, UX + DOF_PER_NODE, -c[AXIAL]);
    k[UX][UX] = c[AXIAL];
    k[UX + DOF_PER_NODE][UX + DOF_PER_NODE] = c[AXIAL];
    sym(&mut k, RX, RX + DOF_PER_NODE, -c[TORSION]);
    k[RX][RX] = c[TORSION];
    k[RX + DOF_PER_NODE][RX + DOF_PER_NODE] = c[TORSION];
    let add = |k: &mut Matrix12, idx: [usize; 4], t: [[f64; 4]; 4]| {
        for r in 0..4 {
            for col in 0..4 {
                k[idx[r]][idx[col]] += t[r][col];
            }
        }
    };
    let (z12, z6, z4, z2) = (c[6], c[7], c[8], c[9]);
    add(
        &mut k,
        [UY, RZ, UY + DOF_PER_NODE, RZ + DOF_PER_NODE],
        [
            [z12, z6, -z12, z6],
            [z6, z4, -z6, z2],
            [-z12, -z6, z12, -z6],
            [z6, z2, -z6, z4],
        ],
    );
    let (y12, y6, y4, y2) = (c[2], c[3], c[4], c[5]);
    add(
        &mut k,
        [UZ, RY, UZ + DOF_PER_NODE, RY + DOF_PER_NODE],
        [
            [y12, -y6, -y12, -y6],
            [-y6, y4, y6, y2],
            [-y12, y6, y12, y6],
            [-y6, y2, y6, y4],
        ],
    );
    k
}

fn bits(k: &Matrix12) -> Vec<u64> {
    k.iter().flatten().map(|v| v.to_bits()).collect()
}

/// The section as PP `derive_pipe_section` forms it
/// (`core/product_physics/src/lib.rs:8471-8475` at 5ae22926e).
fn product_section(e: f64, g: f64, od: f64, t: f64) -> FrameSection {
    let id = od - 2.0 * t;
    let area = PI * (od.powi(2) - id.powi(2)) / 4.0;
    let second_moment = PI * (od.powi(4) - id.powi(4)) / 64.0;
    FrameSection::new(
        e,
        g,
        area,
        second_moment,
        second_moment,
        2.0 * second_moment,
    )
    .unwrap()
}

fn member_properties(m: &RangeMember) -> FrameProperties {
    let section = product_section(
        f64::from_bits(m.e),
        f64::from_bits(m.g),
        f64::from_bits(m.od),
        f64::from_bits(m.t),
    );
    FrameProperties::new(section, f64::from_bits(m.length)).unwrap()
}

fn operands(o: &Operands) -> FrameProperties {
    let v = o.map(f64::from_bits);
    FrameProperties::new(
        FrameSection::new(v[0], v[1], v[2], v[3], v[4], v[5]).unwrap(),
        v[6],
    )
    .unwrap()
}

/// A member along global x from the origin, y reference along global y.
fn x_member(p: &FrameProperties) -> Result<FrameElement, FrameKernelError> {
    FrameElement::new(
        FrameNode::new(0, [0.0, 0.0, 0.0]).unwrap(),
        FrameNode::new(1, [p.length, 0.0, 0.0]).unwrap(),
        p.section,
        [0.0, 1.0, 0.0],
    )
}

fn range(name: &'static str) -> Result<Matrix12, FrameKernelError> {
    Err(FrameKernelError::NumericalRange { name })
}

/// 12EIy/L^3 formed with E scaled by 2^s (exact, all operands normal), then
/// scaled back (exact: the result is normal): the reference for the relative
/// error of the unchecked coefficient, accurate to a few ulps.
fn scaled_bend_y(p: &FrameProperties, k: f64, denominator_power: i32, s: i32) -> f64 {
    let sec = p.section;
    let e_scaled = sec.elastic_modulus * 2f64.powi(s);
    assert!(e_scaled.is_normal());
    let intermediate = k * e_scaled * sec.second_moment_y;
    assert!(intermediate.is_normal());
    let value = intermediate / p.length.powi(denominator_power) * 2f64.powi(-s);
    assert!(value.is_normal());
    value
}

fn relative_error(value: f64, reference: f64) -> f64 {
    ((value - reference) / reference).abs()
}

const BASES: [(&str, usize); 3] = [("CHAIN", 5), ("SKEW", 1), ("CONT", 10)];

fn members_of(case: &str) -> Vec<&'static RangeMember> {
    RF_RANGE_MEMBERS.iter().filter(|m| m.case == case).collect()
}

// ------------------------------------------------------------------ tests

#[test]
fn k2a_rf_range_lef_small_is_silent_unchecked_and_refused_by_name_on_all_three_bases() {
    for (base, count) in BASES {
        let case = format!("RF-RANGE-{base}-LEF-small");
        let members = members_of(&case);
        assert_eq!(members.len(), count, "{case}");
        for m in members {
            let p = member_properties(m);
            let s = p.section;
            // The silent path (paths-differ precondition): on the unchecked
            // formation GJ/L, 6EI/L^2, 4EI/L and 2EI/L are exactly 0 ...
            let c = unchecked_coefficients(&p);
            for (label, idx) in [("GJ/L", 1), ("6EIy/L^2", 3), ("4EIy/L", 4), ("2EIy/L", 5)] {
                assert_eq!(c[idx], 0.0, "{case} {}: {label}", m.member);
            }
            assert_eq!(&c[7..], &[0.0, 0.0, 0.0], "{case} {}: z", m.member);
            // ... while 12EI/L^3 is a normal value 3.5 % wrong, from a
            // least-subnormal intermediate (V1's FORM-C).
            assert_eq!(12.0 * s.elastic_modulus * s.second_moment_y, 5e-324);
            assert!(c[BY12].is_normal() && c[BZ12].is_normal() && c[AXIAL].is_normal());
            let error = relative_error(c[BY12], scaled_bend_y(&p, 12.0, 3, 600));
            assert!(
                error > 0.035 && error < 0.0355,
                "{case} {}: 12EI/L^3 relative error {error}",
                m.member
            );
            // Checked formation refuses it with the named reason.
            assert_eq!(
                local_stiffness(p),
                range("GJ/L: G*J"),
                "{case} {}",
                m.member
            );
            assert_eq!(m.refusal, Some("GJ/L: G*J"));
            // Through an element, the product's route, the member is refused
            // earlier and unchanged: its length is below the axis tolerance
            // (P1: PIPE_ELEMENT_INPUT_INVALID, degenerate element length).
            assert_eq!(
                x_member(&p),
                Err(FrameKernelError::DegenerateAxis {
                    detail: "element length"
                })
            );
        }
    }
}

#[test]
fn k2a_rf_range_lef_large_overflow_is_refused_by_name_on_all_three_bases() {
    for (base, count) in BASES {
        let case = format!("RF-RANGE-{base}-LEF-large");
        let members = members_of(&case);
        assert_eq!(members.len(), count, "{case}");
        for m in members {
            let p = member_properties(m);
            // Today: G*J and E*I overflow, the coefficients are infinite, and
            // the final finiteness check blocks the element as a non-finite
            // "computed local stiffness" (loud, not silent).
            let c = unchecked_coefficients(&p);
            assert!(c[AXIAL].is_normal(), "{case} {}", m.member);
            assert!(c[TORSION].is_infinite() && c[1..].iter().all(|v| v.is_infinite()));
            let first_non_finite = unchecked_local(&p)
                .iter()
                .flatten()
                .copied()
                .find(|v| !v.is_finite());
            assert!(first_non_finite.is_some());
            // Checked formation refuses it with the named reason instead.
            assert_eq!(
                local_stiffness(p),
                range("GJ/L: G*J"),
                "{case} {}",
                m.member
            );
            assert_eq!(m.refusal, Some("GJ/L: G*J"));
            // The same refusal through an element and through assembly.
            let element = x_member(&p).expect("a long member forms its element");
            assert_eq!(element.global_stiffness(), range("GJ/L: G*J"));
            assert_eq!(
                assemble_global_stiffness(2, &[element]),
                Err(FrameKernelError::NumericalRange { name: "GJ/L: G*J" })
            );
        }
    }
}

#[test]
fn k2a_every_other_rf_range_vector_keeps_every_coefficient_normal_and_byte_identical() {
    let mut refused = std::collections::BTreeSet::new();
    let mut identical = 0;
    for m in RF_RANGE_MEMBERS {
        let p = member_properties(m);
        let checked = local_stiffness(p);
        match m.refusal {
            Some(name) => {
                assert_eq!(checked, range(name), "{} {}", m.case, m.member);
                refused.insert(m.case);
            }
            None => {
                let c = unchecked_coefficients(&p);
                assert!(c.iter().all(|v| v.is_normal()), "{} {}", m.case, m.member);
                let k = checked.unwrap_or_else(|e| panic!("{} {}: {e}", m.case, m.member));
                assert_eq!(
                    bits(&k),
                    bits(&unchecked_local(&p)),
                    "{} {}",
                    m.case,
                    m.member
                );
                identical += 1;
            }
        }
    }
    let expected: std::collections::BTreeSet<&str> = [
        "RF-RANGE-CHAIN-LEF-small",
        "RF-RANGE-CHAIN-LEF-large",
        "RF-RANGE-SKEW-LEF-small",
        "RF-RANGE-SKEW-LEF-large",
        "RF-RANGE-CONT-LEF-small",
        "RF-RANGE-CONT-LEF-large",
    ]
    .into_iter()
    .collect();
    assert_eq!(refused, expected);
    // 32 cases: 6 refused (32 members), 26 unaffected (130 members), among
    // them (0, -1000, 0) and +-(-120, 500, 260) on every base, and THIN-A/B.
    assert_eq!(identical, 130);
    for base in ["CHAIN", "SKEW", "CONT"] {
        for v in ["E-1000", "SIM-a", "SIM-b"] {
            let case = format!("RF-RANGE-{base}-{v}");
            assert!(!members_of(&case).is_empty());
            assert!(
                members_of(&case).iter().all(|m| m.refusal.is_none()),
                "{case}"
            );
        }
    }
}

#[test]
fn k2a_partial_underflow_control_is_refused() {
    // Invented: E = 2^-600 Pa, G = 2^-601 Pa, A = 1 m^2, Iy = 2^-477 m^4,
    // Iz = J = 1 m^4, L = 2^-30 m. Axial, torsion and z bending are normal.
    let p = operands(&PARTIAL_UNDERFLOW);
    let c = unchecked_coefficients(&p);
    // Unchecked: 12EIy/L^3 is normal but a third wrong, while 4EIy/L and
    // 2EIy/L underflow to exactly 0 (the element's relations change).
    assert!(c[BY12].is_normal());
    assert_eq!((c[BY4], c[BY2]), (0.0, 0.0));
    let error = relative_error(c[BY12], scaled_bend_y(&p, 12.0, 3, 200));
    assert!(
        error > 0.33 && error < 0.34,
        "12EIy/L^3 relative error {error}"
    );
    assert!([AXIAL, TORSION, 6, 7, 8, 9]
        .iter()
        .all(|&i| c[i].is_normal()));
    // Checked: refused, naming the first refused intermediate, which is the
    // one feeding the normal-looking 12EIy/L^3 (not a final coefficient).
    let name = "12EIy/L^3: (12*E)*Iy";
    assert_eq!(local_stiffness(p), range(name));
    let element = x_member(&p).expect("L = 2^-30 m is above the axis tolerance");
    assert_eq!(element.global_stiffness(), range(name));
    assert_eq!(
        assemble_global_stiffness(2, &[element]),
        Err(FrameKernelError::NumericalRange { name })
    );
}

#[test]
fn k2a_subnormal_intermediate_control_is_refused_although_every_coefficient_is_normal() {
    // Invented: E = 2^-600 Pa, G = 2^-601 Pa, A = 1 m^2, Iy = 0.1 * 2^-445 m^4
    // (binary64), Iz = J = 1 m^4, L = 2^-30 m.
    let p = operands(&SUBNORMAL_INTERMEDIATE);
    let s = p.section;
    let c = unchecked_coefficients(&p);
    // Unchecked: every final coefficient is normal, so a final-coefficient
    // check sees nothing, but each (k*E)*Iy is subnormal and rounded ...
    assert!(c.iter().all(|v| v.is_normal()));
    for k in [12.0, 6.0, 4.0, 2.0] {
        let intermediate = k * s.elastic_modulus * s.second_moment_y;
        assert!(intermediate > 0.0 && !intermediate.is_normal(), "{k}");
    }
    // ... and 2EIy/L is wrong by more than the 1e-9 criterion.
    let error = relative_error(c[BY2], scaled_bend_y(&p, 2.0, 1, 200));
    assert!(error > 1e-9, "2EIy/L relative error {error}");
    assert!(relative_error(c[BY6], scaled_bend_y(&p, 6.0, 2, 200)) > 0.0);
    // Checked: refused.
    assert_eq!(local_stiffness(p), range("12EIy/L^3: (12*E)*Iy"));
    let element = x_member(&p).unwrap();
    assert_eq!(element.global_stiffness(), range("12EIy/L^3: (12*E)*Iy"));
}

#[test]
fn k2a_each_checked_intermediate_is_refused_by_its_own_name() {
    // One invented operand set per checked product and quotient, each making
    // that intermediate the first refused (generated and verified by
    // `k2a_models.py`). Dropping any one check changes that row's outcome.
    assert_eq!(FORMATION_SITES.len(), 26);
    let names: std::collections::BTreeSet<&str> = FORMATION_SITES.iter().map(|s| s.0).collect();
    assert_eq!(names.len(), 26);
    for (name, o) in FORMATION_SITES {
        let p = operands(o);
        // Precondition (paths differ): unchecked, this row forms at least one
        // zero, subnormal or infinite coefficient.
        let c = unchecked_coefficients(&p);
        assert!(c.iter().any(|v| !v.is_normal()), "{name}");
        assert_eq!(local_stiffness(p), range(name), "{name}");
    }
}

#[test]
fn k2a_zero_operand_keeps_its_existing_refusal() {
    // An exactly zero operand is not a range error: today's input check
    // refuses it first, unchanged.
    let good = FrameSection::new(1.0, 1.0, 1.0, 1.0, 1.0, 1.0).unwrap();
    let cases: [(&'static str, fn(&mut FrameSection)); 6] = [
        ("elastic_modulus", |s| s.elastic_modulus = 0.0),
        ("shear_modulus", |s| s.shear_modulus = 0.0),
        ("area", |s| s.area = 0.0),
        ("second_moment_y", |s| s.second_moment_y = 0.0),
        ("second_moment_z", |s| s.second_moment_z = 0.0),
        ("torsion_constant", |s| s.torsion_constant = 0.0),
    ];
    for (name, zero) in cases {
        let mut section = good;
        zero(&mut section);
        assert_eq!(
            local_stiffness(FrameProperties {
                section,
                length: 1.0
            }),
            Err(FrameKernelError::NonPositiveInput { name, value: 0.0 })
        );
    }
    assert_eq!(
        local_stiffness(FrameProperties {
            section: good,
            length: 0.0
        }),
        Err(FrameKernelError::NonPositiveInput {
            name: "length",
            value: 0.0
        })
    );
}

#[test]
fn k2a_normal_formations_are_bit_identical_to_the_unchecked_formation() {
    // A deterministic sweep of invented pipe sections and lengths, formed as
    // the product forms them, plus the extremes of the normal window that
    // stay normal in every intermediate.
    let mut compared = 0;
    for &od in &[0.0213, 0.0603, 0.1143, 0.2191, 0.3239, 0.6096, 1.2192] {
        for &fraction in &[0.02, 0.05, 0.1, 0.25, 0.45] {
            for &e in &[69.0e9, 193.0e9, 200.0e9, 210.0e9, 1.0, 1.0e-3] {
                for &length in &[1.0e-3, 0.05, 0.5, 1.0, 3.7, 12.0, 100.0, 1.0e4] {
                    let section = product_section(e, e / 2.6, od, fraction * od);
                    let p = FrameProperties::new(section, length).unwrap();
                    assert!(unchecked_coefficients(&p).iter().all(|v| v.is_normal()));
                    let k = local_stiffness(p).unwrap();
                    assert_eq!(
                        bits(&k),
                        bits(&unchecked_local(&p)),
                        "{od} {fraction} {e} {length}"
                    );
                    compared += 1;
                }
            }
        }
    }
    for (e, i, length) in [
        (1.0e-150, 1.0e-150, 1.0),
        (1.0e150, 1.0e150, 1.0),
        (2.0e11, 1.0, 1.0e-90),
    ] {
        let section = FrameSection::new(e, e, 1.0, i, i, i).unwrap();
        let p = FrameProperties::new(section, length).unwrap();
        let k = local_stiffness(p).unwrap();
        assert_eq!(bits(&k), bits(&unchecked_local(&p)), "{e} {i} {length}");
        compared += 1;
    }
    assert_eq!(compared, 7 * 5 * 6 * 8 + 3);
}

// ------------------------------------------------------ K-D5 interaction

struct Kd5Model {
    name: &'static str,
    node_j: [f64; 3],
    y_reference: [f64; 3],
    springs: [(usize, f64); 3],
    loads: &'static [(usize, f64)],
}

/// V1's F122 (K-D5's required true positive) and F345 (its control), as
/// K-D5's adapter tests carry them: one member from the origin, E = 200e9 Pa,
/// G = 80e9 Pa, the 0.2/0.18 m pipe section, rigid translations at node 0 and
/// rotational springs there.
const KD5_MODELS: [Kd5Model; 2] = [
    Kd5Model {
        name: "F122",
        node_j: [1.0, 2.0, 2.0],
        y_reference: [1.0, 0.0, 0.0],
        springs: [(3, 144.0), (4, 1000000.0), (5, 1000000.0)],
        loads: &[(9, 0.0048), (10, 0.0096), (11, 0.0096)],
    },
    Kd5Model {
        name: "F345",
        node_j: [3.0, 4.0, 0.0],
        y_reference: [0.0, 0.0, 1.0],
        springs: [(3, 86.4), (4, 1000000.0), (5, 1000000.0)],
        loads: &[(9, 0.005184), (10, 0.006912)],
    },
];

fn kd5_section() -> FrameSection {
    FrameSection::new(
        200000000000.0,
        80000000000.0,
        0.005969026041820614,
        2.700984283923829e-05,
        2.700984283923829e-05,
        5.401968567847658e-05,
    )
    .unwrap()
}

/// The global stiffness of a model from a given element matrix, springs
/// added after the element, as K-D5's adapter tests assemble it.
fn kd5_stiffness(model: &Kd5Model, element_matrix: &Matrix12) -> Vec<Vec<f64>> {
    let mut k = vec![vec![0.0; 12]; 12];
    let map = element_dof_map(0, 1);
    for r in 0..12 {
        for c in 0..12 {
            k[map[r]][map[c]] += element_matrix[r][c];
        }
    }
    for &(dof, value) in &model.springs {
        k[dof][dof] += value;
    }
    k
}

#[test]
fn k2a_kd5_formation_check_outcome_is_unchanged_for_normal_formations() {
    let mut demoted = Vec::new();
    for model in &KD5_MODELS {
        let element = FrameElement::new(
            FrameNode::new(0, [0.0, 0.0, 0.0]).unwrap(),
            FrameNode::new(1, model.node_j).unwrap(),
            kd5_section(),
            model.y_reference,
        )
        .unwrap();
        // The checked element matrix is the unchecked one, bit for bit.
        let checked = element.global_stiffness().unwrap();
        let unchecked = transform_global_stiffness(
            &unchecked_local(&element.properties().unwrap()),
            &element.orientation().unwrap(),
        );
        assert_eq!(bits(&checked), bits(&unchecked), "{}", model.name);
        let mut f = vec![0.0; 12];
        for &(dof, value) in model.loads {
            f[dof] = value;
        }
        let free: Vec<usize> = (3..12).collect();
        let prescribed = [(0, 0.0), (1, 0.0), (2, 0.0)];
        let source = FormationSource {
            node_count: 2,
            frames: vec![element],
            springs: model.springs.to_vec(),
            ..FormationSource::default()
        };
        // The transform's symmetry evidence, as K-D5's adapter records it
        // (one element on DOFs 0..12, so the element evidence is global).
        let roundoff = transform_roundoff(
            &element.local_stiffness().unwrap(),
            &element.orientation().unwrap().transformation_matrix(),
        )
        .unwrap();
        let absolute: Vec<Vec<f64>> = roundoff
            .absolute_roundoff
            .iter()
            .map(|r| r.to_vec())
            .collect();
        let counts: Vec<Vec<usize>> = roundoff
            .operation_counts
            .iter()
            .map(|r| r.to_vec())
            .collect();
        let solve = |k: &Vec<Vec<f64>>| {
            let system = StructuralSystem {
                stiffness: k,
                force: &f,
                free_dofs: &free,
                prescribed: &prescribed,
                contributions: None,
                symmetry: Some(SymmetryEvidence {
                    absolute_roundoff: &absolute,
                    operation_counts: &counts,
                    basis: roundoff.basis,
                }),
            };
            solve_formation_checked_structural_dense(&system.with_formation_source(&source))
                .unwrap()
        };
        let with_checked = solve(&kd5_stiffness(model, &checked));
        let with_unchecked = solve(&kd5_stiffness(model, &unchecked));
        // The K-D5 outcome with checked formation is the outcome before K2a.
        assert_eq!(
            format!("{with_checked:?}"),
            format!("{with_unchecked:?}"),
            "{}",
            model.name
        );
        assert_eq!(
            with_checked
                .displacements
                .iter()
                .map(|v| v.to_bits())
                .collect::<Vec<_>>(),
            with_unchecked
                .displacements
                .iter()
                .map(|v| v.to_bits())
                .collect::<Vec<_>>()
        );
        match &with_checked.formation_check {
            Some(check) => {
                assert_eq!(
                    check.reason,
                    FormationCheckReason::Estimate,
                    "{}",
                    model.name
                );
                assert_eq!(with_checked.report.quality, SolveQuality::Sensitive);
                demoted.push(model.name);
            }
            None => assert_eq!(with_checked.report.quality, SolveQuality::Passed),
        }
    }
    // Not vacuous: the required true positive demotes and its control does not.
    assert_eq!(demoted, vec!["F122"]);
}

#[test]
fn k2a_refused_formation_is_refused_before_the_formation_check_runs() {
    // Invented: E = 2^-600 Pa and Iy = 2^-500 m^4 on a 1 m member: the element
    // forms (its inputs are positive and finite), but its stiffness does not,
    // so no stiffness matrix, structural system or formation-checked system
    // exists for K-D5 to check. The refusal is the formation error itself.
    let p = operands(&[
        (2f64.powi(-600)).to_bits(),
        1f64.to_bits(),
        1f64.to_bits(),
        (2f64.powi(-500)).to_bits(),
        1f64.to_bits(),
        1f64.to_bits(),
        1f64.to_bits(),
    ]);
    // Paths differ: unchecked, 12EIy/L^3 and every y-bending coefficient is 0.
    assert!(unchecked_coefficients(&p)[BY12..=BY2]
        .iter()
        .all(|&v| v == 0.0));
    let refused = x_member(&p).expect("the element's inputs are valid");
    let name = "12EIy/L^3: (12*E)*Iy";
    assert_eq!(refused.global_stiffness(), range(name));
    let normal = FrameElement::new(
        FrameNode::new(1, [1.0, 0.0, 0.0]).unwrap(),
        FrameNode::new(2, [1.0, 2.0, 2.0]).unwrap(),
        kd5_section(),
        [1.0, 0.0, 0.0],
    )
    .unwrap();
    assert!(assemble_global_stiffness(3, &[normal]).is_ok());
    assert_eq!(
        assemble_global_stiffness(3, &[normal, refused]),
        Err(FrameKernelError::NumericalRange { name })
    );
}
