from pathlib import Path
import csv,json,hashlib,re,subprocess,collections
root=Path(subprocess.check_output(['git','rev-parse','--show-toplevel'],text=True).strip());base='2be412ccea62bdc4bd96deb082c46d7a792076ea'
run=Path('projects/pec/execution/_Reconciliation/DeliverableConcordance/PEC_REMAINING_CONCORDANCE_2026-09-05'); pkg=run/'R1_R4_2026-09-05/PACKAGES/PKG-03';out=pkg/'WORKERS/DEL-03-04';d=Path('projects/pec/execution/PKG-03_Reconciliation_Parity/1_Working/DEL-03-04_Practitioner_harness_parity_diff');sow=d/'ScopeOfWork.md';did='DEL-03-04'
paths=set(d.rglob('*'));paths={p for p in paths if p.is_file()}
paths.update(p for p in Path('projects/pec/v2').rglob('*') if p.is_file() and '__pycache__' not in str(p))
paths.update(map(Path,['AGENTS.md','projects/pec/AGENTS.md','agents/AGENT_RECONCILIATION.md','docs/DELIVERABLE_CONCORDANCE_METHOD.md','projects/pec/docs/PRD.md','projects/pec/execution/_Scripts/pec_reliance_hold.py','projects/pec/execution/_Coordination/ACTIVE_RELIANCE_HOLDS.csv','projects/pec/execution/_Coordination/_DECISIONS/_REGISTER.md','tools/practitioner_harness/README.md','tools/REGISTRY.md','projects/pec/execution/_Coordination/WAVE_D-PEC-63/BATCH_B5_FANIN.md','projects/pec/execution/_Coordination/PLAN_2026-07-25_project_setup_dag_gate.md','projects/pec/execution/_Coordination/PEC_CURRENCY_REPAIR_CLOSEOUT_2026-08-09/HANDOFF_STATE.md','projects/pec/execution/PKG-03_Reconciliation_Parity/1_Working/DEL-03-01_Full_rebuild_reconciler_one_command/ScopeOfWork.md','projects/pec/execution/PKG-03_Reconciliation_Parity/1_Working/DEL-03-01_Full_rebuild_reconciler_one_command/_STATUS.md']))
for name in ['_LATEST.md','SOFTWARE_DECOMP.md','ScopeLedger.csv','Deliverables.csv']:paths.add(Path('projects/pec/execution/_Decomposition')/name)
for glob in ['D-PEC-81*.md','D-PEC-82*.md','D-PEC-62*.md']:paths.update(Path('projects/pec/execution/_Coordination/_DECISIONS').glob(glob))
paths.update([run/'CONVENTIONS.md',pkg/'PACKAGE_BASIS.md',pkg/'SOURCE_MANIFEST.json',pkg/'validate_worker.py',pkg/'BRIEFS/DEL-03-04.md'])
for name in ['BRIEFS/PKG-03.md','BRIEF_CLARIFICATION_01.md','RUN_BASIS.md','SOURCE_MANIFEST.json','SCOPE_CENSUS.csv','AGENT0_GRAPH.md']:
 p=run/'R1_R4_2026-09-05/COMMON'/name
 if p.exists():paths.add(p)
contents={str(p):p.read_bytes() for p in sorted(paths)};hashes={p:hashlib.sha256(b).hexdigest() for p,b in contents.items()}
# Explicit current production inventory; absence is bounded evidence, never proof of universal nonimplementation.
production=[p for p in contents if p.startswith('projects/pec/v2/')]; hits=[p for p in production if re.search(rb'parity|DriftFinding',contents[p],re.I)]
cmd=['python3','projects/pec/execution/_Scripts/pec_reliance_hold.py','--register','projects/pec/execution/_Coordination/ACTIVE_RELIANCE_HOLDS.csv','--target',str(d/'ScopeOfWork.md').removeprefix('projects/pec/'),'--operation','candidate-validation'];a=subprocess.run(cmd,capture_output=True,text=True);assert a.returncode==0 and 'ALLOW' in a.stdout
text=contents[str(sow)].decode(); defs=list(re.finditer(r'^- \*\*((?:REQ|AC|VER|CLM|OUT|AX|TBD|CON)-\d{3})\*\* — (.*?)(?=\n- \*\*|\n##|\Z)',text,re.M|re.S));assert len(defs)==86
CH='ClaimID,DeliverableID,ClaimClass,NormativeSource,ScopeItemIDs,DeclaredSource,CurrentState,ImplementationEvidence,VerificationEvidence,ValidationOrProvenanceEvidence,LifecycleEvidence,ExistingRemaining,Disposition,ProposedResidualID,ProposedResidualText,Depends,ExactGate,AuthorityNeeded,Selectability,SourceCommit,SourceHashes,EvidenceReferences,Notes'.split(',');RH='ResidualID,DeliverableID,ClaimIDs,ProposedText,Depends,ExactGate,ClosureEvidence,AuthorityNeeded,Selectability,Notes'.split(',')
sel='NON_SELECTABLE_PENDING_OWNER_APPLICATION';gate='(gated: exact owner Remaining application; every implementation tranche requires its own owner-ruled packet under C14; F-PEC-1; current reliance-hold preflight; production Depends DEL-03-01 remains ACTIVE PREREQUISITE PENDING)'
texts={1:'Establish a source-bound evidence disposition for the accepted SOW-020 parity tool and its VER-001 through VER-015 verification obligations: identify any existing current implementation and exact comparison/test evidence; if unavailable, prepare a bounded owner-ruled production packet covering the accepted comparison, findings, source boundaries, limitations, declared equivalence and standing registration. Do not infer implementation absence from a search miss or transfer upstream harness tests as downstream parity proof.',2:'Route AC-016 to the accountable owner for confirmation or declination of whether this mechanism’s blocking verdict binds a release candidate or remains advisory; preserve the standing comparison either way and record the dated exact ruling.',3:'Route AC-017 to the accountable owner for the exact explanation/closure/non-direction confirmation and a statement of where finding closure is owed; preserve live-source resolution citations and the harness cache boundary without inventing a PEC explanation or closure act.'}
gates={1:gate,2:'(gated: exact owner Remaining application and accountable owner ruling under AC-016 / CON-001; C-08 release-gating force is unconfirmed)',3:'(gated: exact owner Remaining application and accountable owner ruling under AC-017 / CON-002 / CON-003 / CON-005; scope changes require the owning instrument)'}
rows=[]
for m in defs:
 lid=m[1];kind=lid.split('-')[0];statement=m[2].strip();behavior=kind in ['REQ','AC','VER','OUT'];human=lid in ['AC-016','AC-017'];rid=(2 if lid=='AC-016' else 3 if lid=='AC-017' else 1) if behavior else 0
 cls={'REQ':'PRODUCT_REQUIREMENT','AC':'OBSERVED_BEHAVIOR_ACCEPTANCE','VER':'FINITE_VERIFICATION_METHOD','OUT':'PRODUCT_OUTPUT','CLM':'DOCUMENTARY_ALIGNMENT','AX':'DOCUMENTARY_RATIONALE','TBD':'DOCUMENTARY_UNRESOLVED_CHOICE','CON':'DOCUMENTARY_OPEN_QUESTION'}[kind]
 if human:cls='HUMAN_ACCEPTANCE_RELEASE_AUTHORITY' if lid=='AC-016' else 'HUMAN_ACCEPTANCE_CLOSURE_BOUNDARY'
 if lid=='REQ-007':cls='STANDING_BEHAVIOR_REQUIREMENT'
 note='Local statement: '+statement
 if kind=='VER':note+=' Method is declared, not demonstrated executed; finite fixtures would not prove all-input or all-future-state guarantee.'
 if lid in ['CLM-016','AX-010']:note+=' OPEN/no-implementation is dated authoring context, not current state. Current status INITIALIZED; no stale-text repair or lifecycle reversal inferred.'
 if lid=='TBD-001':note+=' Truthful unassigned field agrees with current register; no invented product task or assignment mirror.'
 if lid in ['CLM-008','AX-003','CON-001']:note+=' Documentary alignment records the unresolved authority question; it does not accept release authority. See AC-016.'
 if lid in ['CLM-011','AX-006','AX-007']:note+=' Current dependency satisfaction remains PENDING, despite observable INITIALIZED predecessor; no register flip.'
 row=dict.fromkeys(CH,'');row.update(ClaimID=did+'::'+lid,DeliverableID=did,ClaimClass=cls,NormativeSource=str(sow)+'#'+lid+'; projects/pec/execution/_Decomposition/ScopeLedger.csv#SOW-020',ScopeItemIDs='SOW-020',DeclaredSource=str(sow)+'#'+lid,CurrentState='INITIALIZED; future contract; comparison evidence unestablished' if behavior else 'Documentary assertion assessed at its stated authority/date',ImplementationEvidence='Current v2 inventory contains config/ports, API contract and enforcement; no claim-specific parity implementation located. Search is bounded and does not establish absence.' if behavior else 'Not an implementation claim',VerificationEvidence=('No dated owner ruling satisfying this acceptance identified in declared current decision basis' if human else 'No claim-specific current parity execution evidence identified; historical SOW format PASS is documentary only') if behavior else 'Current registers, contract and cited provenance inspected; no product-test PASS claimed',ValidationOrProvenanceEvidence='BATCH_B5_FANIN accepted exact SOW hash '+hashes[str(sow)]+'; July25 revision record is contract validation only; D81 accepted conventions govern',LifecycleEvidence=str(d/'_STATUS.md')+'#Current State INITIALIZED; history OPEN then INITIALIZED 2026-07-25',ExistingRemaining='No Remaining section',Disposition='UNKNOWN' if behavior else 'ALIGNED',ProposedResidualID=f'{did}-REM-{rid:03}' if rid else '',ProposedResidualText=texts[rid] if rid else '',Depends='DEL-03-01' if rid==1 else 'NONE',ExactGate=gates[rid] if rid else '(gated: any later source or Remaining change requires exact owner authorization; documentary alignment grants no implementation or release authority)',AuthorityNeeded='Exact owner application and bounded C14 production packet' if rid==1 else 'Accountable owner ruling' if human else 'No new authority needed for read-only documentary assessment',Selectability=sel,SourceCommit=base,SourceHashes=json.dumps({str(sow):hashes[str(sow)],str(d/'_STATUS.md'):hashes[str(d/'_STATUS.md')],str(d/'Dependencies.csv'):hashes[str(d/'Dependencies.csv')]},sort_keys=True),EvidenceReferences='READ_MANIFEST.json; EVIDENCE.md; '+str(sow)+'#'+lid,Notes=note);rows.append(row)
for lid,disp,cls,note in [('CURRENT_STATE','ALIGNED','LIFECYCLE','INITIALIZED is authoritative. Dated OPEN in contract is historical authoring framing; no demotion, promotion, issue or release proposed.'),('REMAINING_COMPLETENESS','UNKNOWN','REMAINING_EVIDENCE','No Remaining section exists, but unresolved current parity and human acceptance evidence prevents warranted NONE.')]:
 row=rows[0].copy();row.update(ClaimID=did+'::'+lid,ClaimClass=cls,DeclaredSource=str(d/'_STATUS.md'),NormativeSource=str(d/'_STATUS.md')+'; docs/DELIVERABLE_CONCORDANCE_METHOD.md#6',CurrentState='INITIALIZED; Remaining section absent',ImplementationEvidence='Not an implementation claim',VerificationEvidence='Direct status read',Disposition=disp,ProposedResidualID=f'{did}-REM-001' if disp=='UNKNOWN' else '',ProposedResidualText=texts[1] if disp=='UNKNOWN' else '',Depends='DEL-03-01' if disp=='UNKNOWN' else 'NONE',Notes=note);rows.append(row)
res=[]
for n in texts:
 rid=f'{did}-REM-{n:03}';res.append(dict(zip(RH,[rid,did,';'.join(r['ClaimID'] for r in rows if r['ProposedResidualID']==rid),texts[n],'DEL-03-01' if n==1 else 'NONE',gates[n],'Current source/method-bound parity and test evidence for each linked claim, or owner-accepted bounded disposition of remaining unknowns; no permanent release closure' if n==1 else 'Dated accountable owner ruling addressing the exact linked AC and its retained boundaries','Exact owner application and C14 source packet' if n==1 else 'Accountable owner ruling',sel,'Evidence candidate; not proof of absent implementation' if n==1 else 'Held owner interpretation / acceptance routing; not automatic executable product work'])))
for name,header,data in [('CLAIMS.csv',CH,rows),('RESIDUALS.csv',RH,res)]:
 with (out/name).open('w',newline='') as f:w=csv.DictWriter(f,fieldnames=header,lineterminator='\n');w.writeheader();w.writerows(data)
manifest={'source_commit':base,'hashes':hashes,'historical_sources':[],'checks':[{'command':' '.join(cmd),'cwd':str(root),'environment':'read-only Python; no source tests or caches','exit_code':a.returncode,'result':a.stdout.strip()},{'command':'current v2 file inventory and content search parity|DriftFinding','cwd':str(root),'environment':'read-only bytes','exit_code':0,'result':{'files':len(production),'hits':hits,'limitation':'bounded search is not implementation absence proof'}}], 'source_unchanged':all(Path(p).read_bytes()==b for p,b in contents.items())};(out/'READ_MANIFEST.json').write_text(json.dumps(manifest,indent=2)+'\n')
counts=collections.Counter(r['Disposition'] for r in rows)
(out/'EVIDENCE.md').write_text('# DEL-03-04 evidence boundaries\n\nCurrent basis '+base+'. Exact B5 contract acceptance hash '+hashes[str(sow)]+'. Current v2 production file inventory: '+str(len(production))+' files; parity/DriftFinding hits '+str(hits)+'. Source inventory and scope read do not prove implementation absence, therefore behavior/output/test-execution rows are UNKNOWN. Root harness is an external peer and its own tests cannot establish this downstream comparison. Historical July25 format/checklist PASS is no parity test. No broad tests run.\n\nCurrent SOW-020 belongs here; SOW-093 belongs DEL-10-11. Snapshot drift SOW-019 belongs DEL-03-03; shared entity schema belongs DEL-01-01. C-08 arithmetic exclusion is accepted; release-gating authority remains AC-016. Explanation/closure remains AC-017. CON-004 shared comparison identity and CON-006 upstream generated-view/coverage ambiguities route through respective owners and are not invented schema or predecessor tasks.\n\nDEP-03-04-003 is ACTIVE PREREQUISITE PENDING, exact target DEL-03-01; required maturity INITIALIZED. No observed predecessor state silently updates it. Discovery was permitted independently. Current _CONTEXT/_REFERENCES already name revision1.4; August9 ordinary currency completion prevents reopening old provenance sweep. D79/PRDv2.3 nonapplication and TM022/023 limitations remain untouched.\n\nEvery current file read/hashed is in READ_MANIFEST; historical text within current committed run records remains dated provenance, not separately fetched historical source objects. Sealed brief/common/package artifacts created during D82 reporting are derivative instruction evidence; product/authority files bind to base.\n')
(out/'COVERAGE.md').write_text('# DEL-03-04 atomic coverage\n\nASSESSSED_UNKNOWN (canonical summary ASSESSED_UNKNOWN); warranted NONE prohibited.\n\n86 local definitions covered once: 2 OUT, 15 REQ, 17 AC, 15 VER, 16 CLM, 10 AX, 5 TBD, 6 CON. Two explicit status-derived claims add current lifecycle and Remaining completeness (88 total). Embedded upstream ID quotations are source context, not local definitions. All additional local IDs included; no material local IDs excluded. Each row retains its exact local statement in Notes. Counts: '+json.dumps(dict(counts))+'.\n\nDocumentary ALIGNED means declaration/provenance alignment only; TBD and CON rows truthfully report unsettled choice/question, never product completion. All finite method execution claims remain UNKNOWN; no invented PASS. Human AC016/017 and continuing behavior are separate classes. Three residual proposals: one bounded evidence/production-candidate routing and two held owner acceptance questions. No assignment mirror or metric obligation added.\n')
print(json.dumps({'claims':len(rows),'residuals':len(res),'counts':dict(counts),'hashes':len(hashes),'sow_hash':hashes[str(sow)]}))
