# Root selection — first static development comparisons

Under the owner's explicit resumed validation course and engineering-method delegation, ROOT selects the independently reviewed candidate package identified in ROOT_SELECTION_BASIS.json for two bounded **project-original development comparisons**: original_static_axial_v1 and original_static_bending_torsion_v1, each in sparse_interactive and dense_scrutiny. This selects the actual supplied inputs,73 scalar expectations/selectors and10 structural/summary obligations per case, with their independently checked per-case relative1e-9, prescribed exact-zero and dimension-scaled near-zero budgets. The protected historical stress/kernel/source-method criteria retain their own meanings and remain unchanged. These choices are not universal release thresholds or an adoption of the external reports' sample tolerances.

The source candidate files, including their historical scoring_readiness=false and review-pending metadata, remain immutable preparation evidence. The implementation manager may produce explicit execution bindings derived from them, changing only required admission/provenance/transport metadata while retaining byte/hash provenance to the checked quantities, criteria and selectors. Record the review and this selection truthfully as agent technical work under owner delegation; do not invent a personal human equation review. No numerical target may be filled from the application output or changed after seeing a run.

Execution requires the cleared new ordinary physics-1 adapter, actual closed CLI/mode/raw0.2 contract, pinned reviewed validator/dependency identity and a real build/source binding. Until those are supplied, no real comparison is represented as ready or passed. Preserve all292 scalar and40 structural obligations across the four proposed case-mode runs. Where an obligation needs a derived structural check rather than a direct row, implement and independently check that method; do not delete or replace its denominator. Missing/unsupported quantities remain explicit. The two cases do not establish complete Q1, complete piping stress, transverse-shear stress, signed circumferential output, physical validation, native/agent parity or release.

The entered geometry/material/load data are explicit invented fixtures: the E/nu constitutive variant derives G80GPa rather than silently inheriting a legacy shear modulus. The package's axial/bending/torsion signs, station fields, circular normal maximum and ties are its declared analytical scope. Missing direct stress outputs remain allocated to COR-PRESSURE/COR-RESULTS, including M14/M31. No material/component library or code-rule data is introduced.

Proceed with the finite adapter/binding integration and meaningful negative controls, then actual execution and independent result assessment when prerequisites are met. Routine continuation in this scope does not require another owner activation. Broader profiles and preserved licensing/human/native/release conditions remain separate.
