# Initial stable reader review return

**Not clear for integration yet:** CR-01, CR-02 and CR-03 require repair and an independent delta backcheck. See [findings](FINDINGS.md). The owner has accepted the findings and begun repair; this return is tied to the original frozen candidate, not moving working bytes.

I remained TASK under actual parent `/root/physics_resume`, using `software-code-review`, without delegation or product writes. ROOT's gate review was returned before this task began. The next ROOT-assigned gate-repair backcheck is a separate scope and directory.

Full frozen 24-path source/test/schema/table diff against base `22452ecd148e86486fe36a36e34a184c9a5a5943` was reviewed, including added files and relevant producer/caller context. Manifest `aa9c5693e40ce24fca8cb70871dfc3b4b3fbde2f4d78b0ef0f7335e959cc3abd`; patch `79cd1a2a658fec0ba0bc68ab837b5f3844a9dbbace26fbd0df8525af4a448295`. All 24 reconstructed frozen files match, as do the 16 read-only table/schema/input/raw bindings. Exact path hashes, probe identities, observed runtime records and working-byte drift are in [checked basis](CHECKED_BASIS.json).

Checked behavior includes closed composite/physical receipt joins, case hashes and independent original invocation/mode binding, source/ordinary case separation, maximum signature and SectionLocal operand relationships, support/norm/stress recipes and composed range/error guard boundaries, headless opaque proof and immutable raw result under rule revisions, solve-only closed CLI mode selection, and stress-neutral source/analysis/namespace/nine-member readback. The composite table has 78 signatures/57 kinds; the prior physics rows are retained, with explicit ordinary/source maximum basis discrimination. The three old table hashes and old source receipt schema are unchanged. Composite 8M/case and 64M/invocation do not extend the old source 4M or generic 2M policy, and no tolerance changes were found. Source metadata transport and public checks do not recreate producer custody or native Current standing.

Observed runtime evidence: `reader-03.log` has physics 10 + composite 5 + source 10 passing; headless binding 11 pass with 33 filtered; CLI 18 pass. Earlier Rust failures remain retained. The separately added connected test records one passing test covering eight real headless invocations, but its source is outside this original 24-path review and needs the owner's supplement. Schema run has 100 pass/10 resolver failures, not a current green schema claim. Earlier Python counts retain the drift/skip limitations in the brief. The reviewer ran only bounded Python transport/recipe probes and read/static/hash checks; no Cargo, npm, rustc, product/native execution or Git mutation.

Remaining: owner repair manifests and actual focused checks for CR-01/02/03; resolver/new connected-test supplement; moving TS/display/browser supplement; coherent final candidate qualification. No native, whole-product, WASM, final CI, merge, general numerical range, or engineering qualification follows from this return.
