from pathlib import Path
import csv,json,hashlib,re,subprocess
root=Path(subprocess.check_output(['git','rev-parse','--show-toplevel'],text=True).strip());p=root/'projects/pec';run=p/'execution/_Reconciliation/DeliverableConcordance/PEC_REMAINING_CONCORDANCE_2026-09-05';package=run/'R1_R4_2026-09-05/PACKAGES/PKG-03';w=package/'WORKERS/DEL-03-03';d=p/'execution/PKG-03_Reconciliation_Parity/1_Working/DEL-03-03_Drift_classification';base='2be412ccea62bdc4bd96deb082c46d7a792076ea'
hashes={}
def read(f):
 b=f.read_bytes();hashes[str(f.relative_to(root))]=hashlib.sha256(b).hexdigest();return b.decode()
files=[root/'AGENTS.md',p/'AGENTS.md',root/'agents/AGENT_RECONCILIATION.md',root/'docs/DELIVERABLE_CONCORDANCE_METHOD.md',run/'CONVENTIONS.md',package/'PACKAGE_BASIS.md',package/'SOURCE_MANIFEST.json',package/'BRIEFS/DEL-03-03.md',package/'validate_worker.py',run/'R1_R4_2026-09-05/COMMON/BRIEFS/PKG-03.md',run/'R1_R4_2026-09-05/COMMON/BRIEF_CLARIFICATION_01.md']
files+=list((run/'R1_R4_2026-09-05/COMMON').glob('*.json'))+list((run/'R1_R4_2026-09-05/COMMON').glob('*.md'))+list(d.rglob('*'))
files+=[p/'docs/PRD.md',p/'docs/STATUS.md',p/'loop/LOOP_INIT.md',p/'software-workflow.json',p/'execution/_Scripts/pec_reliance_hold.py',p/'execution/_Coordination/ACTIVE_RELIANCE_HOLDS.csv']
files+=list((p/'execution/_Coordination/_DECISIONS').glob('D-PEC-8[12]*.md'))
files+=[p/'execution/_Decomposition'/f for f in ['_LATEST.md','ScopeLedger.csv','Deliverables.csv','SOFTWARE_DECOMP.md']]
files+=list((p/'v2').rglob('*.py'))+list((p/'v2').rglob('*.json'))+list((p/'v2').rglob('*.md'))
for sibling in ['PKG-03_Reconciliation_Parity/1_Working/DEL-03-01_Full_rebuild_reconciler_one_command','PKG-01_Service_Core_Store/1_Working/DEL-01-01_Record_tier_schema_entity_model']:
 folder=p/'execution'/sibling
 files += [f for f in folder.glob('*') if f.name in ['ScopeOfWork.md','_STATUS.md','_REVIEW.md']]
for f in files:
 if f.is_file():read(f)
sow=read(d/'ScopeOfWork.md');sowpath=str((d/'ScopeOfWork.md').relative_to(root));defs=list(re.finditer(r'^- \*\*((?:REQ|AC|VER|CLM|AX|CON|TBD|OUT)-\d+)\*\* — (.*)',sow,re.M));assert len(defs)==80
cmd=['python3','execution/_Scripts/pec_reliance_hold.py','--register','execution/_Coordination/ACTIVE_RELIANCE_HOLDS.csv','--target',str((d/'ScopeOfWork.md').relative_to(p)),'--operation','candidate-validation'];r=subprocess.run(cmd,cwd=p,capture_output=True,text=True);assert r.returncode==0 and 'ALLOW' in r.stdout
checks=[dict(command=' '.join(cmd),cwd='projects/pec',environment='Python3; read-only; no product invocation',exit_code=r.returncode,result=r.stdout.strip())]
CH='ClaimID,DeliverableID,ClaimClass,NormativeSource,ScopeItemIDs,DeclaredSource,CurrentState,ImplementationEvidence,VerificationEvidence,ValidationOrProvenanceEvidence,LifecycleEvidence,ExistingRemaining,Disposition,ProposedResidualID,ProposedResidualText,Depends,ExactGate,AuthorityNeeded,Selectability,SourceCommit,SourceHashes,EvidenceReferences,Notes'.split(',');RH='ResidualID,DeliverableID,ClaimIDs,ProposedText,Depends,ExactGate,ClosureEvidence,AuthorityNeeded,Selectability,Notes'.split(',')
gate='(gated: separate owner-ruled exact Remaining application; F-PEC-1 source work requires packet naming paths, acts, verification and rollback; ACTIVE reliance holds rechecked; no lifecycle/release/reliance authority under D82)'
texts={1:'Establish source-bound implementation evidence for the drift classifier and REQ-001 through REQ-014 against the accepted contract; if production is authorized, implement only the ruled missing scope without settling upstream schema/snapshot questions by inference.',2:'Supply executing claim-mapped evidence for VER-001 through VER-014 and AC-001 through AC-014; preserve finite fixture limits and separately rerun live upstream integration when available.',3:'Obtain or locate exact current REVIEW acceptance evidence for AC-015, preserving earlier B5/B6 contract acceptance and source semantics; no fresh acceptance is inferred from authoring validation.',4:'Prepare an owner-scoped documentary correction for stale present-tense dependency evidence in CLM-008 and AX-009, and date-qualify OPEN references in CLM-014/AX-012 plus superseded pointer prose; preserve historical contract bytes and current INITIALIZED authority.',5:'Route CON-001 through CON-005 and TBD-004 to the owning schema/store/reconciler and consumer scope decisions: prior-state regeneration, snapshot referent, producer paths, limitation classification and producer attribution remain unresolved; do not silently choose an upstream contract interpretation.'}
rows=[]
for m in defs:
 local,quote=m.groups();kind=local.split('-')[0];n=int(local.split('-')[1]);rid=None;disp='ALIGNED';cl='DOCUMENTARY_ALIGNMENT';ev='Current contract definition and accepted decomposition SOW-019 / OBJ-002 agree at documentary scope strength; this is not behavior evidence.'
 if kind in ['REQ','OUT']:
  cl='PRODUCT_REQUIREMENT';disp='UNKNOWN';rid=1;ev='Current v2 source inventory and implementation inspection identify loop-registry capability, API contract and posture checker, not a demonstrated drift execution path. Historical local runs are contract authoring/repair only. No all-input behavior or implementation-absence conclusion follows from this bounded search.'
 elif kind=='AC':
  cl='HUMAN_ACCEPTANCE' if n==15 else 'ACCEPTANCE_CRITERION';disp='UNKNOWN';rid=3 if n==15 else 2;ev='Local B5/B6 records preserve historical contract acceptance and exact corrections; no current product acceptance run for this criterion was identified. Authoring/checklist PASS does not execute product acceptance.'
 elif kind=='VER':
  cl='FINITE_TEST_METHOD';disp='UNKNOWN';rid=2;ev='Method is explicitly declared in the contract. No corresponding executing drift test artifact was identified in current v2 tests or local run records; not a failed test and not a universal behavior finding.'
 elif kind=='CON' or local=='TBD-004':
  cl='AUTHORITY_QUESTION';disp='UNKNOWN';rid=5;ev='Contract explicitly records this undecided interface/scope question. No owner resolution established in bounded current sources; route rather than manufacture implementation scope.'
 elif local in ['CLM-008','AX-009','CLM-014','AX-012']:
  disp='STALE_INPUT';rid=4;ev='Dependencies.csv DEP-03-03-003 now contains docs/PRD.md, PRD.md §9.2 requirement PEC-RCN-004 and a full EvidenceQuote, repaired under D-PEC-65. _STATUS.md says INITIALIZED, while contract OPEN prose preserves authoring-time state; qualify chronology, do not reverse lifecycle.'
 elif local in ['CLM-007','CLM-009']:
  disp='UNKNOWN';rid=5;ev='Upstream contract quotation is historical context; current successor contract may not preserve exact quotation semantics. No claim of upstream implementation; accepted predecessor maturity does not flip PENDING dependency status.'
 elif kind=='TBD':
  ev='Truthful unassigned ResponsibleParty / production choice is declared state. No administrative assignment or invented class/invocation requirement is proposed.'
 row=dict.fromkeys(CH,'');row.update(ClaimID='DEL-03-03::'+local,DeliverableID='DEL-03-03',ClaimClass=cl,NormativeSource=sowpath+'#'+local,ScopeItemIDs='SOW-019',DeclaredSource=quote,CurrentState='INITIALIZED; no ## Remaining; '+ev,ImplementationEvidence=ev,VerificationEvidence=('Declared '+local+' only; no executing result claimed.' if kind=='VER' else 'READ_MANIFEST.json current source inventory; local _run_records authoring checks only.'),ValidationOrProvenanceEvidence='D81 calibration acceptance and D82 reporting authority; B5/B6 acceptance chronology retained.',LifecycleEvidence=str((d/'_STATUS.md').relative_to(root))+' Current State INITIALIZED',ExistingRemaining='No ## Remaining section; not warranted NONE',Disposition=disp,Depends='DEL-03-01' if rid in [1,2] else 'NONE',ExactGate=gate,AuthorityNeeded='PEC owner exact application; production/source and acceptance gates remain separate',Selectability='NON_SELECTABLE_PENDING_OWNER_APPLICATION',SourceCommit=base,SourceHashes=json.dumps({sowpath:hashes[sowpath]},sort_keys=True),EvidenceReferences='READ_MANIFEST.json; COVERAGE.md; '+sowpath+'#'+local,Notes='Atomic local definition retained in DeclaredSource. Historical quoted upstream IDs are not local definitions; negative inventory is not proof of implementation absence.')
 if rid:row.update(ProposedResidualID=f'DEL-03-03-REM-{rid:03}',ProposedResidualText=texts[rid])
 rows.append(row)
# additional material non-ID documentary provenance claim
local='PROVENANCE_CURRENT';row=rows[0].copy();row.update(ClaimID='DEL-03-03::'+local,ClaimClass='DOCUMENTARY_ALIGNMENT',NormativeSource=sowpath+'#Purpose and Objective Traceability',DeclaredSource='Opening prose says references still name revision1.1 and contract cites revision1.2 as current_basis.',Disposition='STALE_INPUT',CurrentState='_REFERENCES.md and _CONTEXT.md now identify revision1.4; dated provenance requires qualification, not ordinary currency reopening.',ProposedResidualID='DEL-03-03-REM-004',ProposedResidualText=texts[4],Depends='NONE');rows.append(row)
res=[]
for n,t in texts.items():
 rid=f'DEL-03-03-REM-{n:03}';linked=[x['ClaimID'] for x in rows if x['ProposedResidualID']==rid];res.append(dict(zip(RH,[rid,'DEL-03-03',';'.join(linked),t,'DEL-03-01' if n in [1,2] else 'NONE',gate,'Source-bound exact implementation/tests or owner-ruling evidence matching linked claims; source hashes and claim multiset backcheck.','PEC owner; exact application and any product/scope/acceptance authority separately ruled','NON_SELECTABLE_PENDING_OWNER_APPLICATION','Evidence proposal only; '+('Product/evidence candidate' if n in [1,2] else 'Held acceptance/documentary/authority routing; no automatic TM mirror') ])))
for name,header,data in [('CLAIMS.csv',CH,rows),('RESIDUALS.csv',RH,res)]:
 with (w/name).open('w',newline='') as f:
  cw=csv.DictWriter(f,fieldnames=header,lineterminator='\n');cw.writeheader();cw.writerows(data)
manifest=dict(source_commit=base,hashes=hashes,historical_sources=[],checks=checks,source_unchanged=all(hashlib.sha256((root/f).read_bytes()).hexdigest()==h for f,h in hashes.items()));(w/'READ_MANIFEST.json').write_text(json.dumps(manifest,indent=2)+'\n')
counts={v:sum(x['Disposition']==v for x in rows) for v in sorted(set(x['Disposition'] for x in rows))}
(w/'COVERAGE.md').write_text(f'''# DEL-03-03 claim coverage

ASSESSSED_UNKNOWN (canonical summary: ASSESSED_UNKNOWN). Base {base}; derivative only, D82 accepted R1–R4 scope. 80/80 local definitions: OUT2 REQ14 AC15 VER14 CLM14 AX12 TBD4 CON5; one additional opening-provenance claim =81. All full definition lines are retained in DeclaredSource. Embedded blockquoted upstream REQ/OUT IDs, matrix references, SOW/OBJ and dependency IDs are context mapped through CLM records, not duplicate local definitions. Counts {counts}; five residual proposals; warranted NONE forbidden.

Current accepted scope is revision1.4, SOW-019 and OBJ-002 mapping unchanged. _STATUS is INITIALIZED and has no Remaining. The contract's OPEN and stale-pointer language is authoring chronology; the proposed correction is date qualification, never lifecycle reversal or reopening completed ordinary currency. D65 independently repaired dependency evidence, while CLM-008/AX-009 still assert empty evidence. The sole ACTIVE PREREQUISITE is DEP-03-03-003 -> DEL-03-01 with PENDING satisfaction, even though predecessor INITIALIZED maturity is observable. Depends applies only when the proposed item names that exact target; documentary/owner routing has NONE. No unrelated TM023 gate.

Behavior/evidence boundary: v2 production code currently inspected comprises the typed loop-registry protocol and JSON adapter, with API/config contracts and enforcement tests. No drift behavior claim was demonstrated. This is UNKNOWN rather than DOCUMENTED_UNIMPLEMENTED: absence of a drift filename alone is insufficient. Local four run records concern July25 contract authoring and corrections; their validator/checklist passes do not execute VER-001..014. No broad suites were run gratuitously. REQ/OUT are product obligations; AC finite acceptance and VER finite methods remain distinct; AC015 is human REVIEW evidence and historical B5/B6 acceptance is preserved. No release claim exists locally; standing posture enforcement cannot prove this future classifier's dependency/locality behavior.

Cross-package issues retained for manager routing: CON001 prior snapshot regeneration spans DEL01-01/DEL01-03/DEL03-01; CON002 snapshot referent spans schema and reconciliation; CON003 producer paths spans DEL03-02; CON004 limitation versus drift affects DEL09-07 drift-density; CON005 producer attribution affects DEL01-01, DEL03-04 and DEL10-11 parity counts. These are recorded questions, not new scope or authority conflicts proved by this audit. TBD001 assignment is truthful documentary state; TBD002/003 are contract-permitted production choices. Neither creates an automatic administrative Remaining item.

R0 did not sample this member; no R0 behavioral reuse. Accepted conventions are read with D81 append-only acceptance, which supersedes historical candidate label without rewriting it. Current-source bytes and controls rehashed in READ_MANIFEST. No foreign project read or runtime assertion; no live source writes; historical run content is dated documentary evidence at current base, not replayed old product.
''')
print(json.dumps({'claims':len(rows),'residuals':len(res),'counts':counts,'hashes':len(hashes)}))
