#!/usr/bin/env python3
"""Adapt the accepted batch-author harness to frozen PKG-16."""
import re
from pathlib import Path

root = Path(__file__).resolve().parents[8]
template = root / "execution/_Coordination/AgentRuns/SOW-STAGE2-EXEC-20260712-01/instances/WORKING-P2-PKG09/children/AUTHOR-B1/run_author.py"
source = template.read_text(encoding="utf-8")
source = source.replace("WORKING-P2-PKG09", "WORKING-P4-PKG16")
source = source.replace("candidates/W_P2/PIP-PKG09", "candidates/W_P4/PIP-PKG16")
source = source.replace("snapshots/W_P2/preflight/P2_MANIFEST.tsv", "snapshots/W_P4/preflight/P4_MANIFEST.tsv")
source = source.replace("eaad463c0d481f6f1654e6adb5ee718f566176e9", "e8f59a63372f38d9e788ac39b39995558f5aba73")
source = source.replace('DIDS=[f"DEL-09-{n:02d}" for n in range(1,6)]', 'DIDS=[f"DEL-16-{n:02d}" for n in range(1,5)]')
source = source.replace('"--package-id","PKG-09"', '"--package-id","PKG-16"')
source = source.replace("assert total_lines==total_covered==1357", "assert total_lines==total_covered==1097")
source = source.replace('  run(["python3",tool("render_scope_of_work.py"),str(prod),"--output",str(m/f"ScopeOfWork-{suffix}.html")],m/f"render-{suffix}.stdout",m/f"render-{suffix}.stderr")\n', '')
source = source.replace(', ("ScopeOfWork-a.html","ScopeOfWork-b.html")', '')
source = source.replace(',("ScopeOfWork-a.html","ScopeOfWork-b.html")', '')
source = source.replace(',["render_html",sha(m/"ScopeOfWork-a.html"),sha(m/"ScopeOfWork-b.html"),"true"]', '')
source = source.replace('"members":5', '"members":4')
seeds = '''SEEDS={
"DEL-16-01":("A schema-first structured model-operation contract for GUI and agent proposals, with invented fixtures and explicit mutation, model-basis, unit, provenance, diagnostic, and professional-boundary controls, is produced.","The contract preserves the JSON Schema 2020-12 envelope, all declared operation and change categories, structured-only mutation route, target and precondition references, accepted-model-state hashes, unit and dimension requirements, diagnostics, diff-preview and downstream acceptance hooks, assumptions, provenance, invented-public fixture boundaries, professional non-authority, sibling ownership limits, and unresolved persistence, hash-partitioning, operation-granularity, autonomy, and human-disposition questions without creating direct mutation or acceptance.","Validate the contract and review source parity, complete operation/change taxonomy and record fields, structured-only mutation route, model-basis/current-hash and unit boundaries, diagnostics/provenance and invented-fixture posture, sibling ownership separations, retained CT-001 through CT-003 and other TBDs, and absence of hidden mutation, protected content, or professional-authority claims."),
"DEL-16-02":("A backend operation-validation and deterministic diff-preview contract that blocks invalid structured operations before application and preserves accepted model state is produced.","The contract preserves JSON Schema 2020-12 validation, model-basis and current-hash preconditions, canonical dimension and target-reference checks, injected blocking constraint diagnostics, direct-mutation rejection, deterministic before/after preview rows, not-applied and unchanged-state evidence, structured diagnostics/provenance, upstream and downstream ownership boundaries, invented fixture evidence, professional non-authority, and explicit TBDs for final constraint APIs, diff/tolerance payloads, persistence/application, and human dispositions.","Validate the contract and review source parity, schema/constraint/unit/hash/target/direct-mutation blocking paths, deterministic preview shape and no-application behavior, accepted-state nonmutation, dependency and layer boundaries, structured diagnostics/provenance, retained downstream API and tolerance TBDs, and absence of hidden mutation, protected defaults, or professional-authority claims."),
"DEL-16-03":("A deterministic user-acceptance and model-operation audit-trail contract covering accepted, rejected, and held-for-user-acceptance outcomes without applying operations is produced.","The contract preserves explicit user acceptance, passed validation and generated hash-bound diff-preview gates, accepted-model-state hash/precondition evidence, operation history, rationale, assumptions, affected entities, actor/source metadata, timestamps, validation outcomes, audit metadata, deterministic record hashes, visible TBD diagnostics, rejected-record retention in the current payload, unchanged accepted state, invented-public data boundaries, professional non-authority, and unresolved durable persistence, retention, identity, timestamp, application, autonomy, and human-disposition matters.","Validate the contract and review source parity, accepted/rejected/held disposition coverage, explicit user and validation/preview/hash gates, complete SOW-070 audit metadata, deterministic identity, visible missing-input diagnostics, rejected and accepted-state nonmutation behavior, protected-data and professional boundaries, and retention of every persistence, retention, actor, timestamp, application, and human-disposition TBD."),
"DEL-16-04":("A deterministic agent-rationale and professional-boundary control contract that preserves review context while keeping agent output decision-support only is produced.","The contract preserves operation context/history, rationale, unresolved assumptions, affected entities, audit and validation context/references, source/actor metadata, timestamps, diagnostics, provenance, stable rationale identity/hash, visible TBD findings, explicit human-review and external hash-bound human-authority boundaries, copied-context claim scanning, prohibited authority-language blocking, no accepted-record creation, no acceptance bypass, no accepted-state mutation, protected/private-data controls, and unresolved standalone schema, persistence, UI/API/report, broader application, dependency, and human-disposition matters.","Validate the contract and review source parity, rationale/audit/validation/source/actor context preservation, deterministic identity, visible TBD and unresolved-assumption behavior, all prohibited-claim and copied-context guards including false-positive boundaries, external human-owned acceptance separation, no application or state mutation, protected-data posture, retained downstream TBDs, and absence of autonomous acceptance or professional-authority claims.")}
'''
source, count = re.subn(r"SEEDS=\{.*?\}\n\n(?=def sha)", seeds + "\n", source, flags=re.S)
assert count == 1
for forbidden in ("DEL-09-", "PKG-09", "W_P2/PIP-PKG09", "P2_MANIFEST.tsv", "WORKING-P2-PKG09", "ScopeOfWork-a.html"):
    assert forbidden not in source, forbidden
compile(source, str(template), "exec")
exec(compile(source, str(template), "exec"), {"__name__": "__main__"})
