#!/usr/bin/env python3
"""Formal calculation witness checks for TP-WITNESS-023."""

from __future__ import annotations

from copy import deepcopy
import json
from pathlib import Path
import sys
from tempfile import TemporaryDirectory


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from validation.witness.tools.witness_validator import (  # noqa: E402
    WitnessError,
    assert_generated_artifacts_current,
    evaluate_witness,
    load_json,
    render_markdown,
)


WITNESS_PATH = (
    ROOT
    / "validation"
    / "witness"
    / "fixtures"
    / "tp_phys_015_section_property_stress_witness.json"
)


def load_witness():
    return load_json(WITNESS_PATH)


def expect_witness_error(witness, expected_text):
    try:
        evaluate_witness(witness)
    except WitnessError as exc:
        assert expected_text in str(exc)
    else:
        raise AssertionError(f"expected WitnessError containing {expected_text!r}")


def test_tp_phys_015_witness_validates_and_compares_to_result_export():
    witness = load_witness()
    evaluation = evaluate_witness(witness)
    assert evaluation.witness_id == "WITNESS-TP-PHYS-015-SECTION-PROPERTY-STRESS"
    assert len(evaluation.comparisons) == 6
    by_formula = {comparison.formula_id: comparison for comparison in evaluation.comparisons}
    assert by_formula["bending_normal_stress_z"].passed
    assert by_formula["bending_normal_stress_z"].result_id == (
        "result:stress:element-E-1:midspan:bending-normal-z"
    )


def test_generated_markdown_and_mathml_are_current():
    witness = load_witness()
    assert_generated_artifacts_current(witness)
    rendered = render_markdown(witness)
    assert "Witness SHA-256 over canonical JSON" in rendered
    assert "Do not edit this file as the authoritative calculation source." in rendered


def test_rejects_unsupported_openmath_symbol():
    witness = load_witness()
    witness["formulas"][0]["openmath"]["operator"]["name"] = "sin"
    expect_witness_error(witness, "unsupported OpenMath")


def test_rejects_dimension_mismatch():
    witness = load_witness()
    witness["formulas"][1]["expected_dimension"] = "force"
    expect_witness_error(witness, "dimension mismatch")


def test_rejects_stale_generated_markdown(tmp_path):
    witness = load_witness()
    stale = tmp_path / "stale.md"
    stale.write_text("stale\n", encoding="utf-8")
    witness["generated_artifacts"]["markdown_path"] = str(stale)
    try:
        assert_generated_artifacts_current(witness)
    except WitnessError as exc:
        assert "generated Markdown is stale" in str(exc)
    else:
        raise AssertionError("expected stale generated Markdown to be rejected")


def test_rejects_tampered_formula_output():
    witness = load_witness()
    witness["formulas"][-3]["openmath"]["arguments"][0]["name"] = "torsional_moment"
    expect_witness_error(witness, "OPS result mismatch")


def test_rejects_missing_provenance():
    witness = load_witness()
    del witness["provenance"]
    expect_witness_error(witness, "witness schema validation failed")


def test_rejects_ops_result_mismatch(tmp_path):
    witness = load_witness()
    result_path = ROOT / witness["result_export"]["path"]
    result_export = json.loads(result_path.read_text(encoding="utf-8"))
    result_export["result_envelope"]["result_sets"][1]["values"][0]["magnitude"] = 8.0
    tampered_result_path = tmp_path / "tampered-result.json"
    tampered_result_path.write_text(json.dumps(result_export), encoding="utf-8")
    witness["result_export"]["path"] = str(tampered_result_path)
    expect_witness_error(witness, "OPS result mismatch")


def test_rendered_markdown_changes_when_witness_changes():
    witness = load_witness()
    changed = deepcopy(witness)
    changed["title"] = "Changed witness title"
    assert render_markdown(witness) != render_markdown(changed)


def main():
    test_tp_phys_015_witness_validates_and_compares_to_result_export()
    test_generated_markdown_and_mathml_are_current()
    test_rejects_unsupported_openmath_symbol()
    test_rejects_dimension_mismatch()
    with TemporaryDirectory() as directory:
        test_rejects_stale_generated_markdown(Path(directory))
    test_rejects_tampered_formula_output()
    test_rejects_missing_provenance()
    with TemporaryDirectory() as directory:
        test_rejects_ops_result_mismatch(Path(directory))
    test_rendered_markdown_changes_when_witness_changes()


if __name__ == "__main__":
    main()
