# I104 SQ G5: the disposition of every loop on a line B1 added or changed (inv/loops_c1_raw.json, by index),
# and of every existing rule whose bound depends on the case count. Bounds use the chain's count symbols:
# cases = c (requested cases), att = a (cases in A, |A| <= c), L = total loads (<= c*l), Pall = c*P_final
# (every row of the c-case envelope), D = the diagnostics fixpoint; n, m, g, s, k, r, l, P as before.
A = "B1 SP T-5/T-7..T-11: one entry per case in A, the attempted cases (|A| <= a <= c)"
AS = "B1 SP T-8: the prepared cases of A submitted to the one CaseBatchCall (<= |A| <= a)"
C = "B1: one entry per requested case (c <= C = 3; D1.4 at B1 SA)"
PALL = "B1: every row of the c-case envelope (one block of P_final rows per requested case, lib.rs's case loop): c*P_final"
OPT = "Option/Result adapter: the closure runs at most once"
NEW = {  # inventory index -> (bound, why)
  0: ("att", "lib.rs ReservedNotices::reserve: case_ids are A's ids (retained_w1 passes attempted.ids()). " + A),
  1: ("att", "lib.rs ReservedNotices::reserve: one notice slot per case in A. " + A),
  2: ("att", "lib.rs ReservedNotices::publish: the reserved notices, one per case in A. " + A),
  3: ("cases", "lib.rs CaseSet::attempted: the requested cases and their triggers. " + C),
  4: ("cases", "lib.rs w1_case_ids: the request's load_cases, 1 <= len <= LOAD_CASES checked first. " + C),
  6: ("D", "lib.rs ReservedNotices::reserve: the ordinary envelope's diagnostics <= D_env <= D (TEXT fixpoint), once per case in A (the enclosing loop)"),
  8: ("cases", "lib.rs case_triggers: one trigger per requested case id. " + C),
  9: ("cases", "lib.rs case_triggers: numerical_quality.cases, one entry per requested case. " + C),
  10: ("1", "lib.rs case_triggers: only_one(..).map is Option::map. " + OPT),
  11: ("cases", "lib.rs case_triggers: the ordinary seeds, one per requested case (T-2). " + C),
  12: ("cases", "lib.rs retained_w1: .any over case_triggers(..), one item per requested case (the generic 'no iterator source' rule would read it as once). " + C),
  13: ("att", "lib.rs w1_transaction: `reached` scans prepared.attempts, one per case in A. " + A),
  18: ("L", "retained_memory.rs family_clauses (D1.7 per case, B1 SA): every case's primitive loads, sum_i l_i <= L"),
  20: ("cases", "retained_memory.rs family_clauses: the header is the `.flat_map(|case| &case.primitive_loads)` adapter (its receiver text runs back over the preceding loops); the closure runs once per requested case. " + C),
  21: ("cases", "retained_memory.rs ordinary_solve_attempted: capture.ordinary, one seed per requested case (T-3 (e)). " + C),
  23: ("cases", "retained_product.rs bind_observations_by_case: cases = cases_seen() <= c. " + C),
  24: ("cases", "retained_product.rs bind_observations_by_case: one counter pair per case seen. " + C),
  25: ("Pall", "retained_product.rs bind_observations_by_case: one pass over the whole envelope's rows (T-6; RV109 decision 19). " + PALL),
  26: ("cases", "retained_product.rs bind_observations_by_case: the owner search over the cases seen, per mode/parity row. " + C),
  27: ("cases", "retained_product.rs bind_observations_by_case: the presence check per case seen. " + C),
  28: ("att", "retained_product.rs PreparedCases::native: attempts filtered to Prepared. " + A),
  29: ("att", "retained_product.rs PreparedCases::native: attempts filtered to Prepared. " + A),
  30: ("att", "retained_product.rs PreparedCases::freeze: attempts filtered to Selected (T-9). " + A),
  31: ("att", "retained_product.rs PreparedCases::staged_envelope: one overlay per frozen attempt. " + A),
  32: ("Pall", "retained_product.rs bind_case_rows: one pass over the whole envelope's rows (T-6, c >= 2). " + PALL),
  33: ("att", "retained_product.rs prepare_cases: one product attempt per case in A (T-7). " + A),
  34: ("att", "retained_product.rs native_call: submitted() yields the prepared requests. " + AS),
  35: ("att", "retained_product.rs native_call: submitted() yields the prepared requests. " + AS),
  36: ("att", "retained_product.rs native_call: one kernel case per submitted request. " + AS),
  47: ("P", "retained_product.rs prepared_alias: the frozen case's own rows (its case scope, one block of P_final rows)"),
  48: ("P", "retained_product.rs apply_prepared_overlay: the case's scoped rows (one block of P_final; the whole envelope only at c = 1, where it is P_final)"),
  50: ("Pall", "retained_product.rs stage_headlines: the staged envelope's rows of one kind, per headline kind (the enclosing array literal of 2). " + PALL),
  51: ("cases", "retained_product.rs finish: the parked case slots (c - 1 at most). " + C),
  52: ("att", "retained_product.rs PreparedCases::native: attempts.iter().any. " + A),
  53: ("att", "retained_product.rs PreparedCases::native: the filter closure over attempts (its receiver text runs back over the early return). " + A),
  54: ("att", "retained_product.rs PreparedCases::native: submitted() closure: attempts filtered to Prepared. " + A),
  55: ("att", "retained_product.rs PreparedCases::native: submitted() closure's map over the filtered attempts. " + A),
  56: ("att", "retained_product.rs PreparedCases::native/freeze: the filter closure over attempts. " + A),
  58: ("att", "retained_product.rs PreparedCases::freeze: the filter closure over attempts. " + A),
  59: ("att", "retained_product.rs selected_attempts: attempts enumerated and filtered. " + A),
  65: ("cases", "retained_product.rs prepared_custody: the parked slots (c - 1 at most). " + C),
  66: ("cases", "retained_product.rs prepared_custody: parked.iter().any over the parked slots. " + C),
  67: ("att", "retained_product.rs prepared_custody: attempted.iter().any over A's request indices. " + A),
  68: ("att", "retained_product.rs prepared_custody: attempted.windows(2).any over A's request indices. " + A),
  70: ("att", "retained_product.rs native_call: submitted().any (the generic 'no iterator source' rule would read it as once). " + AS),
  71: ("att", "retained_product.rs native_call: the second submitted().any (its receiver text runs back over the first). " + AS),
  73: ("P", "retained_product.rs ProductCaseView::rows: the case's rows (case_rows: its scope, one block of P_final)"),
  74: ("P", "retained_product.rs freeze_case: the case's verdicts, one per row of its scope (inside a #[cfg(test)] println)"),
  75: ("P", "retained_product.rs freeze_case: the case's verdicts, one per row of its scope (inside a #[cfg(test)] println)"),
  76: ("Pall", "retained_product.rs stage_headlines: the filter closure over the staged envelope's rows. " + PALL),
  80: ("cases", "retained_wire.rs material_basis: every requested case's base selector. " + C),
  81: ("D", "retained_wire.rs case_diagnostic_refs_into: the successor envelope's diagnostics, D_env plus the appended selected/unavailable diagnostics <= D (TEXT fixpoint)"),
  82: ("cases", "retained_wire.rs case_diagnostic_refs_into: one ref list per requested case. " + C),
  83: ("att", "retained_wire.rs serialize_cases_with: every attempt's slot. " + A),
  84: ("cases", "retained_wire.rs serialize_cases_with: one legacy disposition per requested case's seed. " + C),
  85: ("cases", "retained_wire.rs serialize_cases_with: each requested case's legacy entry. " + C),
  86: ("cases", "retained_wire.rs serialize_cases_with: `0..count`, count = requested cases. " + C),
  87: ("cases", "retained_wire.rs serialize_cases_with: one ordinary attempt per requested case. " + C),
  88: ("att", "retained_wire.rs serialize_cases_with: each product attempt in start order. " + A),
  89: ("cases", "retained_wire.rs serialize_cases_with: cases[], one per requested case. " + C),
  91: ("att", "retained_wire.rs invocation_arrays: the one call's owners, one per submitted case. " + AS),
  92: ("1", "retained_wire.rs invocation_arrays: inv.calls().iter().any: one CaseBatchCall per invocation (T-8; serialize_cases_with checks calls().len() == 1)"),
  93: ("L+4", "retained_wire.rs case_diagnostic_refs_into: one diagnostic's affected refs (G4's l + 4, rule `for reference in affected`, with a per-load list spanning every case: L + 4)"),
  94: ("cases", "retained_wire.rs serialize_cases_with: the request's load_cases. " + C),
  95: ("cases", "retained_wire.rs serialize_cases_with: seeds zipped with the case ids. " + C),
  96: ("cases", "retained_wire.rs serialize_cases_with: each requested case's attempt slot. " + C),
  98: ("att", "retained_wire.rs serialize_cases_with: the attempts filtered to prepared. " + A),
  99: ("att", "retained_wire.rs serialize_cases_with: the prepared attempts' requests. " + A),
  100: ("att", "retained_wire.rs serialize_cases_with: requests = the prepared attempts' request indices. " + AS),
  101: ("1", "retained_wire.rs serialize_cases_with: Option::filter on the position. " + OPT),
  103: ("att", "retained_wire.rs serialize_cases_with: execution_order over the call's Runs, one per submitted case. " + AS),
  105: ("P", "retained_wire.rs serialize_attempt: the case scope's rows of the successor (one block of P_final)"),
  106: ("1", "retained_wire.rs serialize_attempt: Option::map inside the row map. " + OPT),
  107: ("P", "retained_wire.rs serialize_attempt: the case's bound rows zipped with its row ids (one block of P_final)"),
  110: ("att", "retained_precision.rs g3 (RS): body.sources, one CaseSource per submitted case. " + AS),
  112: ("att", "retained_precision.rs g8 (RS): body.sources, one CaseSource per submitted case. " + AS),
  113: ("cases", "retained_precision.rs preview_physics_transport_metadata (RS): evidence.preview_cases, one per requested case. " + C),
  114: ("g", "retained_precision.rs preview_physics_transport_metadata (RS): one case's withheld support records <= g supports"),
  115: ("2*m", "retained_precision.rs preview_physics_transport_metadata (RS): one case's pipe_stress_extrema <= 2 per member (as G4's extrema rule)"),
  116: ("m", "retained_precision.rs preview_physics_transport_metadata (RS): one case's intensified measures <= one per member"),
  117: ("0", "retained_precision.rs preview_physics_transport_metadata (RS): combination_gates exist only for combinations (none in D1.4/B1)"),
  118: ("cases", "retained_precision.rs g3 (RS): one material basis's case_indices, each a requested case. " + C),
  119: ("8", "retained_precision.rs d38_capture_before_run (RS): STAGE8[2..] (6 of the 8 stage names) chained with a 2-element literal"),
  120: ("2", "retained_precision.rs g8 (RS): the 2-element literal [combinations, components]"),
  121: ("P", "retained_precision.rs g8 (RS): the case's rows (rows_for, one block of P_final)"),
  122: ("cases", "retained_precision.rs g5_ordinary (RS): one material basis's case_indices. " + C),
  123: ("16", "retained_precision.rs preview_physics_transport_metadata `shape` (RS): a literal key list, at most 16 keys"),
  124: ("max(m, g)", "retained_precision.rs preview_physics_transport_metadata `strings` (RS): a pipe-id (<= m) or support-id (<= g) list"),
  127: ("m", "retained_precision.rs preview_physics_transport_metadata (RS): one case's unavailable pipe ids <= m"),
  128: ("g", "retained_precision.rs preview_physics_transport_metadata (RS): one case's attributed support ids <= g"),
  129: ("g", "retained_precision.rs preview_physics_transport_metadata (RS): the withheld records collected for one case <= g"),
  130: ("2", "retained_precision.rs preview_physics_transport_metadata (RS): a 2-element key literal"),
  131: ("2", "retained_precision.rs preview_physics_transport_metadata (RS): a 2-element key literal"),
  132: ("2*m", "retained_precision.rs preview_physics_transport_metadata (RS): one case's pipe_stress_extrema <= 2 per member"),
  134: ("2*m", "retained_precision.rs preview_physics_transport_metadata (RS): unavailable then outside-domain pipe ids, <= m each"),
  135: ("4", "retained_precision.rs preview_physics_transport_metadata (RS): a 4-element key literal"),
  136: ("g", "retained_precision.rs preview_physics_transport_metadata (RS): one case's attributed support ids <= g"),
}
# Existing rules whose bound depended on D1's one case, re-bound for B1 (I82's 22 rebinds are the checklist;
# each is re-derived on B1's code: the regex, the sites it matches at b1-q, and the bound there).
REBIND = [  # (existing rule 're', new bound, why)
  (r'^for\ a\ in\ list\(\&b\["\ "\]\)$', "att", "RS reader (retained_precision.rs :560, :2377, :3956): body.product_attempts, one per case in A. " + A),
  (r'^for\ \(ai,\ a\)\ in\ list\(\&b\["\ "\]\)\.iter\(\)\.enumerate\(\)$', "att", "RS reader (:2083 g5_products): body.product_attempts. " + A),
  (r'^for\ \(si,\ s\)\ in\ list\(\&b\["\ "\]\)\.iter\(\)\.enumerate\(\)$', "att", "RS reader (:735 g3): body.sources, one per submitted case. " + AS),
  (r'^for\ \(i,\ c\)\ in\ list\(\&b\["\ "\]\)\.iter\(\)\.enumerate\(\)$', "cases", "RS reader (:4200 g5_ordinary): body.cases. " + C),
  (r'^for\ \(i,\ a\)\ in\ list\(\&b\["\ "\]\)\.iter\(\)\.enumerate\(\)$', "att", "RS reader (:756 g3): body.product_attempts. " + A),
  (r'^for\ c\ in\ list\(\&b\["\ "\]\)\ \.iter\(\)\ \.filter\(\|c\|\ c\["\ "\]\ ==\ "\ "\)$', "cases", "RS reader (:2657 numeric_cases): body.cases filtered. " + C),
  (r'^for\ c\ in\ list\(\&body\["\ "\]\)$', "cases", "RS reader (:3030 g5a, :4437 validate): body.cases. " + C),
  (r'^for\ s\ in\ list\(\&r\["\ "\]\["\ "\]\)$', "att", "RS reader (:608 g1): body.sources. " + AS),
  (r'^for\ c\ in\ list\(\&r\["\ "\]\["\ "\]\)$', "cases", "RS reader (:631 g1): body.cases. " + C),
  (r'^for\ \(position,\ ri\)\ in\ list\(\&call\["\ "\]\)\.iter\(\)\.enumerate\(\)$', "att", "RS reader (:968 g5_native): the one call's run_refs, one Run per submitted case. " + AS),
  (r'^for\ \(ri,\ si\)\ in\ list\(\&call\["\ "\]\)\.iter\(\)\.zip\(list\(\&call\["\ "\]\)\)$', "att", "RS reader (:1434): the one call's run/source refs. " + AS),
  (r'^for\ si\ in\ list\(\&g\["\ "\]\)$', "att", "RS reader (:952 g5_native): the one group's source_refs, every submitted case's source. " + AS),
  (r'^for\ c\ in\ cases$', "cases", "RS reader (:3206 g5b, :3293 g5c): the numeric cases. " + C),
  (r'^for\ \(i,\ c\)\ in\ cs\.iter\(\)\.enumerate\(\)$', "cases", "RS reader (:668 g3): body.cases. " + C),
  (r'^for\ \(i,\ case\)\ in\ cases\.iter\(\)\.enumerate\(\)$', "cases", "RS reader (:3566 g8): the invocation's load cases. " + C),
  (r'^for\ row\ in\ rows_list$', "Pall", "preview_physics_evidence.rs validate_preview_physics_evidence (:270, :280, :629, :678): the source's whole results array. " + PALL),
  (r'^for\ row\ in\ rows\.iter\(\)\.filter\(\|r\|\ r\["\ "\]\ ==\ kind\)$', "Pall", "preview_physics_evidence.rs headline (:775), called on rows_list (:640, :646): the whole results array. " + PALL),
  (r'flat_map\(\|case\| case\.primitive_loads', "L", "every case's primitive loads (validation.rs :227, :802, :1890; lib.rs :8920 normalize_model_units): sum_i l_i <= L (I82's rebind, re-derived on the real code)"),
  (r'for id in ids', "max(l, L)", "entity id lists (validation.rs detect_empty_ids/detect_duplicate_ids, pressure_runtime.rs :363): the load-id list spans every case (I82's rebind): <= max(l, L)"),
  (r'sources\.iter\(\)\.enumerate\(\)', "att", "FK origins.rs :364 solve_cases and adaptive.rs :4994 solve_cases_projected: one kernel case per submitted source (B1 SP T-8; FK unchanged). " + AS),
  (r'^for\ reference\ in\ affected$', "L+4", "the T17 reader's preview-evidence check (preview_physics_evidence.rs `for reference in affected`): one diagnostic's affected refs (G4's l + 4, with a per-load list spanning every case: L + 4)"),
]
# Existing rules re-checked on B1's code and kept (their D1 reason still holds at c <= 3); listed for the reviewer.
KEEP = [
  (r'^for\ \(mi,\ mb\)\ in\ list\(\&b\["\ "\]\)\.iter\(\)\.enumerate\(\)$', "1", "RS reader (:747 g3, :3616 g8): body.material_bases: the producer emits one material basis (D1.5's one default basis) whose case_indices name every case (retained_wire.rs material_basis)"),
  (r'^for\ \(call_id,\ call\)\ in\ list\(\&b\["\ "\]\)\.iter\(\)\.enumerate\(\)$', "1", "RS reader (:963, :1427): body.calls: one CaseBatchCall per invocation (T-8; the serializer refuses calls().len() != 1)"),
  (r'^for\ \(i,\ g\)\ in\ list\(\&b\["\ "\]\)\.iter\(\)\.enumerate\(\)$', "1", "RS reader (:946): body.groups: every case shares the model and D1.5's one basis, so one stiffness and one group (C2 §4; RV109 round 2 SF-1: one group, C reusing A's builds)"),
  (r'^for\ \(i,\ build\)\ in\ list\(\&b\["\ "\]\)\.iter\(\)\.enumerate\(\)$', "7", "RS reader: body.builds: one shared build per origin slot of the one group (7 slots), reused by every case's Run (RV109 round 2 SF-1)"),
  (r'^iter:inv\.calls\(\)\.iter\(\)\.map$|^iter:inv\.groups\(\)\.iter\(\)\.map$', "1", "retained_wire.rs invocation_arrays: one call and one group (as above)"),
  (r'^iter:inv\.builds\(\)\.iter\(\)\.map$', "7", "retained_wire.rs invocation_arrays: the one group's 7 shared builds (as above)"),
  (r'^for\ row\ in\ rows_list\.iter\(\)\.filter\(in_case\)$', "P", "preview_physics_evidence.rs :523: the rows of one case (inside `for case in preview_cases`)"),
  (r'^for\ item\ in\ array\(v\)\?$', "P", "preview_physics_evidence.rs strings: one case's coverage/attribution id list (<= P, G4's bound), called per case"),
  (r'^for selection in &self\.selections$', "cases", "one selection per case (as G4)"),
]
# Rules placed first, ahead of a composite rule that also matches a per-case loop.
FIRST = [
  (r'^for r in &envelope\.results$', "Pall", "source_receipt.rs finalize_for (:982, :1074; branch X): the whole envelope's rows. " + PALL + " (the composite rule `for r in rows|&case.rows|..|&envelope..` keeps P for per-case rows)"),
  (r'^for row in &envelope\.results$', "Pall", "retained_product.rs bind_observations_by_case (:1142): the whole envelope's rows. " + PALL),
]
EDGE_PER_CALL = [  # (caller, callee, old, new, why)
  ("pressure_runtime.rs:111:validate_profile", "pressure_runtime.rs:85:problem", "l", "L",
   "validate_profile's !exact arm (D1.3) fires PRESSURE_MODEL_REAUTHOR_REQUIRED at most once per primitive load of every case (pressure_runtime.rs :207-225, `for case in &model.load_cases { .. for load in &case.primitive_loads`): <= L per call (I82's rebind, re-derived)"),
]
