from pathlib import Path
import json,subprocess,os,datetime,hashlib,sys
out=Path(__file__).parent;arc=json.loads((out/'ARCHIVE.json').read_text());root=Path(arc['archive']);h='projects/chirality-piping/core/solver/performance_harness';env={**os.environ,'GIT_OPTIONAL_LOCKS':'0','RUSTUP_AUTO_INSTALL':'0','CARGO_NET_OFFLINE':'true','CARGO_INCREMENTAL':'0','CARGO_TARGET_DIR':arc['target'],'PYTHONDONTWRITEBYTECODE':'1'};overrides={k:env[k] for k in ['GIT_OPTIONAL_LOCKS','RUSTUP_AUTO_INSTALL','CARGO_NET_OFFLINE','CARGO_INCREMENTAL','CARGO_TARGET_DIR','PYTHONDONTWRITEBYTECODE']};prefix=['/Users/ryan/.cargo/bin/rustup','run','1.97.1','cargo','test','--manifest-path',h+'/Cargo.toml','--locked','--offline','-j','4']
commands=[('RELEASE',prefix+['--release','--test','k6c_envelope','--test','k6c_h_envelope','--test','k6b_w1','--test','k6b_bin','--test','rv33_reference','--','--test-threads=2'],root),('RUNNER',[sys.executable,'-m','unittest','-v','test_k6_runner'],root/h/'runner'),('DEBUG_BIN',prefix+['--test','k6b_bin','--','--test-threads=2'],root)]
metadata={'env_overrides':overrides,'rustc':subprocess.check_output(['/Users/ryan/.cargo/bin/rustup','run','1.97.1','rustc','-vV'],env=env,text=True),'cargo':subprocess.check_output(['/Users/ryan/.cargo/bin/rustup','run','1.97.1','cargo','-V'],env=env,text=True),'python':sys.version,'commands':[]}
for name,argv,cwd in commands:
 record={'name':name,'argv':argv,'cwd':str(cwd),'start_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'guard':subprocess.check_output(['ps','-p','5387','-o','pid=,etime=,command='],text=True)};assert 'memguard.sh' in record['guard'];metadata['commands'].append(record);(out/'CHECK_COMMANDS.json').write_text(json.dumps(metadata,indent=2)+'\n')
 with (out/(name+'.log')).open('w') as f:p=subprocess.run(argv,cwd=cwd,env=env,stdout=f,stderr=subprocess.STDOUT)
 record.update(exit_code=p.returncode,end_utc=datetime.datetime.now(datetime.timezone.utc).isoformat());(out/'CHECK_COMMANDS.json').write_text(json.dumps(metadata,indent=2)+'\n');print(name,p.returncode,flush=True)
metadata['archive_unchanged']=all(hashlib.sha256((root/x['path']).read_bytes()).hexdigest()==x['sha256'] for x in arc['files']);metadata['binaries']=[{'path':str(p),'sha256':hashlib.sha256(p.read_bytes()).hexdigest()} for profile in ['release','debug'] for p in (Path(arc['target'])/profile/'deps').glob('*') if p.is_file() and p.suffix=='' and p.name.startswith(('rv33_reference-','k6b_bin-','k6b_w1-','k6c_h_envelope-','k6c_envelope-'))];(out/'CHECK_COMMANDS.json').write_text(json.dumps(metadata,indent=2)+'\n');print('finished',metadata['archive_unchanged'],flush=True)
