from pathlib import Path
from decimal import Decimal as D,localcontext
import json,hashlib
with localcontext() as c:
 c.prec=110;a=D(1);b=D(1)/D(2).sqrt();t=D(1)/4;k=D(1)
 for _ in range(10):
  avg=(a+b)/2;b=(a*b).sqrt();t-=k*(a-avg)**2;a=avg;k*=2
 pi=(a+b)**2/(4*t);L=D(2);ro=D('0.1');ri=D('0.09');A=pi*(ro**2-ri**2);Ai=pi*ri**2;I=pi*(ro**4-ri**4)/4;J=2*I;E=D('200e9');nu=D('0.25');G=E/(2*(1+nu));K=D('1e-4')
 Fx,Fy,Fz,Tx,My,Mz=map(D,['.001','.002','-.003','1e-8','-.0005','.0006'])
 fields={'root_rx_rad':Tx/K,'tip_ux_mm':Fx*L/(E*A)*1000,'tip_uy_mm':(Fy*L**3/(3*E*I)+Mz*L**2/(2*E*I))*1000,'tip_uz_mm':(Fz*L**3/(3*E*I)-My*L**2/(2*E*I))*1000,'tip_rx_rad':Tx/K+Tx*L/(G*J),'tip_ry_rad':-Fz*L**2/(2*E*I)+My*L/(E*I),'tip_rz_rad':Fy*L**2/(2*E*I)+Mz*L/(E*I),'maximum_normal_Pa':Fx/A+((D('.0055')**2+D('.0046')**2).sqrt())*ro/I,'torsional_shear_MPa':Tx*ro/J/D('1e6')}
 p=D('1e-5');Ep=D(2000);wall=p*Ai;sigma=wall/A
 mixed={'pressure_wall_N':wall,'pressure_axial_membrane_Pa':sigma,'pressure_tip_ux_mm':L*(1-2*nu)*sigma/Ep*1000,'pressure_inner_hoop_Pa':p*(ro**2+ri**2)/(ro**2-ri**2),'pressure_outer_hoop_Pa':2*p*ri**2/(ro**2-ri**2),'pressure_inner_radial_Pa':-p,'pressure_outer_radial_Pa':D(0),'source_root_rx_rad':D('1e-8')/K,'source_tip_rx_rad':D('1e-8')/K+D('1e-8')*L/(G*J),'source_torsional_shear_MPa':D('1e-8')*ro/J/D('1e6')}
 result={'method':'Independent Decimal110 AGM pi; circular-section area/inertia integrals, Euler-Bernoulli cantilever compatibility, Saint-Venant torsion and equilibrium; explicit uniform-pressure homogeneous E/nu relations and Lamé fields','basis':'Previously reviewed native handoff/maintained source-case input quantities; prepared before actual native fields/mixed solves, not filled from output','section':{k:str(v) for k,v in {'L_m':L,'ro_m':ro,'ri_m':ri,'A_m2':A,'Ai_m2':Ai,'I_m4':I,'J_m4':J}.items()},'fields':{k:{'decimal':str(v),'binary64':float(v)} for k,v in fields.items()},'fields_anchor_actions':[-.001,-.002,.003,0,-.0055,-.0046],'fields_spring_Mx_Nm':-1e-8,'fields_governing_station_fraction':0,'mixed':{k:{'decimal':str(v),'binary64':float(v)} for k,v in mixed.items()},'criteria':'Unchanged nonzero relative1e-9; structurally exact source zeros equal0. Ordinary pressure zero reactions use preexisting pressure_runtime cap-force and cap-force-times-length scales; pressure-stress zeros use pressure scale. Separate modes/receipt identities required.','limits':'Bounded linear straight circular beam cases; no material/component library or code-rule data; no code/equivalent stress or complete general solver claim'}
 result['generator_sha256']=hashlib.sha256(Path(__file__).read_bytes()).hexdigest();p=Path(__file__).with_name('connected-native-references.json');assert not p.exists();p.write_text(json.dumps(result,indent=2)+'\n');print(json.dumps({'reference_sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'fields_expected_maximum_Pa':result['fields']['maximum_normal_Pa']['binary64'],'mixed_expected_pressure_extension_mm':result['mixed']['pressure_tip_ux_mm']['binary64']}))
