#!/usr/bin/env python3
"""Generate R2/PKG-08/PACKAGE_SUMMARY.md §1–§7 from the accepted ledgers (manager brief step 8).
Inputs: <DEL>/<DEL>_claims.csv (sealed), _errata.csv, _reverse.csv; _verify/V-SHARD-*.csv; STATE.jsonl.
Errata-applied figures replace sealed field values with ProposedValue per (ClaimKey, Field).
Section §8 (cross-package observations) is hand-written and appended after generation; pass
--hand <file> to include it verbatim."""
import csv, glob, hashlib, io, os, re, sys, collections
PKG = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
def dicts(p):
    if not os.path.exists(p): return []
    r = list(csv.reader(io.StringIO(open(p, encoding="utf-8", newline="").read())))
    if r and r[-1] == ["#END"]: r = r[:-1]
    return [dict(zip(r[0], x)) for x in r[1:]]
def sha(p): return hashlib.sha256(open(p, "rb").read()).hexdigest()
DELS = sorted(os.path.basename(d) for d in glob.glob(os.path.join(PKG, "DEL-*")))
sealed, applied, errata, rev = {}, {}, {}, {}
for d in DELS:
    rs = dicts(os.path.join(PKG, d, f"{d}_claims.csv")); sealed[d] = rs
    er = dicts(os.path.join(PKG, d, f"{d}_errata.csv")); errata[d] = er
    ap = [dict(r) for r in rs]; idx = {r["ClaimKey"]: r for r in ap}
    for e in er:
        if e["ClaimKey"] in idx: idx[e["ClaimKey"]][e["Field"]] = e["ProposedValue"]
    applied[d] = ap; rev[d] = dicts(os.path.join(PKG, d, f"{d}_reverse.csv"))
CORR = dicts(os.path.join(PKG, "CORRECTIONS.csv")); CENSUS = {"ClaimType", "Disposition", "CauseTag", "AuthorityTier", "Confidence", "HumanDecisionNeeded"}
corrected = {}
for d in DELS:
    cp = [dict(r) for r in applied[d]]; idx = {r["ClaimKey"]: r for r in cp}
    for c in CORR:
        f = c["Field"].split(" ")[0]
        if c["ClaimKey"] in idx and f in CENSUS:
            m = re.match(r"\s*([A-Z0-9_:;\- ]+?)(?:[:.,(]\s|\s*$|\s\|\|)", c["CorrectedValue"])
            if m: idx[c["ClaimKey"]][f] = m.group(1).strip()
    corrected[d] = cp
def reach(r):
    t = set(re.findall(r"REACH=(LIVE|LEGACY_ONLY|TEST_ONLY)", r["ImplementationEvidence"]))
    if not t: return "NONE(no code evidence)"
    return "+".join(sorted(t))
def hdn(r):
    v = [x.strip() for x in r["HumanDecisionNeeded"].split(";") if x.strip()]
    return v
FIELDS = [("ClaimType", lambda r: [r["ClaimType"]]), ("Disposition", lambda r: [r["Disposition"]]),
          ("CauseTag", lambda r: [r["CauseTag"]]), ("AuthorityTier", lambda r: [r["AuthorityTier"]]),
          ("REACH (row-level tag set)", lambda r: [reach(r)]), ("Confidence", lambda r: [r["Confidence"]]),
          ("HumanDecisionNeeded (token-level)", hdn)]
out = []; w = out.append
w("# PACKAGE_SUMMARY — PKG-08 (RUN_D128_CONCORDANCE_2026-09-21_1614Z, R2 wave 1)\n")
w("> Evidence, not rulings. §1–§7 generated by `R2/PKG-08/_scripts/package_summary.py` from the sealed ledgers,")
w("> errata, reverse files and verifier shards; §8 is hand-written by the PKG-08 manager. Basis `00115c719`.\n")
w("## §1 Ledgers of record\n")
w("| Deliverable | Rows | Indexed units | SEE rows | Split units | Sealed SHA-256 | Errata rows | Reverse rows |")
w("|---|---:|---:|---:|---:|---|---:|---:|")
for d in DELS:
    rs = sealed[d]; base = {r["ClaimKey"].split("#")[1].split(".")[0] for r in rs if not re.search(r"#(REGISTER|STATE)-", r["ClaimKey"])}
    split = {r["ClaimKey"].rsplit(".", 1)[0] for r in rs if re.search(r"#[A-Z]+-\d+\.\d+$", r["ClaimKey"])}
    see = sum(1 for r in rs if "SEE:" in r["Notes"])
    w(f"| {d} | {len(rs)} | {len(base)} | {see} | {len(split)} | `{sha(os.path.join(PKG, d, d + '_claims.csv'))}` | {len(errata[d])} | {len(rev[d])} |")
tot = sum(len(sealed[d]) for d in DELS); w(f"\nTotal rows: {tot}. Validator: every ledger, reverse and errata file `RESULT PASS errors=0 warnings=0` (re-run by the manager; see STATE.jsonl).\n")
sec = 2
for name, fn in FIELDS:
    if name == "ClaimType": w("## §2 Censuses\n\nSealed value; where it differs, `sealed→errata-applied→corrected` (corrected = errata then `CORRECTIONS.csv`, RUN_BASIS Addendum 3; only census fields are applied — evidence-field corrections do not move these counts, and REACH is counted from ImplementationEvidence as sealed/errata-applied).\n")
    w(f"### {name}\n")
    cs = {d: collections.Counter(v for r in sealed[d] for v in fn(r)) for d in DELS}
    ca = {d: collections.Counter(v for r in applied[d] for v in fn(r)) for d in DELS}
    cc = {d: collections.Counter(v for r in corrected[d] for v in fn(r)) for d in DELS}
    keys = sorted(set().union(*cs.values(), *ca.values(), *cc.values()), key=lambda k: (-sum(cs[d][k] for d in DELS), k))
    def cell(a, b, c): return str(a) if a == b == c else f"{a}→{b}→{c}"
    w("| Value | " + " | ".join(d[4:] for d in DELS) + " | Total |"); w("|---|" + "---:|" * (len(DELS) + 1))
    for k in keys:
        cells = [cell(cs[d][k], ca[d][k], cc[d][k]) for d in DELS]
        w(f"| `{k}` | " + " | ".join(cells) + " | " + cell(*(sum(x[d][k] for d in DELS) for x in (cs, ca, cc))) + " |")
    w("")
sec = 3
w(f"## §{sec} HumanDecisionNeeded — named questions\n")
for q in ["R4-Q1", "R4-Q2", "R4-Q3", "R4"]:
    per = {d: sum(1 for r in applied[d] if q in hdn(r)) for d in DELS}
    w(f"- `{q}`: " + ", ".join(f"{d} {n}" for d, n in per.items()) + f"; total {sum(per.values())} rows")
dec = collections.Counter(v for d in DELS for r in applied[d] for v in hdn(r) if v.startswith("D-"))
w(f"- Decision IDs: " + (", ".join(f"`{k}` {n}" for k, n in sorted(dec.items())) or "none"))
anyh = sum(1 for d in DELS for r in applied[d] if hdn(r) != ["NO"])
w(f"- Rows with any value other than `NO` (errata-applied): {anyh} of {tot}\n")
other = collections.Counter(r["CauseTag"] for d in DELS for r in applied[d] if r["CauseTag"].startswith("OTHER:"))
w(f"- `OTHER:` CauseTags (CONVENTIONS §4 reporting): " + (", ".join(f"`{k}` {n}" for k, n in other.items()) or "none") + "\n")
w("## §4 Errata applied\n")
w("| Deliverable | ClaimKey | Field | Sealed | Proposed |"); w("|---|---|---|---|---|")
for d in DELS:
    for e in errata[d]:
        if e["Field"] in ("Disposition", "CauseTag", "Confidence", "HumanDecisionNeeded", "AuthorityTier", "ClaimType"):
            w(f"| {d} | `{e['ClaimKey']}` | {e['Field']} | `{e['SealedValue']}` | `{e['ProposedValue']}` |")
fc = collections.Counter((d, e["Field"]) for d in DELS for e in errata[d])
w("\nAll errata rows by field: " + "; ".join(f"{d} {f} {n}" for (d, f), n in sorted(fc.items())) + " (evidence-column errata are not tabulated above).\n")
w(f"Non-verdict corrections from verifier shards (`CORRECTIONS.csv`, {len(CORR)} rows): " + "; ".join(f"`{c['ClaimKey']}` {c['Field']}" for c in CORR) + ".\n")
w("## §5 Verifier outcomes\n")
V = []
for p in sorted(glob.glob(os.path.join(PKG, "_verify", "V-SHARD-*.csv"))):
    for r in dicts(p): r["_shard"] = os.path.basename(p)[2:-4]; V.append(r)
w("| Deliverable | Checked | CONFIRMED | REFUTED | CONTESTED | Distinct rows | REFUTED on verdict field (Disposition/Response) | Verdict share | Addendum 3 |")
w("|---|---:|---:|---:|---:|---:|---:|---:|---|")
for d in DELS:
    vs = [v for v in V if v["Unit"] == d]; c = collections.Counter(v["Verdict"] for v in vs)
    key = lambda v: ("REV:" + v["CapabilityID"] + "|" + v["ClaimKey"]) if v["Class"] == "c" else v["ClaimKey"]
    rows = {key(v) for v in vs}; vr = {key(v) for v in vs if v["Verdict"] == "REFUTED" and v["Field"].split(" ")[0] in ("Disposition", "Response")}
    sh = 100 * len(vr) / len(rows) if rows else 0
    w(f"| {d} | {len(vs)} | {c['CONFIRMED']} | {c['REFUTED']} | {c['CONTESTED']} | {len(rows)} | {len(vr)} | {sh:.1f}% | {'RERUN' if sh > 10 else 'pass'} |")
c = collections.Counter(v["Verdict"] for v in V)
w(f"| **Total** | {len(V)} | {c['CONFIRMED']} | {c['REFUTED']} | {c['CONTESTED']} | | | | |\n")
w("Superseded first attempts (DEL-08-01, DEL-08-05) and their verification are under `_ORIGINAL/` and `_verify/_ORIGINAL/`; see VERIFICATION.md §5.\n")
fields = collections.Counter((v["Verdict"], v["Field"]) for v in V if v["Verdict"] != "CONFIRMED")
w("Non-confirmed verdicts by field: " + "; ".join(f"{a} {b} {n}" for (a, b), n in sorted(fields.items())) + "\n")
w("## §6 Capability responses (reverse pass)\n")
w("| Deliverable | Areas | CLAIMED_BY | PARTIAL | NOT_MINE |"); w("|---|---|---:|---:|---:|")
for d in DELS:
    c = collections.Counter(r["Response"] for r in rev[d])
    areas = sorted({r["CapabilityID"].split("-")[1] for r in rev[d]})
    w(f"| {d} | {', '.join(areas)} | {c['CLAIMED_BY']} | {c['PARTIAL']} | {c['NOT_MINE']} |")
claimed = collections.defaultdict(list)
for d in DELS:
    for r in rev[d]:
        if r["Response"] in ("CLAIMED_BY", "PARTIAL"): claimed[r["CapabilityID"]].append(f"{d}:{r['Response'][0]}")
multi = {k: v for k, v in claimed.items() if sum(1 for x in v if x.endswith(":C")) > 1}
w(f"\nCapabilities CLAIMED_BY more than one PKG-08 deliverable: " + (", ".join(f"`{k}` ({', '.join(v)})" for k, v in sorted(multi.items())) or "none"))
w("\nCLAIMED_BY list: " + "; ".join(f"`{r['CapabilityID']}`→`{r['ClaimKey']}`" for d in DELS for r in rev[d] if r["Response"] == "CLAIMED_BY") + "\n")
w("## §7 Provenance\n")
for p in ["EVIDENCE_PACK/PACK_MANIFEST.md", "VERIFICATION.md", "CORRECTIONS.csv", "_verify/SELECTION.csv", "_BRIEFS/PREGATHER_TASK.md", "_BRIEFS/FORWARD_WORKER_TASK.md", "_BRIEFS/VERIFIER_SHARD_TASK.md"]:
    w(f"- `{p}` `{sha(os.path.join(PKG, p))}`")
w("")
if "--hand" in sys.argv:
    w(open(sys.argv[sys.argv.index("--hand") + 1], encoding="utf-8").read().rstrip("\n"))
open(os.path.join(PKG, "PACKAGE_SUMMARY.md"), "w", encoding="utf-8").write("\n".join(out) + "\n")
print("wrote PACKAGE_SUMMARY.md", sha(os.path.join(PKG, "PACKAGE_SUMMARY.md")))
