# Independent first-static candidate review

**Clear for bounded reference/input/selector/criterion selection; no actionable packet finding.** The25-file submitted packet remains byte-identical to its freeze. This is independent review of two new analytical candidates, not target admission, an actual comparison, completed Q1 coverage or solver/native qualification. [FINAL_CHECKED_HASHES.json](FINAL_CHECKED_HASHES.json) records exact scope and hashes.

## Independent mathematical check

[check_candidates.py](check_candidates.py) exited0. It imports neither author generators nor product code. Exact rational free-body polynomials and virtual-work energy integrals independently produce the support actions, sections and nodal displacements/rotations. Polar area integration supplies A/I/J/Z;125-digit AGM supplies pi independently of the author's Machin series. Cauchy–Schwarz supplies the circular normal maximum and its fibers. [SCALAR_BACKCHECK.json](SCALAR_BACKCHECK.json) retains all146 mathematical expectations; [CHECKS.json](CHECKS.json) records the result.

Every one of the73 scalar expectations per case matches through the stored binary64 value and beyond94 relative decimal digits for nonzero high-precision text. Axial has7 prescribed zeros,51 derived zeros and15 nonzero values; combined has7 prescribed zeros,16 derived zeros and50 nonzero values. Two modes would require292 scalar comparisons; none has occurred here.

The annulus has A=0.0019pi, I=0.0000085975pi and J=2I; E200GPa/nu0.25 gives G80GPa. The new E/nu pair is an explicit invented variant, not a hidden carryover of the older NUM material. Exact represented diameter/wall operand differences change these geometric properties by at most about1.93e-16 relative for the checked expressions, well below the proposed1e-9 field comparison. This is an input-rounding comparison, not a product error bound.

Root support is(-1000,0,0;0,0,0) for axial and(0,-30,40;-20,-80,-60) for combined. The i-end node-on-element row is the negative cut action; interiors and j-end use the positive cut. Stress uses the cut at both ends. Right-handed y/z rotation signs and mm/rad publication agree. The combined support moment norm includes torque, while its normal peak uses the100N*m bending resultant alone:370235.4012024317Pa at root. Torsional shear is37023.54012024317Pa and remains separate. The root's opposite fibers(-0.06,+0.08)m and(+0.06,-0.08)m tie in absolute normal stress. The axial peak167531.51904410035Pa ties at every station/fiber. Tip translation magnitudes are0.0016753151904410036mm and0.024682360080162115mm respectively.

The EB/circular Saint-Venant model, five stations, local/global alignment and small-displacement assumptions are explicit. This two-metre member is a mathematical model verification case; it does not establish negligible real shear deformation. Missing transverse-shear stress distribution and direct signed circumferential-extrema rows remain explicit output obligations. They are neither invented selectors nor asserted zero, and these cases confer no full3D/equivalent-stress pass.

## Inputs, selectors and structural obligations

All146 selectors have correct unique public IDs, units, entities, case basis, frame/location/sign metadata and ordinary physics-1 semantic signatures. The single-case ID qualification route, byte-length support/maximum IDs and endpoint/station spelling agree with the inspected facade. True absent metadata for the two displacement magnitudes is preserved as an adapter requirement. Actual ordinary fixture values were not used as analytical targets.

Both exact-pressure/model0.3 requests describe precisely the checked two-node/one-member/one-anchor/one-case systems with empty pressure regions, no extra components/loads or shear-modulus override. RunnerRequest fields and the final global_x/global_y/global_z/rotation_x vocabulary agree with the inspected CLI path. Earlier invalid draft tokens were corrected before execution and their provenance remains recorded. The pending-review provenance is truthful; selection/status changes must create newly bound input bytes.

[STRUCTURAL_BACKCHECK.json](STRUCTURAL_BACKCHECK.json) covers all ten required obligations for each case: transport/mode, input custody, ordinary contract, material/section completeness, numerical standing, unique scalar coverage, coefficient-only extrema enclosure, governing location and both summary bindings. This is20 prospective checks per mode,40 for four eventual executions. No new output is present, so these are required designs, not successful observations. The thin gate still needs explicit raw0.2/physics-1/mode/absent-metadata and structural-check implementation and review. A matching result kind cannot admit a composite/source-method envelope under these ordinary selectors.

## Criterion recommendation and limits

Recommend the exact submitted per-case criteria: nonzeros use abs(observed−reference)<=1e-9*max(abs(observed),abs(reference)) in the same unit with no absolute floor; prescribed root DOFs/magnitude use exact finite numeric zero with either zero sign; other exact analytical zeros use1e-9 times the precomputed case/dimension scale, no relative term. All rule families, units, dimensions, scale values and assignments match. Independent2×budget perturbations exceed the proposed limits; missing/duplicate rows and categorical sign/unit/identity mismatches must still fail in the future adapter. These controls check the proposed predicate, not an executed gate.

The criteria are reasonable bounded development comparisons for these two moderate represented-input cases. They do not weaken an inherited assertion, activate a universal release tolerance, replace the source method's1e-9 contract, or prove forward accuracy from numerical standing. Compare the independently computed normal value separately from the producer's coefficient-only enclosure; do not demand that an ideal-decimal oracle lie inside that narrower enclosure. Summary values/references must retain exact raw-row binding.

The reused NUMERICAL_REFERENCE/STRESS_REFERENCE and preparation/oracle hashes match their recorded origins. Historical preparation was not policy activation; this review independently checks the reused mathematics without reselecting unrelated numerical policy. The authors' generator/checker bodies were inspected but never executed as independent proof. Actual build/output pairs, four case-mode executions, all required physical observations, frozen adapter qualification and explicit checked-package selection remain outstanding. No observed result, successful profile or new native claim was fabricated.

Reviewer `/root/numerical_resume/n05_admission` remains TASK under original parent `/root/numerical_resume`, with this direct Root cross-manager assignment. No delegation. I authored neither candidate packet nor its generators. Earlier receipt implementation is separate and is not independently reviewed here. Only this INDEPENDENT_REVIEW directory was written; no product/gate/source edit, solver/build/native/deck/network execution or Git mutation occurred. [PROVENANCE.json](PROVENANCE.json) records actual instruction and source origins.
