from pathlib import Path
import json,hashlib,subprocess,datetime
repo=Path('/private/tmp/chirality-app-runtime-integration-20260906-738-49951af');out=Path(__file__).resolve().parent;original=out.parents[3];app=repo/'projects/chirality-app-dev';front=app/'frontend'
before=json.loads((out/'TRACKED_BEFORE.json').read_text());after={p:hashlib.sha256((repo/p).read_bytes()).hexdigest() for p in before};assert before==after
status=subprocess.check_output(['git','status','--porcelain'],cwd=repo,text=True);assert not status,status
(out/'PRESERVATION.json').write_text(json.dumps({'head':subprocess.check_output(['git','rev-parse','HEAD'],cwd=repo,text=True).strip(),'tracked_file_count':len(before),'tracked_hashes_match':True,'git_status_porcelain':status,'source_mutations_by_validator':[]},indent=2)+'\n')
files=['projects/chirality-runtime/package.json','projects/chirality-runtime/package-lock.json','projects/chirality-app-dev/frontend/package.json','projects/chirality-app-dev/frontend/package-lock.json','projects/chirality-app-dev/frontend/tsconfig.electron.json','projects/chirality-app-dev/frontend/dist-electron/main.js','projects/chirality-app-dev/frontend/dist-electron/preload.js','projects/chirality-app-dev/frontend/dist-runtime/chirality-cli.mjs','.github/workflows/harness-premerge.yml','projects/chirality-app-dev/chirality.project.json']
ids={p:hashlib.sha256((repo/p).read_bytes()).hexdigest() for p in files}
dist={str(p.relative_to(repo)):hashlib.sha256(p.read_bytes()).hexdigest() for folder in (repo/'projects/chirality-runtime/packages').glob('*/dist') for p in folder.rglob('*') if p.is_file()}
(out/'INPUT_AND_BUILD_IDENTITIES.json').write_text(json.dumps({'identities':ids,'runtime_dist':dist,'node_version':subprocess.check_output(['node','--version'],text=True).strip(),'npm_version':subprocess.check_output(['npm','--version'],text=True).strip(),'electron_package_version':json.loads((front/'node_modules/electron/package.json').read_text())['version']},indent=2)+'\n')
(out/'RUNTIME_RELAY_PROMPT.md').write_text("""Please inspect this completed App/Runtime integration validation before deciding your next Runtime action.

Immutable local validation commit: 22a65b694007f4d96d33631cf33c2d611517a417, at /private/tmp/chirality-app-runtime-integration-20260906-738-49951af. Parent is published PR #738 head 49951af6237bbb8701c0a2cebcd8c30fbde75b8e; the only additional file is projects/chirality-app-dev/frontend/tsconfig.electron.json, SHA-256 522b114f541f6b4882404069f6b4ca5553f887635948df972c07bbbed849f5b0, implementing the owner-approved D124 declaration-resolution repair. This validates PR738's actual complete source composition plus that config, not just a selected CJS excerpt. No current seven-file shell improvements were included. No merge or publication occurred.

Evidence: /Users/ryan/.codex/worktrees/85d6/chirality/projects/chirality-app-dev/execution/_Coordination/AgentRuns/APP_SHELL_RESUME_2026-09-06/pkg09/combined-integration-v1/

Results: exact-lock Runtime npm ci/build and App npm ci passed. Fresh independent composition review PASS. App typecheck/build, APP-HOLD, harness self-check and pytest passed. Vitest passed 1,730 tests with 4 skips after removing agent-only CHIRALITY_INSTRUCTION_ROOT from the product-test environment to match CI; the prior single environment assertion failure is preserved. Electron daemon startup succeeded under normal macOS safeguards, isolated project registration succeeded, session-list API returned200, and configured stub-provider premerge passed all8 cases. Owned frontend/daemon exited0; socket and disposable credentials/runtime directory were removed. All70,832 tracked files preserved; isolated Git status clean.

The original missing-binding503 and ERR_PACKAGE_PATH_NOT_EXPORTED failures remain historical. This combined result establishes the isolated headless consumer integration; it does not claim full GUI/shell, live-provider, packaging/release or login proof. Runtime's own full validation/acceptance and PR adoption remain with their existing owners. Before relying on Runtime again, fetch origin/main and coordinate any changed basis; do not silently alter the immutable validation snapshot or concurrent dirty App worktree. Please report whether this consumer evidence satisfies your CJS integration concern and identify any concrete remaining Runtime-side requirement. This prompt itself authorizes no source edits, publication or merge.
""")
(out/'RETURN.md').write_text("""# Isolated combined integration — PASS with bounded scope

Immutable head22a65b694007f4d96d33631cf33c2d611517a417 combines published PR73849951af6237bbb8701c0a2cebcd8c30fbde75b8e with only D124 App compiler config. Original seven shell-source changes are absent. This is an isolated validation snapshot, not publication/adoption or whole-shell acceptance.

Runtime npmci/build, App npmci, typecheck/build, APP-HOLD, harness selfcheck and pytest PASS. Final frontend-test CI-env result: 1,730passed4skipped,177filespassed1skipped. Fresh read-only source composition reviewer /root/resume_pkg09/combined_review PASS over actual production/configuration composition. Historical Runtime evidence was not independently re-audited or substituted for Runtime owner's acceptance.

Actual normal-safeguard macOS Electron daemon started, isolated project registration succeeded using truthful owner-authorized provenance, session-list API200, configured stub-provider premerge8/8PASS. No userdaemon, liveprovider, LaunchAgent or GUI proof was used. Daemon/frontend exited0; socket absent before disposable directory removal, all temporary token/credential bytes removed, port connection refused61. All70,832 tracked identities preserved and Gitstatus clean.

Two evidence/fixture corrections are preserved: first registered runner completed commands but failed final report output containment, so no results claimed from it; report path moved to isolated ignored artifacts and copied unchanged. The retained registered report then showed one Vitest fixture failure because agent-only CHIRALITY_INSTRUCTION_ROOT entered the product environment; the registered test alone reran with that variable omitted, matching CI, and passed. No code or assertion changed. Original report remains FAIL; final individual checks are combined from retained exact-source results. Parent authorized this correction. No repeated install/build beyond the evidence-report rerun.

Evidence is derivative of explicit parent v11/ownersteerv5 and immutable Git composition. No authoritative snapshot/pointer/lifecycle/dependency change. Native execution is instruction-asserted; parent explicitly supplied instruction root, exact model unavailable (reviewer reports GPT6 family only). Commands, environments, canonical logs, input/build hashes, preserved failures and cleanup are retained. Token values were never logged; only public token-file paths retained. A1 future login proof and all original-shell gates remain separate. Rerun on changed source/config/declarations or dependency versions; fetch origin/main before Runtime reliance.

Runtime handoff is RUNTIME_RELAY_PROMPT.md, for the user to copy manually. No inter-task message sent. No additional repair, live deliverable-state update, commit, push, PR or merge performed by this validator.
""")
paths=[p for p in out.rglob('*') if p.is_file() and p.name!='OUTPUT_MANIFEST.json'];manifest={str(p.relative_to(out)):{'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size} for p in sorted(paths)}
(out/'OUTPUT_MANIFEST.json').write_text(json.dumps({'head':'22a65b694007f4d96d33631cf33c2d611517a417','status':'BOUNDED_COMPOSITION_PASS','files':manifest},indent=2)+'\n')
for n in ['RETURN.md','OUTPUT_MANIFEST.json','RUNTIME_RELAY_PROMPT.md']:print(n,hashlib.sha256((out/n).read_bytes()).hexdigest())
print('manifestmembers',len(paths),'runtime-dist-files',len(dist))
