#!/usr/bin/env python3
"""D-PEC-96 bound act: PEC loop-registry schema v2 with closed feed profiles.

Writes exactly the pinned postimages of the ruled option into
projects/pec/ of the repository given by --repo, after checking every pinned
preimage and every must-remain file. Writes nothing and exits 1 on any
failure, including a second run. Stdlib only.

  python3 apply_d96.py --repo <REPO_ROOT> [--pec-row migrated|remaining] [--check-only]

--pec-row migrated (default) is option A; --pec-row remaining is option A-R.
--check-only runs every check and reports without writing.
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import sys
from pathlib import Path

PEC = Path("projects/pec")

PREIMAGES = {
    'v2/config/loops.json': '4ce07ad061abd222acabb2afe0f619fdc840b4cc11d31e49f1dff8fcc299d32e',
    'v2/config/loops.schema.json': '1f4d1f0cf9abe5754ebb4260f588dea0d71e7f3cc37af2487b30b9c4aa39ba9b',
    'v2/src/pec_v2/core/ports/loop_registry.py': '3d5862bef122af27d61883fe5542b80daefb3418bccfba31486e4d60289b3662',
    'v2/src/pec_v2/core/ports/__init__.py': '669e1569216722509dcea0ae5ed42dc4a0ca856a196676568ee78d7a38a1edeb',
    'v2/src/pec_v2/core/__init__.py': '33c54e244e8e19b66cb2c53c81fa747979f6d512f227f7a56e3f8d57cfb9ff4a',
    'v2/src/pec_v2/adapters/config/loop_registry.py': '7101740dea837e6077e048ec2a8ef8600c7d1014bd339915aaea285b8236eb2f',
    'v2/tests/config/test_json_loop_registry.py': 'd7efb486287d3703aa9ea007eb5376eba95689286bb322c887eeca8b193ac956',
    'v2/tests/config/test_loop_registry_contract.py': '49b2f6a3b5088bceb82dc393cce050b8800af3a5ac5d34b3b6a3d7b71c01111b',
    'v2/tests/config/fixtures/duplicate_loop_id.json': '2e65c719af6c9eb7e170fb25d437b928847dc8d617c056093de213673b3e3396',
    'v2/tests/config/fixtures/missing_loop_id.json': '2155849d9419f0239dca7a69d919ca9ee46a6434106d5326d85bc8c70afc5257',
    'v2/tests/config/fixtures/schema_version_1.json': None,
}
UNCHANGED = {
    'v2/tests/config/fixtures/malformed.json': 'f37303491c50fa74756f547929f09c99900abfad5a9310cc2b46beb5027425b0',
    'v2/src/pec_v2/adapters/config/__init__.py': '7a9bdbc59b96d3c9f306af483d18d6c0b23b7071481fd6ab79204ba398513cba',
    'v2/src/pec_v2/adapters/__init__.py': '8c80e607671eef1a35dca0334503deb151418c03b618af0c4577514d0184ef22',
    'v2/src/pec_v2/__init__.py': 'ae46d431c13413d5bcbb6ab60a97f6db09510dd97903c1f2a8586a3567b17c1e',
    'software-workflow.json': '8ec9ba6dcba7ea6b935923f5b4d846b2a9ac3f3d5cc43f5e160abe0971058a8b',
    'v2/config/service_core_posture.json': '20d64ff38122fa2f7b4bbe6478e42450ce6f9c8b03dc91c90b5095393ef309ed',
}
POSTIMAGES_A = {
    'v2/config/loops.json': 'aad704700748055e8f5cc1ec0c4f3a29c000c775994e1280dcf651952094678e',
    'v2/config/loops.schema.json': '27b8ff110c07bbba67b17ce98955db9e665f67b55cff92cbe3a34011800f04ce',
    'v2/src/pec_v2/core/ports/loop_registry.py': 'a509bfb74920172a86ac21aff6a67245cd3248c5d73ef4e7427966069099c8a9',
    'v2/src/pec_v2/core/ports/__init__.py': 'e44bf7f00c8ef2cfa5f8006ef2834feb020063df63a3b4b8d8cbd8f359174ff7',
    'v2/src/pec_v2/core/__init__.py': '0e699a54d6bc202ff7a90c25fdb355da5ed2db185709c3a399870c1b0309c42d',
    'v2/src/pec_v2/adapters/config/loop_registry.py': '4fc4bbf72e2b0cc7507a020fe4cce93c793ab2d5b65f2cc6dbbc2db2c6328ad4',
    'v2/tests/config/test_json_loop_registry.py': 'd410afa5a32d4fd11384a4960b1ea28352f3f930f8902488e28b46d392dc3fae',
    'v2/tests/config/test_loop_registry_contract.py': 'b05ed8719c59258998b1c483456b66bd8d4a4d3bc4f68cdd6fb5c02541db7106',
    'v2/tests/config/fixtures/duplicate_loop_id.json': '6875f50023f1ad34a45c1af4b0a65316260c45aa05562ce45bb2d9bd8fd13c7e',
    'v2/tests/config/fixtures/missing_loop_id.json': 'f4255b2483a014b542fb7f25c4314ff75dabb5cebbcfe751a2ad3df425f29598',
    'v2/tests/config/fixtures/schema_version_1.json': '4ce07ad061abd222acabb2afe0f619fdc840b4cc11d31e49f1dff8fcc299d32e',
}
POSTIMAGES_AR = {
    'v2/config/loops.json': '6e1321e32f72b0fc9f9d987a3175266550a23fa40230df0a61418cfccd4c7961',
    'v2/config/loops.schema.json': '27b8ff110c07bbba67b17ce98955db9e665f67b55cff92cbe3a34011800f04ce',
    'v2/src/pec_v2/core/ports/loop_registry.py': 'a509bfb74920172a86ac21aff6a67245cd3248c5d73ef4e7427966069099c8a9',
    'v2/src/pec_v2/core/ports/__init__.py': 'e44bf7f00c8ef2cfa5f8006ef2834feb020063df63a3b4b8d8cbd8f359174ff7',
    'v2/src/pec_v2/core/__init__.py': '0e699a54d6bc202ff7a90c25fdb355da5ed2db185709c3a399870c1b0309c42d',
    'v2/src/pec_v2/adapters/config/loop_registry.py': '4fc4bbf72e2b0cc7507a020fe4cce93c793ab2d5b65f2cc6dbbc2db2c6328ad4',
    'v2/tests/config/test_json_loop_registry.py': '586fcd5ead4bbb19e76a125da972910ea1e93a610b2d74758fcfd7fb89a6ee01',
    'v2/tests/config/test_loop_registry_contract.py': 'b05ed8719c59258998b1c483456b66bd8d4a4d3bc4f68cdd6fb5c02541db7106',
    'v2/tests/config/fixtures/duplicate_loop_id.json': '6875f50023f1ad34a45c1af4b0a65316260c45aa05562ce45bb2d9bd8fd13c7e',
    'v2/tests/config/fixtures/missing_loop_id.json': 'f4255b2483a014b542fb7f25c4314ff75dabb5cebbcfe751a2ad3df425f29598',
    'v2/tests/config/fixtures/schema_version_1.json': '4ce07ad061abd222acabb2afe0f619fdc840b4cc11d31e49f1dff8fcc299d32e',
}
BLOBS = {
    '0e699a54d6bc202ff7a90c25fdb355da5ed2db185709c3a399870c1b0309c42d': (
        'IiIiUEVDLW93bmVkIGRvbWFpbiBhbmQgYXBwbGljYXRpb24gY29udHJhY3RzLiIiIgoKZnJvbSAu'
        'cG9ydHMubG9vcF9yZWdpc3RyeSBpbXBvcnQgRmVlZFByb2ZpbGUsIEZlZWRQcm9maWxlU3RhdGUs'
        'IExvb3BSZWdpc3RyeSwgUmVnaXN0ZXJlZExvb3AKCl9fYWxsX18gPSBbIkZlZWRQcm9maWxlIiwg'
        'IkZlZWRQcm9maWxlU3RhdGUiLCAiTG9vcFJlZ2lzdHJ5IiwgIlJlZ2lzdGVyZWRMb29wIl0K'
    ),
    '27b8ff110c07bbba67b17ce98955db9e665f67b55cff92cbe3a34011800f04ce': (
        'ewogICIkaWQiOiAiaHR0cHM6Ly9jaGlyYWxpdHkubG9jYWwvcGVjL3YyL2NvbmZpZy9sb29wcy5z'
        'Y2hlbWEudjIuanNvbiIsCiAgIiRzY2hlbWEiOiAiaHR0cHM6Ly9qc29uLXNjaGVtYS5vcmcvZHJh'
        'ZnQvMjAyMC0xMi9zY2hlbWEiLAogICJhZGRpdGlvbmFsUHJvcGVydGllcyI6IGZhbHNlLAogICJk'
        'ZXNjcmlwdGlvbiI6ICJMb2NhbCBjb25maWd1cmF0aW9uIGZvcm1hdCBuYW1pbmcgdGhlIGxvb3Bz'
        'IFBFQyBzZXJ2ZXMgYW5kIHRoZSBjbG9zZWQsIFBFQy12ZXJzaW9uZWQgZmVlZCBwcm9maWxlcyBQ'
        'RUMgcmVhZHMgZWFjaCBsb29wIHdpdGguIFNjaGVtYSB2ZXJzaW9uIDEgaXMgbm90IGFjY2VwdGVk'
        'IGJ5IHRoZSB2ZXJzaW9uLTIgbG9hZGVyLiIsCiAgInByb3BlcnRpZXMiOiB7CiAgICAibG9vcHMi'
        'OiB7CiAgICAgICJkZXNjcmlwdGlvbiI6ICJUaGUgY29uZmlndXJlZCBsb29wcyBQRUMgbWF5IHJl'
        'YWQgYXMgbm9uLWF1dGhvcml0YXRpdmUgZmlsZS10cnV0aCBsb2NhdGlvbnMuIiwKICAgICAgIml0'
        'ZW1zIjogewogICAgICAgICJhZGRpdGlvbmFsUHJvcGVydGllcyI6IGZhbHNlLAogICAgICAgICJw'
        'cm9wZXJ0aWVzIjogewogICAgICAgICAgImZlZWRfcHJvZmlsZXMiOiB7CiAgICAgICAgICAgICJk'
        'ZXNjcmlwdGlvbiI6ICJUaGUgZmVlZCBwcm9maWxlcyBQRUMgYXBwbGllcyB0byB0aGlzIGxvb3A6'
        'IFBFQydzIHJlYWRpbmcgaHlwb3RoZXNpcywgbmV2ZXIgdGhlIGxvb3AncyB0cnV0aC4gQXQgbGVh'
        'c3Qgb25lIGVudHJ5IGFuZCBhdCBsZWFzdCBvbmUgbGl2ZSBlbnRyeTsgYSBwcm9maWxlIGlkZW50'
        'aWZpZXIgYXBwZWFycyBhdCBtb3N0IG9uY2UgcGVyIGxvb3AsIGFuZCB0aGUgcHJvZmlsZXMgb24g'
        'b25lIGxvb3AgY292ZXIgcGFpcndpc2UtZGlzam9pbnQgc3VyZmFjZXMsIHNvIG5vIHN1cmZhY2Ug'
        'aXMgcmVhZCB1bmRlciB0d28gZ3JhbW1hcnMgb3IgZGVjbGFyZWQgYm90aCBsaXZlIGFuZCBoaXN0'
        'b3JpY2FsLiIsCiAgICAgICAgICAgICJpdGVtcyI6IHsKICAgICAgICAgICAgICAiYWRkaXRpb25h'
        'bFByb3BlcnRpZXMiOiBmYWxzZSwKICAgICAgICAgICAgICAicHJvcGVydGllcyI6IHsKICAgICAg'
        'ICAgICAgICAgICJiYXNpcyI6IHsKICAgICAgICAgICAgICAgICAgImRlc2NyaXB0aW9uIjogIkNp'
        'dGF0aW9uIHRvIHRoZSBsb29wJ3Mgb3duIHJlY29yZCB0aGF0IHN1cHBvcnRzIHRoaXMgZGVjbGFy'
        'YXRpb24uIE5vcm1hbGl6ZWQgcmVwb3NpdG9yeS1yZWxhdGl2ZSBwYXRoIChubyBsZWFkaW5nICcv'
        'Jywgbm8gJy4uJyBzZWdtZW50LCBubyBiYWNrc2xhc2gpLiIsCiAgICAgICAgICAgICAgICAgICJt'
        'aW5MZW5ndGgiOiAxLAogICAgICAgICAgICAgICAgICAidHlwZSI6ICJzdHJpbmciCiAgICAgICAg'
        'ICAgICAgICB9LAogICAgICAgICAgICAgICAgInByb2ZpbGUiOiB7CiAgICAgICAgICAgICAgICAg'
        'ICJkZXNjcmlwdGlvbiI6ICJJZGVudGlmaWVyIGZyb20gUEVDJ3MgY2xvc2VkIGZlZWQtcHJvZmls'
        'ZSB2b2NhYnVsYXJ5LiBFYWNoIG9wdGlvbiBlbmRzIHdpdGggdGhlIHN1cmZhY2VzIGl0IGNvdmVy'
        'cy4gUGF0aCBjb252ZW50aW9ucyBhbmQgZ3JhbW1hcnMgZm9yIGVhY2ggcHJvZmlsZSBsaXZlIGlu'
        'IFBFQydzIGFkYXB0ZXJzLiIsCiAgICAgICAgICAgICAgICAgICJvbmVPZiI6IFsKICAgICAgICAg'
        'ICAgICAgICAgICB7CiAgICAgICAgICAgICAgICAgICAgICAiY29uc3QiOiAiYWdlbnRydW5zLWpz'
        'b24iLAogICAgICAgICAgICAgICAgICAgICAgImRlc2NyaXB0aW9uIjogIkpTT04gcnVuIGV2aWRl'
        'bmNlIGFueXdoZXJlIHVuZGVyIHRoZSBsb29wJ3MgZXhlY3V0aW9uLyB0cmVlIChXT1JLX0dSQVBI'
        'Lmpzb24sIFNUQVRVUy5qc29uLCBSVU5USU1FX1NVTU1BUlkuanNvbiksIGluY2x1ZGluZyBBZ2Vu'
        'dFJ1bnMvIGFuZCBkZWxpdmVyYWJsZSBfcnVuX3JlY29yZHMvOyB0aGUgaWRlbnRpZmllciBrZWVw'
        'cyBpdHMgU0NBLTAwNSBuYW1lLiBTdXJmYWNlczoganNvbi1ydW4tZXZpZGVuY2UuIgogICAgICAg'
        'ICAgICAgICAgICAgIH0sCiAgICAgICAgICAgICAgICAgICAgewogICAgICAgICAgICAgICAgICAg'
        'ICAgImNvbnN0IjogImxvb3AtcmVjZWlwdHMtbGVkZ2VyIiwKICAgICAgICAgICAgICAgICAgICAg'
        'ICJkZXNjcmlwdGlvbiI6ICJUaGUgbG9vcCdzIGxvb3AvTE9PUF9SRUNFSVBUUy5tZCByZWNlaXB0'
        'IGxlZGdlciwgdW5kZXIgdGhhdCBsb29wJ3MgZ3JhbW1hci4gU3VyZmFjZXM6IHJlY2VpcHQtbGVk'
        'Z2VyLiIKICAgICAgICAgICAgICAgICAgICB9LAogICAgICAgICAgICAgICAgICAgIHsKICAgICAg'
        'ICAgICAgICAgICAgICAgICJjb25zdCI6ICJyZW1haW5pbmctaXRlbXMiLAogICAgICAgICAgICAg'
        'ICAgICAgICAgImRlc2NyaXB0aW9uIjogIlRoZSAnIyMgUmVtYWluaW5nJyBzZWN0aW9ucyBvZiB0'
        'aGUgbG9vcCdzIF9TVEFUVVMubWQgZmlsZXMsIHJlYWQgYXMgZGVsaXZlcmFibGUtbG9jYWwgcmVj'
        'b3JkcyBvZiBvcGVuIHNjb3BlIHdpdGggdGhlaXIgZ2F0ZSBtYXJrZXJzLCBuZXZlciBhcyBhIHdv'
        'cmstc2VsZWN0aW9uIHNpZ25hbC4gU3VyZmFjZXM6IHN0YXR1cy1yZW1haW5pbmcuIgogICAgICAg'
        'ICAgICAgICAgICAgIH0sCiAgICAgICAgICAgICAgICAgICAgewogICAgICAgICAgICAgICAgICAg'
        'ICAgImNvbnN0IjogInJlbWFpbmluZy1sb29wIiwKICAgICAgICAgICAgICAgICAgICAgICJkZXNj'
        'cmlwdGlvbiI6ICJMb29wcyB0aGF0IHNlbGVjdCB3b3JrIGZyb20gX1NUQVRVUy5tZCAnIyMgUmVt'
        'YWluaW5nJyBpdGVtczogbGlmZWN5Y2xlIHdpdGggdGhvc2UgaXRlbXMsIHRoZSBsb29wL0xPT1Bf'
        'UkVDRUlQVFMubWQgbGVkZ2VyIGFzIHRoZSByZWNlaXB0IGZlZWQsIGRlcGVuZGVuY3kgcmVnaXN0'
        'ZXJzIGFuZCBkZWNpc2lvbiByZWdpc3RlcnMuIFN1cmZhY2VzOiBkZWNpc2lvbi1yZWdpc3RlcnMs'
        'IGRlcGVuZGVuY3ktcmVnaXN0ZXJzLCByZWNlaXB0LWxlZGdlciwgc3RhdHVzLWxpZmVjeWNsZSwg'
        'c3RhdHVzLXJlbWFpbmluZy4iCiAgICAgICAgICAgICAgICAgICAgfSwKICAgICAgICAgICAgICAg'
        'ICAgICB7CiAgICAgICAgICAgICAgICAgICAgICAiY29uc3QiOiAic2hhcmVkLWRldi1sb29wIiwK'
        'ICAgICAgICAgICAgICAgICAgICAgICJkZXNjcmlwdGlvbiI6ICJUaGUgc2hhcmVkIGRldmVsb3Bt'
        'ZW50LWxvb3AgbWV0aG9kOiB1bmRlcnRha2luZyB3b3JrIGdyYXBocyAoZXhlY3V0aW9uL19Db29y'
        'ZGluYXRpb24vV29ya0dyYXBocy88dW5kZXJ0YWtpbmc+L1dPUktfR1JBUEgubWQpLCBjZW50cmFs'
        'IHJlY2VpcHRzIChleGVjdXRpb24vX0Nvb3JkaW5hdGlvbi9BZ2VudFJ1bnMvPFJ1bklEPi9SRUNF'
        'SVBULm1kKSwgdGhlIGRlbGl2ZXJhYmxlIE1FTU9SWS5tZCBydW4gaW5kZXgsIF9TVEFUVVMubWQg'
        'bGlmZWN5Y2xlLCBkZXBlbmRlbmN5IHJlZ2lzdGVycyBhbmQgZGVjaXNpb24gcmVnaXN0ZXJzLiBT'
        'dXJmYWNlczogY2VudHJhbC1yZWNlaXB0cywgZGVjaXNpb24tcmVnaXN0ZXJzLCBkZXBlbmRlbmN5'
        'LXJlZ2lzdGVycywgbWVtb3J5LXJ1bi1pbmRleCwgc3RhdHVzLWxpZmVjeWNsZSwgd29yay1ncmFw'
        'aHMuIgogICAgICAgICAgICAgICAgICAgIH0KICAgICAgICAgICAgICAgICAgXSwKICAgICAgICAg'
        'ICAgICAgICAgInR5cGUiOiAic3RyaW5nIgogICAgICAgICAgICAgICAgfSwKICAgICAgICAgICAg'
        'ICAgICJzdGF0ZSI6IHsKICAgICAgICAgICAgICAgICAgImRlc2NyaXB0aW9uIjogImxpdmU6IHRo'
        'ZSBsb29wIGN1cnJlbnRseSB3cml0ZXMgdGhpcyBnZW5lcmF0aW9uLiBoaXN0b3JpY2FsOiB0aGUg'
        'Z2VuZXJhdGlvbiBpcyBmcm96ZW4sIGFuZCBpdHMgc2lsZW5jZSBpcyBuZXZlciByZXBvcnRlZCBh'
        'cyBzdGFsZW5lc3MuIiwKICAgICAgICAgICAgICAgICAgImVudW0iOiBbCiAgICAgICAgICAgICAg'
        'ICAgICAgImhpc3RvcmljYWwiLAogICAgICAgICAgICAgICAgICAgICJsaXZlIgogICAgICAgICAg'
        'ICAgICAgICBdLAogICAgICAgICAgICAgICAgICAidHlwZSI6ICJzdHJpbmciCiAgICAgICAgICAg'
        'ICAgICB9LAogICAgICAgICAgICAgICAgInZlcnNpb24iOiB7CiAgICAgICAgICAgICAgICAgICJj'
        'b25zdCI6IDEsCiAgICAgICAgICAgICAgICAgICJkZXNjcmlwdGlvbiI6ICJWZXJzaW9uIG9mIHRo'
        'ZSBzZWxlY3RlZCBwcm9maWxlOyBldmVyeSBwcm9maWxlIGluIHRoaXMgdm9jYWJ1bGFyeSBpcyBh'
        'dCB2ZXJzaW9uIDEuIiwKICAgICAgICAgICAgICAgICAgInR5cGUiOiAiaW50ZWdlciIKICAgICAg'
        'ICAgICAgICAgIH0KICAgICAgICAgICAgICB9LAogICAgICAgICAgICAgICJyZXF1aXJlZCI6IFsK'
        'ICAgICAgICAgICAgICAgICJiYXNpcyIsCiAgICAgICAgICAgICAgICAicHJvZmlsZSIsCiAgICAg'
        'ICAgICAgICAgICAic3RhdGUiLAogICAgICAgICAgICAgICAgInZlcnNpb24iCiAgICAgICAgICAg'
        'ICAgXSwKICAgICAgICAgICAgICAidHlwZSI6ICJvYmplY3QiCiAgICAgICAgICAgIH0sCiAgICAg'
        'ICAgICAgICJtaW5JdGVtcyI6IDEsCiAgICAgICAgICAgICJ0eXBlIjogImFycmF5IgogICAgICAg'
        'ICAgfSwKICAgICAgICAgICJsb29wX2lkIjogewogICAgICAgICAgICAiZGVzY3JpcHRpb24iOiAi'
        'U3RhYmxlIGxvd2VyLWNhc2UgaWRlbnRpZmllciBmb3Igb25lIGNvbmZpZ3VyZWQgbG9vcC4iLAog'
        'ICAgICAgICAgICAibWluTGVuZ3RoIjogMSwKICAgICAgICAgICAgInBhdHRlcm4iOiAiXlthLXpd'
        'W2EtejAtOS1dKiQiLAogICAgICAgICAgICAidHlwZSI6ICJzdHJpbmciCiAgICAgICAgICB9LAog'
        'ICAgICAgICAgImxvb3BfaW5pdF9wYXRoIjogewogICAgICAgICAgICAiZGVzY3JpcHRpb24iOiAi'
        'UmVwb3NpdG9yeS1yZWxhdGl2ZSBwYXRoIHRvIHRoZSBsb29wJ3MgZ292ZXJuZWQgTE9PUF9JTklU'
        'Lm1kIHN1cmZhY2UuIiwKICAgICAgICAgICAgIm1pbkxlbmd0aCI6IDEsCiAgICAgICAgICAgICJ0'
        'eXBlIjogInN0cmluZyIKICAgICAgICAgIH0KICAgICAgICB9LAogICAgICAgICJyZXF1aXJlZCI6'
        'IFsKICAgICAgICAgICJmZWVkX3Byb2ZpbGVzIiwKICAgICAgICAgICJsb29wX2lkIiwKICAgICAg'
        'ICAgICJsb29wX2luaXRfcGF0aCIKICAgICAgICBdLAogICAgICAgICJ0eXBlIjogIm9iamVjdCIK'
        'ICAgICAgfSwKICAgICAgIm1pbkl0ZW1zIjogMSwKICAgICAgInR5cGUiOiAiYXJyYXkiCiAgICB9'
        'LAogICAgInNjaGVtYV92ZXJzaW9uIjogewogICAgICAiY29uc3QiOiAyLAogICAgICAiZGVzY3Jp'
        'cHRpb24iOiAiVmVyc2lvbiBvZiB0aGlzIGxvY2FsIGxvb3AtcmVnaXN0cnkgY29uZmlndXJhdGlv'
        'biBmb3JtYXQuIiwKICAgICAgInR5cGUiOiAiaW50ZWdlciIKICAgIH0KICB9LAogICJyZXF1aXJl'
        'ZCI6IFsKICAgICJzY2hlbWFfdmVyc2lvbiIsCiAgICAibG9vcHMiCiAgXSwKICAidGl0bGUiOiAi'
        'UEVDIGxvY2FsIGxvb3AgcmVnaXN0cnkgY29uZmlndXJhdGlvbiB2MiIsCiAgInR5cGUiOiAib2Jq'
        'ZWN0Igp9Cg=='
    ),
    '4ce07ad061abd222acabb2afe0f619fdc840b4cc11d31e49f1dff8fcc299d32e': (
        'ewogICJsb29wcyI6IFsKICAgIHsKICAgICAgImxvb3BfaWQiOiAicGVjIiwKICAgICAgImxvb3Bf'
        'aW5pdF9wYXRoIjogInByb2plY3RzL3BlYy9sb29wL0xPT1BfSU5JVC5tZCIKICAgIH0KICBdLAog'
        'ICJzY2hlbWFfdmVyc2lvbiI6IDEKfQo='
    ),
    '4fc4bbf72e2b0cc7507a020fe4cce93c793ab2d5b65f2cc6dbbc2db2c6328ad4': (
        'IiIiSlNPTi1iYWNrZWQgYWRhcHRlciBmb3IgdGhlIGNvcmUtb3duZWQgbG9vcC1yZWdpc3RyeSBw'
        'b3J0LiIiIgoKZnJvbSBfX2Z1dHVyZV9fIGltcG9ydCBhbm5vdGF0aW9ucwoKaW1wb3J0IGpzb24K'
        'aW1wb3J0IHJlCmZyb20gcGF0aGxpYiBpbXBvcnQgUGF0aCwgUHVyZVBvc2l4UGF0aApmcm9tIHR5'
        'cGluZyBpbXBvcnQgQW55Cgpmcm9tIC4uLmNvcmUucG9ydHMubG9vcF9yZWdpc3RyeSBpbXBvcnQg'
        'RmVlZFByb2ZpbGUsIEZlZWRQcm9maWxlU3RhdGUsIFJlZ2lzdGVyZWRMb29wCgoKX0xPT1BfSUQg'
        'PSByZS5jb21waWxlKHIiXlthLXpdW2EtejAtOS1dKiQiKQpfU0NIRU1BX1ZFUlNJT04gPSAyCgoj'
        'IFBFQydzIGNsb3NlZCBmZWVkLXByb2ZpbGUgdm9jYWJ1bGFyeTogZWFjaCBwcm9maWxlIGlkZW50'
        'aWZpZXIgYW5kIHRoZQojIHZlcnNpb25zIHRoaXMgYWRhcHRlciBhY2NlcHRzLiBFeHRlbmRpbmcg'
        'aXQgaXMgYSBQRUMgY29kZSBjaGFuZ2UgdW5kZXIgYW4KIyBvd25lci1ydWxlZCBELVBFQyBwYWNr'
        'ZXQ7IGxvb3BzIG5ldmVyIGRlY2xhcmUgaXQuCkZFRURfUFJPRklMRV9WRVJTSU9OUzogZGljdFtz'
        'dHIsIGZyb3plbnNldFtpbnRdXSA9IHsKICAgICJhZ2VudHJ1bnMtanNvbiI6IGZyb3plbnNldCh7'
        'MX0pLAogICAgImxvb3AtcmVjZWlwdHMtbGVkZ2VyIjogZnJvemVuc2V0KHsxfSksCiAgICAicmVt'
        'YWluaW5nLWl0ZW1zIjogZnJvemVuc2V0KHsxfSksCiAgICAicmVtYWluaW5nLWxvb3AiOiBmcm96'
        'ZW5zZXQoezF9KSwKICAgICJzaGFyZWQtZGV2LWxvb3AiOiBmcm96ZW5zZXQoezF9KSwKfQoKIyBU'
        'aGUgZmlsZS10cnV0aCBzdXJmYWNlcyBlYWNoIHByb2ZpbGUgcmVhZHMuIFRoZSBwcm9maWxlcyBk'
        'ZWNsYXJlZCBvbiBvbmUKIyBsb29wIG11c3QgY292ZXIgcGFpcndpc2UtZGlzam9pbnQgc3VyZmFj'
        'ZXMsIHNvIG5vIHN1cmZhY2UgaXMgcmVhZCB1bmRlciB0d28KIyBncmFtbWFycyBvciBkZWNsYXJl'
        'ZCBib3RoIGxpdmUgYW5kIGhpc3RvcmljYWwuCkZFRURfUFJPRklMRV9TVVJGQUNFUzogZGljdFtz'
        'dHIsIGZyb3plbnNldFtzdHJdXSA9IHsKICAgICJhZ2VudHJ1bnMtanNvbiI6IGZyb3plbnNldCh7'
        'Impzb24tcnVuLWV2aWRlbmNlIn0pLAogICAgImxvb3AtcmVjZWlwdHMtbGVkZ2VyIjogZnJvemVu'
        'c2V0KHsicmVjZWlwdC1sZWRnZXIifSksCiAgICAicmVtYWluaW5nLWl0ZW1zIjogZnJvemVuc2V0'
        'KHsic3RhdHVzLXJlbWFpbmluZyJ9KSwKICAgICJyZW1haW5pbmctbG9vcCI6IGZyb3plbnNldCgK'
        'ICAgICAgICB7CiAgICAgICAgICAgICJkZWNpc2lvbi1yZWdpc3RlcnMiLAogICAgICAgICAgICAi'
        'ZGVwZW5kZW5jeS1yZWdpc3RlcnMiLAogICAgICAgICAgICAicmVjZWlwdC1sZWRnZXIiLAogICAg'
        'ICAgICAgICAic3RhdHVzLWxpZmVjeWNsZSIsCiAgICAgICAgICAgICJzdGF0dXMtcmVtYWluaW5n'
        'IiwKICAgICAgICB9CiAgICApLAogICAgInNoYXJlZC1kZXYtbG9vcCI6IGZyb3plbnNldCgKICAg'
        'ICAgICB7CiAgICAgICAgICAgICJjZW50cmFsLXJlY2VpcHRzIiwKICAgICAgICAgICAgImRlY2lz'
        'aW9uLXJlZ2lzdGVycyIsCiAgICAgICAgICAgICJkZXBlbmRlbmN5LXJlZ2lzdGVycyIsCiAgICAg'
        'ICAgICAgICJtZW1vcnktcnVuLWluZGV4IiwKICAgICAgICAgICAgInN0YXR1cy1saWZlY3ljbGUi'
        'LAogICAgICAgICAgICAid29yay1ncmFwaHMiLAogICAgICAgIH0KICAgICksCn0KCgpjbGFzcyBM'
        'b29wUmVnaXN0cnlDb25maWdFcnJvcihWYWx1ZUVycm9yKToKICAgICIiIkEgbG9jYXRlZCwgZXhw'
        'bGljaXQgZmFpbHVyZSBpbiB0aGUgcmVwbGFjZWFibGUgSlNPTiBhZGFwdGVyLiIiIgoKCmNsYXNz'
        'IEpzb25Mb29wUmVnaXN0cnk6CiAgICAiIiJSZWFkIGFuZCB2YWxpZGF0ZSBvbmUgbG9jYWwgSlNP'
        'TiBsb29wLXJlZ2lzdHJ5IGNvbmZpZ3VyYXRpb24uIiIiCgogICAgZGVmIF9faW5pdF9fKHNlbGYs'
        'IGNvbmZpZ19wYXRoOiBzdHIgfCBQYXRoKSAtPiBOb25lOgogICAgICAgIHNlbGYuX2NvbmZpZ19w'
        'YXRoID0gUGF0aChjb25maWdfcGF0aCkKCiAgICBkZWYgcmVnaXN0ZXJlZF9sb29wcyhzZWxmKSAt'
        'PiB0dXBsZVtSZWdpc3RlcmVkTG9vcCwgLi4uXToKICAgICAgICBkb2N1bWVudCA9IHNlbGYuX3Jl'
        'YWRfZG9jdW1lbnQoKQogICAgICAgIHJldHVybiBzZWxmLl92YWxpZGF0ZV9kb2N1bWVudChkb2N1'
        'bWVudCkKCiAgICBkZWYgX3JlYWRfZG9jdW1lbnQoc2VsZikgLT4gQW55OgogICAgICAgIHRyeToK'
        'ICAgICAgICAgICAgd2l0aCBzZWxmLl9jb25maWdfcGF0aC5vcGVuKGVuY29kaW5nPSJ1dGYtOCIp'
        'IGFzIGhhbmRsZToKICAgICAgICAgICAgICAgIHJldHVybiBqc29uLmxvYWQoaGFuZGxlKQogICAg'
        'ICAgIGV4Y2VwdCBGaWxlTm90Rm91bmRFcnJvciBhcyBlcnJvcjoKICAgICAgICAgICAgcmFpc2Ug'
        'TG9vcFJlZ2lzdHJ5Q29uZmlnRXJyb3IoCiAgICAgICAgICAgICAgICBmIntzZWxmLl9jb25maWdf'
        'cGF0aH06IGNvbmZpZ3VyYXRpb24gZmlsZSBkb2VzIG5vdCBleGlzdCIKICAgICAgICAgICAgKSBm'
        'cm9tIGVycm9yCiAgICAgICAgZXhjZXB0IGpzb24uSlNPTkRlY29kZUVycm9yIGFzIGVycm9yOgog'
        'ICAgICAgICAgICByYWlzZSBMb29wUmVnaXN0cnlDb25maWdFcnJvcigKICAgICAgICAgICAgICAg'
        'IGYie3NlbGYuX2NvbmZpZ19wYXRofTogbWFsZm9ybWVkIEpTT04gYXQgbGluZSB7ZXJyb3IubGlu'
        'ZW5vfSwgIgogICAgICAgICAgICAgICAgZiJjb2x1bW4ge2Vycm9yLmNvbG5vfSIKICAgICAgICAg'
        'ICAgKSBmcm9tIGVycm9yCiAgICAgICAgZXhjZXB0IE9TRXJyb3IgYXMgZXJyb3I6CiAgICAgICAg'
        'ICAgIGRldGFpbCA9IGVycm9yLnN0cmVycm9yIG9yIGVycm9yLl9fY2xhc3NfXy5fX25hbWVfXwog'
        'ICAgICAgICAgICByYWlzZSBMb29wUmVnaXN0cnlDb25maWdFcnJvcigKICAgICAgICAgICAgICAg'
        'IGYie3NlbGYuX2NvbmZpZ19wYXRofTogY29uZmlndXJhdGlvbiBmaWxlIGlzIHVucmVhZGFibGU6'
        'IHtkZXRhaWx9IgogICAgICAgICAgICApIGZyb20gZXJyb3IKCiAgICBkZWYgX3ZhbGlkYXRlX2Rv'
        'Y3VtZW50KHNlbGYsIGRvY3VtZW50OiBBbnkpIC0+IHR1cGxlW1JlZ2lzdGVyZWRMb29wLCAuLi5d'
        'OgogICAgICAgIGlmIG5vdCBpc2luc3RhbmNlKGRvY3VtZW50LCBkaWN0KToKICAgICAgICAgICAg'
        'c2VsZi5fZmFpbCgiJCIsICJleHBlY3RlZCBhbiBvYmplY3QiKQogICAgICAgIHNlbGYuX3JlcXVp'
        'cmVfZXhhY3RfZmllbGRzKGRvY3VtZW50LCB7InNjaGVtYV92ZXJzaW9uIiwgImxvb3BzIn0sICIk'
        'IikKCiAgICAgICAgdmVyc2lvbiA9IGRvY3VtZW50WyJzY2hlbWFfdmVyc2lvbiJdCiAgICAgICAg'
        'aWYgdHlwZSh2ZXJzaW9uKSBpcyBub3QgaW50IG9yIHZlcnNpb24gIT0gX1NDSEVNQV9WRVJTSU9O'
        'OgogICAgICAgICAgICBzZWxmLl9mYWlsKAogICAgICAgICAgICAgICAgIiQuc2NoZW1hX3ZlcnNp'
        'b24iLAogICAgICAgICAgICAgICAgZiJleHBlY3RlZCBpbnRlZ2VyIGNvbnN0YW50IHtfU0NIRU1B'
        'X1ZFUlNJT059OyBubyBvdGhlciBzY2hlbWEgdmVyc2lvbiBpcyBhY2NlcHRlZCIsCiAgICAgICAg'
        'ICAgICkKCiAgICAgICAgbG9vcF9yb3dzID0gZG9jdW1lbnRbImxvb3BzIl0KICAgICAgICBpZiBu'
        'b3QgaXNpbnN0YW5jZShsb29wX3Jvd3MsIGxpc3QpOgogICAgICAgICAgICBzZWxmLl9mYWlsKCIk'
        'Lmxvb3BzIiwgImV4cGVjdGVkIGFuIGFycmF5IikKICAgICAgICBpZiBub3QgbG9vcF9yb3dzOgog'
        'ICAgICAgICAgICBzZWxmLl9mYWlsKCIkLmxvb3BzIiwgImV4cGVjdGVkIGF0IGxlYXN0IG9uZSBs'
        'b29wIGVudHJ5IikKCiAgICAgICAgbG9vcHM6IGxpc3RbUmVnaXN0ZXJlZExvb3BdID0gW10KICAg'
        'ICAgICBzZWVuOiBkaWN0W3N0ciwgaW50XSA9IHt9CiAgICAgICAgZm9yIGluZGV4LCByb3cgaW4g'
        'ZW51bWVyYXRlKGxvb3Bfcm93cyk6CiAgICAgICAgICAgIGxvY2F0aW9uID0gZiIkLmxvb3BzW3tp'
        'bmRleH1dIgogICAgICAgICAgICBpZiBub3QgaXNpbnN0YW5jZShyb3csIGRpY3QpOgogICAgICAg'
        'ICAgICAgICAgc2VsZi5fZmFpbChsb2NhdGlvbiwgImV4cGVjdGVkIGFuIG9iamVjdCIpCiAgICAg'
        'ICAgICAgIHNlbGYuX3JlcXVpcmVfZXhhY3RfZmllbGRzKAogICAgICAgICAgICAgICAgcm93LCB7'
        'Imxvb3BfaWQiLCAibG9vcF9pbml0X3BhdGgiLCAiZmVlZF9wcm9maWxlcyJ9LCBsb2NhdGlvbgog'
        'ICAgICAgICAgICApCgogICAgICAgICAgICBsb29wX2lkID0gcm93WyJsb29wX2lkIl0KICAgICAg'
        'ICAgICAgaWYgbm90IGlzaW5zdGFuY2UobG9vcF9pZCwgc3RyKSBvciBub3QgX0xPT1BfSUQuZnVs'
        'bG1hdGNoKGxvb3BfaWQpOgogICAgICAgICAgICAgICAgc2VsZi5fZmFpbCgKICAgICAgICAgICAg'
        'ICAgICAgICBmIntsb2NhdGlvbn0ubG9vcF9pZCIsCiAgICAgICAgICAgICAgICAgICAgImV4cGVj'
        'dGVkIGEgbm9uLWVtcHR5IGxvd2VyLWNhc2UgaWRlbnRpZmllciIsCiAgICAgICAgICAgICAgICAp'
        'CiAgICAgICAgICAgIGlmIGxvb3BfaWQgaW4gc2VlbjoKICAgICAgICAgICAgICAgIHNlbGYuX2Zh'
        'aWwoCiAgICAgICAgICAgICAgICAgICAgZiJ7bG9jYXRpb259Lmxvb3BfaWQiLAogICAgICAgICAg'
        'ICAgICAgICAgIGYiZHVwbGljYXRlIGxvb3AgaWRlbnRpZmllciBmaXJzdCBkZWNsYXJlZCBhdCAk'
        'Lmxvb3BzW3tzZWVuW2xvb3BfaWRdfV0ubG9vcF9pZCIsCiAgICAgICAgICAgICAgICApCgogICAg'
        'ICAgICAgICBsb29wX2luaXRfcGF0aCA9IHNlbGYuX3JlcG9zaXRvcnlfcGF0aCgKICAgICAgICAg'
        'ICAgICAgIHJvd1sibG9vcF9pbml0X3BhdGgiXSwgZiJ7bG9jYXRpb259Lmxvb3BfaW5pdF9wYXRo'
        'IgogICAgICAgICAgICApCiAgICAgICAgICAgIGZlZWRfcHJvZmlsZXMgPSBzZWxmLl9mZWVkX3By'
        'b2ZpbGVzKAogICAgICAgICAgICAgICAgcm93WyJmZWVkX3Byb2ZpbGVzIl0sIGYie2xvY2F0aW9u'
        'fS5mZWVkX3Byb2ZpbGVzIgogICAgICAgICAgICApCgogICAgICAgICAgICBzZWVuW2xvb3BfaWRd'
        'ID0gaW5kZXgKICAgICAgICAgICAgbG9vcHMuYXBwZW5kKAogICAgICAgICAgICAgICAgUmVnaXN0'
        'ZXJlZExvb3AoCiAgICAgICAgICAgICAgICAgICAgbG9vcF9pZD1sb29wX2lkLAogICAgICAgICAg'
        'ICAgICAgICAgIGxvb3BfaW5pdF9wYXRoPWxvb3BfaW5pdF9wYXRoLAogICAgICAgICAgICAgICAg'
        'ICAgIGZlZWRfcHJvZmlsZXM9ZmVlZF9wcm9maWxlcywKICAgICAgICAgICAgICAgICkKICAgICAg'
        'ICAgICAgKQoKICAgICAgICByZXR1cm4gdHVwbGUobG9vcHMpCgogICAgZGVmIF9mZWVkX3Byb2Zp'
        'bGVzKHNlbGYsIHZhbHVlOiBBbnksIGxvY2F0aW9uOiBzdHIpIC0+IHR1cGxlW0ZlZWRQcm9maWxl'
        'LCAuLi5dOgogICAgICAgIGlmIG5vdCBpc2luc3RhbmNlKHZhbHVlLCBsaXN0KToKICAgICAgICAg'
        'ICAgc2VsZi5fZmFpbChsb2NhdGlvbiwgImV4cGVjdGVkIGFuIGFycmF5IikKICAgICAgICBpZiBu'
        'b3QgdmFsdWU6CiAgICAgICAgICAgIHNlbGYuX2ZhaWwobG9jYXRpb24sICJleHBlY3RlZCBhdCBs'
        'ZWFzdCBvbmUgZmVlZCBwcm9maWxlIikKCiAgICAgICAgcHJvZmlsZXM6IGxpc3RbRmVlZFByb2Zp'
        'bGVdID0gW10KICAgICAgICBzZWVuOiBkaWN0W3N0ciwgaW50XSA9IHt9CiAgICAgICAgY292ZXJl'
        'ZDogZGljdFtzdHIsIGludF0gPSB7fQogICAgICAgIGZvciBpbmRleCwgZW50cnkgaW4gZW51bWVy'
        'YXRlKHZhbHVlKToKICAgICAgICAgICAgZW50cnlfbG9jYXRpb24gPSBmIntsb2NhdGlvbn1be2lu'
        'ZGV4fV0iCiAgICAgICAgICAgIGlmIG5vdCBpc2luc3RhbmNlKGVudHJ5LCBkaWN0KToKICAgICAg'
        'ICAgICAgICAgIHNlbGYuX2ZhaWwoZW50cnlfbG9jYXRpb24sICJleHBlY3RlZCBhbiBvYmplY3Qi'
        'KQogICAgICAgICAgICBzZWxmLl9yZXF1aXJlX2V4YWN0X2ZpZWxkcygKICAgICAgICAgICAgICAg'
        'IGVudHJ5LCB7InByb2ZpbGUiLCAidmVyc2lvbiIsICJzdGF0ZSIsICJiYXNpcyJ9LCBlbnRyeV9s'
        'b2NhdGlvbgogICAgICAgICAgICApCgogICAgICAgICAgICBwcm9maWxlID0gZW50cnlbInByb2Zp'
        'bGUiXQogICAgICAgICAgICBpZiBub3QgaXNpbnN0YW5jZShwcm9maWxlLCBzdHIpIG9yIHByb2Zp'
        'bGUgbm90IGluIEZFRURfUFJPRklMRV9WRVJTSU9OUzoKICAgICAgICAgICAgICAgIHNlbGYuX2Zh'
        'aWwoCiAgICAgICAgICAgICAgICAgICAgZiJ7ZW50cnlfbG9jYXRpb259LnByb2ZpbGUiLAogICAg'
        'ICAgICAgICAgICAgICAgICJleHBlY3RlZCBhbiBpZGVudGlmaWVyIGZyb20gdGhlIGNsb3NlZCBm'
        'ZWVkLXByb2ZpbGUgdm9jYWJ1bGFyeSIsCiAgICAgICAgICAgICAgICApCiAgICAgICAgICAgIGlm'
        'IHByb2ZpbGUgaW4gc2VlbjoKICAgICAgICAgICAgICAgIHNlbGYuX2ZhaWwoCiAgICAgICAgICAg'
        'ICAgICAgICAgZiJ7ZW50cnlfbG9jYXRpb259LnByb2ZpbGUiLAogICAgICAgICAgICAgICAgICAg'
        'IGYiZHVwbGljYXRlIGZlZWQgcHJvZmlsZSBmaXJzdCBkZWNsYXJlZCBhdCB7bG9jYXRpb259W3tz'
        'ZWVuW3Byb2ZpbGVdfV0ucHJvZmlsZSIsCiAgICAgICAgICAgICAgICApCgogICAgICAgICAgICB2'
        'ZXJzaW9uID0gZW50cnlbInZlcnNpb24iXQogICAgICAgICAgICBpZiB0eXBlKHZlcnNpb24pIGlz'
        'IG5vdCBpbnQgb3IgdmVyc2lvbiBub3QgaW4gRkVFRF9QUk9GSUxFX1ZFUlNJT05TW3Byb2ZpbGVd'
        'OgogICAgICAgICAgICAgICAgc2VsZi5fZmFpbCgKICAgICAgICAgICAgICAgICAgICBmIntlbnRy'
        'eV9sb2NhdGlvbn0udmVyc2lvbiIsCiAgICAgICAgICAgICAgICAgICAgZiJleHBlY3RlZCBhIHN1'
        'cHBvcnRlZCBpbnRlZ2VyIHZlcnNpb24gb2YgZmVlZCBwcm9maWxlIHtwcm9maWxlfSIsCiAgICAg'
        'ICAgICAgICAgICApCgogICAgICAgICAgICBzdGF0ZSA9IGVudHJ5WyJzdGF0ZSJdCiAgICAgICAg'
        'ICAgIGlmIG5vdCBpc2luc3RhbmNlKHN0YXRlLCBzdHIpIG9yIHN0YXRlIG5vdCBpbiB7CiAgICAg'
        'ICAgICAgICAgICBtZW1iZXIudmFsdWUgZm9yIG1lbWJlciBpbiBGZWVkUHJvZmlsZVN0YXRlCiAg'
        'ICAgICAgICAgIH06CiAgICAgICAgICAgICAgICBzZWxmLl9mYWlsKGYie2VudHJ5X2xvY2F0aW9u'
        'fS5zdGF0ZSIsICJleHBlY3RlZCBsaXZlIG9yIGhpc3RvcmljYWwiKQoKICAgICAgICAgICAgYmFz'
        'aXMgPSBzZWxmLl9yZXBvc2l0b3J5X3BhdGgoZW50cnlbImJhc2lzIl0sIGYie2VudHJ5X2xvY2F0'
        'aW9ufS5iYXNpcyIpCgogICAgICAgICAgICBmb3Igc3VyZmFjZSBpbiBzb3J0ZWQoRkVFRF9QUk9G'
        'SUxFX1NVUkZBQ0VTW3Byb2ZpbGVdKToKICAgICAgICAgICAgICAgIGlmIHN1cmZhY2UgaW4gY292'
        'ZXJlZDoKICAgICAgICAgICAgICAgICAgICBzZWxmLl9mYWlsKAogICAgICAgICAgICAgICAgICAg'
        'ICAgICBmIntlbnRyeV9sb2NhdGlvbn0ucHJvZmlsZSIsCiAgICAgICAgICAgICAgICAgICAgICAg'
        'IGYic3VyZmFjZSB7c3VyZmFjZX0gaXMgYWxyZWFkeSBjb3ZlcmVkIGJ5ICIKICAgICAgICAgICAg'
        'ICAgICAgICAgICAgZiJ7bG9jYXRpb259W3tjb3ZlcmVkW3N1cmZhY2VdfV0ucHJvZmlsZSIsCiAg'
        'ICAgICAgICAgICAgICAgICAgKQogICAgICAgICAgICBmb3Igc3VyZmFjZSBpbiBGRUVEX1BST0ZJ'
        'TEVfU1VSRkFDRVNbcHJvZmlsZV06CiAgICAgICAgICAgICAgICBjb3ZlcmVkW3N1cmZhY2VdID0g'
        'aW5kZXgKCiAgICAgICAgICAgIHNlZW5bcHJvZmlsZV0gPSBpbmRleAogICAgICAgICAgICBwcm9m'
        'aWxlcy5hcHBlbmQoCiAgICAgICAgICAgICAgICBGZWVkUHJvZmlsZSgKICAgICAgICAgICAgICAg'
        'ICAgICBwcm9maWxlPXByb2ZpbGUsCiAgICAgICAgICAgICAgICAgICAgdmVyc2lvbj12ZXJzaW9u'
        'LAogICAgICAgICAgICAgICAgICAgIHN0YXRlPUZlZWRQcm9maWxlU3RhdGUoc3RhdGUpLAogICAg'
        'ICAgICAgICAgICAgICAgIGJhc2lzPWJhc2lzLAogICAgICAgICAgICAgICAgKQogICAgICAgICAg'
        'ICApCgogICAgICAgIGlmIG5vdCBhbnkoaXRlbS5zdGF0ZSBpcyBGZWVkUHJvZmlsZVN0YXRlLkxJ'
        'VkUgZm9yIGl0ZW0gaW4gcHJvZmlsZXMpOgogICAgICAgICAgICBzZWxmLl9mYWlsKGxvY2F0aW9u'
        'LCAiZXhwZWN0ZWQgYXQgbGVhc3Qgb25lIGxpdmUgZmVlZCBwcm9maWxlIikKICAgICAgICByZXR1'
        'cm4gdHVwbGUocHJvZmlsZXMpCgogICAgZGVmIF9yZXBvc2l0b3J5X3BhdGgoc2VsZiwgdmFsdWU6'
        'IEFueSwgbG9jYXRpb246IHN0cikgLT4gc3RyOgogICAgICAgIGlmIG5vdCBpc2luc3RhbmNlKHZh'
        'bHVlLCBzdHIpIG9yIG5vdCB2YWx1ZToKICAgICAgICAgICAgc2VsZi5fZmFpbChsb2NhdGlvbiwg'
        'ImV4cGVjdGVkIGEgbm9uLWVtcHR5IHN0cmluZyIpCiAgICAgICAgbG9jYXRvciA9IFB1cmVQb3Np'
        'eFBhdGgodmFsdWUpCiAgICAgICAgaWYgbG9jYXRvci5pc19hYnNvbHV0ZSgpIG9yICIuLiIgaW4g'
        'bG9jYXRvci5wYXJ0cyBvciAiXFwiIGluIHZhbHVlOgogICAgICAgICAgICBzZWxmLl9mYWlsKGxv'
        'Y2F0aW9uLCAiZXhwZWN0ZWQgYSBub3JtYWxpemVkIHJlcG9zaXRvcnktcmVsYXRpdmUgcGF0aCIp'
        'CiAgICAgICAgcmV0dXJuIHZhbHVlCgogICAgZGVmIF9yZXF1aXJlX2V4YWN0X2ZpZWxkcygKICAg'
        'ICAgICBzZWxmLCB2YWx1ZTogZGljdFtzdHIsIEFueV0sIGV4cGVjdGVkOiBzZXRbc3RyXSwgbG9j'
        'YXRpb246IHN0cgogICAgKSAtPiBOb25lOgogICAgICAgIG1pc3NpbmcgPSBzb3J0ZWQoZXhwZWN0'
        'ZWQgLSB2YWx1ZS5rZXlzKCkpCiAgICAgICAgaWYgbWlzc2luZzoKICAgICAgICAgICAgc2VsZi5f'
        'ZmFpbChmIntsb2NhdGlvbn0ue21pc3NpbmdbMF19IiwgInJlcXVpcmVkIGZpZWxkIGlzIG1pc3Np'
        'bmciKQogICAgICAgIHVuZXhwZWN0ZWQgPSBzb3J0ZWQodmFsdWUua2V5cygpIC0gZXhwZWN0ZWQp'
        'CiAgICAgICAgaWYgdW5leHBlY3RlZDoKICAgICAgICAgICAgc2VsZi5fZmFpbCgKICAgICAgICAg'
        'ICAgICAgIGYie2xvY2F0aW9ufS57dW5leHBlY3RlZFswXX0iLAogICAgICAgICAgICAgICAgZiJm'
        'aWVsZCBpcyBub3QgZGVmaW5lZCBieSBzY2hlbWEgdntfU0NIRU1BX1ZFUlNJT059IiwKICAgICAg'
        'ICAgICAgKQoKICAgIGRlZiBfZmFpbChzZWxmLCBsb2NhdGlvbjogc3RyLCBtZXNzYWdlOiBzdHIp'
        'IC0+IE5vbmU6CiAgICAgICAgcmFpc2UgTG9vcFJlZ2lzdHJ5Q29uZmlnRXJyb3IoZiJ7c2VsZi5f'
        'Y29uZmlnX3BhdGh9Ontsb2NhdGlvbn06IHttZXNzYWdlfSIpCg=='
    ),
    '586fcd5ead4bbb19e76a125da972910ea1e93a610b2d74758fcfd7fb89a6ee01': (
        'ZnJvbSBfX2Z1dHVyZV9fIGltcG9ydCBhbm5vdGF0aW9ucwoKaW1wb3J0IGNvcHkKaW1wb3J0IGpz'
        'b24KaW1wb3J0IHN5cwppbXBvcnQgdGVtcGZpbGUKaW1wb3J0IHVuaXR0ZXN0CmZyb20gcGF0aGxp'
        'YiBpbXBvcnQgUGF0aAoKClYyX1JPT1QgPSBQYXRoKF9fZmlsZV9fKS5yZXNvbHZlKCkucGFyZW50'
        'c1syXQpTUkNfUk9PVCA9IFYyX1JPT1QgLyAic3JjIgpDT05GSUdfUk9PVCA9IFYyX1JPT1QgLyAi'
        'Y29uZmlnIgpGSVhUVVJFUyA9IFBhdGgoX19maWxlX18pLnJlc29sdmUoKS5wYXJlbnQgLyAiZml4'
        'dHVyZXMiCnN5cy5wYXRoLmluc2VydCgwLCBzdHIoU1JDX1JPT1QpKQoKZnJvbSBwZWNfdjIuYWRh'
        'cHRlcnMuY29uZmlnLmxvb3BfcmVnaXN0cnkgaW1wb3J0ICggICMgbm9xYTogRTQwMgogICAgRkVF'
        'RF9QUk9GSUxFX1NVUkZBQ0VTLAogICAgRkVFRF9QUk9GSUxFX1ZFUlNJT05TLAogICAgSnNvbkxv'
        'b3BSZWdpc3RyeSwKICAgIExvb3BSZWdpc3RyeUNvbmZpZ0Vycm9yLAopCmZyb20gcGVjX3YyLmNv'
        'cmUucG9ydHMubG9vcF9yZWdpc3RyeSBpbXBvcnQgKCAgIyBub3FhOiBFNDAyCiAgICBGZWVkUHJv'
        'ZmlsZSwKICAgIEZlZWRQcm9maWxlU3RhdGUsCiAgICBSZWdpc3RlcmVkTG9vcCwKKQoKClBFQ19M'
        'T09QX0lOSVQgPSAicHJvamVjdHMvcGVjL2xvb3AvTE9PUF9JTklULm1kIgpQRUNfQUdFTlRTID0g'
        'InByb2plY3RzL3BlYy9BR0VOVFMubWQiCkRfUEVDXzk0ID0gKAogICAgInByb2plY3RzL3BlYy9l'
        'eGVjdXRpb24vX0Nvb3JkaW5hdGlvbi9fREVDSVNJT05TLyIKICAgICJELVBFQy05NF9vd25lcl9k'
        'aXJlY3Rpb25fbG9vcF9taWdyYXRpb25fMjAyNi0wOS0yNS5tZCIKKQoKCmRlZiB2YWxpZF9kb2N1'
        'bWVudCgpIC0+IGRpY3Q6CiAgICByZXR1cm4gewogICAgICAgICJzY2hlbWFfdmVyc2lvbiI6IDIs'
        'CiAgICAgICAgImxvb3BzIjogWwogICAgICAgICAgICB7CiAgICAgICAgICAgICAgICAibG9vcF9p'
        'ZCI6ICJwZWMiLAogICAgICAgICAgICAgICAgImxvb3BfaW5pdF9wYXRoIjogUEVDX0xPT1BfSU5J'
        'VCwKICAgICAgICAgICAgICAgICJmZWVkX3Byb2ZpbGVzIjogWwogICAgICAgICAgICAgICAgICAg'
        'IHsicHJvZmlsZSI6ICJzaGFyZWQtZGV2LWxvb3AiLCAidmVyc2lvbiI6IDEsICJzdGF0ZSI6ICJs'
        'aXZlIiwgImJhc2lzIjogRF9QRUNfOTR9LAogICAgICAgICAgICAgICAgICAgIHsicHJvZmlsZSI6'
        'ICJyZW1haW5pbmctaXRlbXMiLCAidmVyc2lvbiI6IDEsICJzdGF0ZSI6ICJsaXZlIiwgImJhc2lz'
        'IjogUEVDX0FHRU5UU30sCiAgICAgICAgICAgICAgICAgICAgeyJwcm9maWxlIjogImxvb3AtcmVj'
        'ZWlwdHMtbGVkZ2VyIiwgInZlcnNpb24iOiAxLCAic3RhdGUiOiAiaGlzdG9yaWNhbCIsICJiYXNp'
        'cyI6IFBFQ19BR0VOVFN9LAogICAgICAgICAgICAgICAgICAgIHsicHJvZmlsZSI6ICJhZ2VudHJ1'
        'bnMtanNvbiIsICJ2ZXJzaW9uIjogMSwgInN0YXRlIjogImhpc3RvcmljYWwiLCAiYmFzaXMiOiBE'
        'X1BFQ185NH0sCiAgICAgICAgICAgICAgICBdLAogICAgICAgICAgICB9CiAgICAgICAgXSwKICAg'
        'IH0KCgpjbGFzcyBKc29uTG9vcFJlZ2lzdHJ5VGVzdHModW5pdHRlc3QuVGVzdENhc2UpOgogICAg'
        'ZGVmIGxvYWQoc2VsZiwgZG9jdW1lbnQ6IG9iamVjdCkgLT4gdHVwbGVbUmVnaXN0ZXJlZExvb3As'
        'IC4uLl06CiAgICAgICAgd2l0aCB0ZW1wZmlsZS5UZW1wb3JhcnlEaXJlY3RvcnkoKSBhcyB0ZW1w'
        'b3Jhcnk6CiAgICAgICAgICAgIHBhdGggPSBQYXRoKHRlbXBvcmFyeSkgLyAiY2FuZGlkYXRlLmpz'
        'b24iCiAgICAgICAgICAgIHBhdGgud3JpdGVfdGV4dChqc29uLmR1bXBzKGRvY3VtZW50KSwgZW5j'
        'b2Rpbmc9InV0Zi04IikKICAgICAgICAgICAgcmV0dXJuIEpzb25Mb29wUmVnaXN0cnkocGF0aCku'
        'cmVnaXN0ZXJlZF9sb29wcygpCgogICAgZGVmIHRlc3RfY2hlY2tlZF9pbl9kZWZhdWx0X2hhc19l'
        'eGFjdGx5X3RoZV9wZWNfbG9vcChzZWxmKSAtPiBOb25lOgogICAgICAgIGxvb3BzID0gSnNvbkxv'
        'b3BSZWdpc3RyeShDT05GSUdfUk9PVCAvICJsb29wcy5qc29uIikucmVnaXN0ZXJlZF9sb29wcygp'
        'CiAgICAgICAgc2VsZi5hc3NlcnRFcXVhbCgKICAgICAgICAgICAgbG9vcHMsCiAgICAgICAgICAg'
        'ICgKICAgICAgICAgICAgICAgIFJlZ2lzdGVyZWRMb29wKAogICAgICAgICAgICAgICAgICAgICJw'
        'ZWMiLAogICAgICAgICAgICAgICAgICAgIFBFQ19MT09QX0lOSVQsCiAgICAgICAgICAgICAgICAg'
        'ICAgKAogICAgICAgICAgICAgICAgICAgICAgICBGZWVkUHJvZmlsZSgKICAgICAgICAgICAgICAg'
        'ICAgICAgICAgICAgICJyZW1haW5pbmctbG9vcCIsCiAgICAgICAgICAgICAgICAgICAgICAgICAg'
        'ICAxLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgRmVlZFByb2ZpbGVTdGF0ZS5MSVZFLAog'
        'ICAgICAgICAgICAgICAgICAgICAgICAgICAgInByb2plY3RzL3BlYy9leGVjdXRpb24vX0Nvb3Jk'
        'aW5hdGlvbi9fREVDSVNJT05TLyIKICAgICAgICAgICAgICAgICAgICAgICAgICAgICJELVBFQy04'
        'Nl9zY2FfMDA1X2ZlZWRfbW9kZWxfcmViYXNlbGluZV8yMDI2LTA5LTIzLm1kIiwKICAgICAgICAg'
        'ICAgICAgICAgICAgICAgKSwKICAgICAgICAgICAgICAgICAgICApLAogICAgICAgICAgICAgICAg'
        'KSwKICAgICAgICAgICAgKSwKICAgICAgICApCgogICAgZGVmIHRlc3Rfc2NoZW1hX2RvY3VtZW50'
        'c19ldmVyeV9maWVsZF9hbmRfdGhlX2V4YWN0X2RlZmF1bHQoc2VsZikgLT4gTm9uZToKICAgICAg'
        'ICBzY2hlbWEgPSBqc29uLmxvYWRzKChDT05GSUdfUk9PVCAvICJsb29wcy5zY2hlbWEuanNvbiIp'
        'LnJlYWRfdGV4dChlbmNvZGluZz0idXRmLTgiKSkKICAgICAgICBkb2N1bWVudCA9IGpzb24ubG9h'
        'ZHMoKENPTkZJR19ST09UIC8gImxvb3BzLmpzb24iKS5yZWFkX3RleHQoZW5jb2Rpbmc9InV0Zi04'
        'IikpCiAgICAgICAgc2VsZi5hc3NlcnRFcXVhbChzY2hlbWFbIiRzY2hlbWEiXSwgImh0dHBzOi8v'
        'anNvbi1zY2hlbWEub3JnL2RyYWZ0LzIwMjAtMTIvc2NoZW1hIikKICAgICAgICBzZWxmLmFzc2Vy'
        'dEVxdWFsKHNjaGVtYVsiJGlkIl0sICJodHRwczovL2NoaXJhbGl0eS5sb2NhbC9wZWMvdjIvY29u'
        'ZmlnL2xvb3BzLnNjaGVtYS52Mi5qc29uIikKICAgICAgICBzZWxmLmFzc2VydEVxdWFsKHNjaGVt'
        'YVsicHJvcGVydGllcyJdWyJzY2hlbWFfdmVyc2lvbiJdWyJjb25zdCJdLCAyKQogICAgICAgIHNl'
        'bGYuYXNzZXJ0RXF1YWwoZG9jdW1lbnRbInNjaGVtYV92ZXJzaW9uIl0sIDIpCiAgICAgICAgc2Vs'
        'Zi5hc3NlcnRFcXVhbChsZW4oZG9jdW1lbnRbImxvb3BzIl0pLCAxKQogICAgICAgIGZvciBmaWVs'
        'ZCBpbiAoInNjaGVtYV92ZXJzaW9uIiwgImxvb3BzIik6CiAgICAgICAgICAgIHNlbGYuYXNzZXJ0'
        'VHJ1ZShzY2hlbWFbInByb3BlcnRpZXMiXVtmaWVsZF1bImRlc2NyaXB0aW9uIl0pCiAgICAgICAg'
        'cm93ID0gc2NoZW1hWyJwcm9wZXJ0aWVzIl1bImxvb3BzIl1bIml0ZW1zIl0KICAgICAgICBzZWxm'
        'LmFzc2VydEVxdWFsKHNvcnRlZChyb3dbInJlcXVpcmVkIl0pLCBbImZlZWRfcHJvZmlsZXMiLCAi'
        'bG9vcF9pZCIsICJsb29wX2luaXRfcGF0aCJdKQogICAgICAgIGZvciBmaWVsZCBpbiAoImxvb3Bf'
        'aWQiLCAibG9vcF9pbml0X3BhdGgiLCAiZmVlZF9wcm9maWxlcyIpOgogICAgICAgICAgICBzZWxm'
        'LmFzc2VydFRydWUocm93WyJwcm9wZXJ0aWVzIl1bZmllbGRdWyJkZXNjcmlwdGlvbiJdKQogICAg'
        'ICAgIGVudHJ5ID0gcm93WyJwcm9wZXJ0aWVzIl1bImZlZWRfcHJvZmlsZXMiXVsiaXRlbXMiXQog'
        'ICAgICAgIHNlbGYuYXNzZXJ0RmFsc2UoZW50cnlbImFkZGl0aW9uYWxQcm9wZXJ0aWVzIl0pCiAg'
        'ICAgICAgc2VsZi5hc3NlcnRFcXVhbChzb3J0ZWQoZW50cnlbInJlcXVpcmVkIl0pLCBbImJhc2lz'
        'IiwgInByb2ZpbGUiLCAic3RhdGUiLCAidmVyc2lvbiJdKQogICAgICAgIGZvciBmaWVsZCBpbiAo'
        'InByb2ZpbGUiLCAidmVyc2lvbiIsICJzdGF0ZSIsICJiYXNpcyIpOgogICAgICAgICAgICBzZWxm'
        'LmFzc2VydFRydWUoZW50cnlbInByb3BlcnRpZXMiXVtmaWVsZF1bImRlc2NyaXB0aW9uIl0pCiAg'
        'ICAgICAgZGVjbGFyZWQgPSB7b3B0aW9uWyJjb25zdCJdOiBvcHRpb25bImRlc2NyaXB0aW9uIl0g'
        'Zm9yIG9wdGlvbiBpbiBlbnRyeVsicHJvcGVydGllcyJdWyJwcm9maWxlIl1bIm9uZU9mIl19CiAg'
        'ICAgICAgc2VsZi5hc3NlcnRFcXVhbChzZXQoZGVjbGFyZWQpLCBzZXQoRkVFRF9QUk9GSUxFX1ZF'
        'UlNJT05TKSkKICAgICAgICBzZWxmLmFzc2VydEVxdWFsKHNldChGRUVEX1BST0ZJTEVfU1VSRkFD'
        'RVMpLCBzZXQoRkVFRF9QUk9GSUxFX1ZFUlNJT05TKSkKICAgICAgICBmb3IgcHJvZmlsZSwgZGVz'
        'Y3JpcHRpb24gaW4gZGVjbGFyZWQuaXRlbXMoKToKICAgICAgICAgICAgd2l0aCBzZWxmLnN1YlRl'
        'c3QocHJvZmlsZT1wcm9maWxlKToKICAgICAgICAgICAgICAgIF8sIF8sIGxpc3RlZCA9IGRlc2Ny'
        'aXB0aW9uLnJzdHJpcCgiLiIpLnBhcnRpdGlvbigiIFN1cmZhY2VzOiAiKQogICAgICAgICAgICAg'
        'ICAgc2VsZi5hc3NlcnRFcXVhbChzZXQobGlzdGVkLnNwbGl0KCIsICIpKSwgc2V0KEZFRURfUFJP'
        'RklMRV9TVVJGQUNFU1twcm9maWxlXSkpCiAgICAgICAgc2VsZi5hc3NlcnRFcXVhbCh7ZW50cnlb'
        'InByb3BlcnRpZXMiXVsidmVyc2lvbiJdWyJjb25zdCJdfSwgc2V0KCkudW5pb24oKkZFRURfUFJP'
        'RklMRV9WRVJTSU9OUy52YWx1ZXMoKSkpCiAgICAgICAgc2VsZi5hc3NlcnRFcXVhbCgKICAgICAg'
        'ICAgICAgc2V0KGVudHJ5WyJwcm9wZXJ0aWVzIl1bInN0YXRlIl1bImVudW0iXSksCiAgICAgICAg'
        'ICAgIHttZW1iZXIudmFsdWUgZm9yIG1lbWJlciBpbiBGZWVkUHJvZmlsZVN0YXRlfSwKICAgICAg'
        'ICApCgogICAgZGVmIHRlc3Rfc2NoZW1hX3ZlcnNpb25fMV9pc19yZWplY3RlZF93aXRoX2xvY2F0'
        'aW9uKHNlbGYpIC0+IE5vbmU6CiAgICAgICAgd2l0aCBzZWxmLmFzc2VydFJhaXNlc1JlZ2V4KAog'
        'ICAgICAgICAgICBMb29wUmVnaXN0cnlDb25maWdFcnJvciwKICAgICAgICAgICAgciJzY2hlbWFf'
        'dmVyc2lvbl8xXC5qc29uOlwkXC5zY2hlbWFfdmVyc2lvbjogZXhwZWN0ZWQgaW50ZWdlciBjb25z'
        'dGFudCAyIiwKICAgICAgICApOgogICAgICAgICAgICBKc29uTG9vcFJlZ2lzdHJ5KEZJWFRVUkVT'
        'IC8gInNjaGVtYV92ZXJzaW9uXzEuanNvbiIpLnJlZ2lzdGVyZWRfbG9vcHMoKQoKICAgIGRlZiB0'
        'ZXN0X21pc3NpbmdfbG9vcF9pZF9pc19yZWplY3RlZF93aXRoX2xvY2F0aW9uKHNlbGYpIC0+IE5v'
        'bmU6CiAgICAgICAgd2l0aCBzZWxmLmFzc2VydFJhaXNlc1JlZ2V4KExvb3BSZWdpc3RyeUNvbmZp'
        'Z0Vycm9yLCByIlwkXC5sb29wc1xbMFxdXC5sb29wX2lkIik6CiAgICAgICAgICAgIEpzb25Mb29w'
        'UmVnaXN0cnkoRklYVFVSRVMgLyAibWlzc2luZ19sb29wX2lkLmpzb24iKS5yZWdpc3RlcmVkX2xv'
        'b3BzKCkKCiAgICBkZWYgdGVzdF9kdXBsaWNhdGVfbG9vcF9pZF9pc19yZWplY3RlZF93aXRoX2xv'
        'Y2F0aW9uKHNlbGYpIC0+IE5vbmU6CiAgICAgICAgd2l0aCBzZWxmLmFzc2VydFJhaXNlc1JlZ2V4'
        'KExvb3BSZWdpc3RyeUNvbmZpZ0Vycm9yLCByIlwkXC5sb29wc1xbMVxdXC5sb29wX2lkIik6CiAg'
        'ICAgICAgICAgIEpzb25Mb29wUmVnaXN0cnkoRklYVFVSRVMgLyAiZHVwbGljYXRlX2xvb3BfaWQu'
        'anNvbiIpLnJlZ2lzdGVyZWRfbG9vcHMoKQoKICAgIGRlZiB0ZXN0X21hbGZvcm1lZF9qc29uX2lz'
        'X3JlamVjdGVkX3dpdGhfbGluZV9hbmRfY29sdW1uKHNlbGYpIC0+IE5vbmU6CiAgICAgICAgd2l0'
        'aCBzZWxmLmFzc2VydFJhaXNlc1JlZ2V4KAogICAgICAgICAgICBMb29wUmVnaXN0cnlDb25maWdF'
        'cnJvciwgciJtYWxmb3JtZWRcLmpzb246IG1hbGZvcm1lZCBKU09OIGF0IGxpbmUgWzAtOV0rLCBj'
        'b2x1bW4gWzAtOV0rIgogICAgICAgICk6CiAgICAgICAgICAgIEpzb25Mb29wUmVnaXN0cnkoRklY'
        'VFVSRVMgLyAibWFsZm9ybWVkLmpzb24iKS5yZWdpc3RlcmVkX2xvb3BzKCkKCiAgICBkZWYgdGVz'
        'dF9hYnNlbnRfZmlsZV9pc19yZWplY3RlZF9leHBsaWNpdGx5KHNlbGYpIC0+IE5vbmU6CiAgICAg'
        'ICAgd2l0aCB0ZW1wZmlsZS5UZW1wb3JhcnlEaXJlY3RvcnkoKSBhcyB0ZW1wb3Jhcnk6CiAgICAg'
        'ICAgICAgIG1pc3NpbmcgPSBQYXRoKHRlbXBvcmFyeSkgLyAiYWJzZW50Lmpzb24iCiAgICAgICAg'
        'ICAgIHdpdGggc2VsZi5hc3NlcnRSYWlzZXNSZWdleChMb29wUmVnaXN0cnlDb25maWdFcnJvciwg'
        'ciJhYnNlbnRcLmpzb246IGNvbmZpZ3VyYXRpb24gZmlsZSBkb2VzIG5vdCBleGlzdCIpOgogICAg'
        'ICAgICAgICAgICAgSnNvbkxvb3BSZWdpc3RyeShtaXNzaW5nKS5yZWdpc3RlcmVkX2xvb3BzKCkK'
        'CiAgICBkZWYgdGVzdF91bnJlYWRhYmxlX3BhdGhfaXNfcmVqZWN0ZWRfZXhwbGljaXRseShzZWxm'
        'KSAtPiBOb25lOgogICAgICAgIHdpdGggdGVtcGZpbGUuVGVtcG9yYXJ5RGlyZWN0b3J5KCkgYXMg'
        'dGVtcG9yYXJ5OgogICAgICAgICAgICBkaXJlY3RvcnkgPSBQYXRoKHRlbXBvcmFyeSkgLyAibm90'
        'LWEtZmlsZS5qc29uIgogICAgICAgICAgICBkaXJlY3RvcnkubWtkaXIoKQogICAgICAgICAgICB3'
        'aXRoIHNlbGYuYXNzZXJ0UmFpc2VzUmVnZXgoTG9vcFJlZ2lzdHJ5Q29uZmlnRXJyb3IsIHIiY29u'
        'ZmlndXJhdGlvbiBmaWxlIGlzIHVucmVhZGFibGUiKToKICAgICAgICAgICAgICAgIEpzb25Mb29w'
        'UmVnaXN0cnkoZGlyZWN0b3J5KS5yZWdpc3RlcmVkX2xvb3BzKCkKCiAgICBkZWYgdGVzdF9pbnZh'
        'bGlkX2ZlZWRfcHJvZmlsZXNfYXJlX3JlamVjdGVkX3dpdGhfbG9jYXRpb24oc2VsZikgLT4gTm9u'
        'ZToKICAgICAgICByb3cgPSAiJC5sb29wc1swXSIKICAgICAgICBlbnRyeSA9IGYie3Jvd30uZmVl'
        'ZF9wcm9maWxlc1swXSIKCiAgICAgICAgZGVmIHdpdGhvdXQobWFwcGluZzogZGljdCwga2V5OiBz'
        'dHIpIC0+IGRpY3Q6CiAgICAgICAgICAgIHJldHVybiB7bmFtZTogdmFsdWUgZm9yIG5hbWUsIHZh'
        'bHVlIGluIG1hcHBpbmcuaXRlbXMoKSBpZiBuYW1lICE9IGtleX0KCiAgICAgICAgY2FzZXMgPSB7'
        'CiAgICAgICAgICAgICJyb3cgbWlzc2luZyBmZWVkX3Byb2ZpbGVzIjogKGxhbWJkYSBkOiBkWyJs'
        'b29wcyJdLl9fc2V0aXRlbV9fKDAsIHdpdGhvdXQoZFsibG9vcHMiXVswXSwgImZlZWRfcHJvZmls'
        'ZXMiKSksIGYie3Jvd30uZmVlZF9wcm9maWxlcyIsICJyZXF1aXJlZCBmaWVsZCBpcyBtaXNzaW5n'
        'IiksCiAgICAgICAgICAgICJyb3cgdW5rbm93biBmaWVsZCI6IChsYW1iZGEgZDogZFsibG9vcHMi'
        'XVswXS5fX3NldGl0ZW1fXygiZ3JhbW1hciIsICJ4IiksIGYie3Jvd30uZ3JhbW1hciIsICJmaWVs'
        'ZCBpcyBub3QgZGVmaW5lZCBieSBzY2hlbWEgdjIiKSwKICAgICAgICAgICAgImZlZWRfcHJvZmls'
        'ZXMgbm90IGFuIGFycmF5IjogKGxhbWJkYSBkOiBkWyJsb29wcyJdWzBdLl9fc2V0aXRlbV9fKCJm'
        'ZWVkX3Byb2ZpbGVzIiwge30pLCBmIntyb3d9LmZlZWRfcHJvZmlsZXMiLCAiZXhwZWN0ZWQgYW4g'
        'YXJyYXkiKSwKICAgICAgICAgICAgImZlZWRfcHJvZmlsZXMgZW1wdHkiOiAobGFtYmRhIGQ6IGRb'
        'Imxvb3BzIl1bMF0uX19zZXRpdGVtX18oImZlZWRfcHJvZmlsZXMiLCBbXSksIGYie3Jvd30uZmVl'
        'ZF9wcm9maWxlcyIsICJleHBlY3RlZCBhdCBsZWFzdCBvbmUgZmVlZCBwcm9maWxlIiksCiAgICAg'
        'ICAgICAgICJlbnRyeSBub3QgYW4gb2JqZWN0IjogKGxhbWJkYSBkOiBkWyJsb29wcyJdWzBdWyJm'
        'ZWVkX3Byb2ZpbGVzIl0uX19zZXRpdGVtX18oMCwgInNoYXJlZC1kZXYtbG9vcCIpLCBlbnRyeSwg'
        'ImV4cGVjdGVkIGFuIG9iamVjdCIpLAogICAgICAgICAgICAiZW50cnkgbWlzc2luZyBiYXNpcyI6'
        'IChsYW1iZGEgZDogZFsibG9vcHMiXVswXVsiZmVlZF9wcm9maWxlcyJdLl9fc2V0aXRlbV9fKDAs'
        'IHdpdGhvdXQoZFsibG9vcHMiXVswXVsiZmVlZF9wcm9maWxlcyJdWzBdLCAiYmFzaXMiKSksIGYi'
        'e2VudHJ5fS5iYXNpcyIsICJyZXF1aXJlZCBmaWVsZCBpcyBtaXNzaW5nIiksCiAgICAgICAgICAg'
        'ICJlbnRyeSB1bmtub3duIGZpZWxkIjogKGxhbWJkYSBkOiBkWyJsb29wcyJdWzBdWyJmZWVkX3By'
        'b2ZpbGVzIl1bMF0uX19zZXRpdGVtX18oInBhdGhzIiwgWyJ4Il0pLCBmIntlbnRyeX0ucGF0aHMi'
        'LCAiZmllbGQgaXMgbm90IGRlZmluZWQgYnkgc2NoZW1hIHYyIiksCiAgICAgICAgICAgICJ1bmtu'
        'b3duIHByb2ZpbGUiOiAobGFtYmRhIGQ6IGRbImxvb3BzIl1bMF1bImZlZWRfcHJvZmlsZXMiXVsw'
        'XS5fX3NldGl0ZW1fXygicHJvZmlsZSIsICJhZGFwdGVyLXlhbWwiKSwgZiJ7ZW50cnl9LnByb2Zp'
        'bGUiLCAiY2xvc2VkIGZlZWQtcHJvZmlsZSB2b2NhYnVsYXJ5IiksCiAgICAgICAgICAgICJwcm9m'
        'aWxlIG5vdCBhIHN0cmluZyI6IChsYW1iZGEgZDogZFsibG9vcHMiXVswXVsiZmVlZF9wcm9maWxl'
        'cyJdWzBdLl9fc2V0aXRlbV9fKCJwcm9maWxlIiwgMSksIGYie2VudHJ5fS5wcm9maWxlIiwgImNs'
        'b3NlZCBmZWVkLXByb2ZpbGUgdm9jYWJ1bGFyeSIpLAogICAgICAgICAgICAiZHVwbGljYXRlIHBy'
        'b2ZpbGUiOiAobGFtYmRhIGQ6IGRbImxvb3BzIl1bMF1bImZlZWRfcHJvZmlsZXMiXVsxXS5fX3Nl'
        'dGl0ZW1fXygicHJvZmlsZSIsICJzaGFyZWQtZGV2LWxvb3AiKSwgZiJ7cm93fS5mZWVkX3Byb2Zp'
        'bGVzWzFdLnByb2ZpbGUiLCAiZHVwbGljYXRlIGZlZWQgcHJvZmlsZSBmaXJzdCBkZWNsYXJlZCBh'
        'dCIpLAogICAgICAgICAgICAidW5zdXBwb3J0ZWQgdmVyc2lvbiI6IChsYW1iZGEgZDogZFsibG9v'
        'cHMiXVswXVsiZmVlZF9wcm9maWxlcyJdWzBdLl9fc2V0aXRlbV9fKCJ2ZXJzaW9uIiwgMiksIGYi'
        'e2VudHJ5fS52ZXJzaW9uIiwgInN1cHBvcnRlZCBpbnRlZ2VyIHZlcnNpb24iKSwKICAgICAgICAg'
        'ICAgImJvb2xlYW4gdmVyc2lvbiI6IChsYW1iZGEgZDogZFsibG9vcHMiXVswXVsiZmVlZF9wcm9m'
        'aWxlcyJdWzBdLl9fc2V0aXRlbV9fKCJ2ZXJzaW9uIiwgVHJ1ZSksIGYie2VudHJ5fS52ZXJzaW9u'
        'IiwgInN1cHBvcnRlZCBpbnRlZ2VyIHZlcnNpb24iKSwKICAgICAgICAgICAgInN0cmluZyB2ZXJz'
        'aW9uIjogKGxhbWJkYSBkOiBkWyJsb29wcyJdWzBdWyJmZWVkX3Byb2ZpbGVzIl1bMF0uX19zZXRp'
        'dGVtX18oInZlcnNpb24iLCAiMSIpLCBmIntlbnRyeX0udmVyc2lvbiIsICJzdXBwb3J0ZWQgaW50'
        'ZWdlciB2ZXJzaW9uIiksCiAgICAgICAgICAgICJ1bmtub3duIHN0YXRlIjogKGxhbWJkYSBkOiBk'
        'WyJsb29wcyJdWzBdWyJmZWVkX3Byb2ZpbGVzIl1bMF0uX19zZXRpdGVtX18oInN0YXRlIiwgImFj'
        'dGl2ZSIpLCBmIntlbnRyeX0uc3RhdGUiLCAiZXhwZWN0ZWQgbGl2ZSBvciBoaXN0b3JpY2FsIiks'
        'CiAgICAgICAgICAgICJzdGF0ZSBub3QgYSBzdHJpbmciOiAobGFtYmRhIGQ6IGRbImxvb3BzIl1b'
        'MF1bImZlZWRfcHJvZmlsZXMiXVswXS5fX3NldGl0ZW1fXygic3RhdGUiLCAxKSwgZiJ7ZW50cnl9'
        'LnN0YXRlIiwgImV4cGVjdGVkIGxpdmUgb3IgaGlzdG9yaWNhbCIpLAogICAgICAgICAgICAicHJv'
        'ZmlsZSBudWxsIjogKGxhbWJkYSBkOiBkWyJsb29wcyJdWzBdWyJmZWVkX3Byb2ZpbGVzIl1bMF0u'
        'X19zZXRpdGVtX18oInByb2ZpbGUiLCBOb25lKSwgZiJ7ZW50cnl9LnByb2ZpbGUiLCAiY2xvc2Vk'
        'IGZlZWQtcHJvZmlsZSB2b2NhYnVsYXJ5IiksCiAgICAgICAgICAgICJsZWRnZXIgbGl2ZSBhbmQg'
        'aGlzdG9yaWNhbCI6IChsYW1iZGEgZDogZFsibG9vcHMiXVswXS5fX3NldGl0ZW1fXygiZmVlZF9w'
        'cm9maWxlcyIsIFtkaWN0KGRbImxvb3BzIl1bMF1bImZlZWRfcHJvZmlsZXMiXVsyXSwgcHJvZmls'
        'ZT0icmVtYWluaW5nLWxvb3AiLCBzdGF0ZT0ibGl2ZSIpLCBkWyJsb29wcyJdWzBdWyJmZWVkX3By'
        'b2ZpbGVzIl1bMl1dKSwgZiJ7cm93fS5mZWVkX3Byb2ZpbGVzWzFdLnByb2ZpbGUiLCAic3VyZmFj'
        'ZSByZWNlaXB0LWxlZGdlciBpcyBhbHJlYWR5IGNvdmVyZWQgYnkiKSwKICAgICAgICAgICAgInR3'
        'byBsaXZlIGxpZmVjeWNsZSByZWFkZXJzIjogKGxhbWJkYSBkOiBkWyJsb29wcyJdWzBdLl9fc2V0'
        'aXRlbV9fKCJmZWVkX3Byb2ZpbGVzIiwgW2RbImxvb3BzIl1bMF1bImZlZWRfcHJvZmlsZXMiXVsw'
        'XSwgZGljdChkWyJsb29wcyJdWzBdWyJmZWVkX3Byb2ZpbGVzIl1bMF0sIHByb2ZpbGU9InJlbWFp'
        'bmluZy1sb29wIildKSwgZiJ7cm93fS5mZWVkX3Byb2ZpbGVzWzFdLnByb2ZpbGUiLCAic3VyZmFj'
        'ZSBkZWNpc2lvbi1yZWdpc3RlcnMgaXMgYWxyZWFkeSBjb3ZlcmVkIGJ5IiksCiAgICAgICAgICAg'
        'ICJyZW1haW5pbmcgcmVhZCB0d2ljZSI6IChsYW1iZGEgZDogZFsibG9vcHMiXVswXS5fX3NldGl0'
        'ZW1fXygiZmVlZF9wcm9maWxlcyIsIFtkaWN0KGRbImxvb3BzIl1bMF1bImZlZWRfcHJvZmlsZXMi'
        'XVswXSwgcHJvZmlsZT0icmVtYWluaW5nLWxvb3AiKSwgZFsibG9vcHMiXVswXVsiZmVlZF9wcm9m'
        'aWxlcyJdWzFdXSksIGYie3Jvd30uZmVlZF9wcm9maWxlc1sxXS5wcm9maWxlIiwgInN1cmZhY2Ug'
        'c3RhdHVzLXJlbWFpbmluZyBpcyBhbHJlYWR5IGNvdmVyZWQgYnkiKSwKICAgICAgICAgICAgIm5v'
        'IGxpdmUgcHJvZmlsZSI6IChsYW1iZGEgZDogW2VudHJ5Ll9fc2V0aXRlbV9fKCJzdGF0ZSIsICJo'
        'aXN0b3JpY2FsIikgZm9yIGVudHJ5IGluIGRbImxvb3BzIl1bMF1bImZlZWRfcHJvZmlsZXMiXV0s'
        'IGYie3Jvd30uZmVlZF9wcm9maWxlcyIsICJleHBlY3RlZCBhdCBsZWFzdCBvbmUgbGl2ZSBmZWVk'
        'IHByb2ZpbGUiKSwKICAgICAgICAgICAgImVtcHR5IGJhc2lzIjogKGxhbWJkYSBkOiBkWyJsb29w'
        'cyJdWzBdWyJmZWVkX3Byb2ZpbGVzIl1bMF0uX19zZXRpdGVtX18oImJhc2lzIiwgIiIpLCBmIntl'
        'bnRyeX0uYmFzaXMiLCAiZXhwZWN0ZWQgYSBub24tZW1wdHkgc3RyaW5nIiksCiAgICAgICAgICAg'
        'ICJhYnNvbHV0ZSBiYXNpcyI6IChsYW1iZGEgZDogZFsibG9vcHMiXVswXVsiZmVlZF9wcm9maWxl'
        'cyJdWzBdLl9fc2V0aXRlbV9fKCJiYXNpcyIsICIvZXRjL3Bhc3N3ZCIpLCBmIntlbnRyeX0uYmFz'
        'aXMiLCAibm9ybWFsaXplZCByZXBvc2l0b3J5LXJlbGF0aXZlIHBhdGgiKSwKICAgICAgICAgICAg'
        'InRyYXZlcnNpbmcgYmFzaXMiOiAobGFtYmRhIGQ6IGRbImxvb3BzIl1bMF1bImZlZWRfcHJvZmls'
        'ZXMiXVswXS5fX3NldGl0ZW1fXygiYmFzaXMiLCAicHJvamVjdHMvLi4veC5tZCIpLCBmIntlbnRy'
        'eX0uYmFzaXMiLCAibm9ybWFsaXplZCByZXBvc2l0b3J5LXJlbGF0aXZlIHBhdGgiKSwKICAgICAg'
        'ICAgICAgImJhY2tzbGFzaCBiYXNpcyI6IChsYW1iZGEgZDogZFsibG9vcHMiXVswXVsiZmVlZF9w'
        'cm9maWxlcyJdWzBdLl9fc2V0aXRlbV9fKCJiYXNpcyIsICJwcm9qZWN0c1xccGVjXFxBR0VOVFMu'
        'bWQiKSwgZiJ7ZW50cnl9LmJhc2lzIiwgIm5vcm1hbGl6ZWQgcmVwb3NpdG9yeS1yZWxhdGl2ZSBw'
        'YXRoIiksCiAgICAgICAgfQogICAgICAgIGZvciBuYW1lLCAobXV0YXRlLCBsb2NhdGlvbiwgbWVz'
        'c2FnZSkgaW4gY2FzZXMuaXRlbXMoKToKICAgICAgICAgICAgd2l0aCBzZWxmLnN1YlRlc3QoY2Fz'
        'ZT1uYW1lKToKICAgICAgICAgICAgICAgIGRvY3VtZW50ID0gY29weS5kZWVwY29weSh2YWxpZF9k'
        'b2N1bWVudCgpKQogICAgICAgICAgICAgICAgbXV0YXRlKGRvY3VtZW50KQogICAgICAgICAgICAg'
        'ICAgd2l0aCBzZWxmLmFzc2VydFJhaXNlcyhMb29wUmVnaXN0cnlDb25maWdFcnJvcikgYXMgcmFp'
        'c2VkOgogICAgICAgICAgICAgICAgICAgIHNlbGYubG9hZChkb2N1bWVudCkKICAgICAgICAgICAg'
        'ICAgIHRleHQgPSBzdHIocmFpc2VkLmV4Y2VwdGlvbikKICAgICAgICAgICAgICAgIHNlbGYuYXNz'
        'ZXJ0SW4oZiI6e2xvY2F0aW9ufTogIiwgdGV4dCkKICAgICAgICAgICAgICAgIHNlbGYuYXNzZXJ0'
        'SW4obWVzc2FnZSwgdGV4dCkKCiAgICBkZWYgdGVzdF9mYWlsdXJlc19kb19ub3RfZWNob19kb2N1'
        'bWVudF92YWx1ZXMoc2VsZikgLT4gTm9uZToKICAgICAgICBzZW50aW5lbCA9ICJ6enNlbnRpbmVs'
        'enoiCiAgICAgICAgY2FzZXMgPSB7CiAgICAgICAgICAgICJsb29wX2lkIjogbGFtYmRhIGQ6IGRb'
        'Imxvb3BzIl1bMF0uX19zZXRpdGVtX18oImxvb3BfaWQiLCBzZW50aW5lbC51cHBlcigpKSwKICAg'
        'ICAgICAgICAgImxvb3BfaW5pdF9wYXRoIjogbGFtYmRhIGQ6IGRbImxvb3BzIl1bMF0uX19zZXRp'
        'dGVtX18oImxvb3BfaW5pdF9wYXRoIiwgZiIve3NlbnRpbmVsfSIpLAogICAgICAgICAgICAicHJv'
        'ZmlsZSI6IGxhbWJkYSBkOiBkWyJsb29wcyJdWzBdWyJmZWVkX3Byb2ZpbGVzIl1bMF0uX19zZXRp'
        'dGVtX18oInByb2ZpbGUiLCBzZW50aW5lbCksCiAgICAgICAgICAgICJ2ZXJzaW9uIjogbGFtYmRh'
        'IGQ6IGRbImxvb3BzIl1bMF1bImZlZWRfcHJvZmlsZXMiXVswXS5fX3NldGl0ZW1fXygidmVyc2lv'
        'biIsIHNlbnRpbmVsKSwKICAgICAgICAgICAgInN0YXRlIjogbGFtYmRhIGQ6IGRbImxvb3BzIl1b'
        'MF1bImZlZWRfcHJvZmlsZXMiXVswXS5fX3NldGl0ZW1fXygic3RhdGUiLCBzZW50aW5lbCksCiAg'
        'ICAgICAgICAgICJiYXNpcyI6IGxhbWJkYSBkOiBkWyJsb29wcyJdWzBdWyJmZWVkX3Byb2ZpbGVz'
        'Il1bMF0uX19zZXRpdGVtX18oImJhc2lzIiwgZiIuLi97c2VudGluZWx9IiksCiAgICAgICAgfQog'
        'ICAgICAgIGZvciBuYW1lLCBtdXRhdGUgaW4gY2FzZXMuaXRlbXMoKToKICAgICAgICAgICAgd2l0'
        'aCBzZWxmLnN1YlRlc3QoZmllbGQ9bmFtZSk6CiAgICAgICAgICAgICAgICBkb2N1bWVudCA9IGNv'
        'cHkuZGVlcGNvcHkodmFsaWRfZG9jdW1lbnQoKSkKICAgICAgICAgICAgICAgIG11dGF0ZShkb2N1'
        'bWVudCkKICAgICAgICAgICAgICAgIHdpdGggc2VsZi5hc3NlcnRSYWlzZXMoTG9vcFJlZ2lzdHJ5'
        'Q29uZmlnRXJyb3IpIGFzIHJhaXNlZDoKICAgICAgICAgICAgICAgICAgICBzZWxmLmxvYWQoZG9j'
        'dW1lbnQpCiAgICAgICAgICAgICAgICBzZWxmLmFzc2VydE5vdEluKHNlbnRpbmVsLCBzdHIocmFp'
        'c2VkLmV4Y2VwdGlvbikubG93ZXIoKSkKCiAgICBkZWYgdGVzdF9hZGRpdGlvbmFsX2xvb3BzX25l'
        'ZWRfZW50cmllc19vbmx5KHNlbGYpIC0+IE5vbmU6CiAgICAgICAgZG9jdW1lbnQgPSB2YWxpZF9k'
        'b2N1bWVudCgpCiAgICAgICAgZG9jdW1lbnRbImxvb3BzIl0uYXBwZW5kKAogICAgICAgICAgICB7'
        'CiAgICAgICAgICAgICAgICAibG9vcF9pZCI6ICJzZWNvbmQtbG9vcCIsCiAgICAgICAgICAgICAg'
        'ICAibG9vcF9pbml0X3BhdGgiOiAicHJvamVjdHMvc2Vjb25kL2xvb3AvTE9PUF9JTklULm1kIiwK'
        'ICAgICAgICAgICAgICAgICJmZWVkX3Byb2ZpbGVzIjogWwogICAgICAgICAgICAgICAgICAgIHsi'
        'cHJvZmlsZSI6IHByb2ZpbGUsICJ2ZXJzaW9uIjogMSwgInN0YXRlIjogc3RhdGUsICJiYXNpcyI6'
        'ICJwcm9qZWN0cy9zZWNvbmQvQUdFTlRTLm1kIn0KICAgICAgICAgICAgICAgICAgICBmb3IgcHJv'
        'ZmlsZSwgc3RhdGUgaW4gKAogICAgICAgICAgICAgICAgICAgICAgICAoInNoYXJlZC1kZXYtbG9v'
        'cCIsICJsaXZlIiksCiAgICAgICAgICAgICAgICAgICAgICAgICgibG9vcC1yZWNlaXB0cy1sZWRn'
        'ZXIiLCAiaGlzdG9yaWNhbCIpLAogICAgICAgICAgICAgICAgICAgICAgICAoImFnZW50cnVucy1q'
        'c29uIiwgImhpc3RvcmljYWwiKSwKICAgICAgICAgICAgICAgICAgICApCiAgICAgICAgICAgICAg'
        'ICBdLAogICAgICAgICAgICB9CiAgICAgICAgKQogICAgICAgIGxvb3BzID0gc2VsZi5sb2FkKGRv'
        'Y3VtZW50KQogICAgICAgIHNlbGYuYXNzZXJ0RXF1YWwoW2xvb3AubG9vcF9pZCBmb3IgbG9vcCBp'
        'biBsb29wc10sIFsicGVjIiwgInNlY29uZC1sb29wIl0pCiAgICAgICAgc2VsZi5hc3NlcnRFcXVh'
        'bCgKICAgICAgICAgICAgW3Byb2ZpbGUucHJvZmlsZSBmb3IgcHJvZmlsZSBpbiBsb29wc1sxXS5m'
        'ZWVkX3Byb2ZpbGVzXSwKICAgICAgICAgICAgWyJzaGFyZWQtZGV2LWxvb3AiLCAibG9vcC1yZWNl'
        'aXB0cy1sZWRnZXIiLCAiYWdlbnRydW5zLWpzb24iXSwKICAgICAgICApCiAgICAgICAgc2VsZi5h'
        'c3NlcnRFcXVhbChsb29wc1sxXS5mZWVkX3Byb2ZpbGVzWzJdLnN0YXRlLCBGZWVkUHJvZmlsZVN0'
        'YXRlLkhJU1RPUklDQUwpCgogICAgZGVmIHRlc3RfaW52YWxpZF9kb2N1bWVudF9uZXZlcl9yZXR1'
        'cm5zX3BhcnRpYWxfb3JfZW1wdHlfc2V0KHNlbGYpIC0+IE5vbmU6CiAgICAgICAgZm9yIGZpeHR1'
        'cmUgaW4gKAogICAgICAgICAgICAic2NoZW1hX3ZlcnNpb25fMS5qc29uIiwKICAgICAgICAgICAg'
        'Im1pc3NpbmdfbG9vcF9pZC5qc29uIiwKICAgICAgICAgICAgImR1cGxpY2F0ZV9sb29wX2lkLmpz'
        'b24iLAogICAgICAgICAgICAibWFsZm9ybWVkLmpzb24iLAogICAgICAgICk6CiAgICAgICAgICAg'
        'IHdpdGggc2VsZi5zdWJUZXN0KGZpeHR1cmU9Zml4dHVyZSk6CiAgICAgICAgICAgICAgICB3aXRo'
        'IHNlbGYuYXNzZXJ0UmFpc2VzKExvb3BSZWdpc3RyeUNvbmZpZ0Vycm9yKToKICAgICAgICAgICAg'
        'ICAgICAgICBKc29uTG9vcFJlZ2lzdHJ5KEZJWFRVUkVTIC8gZml4dHVyZSkucmVnaXN0ZXJlZF9s'
        'b29wcygpCiAgICAgICAgZG9jdW1lbnQgPSB2YWxpZF9kb2N1bWVudCgpCiAgICAgICAgZG9jdW1l'
        'bnRbImxvb3BzIl0uYXBwZW5kKGNvcHkuZGVlcGNvcHkoZG9jdW1lbnRbImxvb3BzIl1bMF0pKQog'
        'ICAgICAgIGRvY3VtZW50WyJsb29wcyJdWzFdWyJsb29wX2lkIl0gPSAic2Vjb25kLWxvb3AiCiAg'
        'ICAgICAgZG9jdW1lbnRbImxvb3BzIl1bMV1bImZlZWRfcHJvZmlsZXMiXVswXVsic3RhdGUiXSA9'
        'ICJzdGFsZSIKICAgICAgICB3aXRoIHNlbGYuYXNzZXJ0UmFpc2VzUmVnZXgoTG9vcFJlZ2lzdHJ5'
        'Q29uZmlnRXJyb3IsIHIiXCRcLmxvb3BzXFsxXF1cLmZlZWRfcHJvZmlsZXNcWzBcXVwuc3RhdGUi'
        'KToKICAgICAgICAgICAgc2VsZi5sb2FkKGRvY3VtZW50KQoKCmlmIF9fbmFtZV9fID09ICJfX21h'
        'aW5fXyI6CiAgICB1bml0dGVzdC5tYWluKCkK'
    ),
    '6875f50023f1ad34a45c1af4b0a65316260c45aa05562ce45bb2d9bd8fd13c7e': (
        'ewogICJsb29wcyI6IFsKICAgIHsKICAgICAgImZlZWRfcHJvZmlsZXMiOiBbCiAgICAgICAgewog'
        'ICAgICAgICAgImJhc2lzIjogInByb2plY3RzL3BlYy9leGVjdXRpb24vX0Nvb3JkaW5hdGlvbi9f'
        'REVDSVNJT05TL0QtUEVDLTk0X293bmVyX2RpcmVjdGlvbl9sb29wX21pZ3JhdGlvbl8yMDI2LTA5'
        'LTI1Lm1kIiwKICAgICAgICAgICJwcm9maWxlIjogInNoYXJlZC1kZXYtbG9vcCIsCiAgICAgICAg'
        'ICAic3RhdGUiOiAibGl2ZSIsCiAgICAgICAgICAidmVyc2lvbiI6IDEKICAgICAgICB9CiAgICAg'
        'IF0sCiAgICAgICJsb29wX2lkIjogInBlYyIsCiAgICAgICJsb29wX2luaXRfcGF0aCI6ICJwcm9q'
        'ZWN0cy9wZWMvbG9vcC9MT09QX0lOSVQubWQiCiAgICB9LAogICAgewogICAgICAiZmVlZF9wcm9m'
        'aWxlcyI6IFsKICAgICAgICB7CiAgICAgICAgICAiYmFzaXMiOiAicHJvamVjdHMvcGVjL2V4ZWN1'
        'dGlvbi9fQ29vcmRpbmF0aW9uL19ERUNJU0lPTlMvRC1QRUMtOTRfb3duZXJfZGlyZWN0aW9uX2xv'
        'b3BfbWlncmF0aW9uXzIwMjYtMDktMjUubWQiLAogICAgICAgICAgInByb2ZpbGUiOiAic2hhcmVk'
        'LWRldi1sb29wIiwKICAgICAgICAgICJzdGF0ZSI6ICJsaXZlIiwKICAgICAgICAgICJ2ZXJzaW9u'
        'IjogMQogICAgICAgIH0KICAgICAgXSwKICAgICAgImxvb3BfaWQiOiAicGVjIiwKICAgICAgImxv'
        'b3BfaW5pdF9wYXRoIjogInNvbWV3aGVyZS9lbHNlL0xPT1BfSU5JVC5tZCIKICAgIH0KICBdLAog'
        'ICJzY2hlbWFfdmVyc2lvbiI6IDIKfQo='
    ),
    '6e1321e32f72b0fc9f9d987a3175266550a23fa40230df0a61418cfccd4c7961': (
        'ewogICJsb29wcyI6IFsKICAgIHsKICAgICAgImZlZWRfcHJvZmlsZXMiOiBbCiAgICAgICAgewog'
        'ICAgICAgICAgImJhc2lzIjogInByb2plY3RzL3BlYy9leGVjdXRpb24vX0Nvb3JkaW5hdGlvbi9f'
        'REVDSVNJT05TL0QtUEVDLTg2X3NjYV8wMDVfZmVlZF9tb2RlbF9yZWJhc2VsaW5lXzIwMjYtMDkt'
        'MjMubWQiLAogICAgICAgICAgInByb2ZpbGUiOiAicmVtYWluaW5nLWxvb3AiLAogICAgICAgICAg'
        'InN0YXRlIjogImxpdmUiLAogICAgICAgICAgInZlcnNpb24iOiAxCiAgICAgICAgfQogICAgICBd'
        'LAogICAgICAibG9vcF9pZCI6ICJwZWMiLAogICAgICAibG9vcF9pbml0X3BhdGgiOiAicHJvamVj'
        'dHMvcGVjL2xvb3AvTE9PUF9JTklULm1kIgogICAgfQogIF0sCiAgInNjaGVtYV92ZXJzaW9uIjog'
        'Mgp9Cg=='
    ),
    'a509bfb74920172a86ac21aff6a67245cd3248c5d73ef4e7427966069099c8a9': (
        'IiIiVHlwZWQgY29yZSBjb250cmFjdCBmb3IgZGlzY292ZXJpbmcgdGhlIGxvb3BzIFBFQyBpcyBj'
        'b25maWd1cmVkIHRvIHNlcnZlLiIiIgoKZnJvbSBfX2Z1dHVyZV9fIGltcG9ydCBhbm5vdGF0aW9u'
        'cwoKZnJvbSBkYXRhY2xhc3NlcyBpbXBvcnQgZGF0YWNsYXNzCmZyb20gZW51bSBpbXBvcnQgRW51'
        'bQpmcm9tIHR5cGluZyBpbXBvcnQgUHJvdG9jb2wKCgpjbGFzcyBGZWVkUHJvZmlsZVN0YXRlKEVu'
        'dW0pOgogICAgIiIiV2hldGhlciBhIGRlY2xhcmVkIGZlZWQtcHJvZmlsZSBnZW5lcmF0aW9uIGlz'
        'IGxpdmUgb3IgaGlzdG9yaWNhbCBmb3IgaXRzIGxvb3AuIiIiCgogICAgTElWRSA9ICJsaXZlIgog'
        'ICAgSElTVE9SSUNBTCA9ICJoaXN0b3JpY2FsIgoKCkBkYXRhY2xhc3MoZnJvemVuPVRydWUsIHNs'
        'b3RzPVRydWUpCmNsYXNzIEZlZWRQcm9maWxlOgogICAgIiIiT25lIGNsb3NlZCwgUEVDLXZlcnNp'
        'b25lZCBmZWVkIHByb2ZpbGUgZGVjbGFyZWQgZm9yIGEgcmVnaXN0ZXJlZCBsb29wLgoKICAgIEEg'
        'cHJvZmlsZSBpcyBQRUMncyByZWFkaW5nIGh5cG90aGVzaXMgYWJvdXQgdGhlIGxvb3AncyBmaWxl'
        'IHRydXRoLCBuZXZlciB0aGUKICAgIGxvb3AncyB0cnV0aC4gYGBiYXNpc2BgIGlzIHRoZSByZXBv'
        'c2l0b3J5LXJlbGF0aXZlIGxvY2F0b3Igb2YgdGhlIGxvb3AncyBvd24KICAgIHJlY29yZCB0aGF0'
        'IHN1cHBvcnRzIHRoZSBkZWNsYXJhdGlvbi4KICAgICIiIgoKICAgIHByb2ZpbGU6IHN0cgogICAg'
        'dmVyc2lvbjogaW50CiAgICBzdGF0ZTogRmVlZFByb2ZpbGVTdGF0ZQogICAgYmFzaXM6IHN0cgoK'
        'CkBkYXRhY2xhc3MoZnJvemVuPVRydWUsIHNsb3RzPVRydWUpCmNsYXNzIFJlZ2lzdGVyZWRMb29w'
        'OgogICAgIiIiT25lIGNvbmZpZ3VyZWQgbG9vcCwgdGhlIGxvY2F0b3Igb2YgaXRzIGZpbGUgdHJ1'
        'dGgsIGFuZCBpdHMgZmVlZCBwcm9maWxlcy4iIiIKCiAgICBsb29wX2lkOiBzdHIKICAgIGxvb3Bf'
        'aW5pdF9wYXRoOiBzdHIKICAgIGZlZWRfcHJvZmlsZXM6IHR1cGxlW0ZlZWRQcm9maWxlLCAuLi5d'
        'CgoKY2xhc3MgTG9vcFJlZ2lzdHJ5KFByb3RvY29sKToKICAgICIiIkNvcmUtb3duZWQgY2FwYWJp'
        'bGl0eSBwb3J0IGZvciB0aGUgY29uZmlndXJlZCByZWdpc3RlcmVkLWxvb3Agc2V0LiIiIgoKICAg'
        'IGRlZiByZWdpc3RlcmVkX2xvb3BzKHNlbGYpIC0+IHR1cGxlW1JlZ2lzdGVyZWRMb29wLCAuLi5d'
        'OgogICAgICAgICIiIlJldHVybiB0aGUgY29tcGxldGUgdmFsaWRhdGVkIHJlZ2lzdGVyZWQtbG9v'
        'cCBzZXQuIiIiCiAgICAgICAgLi4uCg=='
    ),
    'aad704700748055e8f5cc1ec0c4f3a29c000c775994e1280dcf651952094678e': (
        'ewogICJsb29wcyI6IFsKICAgIHsKICAgICAgImZlZWRfcHJvZmlsZXMiOiBbCiAgICAgICAgewog'
        'ICAgICAgICAgImJhc2lzIjogInByb2plY3RzL3BlYy9leGVjdXRpb24vX0Nvb3JkaW5hdGlvbi9f'
        'REVDSVNJT05TL0QtUEVDLTk0X293bmVyX2RpcmVjdGlvbl9sb29wX21pZ3JhdGlvbl8yMDI2LTA5'
        'LTI1Lm1kIiwKICAgICAgICAgICJwcm9maWxlIjogInNoYXJlZC1kZXYtbG9vcCIsCiAgICAgICAg'
        'ICAic3RhdGUiOiAibGl2ZSIsCiAgICAgICAgICAidmVyc2lvbiI6IDEKICAgICAgICB9LAogICAg'
        'ICAgIHsKICAgICAgICAgICJiYXNpcyI6ICJwcm9qZWN0cy9wZWMvQUdFTlRTLm1kIiwKICAgICAg'
        'ICAgICJwcm9maWxlIjogInJlbWFpbmluZy1pdGVtcyIsCiAgICAgICAgICAic3RhdGUiOiAibGl2'
        'ZSIsCiAgICAgICAgICAidmVyc2lvbiI6IDEKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAg'
        'ICJiYXNpcyI6ICJwcm9qZWN0cy9wZWMvQUdFTlRTLm1kIiwKICAgICAgICAgICJwcm9maWxlIjog'
        'Imxvb3AtcmVjZWlwdHMtbGVkZ2VyIiwKICAgICAgICAgICJzdGF0ZSI6ICJoaXN0b3JpY2FsIiwK'
        'ICAgICAgICAgICJ2ZXJzaW9uIjogMQogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgImJh'
        'c2lzIjogInByb2plY3RzL3BlYy9leGVjdXRpb24vX0Nvb3JkaW5hdGlvbi9fREVDSVNJT05TL0Qt'
        'UEVDLTk0X293bmVyX2RpcmVjdGlvbl9sb29wX21pZ3JhdGlvbl8yMDI2LTA5LTI1Lm1kIiwKICAg'
        'ICAgICAgICJwcm9maWxlIjogImFnZW50cnVucy1qc29uIiwKICAgICAgICAgICJzdGF0ZSI6ICJo'
        'aXN0b3JpY2FsIiwKICAgICAgICAgICJ2ZXJzaW9uIjogMQogICAgICAgIH0KICAgICAgXSwKICAg'
        'ICAgImxvb3BfaWQiOiAicGVjIiwKICAgICAgImxvb3BfaW5pdF9wYXRoIjogInByb2plY3RzL3Bl'
        'Yy9sb29wL0xPT1BfSU5JVC5tZCIKICAgIH0KICBdLAogICJzY2hlbWFfdmVyc2lvbiI6IDIKfQo='
    ),
    'b05ed8719c59258998b1c483456b66bd8d4a4d3bc4f68cdd6fb5c02541db7106': (
        'ZnJvbSBfX2Z1dHVyZV9fIGltcG9ydCBhbm5vdGF0aW9ucwoKaW1wb3J0IGFzdAppbXBvcnQgZGF0'
        'YWNsYXNzZXMKaW1wb3J0IGluc3BlY3QKaW1wb3J0IHN5cwppbXBvcnQgc3lzY29uZmlnCmltcG9y'
        'dCB1bml0dGVzdApmcm9tIHBhdGhsaWIgaW1wb3J0IFBhdGgKCgpWMl9ST09UID0gUGF0aChfX2Zp'
        'bGVfXykucmVzb2x2ZSgpLnBhcmVudHNbMl0KU1JDX1JPT1QgPSBWMl9ST09UIC8gInNyYyIKc3lz'
        'LnBhdGguaW5zZXJ0KDAsIHN0cihTUkNfUk9PVCkpCgpmcm9tIHBlY192Mi5jb3JlLnBvcnRzLmxv'
        'b3BfcmVnaXN0cnkgaW1wb3J0ICggICMgbm9xYTogRTQwMgogICAgRmVlZFByb2ZpbGUsCiAgICBG'
        'ZWVkUHJvZmlsZVN0YXRlLAogICAgTG9vcFJlZ2lzdHJ5LAogICAgUmVnaXN0ZXJlZExvb3AsCikK'
        'CgpjbGFzcyBMb29wUmVnaXN0cnlDb250cmFjdFRlc3RzKHVuaXR0ZXN0LlRlc3RDYXNlKToKICAg'
        'IGRlZiB0ZXN0X3JlZ2lzdGVyZWRfbG9vcF9pc19pbW11dGFibGUoc2VsZikgLT4gTm9uZToKICAg'
        'ICAgICBwcm9maWxlID0gRmVlZFByb2ZpbGUoCiAgICAgICAgICAgICJzaGFyZWQtZGV2LWxvb3Ai'
        'LCAxLCBGZWVkUHJvZmlsZVN0YXRlLkxJVkUsICJwcm9qZWN0cy9wZWMvQUdFTlRTLm1kIgogICAg'
        'ICAgICkKICAgICAgICBsb29wID0gUmVnaXN0ZXJlZExvb3AoInBlYyIsICJwcm9qZWN0cy9wZWMv'
        'bG9vcC9MT09QX0lOSVQubWQiLCAocHJvZmlsZSwpKQogICAgICAgIHdpdGggc2VsZi5hc3NlcnRS'
        'YWlzZXMoZGF0YWNsYXNzZXMuRnJvemVuSW5zdGFuY2VFcnJvcik6CiAgICAgICAgICAgIGxvb3Au'
        'bG9vcF9pZCA9ICJyb290IiAgIyB0eXBlOiBpZ25vcmVbbWlzY10KICAgICAgICB3aXRoIHNlbGYu'
        'YXNzZXJ0UmFpc2VzKGRhdGFjbGFzc2VzLkZyb3plbkluc3RhbmNlRXJyb3IpOgogICAgICAgICAg'
        'ICBsb29wLmZlZWRfcHJvZmlsZXMgPSAoKSAgIyB0eXBlOiBpZ25vcmVbbWlzY10KICAgICAgICB3'
        'aXRoIHNlbGYuYXNzZXJ0UmFpc2VzKGRhdGFjbGFzc2VzLkZyb3plbkluc3RhbmNlRXJyb3IpOgog'
        'ICAgICAgICAgICBwcm9maWxlLnN0YXRlID0gRmVlZFByb2ZpbGVTdGF0ZS5ISVNUT1JJQ0FMICAj'
        'IHR5cGU6IGlnbm9yZVttaXNjXQoKICAgIGRlZiB0ZXN0X3JlZ2lzdGVyZWRfbG9vcF9jYXJyaWVz'
        'X3RoZV90eXBlZF9mZWVkX3Byb2ZpbGVfZmllbGQoc2VsZikgLT4gTm9uZToKICAgICAgICBzZWxm'
        'LmFzc2VydEVxdWFsKAogICAgICAgICAgICBbZmllbGQubmFtZSBmb3IgZmllbGQgaW4gZGF0YWNs'
        'YXNzZXMuZmllbGRzKFJlZ2lzdGVyZWRMb29wKV0sCiAgICAgICAgICAgIFsibG9vcF9pZCIsICJs'
        'b29wX2luaXRfcGF0aCIsICJmZWVkX3Byb2ZpbGVzIl0sCiAgICAgICAgKQogICAgICAgIHNlbGYu'
        'YXNzZXJ0RXF1YWwoCiAgICAgICAgICAgIFtmaWVsZC5uYW1lIGZvciBmaWVsZCBpbiBkYXRhY2xh'
        'c3Nlcy5maWVsZHMoRmVlZFByb2ZpbGUpXSwKICAgICAgICAgICAgWyJwcm9maWxlIiwgInZlcnNp'
        'b24iLCAic3RhdGUiLCAiYmFzaXMiXSwKICAgICAgICApCiAgICAgICAgc2VsZi5hc3NlcnRFcXVh'
        'bCgKICAgICAgICAgICAge21lbWJlci52YWx1ZSBmb3IgbWVtYmVyIGluIEZlZWRQcm9maWxlU3Rh'
        'dGV9LCB7ImxpdmUiLCAiaGlzdG9yaWNhbCJ9CiAgICAgICAgKQoKICAgIGRlZiB0ZXN0X3BvcnRf'
        'aGFzX29ubHlfdGhlX3R5cGVkX2NhcGFiaWxpdHlfbWV0aG9kKHNlbGYpIC0+IE5vbmU6CiAgICAg'
        'ICAgcHVibGljID0gW25hbWUgZm9yIG5hbWUgaW4gdmFycyhMb29wUmVnaXN0cnkpIGlmIG5vdCBu'
        'YW1lLnN0YXJ0c3dpdGgoIl8iKV0KICAgICAgICBzZWxmLmFzc2VydEVxdWFsKHB1YmxpYywgWyJy'
        'ZWdpc3RlcmVkX2xvb3BzIl0pCiAgICAgICAgc2lnbmF0dXJlID0gc3RyKGluc3BlY3Quc2lnbmF0'
        'dXJlKExvb3BSZWdpc3RyeS5yZWdpc3RlcmVkX2xvb3BzKSkKICAgICAgICBzZWxmLmFzc2VydElu'
        'KCJ0dXBsZVtSZWdpc3RlcmVkTG9vcCwgLi4uXSIsIHNpZ25hdHVyZSkKICAgICAgICBmb3IgZm9y'
        'YmlkZGVuIGluICgiUGF0aCIsICJqc29uIiwgImNvbmZpZyIsICJzZXJpYWxpemF0aW9uIiwgIkVy'
        'cm9yIik6CiAgICAgICAgICAgIHNlbGYuYXNzZXJ0Tm90SW4oZm9yYmlkZGVuLCBzaWduYXR1cmUp'
        'CgogICAgZGVmIHRlc3RfY29yZV9pbXBvcnRzX25vX2FkYXB0ZXJfb3Jfb3V0ZXJfaW9fbW9kdWxl'
        'KHNlbGYpIC0+IE5vbmU6CiAgICAgICAgY29yZV9yb290ID0gU1JDX1JPT1QgLyAicGVjX3YyIiAv'
        'ICJjb3JlIgogICAgICAgIGZvcmJpZGRlbiA9IHsicGVjX3YyLmFkYXB0ZXJzIiwgImpzb24iLCAi'
        'cGF0aGxpYiIsICJzb2NrZXQiLCAic3FsaXRlMyIsICJ1cmxsaWIifQogICAgICAgIGZvciBwYXRo'
        'IGluIGNvcmVfcm9vdC5yZ2xvYigiKi5weSIpOgogICAgICAgICAgICB0cmVlID0gYXN0LnBhcnNl'
        'KHBhdGgucmVhZF90ZXh0KGVuY29kaW5nPSJ1dGYtOCIpLCBmaWxlbmFtZT1zdHIocGF0aCkpCiAg'
        'ICAgICAgICAgIGltcG9ydHM6IHNldFtzdHJdID0gc2V0KCkKICAgICAgICAgICAgZm9yIG5vZGUg'
        'aW4gYXN0LndhbGsodHJlZSk6CiAgICAgICAgICAgICAgICBpZiBpc2luc3RhbmNlKG5vZGUsIGFz'
        'dC5JbXBvcnQpOgogICAgICAgICAgICAgICAgICAgIGltcG9ydHMudXBkYXRlKGFsaWFzLm5hbWUg'
        'Zm9yIGFsaWFzIGluIG5vZGUubmFtZXMpCiAgICAgICAgICAgICAgICBlbGlmIGlzaW5zdGFuY2Uo'
        'bm9kZSwgYXN0LkltcG9ydEZyb20pIGFuZCBub2RlLm1vZHVsZToKICAgICAgICAgICAgICAgICAg'
        'ICBpbXBvcnRzLmFkZChub2RlLm1vZHVsZSkKICAgICAgICAgICAgc2VsZi5hc3NlcnRGYWxzZSgK'
        'ICAgICAgICAgICAgICAgIGFueShuYW1lID09IGl0ZW0gb3IgbmFtZS5zdGFydHN3aXRoKGYie2l0'
        'ZW19LiIpIGZvciBuYW1lIGluIGltcG9ydHMgZm9yIGl0ZW0gaW4gZm9yYmlkZGVuKSwKICAgICAg'
        'ICAgICAgICAgIGYiZm9yYmlkZGVuIGNvcmUgaW1wb3J0IGluIHtwYXRofToge3NvcnRlZChpbXBv'
        'cnRzKX0iLAogICAgICAgICAgICApCgogICAgZGVmIHRlc3RfaW1wbGVtZW50YXRpb25fdXNlc19v'
        'bmx5X3N0ZGxpYl9hbmRfbm9fbmV0d29ya19tb2R1bGUoc2VsZikgLT4gTm9uZToKICAgICAgICBz'
        'b3VyY2Vfcm9vdCA9IFNSQ19ST09UIC8gInBlY192MiIKICAgICAgICBzdGRsaWIgPSBzZXQoc3lz'
        'LnN0ZGxpYl9tb2R1bGVfbmFtZXMpCiAgICAgICAgbmV0d29ya19tb2R1bGVzID0geyJhc3luY2lv'
        'IiwgImh0dHAiLCAic29ja2V0IiwgInVybGxpYiJ9CiAgICAgICAgdGhpcmRfcGFydHlfcm9vdCA9'
        'IFBhdGgoc3lzY29uZmlnLmdldF9wYXRocygpWyJwdXJlbGliIl0pCiAgICAgICAgZm9yIHBhdGgg'
        'aW4gc291cmNlX3Jvb3Qucmdsb2IoIioucHkiKToKICAgICAgICAgICAgdHJlZSA9IGFzdC5wYXJz'
        'ZShwYXRoLnJlYWRfdGV4dChlbmNvZGluZz0idXRmLTgiKSwgZmlsZW5hbWU9c3RyKHBhdGgpKQog'
        'ICAgICAgICAgICBmb3Igbm9kZSBpbiBhc3Qud2Fsayh0cmVlKToKICAgICAgICAgICAgICAgIGlm'
        'IGlzaW5zdGFuY2Uobm9kZSwgYXN0LkltcG9ydCk6CiAgICAgICAgICAgICAgICAgICAgbmFtZXMg'
        'PSBbYWxpYXMubmFtZSBmb3IgYWxpYXMgaW4gbm9kZS5uYW1lc10KICAgICAgICAgICAgICAgIGVs'
        'aWYgaXNpbnN0YW5jZShub2RlLCBhc3QuSW1wb3J0RnJvbSkgYW5kIG5vZGUubGV2ZWwgPT0gMCBh'
        'bmQgbm9kZS5tb2R1bGU6CiAgICAgICAgICAgICAgICAgICAgbmFtZXMgPSBbbm9kZS5tb2R1bGVd'
        'CiAgICAgICAgICAgICAgICBlbHNlOgogICAgICAgICAgICAgICAgICAgIGNvbnRpbnVlCiAgICAg'
        'ICAgICAgICAgICBmb3IgbmFtZSBpbiBuYW1lczoKICAgICAgICAgICAgICAgICAgICByb290ID0g'
        'bmFtZS5zcGxpdCgiLiIsIDEpWzBdCiAgICAgICAgICAgICAgICAgICAgc2VsZi5hc3NlcnROb3RJ'
        'bihyb290LCBuZXR3b3JrX21vZHVsZXMsIGYibmV0d29yayBpbXBvcnQgaW4ge3BhdGh9OiB7bmFt'
        'ZX0iKQogICAgICAgICAgICAgICAgICAgIHNlbGYuYXNzZXJ0VHJ1ZSgKICAgICAgICAgICAgICAg'
        'ICAgICAgICAgcm9vdCBpbiBzdGRsaWIgb3Igcm9vdCA9PSAicGVjX3YyIiwKICAgICAgICAgICAg'
        'ICAgICAgICAgICAgZiJub24tc3RkbGliIGltcG9ydCBpbiB7cGF0aH06IHtuYW1lfSAoc2l0ZSBy'
        'b290IHt0aGlyZF9wYXJ0eV9yb290fSkiLAogICAgICAgICAgICAgICAgICAgICkKCgppZiBfX25h'
        'bWVfXyA9PSAiX19tYWluX18iOgogICAgdW5pdHRlc3QubWFpbigpCg=='
    ),
    'd410afa5a32d4fd11384a4960b1ea28352f3f930f8902488e28b46d392dc3fae': (
        'ZnJvbSBfX2Z1dHVyZV9fIGltcG9ydCBhbm5vdGF0aW9ucwoKaW1wb3J0IGNvcHkKaW1wb3J0IGpz'
        'b24KaW1wb3J0IHN5cwppbXBvcnQgdGVtcGZpbGUKaW1wb3J0IHVuaXR0ZXN0CmZyb20gcGF0aGxp'
        'YiBpbXBvcnQgUGF0aAoKClYyX1JPT1QgPSBQYXRoKF9fZmlsZV9fKS5yZXNvbHZlKCkucGFyZW50'
        'c1syXQpTUkNfUk9PVCA9IFYyX1JPT1QgLyAic3JjIgpDT05GSUdfUk9PVCA9IFYyX1JPT1QgLyAi'
        'Y29uZmlnIgpGSVhUVVJFUyA9IFBhdGgoX19maWxlX18pLnJlc29sdmUoKS5wYXJlbnQgLyAiZml4'
        'dHVyZXMiCnN5cy5wYXRoLmluc2VydCgwLCBzdHIoU1JDX1JPT1QpKQoKZnJvbSBwZWNfdjIuYWRh'
        'cHRlcnMuY29uZmlnLmxvb3BfcmVnaXN0cnkgaW1wb3J0ICggICMgbm9xYTogRTQwMgogICAgRkVF'
        'RF9QUk9GSUxFX1NVUkZBQ0VTLAogICAgRkVFRF9QUk9GSUxFX1ZFUlNJT05TLAogICAgSnNvbkxv'
        'b3BSZWdpc3RyeSwKICAgIExvb3BSZWdpc3RyeUNvbmZpZ0Vycm9yLAopCmZyb20gcGVjX3YyLmNv'
        'cmUucG9ydHMubG9vcF9yZWdpc3RyeSBpbXBvcnQgKCAgIyBub3FhOiBFNDAyCiAgICBGZWVkUHJv'
        'ZmlsZSwKICAgIEZlZWRQcm9maWxlU3RhdGUsCiAgICBSZWdpc3RlcmVkTG9vcCwKKQoKClBFQ19M'
        'T09QX0lOSVQgPSAicHJvamVjdHMvcGVjL2xvb3AvTE9PUF9JTklULm1kIgpQRUNfQUdFTlRTID0g'
        'InByb2plY3RzL3BlYy9BR0VOVFMubWQiCkRfUEVDXzk0ID0gKAogICAgInByb2plY3RzL3BlYy9l'
        'eGVjdXRpb24vX0Nvb3JkaW5hdGlvbi9fREVDSVNJT05TLyIKICAgICJELVBFQy05NF9vd25lcl9k'
        'aXJlY3Rpb25fbG9vcF9taWdyYXRpb25fMjAyNi0wOS0yNS5tZCIKKQoKCmRlZiB2YWxpZF9kb2N1'
        'bWVudCgpIC0+IGRpY3Q6CiAgICByZXR1cm4gewogICAgICAgICJzY2hlbWFfdmVyc2lvbiI6IDIs'
        'CiAgICAgICAgImxvb3BzIjogWwogICAgICAgICAgICB7CiAgICAgICAgICAgICAgICAibG9vcF9p'
        'ZCI6ICJwZWMiLAogICAgICAgICAgICAgICAgImxvb3BfaW5pdF9wYXRoIjogUEVDX0xPT1BfSU5J'
        'VCwKICAgICAgICAgICAgICAgICJmZWVkX3Byb2ZpbGVzIjogWwogICAgICAgICAgICAgICAgICAg'
        'IHsicHJvZmlsZSI6ICJzaGFyZWQtZGV2LWxvb3AiLCAidmVyc2lvbiI6IDEsICJzdGF0ZSI6ICJs'
        'aXZlIiwgImJhc2lzIjogRF9QRUNfOTR9LAogICAgICAgICAgICAgICAgICAgIHsicHJvZmlsZSI6'
        'ICJyZW1haW5pbmctaXRlbXMiLCAidmVyc2lvbiI6IDEsICJzdGF0ZSI6ICJsaXZlIiwgImJhc2lz'
        'IjogUEVDX0FHRU5UU30sCiAgICAgICAgICAgICAgICAgICAgeyJwcm9maWxlIjogImxvb3AtcmVj'
        'ZWlwdHMtbGVkZ2VyIiwgInZlcnNpb24iOiAxLCAic3RhdGUiOiAiaGlzdG9yaWNhbCIsICJiYXNp'
        'cyI6IFBFQ19BR0VOVFN9LAogICAgICAgICAgICAgICAgICAgIHsicHJvZmlsZSI6ICJhZ2VudHJ1'
        'bnMtanNvbiIsICJ2ZXJzaW9uIjogMSwgInN0YXRlIjogImhpc3RvcmljYWwiLCAiYmFzaXMiOiBE'
        'X1BFQ185NH0sCiAgICAgICAgICAgICAgICBdLAogICAgICAgICAgICB9CiAgICAgICAgXSwKICAg'
        'IH0KCgpjbGFzcyBKc29uTG9vcFJlZ2lzdHJ5VGVzdHModW5pdHRlc3QuVGVzdENhc2UpOgogICAg'
        'ZGVmIGxvYWQoc2VsZiwgZG9jdW1lbnQ6IG9iamVjdCkgLT4gdHVwbGVbUmVnaXN0ZXJlZExvb3As'
        'IC4uLl06CiAgICAgICAgd2l0aCB0ZW1wZmlsZS5UZW1wb3JhcnlEaXJlY3RvcnkoKSBhcyB0ZW1w'
        'b3Jhcnk6CiAgICAgICAgICAgIHBhdGggPSBQYXRoKHRlbXBvcmFyeSkgLyAiY2FuZGlkYXRlLmpz'
        'b24iCiAgICAgICAgICAgIHBhdGgud3JpdGVfdGV4dChqc29uLmR1bXBzKGRvY3VtZW50KSwgZW5j'
        'b2Rpbmc9InV0Zi04IikKICAgICAgICAgICAgcmV0dXJuIEpzb25Mb29wUmVnaXN0cnkocGF0aCku'
        'cmVnaXN0ZXJlZF9sb29wcygpCgogICAgZGVmIHRlc3RfY2hlY2tlZF9pbl9kZWZhdWx0X2hhc19l'
        'eGFjdGx5X3RoZV9wZWNfbG9vcChzZWxmKSAtPiBOb25lOgogICAgICAgIGxvb3BzID0gSnNvbkxv'
        'b3BSZWdpc3RyeShDT05GSUdfUk9PVCAvICJsb29wcy5qc29uIikucmVnaXN0ZXJlZF9sb29wcygp'
        'CiAgICAgICAgc2VsZi5hc3NlcnRFcXVhbCgKICAgICAgICAgICAgbG9vcHMsCiAgICAgICAgICAg'
        'ICgKICAgICAgICAgICAgICAgIFJlZ2lzdGVyZWRMb29wKAogICAgICAgICAgICAgICAgICAgICJw'
        'ZWMiLAogICAgICAgICAgICAgICAgICAgIFBFQ19MT09QX0lOSVQsCiAgICAgICAgICAgICAgICAg'
        'ICAgKAogICAgICAgICAgICAgICAgICAgICAgICBGZWVkUHJvZmlsZSgic2hhcmVkLWRldi1sb29w'
        'IiwgMSwgRmVlZFByb2ZpbGVTdGF0ZS5MSVZFLCBEX1BFQ185NCksCiAgICAgICAgICAgICAgICAg'
        'ICAgICAgIEZlZWRQcm9maWxlKCJyZW1haW5pbmctaXRlbXMiLCAxLCBGZWVkUHJvZmlsZVN0YXRl'
        'LkxJVkUsIFBFQ19BR0VOVFMpLAogICAgICAgICAgICAgICAgICAgICAgICBGZWVkUHJvZmlsZSgi'
        'bG9vcC1yZWNlaXB0cy1sZWRnZXIiLCAxLCBGZWVkUHJvZmlsZVN0YXRlLkhJU1RPUklDQUwsIFBF'
        'Q19BR0VOVFMpLAogICAgICAgICAgICAgICAgICAgICAgICBGZWVkUHJvZmlsZSgiYWdlbnRydW5z'
        'LWpzb24iLCAxLCBGZWVkUHJvZmlsZVN0YXRlLkhJU1RPUklDQUwsIERfUEVDXzk0KSwKICAgICAg'
        'ICAgICAgICAgICAgICApLAogICAgICAgICAgICAgICAgKSwKICAgICAgICAgICAgKSwKICAgICAg'
        'ICApCgogICAgZGVmIHRlc3Rfc2NoZW1hX2RvY3VtZW50c19ldmVyeV9maWVsZF9hbmRfdGhlX2V4'
        'YWN0X2RlZmF1bHQoc2VsZikgLT4gTm9uZToKICAgICAgICBzY2hlbWEgPSBqc29uLmxvYWRzKChD'
        'T05GSUdfUk9PVCAvICJsb29wcy5zY2hlbWEuanNvbiIpLnJlYWRfdGV4dChlbmNvZGluZz0idXRm'
        'LTgiKSkKICAgICAgICBkb2N1bWVudCA9IGpzb24ubG9hZHMoKENPTkZJR19ST09UIC8gImxvb3Bz'
        'Lmpzb24iKS5yZWFkX3RleHQoZW5jb2Rpbmc9InV0Zi04IikpCiAgICAgICAgc2VsZi5hc3NlcnRF'
        'cXVhbChzY2hlbWFbIiRzY2hlbWEiXSwgImh0dHBzOi8vanNvbi1zY2hlbWEub3JnL2RyYWZ0LzIw'
        'MjAtMTIvc2NoZW1hIikKICAgICAgICBzZWxmLmFzc2VydEVxdWFsKHNjaGVtYVsiJGlkIl0sICJo'
        'dHRwczovL2NoaXJhbGl0eS5sb2NhbC9wZWMvdjIvY29uZmlnL2xvb3BzLnNjaGVtYS52Mi5qc29u'
        'IikKICAgICAgICBzZWxmLmFzc2VydEVxdWFsKHNjaGVtYVsicHJvcGVydGllcyJdWyJzY2hlbWFf'
        'dmVyc2lvbiJdWyJjb25zdCJdLCAyKQogICAgICAgIHNlbGYuYXNzZXJ0RXF1YWwoZG9jdW1lbnRb'
        'InNjaGVtYV92ZXJzaW9uIl0sIDIpCiAgICAgICAgc2VsZi5hc3NlcnRFcXVhbChsZW4oZG9jdW1l'
        'bnRbImxvb3BzIl0pLCAxKQogICAgICAgIGZvciBmaWVsZCBpbiAoInNjaGVtYV92ZXJzaW9uIiwg'
        'Imxvb3BzIik6CiAgICAgICAgICAgIHNlbGYuYXNzZXJ0VHJ1ZShzY2hlbWFbInByb3BlcnRpZXMi'
        'XVtmaWVsZF1bImRlc2NyaXB0aW9uIl0pCiAgICAgICAgcm93ID0gc2NoZW1hWyJwcm9wZXJ0aWVz'
        'Il1bImxvb3BzIl1bIml0ZW1zIl0KICAgICAgICBzZWxmLmFzc2VydEVxdWFsKHNvcnRlZChyb3db'
        'InJlcXVpcmVkIl0pLCBbImZlZWRfcHJvZmlsZXMiLCAibG9vcF9pZCIsICJsb29wX2luaXRfcGF0'
        'aCJdKQogICAgICAgIGZvciBmaWVsZCBpbiAoImxvb3BfaWQiLCAibG9vcF9pbml0X3BhdGgiLCAi'
        'ZmVlZF9wcm9maWxlcyIpOgogICAgICAgICAgICBzZWxmLmFzc2VydFRydWUocm93WyJwcm9wZXJ0'
        'aWVzIl1bZmllbGRdWyJkZXNjcmlwdGlvbiJdKQogICAgICAgIGVudHJ5ID0gcm93WyJwcm9wZXJ0'
        'aWVzIl1bImZlZWRfcHJvZmlsZXMiXVsiaXRlbXMiXQogICAgICAgIHNlbGYuYXNzZXJ0RmFsc2Uo'
        'ZW50cnlbImFkZGl0aW9uYWxQcm9wZXJ0aWVzIl0pCiAgICAgICAgc2VsZi5hc3NlcnRFcXVhbChz'
        'b3J0ZWQoZW50cnlbInJlcXVpcmVkIl0pLCBbImJhc2lzIiwgInByb2ZpbGUiLCAic3RhdGUiLCAi'
        'dmVyc2lvbiJdKQogICAgICAgIGZvciBmaWVsZCBpbiAoInByb2ZpbGUiLCAidmVyc2lvbiIsICJz'
        'dGF0ZSIsICJiYXNpcyIpOgogICAgICAgICAgICBzZWxmLmFzc2VydFRydWUoZW50cnlbInByb3Bl'
        'cnRpZXMiXVtmaWVsZF1bImRlc2NyaXB0aW9uIl0pCiAgICAgICAgZGVjbGFyZWQgPSB7b3B0aW9u'
        'WyJjb25zdCJdOiBvcHRpb25bImRlc2NyaXB0aW9uIl0gZm9yIG9wdGlvbiBpbiBlbnRyeVsicHJv'
        'cGVydGllcyJdWyJwcm9maWxlIl1bIm9uZU9mIl19CiAgICAgICAgc2VsZi5hc3NlcnRFcXVhbChz'
        'ZXQoZGVjbGFyZWQpLCBzZXQoRkVFRF9QUk9GSUxFX1ZFUlNJT05TKSkKICAgICAgICBzZWxmLmFz'
        'c2VydEVxdWFsKHNldChGRUVEX1BST0ZJTEVfU1VSRkFDRVMpLCBzZXQoRkVFRF9QUk9GSUxFX1ZF'
        'UlNJT05TKSkKICAgICAgICBmb3IgcHJvZmlsZSwgZGVzY3JpcHRpb24gaW4gZGVjbGFyZWQuaXRl'
        'bXMoKToKICAgICAgICAgICAgd2l0aCBzZWxmLnN1YlRlc3QocHJvZmlsZT1wcm9maWxlKToKICAg'
        'ICAgICAgICAgICAgIF8sIF8sIGxpc3RlZCA9IGRlc2NyaXB0aW9uLnJzdHJpcCgiLiIpLnBhcnRp'
        'dGlvbigiIFN1cmZhY2VzOiAiKQogICAgICAgICAgICAgICAgc2VsZi5hc3NlcnRFcXVhbChzZXQo'
        'bGlzdGVkLnNwbGl0KCIsICIpKSwgc2V0KEZFRURfUFJPRklMRV9TVVJGQUNFU1twcm9maWxlXSkp'
        'CiAgICAgICAgc2VsZi5hc3NlcnRFcXVhbCh7ZW50cnlbInByb3BlcnRpZXMiXVsidmVyc2lvbiJd'
        'WyJjb25zdCJdfSwgc2V0KCkudW5pb24oKkZFRURfUFJPRklMRV9WRVJTSU9OUy52YWx1ZXMoKSkp'
        'CiAgICAgICAgc2VsZi5hc3NlcnRFcXVhbCgKICAgICAgICAgICAgc2V0KGVudHJ5WyJwcm9wZXJ0'
        'aWVzIl1bInN0YXRlIl1bImVudW0iXSksCiAgICAgICAgICAgIHttZW1iZXIudmFsdWUgZm9yIG1l'
        'bWJlciBpbiBGZWVkUHJvZmlsZVN0YXRlfSwKICAgICAgICApCgogICAgZGVmIHRlc3Rfc2NoZW1h'
        'X3ZlcnNpb25fMV9pc19yZWplY3RlZF93aXRoX2xvY2F0aW9uKHNlbGYpIC0+IE5vbmU6CiAgICAg'
        'ICAgd2l0aCBzZWxmLmFzc2VydFJhaXNlc1JlZ2V4KAogICAgICAgICAgICBMb29wUmVnaXN0cnlD'
        'b25maWdFcnJvciwKICAgICAgICAgICAgciJzY2hlbWFfdmVyc2lvbl8xXC5qc29uOlwkXC5zY2hl'
        'bWFfdmVyc2lvbjogZXhwZWN0ZWQgaW50ZWdlciBjb25zdGFudCAyIiwKICAgICAgICApOgogICAg'
        'ICAgICAgICBKc29uTG9vcFJlZ2lzdHJ5KEZJWFRVUkVTIC8gInNjaGVtYV92ZXJzaW9uXzEuanNv'
        'biIpLnJlZ2lzdGVyZWRfbG9vcHMoKQoKICAgIGRlZiB0ZXN0X21pc3NpbmdfbG9vcF9pZF9pc19y'
        'ZWplY3RlZF93aXRoX2xvY2F0aW9uKHNlbGYpIC0+IE5vbmU6CiAgICAgICAgd2l0aCBzZWxmLmFz'
        'c2VydFJhaXNlc1JlZ2V4KExvb3BSZWdpc3RyeUNvbmZpZ0Vycm9yLCByIlwkXC5sb29wc1xbMFxd'
        'XC5sb29wX2lkIik6CiAgICAgICAgICAgIEpzb25Mb29wUmVnaXN0cnkoRklYVFVSRVMgLyAibWlz'
        'c2luZ19sb29wX2lkLmpzb24iKS5yZWdpc3RlcmVkX2xvb3BzKCkKCiAgICBkZWYgdGVzdF9kdXBs'
        'aWNhdGVfbG9vcF9pZF9pc19yZWplY3RlZF93aXRoX2xvY2F0aW9uKHNlbGYpIC0+IE5vbmU6CiAg'
        'ICAgICAgd2l0aCBzZWxmLmFzc2VydFJhaXNlc1JlZ2V4KExvb3BSZWdpc3RyeUNvbmZpZ0Vycm9y'
        'LCByIlwkXC5sb29wc1xbMVxdXC5sb29wX2lkIik6CiAgICAgICAgICAgIEpzb25Mb29wUmVnaXN0'
        'cnkoRklYVFVSRVMgLyAiZHVwbGljYXRlX2xvb3BfaWQuanNvbiIpLnJlZ2lzdGVyZWRfbG9vcHMo'
        'KQoKICAgIGRlZiB0ZXN0X21hbGZvcm1lZF9qc29uX2lzX3JlamVjdGVkX3dpdGhfbGluZV9hbmRf'
        'Y29sdW1uKHNlbGYpIC0+IE5vbmU6CiAgICAgICAgd2l0aCBzZWxmLmFzc2VydFJhaXNlc1JlZ2V4'
        'KAogICAgICAgICAgICBMb29wUmVnaXN0cnlDb25maWdFcnJvciwgciJtYWxmb3JtZWRcLmpzb246'
        'IG1hbGZvcm1lZCBKU09OIGF0IGxpbmUgWzAtOV0rLCBjb2x1bW4gWzAtOV0rIgogICAgICAgICk6'
        'CiAgICAgICAgICAgIEpzb25Mb29wUmVnaXN0cnkoRklYVFVSRVMgLyAibWFsZm9ybWVkLmpzb24i'
        'KS5yZWdpc3RlcmVkX2xvb3BzKCkKCiAgICBkZWYgdGVzdF9hYnNlbnRfZmlsZV9pc19yZWplY3Rl'
        'ZF9leHBsaWNpdGx5KHNlbGYpIC0+IE5vbmU6CiAgICAgICAgd2l0aCB0ZW1wZmlsZS5UZW1wb3Jh'
        'cnlEaXJlY3RvcnkoKSBhcyB0ZW1wb3Jhcnk6CiAgICAgICAgICAgIG1pc3NpbmcgPSBQYXRoKHRl'
        'bXBvcmFyeSkgLyAiYWJzZW50Lmpzb24iCiAgICAgICAgICAgIHdpdGggc2VsZi5hc3NlcnRSYWlz'
        'ZXNSZWdleChMb29wUmVnaXN0cnlDb25maWdFcnJvciwgciJhYnNlbnRcLmpzb246IGNvbmZpZ3Vy'
        'YXRpb24gZmlsZSBkb2VzIG5vdCBleGlzdCIpOgogICAgICAgICAgICAgICAgSnNvbkxvb3BSZWdp'
        'c3RyeShtaXNzaW5nKS5yZWdpc3RlcmVkX2xvb3BzKCkKCiAgICBkZWYgdGVzdF91bnJlYWRhYmxl'
        'X3BhdGhfaXNfcmVqZWN0ZWRfZXhwbGljaXRseShzZWxmKSAtPiBOb25lOgogICAgICAgIHdpdGgg'
        'dGVtcGZpbGUuVGVtcG9yYXJ5RGlyZWN0b3J5KCkgYXMgdGVtcG9yYXJ5OgogICAgICAgICAgICBk'
        'aXJlY3RvcnkgPSBQYXRoKHRlbXBvcmFyeSkgLyAibm90LWEtZmlsZS5qc29uIgogICAgICAgICAg'
        'ICBkaXJlY3RvcnkubWtkaXIoKQogICAgICAgICAgICB3aXRoIHNlbGYuYXNzZXJ0UmFpc2VzUmVn'
        'ZXgoTG9vcFJlZ2lzdHJ5Q29uZmlnRXJyb3IsIHIiY29uZmlndXJhdGlvbiBmaWxlIGlzIHVucmVh'
        'ZGFibGUiKToKICAgICAgICAgICAgICAgIEpzb25Mb29wUmVnaXN0cnkoZGlyZWN0b3J5KS5yZWdp'
        'c3RlcmVkX2xvb3BzKCkKCiAgICBkZWYgdGVzdF9pbnZhbGlkX2ZlZWRfcHJvZmlsZXNfYXJlX3Jl'
        'amVjdGVkX3dpdGhfbG9jYXRpb24oc2VsZikgLT4gTm9uZToKICAgICAgICByb3cgPSAiJC5sb29w'
        'c1swXSIKICAgICAgICBlbnRyeSA9IGYie3Jvd30uZmVlZF9wcm9maWxlc1swXSIKCiAgICAgICAg'
        'ZGVmIHdpdGhvdXQobWFwcGluZzogZGljdCwga2V5OiBzdHIpIC0+IGRpY3Q6CiAgICAgICAgICAg'
        'IHJldHVybiB7bmFtZTogdmFsdWUgZm9yIG5hbWUsIHZhbHVlIGluIG1hcHBpbmcuaXRlbXMoKSBp'
        'ZiBuYW1lICE9IGtleX0KCiAgICAgICAgY2FzZXMgPSB7CiAgICAgICAgICAgICJyb3cgbWlzc2lu'
        'ZyBmZWVkX3Byb2ZpbGVzIjogKGxhbWJkYSBkOiBkWyJsb29wcyJdLl9fc2V0aXRlbV9fKDAsIHdp'
        'dGhvdXQoZFsibG9vcHMiXVswXSwgImZlZWRfcHJvZmlsZXMiKSksIGYie3Jvd30uZmVlZF9wcm9m'
        'aWxlcyIsICJyZXF1aXJlZCBmaWVsZCBpcyBtaXNzaW5nIiksCiAgICAgICAgICAgICJyb3cgdW5r'
        'bm93biBmaWVsZCI6IChsYW1iZGEgZDogZFsibG9vcHMiXVswXS5fX3NldGl0ZW1fXygiZ3JhbW1h'
        'ciIsICJ4IiksIGYie3Jvd30uZ3JhbW1hciIsICJmaWVsZCBpcyBub3QgZGVmaW5lZCBieSBzY2hl'
        'bWEgdjIiKSwKICAgICAgICAgICAgImZlZWRfcHJvZmlsZXMgbm90IGFuIGFycmF5IjogKGxhbWJk'
        'YSBkOiBkWyJsb29wcyJdWzBdLl9fc2V0aXRlbV9fKCJmZWVkX3Byb2ZpbGVzIiwge30pLCBmInty'
        'b3d9LmZlZWRfcHJvZmlsZXMiLCAiZXhwZWN0ZWQgYW4gYXJyYXkiKSwKICAgICAgICAgICAgImZl'
        'ZWRfcHJvZmlsZXMgZW1wdHkiOiAobGFtYmRhIGQ6IGRbImxvb3BzIl1bMF0uX19zZXRpdGVtX18o'
        'ImZlZWRfcHJvZmlsZXMiLCBbXSksIGYie3Jvd30uZmVlZF9wcm9maWxlcyIsICJleHBlY3RlZCBh'
        'dCBsZWFzdCBvbmUgZmVlZCBwcm9maWxlIiksCiAgICAgICAgICAgICJlbnRyeSBub3QgYW4gb2Jq'
        'ZWN0IjogKGxhbWJkYSBkOiBkWyJsb29wcyJdWzBdWyJmZWVkX3Byb2ZpbGVzIl0uX19zZXRpdGVt'
        'X18oMCwgInNoYXJlZC1kZXYtbG9vcCIpLCBlbnRyeSwgImV4cGVjdGVkIGFuIG9iamVjdCIpLAog'
        'ICAgICAgICAgICAiZW50cnkgbWlzc2luZyBiYXNpcyI6IChsYW1iZGEgZDogZFsibG9vcHMiXVsw'
        'XVsiZmVlZF9wcm9maWxlcyJdLl9fc2V0aXRlbV9fKDAsIHdpdGhvdXQoZFsibG9vcHMiXVswXVsi'
        'ZmVlZF9wcm9maWxlcyJdWzBdLCAiYmFzaXMiKSksIGYie2VudHJ5fS5iYXNpcyIsICJyZXF1aXJl'
        'ZCBmaWVsZCBpcyBtaXNzaW5nIiksCiAgICAgICAgICAgICJlbnRyeSB1bmtub3duIGZpZWxkIjog'
        'KGxhbWJkYSBkOiBkWyJsb29wcyJdWzBdWyJmZWVkX3Byb2ZpbGVzIl1bMF0uX19zZXRpdGVtX18o'
        'InBhdGhzIiwgWyJ4Il0pLCBmIntlbnRyeX0ucGF0aHMiLCAiZmllbGQgaXMgbm90IGRlZmluZWQg'
        'Ynkgc2NoZW1hIHYyIiksCiAgICAgICAgICAgICJ1bmtub3duIHByb2ZpbGUiOiAobGFtYmRhIGQ6'
        'IGRbImxvb3BzIl1bMF1bImZlZWRfcHJvZmlsZXMiXVswXS5fX3NldGl0ZW1fXygicHJvZmlsZSIs'
        'ICJhZGFwdGVyLXlhbWwiKSwgZiJ7ZW50cnl9LnByb2ZpbGUiLCAiY2xvc2VkIGZlZWQtcHJvZmls'
        'ZSB2b2NhYnVsYXJ5IiksCiAgICAgICAgICAgICJwcm9maWxlIG5vdCBhIHN0cmluZyI6IChsYW1i'
        'ZGEgZDogZFsibG9vcHMiXVswXVsiZmVlZF9wcm9maWxlcyJdWzBdLl9fc2V0aXRlbV9fKCJwcm9m'
        'aWxlIiwgMSksIGYie2VudHJ5fS5wcm9maWxlIiwgImNsb3NlZCBmZWVkLXByb2ZpbGUgdm9jYWJ1'
        'bGFyeSIpLAogICAgICAgICAgICAiZHVwbGljYXRlIHByb2ZpbGUiOiAobGFtYmRhIGQ6IGRbImxv'
        'b3BzIl1bMF1bImZlZWRfcHJvZmlsZXMiXVsxXS5fX3NldGl0ZW1fXygicHJvZmlsZSIsICJzaGFy'
        'ZWQtZGV2LWxvb3AiKSwgZiJ7cm93fS5mZWVkX3Byb2ZpbGVzWzFdLnByb2ZpbGUiLCAiZHVwbGlj'
        'YXRlIGZlZWQgcHJvZmlsZSBmaXJzdCBkZWNsYXJlZCBhdCIpLAogICAgICAgICAgICAidW5zdXBw'
        'b3J0ZWQgdmVyc2lvbiI6IChsYW1iZGEgZDogZFsibG9vcHMiXVswXVsiZmVlZF9wcm9maWxlcyJd'
        'WzBdLl9fc2V0aXRlbV9fKCJ2ZXJzaW9uIiwgMiksIGYie2VudHJ5fS52ZXJzaW9uIiwgInN1cHBv'
        'cnRlZCBpbnRlZ2VyIHZlcnNpb24iKSwKICAgICAgICAgICAgImJvb2xlYW4gdmVyc2lvbiI6IChs'
        'YW1iZGEgZDogZFsibG9vcHMiXVswXVsiZmVlZF9wcm9maWxlcyJdWzBdLl9fc2V0aXRlbV9fKCJ2'
        'ZXJzaW9uIiwgVHJ1ZSksIGYie2VudHJ5fS52ZXJzaW9uIiwgInN1cHBvcnRlZCBpbnRlZ2VyIHZl'
        'cnNpb24iKSwKICAgICAgICAgICAgInN0cmluZyB2ZXJzaW9uIjogKGxhbWJkYSBkOiBkWyJsb29w'
        'cyJdWzBdWyJmZWVkX3Byb2ZpbGVzIl1bMF0uX19zZXRpdGVtX18oInZlcnNpb24iLCAiMSIpLCBm'
        'IntlbnRyeX0udmVyc2lvbiIsICJzdXBwb3J0ZWQgaW50ZWdlciB2ZXJzaW9uIiksCiAgICAgICAg'
        'ICAgICJ1bmtub3duIHN0YXRlIjogKGxhbWJkYSBkOiBkWyJsb29wcyJdWzBdWyJmZWVkX3Byb2Zp'
        'bGVzIl1bMF0uX19zZXRpdGVtX18oInN0YXRlIiwgImFjdGl2ZSIpLCBmIntlbnRyeX0uc3RhdGUi'
        'LCAiZXhwZWN0ZWQgbGl2ZSBvciBoaXN0b3JpY2FsIiksCiAgICAgICAgICAgICJzdGF0ZSBub3Qg'
        'YSBzdHJpbmciOiAobGFtYmRhIGQ6IGRbImxvb3BzIl1bMF1bImZlZWRfcHJvZmlsZXMiXVswXS5f'
        'X3NldGl0ZW1fXygic3RhdGUiLCAxKSwgZiJ7ZW50cnl9LnN0YXRlIiwgImV4cGVjdGVkIGxpdmUg'
        'b3IgaGlzdG9yaWNhbCIpLAogICAgICAgICAgICAicHJvZmlsZSBudWxsIjogKGxhbWJkYSBkOiBk'
        'WyJsb29wcyJdWzBdWyJmZWVkX3Byb2ZpbGVzIl1bMF0uX19zZXRpdGVtX18oInByb2ZpbGUiLCBO'
        'b25lKSwgZiJ7ZW50cnl9LnByb2ZpbGUiLCAiY2xvc2VkIGZlZWQtcHJvZmlsZSB2b2NhYnVsYXJ5'
        'IiksCiAgICAgICAgICAgICJsZWRnZXIgbGl2ZSBhbmQgaGlzdG9yaWNhbCI6IChsYW1iZGEgZDog'
        'ZFsibG9vcHMiXVswXS5fX3NldGl0ZW1fXygiZmVlZF9wcm9maWxlcyIsIFtkaWN0KGRbImxvb3Bz'
        'Il1bMF1bImZlZWRfcHJvZmlsZXMiXVsyXSwgcHJvZmlsZT0icmVtYWluaW5nLWxvb3AiLCBzdGF0'
        'ZT0ibGl2ZSIpLCBkWyJsb29wcyJdWzBdWyJmZWVkX3Byb2ZpbGVzIl1bMl1dKSwgZiJ7cm93fS5m'
        'ZWVkX3Byb2ZpbGVzWzFdLnByb2ZpbGUiLCAic3VyZmFjZSByZWNlaXB0LWxlZGdlciBpcyBhbHJl'
        'YWR5IGNvdmVyZWQgYnkiKSwKICAgICAgICAgICAgInR3byBsaXZlIGxpZmVjeWNsZSByZWFkZXJz'
        'IjogKGxhbWJkYSBkOiBkWyJsb29wcyJdWzBdLl9fc2V0aXRlbV9fKCJmZWVkX3Byb2ZpbGVzIiwg'
        'W2RbImxvb3BzIl1bMF1bImZlZWRfcHJvZmlsZXMiXVswXSwgZGljdChkWyJsb29wcyJdWzBdWyJm'
        'ZWVkX3Byb2ZpbGVzIl1bMF0sIHByb2ZpbGU9InJlbWFpbmluZy1sb29wIildKSwgZiJ7cm93fS5m'
        'ZWVkX3Byb2ZpbGVzWzFdLnByb2ZpbGUiLCAic3VyZmFjZSBkZWNpc2lvbi1yZWdpc3RlcnMgaXMg'
        'YWxyZWFkeSBjb3ZlcmVkIGJ5IiksCiAgICAgICAgICAgICJyZW1haW5pbmcgcmVhZCB0d2ljZSI6'
        'IChsYW1iZGEgZDogZFsibG9vcHMiXVswXS5fX3NldGl0ZW1fXygiZmVlZF9wcm9maWxlcyIsIFtk'
        'aWN0KGRbImxvb3BzIl1bMF1bImZlZWRfcHJvZmlsZXMiXVswXSwgcHJvZmlsZT0icmVtYWluaW5n'
        'LWxvb3AiKSwgZFsibG9vcHMiXVswXVsiZmVlZF9wcm9maWxlcyJdWzFdXSksIGYie3Jvd30uZmVl'
        'ZF9wcm9maWxlc1sxXS5wcm9maWxlIiwgInN1cmZhY2Ugc3RhdHVzLXJlbWFpbmluZyBpcyBhbHJl'
        'YWR5IGNvdmVyZWQgYnkiKSwKICAgICAgICAgICAgIm5vIGxpdmUgcHJvZmlsZSI6IChsYW1iZGEg'
        'ZDogW2VudHJ5Ll9fc2V0aXRlbV9fKCJzdGF0ZSIsICJoaXN0b3JpY2FsIikgZm9yIGVudHJ5IGlu'
        'IGRbImxvb3BzIl1bMF1bImZlZWRfcHJvZmlsZXMiXV0sIGYie3Jvd30uZmVlZF9wcm9maWxlcyIs'
        'ICJleHBlY3RlZCBhdCBsZWFzdCBvbmUgbGl2ZSBmZWVkIHByb2ZpbGUiKSwKICAgICAgICAgICAg'
        'ImVtcHR5IGJhc2lzIjogKGxhbWJkYSBkOiBkWyJsb29wcyJdWzBdWyJmZWVkX3Byb2ZpbGVzIl1b'
        'MF0uX19zZXRpdGVtX18oImJhc2lzIiwgIiIpLCBmIntlbnRyeX0uYmFzaXMiLCAiZXhwZWN0ZWQg'
        'YSBub24tZW1wdHkgc3RyaW5nIiksCiAgICAgICAgICAgICJhYnNvbHV0ZSBiYXNpcyI6IChsYW1i'
        'ZGEgZDogZFsibG9vcHMiXVswXVsiZmVlZF9wcm9maWxlcyJdWzBdLl9fc2V0aXRlbV9fKCJiYXNp'
        'cyIsICIvZXRjL3Bhc3N3ZCIpLCBmIntlbnRyeX0uYmFzaXMiLCAibm9ybWFsaXplZCByZXBvc2l0'
        'b3J5LXJlbGF0aXZlIHBhdGgiKSwKICAgICAgICAgICAgInRyYXZlcnNpbmcgYmFzaXMiOiAobGFt'
        'YmRhIGQ6IGRbImxvb3BzIl1bMF1bImZlZWRfcHJvZmlsZXMiXVswXS5fX3NldGl0ZW1fXygiYmFz'
        'aXMiLCAicHJvamVjdHMvLi4veC5tZCIpLCBmIntlbnRyeX0uYmFzaXMiLCAibm9ybWFsaXplZCBy'
        'ZXBvc2l0b3J5LXJlbGF0aXZlIHBhdGgiKSwKICAgICAgICAgICAgImJhY2tzbGFzaCBiYXNpcyI6'
        'IChsYW1iZGEgZDogZFsibG9vcHMiXVswXVsiZmVlZF9wcm9maWxlcyJdWzBdLl9fc2V0aXRlbV9f'
        'KCJiYXNpcyIsICJwcm9qZWN0c1xccGVjXFxBR0VOVFMubWQiKSwgZiJ7ZW50cnl9LmJhc2lzIiwg'
        'Im5vcm1hbGl6ZWQgcmVwb3NpdG9yeS1yZWxhdGl2ZSBwYXRoIiksCiAgICAgICAgfQogICAgICAg'
        'IGZvciBuYW1lLCAobXV0YXRlLCBsb2NhdGlvbiwgbWVzc2FnZSkgaW4gY2FzZXMuaXRlbXMoKToK'
        'ICAgICAgICAgICAgd2l0aCBzZWxmLnN1YlRlc3QoY2FzZT1uYW1lKToKICAgICAgICAgICAgICAg'
        'IGRvY3VtZW50ID0gY29weS5kZWVwY29weSh2YWxpZF9kb2N1bWVudCgpKQogICAgICAgICAgICAg'
        'ICAgbXV0YXRlKGRvY3VtZW50KQogICAgICAgICAgICAgICAgd2l0aCBzZWxmLmFzc2VydFJhaXNl'
        'cyhMb29wUmVnaXN0cnlDb25maWdFcnJvcikgYXMgcmFpc2VkOgogICAgICAgICAgICAgICAgICAg'
        'IHNlbGYubG9hZChkb2N1bWVudCkKICAgICAgICAgICAgICAgIHRleHQgPSBzdHIocmFpc2VkLmV4'
        'Y2VwdGlvbikKICAgICAgICAgICAgICAgIHNlbGYuYXNzZXJ0SW4oZiI6e2xvY2F0aW9ufTogIiwg'
        'dGV4dCkKICAgICAgICAgICAgICAgIHNlbGYuYXNzZXJ0SW4obWVzc2FnZSwgdGV4dCkKCiAgICBk'
        'ZWYgdGVzdF9mYWlsdXJlc19kb19ub3RfZWNob19kb2N1bWVudF92YWx1ZXMoc2VsZikgLT4gTm9u'
        'ZToKICAgICAgICBzZW50aW5lbCA9ICJ6enNlbnRpbmVsenoiCiAgICAgICAgY2FzZXMgPSB7CiAg'
        'ICAgICAgICAgICJsb29wX2lkIjogbGFtYmRhIGQ6IGRbImxvb3BzIl1bMF0uX19zZXRpdGVtX18o'
        'Imxvb3BfaWQiLCBzZW50aW5lbC51cHBlcigpKSwKICAgICAgICAgICAgImxvb3BfaW5pdF9wYXRo'
        'IjogbGFtYmRhIGQ6IGRbImxvb3BzIl1bMF0uX19zZXRpdGVtX18oImxvb3BfaW5pdF9wYXRoIiwg'
        'ZiIve3NlbnRpbmVsfSIpLAogICAgICAgICAgICAicHJvZmlsZSI6IGxhbWJkYSBkOiBkWyJsb29w'
        'cyJdWzBdWyJmZWVkX3Byb2ZpbGVzIl1bMF0uX19zZXRpdGVtX18oInByb2ZpbGUiLCBzZW50aW5l'
        'bCksCiAgICAgICAgICAgICJ2ZXJzaW9uIjogbGFtYmRhIGQ6IGRbImxvb3BzIl1bMF1bImZlZWRf'
        'cHJvZmlsZXMiXVswXS5fX3NldGl0ZW1fXygidmVyc2lvbiIsIHNlbnRpbmVsKSwKICAgICAgICAg'
        'ICAgInN0YXRlIjogbGFtYmRhIGQ6IGRbImxvb3BzIl1bMF1bImZlZWRfcHJvZmlsZXMiXVswXS5f'
        'X3NldGl0ZW1fXygic3RhdGUiLCBzZW50aW5lbCksCiAgICAgICAgICAgICJiYXNpcyI6IGxhbWJk'
        'YSBkOiBkWyJsb29wcyJdWzBdWyJmZWVkX3Byb2ZpbGVzIl1bMF0uX19zZXRpdGVtX18oImJhc2lz'
        'IiwgZiIuLi97c2VudGluZWx9IiksCiAgICAgICAgfQogICAgICAgIGZvciBuYW1lLCBtdXRhdGUg'
        'aW4gY2FzZXMuaXRlbXMoKToKICAgICAgICAgICAgd2l0aCBzZWxmLnN1YlRlc3QoZmllbGQ9bmFt'
        'ZSk6CiAgICAgICAgICAgICAgICBkb2N1bWVudCA9IGNvcHkuZGVlcGNvcHkodmFsaWRfZG9jdW1l'
        'bnQoKSkKICAgICAgICAgICAgICAgIG11dGF0ZShkb2N1bWVudCkKICAgICAgICAgICAgICAgIHdp'
        'dGggc2VsZi5hc3NlcnRSYWlzZXMoTG9vcFJlZ2lzdHJ5Q29uZmlnRXJyb3IpIGFzIHJhaXNlZDoK'
        'ICAgICAgICAgICAgICAgICAgICBzZWxmLmxvYWQoZG9jdW1lbnQpCiAgICAgICAgICAgICAgICBz'
        'ZWxmLmFzc2VydE5vdEluKHNlbnRpbmVsLCBzdHIocmFpc2VkLmV4Y2VwdGlvbikubG93ZXIoKSkK'
        'CiAgICBkZWYgdGVzdF9hZGRpdGlvbmFsX2xvb3BzX25lZWRfZW50cmllc19vbmx5KHNlbGYpIC0+'
        'IE5vbmU6CiAgICAgICAgZG9jdW1lbnQgPSB2YWxpZF9kb2N1bWVudCgpCiAgICAgICAgZG9jdW1l'
        'bnRbImxvb3BzIl0uYXBwZW5kKAogICAgICAgICAgICB7CiAgICAgICAgICAgICAgICAibG9vcF9p'
        'ZCI6ICJzZWNvbmQtbG9vcCIsCiAgICAgICAgICAgICAgICAibG9vcF9pbml0X3BhdGgiOiAicHJv'
        'amVjdHMvc2Vjb25kL2xvb3AvTE9PUF9JTklULm1kIiwKICAgICAgICAgICAgICAgICJmZWVkX3By'
        'b2ZpbGVzIjogWwogICAgICAgICAgICAgICAgICAgIHsicHJvZmlsZSI6IHByb2ZpbGUsICJ2ZXJz'
        'aW9uIjogMSwgInN0YXRlIjogc3RhdGUsICJiYXNpcyI6ICJwcm9qZWN0cy9zZWNvbmQvQUdFTlRT'
        'Lm1kIn0KICAgICAgICAgICAgICAgICAgICBmb3IgcHJvZmlsZSwgc3RhdGUgaW4gKAogICAgICAg'
        'ICAgICAgICAgICAgICAgICAoInNoYXJlZC1kZXYtbG9vcCIsICJsaXZlIiksCiAgICAgICAgICAg'
        'ICAgICAgICAgICAgICgibG9vcC1yZWNlaXB0cy1sZWRnZXIiLCAiaGlzdG9yaWNhbCIpLAogICAg'
        'ICAgICAgICAgICAgICAgICAgICAoImFnZW50cnVucy1qc29uIiwgImhpc3RvcmljYWwiKSwKICAg'
        'ICAgICAgICAgICAgICAgICApCiAgICAgICAgICAgICAgICBdLAogICAgICAgICAgICB9CiAgICAg'
        'ICAgKQogICAgICAgIGxvb3BzID0gc2VsZi5sb2FkKGRvY3VtZW50KQogICAgICAgIHNlbGYuYXNz'
        'ZXJ0RXF1YWwoW2xvb3AubG9vcF9pZCBmb3IgbG9vcCBpbiBsb29wc10sIFsicGVjIiwgInNlY29u'
        'ZC1sb29wIl0pCiAgICAgICAgc2VsZi5hc3NlcnRFcXVhbCgKICAgICAgICAgICAgW3Byb2ZpbGUu'
        'cHJvZmlsZSBmb3IgcHJvZmlsZSBpbiBsb29wc1sxXS5mZWVkX3Byb2ZpbGVzXSwKICAgICAgICAg'
        'ICAgWyJzaGFyZWQtZGV2LWxvb3AiLCAibG9vcC1yZWNlaXB0cy1sZWRnZXIiLCAiYWdlbnRydW5z'
        'LWpzb24iXSwKICAgICAgICApCiAgICAgICAgc2VsZi5hc3NlcnRFcXVhbChsb29wc1sxXS5mZWVk'
        'X3Byb2ZpbGVzWzJdLnN0YXRlLCBGZWVkUHJvZmlsZVN0YXRlLkhJU1RPUklDQUwpCgogICAgZGVm'
        'IHRlc3RfaW52YWxpZF9kb2N1bWVudF9uZXZlcl9yZXR1cm5zX3BhcnRpYWxfb3JfZW1wdHlfc2V0'
        'KHNlbGYpIC0+IE5vbmU6CiAgICAgICAgZm9yIGZpeHR1cmUgaW4gKAogICAgICAgICAgICAic2No'
        'ZW1hX3ZlcnNpb25fMS5qc29uIiwKICAgICAgICAgICAgIm1pc3NpbmdfbG9vcF9pZC5qc29uIiwK'
        'ICAgICAgICAgICAgImR1cGxpY2F0ZV9sb29wX2lkLmpzb24iLAogICAgICAgICAgICAibWFsZm9y'
        'bWVkLmpzb24iLAogICAgICAgICk6CiAgICAgICAgICAgIHdpdGggc2VsZi5zdWJUZXN0KGZpeHR1'
        'cmU9Zml4dHVyZSk6CiAgICAgICAgICAgICAgICB3aXRoIHNlbGYuYXNzZXJ0UmFpc2VzKExvb3BS'
        'ZWdpc3RyeUNvbmZpZ0Vycm9yKToKICAgICAgICAgICAgICAgICAgICBKc29uTG9vcFJlZ2lzdHJ5'
        'KEZJWFRVUkVTIC8gZml4dHVyZSkucmVnaXN0ZXJlZF9sb29wcygpCiAgICAgICAgZG9jdW1lbnQg'
        'PSB2YWxpZF9kb2N1bWVudCgpCiAgICAgICAgZG9jdW1lbnRbImxvb3BzIl0uYXBwZW5kKGNvcHku'
        'ZGVlcGNvcHkoZG9jdW1lbnRbImxvb3BzIl1bMF0pKQogICAgICAgIGRvY3VtZW50WyJsb29wcyJd'
        'WzFdWyJsb29wX2lkIl0gPSAic2Vjb25kLWxvb3AiCiAgICAgICAgZG9jdW1lbnRbImxvb3BzIl1b'
        'MV1bImZlZWRfcHJvZmlsZXMiXVswXVsic3RhdGUiXSA9ICJzdGFsZSIKICAgICAgICB3aXRoIHNl'
        'bGYuYXNzZXJ0UmFpc2VzUmVnZXgoTG9vcFJlZ2lzdHJ5Q29uZmlnRXJyb3IsIHIiXCRcLmxvb3Bz'
        'XFsxXF1cLmZlZWRfcHJvZmlsZXNcWzBcXVwuc3RhdGUiKToKICAgICAgICAgICAgc2VsZi5sb2Fk'
        'KGRvY3VtZW50KQoKCmlmIF9fbmFtZV9fID09ICJfX21haW5fXyI6CiAgICB1bml0dGVzdC5tYWlu'
        'KCkK'
    ),
    'e44bf7f00c8ef2cfa5f8006ef2834feb020063df63a3b4b8d8cbd8f359174ff7': (
        'IiIiQ29yZS1vd25lZCBwb3J0cyBmb3IgcmVwbGFjZWFibGUgUEVDIGFkYXB0ZXJzLiIiIgoKZnJv'
        'bSAubG9vcF9yZWdpc3RyeSBpbXBvcnQgRmVlZFByb2ZpbGUsIEZlZWRQcm9maWxlU3RhdGUsIExv'
        'b3BSZWdpc3RyeSwgUmVnaXN0ZXJlZExvb3AKCl9fYWxsX18gPSBbIkZlZWRQcm9maWxlIiwgIkZl'
        'ZWRQcm9maWxlU3RhdGUiLCAiTG9vcFJlZ2lzdHJ5IiwgIlJlZ2lzdGVyZWRMb29wIl0K'
    ),
    'f4255b2483a014b542fb7f25c4314ff75dabb5cebbcfe751a2ad3df425f29598': (
        'ewogICJsb29wcyI6IFsKICAgIHsKICAgICAgImZlZWRfcHJvZmlsZXMiOiBbCiAgICAgICAgewog'
        'ICAgICAgICAgImJhc2lzIjogInByb2plY3RzL3BlYy9leGVjdXRpb24vX0Nvb3JkaW5hdGlvbi9f'
        'REVDSVNJT05TL0QtUEVDLTk0X293bmVyX2RpcmVjdGlvbl9sb29wX21pZ3JhdGlvbl8yMDI2LTA5'
        'LTI1Lm1kIiwKICAgICAgICAgICJwcm9maWxlIjogInNoYXJlZC1kZXYtbG9vcCIsCiAgICAgICAg'
        'ICAic3RhdGUiOiAibGl2ZSIsCiAgICAgICAgICAidmVyc2lvbiI6IDEKICAgICAgICB9CiAgICAg'
        'IF0sCiAgICAgICJsb29wX2luaXRfcGF0aCI6ICJwcm9qZWN0cy9wZWMvbG9vcC9MT09QX0lOSVQu'
        'bWQiCiAgICB9CiAgXSwKICAic2NoZW1hX3ZlcnNpb24iOiAyCn0K'
    ),
}


def sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def fail(message: str) -> int:
    print(f"FAIL {message}; nothing written")
    return 1


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo", required=True)
    parser.add_argument("--pec-row", choices=["migrated", "remaining"], default="migrated")
    parser.add_argument("--check-only", action="store_true")
    args = parser.parse_args()

    root = Path(args.repo).resolve() / PEC
    if not root.is_dir():
        return fail(f"{root} is not a directory")
    postimages = POSTIMAGES_A if args.pec_row == "migrated" else POSTIMAGES_AR
    if set(postimages) != set(PREIMAGES):
        return fail("postimage set differs from the grant")

    for rel, expected in sorted(UNCHANGED.items()):
        path = root / rel
        if not path.is_file() or sha(path.read_bytes()) != expected:
            return fail(f"must-remain file differs: {rel}")
        print(f"UNCHANGED {rel} {expected}")

    for rel, expected in sorted(PREIMAGES.items()):
        path = root / rel
        if expected is None:
            if path.exists():
                return fail(f"path to create already exists: {rel}")
            print(f"READ {rel} absent")
            continue
        if not path.is_file():
            return fail(f"preimage missing: {rel}")
        actual = sha(path.read_bytes())
        if actual != expected:
            return fail(f"preimage mismatch {rel}: {actual} != {expected}")
        print(f"READ {rel} {actual}")

    rendered: dict[str, bytes] = {}
    for rel, digest in sorted(postimages.items()):
        data = base64.b64decode("".join(BLOBS[digest]))
        if sha(data) != digest:
            return fail(f"embedded postimage corrupt: {rel}")
        rendered[rel] = data

    for rel, data in sorted(rendered.items()):
        if args.check_only:
            print(f"RENDER {rel} {sha(data)}")
            continue
        path = root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)

    if not args.check_only:
        for rel, digest in sorted(postimages.items()):
            actual = sha((root / rel).read_bytes())
            if actual != digest:
                print(f"FAIL postimage mismatch after write {rel}: {actual}")
                return 1
            print(f"WRITE {rel} {actual}")
    print(f"OK option={'A' if args.pec_row == 'migrated' else 'A-R'} files={len(rendered)} "
          f"mode={'check-only' if args.check_only else 'written'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
