#!/usr/bin/env python3
"""Adapt the accepted P2 PKG09 author harness to the frozen PKG10 population."""
import re
from pathlib import Path

root = Path(__file__).resolve().parents[8]
template = root / "execution/_Coordination/AgentRuns/SOW-STAGE2-EXEC-20260712-01/instances/WORKING-P2-PKG09/children/AUTHOR-B1/run_author.py"
source = template.read_text(encoding="utf-8")
source = source.replace("WORKING-P2-PKG09", "WORKING-P3-PKG10")
source = source.replace("candidates/W_P2/PIP-PKG09", "candidates/W_P3/PIP-PKG10")
source = source.replace("snapshots/W_P2/preflight/P2_MANIFEST.tsv", "snapshots/W_P3/preflight/P3_MANIFEST.tsv")
source = source.replace("eaad463c0d481f6f1654e6adb5ee718f566176e9", "4d153302c3c4cd42578936db160c2bac1270225a")
source = source.replace('DIDS=[f"DEL-09-{n:02d}" for n in range(1,6)]', 'DIDS=[f"DEL-10-{n:02d}" for n in range(1,6)]')
source = source.replace('"--package-id","PKG-09"', '"--package-id","PKG-10"')
source = source.replace("assert total_lines==total_covered==1357", "assert total_lines==total_covered==1594")
seeds = '''SEEDS={
"DEL-10-01":("A public API and plugin-boundary contract for governed model exchange, solver jobs, results, rule-pack hooks, diagnostics, provenance, units, privacy, and report controls is produced.","The contract preserves schema-first command/query/job/result envelopes, deny-bypass service boundaries, unit and provenance validation, protected/private-data controls, deterministic plugin declarations, current implemented-slice evidence, visible transport and permission-taxonomy TBDs, and the prohibition on compliance, certification, or professional-approval claims.","Validate the contract and review source parity, operation-family and plugin-boundary coverage, current-versus-historical declarations, units/provenance/privacy and deny-bypass controls, diagnostic/result-envelope requirements, retained transport and permission TBDs, and professional-authority limits."),
"DEL-10-02":("An import-export adapter-framework contract for governed external-data translation and round-trip evidence is produced.","The contract preserves schema-first adapter interfaces, unit/dimensional/provenance and redistribution checks, public/private data separation, protected-content quarantine, diagnostics and loss reporting, deterministic round-trip behavior, format-specific extension boundaries, downstream FEA-handoff compatibility, and unresolved external-format decisions without inventing implementation authority.","Validate the contract and review source parity, adapter lifecycle and format-extension coverage, unit/provenance/private-data controls, loss and diagnostic visibility, round-trip and downstream-handoff evidence, retained format TBDs, and no-bypass or professional-authority limits."),
"DEL-10-03":("A local FEA handoff data-contract for explicit governed export of geometry, properties, loads, constraints, units, provenance, mappings, and result re-association is produced.","The contract preserves solver-neutral schema and manifest boundaries, stable identifiers, coordinate and unit conventions, provenance and protected/private-data controls, completeness and diagnostic checks, deterministic hashes, local-tool separation, declared omissions and unsupported features, and visible solver/export-format TBDs without claiming external-solver validation or professional approval.","Validate the contract and review source parity, geometry/property/load/constraint and mapping coverage, coordinate/unit/provenance requirements, manifest/hash and diagnostic evidence, local FEA boundary and re-association behavior, retained tool/format TBDs, and prohibited validation or approval claims."),
"DEL-10-04":("A reproducible build, packaging, and CI/CD pipeline contract for supported development and release-preparation surfaces is produced.","The contract preserves deterministic build and test gates, Rust and GUI/toolchain boundaries, artifact provenance and checksums, platform/package evidence, protected-content and private-data controls, failure diagnostics, current implementation evidence, and explicit unresolved CI-provider, signing, publication, coverage, and platform-matrix decisions without making release or security assurances.","Validate the contract and review source parity, build/test/package stage coverage, reproducibility and provenance evidence, platform and toolchain boundaries, protected/private-data controls, retained provider/signing/publication/coverage TBDs, and separation of pipeline evidence from release acceptance."),
"DEL-10-05":("A headless CLI and structured-I/O analysis-runner contract for governed solve, input validation, result export, benchmark, and regression workflows is produced.","The contract preserves the DEC-065 local command surface, schema-first application-service routing, unit-aware deterministic I/O, blocking diagnostics, result-envelope and reproducibility evidence, invented/permitted fixtures, local-first private-data behavior, current bounded implementation evidence, and deferred persisted-project, external-adapter, CI, public-transport, and release concerns without compliance claims.","Validate the contract and review source parity, five stable verb families, service-boundary and unit-aware I/O behavior, blocking diagnostics and result envelopes, deterministic fixture evidence, retained downstream/deferred integrations, privacy/protected-content controls, and professional-authority limits.")}
'''
source, count = re.subn(r"SEEDS=\{.*?\}\n\n(?=def sha)", seeds + "\n", source, flags=re.S)
assert count == 1
for forbidden in ("DEL-09-", "PKG-09", "W_P2/PIP-PKG09", "P2_MANIFEST.tsv", "WORKING-P2-PKG09"):
    assert forbidden not in source, forbidden
compile(source, str(template), "exec")
exec(compile(source, str(template), "exec"), {"__name__": "__main__"})
