from pathlib import Path
import shutil,json,hashlib
wt=Path('/Users/ryan/dev/chirality/.claude/worktrees/swbpipe-control-layer-8a41be/.claude/t3'); src=wt/'f2a'; out=Path(__file__).resolve().parent; dst=wt/'scratch/rv62-selected-material'; core=Path('projects/chirality-piping/core'); pp=core/'product_physics'
assert not dst.exists();(dst/core).mkdir(parents=True)
for p in (src/core).iterdir():
 if p.name=='product_physics':shutil.copytree(p,dst/pp,ignore=shutil.ignore_patterns('target'))
 else:(dst/core/p.name).symlink_to(p,target_is_directory=p.is_dir())
(dst/'projects/chirality-piping/fixtures').symlink_to(src/'projects/chirality-piping/fixtures',target_is_directory=True)
access='''\n#[cfg(test)]\nimpl ProductCapture {\n    pub(super) fn rv62_source_check(&mut self, case: &PreviewLoadCase) -> Result<(), CaptureError> { self.basis_source_case(case) }\n    pub(super) fn rv62_record_check(&self, row: &ResultItem) -> Result<(), CaptureError> { self.validate_modulus_record(row) }\n}\n'''
control='''\n#[test]\nfn rv62_independent_source_and_owned_text_controls() {\n    use super::retained_product::{AdapterEvent as E, AdapterFault, AdapterWork, CaptureError};\n    for interpolated in [false, true] {\n        let raw = i47_selected_specimen(interpolated, true);\n        let (request, _) = source_receipt::CapturedInvocation::parse(raw.clone(), PreviewSolverMode::SparseInteractive).unwrap();\n        let case = &request.model.load_cases[0];\n        let (envelope, mut o) = observed(raw);\n        let row = envelope.results.iter().find(|r| r.kind == "modulus_basis_record").unwrap();\n        assert!(o.error.is_none());\n        o.rv62_source_check(case).unwrap();\n        o.rv62_record_check(row).unwrap();\n        let mut capture = o.basis_record.take().unwrap();\n        o.basis_record_calls = 0;\n        assert!(o.rv62_source_check(case).is_err(), "source-side missing capture must refuse");\n        assert!(o.basis_expected, "source expectation survives missing successful capture");\n        o.basis_record_calls = 1;\n        capture.case.push('x');\n        o.basis_record = Some(capture);\n        assert!(o.rv62_source_check(case).is_err(), "foreign captured owner");\n        o.basis_record.as_mut().unwrap().case.pop();\n        o.rv62_source_check(case).unwrap();\n        let mut foreign = case.clone(); foreign.id.push('x');\n        assert!(o.rv62_source_check(&foreign).is_err(), "foreign actual source owner");\n        let mut base = case.clone(); base.modulus_basis_ref=None; base.modulus_basis_temperature=None;\n        assert!(o.rv62_source_check(&base).is_err(), "base rejects captured selected history");\n        o.rv62_source_check(case).unwrap();\n        let mut altered = row.clone();\n        altered.metadata.as_mut().unwrap().basis.push_str(" é");\n        assert!(o.rv62_record_check(&altered).is_err());\n        // Dynamic text is owned bytes, not a parser or a numerical reconstruction.\n        o.basis_record.as_mut().unwrap().text = altered.metadata.as_ref().unwrap().basis.clone();\n        o.rv62_record_check(&altered).unwrap();\n        assert!(o.rv62_record_check(row).is_err());\n        for event in [E::ValidationEntry,E::LibraryBoundary,E::KeyProbe,E::IdentityByteRead] {\n            o.adapter=AdapterWork::default();\n            let mut counts=[0;10];counts[event as usize]=u64::MAX;o.adapter.counts.set(counts);\n            assert!(matches!(o.rv62_record_check(&altered), Err(CaptureError::Accounting(AdapterFault::Overflow(actual))) if actual==event));\n            let prefix=o.adapter.counts.get();\n            assert!(o.rv62_record_check(&altered).is_err());\n            assert_eq!(o.adapter.counts.get(),prefix);\n            println!("RV62_RECORD_PREFIX {interpolated} {event:?} {prefix:?}");\n        }\n    }\n    println!("RV62_SOURCE_TEXT_CONTROLS passed");\n}\n'''
(out/'access.rs').write_text(access);(out/'controls.rs').write_text(control)
for name,text in [('retained_product.rs',access),('retained_product_tests.rs',control)]:
 with (dst/pp/'src'/name).open('a') as f:f.write(text)
inv={str(p.relative_to(dst)):hashlib.sha256(p.read_bytes()).hexdigest() for p in (dst/pp).rglob('*') if p.is_file()}
(out/'OVERLAY.json').write_text(json.dumps({'source':str(src),'candidate':'d0daa18717f8243a7232e898c9ef9b4f4d18d9e4','scratch':str(dst),'recipe':'Copy frozen PP tree, append access.rs to retained_product.rs and controls.rs to retained_product_tests.rs. Other core directories and fixtures read only symlinks. Live overlay is not sealed.','files':inv},indent=2)+'\n')
runner=(out/'run.py').read_text().replace("code=wt/'f2a'","code=wt/'scratch/rv62-selected-material'")
(out/'run_controls.py').write_text(runner)
print('Overlay ready with frozen copied PP and two test-only append files.')
