"""I97 B2-C revision 01: regenerate DEF-C and PTABLE (records only; standard library only).

Imports the sealed v0 generator `b2c_statics.py` unchanged, checks that it still reproduces the sealed v0 statics, then
applies revision 01's changes (REVISION_01.md):
  DEF-C  rows.displacement_magnitude  S-4 (a): DEF-O's support-magnitude pattern (binary64 hypot of published components)
         stages.observables (new)     S-4 (b): the combination's observables stage
         scope.operand_equality       RV115 NB-1: "the selected material operands of every member, bit for bit"
         lanes.loads                  RV115 NB-3: data flags per individual product, never per net
  PTABLE accuracy_classification.scope  N-7 with S-3: states R-COMB-1 (quantity rows not_covered; records non_quantity)
         product_formation_definitions  DEF-C's new H
SCHEMA is regenerated by v0's functions and compared with the sealed v0 statics (it does not change).

Writes into <out_dir>:
  retained_precision_prepared_combination_v1.json          DEF-C r1
  semantic_contract_v0_3_preview_physics_retained_1.json   PTABLE r1
  b2c_statics_r1.out.json                                  hashes, controls and deltas

Usage: python b2c_statics_r1.py <P> <I96 record folder> <v0 b2c_statics.py> <v0 statics folder> <out_dir>
"""
import copy
import importlib.util
import json
import sys
from pathlib import Path

DISPLACEMENT_MAGNITUDE = (
    "finish the same node's frozen global_nodal_displacement_x/y/z rows; binary64 hypot(hypot(x,y),z) of their frozen "
    "raw values (mm), finite nonnegative and canonical +0, SI by the projection's mm rule; still certify dual physical "
    "norm and the unchanged 64-epsilon combination magnitude guard (base G7 combination_magnitudes), which the "
    "observables stage checks; not H of a lane norm hull")
OBSERVABLES = (
    "base G7 combination_magnitudes on the frozen rows: one support-action row per support and component, and each "
    "displacement, force and moment magnitude within 64 epsilon relative of binary64 hypot(hypot(x,y),z) of the same "
    "combination's published components; the case support coverage and guard; no preview case evidence, maximum or "
    "headline check; a failure is this combination's facade_certificate")
OPERAND_EQUALITY = (
    "equal K4STF bytes, layout, stations and supports (kernel OperandsDiffer) and equal prepared section facts across "
    "all operands and the combination: material basis, the selected material operands of every member bit for bit, "
    "normalized D, effective wall and the prepared A,I,J,Z,c bits of every member, as the operands' preparations and "
    "CaseSource section_terms state them")
LOADS = (
    "each loaded DOF's exact combined net N_g (the owner's K4LED: every operand term's exact product c_i*v_ij, summed "
    "exactly per DOF) enclosed outward at 1024 bits as [RD1024(N_g),RU1024(N_g)], in free residual rows and "
    "constrained reaction offsets; prescribed coordinates exact zero; data flags from each individual product "
    "(c_i!=0 and v_ij!=0), never from a net, so an exactly cancelled net stays data; the enclosure never takes an "
    "operand's individual terms, a binary64 product or a rounded net")
SCOPE_V0 = (
    "registered ordinary-prepared source, and registered prepared mechanics combinations "
    "(RP-PREPARED-COMBINATION-DUAL-v1: their own solve on the combined exact ledger, at least one operand "
    "selected); no exact-profile, subtraction or range extension")
SCOPE_R1 = SCOPE_V0 + (
    "; R-COMB-1: each quantity row of a retained_unavailable combination, and of an ordinary combination whose "
    "expression names a load case that is not not_required, is not_covered and withheld from binding with its value "
    "unchanged; record rows stay non_quantity")


def load(path, name):
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


def definition_r1(defc0, defo):
    d = copy.deepcopy(defc0)
    # S-4 (a): DEF-O's support-magnitude pattern, applied to the combination's displacement magnitude.
    assert defo["rows"]["support_magnitude"].startswith("finish same-support authenticated")
    assert "binary64 hypot(hypot(x,y),z)" in defo["rows"]["support_magnitude"]
    assert d["rows"]["displacement_magnitude"] == defo["rows"]["displacement_magnitude"]
    d["rows"]["displacement_magnitude"] = DISPLACEMENT_MAGNITUDE
    # S-4 (b): the observables stage is defined.
    assert "observables" in d["stages"]["entered"] and "observables" not in d["stages"]
    d["stages"]["observables"] = OBSERVABLES
    # RV115 NB-1 and NB-3.
    assert "material basis, normalized D" in d["scope"]["operand_equality"]
    d["scope"]["operand_equality"] = OPERAND_EQUALITY
    assert d["lanes"]["loads"].endswith("never an operand's individual terms, a binary64 product or a rounded net")
    d["lanes"]["loads"] = LOADS
    return d


def paths_changed(a, b, prefix=""):
    out = []
    for k in sorted(set(a) | set(b)):
        x, y = a.get(k), b.get(k)
        if isinstance(x, dict) and isinstance(y, dict):
            out += paths_changed(x, y, f"{prefix}{k}.")
        elif x != y:
            out.append(f"{prefix}{k}")
    return out


def main():
    p, i96, v0_gen, v0_statics, out = (Path(a) for a in sys.argv[1:6])
    out.mkdir(parents=True, exist_ok=True)
    v0 = load(v0_gen, "b2c_statics")
    load(i96 / "_run_records/b3d_statics.py", "b3d_statics")
    r1_b3 = load(i96 / "_run_records/revision_01/b3d_statics_r1.py", "b3d_statics_r1")
    res = p / "fixtures/results"
    defo_raw = (res / "retained_precision_prepared_ordinary_v1.json").read_bytes()
    defo = json.loads(defo_raw)
    ptable_raw = (res / "semantic_contract_v0_3_preview_physics_retained_1.json").read_bytes()
    schema_raw = (p / "schemas/retained_precision_mp_v2.schema.json").read_bytes()
    main_schema = json.loads(schema_raw)
    xtable = json.loads((i96 / "statics/r1/semantic_contract_v0_3_physics_retained_1.json").read_bytes())
    sealed = {name: (v0_statics / name).read_bytes() for name in (
        "retained_precision_prepared_combination_v1.json", "semantic_contract_v0_3_preview_physics_retained_1.json",
        "SCHEMA_B2.diff", "retained_precision_mp_v2.schema.json", "SCHEMA_J1.diff")}
    report = {"inputs": {"DEF-O": v0.sha(defo_raw), "PTABLE (main)": v0.sha(ptable_raw), "SCHEMA (main)": v0.sha(schema_raw),
                         "b2c_statics.py (v0, sealed)": v0.sha(v0_gen.read_bytes()),
                         **{f"v0 statics/{k}": v0.sha(v) for k, v in sealed.items()}}}
    defo_h = v0.h(v0.FORMATION_DOMAIN, defo)

    # Controls: v0's generator still reproduces every sealed v0 static byte for byte.
    defc0 = v0.combination_definition(defo)
    defc0_h = v0.h(v0.FORMATION_DOMAIN, defc0)
    table0 = v0.ptable_revision(ptable_raw, defo_h, defc0_h, xtable)
    b2 = v0.pretty(v0.apply_b2(main_schema))
    j1, _ = v0.apply_j1(main_schema, r1_b3.schema_r1)
    j1_raw = v0.pretty(j1)
    name = "schemas/retained_precision_mp_v2.schema.json"
    report["controls"] = {
        "v0_DEF_C_reproduces": v0.canonical(defc0) == sealed["retained_precision_prepared_combination_v1.json"],
        "v0_PTABLE_reproduces": table0 == sealed["semantic_contract_v0_3_preview_physics_retained_1.json"],
        "v0_SCHEMA_B2_diff_reproduces": v0.udiff(schema_raw, b2, name).encode() == sealed["SCHEMA_B2.diff"],
        "v0_J1_SCHEMA_reproduces": j1_raw == sealed["retained_precision_mp_v2.schema.json"],
        "v0_SCHEMA_J1_diff_reproduces": v0.udiff(schema_raw, j1_raw, name).encode() == sealed["SCHEMA_J1.diff"],
        "DEF_O_H": defo_h, "v0_DEF_C_H": defc0_h,
    }
    assert all(v for k, v in report["controls"].items() if k.startswith("v0_") and isinstance(v, bool))

    # DEF-C r1.
    defc1 = definition_r1(defc0, defo)
    defc1_raw = v0.canonical(defc1)
    assert all(b < 128 for b in defc1_raw) and v0.floats(defc1) == 0
    defc1_h = v0.h(v0.FORMATION_DOMAIN, defc1)
    (out / "retained_precision_prepared_combination_v1.json").write_bytes(defc1_raw)
    report["definition"] = {
        "file": "retained_precision_prepared_combination_v1.json", "bytes": len(defc1_raw),
        "raw_sha256": v0.sha(defc1_raw), "H_retained_precision_formation_v1": defc1_h,
        "H_alternative_domain_retained_precision_combination_formation_v1": v0.h(
            "retained_precision_combination_formation_v1", defc1),
        "ascii_only": True, "json_floats": 0,
        "canonical_bytes": v0.canonical(json.loads(defc1_raw)) == defc1_raw,
        "operand_definition_sha256_is_H_DEF_O": defc1["inherits"]["operand_definition"]["sha256"] == defo_h,
        "paths_changed_from_v0_DEF_C": paths_changed(defc0, defc1),
        "paths_changed_from_DEF_O": paths_changed(defo, defc1),
        "support_magnitude_equal_to_DEF_O": defc1["rows"]["support_magnitude"] == defo["rows"]["support_magnitude"],
        "rows.displacement_magnitude": defc1["rows"]["displacement_magnitude"],
        "DEF_O rows.support_magnitude": defo["rows"]["support_magnitude"],
    }

    # PTABLE r1: v0's revision with DEF-C r1's H, then the scope text (N-7, S-3).
    t = json.loads(v0.ptable_revision(ptable_raw, defo_h, defc1_h, xtable))
    assert t["accuracy_classification"]["scope"] == SCOPE_V0
    t["accuracy_classification"]["scope"] = SCOPE_R1
    table1 = v0.pretty(t)
    (out / "semantic_contract_v0_3_preview_physics_retained_1.json").write_bytes(table1)
    pt, t0 = json.loads(ptable_raw), json.loads(table0)
    report["table"] = {
        "file": "semantic_contract_v0_3_preview_physics_retained_1.json", "bytes": len(table1),
        "sha256": v0.sha(table1),
        "members_changed_from_main": [k for k in pt if t[k] != pt[k]],
        "members_added_to_main": [k for k in t if k not in pt],
        "paths_changed_from_v0_draft": paths_changed(t0, t),
        "accuracy_classification_keys_changed_from_main": [k for k in pt["accuracy_classification"]
                                                           if t["accuracy_classification"][k]
                                                           != pt["accuracy_classification"][k]],
        "product_formation_definitions": t["product_formation_definitions"],
        "scope": t["accuracy_classification"]["scope"],
        "formation_warrant_equal_to_v0_draft": t["formation_warrant"] == t0["formation_warrant"],
        "receipt_bindings_equal_to_XTABLE": v0.canonical(t["receipt_bindings"]) == v0.canonical(xtable["receipt_bindings"]),
        "roundtrip_indent2_ascii": v0.pretty(json.loads(table1)) == table1,
    }

    # SCHEMA: unchanged by revision 01 (no member of it binds DEF-C's bytes or PTABLE).
    report["schema"] = {
        "b2_only_sha256": v0.sha(b2), "j1_merged_sha256": v0.sha(j1_raw),
        "SCHEMA_B2_diff_sha256": v0.sha(sealed["SCHEMA_B2.diff"]), "SCHEMA_J1_diff_sha256": v0.sha(sealed["SCHEMA_J1.diff"]),
        "unchanged_from_v0_statics": True,
        "contains_a_definition_or_table_hash": any(x in j1_raw.decode() for x in (defo_h, defc0_h, defc1_h)),
        "OperandPreparation.definition_id": j1["$defs"]["OperandPreparation"]["properties"]["definition_id"],
        "CombinationAttempt.definition_id": j1["$defs"]["CombinationAttempt"]["properties"]["definition_id"],
    }
    report["reviewed_inputs_cascade"] = {
        "new_hashes": {"SCHEMA": v0.sha(j1_raw), "PTABLE": v0.sha(table1), "DEF-C": v0.sha(defc1_raw)},
        "moved_from_v0": {"PTABLE": [v0.sha(table0), v0.sha(table1)],
                          "DEF-C": [v0.sha(sealed["retained_precision_prepared_combination_v1.json"]), v0.sha(defc1_raw)]},
    }
    (out / "b2c_statics_r1.out.json").write_text(json.dumps(report, indent=2, sort_keys=True) + "\n")
    print(json.dumps({k: report[k] for k in ("controls", "reviewed_inputs_cascade")}, indent=1, sort_keys=True))
    print(json.dumps({"DEF-C": {k: report["definition"][k] for k in ("raw_sha256", "H_retained_precision_formation_v1",
                                                                      "paths_changed_from_v0_DEF_C")},
                      "PTABLE": {k: report["table"][k] for k in ("sha256", "paths_changed_from_v0_draft",
                                                                  "members_changed_from_main", "members_added_to_main")}},
                     indent=1))


if __name__ == "__main__":
    main()
