import { mkdir,mkdtemp,readFile,writeFile,symlink } from "node:fs/promises";
import {join,dirname} from "node:path";
import {it,expect} from "vitest";
import {discoverMethodCatalog} from "@chirality/runtime-core";
const base="/private/tmp/chirality-v3-adoption-20260909/execution/_Coordination/AgentRuns/CHIRALITY_V3_ADOPTION_20260909/astra-second-pass/runtime";
const fixture=JSON.parse(await readFile("/private/tmp/chirality-v3-adoption-20260909/tools/validation/fixtures/method_discovery_v1.json","utf8"));
async function put(path:string,text:string){await mkdir(dirname(path),{recursive:true});await writeFile(path,text);}
async function root(){return {source:"project" as const,sourceRootId:"fixture-project",rootPath:await mkdtemp(join(base,"shared-fixture-")),version:"v1"};}
const body=(name:string)=>`---\nname: ${name}\ndescription: Fixture\n---\nBody`;
for(const test of fixture.packageYamlCases) it(`shared YAML ${test.id}`,async()=>{const r=await root();const name=test.expected?.name??"first";await put(join(r.rootPath,".agents/skills",name,"SKILL.md"),`---\n${test.yaml}---\n`);const c=await discoverMethodCatalog([r]);if(test.expectedError){expect(c.response.methods).toHaveLength(0);expect(c.response.malformedPackages).toHaveLength(1);}else expect(c.response.methods[0]).toMatchObject(test.expected);});
for(const test of fixture.frontmatterDocumentCases) it(`shared frontmatter ${test.id}`,async()=>{const r=await root();await put(join(r.rootPath,".agents/skills/embedded-delimiter/SKILL.md"),test.document);const c=await discoverMethodCatalog([r]);expect(c.response.methods[0].description).toBe(test.expectedDescription);});
for(const test of fixture.methodNameCases) it(`shared name ${test.name}`,async()=>{const r=await root();await put(join(r.rootPath,".agents/skills",test.name,"SKILL.md"),body(test.name));const c=await discoverMethodCatalog([r]);expect(c.response.methods.length===1).toBe(test.valid);});
for(const kind of ["skill","workflow"]){for(const test of fixture[kind+"ExecutionCases"]) it(`shared ${kind} execution ${test.id}`,async()=>{const r=await root();const dir=join(r.rootPath,kind==="skill"?".agents/skills":"workflows","example");await put(join(dir,kind==="skill"?"SKILL.md":"WORKFLOW.md"),body("example"));if(test.executionJson!==null) await put(join(dir,"execution.json"),JSON.stringify(test.executionJson));const c=await discoverMethodCatalog([r]);if(test.expectedError){expect(c.response.methods).toHaveLength(0);expect(c.response.malformedPackages[0].code).toBe("malformed-execution-metadata");}else{const d=c.response.methods[0];expect(d.executionRoleIds).toEqual(test.expectedExecutionRoleIds);if(test.expectedExecution===null)expect(d.execution).toBeUndefined();else if(test.expectedExecution)expect(d.execution).toEqual(test.expectedExecution);if(test.expectedCommands)expect(d.execution?.tools?.commands).toEqual(test.expectedCommands);}});}
for(const test of fixture.packageContainmentCases)it(`shared containment ${test.id}`,async()=>{const r=await root();const outside=await mkdtemp(join(base,"outside-library-"));await put(join(outside,"example/SKILL.md"),body("example"));if(test.packagePathType.startsWith("collection")){await mkdir(join(r.rootPath,".agents"));await symlink(outside,join(r.rootPath,".agents/skills"));}else{await mkdir(join(r.rootPath,".agents/skills"),{recursive:true});await symlink(join(outside,"example"),join(r.rootPath,".agents/skills/example"));}const c=await discoverMethodCatalog([r]);expect(c.response.methods).toHaveLength(0);expect(c.response.malformedPackages.length).toBeGreaterThan(0);});
