#!/usr/bin/env python3
"""Bounded independent exact vectors; stdout is the reproducible Rust fixture.
No product arithmetic, binary64 arithmetic, bisection, or exponent-sized integers.
Sqrt uses isqrt and midpoint-square; binary64 uses direct quantum rounding.
"""
from fractions import Fraction as F
from math import isqrt

P = 1024
LIMIT = 1 << 62
MAX = 0x7fefffffffffffff


def pow2(e):
    assert abs(e) <= 2200
    return F(1 << e) if e >= 0 else F(1, 1 << -e)


def floor_log2(x):
    e = x.numerator.bit_length() - x.denominator.bit_length()
    return e - (x < pow2(e))


def decode(bits):
    sign = -1 if bits >> 63 else 1
    exp, frac = (bits >> 52) & 2047, bits & ((1 << 52) - 1)
    assert exp < 2047
    return sign * (frac * pow2(-1074) if exp == 0 else ((1 << 52) + frac) * pow2(exp - 1075))


def encode_exact(x):
    if x == 0:
        return 0
    e = floor_log2(x)
    if e > 1023:
        return 0x7ff0000000000000
    if e < -1022:
        n = x / pow2(-1074)
        assert n.denominator == 1
        return int(n)
    n = x / pow2(e - 52)
    assert n.denominator == 1
    return ((e + 1023) << 52) + int(n) - (1 << 52)


def round64(x, upward=False):
    if x == 0:
        return 0
    unit = pow2(max(floor_log2(x) - 52, -1074))
    n, d = (x / unit).as_integer_ratio()
    q, r = divmod(n, d)
    if (upward and r) or (not upward and (2*r > d or (2*r == d and q & 1))):
        q += 1
    return encode_exact(q * unit)


def scaled_component(x, power):
    # Simulate BOTH actual RN64 operations before the scale-back predicate.
    nearest = round64(x / pow2(power))
    back = round64(decode(nearest) * pow2(power))
    if back != 0x7ff0000000000000 and decode(back) < x:
        nearest += 1
    return nearest


def row(v, s):
    b = scaled_component(decode(s), 64)
    r = scaled_component(abs(decode(v)), 53)
    exact = decode(b) + decode(r) + pow2(-1074)
    answer = round64(exact, upward=True)
    assert decode(answer) >= exact
    assert decode(answer-1) < exact
    return b, r, answer


def token(m, e):
    if m == 1 << P:
        m >>= 1
        e += 1
    return '+' + f'{m:0256x}'.rstrip('0') + 'p' + str(e)


def sqrt_case(m, e):
    # Huge exponents enter only this symbolic output metadata.
    n = m << (1023 + e % 2)
    lo = isqrt(n)
    assert lo*lo <= n < (lo+1)*(lo+1)
    hi = lo + (lo*lo != n)
    twice_mid_square = (2*lo+1)**2
    near = lo + (4*n > twice_mid_square or (4*n == twice_mid_square and lo & 1))
    return token(lo, e//2), token(hi, e//2), token(near, e//2)


def main():
    print('// Generated by certificate_arithmetic_vectors.py; do not hand edit.')
    print('pub const SQRT: &[(&str, &str, &str, &str, &str)] = &[')
    m0 = 1 << 1023
    cases = [('one',m0,0), ('four',m0,2), ('nine',9 << 1020,3),
             ('sqrt_two',m0,1), ('sqrt_half',m0,-1), ('odd_negative',m0,-7),
             ('dense', (1<<1024)-1,0), ('above_one',m0+1,0),
             ('below_four',(1<<1024)-1,1), ('low_bits',m0+12345,-101),
             ('perfect_min',m0,-LIMIT), ('perfect_max',m0,LIMIT),
             ('max_odd',m0,LIMIT-1), ('near_min_safe',m0+1,-LIMIT+4096)]
    for name,m,e in cases:
        down,up,near = sqrt_case(m,e)
        print(f'    ("{name}", "{token(m,e)}", "{down}", "{up}", "{near}"),')
    print('];')
    print('pub const SMALL: &[(&str, u64, u64, u64, u64, u64)] = &[')
    cases = [('zero',0,1),('negative_zero',1<<63,1),('one_quantum',1,1),
             ('half_subnormal',0x0010000000000000,1),
             ('above_half_subnormal',0x0010000000000001,1),
             ('normal_boundary',0x035fffffffffffff,1),
             ('normal_equality',0x0360000000000000,1),
             ('normal_tie',0x0360000000000001,1),
             ('normal_above_tie',0x0360000000000002,1),
             ('final_normal_tie_even_up',0x0370000000000000,0x00e0000000000000),
             ('final_normal_tie_even_down',0x0370000000000001,0x00e0000000000000),
             ('double_round',0x4030000000000000,1),
             ('negative_double_round',0xc030000000000000,1),
             ('maximum_value',MAX,1),('b0_tie',0,0x00b0000000000000),
             ('b0_above_tie',0,0x00b0000000000001),
             ('scale_ceiling',0x000fffffffffffff,0x022fffffffffffff),
             ('exact_equality',0x000fffffffffffff,0x0010000000000000)]
    for name,v,s in cases:
        b,r,out = row(v,s)
        print('    (')
        print(f'        "{name}",')
        for bits in [v,s,b,r,out]:
            print(f'        0x{bits:016x},')
        print('    ),')
    # At the next normal binade, 3 subnormal quanta is exactly half-way
    # between two adjacent normal candidates (quantum=2h). Exercise both
    # nearest-even directions while the required final answer is always RU.
    for v in [0x0370000000000000, 0x0370000000000001]:
        b,r,out = row(v,0x00e0000000000000)
        exact = decode(b)+decode(r)+pow2(-1074)
        assert exact == (decode(out)+decode(out-1))/2
    assert round64(decode(row(0x0370000000000000,0x00e0000000000000)[1])+3*pow2(-1074)) == row(0x0370000000000000,0x00e0000000000000)[2]
    assert round64(decode(row(0x0370000000000001,0x00e0000000000000)[1])+3*pow2(-1074)) == row(0x0370000000000001,0x00e0000000000000)[2]-1
    # q=16 makes b0+h exactly half a p1024 ulp at r=2^-49. RN1024
    # loses that positive tail, and a subsequent upward binary64 conversion
    # is one bit below the direct quantum-ceil result.
    b,r,out = row(0x4030000000000000,1)
    assert decode(b)+pow2(-1074) == pow2(-1073)
    assert out == r+1 and r & 1 == 0
    print('];')


if __name__ == '__main__':
    main()
