#!/usr/bin/env python3
"""Independent exact cantilever oracle: rational annulus difference of powers,
atan(1/2)+atan(1/3) pi enclosure, closed mechanics, integer sqrt. No evaluator
imports. Generation is deterministic; --diagnose LOG checks actual emitted rows.
"""
from fractions import Fraction as F
from pathlib import Path
import json, math, struct, sys

def bits(x): return struct.unpack('>Q', struct.pack('>d', x))[0]
def real(bits): return F(struct.unpack('>d', struct.pack('>Q', bits))[0])
def atan(q, count=400):
    value=sum(((-1 if k % 2 else 1)*F(1, (2*k+1)*q**(2*k+1)) for k in range(count)), F(0))
    other=value+F(1, (2*count+1)*q**(2*count+1))
    return value, other
p2,p3=atan(2),atan(3)
PI=(4*(p2[0]+p3[0]),4*(p2[1]+p3[1]))
D,T,E,G=map(F,[0.1,0.005,210e9,80e9])
DI=D-2*T
AG=tuple(p*(D*D-DI*DI)/4 for p in PI)
IG=tuple(p*(D**4-DI**4)/64 for p in PI)
JG=tuple(2*i for i in IG)
# Fixed native K primitive bits. They are proposed test data, not a PP build.
A=F(float((AG[0]+AG[1])/2)); I=F(float((IG[0]+IG[1])/2)); J=F(float((JG[0]+JG[1])/2))
Z=F(float(I/(D/2)))
K=[(F(1)/(E*A),)*2,(F(1)/(3*E*I),)*2,(F(0),)*2,(F(1)/(G*J),)*2,(F(0),)*2,(F(1)/(2*E*I),)*2]
Q=[(1/(E*AG[1]),1/(E*AG[0])),(1/(3*E*IG[1]),1/(3*E*IG[0])),(F(0),)*2,(1/(G*JG[1]),1/(G*JG[0])),(F(0),)*2,(1/(2*E*IG[1]),1/(2*E*IG[0]))]

def floorlog(x):
    e=x.numerator.bit_length()-x.denominator.bit_length()
    if x < F(2)**e: e-=1
    return e

def dyadic(x, up):
    if x==0: return F(0)
    quantum=F(2)**(floorlog(abs(x))-511)
    f=x/quantum
    n=f.numerator//f.denominator
    if up and n*f.denominator!=f.numerator: n+=1
    return n*quantum

def sqrt_bound(x,up):
    if x==0:return F(0)
    e=floorlog(x)//2-511
    scaled=x/F(2)**(2*e)
    n=math.isqrt(scaled.numerator//scaled.denominator)
    if up and n*n*scaled.denominator!=scaled.numerator:n+=1
    return n*F(2)**e

def magnitude(u):
    return (sqrt_bound(sum(v[0]**2 for v in u[:3]),False),sqrt_bound(sum(v[1]**2 for v in u[:3]),True))

def lit(x):
    if x==0:return 'ZERO'
    neg=x<0;x=abs(x);e=floorlog(x);m=x/F(2)**(e-1023)
    assert m.denominator==1
    limbs=[(m.numerator>>(64*k)) & (2**64-1) for k in range(16)]
    return '('+str(neg).lower()+', '+str(e)+', ['+', '.join(f'0x{v:016x}' for v in limbs)+'])'

def pair(v):return '('+lit(dyadic(v[0],False))+', '+lit(dyadic(v[1],True))+')'

def generate():
    lines=['// Generated by source_bridge_vectors.py; independent exact source and K oracle.', 'pub type Bits = (bool, i64, [u64; 16]);','pub const ZERO: Bits = (false, 0, [0; 16]);']
    for name,value in [('D',D),('T',T),('E',E),('G',G),('A',A),('I',I),('J',J),('Z',Z)]:lines.append(f'pub const {name}: u64 = 0x{bits(float(value)):016x};')
    for name,value in [('K_MOTION',K),('G_MOTION',Q)]:
        lines.append(f'pub const {name}: [(Bits, Bits); 6] = [\n'+',\n'.join(pair(v) for v in value)+'\n];')
    for name,value in [('K_MAG',magnitude(K)),('G_MAG',magnitude(Q)),('ROOT_TWO',(sqrt_bound(F(2),False),sqrt_bound(F(2),True)))]:lines.append(f'pub const {name}: (Bits, Bits) = '+pair(value)+';')
    target=Path(__file__).with_suffix('.rs');target.write_text('\n'.join(lines)+'\n')
    print(json.dumps({'oracle':'rational closed cantilever; 400-term atan1/2+atan1/3; integer isqrt','file':str(target),'pi_width_log2_upper':floorlog(PI[1]-PI[0])+1,'native_bits':{n:hex(bits(float(v))) for n,v in [('A',A),('I',I),('J',J)]}}))

def wide(value):
    sign,exponent,mantissa=value
    return (-1 if sign else 1)*int(mantissa,16)*F(2)**(exponent-1023)

def contraction_check(raw,block):
    # Direct dense 12x12 matrix oracle; does not use the streaming contractions.
    rows={d['index']:d for d in raw if d['witness']=='loaded'}
    if not rows:return None
    scales=[F(0)]*6+[F(2)**s for s in block['scales']]
    motion=[F(0)]*6+[abs(real(int(rows[i]['x'],16)))+real(int(rows[i]['radius'],16)) for i in range(6,12)]
    b=[[F(0) for _ in range(12)] for _ in range(6)]
    h=[[F(0) for _ in range(12)] for _ in range(6)]
    for r in range(6):
        for j in range(12):
            if (r==0 and j%6<3) or (r==1 and j%6>=3) or (r>=2 and j%6<3) or (r in (2,4) and 3<=j<6) or (r in (3,5) and 9<=j<12):b[r][j]=F(1)
    for r,cols in enumerate([[0,6],[3,9],[1,7,5],[1,7,11],[2,8,4],[2,8,10]]):
        for j in cols:h[r][j]=F(1)
    ck=[E*A,G*J,E*I,E*I]
    cg=[tuple(E*a for a in AG),tuple(G*j for j in JG),tuple(E*i for i in IG),tuple(E*i for i in IG)]
    dc=[max(abs(lo-k),abs(hi-k)) for k,(lo,hi) in zip(ck,cg)]
    def matrix(c):
        return [[c[0],0,0,0,0,0],[0,c[1],0,0,0,0],[0,0,4*c[2],2*c[2],0,0],[0,0,2*c[2],4*c[2],0,0],[0,0,0,0,4*c[3],2*c[3]],[0,0,0,0,2*c[3],4*c[3]]]
    dg,dd=matrix([hi for lo,hi in cg]),matrix(dc)
    def dense(left,d):return [[sum(left[r][i]*d[r][s]*b[s][j] for r in range(6) for s in range(6)) for j in range(12)] for i in range(12)]
    perturbation=dense(b,dd)
    eta=max(scales[i]*sum(perturbation[i][j]*scales[j] for j in range(12)) for i in range(6,12))
    v=max(scales[i]*sum(perturbation[i][j]*motion[j] for j in range(12)) for i in range(6,12))
    beta=2*real(int(block['bound'],16)); alpha=beta*eta
    assert alpha<1
    tau=beta*v/(1-alpha)
    assert wide(block['alpha'])>=alpha and wide(block['tau'])>=tau
    corrections=[s*wide(block['tau']) for s in scales]
    ag,da=dense(h,dg),dense(h,dd)
    rg=dense(b,dg)
    response=[sum(ag[i][j]*corrections[j] for j in range(12)) for i in range(12)]
    coefficient=[sum(da[i][j]*motion[j] for j in range(12)) for i in range(12)]
    local=[a+b for a,b in zip(response,coefficient)]
    reaction=[sum(rg[i][j]*corrections[j]+perturbation[i][j]*motion[j] for j in range(12)) for i in range(6)]
    for i in range(12):assert wide(rows[14+i]['error'])>=local[i],('both end terms',i)
    for i in range(6):assert wide(rows[44+i]['error'])>=reaction[i],('both reaction terms',i)
    for si,t in enumerate([F(0),F(1,4),F(1)]):
        for c in range(6):
            expected=local[6+c] if c<4 else (1-t)*local[c]+t*local[6+c]
            assert wide(rows[26+6*si+c]['error'])>=expected,('station',si,c)
    # The two omitted-term mutants are discriminated: each true contribution is
    # nonzero and the production bound's rounding slack is far smaller than it.
    for i in range(12):
        actual=wide(rows[14+i]['error']); slack=actual-local[i]
        assert response[i]>slack and coefficient[i]>slack,('omitted-term discriminator',i)
    return {'dense_perturbation_entries':144,'local_rows':12,'reaction_rows':6,'station_rows':18,'both_terms_discriminated':12,'beta':float(beta),'alpha_lower':float(alpha),'tau_lower':float(tau),'actual_alpha':float(wide(block['alpha'])),'actual_tau':float(wide(block['tau']))}

def diagnose(path):
    reports=[]
    raw=[]
    block=None
    for line in Path(path).read_text().splitlines():
        if 'I42_BLOCK ' in line:block=json.loads(line.split('I42_BLOCK ',1)[1])
        at=line.find('I42_ROW ')
        if at<0:continue
        d=json.loads(line[at+8:]); raw.append(d); x=real(int(d['x'],16)); r=None if d['radius']=='absent' else real(int(d['radius'],16))
        lo,hi=wide(d['lo']),wide(d['hi']); k0,k1=wide(d['klo']),wide(d['khi']); g0,g1=wide(d['glo']),wide(d['ghi'])
        assert lo<=g0<=g1<=hi,(d['id'],'source enclosure')
        if r is not None: assert x-r<=k0<=k1<=x+r,(d['id'],'native K radius')
        h=max(abs(x-lo),abs(x-hi)); actual_lower=F(0) if g0<=x<=g1 else min(abs(x-g0),abs(x-g1)); actual_upper=max(abs(x-g0),abs(x-g1))
        if d['class']=='input':
            verdict=h==0; oracle_out=actual_lower>0; allowance=F(0)
        elif d['class']=='absolute':
            allowance=real(int(d['bound'],16));verdict=h<=allowance;oracle_out=actual_lower>allowance
        else:
            scale=real(int(d['scale'],16)); allowance=F(2)**-64*max(abs(x),scale)*(1+F(2)**-21)+F(2)**-53*abs(x)+F(2)**-1074
            f64_allowance=real(int(d['sharper'],16)); allowance=min(allowance,f64_allowance,abs(x)/10**9)
            verdict=h<=allowance; oracle_out=actual_lower>allowance
            # Native raw units here equal SI, so the second decimal test is identical.
        reports.append({'witness':d['witness'],'id':d['id'],'predicate_pass':verdict,'oracle_proves_actual_failure':oracle_out,'oracle_proves_actual_pass':actual_upper<=allowance,'enclosure_H':float(h),'allowance':float(allowance),'actual_error_lower':float(actual_lower),'actual_error_upper':float(actual_upper)})
    assert reports,'no diagnostic rows'
    summary={w:{'rows':sum(r['witness']==w for r in reports),'predicate_pass':sum(r['witness']==w and r['predicate_pass'] for r in reports),'oracle_proves_actual_failure':sum(r['witness']==w and r['oracle_proves_actual_failure'] for r in reports),'oracle_proves_actual_pass':sum(r['witness']==w and r['oracle_proves_actual_pass'] for r in reports)} for w in sorted({r['witness'] for r in reports})}
    print(json.dumps({'summary':summary,'contractions':contraction_check(raw,block),'rows':reports},indent=2))
if __name__=='__main__':
    if len(sys.argv)==3 and sys.argv[1]=='--diagnose':diagnose(sys.argv[2])
    else:generate()
