#!/usr/bin/env python3
"""Independent exact cantilever oracle: rational annulus difference of powers,
atan(1/2)+atan(1/3) pi enclosure, closed mechanics, integer sqrt. No evaluator
imports. Generation is deterministic; passing LOG checks actual emitted rows, casts,
centers and full source residuals with independent rational mechanics.
"""
from fractions import Fraction as F
from pathlib import Path
import json, math, struct, sys

def bits(x): return struct.unpack('>Q', struct.pack('>d', x))[0]
def real(bits): return F(struct.unpack('>d', struct.pack('>Q', bits))[0])
def atan(q, count=400):
    value=sum(((-1 if k % 2 else 1)*F(1, (2*k+1)*q**(2*k+1)) for k in range(count)), F(0))
    other=value+F(1, (2*count+1)*q**(2*count+1))
    return value, other
p2,p3=atan(2),atan(3)
PI=(4*(p2[0]+p3[0]),4*(p2[1]+p3[1]))
D,T,E,G=map(F,[0.1,0.005,210e9,80e9])
DI=D-2*T
AG=tuple(p*(D*D-DI*DI)/4 for p in PI)
IG=tuple(p*(D**4-DI**4)/64 for p in PI)
JG=tuple(2*i for i in IG)
# Fixed native K primitive bits. They are proposed test data, not a PP build.
A=F(float((AG[0]+AG[1])/2)); I=F(float((IG[0]+IG[1])/2)); J=F(float((JG[0]+JG[1])/2))
Z=F(float(I/(D/2)))
K=[(F(1)/(E*A),)*2,(F(1)/(3*E*I),)*2,(F(0),)*2,(F(1)/(G*J),)*2,(F(0),)*2,(F(1)/(2*E*I),)*2]
Q=[(1/(E*AG[1]),1/(E*AG[0])),(1/(3*E*IG[1]),1/(3*E*IG[0])),(F(0),)*2,(1/(G*JG[1]),1/(G*JG[0])),(F(0),)*2,(1/(2*E*IG[1]),1/(2*E*IG[0]))]

def floorlog(x):
    e=x.numerator.bit_length()-x.denominator.bit_length()
    if x < F(2)**e: e-=1
    return e

def dyadic(x, up):
    if x==0: return F(0)
    quantum=F(2)**(floorlog(abs(x))-767)
    f=x/quantum
    n=f.numerator//f.denominator
    if up and n*f.denominator!=f.numerator: n+=1
    return n*quantum

def sqrt_bound(x,up):
    if x==0:return F(0)
    e=floorlog(x)//2-767
    scaled=x/F(2)**(2*e)
    n=math.isqrt(scaled.numerator//scaled.denominator)
    if up and n*n*scaled.denominator!=scaled.numerator:n+=1
    return n*F(2)**e

def magnitude(u):
    return (sqrt_bound(sum(v[0]**2 for v in u[:3]),False),sqrt_bound(sum(v[1]**2 for v in u[:3]),True))

def lit(x):
    if x==0:return 'ZERO'
    neg=x<0;x=abs(x);e=floorlog(x);m=x/F(2)**(e-1023)
    assert m.denominator==1
    limbs=[(m.numerator>>(64*k)) & (2**64-1) for k in range(16)]
    return '('+str(neg).lower()+', '+str(e)+', ['+', '.join(f'0x{v:016x}' for v in limbs)+'])'

def pair(v):return '('+lit(dyadic(v[0],False))+', '+lit(dyadic(v[1],True))+')'

def generate():
    lines=['// Generated by source_residual_vectors.py; independent exact source and K oracle.', 'pub type Bits = (bool, i64, [u64; 16]);','pub const ZERO: Bits = (false, 0, [0; 16]);']
    for name,value in [('D',D),('T',T),('E',E),('G',G),('A',A),('I',I),('J',J),('Z',Z)]:lines.append(f'pub const {name}: u64 = 0x{bits(float(value)):016x};')
    for name,value in [('K_MOTION',K),('G_MOTION',Q)]:
        lines.append(f'pub const {name}: [(Bits, Bits); 6] = [\n'+',\n'.join(pair(v) for v in value)+'\n];')
    for name,value in [('K_MAG',magnitude(K)),('G_MAG',magnitude(Q)),('ROOT_TWO',(sqrt_bound(F(2),False),sqrt_bound(F(2),True)))]:lines.append(f'pub const {name}: (Bits, Bits) = '+pair(value)+';')
    extras={
      'FIXED_AXIAL':(E*AG[0]*F(0.0001),E*AG[1]*F(0.0001)),
      'SPRING_U':(1/(E*AG[1]+F(100000000)),1/(E*AG[0]+F(100000000))),
      'SPRING_ACTION':(-F(100000000)/(E*AG[0]+F(100000000)),-F(100000000)/(E*AG[1]+F(100000000))),
      'SPRING_REACTION':(-E*AG[1]/(E*AG[1]+F(100000000)),-E*AG[0]/(E*AG[0]+F(100000000))),
      'ROTATED_UX':(15/(E*AG[1]),15/(E*AG[0])),
      'ROTATED_UY':(20/(E*AG[1]),20/(E*AG[0])),
      'ROTATED_MAG':(25/(E*AG[1]),25/(E*AG[0])),
    }
    for name,value in extras.items():lines.append(f'pub const {name}: (Bits, Bits) = '+pair(value)+';')
    target=Path(__file__).with_suffix('.rs');target.write_text('\n'.join(lines)+'\n')
    print(json.dumps({'oracle':'rational closed cantilever; 400-term atan1/2+atan1/3; integer isqrt','file':str(target),'pi_width_log2_upper':floorlog(PI[1]-PI[0])+1,'native_bits':{n:hex(bits(float(v))) for n,v in [('A',A),('I',I),('J',J)]}}))

def wide(value):
    sign,exponent,mantissa=value
    return (-1 if sign else 1)*int(mantissa,16)*F(2)**(exponent-1023)




def diagnose(path):
    rows=[]; centers={};blocks={}
    for line in Path(path).read_text().splitlines():
        for marker in ['I44_ROW ','I44_CENTER ','I44_BLOCK ']:
            if marker not in line:continue
            d=json.loads(line.split(marker,1)[1])
            if marker=='I44_ROW ':rows.append(d)
            elif marker=='I44_CENTER ':centers.setdefault(d['witness'],{})[d['a']]=d
            else:blocks[d['witness']]=d
    assert len(rows)==104 and set(blocks)=={'zero','loaded'}
    def rn(x,p):
        if not x:return x
        step=F(2)**(floorlog(abs(x))-p+1);q=x/step;n=q.numerator//q.denominator;rem=q-n
        if rem>F(1,2) or rem==F(1,2) and n%2:n+=1
        return n*step
    def actions(u,p):
        ea=E*p*(D*D-DI*DI)/4;ei=E*p*(D**4-DI**4)/64;gj=G*p*(D**4-DI**4)/32
        return [ea*u[0],ei*(12*u[1]-6*u[5]),ei*(12*u[2]+6*u[4]),gj*u[3],ei*(6*u[2]+4*u[4]),ei*(-6*u[1]+4*u[5])]
    for label,cs in centers.items():
        block=blocks[label]; rr={d['index']:d for d in rows if d['witness']==label}
        x=[real(int(rr[6+a]['x'],16)) for a in range(6)]
        y=[wide(cs[a]['center']) for a in range(6)]
        scale=[F(2)**cs[a]['s'] for a in range(6)]
        f=[F(int(label=='loaded')) if a in (0,1,3) else F(0) for a in range(6)]
        for prefix,u in [('initial',x),('rho',y)]:
            ends=[[scale[a]*(f[a]-v) for a,v in enumerate(actions(u,p))] for p in PI]
            for a in range(6):
                lo=min(ends[0][a],ends[1][a]);hi=max(ends[0][a],ends[1][a])
                assert wide(cs[a][prefix+'_lo'])<=lo<=hi<=wide(cs[a][prefix+'_hi']),(label,prefix,a)
        if label=='loaded':
            for a in range(6):
                midpoint=rn(wide(cs[a]['initial_lo'])+wide(cs[a]['initial_hi']),1024)/2
                assert wide(cs[a]['rhs'])==rn(midpoint,block['P']),('actual cast',a)
                assert y[a]==rn(x[a]+scale[a]*wide(cs[a]['correction']),1024),('actual center',a)
            alpha=wide(block['alpha']);beta=2*real(int(block['bound'],16));eps=wide(block['epsilon'])
            omega=max(max(abs(wide(c['rho_lo'])),abs(wide(c['rho_hi']))) for c in cs.values())
            assert alpha<1 and eps>=beta*omega/(1-alpha)
            for a in range(6):assert y[a]-scale[a]*eps<=Q[a][0]<=Q[a][1]<=y[a]+scale[a]*eps
        else:assert all(v==0 for v in y) and wide(block['epsilon'])==0
    passed={}
    for d in rows:
        lo,hi=wide(d['lo']),wide(d['hi']);x=real(int(d['x'],16));b=real(int(d['bound'],16))
        assert lo<=wide(d['glo'])<=wide(d['ghi'])<=hi
        h=max(abs(x-lo),abs(x-hi));actual=h<=b
        if d['class']=='relative':
            scale=real(int(d['scale'],16))
            exact_allowance=F(2)**-64*max(abs(x),scale)+F(2)**-85*max(abs(x),scale)+F(2)**-53*abs(x)+F(2)**-1074
            # Independently reproduce each of the five binary64 RN operations.
            rn64=lambda z:F(float(z))
            a0=rn64(F(2)**-64*max(abs(x),scale));a1=rn64(a0*(1+F(2)**-21))
            u0=rn64(F(2)**-53*abs(x));u1=rn64(u0+F(2)**-1074)
            assert b==rn64(a1+u1),('five-operation binary64 allowance',d['index'])
            # Raw=SI; both decimal gates have identical exact operands.
            actual=actual and h<=exact_allowance and 10**9*h<=abs(x)
        assert actual==d['pass']
        passed[d['witness']]=passed.get(d['witness'],0)+actual
    assert passed=={'zero':52,'loaded':52}
    # Exact counter-control: a K-only residual after K correction misses delta*c.
    delta=F(1,8);x=F(1);correction=-delta;y=x+correction
    assert -delta-correction==0 and 1-(1+delta)*y==delta**2
    print(json.dumps({'source_rows':len(rows),'full_native_predicates':passed,'relative_gates':'H<=A_exact, H<=A_f64, 10^9 H<=abs(x) in SI and raw=SI','initial_and_recomputed_source_residual_components':24,'actual_cast_checks':6,'actual_center_checks':6,'wrong_K_only_residual':str(delta**2),'note':'actual factor output observed, never used as an expected source solution'}))

if __name__=='__main__':
    if len(sys.argv)>1:diagnose(sys.argv[1])
    else:generate()
