"""Prove the regenerated load-reference-1 raw envelopes differ from the frozen
CP3 inputs only in the LOAD_STATE_SOURCE_RECOVERY_NOT_JOINED message text.
The frozen inputs were never committed; they are reconstructed byte-exactly by
substituting the CP2 message into the regenerated bytes and must reproduce the
frozen sha256 values relayed in the CP3 briefs."""
import hashlib, json, pathlib, sys
root = pathlib.Path(sys.argv[1])
frozen = {
    "connected-sparse_interactive": "6c1dd176e5600bdbec08066345372a26459746ed34d665fa4767569594dd03bf",
    "connected-dense_scrutiny": "333515b39d15e1fc270b40f267d6ff47c5de24acd733ee52660d4488a3c31c11",
    "pressure-sparse_interactive": "20802f97f3e00fe7043d3adf5d78e926270f0e0f9c80f4b724ef4d122fc9ab75",
    "pressure-dense_scrutiny": "8215cad29a51e0e9d59f90b5db014256787592cf514b82ccef56fd814ce94be3",
}
NEW = "requested_mode={mode}; the published response for this case is the ordinary structural route; no retained-source response is joined into it; retained_source_attempt=not_required_ordinary_checks_passed"
OLD = "requested_mode={mode}; retained-source recovery is not attempted for resolved load/reference-state inputs until its join is verified; only the ordinary structural route is published; ordinary_needed_source_recovery=false"
report = {}
for name, sha in frozen.items():
    mode = name.split("-")[1]
    text = (root / f"fixtures/product_preview/load_reference/{name}.raw.json").read_text()
    count = text.count(NEW.format(mode=mode))
    raw = json.loads(text)
    cases = len(raw["numerical_quality"]["cases"])
    assert count == cases, (name, count, cases)
    old = text.replace(NEW.format(mode=mode), OLD.format(mode=mode))
    rebuilt = hashlib.sha256(old.encode()).hexdigest()
    report[name] = {"new_sha256": hashlib.sha256(text.encode()).hexdigest(), "reconstructed_frozen_sha256": rebuilt,
                    "matches_frozen": rebuilt == sha, "substituted_messages": count}
print(json.dumps(report, indent=1))
assert all(r["matches_frozen"] for r in report.values())
