# RV122's own mutants on lane A's new bounds and branches (PP retained_memory.rs at e96355ef8f).
# Each: (id, check, old, new). `old` must occur exactly once.
M = [
 ("RQ-01", "C-9 removed", "if m.combinations.iter().any(|combination| m.load_cases.iter().any(|case| case.id == combination.id)) {", "if false && m.combinations.iter().any(|combination| m.load_cases.iter().any(|case| case.id == combination.id)) {"),
 ("RQ-02", "C-9 against the first case only", "m.load_cases.iter().any(|case| case.id == combination.id)", "m.load_cases.iter().take(1).any(|case| case.id == combination.id)"),
 ("RQ-03", "C-9 over the first combination only", "if m.combinations.iter().any(|combination|", "if m.combinations.iter().take(1).any(|combination|"),
 ("RQ-04", "z cap 2 -> 3", "pub(crate) const COMBINATIONS: usize = 2;", "pub(crate) const COMBINATIONS: usize = 3;"),
 ("RQ-05", "z row observes 0", "row(K::Combinations, t.combinations.length, COMBINATIONS),", "row(K::Combinations, 0, COMBINATIONS),"),
 ("RQ-06", "C_eq cap 3 -> 4", "pub(crate) const CASE_EQUIVALENTS: usize = 3;", "pub(crate) const CASE_EQUIVALENTS: usize = 4;"),
 ("RQ-07", "C_eq drops z", "t.load_cases.length.saturating_add(t.combinations.length)", "t.load_cases.length"),
 ("RQ-08", "C_eq drops c", "t.load_cases.length.saturating_add(t.combinations.length)", "t.combinations.length"),
 ("RQ-09", "h cap 3 -> 4", "pub(crate) const COMBINATION_TERMS: usize = 3;", "pub(crate) const COMBINATION_TERMS: usize = 4;"),
 ("RQ-10", "census over the first combination only", "for combination in &request.model.combinations {", "for combination in request.model.combinations.iter().take(1) {"),
 ("RQ-11", "terms capacity read as length", "widest(&mut facts.terms, combination.terms.len(), combination.terms.capacity());", "widest(&mut facts.terms, combination.terms.len(), combination.terms.len());"),
 ("RQ-12", "range-operand cap 3 -> 4", "pub(crate) const RANGE_OPERANDS: usize = 3;", "pub(crate) const RANGE_OPERANDS: usize = 4;"),
 ("RQ-13", "operand ids not censused", "widest(&mut facts.range_operands, ids.len(), ids.capacity());", "let _ = ids;"),
 ("RQ-14", "operand-ids capacity read as length", "widest(&mut facts.range_operands, ids.len(), ids.capacity());", "widest(&mut facts.range_operands, ids.len(), ids.len());"),
 ("RQ-15", "CombinationsCapacity cap z+1", "row(K::CombinationsCapacity, t.combinations.capacity, COMBINATIONS),", "row(K::CombinationsCapacity, t.combinations.capacity, COMBINATIONS + 1),"),
 ("RQ-16", "walk skips combination provenance", "self.optional(&combination.provenance)?;", "let _ = &combination.provenance;"),
 ("RQ-17", "walk skips term case ids", "self.string(&term.load_case)?;", "let _ = term;"),
 ("RQ-18", "walk skips operand ids", "for id in combination.operand_ids.iter().flatten() {\n                self.string(id)?;", "for id in combination.operand_ids.iter().flatten() {\n                let _ = id;"),
 ("RQ-19", "walk skips combination label", "self.optional(&combination.label)?;", "let _ = &combination.label;"),
 ("RQ-20", "G-C rows bound (C_eq+1)", "            ceq * P_FINAL,\n", "            (ceq + 1) * P_FINAL,\n"),
 ("RQ-21", "G-C error-text bound (C_eq+1)", "ceq * (3 * m + 1) * text_atoms::ERR,", "(ceq + 1) * (3 * m + 1) * text_atoms::ERR,"),
 ("RQ-22", "B2A-13 analogue: C_eq read as C (equivalent while caps equal)", "let ceq = CASE_EQUIVALENTS as u64;", "let ceq = LOAD_CASES as u64;"),
 ("RQ-23", "L3 ignores the version", "(\"0.3.0\", Some(c)) if contract_is(c, \"1.0.0\", \"legacy_pressure_v1\")", "(\"0.3.0\", Some(c)) if c.mode.as_deref() == Some(\"legacy_pressure_v1\")"),
 ("RQ-24", "L3 ignores the mode", "(\"0.3.0\", Some(c)) if contract_is(c, \"1.0.0\", \"legacy_pressure_v1\")", "(\"0.3.0\", Some(c)) if c.version.as_deref() == Some(\"1.0.0\")"),
 ("RQ-25", "L3 admits 0.4.0", "(\"0.3.0\", Some(c)) if contract_is(c, \"1.0.0\"", "(\"0.3.0\" | \"0.4.0\", Some(c)) if contract_is(c, \"1.0.0\""),
 ("RQ-26", "E ignores the version", "(\"0.3.0\", Some(c)) if contract_is(c, \"2.0.0\", \"exact_straight_pressure_v2\")", "(\"0.3.0\", Some(c)) if c.mode.as_deref() == Some(\"exact_straight_pressure_v2\")"),
 ("RQ-27", "E admits 0.4.0", "(\"0.3.0\", Some(c)) if contract_is(c, \"2.0.0\"", "(\"0.3.0\" | \"0.4.0\", Some(c)) if contract_is(c, \"2.0.0\""),
 ("RQ-28", "refusal map: 0.3.0 mismatch -> SchemaVersion", "(\"0.1.0\" | \"0.2.0\" | \"0.3.0\", _) => Err(FamilyFact::PressureContract),", "(\"0.1.0\" | \"0.2.0\", _) => Err(FamilyFact::PressureContract),"),
 ("RQ-29", "L admits any contract", "(\"0.1.0\" | \"0.2.0\", None) => Ok(NamespaceBranch::Legacy),", "(\"0.1.0\" | \"0.2.0\", _) => Ok(NamespaceBranch::Legacy),"),
 ("RQ-30", "exact D1.4 clause removed", "if exact && !m.combinations.is_empty() {", "if false && exact && !m.combinations.is_empty() {"),
 ("RQ-31", "E admits non-empty regions", "Some(regions) => exact && regions.is_empty(),", "Some(_regions) => exact,"),
 ("RQ-32", "E admits absent regions", "None => !exact,", "None => true,"),
 ("RQ-33", "L/L3 admit Some([])", "Some(regions) => exact && regions.is_empty(),", "Some(regions) => regions.is_empty(),"),
 ("RQ-34", "exact clauses applied on L3", "Ok(branch) => branch == NamespaceBranch::Exact,", "Ok(branch) => branch != NamespaceBranch::Legacy,"),
 ("RQ-35", "walk skips the contract strings", "            self.optional(&contract.version)?;\n            self.optional(&contract.mode)?;", "            let _ = contract;"),
 ("RQ-36", "branch E dropped (E refused)", "        (\"0.3.0\", Some(c)) if contract_is(c, \"2.0.0\", \"exact_straight_pressure_v2\") => Ok(NamespaceBranch::Exact),\n", ""),
 ("RQ-37", "terms-capacity row reads length", "row(K::CombinationTermsCapacity, z.terms.capacity, COMBINATION_TERMS),", "row(K::CombinationTermsCapacity, z.terms.length, COMBINATION_TERMS),"),
 ("RQ-38", "operand-capacity row reads length", "row(K::RangeOperandsCapacity, z.range_operands.capacity, RANGE_OPERANDS),", "row(K::RangeOperandsCapacity, z.range_operands.length, RANGE_OPERANDS),"),
 ("RQ-39", "census keeps the last combination only", "fact.length = fact.length.max(length);", "fact.length = length;"),
 ("RQ-40", "C-9 compares ids by prefix", "case.id == combination.id)", "combination.id.starts_with(case.id.as_str()) && case.id.len() + 1 < combination.id.len())"),
]
