//! Stable binary64 evaluation of the arc integrals that cancel at small
//! included angles (T4-U1; `curved-numerical-integrity.md`, "Stable
//! small-angle evaluation").
//!
//! Each function below is a fixed combination of φ, S = sin φ and
//! C = cos φ whose closed form loses relative accuracy like 1/φ^k as φ → 0.
//! It is evaluated as
//! - a Taylor series φ^m · Σ a_k (φ²)^k (Horner, fixed term count) when the
//!   half-angle sine s = sin(φ/2) satisfies s < 1/2 (φ < π/3), and
//! - otherwise as its closed form in half-angle quantities: S = 2sc,
//!   C = 1 − 2s², 1 − C = 2s² (no libm call; s and c are the element's
//!   correctly rounded geometry).
//!
//! The switch compares the binary64 s with the exact constant 1/2, so it is
//! bitwise deterministic and independent of libm. The truncated series at
//! φ ≤ 1.049 (> π/3) omits less than 2⁻⁶² of the leading term, and at the
//! switch the two forms agree to a few ulp of each function (T4-I14 sweep:
//! jump ≤ 2.1e-15 relative), so the evaluation is continuous to rounding.
//! The coefficients are the exact rationals (listed per series), rounded
//! once to binary64; they were generated by exact rational arithmetic
//! (T4-I14 `series_gen.py`, standard library only).

/// Half-angle sine below which the series are used (φ < π/3).
pub(crate) const SERIES_SWITCH_HALF_SINE: f64 = 0.5;

struct Series {
    power: u32,
    coefficients: &'static [f64],
}

impl Series {
    fn eval(&self, phi: f64) -> f64 {
        let square = phi * phi;
        let mut sum = 0.0;
        for coefficient in self.coefficients.iter().rev() {
            sum = sum * square + coefficient;
        }
        let mut power = 1.0;
        for _ in 0..self.power {
            power *= phi;
        }
        power * sum
    }
}

// g0: phi^3 * sum_k a_k phi^(2k); exact a_k: 1/6, -1/120, 1/5040, -1/362880, 1/39916800, -1/6227020800, 1/1307674368000, -1/355687428096000, 1/121645100408832000, -1/51090942171709440000
const PHI_MINUS_SIN: Series = Series {
    power: 3,
    coefficients: &[
        0.16666666666666666,
        -0.008333333333333333,
        0.0001984126984126984,
        -2.7557319223985893e-06,
        2.505210838544172e-08,
        -1.6059043836821613e-10,
        7.647163731819816e-13,
        -2.8114572543455206e-15,
        8.22063524662433e-18,
        -1.9572941063391263e-20,
    ],
};
// g1: phi^3 * sum_k a_k phi^(2k); exact a_k: 2/3, -2/15, 4/315, -2/2835, 4/155925, -4/6081075, 8/638512875, -2/10854718875, 4/1856156927625, -4/194896477400625, 8/49308808782358125, -4/3698160658676859375
const PHI_MINUS_SIN_COS: Series = Series {
    power: 3,
    coefficients: &[
        0.6666666666666666,
        -0.13333333333333333,
        0.012698412698412698,
        -0.0007054673721340388,
        2.565335898669232e-05,
        -6.577784355562133e-07,
        1.2529113058213587e-08,
        -1.8425166262078804e-10,
        2.1549902060910882e-12,
        -2.0523716248486557e-14,
        1.622428161935696e-16,
        -1.0816187746237974e-18,
    ],
};
// g2: phi^3 * sum_k a_k phi^(2k); exact a_k: 1/3, -1/30, 1/840, -1/45360, 1/3991680, -1/518918400, 1/93405312000, -1/22230464256000, 1/6758061133824000, -1/2554547108585472000
const SIN_MINUS_PHI_COS: Series = Series {
    power: 3,
    coefficients: &[
        0.3333333333333333,
        -0.03333333333333333,
        0.0011904761904761906,
        -2.2045855379188714e-05,
        2.505210838544172e-07,
        -1.9270852604185937e-09,
        1.0706029224547743e-11,
        -4.498331606952833e-14,
        1.4797143443923793e-16,
        -3.9145882126782523e-19,
    ],
};
// g4: phi^4 * sum_k a_k phi^(2k); exact a_k: 1/24, -1/360, 1/13440, -1/907200, 1/95800320, -1/14529715200, 1/2988969984000, -1/800296713216000, 1/270322445352960000, -1/112400072777760768000
const ONE_MINUS_COS_MINUS_HALF_PHI_SIN: Series = Series {
    power: 4,
    coefficients: &[
        0.041666666666666664,
        -0.002777777777777778,
        7.440476190476191e-05,
        -1.1022927689594355e-06,
        1.043837849393405e-08,
        -6.882447358637835e-11,
        3.3456341326711696e-13,
        -1.249536557486898e-15,
        3.6992858609809485e-18,
        -8.896791392450573e-21,
    ],
};
// a1: phi^3 * sum_k a_k phi^(2k); exact a_k: 1/3, -3/20, 13/504, -11/5184, 683/6652800, -133/40435200, 3781/50295168000, -76459/59281238016000, 61681/3577797070848000, -22577/122227134382080000, 776723/478741050720092160000, -308611/25938478333329408000000, 7320967/98989722276530474188800000
const IN_PLANE_XX: Series = Series {
    power: 3,
    coefficients: &[
        0.3333333333333333,
        -0.15,
        0.025793650793650792,
        -0.0021219135802469135,
        0.00010266354016354016,
        -3.289213358657803e-06,
        7.517620778202789e-08,
        -1.289767261260025e-09,
        1.72399380899992e-11,
        -1.8471348538226112e-13,
        1.6224282392990994e-15,
        -1.1897806649800776e-17,
        7.395683947418985e-20,
    ],
};
// a2: phi^4 * sum_k a_k phi^(2k); exact a_k: -5/24, 49/720, -107/13440, 1793/3628800, -9217/479001600, 15019/29059430400, -19363/1902071808000, 983041/6402373705728000, -495161/270322445352960000, 569227/32114306507931648000, -17616077/124089680346647887872000, 128625323/134430487042201878528000000
const IN_PLANE_XY: Series = Series {
    power: 4,
    coefficients: &[
        -0.20833333333333334,
        0.06805555555555555,
        -0.007961309523809523,
        0.000494102733686067,
        -1.9242106915718025e-05,
        5.168373843969083e-07,
        -1.0179952154571863e-08,
        1.5354320837605974e-10,
        -1.8317420862091875e-12,
        1.772502855882662e-14,
        -1.4196246578111098e-16,
        9.568166108006477e-19,
    ],
};
// a3: phi^5 * sum_k a_k phi^(2k); exact a_k: 2/15, -8/315, 2/945, -16/155925, 4/1216215, -16/212837625, 2/1550674125, -32/1856156927625, 4/21655164155625, -16/9861761756471625, 4/336196423516078125, -32/432684797065192546875
const IN_PLANE_YY: Series = Series {
    power: 5,
    coefficients: &[
        0.13333333333333333,
        -0.025396825396825397,
        0.0021164021164021165,
        -0.00010261343594676929,
        3.2888921777810667e-06,
        -7.517467834928152e-08,
        1.2897616383455163e-09,
        -1.7239921648728706e-11,
        1.84713446236379e-13,
        -1.622428161935696e-15,
        1.1897806520861771e-17,
        -7.395683929051606e-20,
    ],
};
// d1: phi^5 * sum_k a_k phi^(2k); exact a_k: 1/20, -1/168, 1/2880, -17/1330560, 31/94348800, -1/159667200, 5461/59281238016000, -257/238519804723200, 73/7113748561920000, -1271/15667888932657561600, 60787/112400072777760768000000
const TORSION_ZZ: Series = Series {
    power: 5,
    coefficients: &[
        0.05,
        -0.005952380952380952,
        0.00034722222222222224,
        -1.2776575276575277e-05,
        3.285680369013702e-07,
        -6.26302709636043e-09,
        9.212020839588534e-11,
        -1.077478661775051e-12,
        1.026181897836115e-14,
        -8.112133073338138e-17,
        5.40809258372893e-19,
    ],
};

// T4-U1b (T4-RV8 C-1): the integrals of the uniform-load free-tip deflection
// (`tip_deflection_under_uniform_load`), each ∫₀^φ f(θ) dθ with ψ = φ − θ,
// a_x(θ) = S − sin θ − ψ cos θ and a_y(θ) = cos θ − C − ψ sin θ (the load's
// in-plane moment arms). Below the switch they are these series; above it
// CB keeps its Gram closed forms. Generated by T4-I17 `load_series_gen.py`
// (exact rationals; integrand kept to total degree 90; K terms leave less
// than 2⁻⁶² of the leading term at φ = 1.049), checked against direct
// 45-digit quadrature at φ = 0.3, 0.8 and 1.04 (≤ 2.4e-17 relative).
// LOAD_P0X: int (sin t - S) a_x = phi^5 * sum_k a_k phi^(2k); K = 12; exact a_k: 7/120, -83/5040, 193/120960, -3331/39916800, 17411/6227020800, -28673/435891456000, 409603/355687428096000, -172777/11058645491712000, 192239/1135354270482432000, -456439/304141373398646784000, 171966467/15511210043330985984000000, -251658241/3629623150139450720256000000
const LOAD_P0X: Series = Series {
    power: 5,
    coefficients: &[
        0.058333333333333334,
        -0.01646825396825397,
        0.0015955687830687831,
        -8.344857303190637e-05,
        2.7960401224290112e-06,
        -6.578013770474088e-08,
        1.1515813257516883e-09,
        -1.562370365606613e-11,
        1.6932071776883726e-13,
        -1.500746165835624e-15,
        1.1086592633302431e-17,
        -6.93345371103695e-20,
    ],
};
// LOAD_P0Y: int (sin t - S) a_y = phi^4 * sum_k a_k phi^(2k); K = 12; exact a_k: -1/8, 31/720, -233/40320, 473/1209600, -1099/68428800, 5561/12454041600, -997/110702592000, 176951/1280474741145600, -4063253/2432902008176640000, 6116701/374666909259202560000, -81788953/620448401733239439360000, 360710171/403291461126605635584000000
const LOAD_P0Y: Series = Series {
    power: 4,
    coefficients: &[
        -0.125,
        0.043055555555555555,
        -0.0057787698412698416,
        0.00039103835978835977,
        -1.6060489150766928e-05,
        4.46521713882825e-07,
        -9.006112521737522e-09,
        1.3819171461491507e-10,
        -1.6701260413876025e-12,
        1.6325703842098145e-14,
        -1.318223284507146e-16,
        8.944155921187777e-19,
    ],
};
// LOAD_P1X: int (C - cos t) a_x = phi^6 * sum_k a_k phi^(2k); K = 12; exact a_k: 13/360, -113/20160, 47/120960, -3841/239500800, 19457/43589145600, -31403/3487131648000, 442369/3201186852864000, -290231/173778714869760000, 1019449/62444484876533760000, -8178893/62044840173323943936000, 180355073/201645730563302817792000000, -262843051/50814724101952310083584000000
const LOAD_P1X: Series = Series {
    power: 6,
    coefficients: &[
        0.03611111111111111,
        -0.00560515873015873,
        0.00038855820105820107,
        -1.6037524718080274e-05,
        4.4637259419005453e-07,
        -9.005395600137663e-09,
        1.381890593497304e-10,
        -1.670118231784118e-12,
        1.632568515883622e-14,
        -1.3182229138075044e-16,
        8.944155301288711e-19,
        -5.172576564080991e-21,
    ],
};
// LOAD_P1Y: int (C - cos t) a_y = phi^5 * sum_k a_k phi^(2k); K = 12; exact a_k: -3/40, 29/1680, -13/8064, 53/633600, -5807/2075673600, 869/13208832000, -389/337784832000, 12929/827517689856000, -18847/111309242204160000, 45377/30236276887584768000, -57322163/5170403347776995328000000, 191959/2768591266315370496000000
const LOAD_P1Y: Series = Series {
    power: 5,
    coefficients: &[
        -0.075,
        0.017261904761904763,
        -0.0016121031746031745,
        8.36489898989899e-05,
        -2.7976460268126934e-06,
        6.578931430121906e-08,
        -1.1516206861532493e-09,
        1.5623835186230077e-11,
        -1.693210700817764e-13,
        1.500746939469658e-15,
        -1.1086594051631494e-17,
        6.933453931445507e-20,
    ],
};
// LOAD_P5X: int a_x = phi^4 * sum_k a_k phi^(2k); K = 10; exact a_k: -1/12, 1/180, -1/6720, 1/453600, -1/47900160, 1/7264857600, -1/1494484992000, 1/400148356608000, -1/135161222676480000, 1/56200036388880384000
const LOAD_P5X: Series = Series {
    power: 4,
    coefficients: &[
        -0.08333333333333333,
        0.005555555555555556,
        -0.00014880952380952382,
        2.204585537918871e-06,
        -2.08767569878681e-08,
        1.376489471727567e-10,
        -6.691268265342339e-13,
        2.499073114973796e-15,
        -7.398571721961897e-18,
        1.7793582784901146e-20,
    ],
};
// LOAD_P5Y: int a_y = phi^3 * sum_k a_k phi^(2k); K = 10; exact a_k: 1/6, -1/40, 1/1008, -1/51840, 1/4435200, -1/566092800, 1/100590336000, -1/23712495206400, 1/7155594141696000, -1/2688996956405760000
const LOAD_P5Y: Series = Series {
    power: 3,
    coefficients: &[
        0.16666666666666666,
        -0.025,
        0.000992063492063492,
        -1.9290123456790123e-05,
        2.2546897546897547e-07,
        -1.7664948220503776e-09,
        9.941312851365761e-12,
        -4.217185881518281e-14,
        1.3975079919261362e-16,
        -3.7188588020443397e-19,
    ],
};
// LOAD_Q2: int sin psi (1 - cos psi) = phi^4 * sum_k a_k phi^(2k); K = 12; exact a_k: 1/8, -1/48, 1/640, -17/241920, 31/14515200, -1/21288960, 5461/6974263296000, -257/25107347865600, 73/677499863040000, -1271/1362425124578918400, 60787/8992005822220861440000, -241/5793169017117081600000
const LOAD_Q2: Series = Series {
    power: 4,
    coefficients: &[
        0.125,
        -0.020833333333333332,
        0.0015625,
        -7.027116402116402e-05,
        2.1356922398589067e-06,
        -4.697270322270322e-08,
        7.830217713650253e-10,
        -1.0236047286862984e-11,
        1.0774909927279209e-13,
        -9.32895303433886e-16,
        6.7601157296611625e-18,
        -4.160071962131902e-20,
    ],
};
// LOAD_Q3: int cos t (1 - cos psi) = phi^3 * sum_k a_k phi^(2k); K = 10; exact a_k: 1/6, -1/60, 1/1680, -1/90720, 1/7983360, -1/1037836800, 1/186810624000, -1/44460928512000, 1/13516122267648000, -1/5109094217170944000
const LOAD_Q3: Series = Series {
    power: 3,
    coefficients: &[
        0.16666666666666666,
        -0.016666666666666666,
        0.0005952380952380953,
        -1.1022927689594357e-05,
        1.252605419272086e-07,
        -9.635426302092969e-10,
        5.353014612273871e-12,
        -2.2491658034764165e-14,
        7.398571721961897e-17,
        -1.9572941063391261e-19,
    ],
};
// LOAD_Q4: int sin t (1 - cos psi) = phi^4 * sum_k a_k phi^(2k); K = 10; exact a_k: 1/24, -1/360, 1/13440, -1/907200, 1/95800320, -1/14529715200, 1/2988969984000, -1/800296713216000, 1/270322445352960000, -1/112400072777760768000
const LOAD_Q4: Series = Series {
    power: 4,
    coefficients: &[
        0.041666666666666664,
        -0.002777777777777778,
        7.440476190476191e-05,
        -1.1022927689594355e-06,
        1.043837849393405e-08,
        -6.882447358637835e-11,
        3.3456341326711696e-13,
        -1.249536557486898e-15,
        3.6992858609809485e-18,
        -8.896791392450573e-21,
    ],
};
// LOAD_T2: int (1 - cos psi)(psi - sin psi) = phi^6 * sum_k a_k phi^(2k); K = 11; exact a_k: 1/72, -1/720, 41/604800, -23/10886400, 157/3353011200, -31/39626496000, 1927/188305108992000, -3449/32011868528640000, 4481/4803421913579520000, -4559/674400436666564608000, 88301/2122586637508450713600000
const LOAD_T2: Series = Series {
    power: 6,
    coefficients: &[
        0.013888888888888888,
        -0.001388888888888889,
        6.779100529100529e-05,
        -2.1127278071722516e-06,
        4.6823583529932736e-08,
        -7.823048497651672e-10,
        1.0233392021678324e-11,
        -1.0774128966930779e-13,
        9.32876620171962e-16,
        -6.7600786596970275e-18,
        4.160065763141244e-20,
    ],
};
// LOAD_T3: int sin t (psi - sin psi) = phi^5 * sum_k a_k phi^(2k); K = 9; exact a_k: 1/120, -1/2520, 1/120960, -1/9979200, 1/1245404160, -1/217945728000, 1/50812489728000, -1/15205637551104000, 1/5676771352412160000
const LOAD_T3: Series = Series {
    power: 5,
    coefficients: &[
        0.008333333333333333,
        -0.0003968253968253968,
        8.267195767195768e-06,
        -1.0020843354176688e-07,
        8.029521918410807e-10,
        -4.58829823909189e-12,
        1.9680200780418645e-14,
        -6.576508197299464e-17,
        1.7615646957052136e-19,
    ],
};
// LOAD_T4: int cos t (psi - sin psi) = phi^4 * sum_k a_k phi^(2k); K = 10; exact a_k: 1/24, -1/360, 1/13440, -1/907200, 1/95800320, -1/14529715200, 1/2988969984000, -1/800296713216000, 1/270322445352960000, -1/112400072777760768000
const LOAD_T4: Series = Series {
    power: 4,
    coefficients: &[
        0.041666666666666664,
        -0.002777777777777778,
        7.440476190476191e-05,
        -1.1022927689594355e-06,
        1.043837849393405e-08,
        -6.882447358637835e-11,
        3.3456341326711696e-13,
        -1.249536557486898e-15,
        3.6992858609809485e-18,
        -8.896791392450573e-21,
    ],
};
// LOAD_ASC: int psi sin t cos t = phi^3 * sum_k a_k phi^(2k); K = 12; exact a_k: 1/6, -1/30, 1/315, -1/5670, 1/155925, -1/6081075, 2/638512875, -1/21709437750, 1/1856156927625, -1/194896477400625, 2/49308808782358125, -1/3698160658676859375
const LOAD_ASC: Series = Series {
    power: 3,
    coefficients: &[
        0.16666666666666666,
        -0.03333333333333333,
        0.0031746031746031746,
        -0.0001763668430335097,
        6.41333974667308e-06,
        -1.6444460888905332e-07,
        3.132278264553397e-09,
        -4.606291565519701e-11,
        5.387475515227721e-13,
        -5.130929062121639e-15,
        4.05607040483924e-17,
        -2.7040469365594935e-19,
    ],
};
// LOAD_ASS: int psi sin^2 t = phi^4 * sum_k a_k phi^(2k); K = 12; exact a_k: 1/12, -1/90, 1/1260, -1/28350, 1/935550, -1/42567525, 1/2554051500, -1/195384939750, 1/18561569276250, -1/2143861251406875, 1/295852852694148750, -1/48076088562799171875
const LOAD_ASS: Series = Series {
    power: 4,
    coefficients: &[
        0.08333333333333333,
        -0.011111111111111112,
        0.0007936507936507937,
        -3.527336860670194e-05,
        1.0688899577788467e-06,
        -2.3492086984150476e-08,
        3.915347830691746e-10,
        -5.118101739466334e-12,
        5.387475515227721e-14,
        -4.664480965565127e-16,
        3.380058670699367e-18,
        -2.0800361050457643e-20,
    ],
};
// LOAD_ACC: int psi cos^2 t = phi^2 * sum_k a_k phi^(2k); K = 12; exact a_k: 1/2, -1/12, 1/90, -1/1260, 1/28350, -1/935550, 1/42567525, -1/2554051500, 1/195384939750, -1/18561569276250, 1/2143861251406875, -1/295852852694148750
const LOAD_ACC: Series = Series {
    power: 2,
    coefficients: &[
        0.5,
        -0.08333333333333333,
        0.011111111111111112,
        -0.0007936507936507937,
        3.527336860670194e-05,
        -1.0688899577788467e-06,
        2.3492086984150476e-08,
        -3.915347830691746e-10,
        5.118101739466334e-12,
        -5.387475515227721e-14,
        4.664480965565127e-16,
        -3.380058670699367e-18,
    ],
};

/// The uniform-load integrals of `LOAD_*` (names as there: p0x = ∫(sin θ − S)a_x,
/// p0y = ∫(sin θ − S)a_y, p1x = ∫(C − cos θ)a_x, p1y = ∫(C − cos θ)a_y,
/// p5x = ∫a_x, p5y = ∫a_y, q2 = ∫sin ψ(1 − cos ψ), q3 = ∫cos θ(1 − cos ψ),
/// q4 = ∫sin θ(1 − cos ψ), t2 = ∫(1 − cos ψ)(ψ − sin ψ), t3 = ∫sin θ(ψ − sin ψ),
/// t4 = ∫cos θ(ψ − sin ψ), asc = ∫ψ sin θ cos θ, ass = ∫ψ sin²θ, acc = ∫ψ cos²θ).
#[derive(Debug, Clone, Copy)]
pub(crate) struct LoadIntegrals {
    pub(crate) p0x: f64,
    pub(crate) p0y: f64,
    pub(crate) p1x: f64,
    pub(crate) p1y: f64,
    pub(crate) p5x: f64,
    pub(crate) p5y: f64,
    pub(crate) q2: f64,
    pub(crate) q3: f64,
    pub(crate) q4: f64,
    pub(crate) t2: f64,
    pub(crate) t3: f64,
    pub(crate) t4: f64,
    pub(crate) asc: f64,
    pub(crate) ass: f64,
    pub(crate) acc: f64,
}

/// Half-angle quantities of one arc: φ, s = sin(φ/2), c = cos(φ/2).
#[derive(Debug, Clone, Copy)]
pub(crate) struct HalfAngle {
    pub(crate) phi: f64,
    pub(crate) s: f64,
    pub(crate) c: f64,
}

impl HalfAngle {
    pub(crate) fn use_series(&self) -> bool {
        self.s < SERIES_SWITCH_HALF_SINE
    }
    /// sin φ = 2sc.
    pub(crate) fn sin(&self) -> f64 {
        2.0 * self.s * self.c
    }
    /// cos φ = 1 − 2s².
    pub(crate) fn cos(&self) -> f64 {
        1.0 - 2.0 * self.s * self.s
    }
    /// 1 − cos φ = 2s² (exact from s up to one rounding).
    pub(crate) fn one_minus_cos(&self) -> f64 {
        2.0 * self.s * self.s
    }
    /// φ − sin φ.
    pub(crate) fn phi_minus_sin(&self) -> f64 {
        if self.use_series() {
            PHI_MINUS_SIN.eval(self.phi)
        } else {
            self.phi - self.sin()
        }
    }
    /// φ − sin φ cos φ = 2∫₀^φ sin²θ dθ.
    pub(crate) fn phi_minus_sin_cos(&self) -> f64 {
        if self.use_series() {
            PHI_MINUS_SIN_COS.eval(self.phi)
        } else {
            self.phi - self.sin() * self.cos()
        }
    }
    /// sin φ − φ cos φ.
    pub(crate) fn sin_minus_phi_cos(&self) -> f64 {
        if self.use_series() {
            SIN_MINUS_PHI_COS.eval(self.phi)
        } else {
            self.sin() - self.phi * self.cos()
        }
    }
    /// (1 − cos φ) − φ sin φ / 2 = ∫₀^φ (1 − cos(φ − θ)) sin θ dθ.
    pub(crate) fn one_minus_cos_minus_half_phi_sin(&self) -> f64 {
        if self.use_series() {
            ONE_MINUS_COS_MINUS_HALF_PHI_SIN.eval(self.phi)
        } else {
            self.one_minus_cos() - 0.5 * self.phi * self.sin()
        }
    }
    /// ∫₀^φ (sin φ − sin θ)² dθ = φS² − 2S(1 − C) + (φ − SC)/2.
    pub(crate) fn in_plane_xx(&self) -> f64 {
        if self.use_series() {
            IN_PLANE_XX.eval(self.phi)
        } else {
            let (sin, cos) = (self.sin(), self.cos());
            self.phi * sin * sin - 2.0 * sin * self.one_minus_cos() + 0.5 * (self.phi - sin * cos)
        }
    }
    /// ∫₀^φ (sin φ − sin θ)(cos φ − cos θ) dθ = φSC − S²/2 − C(1 − C).
    pub(crate) fn in_plane_xy(&self) -> f64 {
        if self.use_series() {
            IN_PLANE_XY.eval(self.phi)
        } else {
            let (sin, cos) = (self.sin(), self.cos());
            self.phi * sin * cos - 0.5 * sin * sin - cos * self.one_minus_cos()
        }
    }
    /// ∫₀^φ (cos φ − cos θ)² dθ = φC² − 2CS + (φ + SC)/2.
    pub(crate) fn in_plane_yy(&self) -> f64 {
        if self.use_series() {
            IN_PLANE_YY.eval(self.phi)
        } else {
            let (sin, cos) = (self.sin(), self.cos());
            self.phi * cos * cos - 2.0 * cos * sin + 0.5 * (self.phi + sin * cos)
        }
    }
    /// The load integrals by their series (valid below the switch only;
    /// the caller checks `use_series`).
    pub(crate) fn load_integrals_series(&self) -> LoadIntegrals {
        let phi = self.phi;
        LoadIntegrals {
            p0x: LOAD_P0X.eval(phi),
            p0y: LOAD_P0Y.eval(phi),
            p1x: LOAD_P1X.eval(phi),
            p1y: LOAD_P1Y.eval(phi),
            p5x: LOAD_P5X.eval(phi),
            p5y: LOAD_P5Y.eval(phi),
            q2: LOAD_Q2.eval(phi),
            q3: LOAD_Q3.eval(phi),
            q4: LOAD_Q4.eval(phi),
            t2: LOAD_T2.eval(phi),
            t3: LOAD_T3.eval(phi),
            t4: LOAD_T4.eval(phi),
            asc: LOAD_ASC.eval(phi),
            ass: LOAD_ASS.eval(phi),
            acc: LOAD_ACC.eval(phi),
        }
    }
    /// ∫₀^φ (1 − cos ψ)² dψ = 3φ/2 − 2S + SC/2.
    pub(crate) fn torsion_zz(&self) -> f64 {
        if self.use_series() {
            TORSION_ZZ.eval(self.phi)
        } else {
            let (sin, cos) = (self.sin(), self.cos());
            1.5 * self.phi - 2.0 * sin + 0.5 * sin * cos
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn half(phi: f64) -> HalfAngle {
        HalfAngle {
            phi,
            s: (0.5 * phi).sin(),
            c: (0.5 * phi).cos(),
        }
    }

    // Each series against its own closed form just above the switch, where
    // the closed form is accurate (cancellation there is at most a factor
    // of about 20): continuity of the switch to rounding.
    #[test]
    fn series_and_closed_forms_agree_at_the_switch() {
        let from_s = |s: f64| {
            let c = (1.0 - s * s).sqrt();
            HalfAngle {
                phi: 2.0 * s.atan2(c),
                s,
                c,
            }
        };
        let below = from_s(SERIES_SWITCH_HALF_SINE * (1.0 - f64::EPSILON));
        let above = from_s(SERIES_SWITCH_HALF_SINE);
        assert!(below.use_series() && !above.use_series());
        let pairs: [(f64, f64); 8] = [
            (below.phi_minus_sin(), above.phi_minus_sin()),
            (below.phi_minus_sin_cos(), above.phi_minus_sin_cos()),
            (below.sin_minus_phi_cos(), above.sin_minus_phi_cos()),
            (
                below.one_minus_cos_minus_half_phi_sin(),
                above.one_minus_cos_minus_half_phi_sin(),
            ),
            (below.in_plane_xx(), above.in_plane_xx()),
            (below.in_plane_xy(), above.in_plane_xy()),
            (below.in_plane_yy(), above.in_plane_yy()),
            (below.torsion_zz(), above.torsion_zz()),
        ];
        for (series, closed) in pairs {
            assert!(
                (series - closed).abs() <= 1e-13 * closed.abs(),
                "series {series} closed {closed}"
            );
        }
    }

    // Leading terms at tiny angles: phi^3/6, 2phi^3/3, phi^3/3, phi^4/24,
    // phi^3/3, -5phi^4/24, 2phi^5/15, phi^5/20.
    #[test]
    fn series_reproduce_leading_terms_at_small_angles() {
        let phi = 1e-8;
        let h = half(phi);
        assert!(h.use_series());
        let p3 = phi * phi * phi;
        let p4 = p3 * phi;
        let p5 = p4 * phi;
        for (value, expected) in [
            (h.phi_minus_sin(), p3 / 6.0),
            (h.phi_minus_sin_cos(), 2.0 * p3 / 3.0),
            (h.sin_minus_phi_cos(), p3 / 3.0),
            (h.one_minus_cos_minus_half_phi_sin(), p4 / 24.0),
            (h.in_plane_xx(), p3 / 3.0),
            (h.in_plane_xy(), -5.0 * p4 / 24.0),
            (h.in_plane_yy(), 2.0 * p5 / 15.0),
            (h.torsion_zz(), p5 / 20.0),
        ] {
            assert!((value - expected).abs() <= 1e-14 * expected.abs());
        }
    }
}
