//! Stable binary64 evaluation of the arc integrals that cancel at small
//! included angles (T4-U1; `curved-numerical-integrity.md`, "Stable
//! small-angle evaluation").
//!
//! Each function below is a fixed combination of φ, S = sin φ and
//! C = cos φ whose closed form loses relative accuracy like 1/φ^k as φ → 0.
//! It is evaluated as
//! - a Taylor series φ^m · Σ a_k (φ²)^k (Horner, fixed term count) when the
//!   half-angle sine s = sin(φ/2) satisfies s < 1/2 (φ < π/3), and
//! - otherwise as its closed form in half-angle quantities: S = 2sc,
//!   C = 1 − 2s², 1 − C = 2s² (no libm call; s and c are the element's
//!   correctly rounded geometry).
//!
//! The switch compares the binary64 s with the exact constant 1/2, so it is
//! bitwise deterministic and independent of libm. The truncated series at
//! φ ≤ 1.049 (> π/3) omits less than 2⁻⁶² of the leading term, and at the
//! switch the two forms agree to a few ulp of each function (jump ≤ 5.0e-15
//! relative, in the torsion integral at s = 1/2, whose closed form carries
//! 4.5e-15: T4-RV11's high-precision check; T4-I14's sweep had reported
//! 2.1e-15), so the evaluation is continuous to rounding.
//! The coefficients are the exact rationals (listed per series), rounded
//! once to binary64; they were generated by exact rational arithmetic
//! (T4-I14 `series_gen.py`, standard library only).

/// Half-angle sine below which the series are used (φ < π/3).
pub(crate) const SERIES_SWITCH_HALF_SINE: f64 = 0.5;

struct Series {
    power: u32,
    coefficients: &'static [f64],
}

impl Series {
    fn eval(&self, phi: f64) -> f64 {
        let square = phi * phi;
        let mut sum = 0.0;
        for coefficient in self.coefficients.iter().rev() {
            sum = sum * square + coefficient;
        }
        let mut power = 1.0;
        for _ in 0..self.power {
            power *= phi;
        }
        power * sum
    }
}

// g0: phi^3 * sum_k a_k phi^(2k); exact a_k: 1/6, -1/120, 1/5040, -1/362880, 1/39916800, -1/6227020800, 1/1307674368000, -1/355687428096000, 1/121645100408832000, -1/51090942171709440000
const PHI_MINUS_SIN: Series = Series {
    power: 3,
    coefficients: &[
        0.16666666666666666,
        -0.008333333333333333,
        0.0001984126984126984,
        -2.7557319223985893e-06,
        2.505210838544172e-08,
        -1.6059043836821613e-10,
        7.647163731819816e-13,
        -2.8114572543455206e-15,
        8.22063524662433e-18,
        -1.9572941063391263e-20,
    ],
};
// g1: phi^3 * sum_k a_k phi^(2k); exact a_k: 2/3, -2/15, 4/315, -2/2835, 4/155925, -4/6081075, 8/638512875, -2/10854718875, 4/1856156927625, -4/194896477400625, 8/49308808782358125, -4/3698160658676859375
const PHI_MINUS_SIN_COS: Series = Series {
    power: 3,
    coefficients: &[
        0.6666666666666666,
        -0.13333333333333333,
        0.012698412698412698,
        -0.0007054673721340388,
        2.565335898669232e-05,
        -6.577784355562133e-07,
        1.2529113058213587e-08,
        -1.8425166262078804e-10,
        2.1549902060910882e-12,
        -2.0523716248486557e-14,
        1.622428161935696e-16,
        -1.0816187746237974e-18,
    ],
};
// g2: phi^3 * sum_k a_k phi^(2k); exact a_k: 1/3, -1/30, 1/840, -1/45360, 1/3991680, -1/518918400, 1/93405312000, -1/22230464256000, 1/6758061133824000, -1/2554547108585472000
const SIN_MINUS_PHI_COS: Series = Series {
    power: 3,
    coefficients: &[
        0.3333333333333333,
        -0.03333333333333333,
        0.0011904761904761906,
        -2.2045855379188714e-05,
        2.505210838544172e-07,
        -1.9270852604185937e-09,
        1.0706029224547743e-11,
        -4.498331606952833e-14,
        1.4797143443923793e-16,
        -3.9145882126782523e-19,
    ],
};
// g4: phi^4 * sum_k a_k phi^(2k); exact a_k: 1/24, -1/360, 1/13440, -1/907200, 1/95800320, -1/14529715200, 1/2988969984000, -1/800296713216000, 1/270322445352960000, -1/112400072777760768000
const ONE_MINUS_COS_MINUS_HALF_PHI_SIN: Series = Series {
    power: 4,
    coefficients: &[
        0.041666666666666664,
        -0.002777777777777778,
        7.440476190476191e-05,
        -1.1022927689594355e-06,
        1.043837849393405e-08,
        -6.882447358637835e-11,
        3.3456341326711696e-13,
        -1.249536557486898e-15,
        3.6992858609809485e-18,
        -8.896791392450573e-21,
    ],
};
// a1: phi^3 * sum_k a_k phi^(2k); exact a_k: 1/3, -3/20, 13/504, -11/5184, 683/6652800, -133/40435200, 3781/50295168000, -76459/59281238016000, 61681/3577797070848000, -22577/122227134382080000, 776723/478741050720092160000, -308611/25938478333329408000000, 7320967/98989722276530474188800000
const IN_PLANE_XX: Series = Series {
    power: 3,
    coefficients: &[
        0.3333333333333333,
        -0.15,
        0.025793650793650792,
        -0.0021219135802469135,
        0.00010266354016354016,
        -3.289213358657803e-06,
        7.517620778202789e-08,
        -1.289767261260025e-09,
        1.72399380899992e-11,
        -1.8471348538226112e-13,
        1.6224282392990994e-15,
        -1.1897806649800776e-17,
        7.395683947418985e-20,
    ],
};
// a2: phi^4 * sum_k a_k phi^(2k); exact a_k: -5/24, 49/720, -107/13440, 1793/3628800, -9217/479001600, 15019/29059430400, -19363/1902071808000, 983041/6402373705728000, -495161/270322445352960000, 569227/32114306507931648000, -17616077/124089680346647887872000, 128625323/134430487042201878528000000
const IN_PLANE_XY: Series = Series {
    power: 4,
    coefficients: &[
        -0.20833333333333334,
        0.06805555555555555,
        -0.007961309523809523,
        0.000494102733686067,
        -1.9242106915718025e-05,
        5.168373843969083e-07,
        -1.0179952154571863e-08,
        1.5354320837605974e-10,
        -1.8317420862091875e-12,
        1.772502855882662e-14,
        -1.4196246578111098e-16,
        9.568166108006477e-19,
    ],
};
// a3: phi^5 * sum_k a_k phi^(2k); exact a_k: 2/15, -8/315, 2/945, -16/155925, 4/1216215, -16/212837625, 2/1550674125, -32/1856156927625, 4/21655164155625, -16/9861761756471625, 4/336196423516078125, -32/432684797065192546875
const IN_PLANE_YY: Series = Series {
    power: 5,
    coefficients: &[
        0.13333333333333333,
        -0.025396825396825397,
        0.0021164021164021165,
        -0.00010261343594676929,
        3.2888921777810667e-06,
        -7.517467834928152e-08,
        1.2897616383455163e-09,
        -1.7239921648728706e-11,
        1.84713446236379e-13,
        -1.622428161935696e-15,
        1.1897806520861771e-17,
        -7.395683929051606e-20,
    ],
};
// d1: phi^5 * sum_k a_k phi^(2k); exact a_k: 1/20, -1/168, 1/2880, -17/1330560, 31/94348800, -1/159667200, 5461/59281238016000, -257/238519804723200, 73/7113748561920000, -1271/15667888932657561600, 60787/112400072777760768000000
const TORSION_ZZ: Series = Series {
    power: 5,
    coefficients: &[
        0.05,
        -0.005952380952380952,
        0.00034722222222222224,
        -1.2776575276575277e-05,
        3.285680369013702e-07,
        -6.26302709636043e-09,
        9.212020839588534e-11,
        -1.077478661775051e-12,
        1.026181897836115e-14,
        -8.112133073338138e-17,
        5.40809258372893e-19,
    ],
};

/// Half-angle quantities of one arc: φ, s = sin(φ/2), c = cos(φ/2).
#[derive(Debug, Clone, Copy)]
pub(crate) struct HalfAngle {
    pub(crate) phi: f64,
    pub(crate) s: f64,
    pub(crate) c: f64,
}

impl HalfAngle {
    fn use_series(&self) -> bool {
        self.s < SERIES_SWITCH_HALF_SINE
    }
    /// sin φ = 2sc.
    pub(crate) fn sin(&self) -> f64 {
        2.0 * self.s * self.c
    }
    /// cos φ = 1 − 2s².
    pub(crate) fn cos(&self) -> f64 {
        1.0 - 2.0 * self.s * self.s
    }
    /// 1 − cos φ = 2s² (exact from s up to one rounding).
    pub(crate) fn one_minus_cos(&self) -> f64 {
        2.0 * self.s * self.s
    }
    /// φ − sin φ.
    pub(crate) fn phi_minus_sin(&self) -> f64 {
        if self.use_series() {
            PHI_MINUS_SIN.eval(self.phi)
        } else {
            self.phi - self.sin()
        }
    }
    /// φ − sin φ cos φ = 2∫₀^φ sin²θ dθ.
    pub(crate) fn phi_minus_sin_cos(&self) -> f64 {
        if self.use_series() {
            PHI_MINUS_SIN_COS.eval(self.phi)
        } else {
            self.phi - self.sin() * self.cos()
        }
    }
    /// sin φ − φ cos φ.
    pub(crate) fn sin_minus_phi_cos(&self) -> f64 {
        if self.use_series() {
            SIN_MINUS_PHI_COS.eval(self.phi)
        } else {
            self.sin() - self.phi * self.cos()
        }
    }
    /// (1 − cos φ) − φ sin φ / 2 = ∫₀^φ (1 − cos(φ − θ)) sin θ dθ.
    pub(crate) fn one_minus_cos_minus_half_phi_sin(&self) -> f64 {
        if self.use_series() {
            ONE_MINUS_COS_MINUS_HALF_PHI_SIN.eval(self.phi)
        } else {
            self.one_minus_cos() - 0.5 * self.phi * self.sin()
        }
    }
    /// ∫₀^φ (sin φ − sin θ)² dθ = φS² − 2S(1 − C) + (φ − SC)/2.
    pub(crate) fn in_plane_xx(&self) -> f64 {
        if self.use_series() {
            IN_PLANE_XX.eval(self.phi)
        } else {
            let (sin, cos) = (self.sin(), self.cos());
            self.phi * sin * sin - 2.0 * sin * self.one_minus_cos() + 0.5 * (self.phi - sin * cos)
        }
    }
    /// ∫₀^φ (sin φ − sin θ)(cos φ − cos θ) dθ = φSC − S²/2 − C(1 − C).
    pub(crate) fn in_plane_xy(&self) -> f64 {
        if self.use_series() {
            IN_PLANE_XY.eval(self.phi)
        } else {
            let (sin, cos) = (self.sin(), self.cos());
            self.phi * sin * cos - 0.5 * sin * sin - cos * self.one_minus_cos()
        }
    }
    /// ∫₀^φ (cos φ − cos θ)² dθ = φC² − 2CS + (φ + SC)/2.
    pub(crate) fn in_plane_yy(&self) -> f64 {
        if self.use_series() {
            IN_PLANE_YY.eval(self.phi)
        } else {
            let (sin, cos) = (self.sin(), self.cos());
            self.phi * cos * cos - 2.0 * cos * sin + 0.5 * (self.phi + sin * cos)
        }
    }
    /// ∫₀^φ (1 − cos ψ)² dψ = 3φ/2 − 2S + SC/2.
    pub(crate) fn torsion_zz(&self) -> f64 {
        if self.use_series() {
            TORSION_ZZ.eval(self.phi)
        } else {
            let (sin, cos) = (self.sin(), self.cos());
            1.5 * self.phi - 2.0 * sin + 0.5 * sin * cos
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn half(phi: f64) -> HalfAngle {
        HalfAngle {
            phi,
            s: (0.5 * phi).sin(),
            c: (0.5 * phi).cos(),
        }
    }

    // Each series against its own closed form just above the switch, where
    // the closed form is accurate (cancellation there is at most a factor
    // of about 20): continuity of the switch to rounding.
    #[test]
    fn series_and_closed_forms_agree_at_the_switch() {
        let from_s = |s: f64| {
            let c = (1.0 - s * s).sqrt();
            HalfAngle {
                phi: 2.0 * s.atan2(c),
                s,
                c,
            }
        };
        let below = from_s(SERIES_SWITCH_HALF_SINE * (1.0 - f64::EPSILON));
        let above = from_s(SERIES_SWITCH_HALF_SINE);
        assert!(below.use_series() && !above.use_series());
        let pairs: [(f64, f64); 8] = [
            (below.phi_minus_sin(), above.phi_minus_sin()),
            (below.phi_minus_sin_cos(), above.phi_minus_sin_cos()),
            (below.sin_minus_phi_cos(), above.sin_minus_phi_cos()),
            (
                below.one_minus_cos_minus_half_phi_sin(),
                above.one_minus_cos_minus_half_phi_sin(),
            ),
            (below.in_plane_xx(), above.in_plane_xx()),
            (below.in_plane_xy(), above.in_plane_xy()),
            (below.in_plane_yy(), above.in_plane_yy()),
            (below.torsion_zz(), above.torsion_zz()),
        ];
        for (series, closed) in pairs {
            assert!(
                (series - closed).abs() <= 1e-13 * closed.abs(),
                "series {series} closed {closed}"
            );
        }
    }

    // Leading terms at tiny angles: phi^3/6, 2phi^3/3, phi^3/3, phi^4/24,
    // phi^3/3, -5phi^4/24, 2phi^5/15, phi^5/20.
    #[test]
    fn series_reproduce_leading_terms_at_small_angles() {
        let phi = 1e-8;
        let h = half(phi);
        assert!(h.use_series());
        let p3 = phi * phi * phi;
        let p4 = p3 * phi;
        let p5 = p4 * phi;
        for (value, expected) in [
            (h.phi_minus_sin(), p3 / 6.0),
            (h.phi_minus_sin_cos(), 2.0 * p3 / 3.0),
            (h.sin_minus_phi_cos(), p3 / 3.0),
            (h.one_minus_cos_minus_half_phi_sin(), p4 / 24.0),
            (h.in_plane_xx(), p3 / 3.0),
            (h.in_plane_xy(), -5.0 * p4 / 24.0),
            (h.in_plane_yy(), 2.0 * p5 / 15.0),
            (h.torsion_zz(), p5 / 20.0),
        ] {
            assert!((value - expected).abs() <= 1e-14 * expected.abs());
        }
    }
}
