import {build} from '../app/node_modules/esbuild/lib/main.js';
import {readFileSync,writeFileSync} from 'node:fs';
import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
const source=process.argv[2],output=process.argv[3];
const code=readFileSync(source,'utf8').replace('import { useState } from "react";','const useState = globalThis.syntheticUseState;');
await build({stdin:{contents:code,resolveDir:new URL('../app',import.meta.url).pathname,loader:'tsx'},bundle:true,format:'esm',outfile:output,jsx:'automatic'});
let hooks=[],position=0;globalThis.syntheticUseState=initial=>{const index=position++;if(index===hooks.length)hooks.push(initial);return[hooks[index],value=>{hooks[index]=typeof value==='function'?value(hooks[index]):value}];};
const {FileActPanel}=await import(pathToFileURL(output));
let selected=0;const calls=[];
const offer=id=>({reference:id,offer:{wording:'mark checked',subject:{ref:id},scope:'scope',purpose:'purpose'},byteLength:1,utf8:'x',hex:'78'});
const pending={state:'AC-8 record pending',capture:{captureId:'capture-A'}};
const command=async(name,args)=>{calls.push({name,args});if(name==='file_act_select')return offer(++selected===1?'A':'B');if(name==='file_act_confirm')return pending;if(name==='file_act_read')return{hotOffers:[{reference:'A',status:pending}],rows:[]};if(name==='file_act_continue')return{state:'AC-7 recorded',capture:{captureId:'capture-A'}};throw Error(name)};
const render=()=>{position=0;return FileActPanel({command})};
const flatten=node=>node==null||typeof node!=='object'?[]:Array.isArray(node)?node.flatMap(flatten):[node,...flatten(node.props?.children)];
const label=node=>typeof node==='string'?node:Array.isArray(node)?node.map(label).join(''):node?.props?label(node.props.children):'';
const button=(tree,text)=>flatten(tree).find(node=>node.type==='button'&&label(node)===text);
const click=async text=>{const node=button(render(),text);assert(node,`missing ${text}`);assert.equal(node.props.disabled,false,`disabled ${text}`);await node.props.onClick();};
// Drive the real component handler; synthetic hooks supply only React state scheduling.
flatten(render()).filter(node=>node.type==='input').forEach(node=>node.props.onChange({target:{value:'explicit scope/purpose'}}));
await click('Select file and freeze preview…');await click('Review native act / decline / cancel…');await click('Read file-act log and current content');await click('Select file and freeze preview…');await click('Continue original capture/record only');
const tree=render();
assert.equal(button(tree,'Review native act / decline / cancel…').props.disabled,false,'continuing A must leave newly composed B operable');
assert.equal(button(tree,'Dismiss offer without capture').props.disabled,false,'B dismissal remains available');
assert.equal(button(tree,'Continue this original capture/record only'),undefined,'A continuation must not mint a B continuation');
assert.equal(calls.at(-1).args.reference,'A');
const articles=flatten(tree).filter(node=>node.type==='article');assert(articles.some(a=>label(a).includes('Original offer A: AC-7 recorded')));
writeFileSync(output+'.result.json',JSON.stringify({passed:true,source,calls},null,2));console.log('PASS actual panel A pending → compose B → continue A; B remains unattempted, A owns result');
