#!/usr/bin/env python3
"""Generate VERIFICATION.md §1-§3 for PKG-01 (structural validator results, recheck tables, every REFUTED /
CONTESTED item). §4-§5 (patterns, rerun decisions) are read from _scripts/verification_patterns.md."""
import csv, glob, hashlib, io, os, subprocess, collections
P = os.path.dirname(os.path.dirname(os.path.abspath(__file__))); RUN = os.path.dirname(os.path.dirname(P)); APP = os.path.abspath(os.path.join(RUN, "../../../.."))
V = ["python3", os.path.join(RUN, "_scripts", "validate_ledger.py")]
ACCEPT = {"DEL-01-01": "ledger of record", "DEL-01-02": "ledger of record (merged S1+S2)", "DEL-01-03_A": "ledger of record",
          "DEL-01-03_B": "double-blind comparison only (not verified)", "DEL-01-04": "ledger of record"}
import re
def unit_of(shard): return re.sub(r"-\d+$", "", shard[2:]) if re.search(r"DEL-\d\d-\d\d-\d+$", shard) else shard[2:]
def rows(p):
    t = open(p, encoding="utf-8").read().rstrip()
    t = t[:-6] if t.endswith('"#END"') else (t[:-4] if t.endswith("#END") else t)
    return list(csv.DictReader(io.StringIO(t)))
def sha(p): return hashlib.sha256(open(p, "rb").read()).hexdigest()
def val(args): 
    o = subprocess.run(V + args, cwd=APP, capture_output=True, text=True).stdout.strip().splitlines()
    return o[-1].replace("RESULT ", "") if o else "?"
out = ["# VERIFICATION — PKG-01 (RUN_D128_CONCORDANCE_2026-09-21_1614Z, R2 wave 4)", "",
       "> §1–§3 generated by `R2/PKG-01/_scripts/verify_tables.py`; §4–§5 hand-written by the PKG-01 manager.",
       "> Verification evidence, not a ruling. Verifiers were fresh evidence-only TASK shards sharing one grading key",
       "> (`BRIEFS/VERIFIER_BRIEF.md`); selection by `_scripts/select_rechecks.py` → `_verify/SELECTION.csv` (R0 method).", "",
       "## §1 Structural validator (`_scripts/validate_ledger.py`, run from `projects/chirality-app-dev`)", "",
       "| Unit | Status | claims (ledger) | reverse (per area file) | errata | Claims SHA-256 | Reverse SHA-256 |", "|---|---|---|---|---|---|---|"]
for d in sorted(glob.glob(os.path.join(P, "DEL-*"))):
    u = os.path.basename(d); dl = u.split("_")[0]
    c = os.path.join(d, dl + "_claims.csv"); r = os.path.join(d, dl + "_reverse.csv"); e = os.path.join(d, dl + "_errata.csv")
    if not os.path.exists(c): continue
    areas = sorted({x["CapabilityID"].split("-")[1] for x in rows(r)}) if os.path.exists(r) else []
    rv = collections.Counter(val(["reverse", "--capabilities", os.path.join(RUN, "R2", "SURFACES", a + "_capabilities.csv"), r]) for a in areas)
    out.append(f"| {u} | {ACCEPT.get(u, '?')} | {val(['ledger', c])} | " + "; ".join(f"{k} ×{n}" for k, n in rv.items()) + f" ({len(areas)} areas) | " +
               (val(["errata", e]) if os.path.exists(e) else "none") + f" | `{sha(c)[:16]}…` | `{sha(r)[:16]}…` |")
out += ["", "Every file passes with 0 errors and 0 warnings; full SHA-256 values are in `STATE.jsonl` and `PACKAGE_SUMMARY.md` §1.", ""]
sel = rows(os.path.join(P, "_verify", "SELECTION.csv"))
out += ["## §2 Recheck results", "", f"Selection: {len(sel)} items in {len(set(s['Shard'] for s in sel))} shards (≤ 50 each). Classes: a = LOW / self-flag / AUTHORITY_CONFLICT / UNKNOWN / REMAINING_WORK; a30 = 30% of other non-ALIGNED; b = 15% of ALIGNED; c = 20% of CLAIMED_BY/PARTIAL; e = every errata row.", "",
        "### Per shard", "", "| Shard | Unit status | Items | CONFIRMED | REFUTED | CONTESTED | Distinct items checked | Items REFUTED (any field) | Share (any field) | Verdict-field REFUTED | Verdict share | CSV SHA-256 |", "|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---|"]
allv = []; cls = collections.Counter()
for f in sorted(glob.glob(os.path.join(P, "_verify", "V-*.csv"))):
    s = os.path.basename(f)[:-4]; vr = rows(f); allv += vr; c = collections.Counter(x["Verdict"] for x in vr)
    for x in vr: cls[(x["Class"], x["Verdict"])] += 1
    k = {x["ClaimKey"] + "|" + x["CapabilityID"] for x in vr}; rf = {x["ClaimKey"] + "|" + x["CapabilityID"] for x in vr if x["Verdict"] == "REFUTED"}
    vf = {x["ClaimKey"] + "|" + x["CapabilityID"] for x in vr if x["Verdict"] == "REFUTED" and ({y.strip() for y in x["Field"].split(";")} & {"Disposition", "Response", "ClaimKey"})}
    out.append(f"| {s} | {ACCEPT.get(unit_of(s), '?')} | {len(vr)} | {c['CONFIRMED']} | {c['REFUTED']} | {c['CONTESTED']} | {len(k)} | {len(rf)} | {100*len(rf)/max(len(k),1):.1f}% | {len(vf)} | {100*len(vf)/max(len(k),1):.1f}% | `{sha(f)[:16]}…` |")
t = collections.Counter(x["Verdict"] for x in allv)
VF = {"Disposition", "Response", "ClaimKey"}
out += ["", "### Per deliverable — rerun threshold computed separately on ledger rows and on reverse responses (RUN_BASIS Addendum 3)", "",
        "| Unit | Ledger items checked (distinct keys; classes a/a30/b/e) | Ledger verdict-REFUTED (Disposition) | Share | Reverse responses checked (class c) | Reverse verdict-REFUTED (Response/ClaimKey) | Share | Any-field REFUTED | CONTESTED | Rerun? |",
        "|---|---:|---:|---:|---:|---:|---:|---:|---:|---|"]
byu = collections.OrderedDict()
for f in sorted(glob.glob(os.path.join(P, "_verify", "V-*.csv"))):
    for x in rows(f): byu.setdefault(unit_of(os.path.basename(f)[:-4]), []).append(x)
for u, vr in byu.items():
    led = [x for x in vr if x["Class"] != "c"]; rev = [x for x in vr if x["Class"] == "c"]
    lk = {x["ClaimKey"] for x in led}; rk = {x["CapabilityID"] + "|" + x["ClaimKey"] for x in rev}
    lr = {x["ClaimKey"] for x in led if x["Verdict"] == "REFUTED" and {y.strip() for y in x["Field"].split(";")} & VF}
    rr = {x["CapabilityID"] + "|" + x["ClaimKey"] for x in rev if x["Verdict"] == "REFUTED" and {y.strip() for y in x["Field"].split(";")} & VF}
    anyr = sum(1 for x in vr if x["Verdict"] == "REFUTED"); con = sum(1 for x in vr if x["Verdict"] == "CONTESTED")
    pl = 100*len(lr)/max(len(lk),1); pr = 100*len(rr)/max(len(rk),1)
    out.append(f"| {u} | {len(lk)} | {len(lr)} | {pl:.1f}% | {len(rk)} | {len(rr)} | {pr:.1f}% | {anyr} | {con} | {'YES' if pl > 10 or pr > 10 else 'no'} |")
out += ["", "Rerun rule (RUN_BASIS Addendum 3): a ledger is rerun on a structural failure or when more than 10% of checked distinct items are REFUTED on a verdict field (Disposition, reverse Response/ClaimKey). Field-level refutations go to `CORRECTIONS.csv` (`_scripts/corrections.py`)."]
vv = [(os.path.basename(f)[:-4], x) for f in sorted(glob.glob(os.path.join(P, "_verify", "V-*.csv"))) for x in rows(f) if x["Verdict"] == "REFUTED" and ({y.strip() for y in x["Field"].split(";")} & {"Disposition", "Response", "ClaimKey"})]
out += ["", "**Verdict-field refutations, all attempts** (not in CORRECTIONS.csv; R3 decides):", ""] + [f"- {s} ({ACCEPT.get(unit_of(s), '?')}) `{x['ClaimKey']}` {x['Field']}: sealed `{x['RowValue']}` → verifier `{' '.join(x['CorrectReading'].split())[:160]}…`" for s, x in vv]
out += ["", f"All shards: {len(allv)} checks — CONFIRMED {t['CONFIRMED']}, REFUTED {t['REFUTED']}, CONTESTED {t['CONTESTED']}.", "",
        "### By class (all shards)", "", "| Class | CONFIRMED | REFUTED | CONTESTED |", "|---|---:|---:|---:|"]
for k in ["a", "a30", "b", "c", "e"]: out.append(f"| {k} | {cls[(k,'CONFIRMED')]} | {cls[(k,'REFUTED')]} | {cls[(k,'CONTESTED')]} |")
fr = collections.Counter(x["Field"] for x in allv if x["Verdict"] == "REFUTED"); fc = collections.Counter(x["Field"] for x in allv if x["Verdict"] == "CONTESTED")
out += ["", f"REFUTED by field: {dict(fr)}. CONTESTED by field: {dict(fc)}.", "",
        "## §3 Every REFUTED and CONTESTED item", "", "Fields are quoted from the shard CSVs (text cut at 400 characters; the full text is in `_verify/<shard>.csv`).", ""]
def cut(s, n=400): s = " ".join(s.split()); return s if len(s) <= n else s[:n] + " …"
for f in sorted(glob.glob(os.path.join(P, "_verify", "V-*.csv"))):
    s = os.path.basename(f)[:-4]; bad = [x for x in rows(f) if x["Verdict"] != "CONFIRMED"]
    out += [f"### {s} ({ACCEPT.get(unit_of(s), '?')}) — {len(bad)} items", "", "| Class | ClaimKey | Cap | Verdict | Field | Row value | Correct reading | Evidence | Rule |", "|---|---|---|---|---|---|---|---|---|"]
    for x in bad:
        out.append("| " + " | ".join(cut(v).replace("|", "\\|") for v in [x["Class"], x["ClaimKey"], x["CapabilityID"] or "-", x["Verdict"], x["Field"], x["RowValue"], x["CorrectReading"], x["Evidence"], x["ConventionIssue"]]) + " |")
    out.append("")
pp = os.path.join(P, "_scripts", "verification_patterns.md")
if os.path.exists(pp): out += [open(pp).read().rstrip(), ""]
out.append("*End of VERIFICATION.md. Verification evidence, not a ruling.*")
open(os.path.join(P, "VERIFICATION.md"), "w").write("\n".join(out) + "\n"); print(sha(os.path.join(P, "VERIFICATION.md")))
