"""I99 B3-W: summarize a probe log's I99_ lines into summary.md (per input and mode).
usage: summarize.py <probe log> <summary.md>"""
import json, re, sys

def probe_lines(path):
    for line in open(path, encoding="utf-8", errors="replace"):
        line = line.rstrip("\n")
        if line.startswith("test ") and " I99_" in line:
            line = line[line.index(" I99_") + 1:]
        if line.startswith("I99_"):
            yield line

def kv(line, key):
    m = re.search(r"(?:^| )" + re.escape(key) + r"=(\S+)", line)
    return m.group(1) if m else None

rec, order, files, census = {}, [], {}, {}
cur = None      # (label, mode)
phase = None    # "direct" or "driver"
for line in probe_lines(sys.argv[1]):
    tag = line.split(" ", 1)[0]
    if tag == "I99_FILE":
        _, label, rest = line.split(" ", 2)
        files[label] = (kv(line, "file_sha"), kv(line, "value_sha"))
        continue
    if tag == "I99_CENSUS":
        label = line.split(" ")[1]
        census[label] = (kv(line, "refusal") or "") + " " + (line.split("refusal=")[1].split(" required=")[0] if "refusal=" in line else "")
        census[label] = line.split("refusal=")[1].split(" required=")[0]
        continue
    if tag == "I99_BEGIN":
        _, label, mode, _ = line.split(" ", 3)
        cur = (label, mode); phase = "direct"
        rec[cur] = {"native": {"direct": [], "driver": []}, "seeds": {}, "events": {"direct": [], "driver": []}}
        order.append(cur)
        rec[cur]["input_sha"] = kv(line, "input_sha")
        continue
    if cur is None:
        continue
    r = rec[cur]
    if tag == "I99_ORDINARY":
        head, f = line.split(" facts=", 1)
        r["ordinary"] = json.loads(f)
        r["plain"] = (kv(head, "plain_sha"), kv(head, "plain_len"), kv(head, "results"))
    elif tag == "I99_ADMISSION":
        r["admission"] = line.split("refusal=")[1].split(" domain=")[0]
    elif tag == "I99_W1":
        r["direct"] = {k: kv(line, k) for k in ["notices", "bytes_eq_plain", "bytes_eq_with_notice_plain_case_none", "published_sha", "published_len"]}
        r["direct"]["cause"] = line.split("cause=")[1].split(" phase=")[0]
    elif tag == "I99_SUCCESSOR":
        r["successor"] = {"receipt": kv(line, "receipt_sha256"), "reader": line.split("rust_reader=")[1].split(" case_status=")[0], "status": kv(line, "case_status")}
    elif tag == "I99_DRIVER_ORDINARY":
        phase = "driver"
        r["driver_ordinary"] = (kv(line, "sha"), kv(line, "len"), kv(line, "exact_selected"))
    elif tag == "I99_SEEDS":
        site = kv(line, "site")
        r["seeds"][site] = json.loads(line.split(" seeds=", 1)[1])
    elif tag == "I99_WITNESS_CAPTURE_ERROR":
        r["capture_error"] = line.split(" ", 3)[3]
    elif tag == "I99_NATIVE_OUTCOME":
        r["native"][phase].append(line[len("I99_NATIVE_OUTCOME "):][:160])
    elif tag in ("I99_W1_START", "I99_PREPARATION_FAILURE", "I99_CANDIDATE_REFUSAL", "I99_PRECOMMIT_ERROR"):
        text = line
        if tag == "I99_CANDIDATE_REFUSAL":
            m = re.search(r"cause: (\w+\([^)]*\)|\w+ \{[^}]*\})", line)
            text = "I99_CANDIDATE_REFUSAL " + (m.group(1) if m else line[:200])
        r["events"][phase].append(text[4:][:220])
    elif tag == "I99_WITNESS":
        r["driver"] = line.split("ran=")[1].split(" furthest_phase=")[0]
        r["driver_phase"] = line.split("furthest_phase=")[1]
    elif tag == "I99_BUDGET":
        parts = re.findall(r"\[per_case_limit=(\d+) sha=(\w+) len=(\d+) eq_value_route=(\w+) contract=\"([^\"]+)\" exact_block=(.*?)\](?= \[|$)", line)
        r["budget"] = {"same": kv(line, "same_bytes_4M_8M"), "runs": []}
        for limit, sha, ln, eqv, contract, eb in parts:
            eb = json.loads(eb)
            sel = "none" if eb is None else ",".join(f"{c['ref']}:{c['selected_method']}(charged {c['work']['charged']}/limit {c['work']['limit']})" for c in eb["cases"])
            r["budget"]["runs"].append({"limit": limit, "sha": sha[:12], "len": ln, "eq_value_route": eqv, "contract": contract.rsplit("/", 1)[1], "selection": sel})

def short_contract(c):
    return c.rsplit("/", 1)[1] if c else c

out = ["# I99 B3-W probe summary (generated by summarize.py from one probe log)", ""]
out.append("Inputs (file sha256; Value sha256 = sha256 of serde_json::to_vec of the parsed file):")
out.append("")
for label, (fs, vs) in files.items():
    out.append(f"- `{label}`: file `{fs}`; Value `{vs}`; Direct census refusal `{census.get(label)}`")
out.append("")
out.append("| Input | Mode | Ordinary route (8M): contract; status; results; plain sha256 (len) | Verdicts | physics-source-1 (exact-block) | Rows per case | Direct entry | Private driver (4M): ordinary; seeds (legacy); W1 | 4M vs 8M (P-2) |")
out.append("|---|---|---|---|---|---|---|---|---|")
for key in order:
    label, mode = key
    r = rec[key]
    o = r.get("ordinary", {})
    contract = short_contract(o.get("contract"))
    verdicts = ", ".join(f"{v['ref']}: {v['solve_quality']}" for v in o.get("verdicts", []))
    eb = o.get("exact_block")
    if eb:
        sel = "; ".join(f"{c['ref']}: **{c['selected_method']}** ({c['outcome']}; charged {c['work']['charged']} / limit {c['work']['limit']})" for c in eb["cases"])
    else:
        sbd = [d for d in o.get("source_block_diagnostics", []) if d["code"] == "SOURCE_BLOCK_RECOVERY_UNAVAILABLE"]
        reasons = []
        for d in sbd:
            m = re.search(r'error: (\w+\("[^"]*"\))', d["message"]); w = re.search(r"charged: (\d+), rejected: \d+, limit: (\d+)", d["message"])
            reasons.append(f"{','.join(d['refs'])}: not selected ({m.group(1) if m else '?'}; charged {w.group(1) if w else '?'} / limit {w.group(2) if w else '?'})")
        sel = "none" + ("; " + "; ".join(reasons) if reasons else " (no attempt: no case needed it)")
    rows = ", ".join(f"{c}: {n}" for c, n in o.get("rows_per_case", {}).items())
    plain = r.get("plain", (None, None, None))
    d = r.get("direct", {})
    direct = f"admission refusal {r.get('admission')}; W1 {d.get('cause')}; notices {d.get('notices')}; bytes = ordinary {d.get('bytes_eq_plain')}; = with_notice {d.get('bytes_eq_with_notice_plain_case_none')}"
    if r.get("native", {}).get("direct"):
        direct += f"; native {'/'.join(r['native']['direct'])}"
    ev = [e for e in r["events"]["direct"] if not e.startswith("W1_START")]
    if ev:
        direct += "; " + "; ".join(ev)
    if "successor" in r:
        s = r["successor"]
        direct += f"; successor {d.get('published_sha', '')[:12]} ({d.get('published_len')} B), reader {s['reader'].split(' ')[0]}, case status {s['status']}"
    seeds = r["seeds"].get("witness_driver", [])
    seedtxt = ", ".join(f"{s['case']}: {s['initial'].get('outcome') or s['initial'].get('tag') or s['initial'].get('kind')} ({s['legacy']})" for s in seeds)
    dor = r.get("driver_ordinary", (None, None, None))
    drv = f"ordinary {dor[0][:12] if dor[0] else None} ({dor[1]} B), exact_selected {dor[2]}; seeds {seedtxt}; W1 **{r.get('driver')}** (phase {r.get('driver_phase')})"
    if r.get("capture_error"):
        drv += f"; capture error {r['capture_error']}"
    if r["native"]["driver"]:
        drv += f"; native {'/'.join(r['native']['driver'])}"
    ev = [e for e in r["events"]["driver"] if not e.startswith("W1_START")]
    if ev:
        drv += "; " + "; ".join(ev)
    b = r.get("budget", {})
    bud = f"same bytes {b.get('same')}; " + "; ".join(f"{x['limit']}: {x['contract']}, {x['selection']}, {x['sha']} ({x['len']} B), = ordinary route {x['eq_value_route']}" for x in b.get("runs", []))
    out.append(f"| `{label}` | {mode} | {contract}; {o.get('status', {}).get('mechanics')}; {plain[2]}; `{(plain[0] or '')[:12]}` ({plain[1]} B) | {verdicts} | {sel} | {rows} | {direct} | {drv} | {bud} |")
out.append("")
out.append("Rows by kind, per input, mode and case (the ordinary route):")
out.append("")
for key in order:
    o = rec[key].get("ordinary", {})
    for case, kinds in o.get("rows_by_kind", {}).items():
        out.append(f"- `{key[0]}` {key[1]} `{case}`: " + ", ".join(f"{k} {n}" for k, n in kinds.items()))
out.append("")
out.append("Integrity evidence (the ordinary route): reciprocal condition estimate and K-D5's line, per case:")
out.append("")
for key in order:
    o = rec[key].get("ordinary", {})
    for rc, d5 in zip(o.get("rcond", []), o.get("d5", [])):
        out.append(f"- `{key[0]}` {key[1]} {','.join(rc['refs'])}: rcond {rc['rcond']}; {d5['d5'] or 'no D-5 line'}")
open(sys.argv[2], "w").write("\n".join(out) + "\n")
print("rows:", len(order))
