//! T4-U3 (J-B): the frozen T4-I12 round-02 system cases end to end through
//! PP's public entries, in both solver modes: the admitted documents against
//! their independently derived values (criterion: relative 1e-9 with the
//! case's zero-scale floors), the controls' equalities, and each refusal
//! variant with exactly its intended blocking code.
//!
//! The references are `P/validation/references/t4_i12/u3_reference_cases.json`
//! (bytes unchanged; see its README). Nothing here is generated by the product.
use open_pipe_stress_product_physics::{
    run_linear_static_preview_value_with_mode, run_linear_static_preview_with_mode,
    PreviewSolverMode,
};
use serde_json::{json, Value};

const MODES: [PreviewSolverMode; 2] = [
    PreviewSolverMode::SparseInteractive,
    PreviewSolverMode::DenseScrutiny,
];
const REFERENCES: &str =
    include_str!("../../../validation/references/t4_i12/u3_reference_cases.json");

fn references() -> Value {
    serde_json::from_str(REFERENCES).unwrap()
}

fn case(id: &str) -> Value {
    references()["cases"][id].clone()
}

/// Both entries (captured value and typed DTO) in both modes; the entries
/// agree in each mode.
fn run(document: &Value) -> Vec<Value> {
    let mut outputs = Vec::new();
    for mode in MODES {
        let captured = serde_json::to_value(
            run_linear_static_preview_value_with_mode(document.clone(), mode).unwrap(),
        )
        .unwrap();
        let typed = serde_json::to_value(run_linear_static_preview_with_mode(
            serde_json::from_value(document.clone()).unwrap(),
            mode,
        ))
        .unwrap();
        assert_eq!(captured["status"], typed["status"]);
        assert_eq!(captured["results"], typed["results"]);
        outputs.push(captured);
    }
    outputs
}

fn number(text: &Value) -> f64 {
    text.as_str().unwrap().parse::<f64>().unwrap()
}

fn rows<'e>(envelope: &'e Value, case: &str) -> Vec<&'e Value> {
    envelope["results"]
        .as_array()
        .unwrap()
        .iter()
        .filter(|r| r["basis_ref"]["ref_id"] == case)
        .collect()
}

fn row(envelope: &Value, case: &str, kind: &str, entity: &str, component: &str) -> f64 {
    let found = rows(envelope, case)
        .into_iter()
        .filter(|r| {
            r["kind"] == kind && r["entity_ref"] == entity && r["metadata"]["component"] == component
        })
        .collect::<Vec<_>>();
    assert_eq!(found.len(), 1, "{case} {kind} {entity} {component}");
    let value = found[0]["value"].as_f64().unwrap();
    match found[0]["unit"].as_str().unwrap() {
        "mm" => value / 1000.0,
        _ => value,
    }
}

fn connector_row(envelope: &Value, case: &str, kind: &str, location: &str, component: &str) -> f64 {
    let found = rows(envelope, case)
        .into_iter()
        .filter(|r| {
            r["kind"] == kind
                && r["entity_ref"] == "component:C-150"
                && r["metadata"]["location"] == location
                && r["metadata"]["component"] == component
        })
        .collect::<Vec<_>>();
    assert_eq!(found.len(), 1, "{case} {kind} {location} {component}");
    found[0]["value"].as_f64().unwrap()
}

fn close(observed: f64, expected: f64, floor: f64, what: &str) {
    assert!(
        (observed - expected).abs() <= 1e-9 * expected.abs().max(floor),
        "{what}: {observed} vs {expected} (floor {floor})"
    );
}

/// Every displacement, reaction and connector value of `expected` (one case
/// map of a system reference) against `envelope`.
fn assert_case_values(envelope: &Value, expected: &Value, label: &str) {
    assert_eq!(envelope["status"]["mechanics"], "MECHANICS_SOLVED", "{label}: {}", envelope["diagnostics"]);
    for (case, values) in expected.as_object().unwrap() {
        let floors = &values["zero_scale_floors"];
        let floor = |name: &str| number(&floors[name]);
        for (node, d) in values["displacements"].as_object().unwrap() {
            for (axis, component) in ["x", "y", "z"].iter().enumerate() {
                close(
                    row(envelope, case, &format!("global_nodal_displacement_{component}"), node, &format!("nodal_displacement_{component}")),
                    number(&d["u_m"][axis]),
                    floor("translation_m"),
                    &format!("{label} {case} {node} u{component}"),
                );
                close(
                    row(envelope, case, &format!("global_nodal_rotation_{component}"), node, &format!("nodal_rotation_{component}")),
                    number(&d["theta_rad"][axis]),
                    floor("rotation_rad"),
                    &format!("{label} {case} {node} theta{component}"),
                );
            }
        }
        for (support, r) in values["reactions_support_on_pipe_global_Fx_Fy_Fz_Mx_My_Mz"].as_object().unwrap() {
            for (k, component) in ["Fx", "Fy", "Fz", "Mx", "My", "Mz"].iter().enumerate() {
                close(
                    row(envelope, case, "support_reaction_component_v2", support, component),
                    number(&r[k]),
                    if k < 3 { floor("force_N") } else { floor("moment_N_m") },
                    &format!("{label} {case} {support} {component}"),
                );
            }
        }
        let c = &values["connector"];
        for (k, axis) in ["x", "y", "z"].iter().enumerate() {
            close(connector_row(envelope, case, "connector_generalized_translation_v1", "connector_local", &format!("qt_{axis}")),
                number(&c["q_local"][k]), floor("q_translation_m"), &format!("{label} {case} qt_{axis}"));
            close(connector_row(envelope, case, "connector_generalized_rotation_v1", "connector_local", &format!("qr_{axis}")),
                number(&c["q_local"][k + 3]), floor("q_rotation_rad"), &format!("{label} {case} qr_{axis}"));
            close(connector_row(envelope, case, "connector_generalized_force_v1", "connector_local", &format!("gt_{axis}")),
                number(&c["g_local"][k]), floor("g_force_N"), &format!("{label} {case} gt_{axis}"));
            close(connector_row(envelope, case, "connector_generalized_moment_v1", "connector_local", &format!("gr_{axis}")),
                number(&c["g_local"][k + 3]), floor("g_moment_N_m"), &format!("{label} {case} gr_{axis}"));
        }
        let ends = &c["end_actions_node_on_element"];
        for (location, force, moment) in [("end_i", "Fi_at_N-130", "Mi_at_N-130"), ("end_j", "Fj_at_N-140", "Mj_at_N-140")] {
            for (k, axis) in ["x", "y", "z"].iter().enumerate() {
                close(connector_row(envelope, case, "connector_endpoint_force_v1", location, &format!("F{axis}")),
                    number(&ends[force][k]), floor("force_N"), &format!("{label} {case} {location} F{axis}"));
                close(connector_row(envelope, case, "connector_endpoint_moment_v1", location, &format!("M{axis}")),
                    number(&ends[moment][k]), floor("moment_N_m"), &format!("{label} {case} {location} M{axis}"));
            }
        }
        // S20/S21: the replaced span has no member row and no per-pipe evidence.
        assert!(!rows(envelope, case).iter().any(|r| r["entity_ref"] == "pipe:P-130"), "{label} {case}");
    }
    // The connector's own record names its replaced span; no per-pipe list does.
    let mut evidence = envelope["contract_evidence"].clone();
    let records = evidence.as_object_mut().unwrap().remove("connector").unwrap();
    assert_eq!(records[0]["replaced_pipe_id"], "pipe:P-130", "{label}");
    assert!(!evidence.to_string().contains("\"pipe:P-130\""), "{label}: P-130 in published evidence");
}

/// The published displacement, reaction and connector rows of an envelope,
/// for bitwise comparison between runs.
fn mechanics_rows(envelope: &Value) -> Vec<Value> {
    envelope["results"]
        .as_array()
        .unwrap()
        .iter()
        .filter(|r| {
            let kind = r["kind"].as_str().unwrap();
            kind.starts_with("global_nodal_") || kind == "support_reaction_component_v2" || kind.starts_with("connector_")
        })
        .map(|r| json!([r["id"], r["value"]]))
        .collect()
}

#[test]
fn demo_connector_001_and_its_0_4_0_twin_match_the_frozen_values_in_both_modes() {
    let c001 = case("U3-SYS-DEMO-CONNECTOR-001");
    let c002 = case("U3-SYS-DEMO-CONNECTOR-002-LR1");
    let first = run(&c001["inputs"]["document_v3_0.3.0"]);
    let second = run(&c002["inputs"]["document_v3_0.4.0"]);
    for (index, (a, b)) in first.iter().zip(&second).enumerate() {
        assert_case_values(a, &c001["expected"], &format!("001 mode {index}"));
        assert_case_values(b, &c002["expected"], &format!("002 mode {index}"));
        // The same operands reach the same assembly.
        assert_eq!(mechanics_rows(a), mechanics_rows(b), "mode {index}");
        // T4-U3 states the connector's law on v3.
        assert!(a["formulation_basis"]["limitations"].to_string().contains("Objective connectors"));
    }
}

/// The 770, 275 and 440 N·m discriminators: the deleted element's raw
/// endpoint-difference measure would leave those moment imbalances; the
/// published reactions differ from that solve on every discriminating
/// component by far more than the criterion (and match the reference above).
#[test]
fn raw_difference_discriminators_are_not_reproduced() {
    let c001 = case("U3-SYS-DEMO-CONNECTOR-001");
    let outputs = run(&c001["inputs"]["document_v3_0.3.0"]);
    let mut imbalances = Vec::new();
    for (case_id, d) in c001["wrong_result_discriminators"].as_object().unwrap() {
        let raw = &d["raw_difference_element_solve"];
        let imbalance = raw["global_moment_imbalance_about_origin_N_m"]
            .as_array()
            .unwrap()
            .iter()
            .map(number)
            .fold(0.0_f64, |m, v| m.max(v.abs()));
        imbalances.push(imbalance);
        let floors = &c001["expected"][case_id]["zero_scale_floors"];
        for component in raw["discriminating_components"].as_array().unwrap() {
            let (support, axis) = component.as_str().unwrap().split_once('.').unwrap();
            let k = ["Fx", "Fy", "Fz", "Mx", "My", "Mz"].iter().position(|a| *a == axis).unwrap();
            let wrong = number(&raw["reactions"][support][k]);
            let floor = number(&floors[if k < 3 { "force_N" } else { "moment_N_m" }]);
            for envelope in &outputs {
                let observed = row(envelope, case_id, "support_reaction_component_v2", support, axis);
                assert!((observed - wrong).abs() > 1e-6 * floor, "{case_id} {component}");
            }
        }
    }
    imbalances.sort_by(f64::total_cmp);
    assert_eq!(imbalances, vec![275.0, 440.0, 770.0]);
}

#[test]
fn replaced_span_controls_are_admitted_with_unchanged_rows() {
    let c001 = case("U3-SYS-DEMO-CONNECTOR-001");
    let c002 = case("U3-SYS-DEMO-CONNECTOR-002-LR1");
    let base3 = run(&c001["inputs"]["document_v3_0.3.0"]);
    let base4 = run(&c002["inputs"]["document_v3_0.4.0"]);
    // P-130's material changed: no assembly or recovery path reads it.
    let material = case("U3-SYS-REPLACED-SPAN-MATERIAL-CONTROL");
    for (document, base) in [("document_v3_0.3.0", &base3), ("document_v3_0.4.0", &base4)] {
        for (index, envelope) in run(&material["inputs"][document]).iter().enumerate() {
            assert_case_values(envelope, &c001["expected"], &format!("material control {document}"));
            assert_eq!(mechanics_rows(envelope), mechanics_rows(&base[index]), "{document} mode {index}");
        }
    }
    // A weight stored on P-130 but applied by no case has no effect.
    let stored = case("U3-SYS-LR1-REPLACED-SPAN-STORED-UNAPPLIED-CONTROL");
    for (index, envelope) in run(&stored["inputs"]["document_v3_0.4.0"]).iter().enumerate() {
        assert_case_values(envelope, &c002["expected"], "stored unapplied");
        assert_eq!(mechanics_rows(envelope), mechanics_rows(&base4[index]), "mode {index}");
    }
    // An explicit zero strain on P-130 resolves to exactly zero: admitted.
    let strain = case("U3-SYS-LR1-REPLACED-SPAN-EIGENSTRAIN-REFUSAL");
    let boundary = &strain["boundary_zero_strain"];
    for (index, envelope) in run(&boundary["document_v3_0.4.0"]).iter().enumerate() {
        assert_case_values(envelope, &boundary["expected_values"], "zero strain");
        assert_eq!(mechanics_rows(envelope), mechanics_rows(&base4[index]), "mode {index}");
    }
}

fn blocking(envelope: &Value) -> Vec<&Value> {
    envelope["diagnostics"]
        .as_array()
        .unwrap()
        .iter()
        .filter(|d| d["severity"] == "blocking")
        .collect()
}

fn assert_refused(envelope: &Value, code: &str, refs: &[&str], label: &str) {
    assert_eq!(envelope["status"]["mechanics"], "MODEL_INCOMPLETE", "{label}");
    assert_eq!(envelope["results"], json!([]), "{label}");
    let found = blocking(envelope);
    assert!(!found.is_empty(), "{label}");
    for d in &found {
        assert_eq!(d["code"], code, "{label}: {found:#?}");
    }
    for r in refs {
        assert!(found.iter().any(|d| d["affected_refs"].as_array().unwrap().contains(&json!(r))), "{label}: {r} in {found:#?}");
    }
}

/// RFC 6902 `add`, `replace` and `remove` on JSON pointers (the variants'
/// patch form).
fn patch(document: &Value, operations: &Value) -> Value {
    let mut document = document.clone();
    for op in operations.as_array().unwrap() {
        let path = op["path"].as_str().unwrap();
        let (parent, key) = path.rsplit_once('/').unwrap();
        let target = document.pointer_mut(parent).unwrap();
        match (op["op"].as_str().unwrap(), target) {
            ("add", Value::Array(items)) if key == "-" => items.push(op["value"].clone()),
            ("add", Value::Array(items)) => items.insert(key.parse().unwrap(), op["value"].clone()),
            ("add" | "replace", Value::Object(map)) => {
                map.insert(key.replace("~1", "/").replace("~0", "~"), op["value"].clone());
            }
            ("replace", Value::Array(items)) => items[key.parse::<usize>().unwrap()] = op["value"].clone(),
            ("remove", Value::Array(items)) => {
                items.remove(key.parse::<usize>().unwrap());
            }
            ("remove", Value::Object(map)) => {
                map.remove(&key.replace("~1", "/").replace("~0", "~"));
            }
            (other, _) => panic!("unsupported patch op {other}"),
        }
    }
    document
}

#[test]
fn every_refusal_variant_fails_for_exactly_its_intended_reason() {
    let c001 = case("U3-SYS-DEMO-CONNECTOR-001");
    let document = &c001["inputs"]["document_v3_0.3.0"];
    let variants = &c001["refusal_variants"];
    let mut checked = 0;
    for (name, variant) in variants.as_object().unwrap() {
        let expected = &variant["expected_round_02"];
        let code = expected["blocking_codes_exactly"][0].as_str().unwrap();
        let refs: Vec<&str> = expected["affected_refs_include"]
            .as_array()
            .map(|r| r.iter().map(|v| v.as_str().unwrap()).collect())
            .unwrap_or_else(|| vec!["component:C-150"]);
        let mut documents = Vec::new();
        if let Some(single) = variant.get("document_patch_round_02") {
            documents.push((name.clone(), patch(document, &single["operations"])));
        }
        if let Some(many) = variant.get("document_patches_round_02").and_then(Value::as_object) {
            for (sub, p) in many {
                if p.get("operations").is_some() {
                    documents.push((format!("{name}/{sub}"), patch(document, &p["operations"])));
                }
            }
        }
        assert!(!documents.is_empty(), "{name}");
        for (label, document) in documents {
            for envelope in run(&document) {
                assert_refused(&envelope, code, &refs, &label);
                // An annotation is never the legacy refusal (RV9).
                assert!(!envelope["diagnostics"].to_string().contains("LEGACY_FINITE_CONNECTOR_REAUTHOR_REQUIRED"), "{label}");
            }
            checked += 1;
        }
    }
    assert_eq!(checked, 7);
    // 0.4.0 variants a (thermal), b (fit strain) and c (an applied weight).
    let strain = case("U3-SYS-LR1-REPLACED-SPAN-EIGENSTRAIN-REFUSAL");
    for variant in ["a_thermal_on_replaced_span", "b_fit_strain_on_replaced_span", "c_weight_on_replaced_span"] {
        let v = &strain["expected"][variant];
        let refs: Vec<&str> = v["expected_round_02"]["affected_refs_include"]
            .as_array()
            .unwrap()
            .iter()
            .map(|r| r.as_str().unwrap())
            .collect();
        for envelope in run(&v["document_v3_0.4.0"]) {
            assert_refused(&envelope, "JOINT_REPLACED_SPAN_LOAD_UNOWNED", &refs, variant);
            assert_eq!(
                blocking(&envelope).len(),
                v["expected_round_02"]["refused_cases"].as_array().unwrap().len(),
                "{variant}: one refusal per refused case"
            );
        }
    }
}
