#!/usr/bin/env python3
"""SCA-APP-011 checkpoint-group-2 exact amendment: check, render and (group 3 only) apply.

Run from the repository root.

  build_amendment_preview.py            check every edit against the current tree, dry-run
                                        the postimages, and write Amendment_Preview.md and
                                        Evidence/Group2/PREIMAGE_POSTIMAGE.csv
  build_amendment_preview.py --check    check only: every preimage still matches the hashes
                                        recorded in PREIMAGE_POSTIMAGE.csv (drift detection
                                        before application); writes nothing
  build_amendment_preview.py --apply --date YYYY-MM-DD --group3-decision PATH
                                        group 3 only: apply the edits, filling
                                        {APPLICATION_DATE}; refuses unless PATH is the
                                        SCA-APP-011 group-3 DECISION.md whose first line is
                                        "# SCA-APP-011 checkpoint group 3 — accepted ..."

Each edit replaces one exact substring that must occur exactly once in the file,
as it stands after the earlier edits to that file.
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import importlib.util
import os
import re
import sys
from collections import OrderedDict

HERE = os.path.dirname(os.path.abspath(__file__))
SNAP = os.path.dirname(os.path.dirname(HERE))
SLOT = "{APPLICATION_DATE}"
CSV_PATH = os.path.join(HERE, "PREIMAGE_POSTIMAGE.csv")
PREVIEW = os.path.join(SNAP, "Amendment_Preview.md")


def load_edits():
    spec = importlib.util.spec_from_file_location("amendment_edits", os.path.join(HERE, "amendment_edits.py"))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod.EDITS, mod.CARRIED_BY


def sha(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def plan(edits, date: str | None):
    by_file: "OrderedDict[str, list]" = OrderedDict()
    for e in edits:
        by_file.setdefault(e["file"], []).append(e)
    results = OrderedDict()
    errors = []
    for path, items in by_file.items():
        if not os.path.isfile(path):
            errors.append(f"{path}: missing")
            continue
        original = open(path, encoding="utf-8").read()
        text = original
        rendered = []
        for e in items:
            count = text.count(e["old"])
            if count != 1:
                errors.append(f"{e['id']} {path}: old text occurs {count} times (expected 1)")
                continue
            line = original.count("\n", 0, original.find(e["old"])) + 1 if e["old"] in original else None
            new = e["new"].replace(SLOT, date) if date else e["new"]
            text = text.replace(e["old"], new, 1)
            rendered.append((e, line))
        results[path] = dict(original=original, post=text, edits=rendered,
                             conditional=any(e.get("conditional") for e in items))
    return results, errors


def fence(text: str) -> str:
    body = text.rstrip("\n")
    return "```text\n" + (body if body else "(nothing: the text is removed)") + "\n```\n"


def render(results, carried) -> str:
    total = sum(len(r["edits"]) for r in results.values())
    out = [
        "# SCA-APP-011 — Amendment Preview (checkpoint group 2)\n\n",
        "Generated by `Evidence/Group2/build_amendment_preview.py` from `Evidence/Group2/amendment_edits.py` "
        "against the tree at the time of generation. Each edit replaces one exact passage (before → after). "
        f"{total} edits in {len(results)} files. Line numbers are the edit's first line in the current file. "
        "Nothing here is applied before checkpoint group 3 is accepted.\n\n",
        "## Acceptance-conditional edits\n\n",
        "Only one slot depends on the acceptance act: `{APPLICATION_DATE}` in edit E47 (decomposition Coverage and "
        "Telemetry `Date`). It is filled with the date in the heading of the SCA-APP-011 group-3 `DECISION.md`, "
        "formatted `YYYY-MM-DD`. All other bytes are fixed, and their expected postimage hashes are recorded in "
        "`Evidence/Group2/PREIMAGE_POSTIMAGE.csv`. The pointer move (`_LATEST.md` to the accepted SCA-APP-011 "
        "snapshot) and the group-3 decision snapshot are listed in `Propagation_Plan.md` §6.\n\n",
    ]
    if carried:
        out.append("## Rows carried by another row's edit\n\n")
        for seq, ids in carried.items():
            out.append(f"- Register row {seq}: carried by {', '.join(ids)}.\n")
        out.append("\n")
    for path, r in results.items():
        out.append(f"## `{path}`\n\n")
        for e, line in r["edits"]:
            cond = " — acceptance-conditional" if e.get("conditional") else ""
            where = f"L{line}" if line else "after an earlier edit"
            out.append(f"### {e['id']} — register row {e['seq']} — {where}{cond}\n\n")
            out.append("Before:\n\n" + fence(e["old"]) + "\nAfter:\n\n" + fence(e["new"]) + "\n")
    return "".join(out).rstrip("\n") + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--apply", action="store_true")
    ap.add_argument("--date")
    ap.add_argument("--group3-decision")
    args = ap.parse_args()
    edits, carried = load_edits()
    ids = [e["id"] for e in edits]
    if len(ids) != len(set(ids)):
        print("duplicate edit ids", file=sys.stderr)
        return 2

    if args.check:
        recorded = {r["File"]: r for r in csv.DictReader(open(CSV_PATH, newline=""))}
        bad = 0
        for path, rec in recorded.items():
            cur = sha(open(path, encoding="utf-8").read()) if os.path.isfile(path) else "MISSING"
            ok = cur == rec["PreimageSHA256"]
            bad += not ok
            print(("OK   " if ok else "DRIFT"), path)
        results, errors = plan(edits, None)
        for err in errors:
            print("ERROR", err)
        return 1 if bad or errors else 0

    if args.apply:
        if not (args.date and re.fullmatch(r"\d{4}-\d{2}-\d{2}", args.date)):
            print("--apply needs --date YYYY-MM-DD", file=sys.stderr)
            return 2
        dec = args.group3_decision
        first = ""
        if dec and os.path.isfile(dec):
            first = next((ln.strip() for ln in open(dec, encoding="utf-8") if ln.strip()), "")
        if not re.match(r"^# SCA-APP-011 checkpoint group 3 — accepted[ .,;]", first + " "):
            print("refused: no accepted SCA-APP-011 group-3 DECISION.md", file=sys.stderr)
            return 3
        results, errors = plan(edits, args.date)
        if errors:
            print("\n".join(errors), file=sys.stderr)
            return 1
        for path, r in results.items():
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(r["post"])
            print("applied", path, sha(r["post"]))
        return 0

    results, errors = plan(edits, None)
    if errors:
        print("\n".join(errors), file=sys.stderr)
        return 1
    with open(PREVIEW, "w", encoding="utf-8") as fh:
        fh.write(render(results, carried))
    with open(CSV_PATH, "w", newline="", encoding="utf-8") as fh:
        w = csv.writer(fh, lineterminator="\n")
        w.writerow(["File", "Edits", "PreimageSHA256", "PostimageSHA256", "PostimageDeterminable"])
        for path, r in results.items():
            w.writerow([path, ";".join(e["id"] for e, _ in r["edits"]), sha(r["original"]),
                        "" if r["conditional"] else sha(r["post"]),
                        "NO (slot {APPLICATION_DATE})" if r["conditional"] else "YES"])
    print(f"{sum(len(r['edits']) for r in results.values())} edits, {len(results)} files: OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
