//! Control for the load/reference-state inbound-reference refusals added to the
//! delete operations (T1 WP3 follow-up): on models that carry no
//! `reference_configurations`, `expansion_laws` or `analysis_state`, every
//! pipe, support, material and primitive-load delete outcome is byte-identical
//! to the outcome of the code before the change.
//!
//! The golden file `fixtures/model_operations/load_reference_delete_control.json`
//! holds the sha256 of each serialized `OperationOutcome` (validate and apply)
//! as produced by the base revision's applier. It was generated by running this
//! test with `LOAD_REFERENCE_DELETE_CONTROL_BLESS=1` on a scratch copy of the
//! base revision (see the WP3 return, addendum 1). Without the variable the test
//! compares. All models are invented fixtures.
//!
//! Addendum 2 adds `fixtures/model_operations/load_reference_authoring_control.json`
//! the same way: pressure-profile and temperature-point authoring outcomes on the
//! 0.2.0 and 0.3.0 fixture models, blessed from the base revision (`203396e4d`).
use open_pipe_stress_operation_applier::{
    apply_operation, canonical_json, sha256_hex, validate_operation,
};
use serde_json::{json, Map, Value};

const GOLDEN: &str = "../../../fixtures/model_operations/load_reference_delete_control.json";

fn fixture(text: &str) -> Value {
    let value: Value = serde_json::from_str(text).unwrap();
    value.get("model").cloned().unwrap_or(value)
}
/// The 0.4.0 witnesses with every load/reference-state record removed.
fn stripped(text: &str) -> Value {
    let mut model = fixture(text);
    model
        .as_object_mut()
        .unwrap()
        .remove("reference_configurations");
    for material in model["materials"].as_array_mut().unwrap() {
        material.as_object_mut().unwrap().remove("expansion_laws");
    }
    for case in model["load_cases"].as_array_mut().unwrap() {
        case.as_object_mut().unwrap().remove("analysis_state");
    }
    model
}
fn models() -> Vec<(&'static str, Value)> {
    vec![
        (
            "precision_connected_ui_model_0_2_0",
            fixture(include_str!(
                "../../../../fixtures/model_operations/precision_connected_ui_model.json"
            )),
        ),
        (
            "exact_pressure_authoring_model_0_3_0",
            fixture(include_str!(
                "../../../../fixtures/model_operations/exact_pressure_authoring_model.json"
            )),
        ),
        (
            "physics_thermal_ui_model_0_3_0",
            fixture(include_str!(
                "../../../../fixtures/model_operations/physics_thermal_ui_model.json"
            )),
        ),
        (
            "connected_0_4_0_without_load_state_records",
            stripped(include_str!(
                "../../../../fixtures/product_preview/load_reference/connected.request.json"
            )),
        ),
        (
            "eigen_motion_0_4_0_without_load_state_records",
            stripped(include_str!(
                "../../../../fixtures/product_preview/load_reference_source/eigen_motion.request.json"
            )),
        ),
    ]
}
fn hash(model: &Value) -> Value {
    json!({"algorithm":"sha256","canonicalization":"rfc8785_jcs","payload_scope":"model_payload",
        "value":format!("sha256:{}",sha256_hex(&canonical_json(model)))})
}
#[allow(clippy::too_many_arguments)]
fn intent(
    object: &str,
    id: &str,
    kind: &str,
    path: &str,
    before: &str,
    after: &str,
    unit: &str,
    dimension: &str,
) -> Value {
    json!({"operation_id":format!("op:control:{kind}:{id}:{path}"),"operation_kind":"delete","operation_status":"proposed","author_type":"user",
      "target":{"object_type":object,"ref":id},
      "change":{"change_id":format!("change:control:{kind}:{id}:{path}"),"change_kind":kind,"field_label":path,"field_path":path,
        "before":before,"after":after,"unit":unit,"dimension":dimension,"source_note":"Invented delete control"},
      "validation":{"schema_validation":"not_run","constraint_validation":"not_run","unit_validation":"not_run","diff_preview_status":"not_generated","application_status":"not_applied"},
      "rationale":"Invented delete control",
      "audit_boundary":{"mutation_route":"structured_operations_only","direct_model_mutation_allowed":false,"requires_user_acceptance":true,"mutates_accepted_model_state":false},
      "professional_boundary":{"human_review_required":true,"software_makes_compliance_claim":false,"software_makes_certification_claim":false,"software_makes_sealing_claim":false,"software_makes_approval_claim":false,"software_makes_authentication_claim":false}})
}
fn text(value: &Value, key: &str) -> String {
    value
        .get(key)
        .and_then(Value::as_str)
        .unwrap_or("")
        .trim()
        .to_string()
}
fn number(value: f64) -> String {
    serde_json::to_string(&json!(value))
        .unwrap()
        .trim_end_matches(".0")
        .to_string()
}
/// Every delete intent the four affected operations accept in shape, with
/// before-values built from the current records.
fn intents(model: &Value) -> Vec<(String, Value)> {
    let mut out = Vec::new();
    for pipe in model["pipe_segments"].as_array().into_iter().flatten() {
        let id = text(pipe, "id");
        let before = format!(
            "{}; {}->{}; material={}",
            text(pipe, "label"),
            text(pipe, "from"),
            text(pipe, "to"),
            text(pipe, "material")
        );
        out.push((
            format!("delete_pipe_run:{id}"),
            intent(
                "Element",
                &id,
                "delete_pipe_run",
                "pipe_segments",
                &before,
                "not_present",
                "none",
                "dimensionless",
            ),
        ));
    }
    for support in model["supports"].as_array().into_iter().flatten() {
        let id = text(support, "id");
        out.push((
            format!("delete_support:{id}"),
            intent(
                "Support",
                &id,
                "delete_support",
                "supports",
                &text(support, "label"),
                "not_present",
                "none",
                "dimensionless",
            ),
        ));
    }
    for material in model["materials"].as_array().into_iter().flatten() {
        let id = text(material, "id");
        out.push((
            format!("delete_material:{id}"),
            intent(
                "Material",
                &id,
                "delete_material",
                "materials",
                &canonical_json(material),
                "deleted",
                "none",
                "dimensionless",
            ),
        ));
    }
    for case in model["load_cases"].as_array().into_iter().flatten() {
        let case_id = text(case, "id");
        for (index, load) in case["primitive_loads"]
            .as_array()
            .into_iter()
            .flatten()
            .enumerate()
        {
            let target = load["target"]
                .as_object()
                .map(|t| {
                    let kind = t.get("type").and_then(Value::as_str).unwrap_or("target");
                    ["pipe", "node", "support"]
                        .iter()
                        .find_map(|k| t.get(*k).and_then(Value::as_str))
                        .map(|v| format!("{kind}:{v}"))
                        .unwrap_or(format!("{kind}:TBD"))
                })
                .unwrap_or("target:TBD".into());
            let unit = load["magnitude"]["unit"].as_str().unwrap_or("").to_string();
            let before = format!(
                "{}; {}; {target}; {}; {} {unit}; {}",
                text(load, "id"),
                load["category"].as_str().unwrap_or("TBD"),
                load["direction"].as_str().unwrap_or("TBD"),
                number(load["magnitude"]["value"].as_f64().unwrap_or(f64::NAN)),
                text(load, "dimension")
            );
            let path = format!("primitive_loads.{index}");
            out.push((
                format!("delete_primitive_load:{case_id}:{index}"),
                intent(
                    "Load",
                    &case_id,
                    "delete_primitive_load",
                    &path,
                    &before,
                    "not_present",
                    &unit,
                    &text(load, "dimension"),
                ),
            ));
        }
    }
    out
}
fn outcomes() -> Value {
    let mut records = Map::new();
    for (name, model) in models() {
        let claim = hash(&model);
        for (key, op) in intents(&model) {
            for (mode, outcome) in [
                ("validate", validate_operation(&model, &op, Some(&claim))),
                ("apply", apply_operation(&model, &op, Some(&claim))),
            ] {
                let codes: Vec<&str> = outcome
                    .diagnostics
                    .iter()
                    .map(|d| d.code.as_str())
                    .collect();
                records.insert(
                    format!("{name}|{key}|{mode}"),
                    json!({
                        "outcome_sha256": sha256_hex(&serde_json::to_string(&outcome).unwrap()),
                        "applied": outcome.applied_model.is_some(),
                        "codes": codes,
                    }),
                );
            }
        }
    }
    Value::Object(records)
}

#[test]
fn delete_outcomes_without_load_state_records_are_byte_identical_to_the_base_revision() {
    let actual = outcomes();
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join(GOLDEN);
    if std::env::var_os("LOAD_REFERENCE_DELETE_CONTROL_BLESS").is_some() {
        std::fs::write(&path, serde_json::to_string_pretty(&actual).unwrap() + "\n").unwrap();
        return;
    }
    let golden: Value = serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap();
    assert_eq!(golden, actual);
    // The control is not vacuous: it covers all four operations, accepted and
    // refused outcomes, including existing reference refusals.
    let rows = golden.as_object().unwrap();
    for kind in [
        "delete_pipe_run",
        "delete_support",
        "delete_material",
        "delete_primitive_load",
    ] {
        assert!(rows.keys().any(|k| k.contains(kind)), "{kind}");
    }
    assert!(rows.values().any(|r| r["applied"] == true));
    assert!(rows.values().any(|r| r["applied"] == false));
}

// ---------------------------------------------------------------------------
// Addendum 2 (review B F1, F2, F9): pressure-profile and temperature-point
// authoring on models before 0.4.0 is byte-identical to the base revision.
// ---------------------------------------------------------------------------

const AUTHORING_GOLDEN: &str =
    "../../../fixtures/model_operations/load_reference_authoring_control.json";

fn set_intent(object: &str, id: &str, path: &str, before: &str, after: &str) -> Value {
    let mut op = intent(
        object,
        id,
        "set_field",
        path,
        before,
        after,
        "none",
        "dimensionless",
    );
    op["operation_kind"] = json!("modify");
    op
}
/// Invented temperature points: one E/nu point with a coefficient, one legacy
/// E/G point.
fn invented_points() -> Value {
    json!([
        {"id":"point:invented-cold","temperature":{"value":20,"unit":"degC"},"elastic_modulus":{"value":200,"unit":"GPa"},
         "poisson_ratio":{"value":0.3,"unit":"1"},"thermal_expansion_coefficient":{"value":1.2e-5,"unit":"1/K"},"provenance":"invented control point"},
        {"id":"point:invented-hot","temperature":{"value":150,"unit":"degC"},"elastic_modulus":{"value":150,"unit":"GPa"},
         "shear_modulus":{"value":60,"unit":"GPa"},"provenance":"invented control point"}
    ])
}
fn authoring_intents(model: &Value) -> Vec<(String, Value, Value)> {
    let mut out = Vec::new();
    let project = text(&model["project"], "id");
    let profile: Map<String, Value> = ["schema_version", "pressure_contract"]
        .iter()
        .filter_map(|k| model.get(*k).map(|v| ((*k).to_string(), v.clone())))
        .collect();
    let before = canonical_json(&Value::Object(profile.clone()));
    let exact = json!({"version":"2.0.0","mode":"exact_straight_pressure_v2"});
    for (label, after) in [
        (
            "exact_0_3_0",
            json!({"schema_version":"0.3.0","pressure_contract":exact}).to_string(),
        ),
        (
            "to_0_4_0",
            json!({"schema_version":"0.4.0","pressure_contract":exact}).to_string(),
        ),
        ("unchanged", Value::Object(profile.clone()).to_string()),
    ] {
        out.push((
            format!("pressure_profile:{label}"),
            model.clone(),
            set_intent("Model", &project, "pressure_profile", &before, &after),
        ));
    }
    for (index, material) in model["materials"]
        .as_array()
        .into_iter()
        .flatten()
        .enumerate()
    {
        let id = text(material, "id");
        let points = invented_points();
        let current = material
            .get("temperature_points")
            .map(canonical_json)
            .unwrap_or("not_present".into());
        out.push((
            format!("temperature_points:{id}:author"),
            model.clone(),
            set_intent(
                "Material",
                &id,
                "temperature_points",
                &current,
                &points.to_string(),
            ),
        ));
        let mut with_points = model.clone();
        with_points["materials"][index]["temperature_points"] = points.clone();
        let before = canonical_json(&points);
        let mut removed = points.clone();
        removed.as_array_mut().unwrap().remove(0);
        let mut renamed = points.clone();
        renamed[0]["id"] = json!("point:invented-renamed");
        let mut added = points.clone();
        added.as_array_mut().unwrap().push(json!({"id":"point:invented-partial","temperature":{"value":80,"unit":"degC"},"provenance":"invented control point"}));
        for (label, after) in [
            ("remove", removed),
            ("rename", renamed),
            ("add_incomplete", added),
            ("unchanged", points.clone()),
            ("empty", json!([])),
        ] {
            out.push((
                format!("temperature_points:{id}:{label}"),
                with_points.clone(),
                set_intent(
                    "Material",
                    &id,
                    "temperature_points",
                    &before,
                    &after.to_string(),
                ),
            ));
        }
    }
    out
}
fn authoring_outcomes() -> Value {
    let mut records = Map::new();
    // Models before 0.4.0 only: F9 deliberately changes 0.4.0 warnings.
    for (name, model) in models().into_iter().take(3) {
        for (key, base, op) in authoring_intents(&model) {
            let claim = hash(&base);
            for (mode, outcome) in [
                ("validate", validate_operation(&base, &op, Some(&claim))),
                ("apply", apply_operation(&base, &op, Some(&claim))),
            ] {
                let codes: Vec<&str> = outcome
                    .diagnostics
                    .iter()
                    .map(|d| d.code.as_str())
                    .collect();
                records.insert(
                    format!("{name}|{key}|{mode}"),
                    json!({
                        "outcome_sha256": sha256_hex(&serde_json::to_string(&outcome).unwrap()),
                        "applied": outcome.applied_model.is_some(),
                        "codes": codes,
                    }),
                );
            }
        }
    }
    Value::Object(records)
}

#[test]
fn pressure_profile_and_temperature_point_outcomes_before_0_4_0_are_byte_identical_to_the_base_revision(
) {
    let actual = authoring_outcomes();
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join(AUTHORING_GOLDEN);
    if std::env::var_os("LOAD_REFERENCE_DELETE_CONTROL_BLESS").is_some() {
        std::fs::write(&path, serde_json::to_string_pretty(&actual).unwrap() + "\n").unwrap();
        return;
    }
    let golden: Value = serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap();
    assert_eq!(golden, actual);
    let rows = golden.as_object().unwrap();
    for kind in ["pressure_profile", "temperature_points"] {
        assert!(rows.keys().any(|k| k.contains(kind)), "{kind}");
    }
    assert!(rows.values().any(|r| r["applied"] == true));
    assert!(rows.values().any(|r| r["applied"] == false));
}
