import { act, renderHook } from "@testing-library/react";
import { expect, it, vi, afterEach } from "vitest";
import { invoke } from '@tauri-apps/api/core';
import modelFixture from '../../../../../fixtures/product_preview/invented_preview_model.json';
import producerFixture from '../../../../../fixtures/product_preview/invented_mechanics_result_precision_1_sparse.json';
import {runPreviewMechanics,buildAnalysisRunPreview} from '../../services/previewService';
import {buildCurrentSessionInputManifest} from '../../services/inputManifestService';
import type {PreviewModel} from '../../types';
vi.mock('@tauri-apps/api/core',()=>({invoke:vi.fn()}));
afterEach(()=>{delete (window as any).__TAURI_INTERNALS__;vi.resetAllMocks();});
import { useResultsSessionState } from "./resultsSessionState";
import type { MechanicsResult } from "../../types";
it("keeps solved historical and unassessed carriers out of Current without changing stored evidence", () => {
 const {result} = renderHook(() => useResultsSessionState());
 const legacy = {schema_version:"0.1.0", document_kind:"MechanicsResult", run_id:"r",model_ref:"m",status:{mechanics:"MECHANICS_SOLVED",rule_check:"RULE_INPUTS_INCOMPLETE",professional_acceptance:"NOT_PROVIDED"}, summary:{},results:[],diagnostics:[]} as MechanicsResult;
 act(()=>result.current.setResult(legacy));
 expect(result.current.result).toBe(legacy);
 expect(result.current.currentSolvedResult).toBeNull();
 expect(result.current.currentSolvedResultRef.current).toBeNull();
 expect(result.current.comparison).toBeNull();
 const unknown = {...legacy,schema_version:"0.2.0"};
 act(()=>result.current.setResult(unknown));
 expect(result.current.result).toBe(unknown);
 expect(result.current.currentSolvedResult).toBeNull();
});

it("requires actual invocation plus joined precision analysis and manifest identities before publishing Current", async () => {
 const {result} = renderHook(() => useResultsSessionState());
 const model=structuredClone(modelFixture) as PreviewModel;
 Object.defineProperty(window,'__TAURI_INTERNALS__',{value:{},configurable:true});
 vi.mocked(invoke).mockResolvedValueOnce(structuredClone(producerFixture));
 const source=await runPreviewMechanics(model);
 const manifest=await buildCurrentSessionInputManifest({model,solver:{solver_name:source.producer!.component_name,solver_version:source.producer!.component_version,solver_build_ref:'mocked-native-build',solver_mode:'sparse_interactive',settings:{}},active_rule_packs:[],external_assets:[]});
 const analysis=await buildAnalysisRunPreview(source,{inputManifest:manifest});
 act(()=>{result.current.setResult(source);result.current.setInputManifest(manifest as never);});
 expect(result.current.currentSolvedResult).toBeNull();
 act(()=>result.current.setAnalysisRun(analysis as never));
 expect(result.current.currentSolvedResult).toBe(source);
 const sensitive = structuredClone(source);
 sensitive.numerical_quality!.status = "sensitive";
 sensitive.numerical_quality!.cases[0].solve_quality = "sensitive";
 sensitive.numerical_quality!.cases[0].accuracy_evidence = "reference_verified";
 const before = JSON.stringify(sensitive);
 vi.mocked(invoke).mockResolvedValueOnce(sensitive);
 const sensitiveResponse=await runPreviewMechanics(model);
 act(()=>result.current.setResult(sensitiveResponse));
 expect(result.current.result).toBe(sensitive);
 expect(result.current.currentSolvedResult).toBeNull();
 expect(result.current.currentSolvedResultRef.current).toBeNull();
 expect(JSON.stringify(sensitive)).toBe(before);
 act(()=>result.current.setResult(source));
 expect(result.current.currentSolvedResult).toBe(source);
 act(()=>result.current.setAnalysisRun({...analysis,schema_version:"0.2.0"} as never));
 expect(result.current.currentSolvedResult).toBeNull();
});
