# C1 register proposals, refreshed. One dict per proposed register change.
# kind: MIRROR (row for an arc DAG-001 already carries), NEWREP (representative
# UPSTREAM row of a new arc), NEWMIR (supplier-side DOWNSTREAM row of a new arc),
# EXT (new non-deliverable row), EDIT (field edit on an existing row),
# PKG (package-row treatment), NORM (value normalization)
# disp: KEEP / AMEND / DROP / DEFER
# route: EXTRACT (dependency-extract UPDATE) / DECLARE (human declaration) / NONE
# ev: (design-file key, regex) locating the evidence line in the host's own sources
P = []
def add(**k): P.append(k)

# ---------------- C1-A: DEL-04-01 (ACT) ----------------
H='DEL-04-01'
add(c1='R-04-01-a',host=H,dir='DOWNSTREAM',typ='HANDOVER',tgt='DEL-03-02',kind='MIRROR',cp='DEP-03-02-017',disp='KEEP',route='EXTRACT',ev=('ACT',r'^\| V-03 \|'),stmt='Supplies the adopted class vocabulary, resolution order, grant model and outcome map (ACT §10.1 V-02, V-03, V-04, V-05, V-14) to the proposal contract.')
add(c1='R-04-01-b',host=H,dir='DOWNSTREAM',typ='HANDOVER',tgt='DEL-05-01',kind='MIRROR',cp='DEP-05-01-018',disp='KEEP',route='EXTRACT',ev=('ACT',r'^\| V-04 \|'),stmt='Supplies act names, class values, grant model, outcome map and checkpoint rules (ACT §10.1 V-01…V-05, V-09, V-21) to the host-loop receiving contract.')
add(c1='R-04-01-c',host=H,dir='DOWNSTREAM',typ='HANDOVER',tgt='DEL-05-02',kind='MIRROR',cp='DEP-05-02-008',disp='KEEP',route='EXTRACT',ev=('ACT',r'^\| V-07 \|'),stmt='Supplies act names, outcome map, label rules and A3≠A4 display rules (ACT §10.1 V-01, V-05, V-07, V-12) to the panel receiving contract.')
add(c1='R-04-01-d',host=H,dir='DOWNSTREAM',typ='HANDOVER',tgt='DEL-03-03',kind='MIRROR',cp='DEP-03-03-008',disp='KEEP',route='EXTRACT',ev=('ACT',r'^\| V-10 \|'),stmt='Supplies class values, resolution order and the external-access rules including A13 (ACT §10.1 V-02, V-03, V-10, V-14) to the external receiving adapter.')
add(c1='R-04-01-e',host=H,dir='DOWNSTREAM',typ='HANDOVER',tgt='DEL-03-04',kind='MIRROR',cp='DEP-03-04-011',disp='KEEP',route='EXTRACT',ev=('ACT',r'^- DEL-03-04 \(DEP-03-04-011\)'),stmt='Declared consumer of the operation-policy contract for the integrated host guide (ACT §10.3).')
add(c1='R-04-01-f',host=H,dir='DOWNSTREAM',typ='HANDOVER',tgt='DEL-09-09',kind='MIRROR',cp='DEP-09-09-010',disp='KEEP',route='EXTRACT',ev=('ACT',r'^\| V-08 \|'),stmt='Supplies professional-standing, external-access, record-shape and reserved-operation values (ACT §10.1 V-08, V-10, V-11, V-13, V-14) to the external trace cases.')
add(c1='R-04-01-g',host=H,dir='DOWNSTREAM',typ='HANDOVER',tgt='DEL-09-06',kind='NEWMIR',arc='N-28',disp='DROP',route='NONE',ev=None,why='Optional supplier-side mirror of N-28. ACT names DEL-09-06 only as a source of SWBPIPE answers in its consumed-inputs list, not as a consumer, so DEL-04-01 extraction would not support it. The representative row is DEL-09-06 UPSTREAM (R9-6-3).')
add(c1='DEP-04-01-017',host=H,kind='EDIT',row='DEP-04-01-017',disp='AMEND',route='EXTRACT',ev=('SOW',r'TBD-001'),stmt='Statement/Notes: OI-001 ruled for the first increment by APP-V4-FIRST-INCREMENT-20260928-DECISION-1 D2 (five reserved acts; stand under DECISION-4); residual operation-specific additions are OI-021 (row R-04-01-h). SatisfactionStatus unchanged (owning route).',why='C1 pointer update; depends on P1 SC-04-01-8 revising TBD-001. Evidence drift only.')
add(c1='DEP-04-01-018',host=H,kind='EDIT',row='DEP-04-01-018',disp='AMEND',route='EXTRACT',ev=('SOW',r'TBD-002'),stmt='Statement/Notes: OI-002 ruled by DECISION-1 D3; no open part for the first increment. Status stays ACTIVE until the SoW TBD-002 text is revised; if P1 SC-04-01-9 removes the open condition the next extraction retires the row (retired_by=source_changed).',why='C1 pointer update; P1 SC-04-01-9. Evidence drift only.')
add(c1='R-04-01-h',host=H,dir='UPSTREAM',typ='CONSTRAINT',tgt='EXT:OI-021',kind='EXT',disp='KEEP',route='EXTRACT',ev=('ACT',r'^\| V-20 / V-22 \|'),stmt='Operation-specific reserved additions and the first connected operation remain UNRESOLVED{OI-021} (owner via the outside SWB session and App/shared owner); still open after R8-10.')
add(c1='R-04-01-i',host=H,dir='UPSTREAM',typ='CONSTRAINT',tgt='EXT:DECISION-4-GOV',kind='EXT',disp='AMEND',route='EXTRACT',ev=('ACT',r'^\| V-26 \|'),stmt='App-side run holds are governance-phase only: D6 is closed for Phase 1 by APP-V4-SWBPIPE-INTAKE-20260928-DECISION-4 D4-1 and re-opens when the governance phase is taken up (R8-2; SQ-02 answered: route (iv), none planned).',why='C1 targeted "DECISION-2 D6 / relay SQ-02". SQ-02 is now answered and D6 is closed for Phase 1 (R8-2), so the constraint is retargeted to the governance-phase re-opening.')

# ---------------- C1-A: DEL-04-02 (AS) ----------------
H='DEL-04-02'
add(c1='R-04-02-a',host=H,dir='UPSTREAM',typ='INTERFACE',tgt='DEL-03-02',kind='MIRROR',cp='DEP-03-02-018',disp='KEEP',route='EXTRACT',ev=('AS',r'^\| Route and outcome \|'),stmt='Receives the proposal outcome taxonomy, direct-branch entry condition and origin semantics (P §4.4, §9) for the result standing model (AS §8).')
add(c1='R-04-02-b',host=H,dir='DOWNSTREAM',typ='HANDOVER',tgt='DEL-03-04',kind='MIRROR',cp='DEP-03-04-012',disp='KEEP',route='EXTRACT',ev=('AS',r'Host builder via DEL-03-04'),stmt='Supplies the grant display and standing model to the integrated host guide (AS Receivers: host builder via DEL-03-04).')
add(c1='R-04-02-c',host=H,dir='UPSTREAM',typ='INTERFACE',tgt='DEL-03-01',kind='NEWREP',arc='N-01',disp='KEEP',route='EXTRACT',ev=('AS',r'^\| Temporal \|'),stmt='Receives the catalog standing facets and read-result standing (C §6.2) for the temporal facet of result standing (AS §8).')
add(c1='R-04-02-d',host=H,dir='UPSTREAM',typ='INTERFACE',tgt='DEL-02-03',kind='NEWREP',arc='N-02',disp='AMEND',route='EXTRACT',ev=('AS',r'Display meanings of the DEL-02-03 hold machine'),stmt='Receives the display meanings of the EXEC annotations and compatibility report (Phase 1) and, for the governance phase, the hold-machine and hold-support values (EXEC §2.1, §2.2, §3.6, §4) for the checkpoint overlay (AS §4).',why='Amended for R8-1: the overlay is observation in Phase 1; hold values are governance phase (retained).')
for (c,t,a) in [('R-04-02-e','DEL-05-01','N-03'),('R-04-02-f','DEL-05-02','N-04'),('R-04-02-g','DEL-03-02','N-05'),('R-04-02-h','DEL-03-03','N-06'),('R-04-02-i','DEL-02-03','N-07')]:
    add(c1=c,host=H,dir='DOWNSTREAM',typ='HANDOVER',tgt=t,kind='NEWMIR',arc=a,disp='KEEP',route='EXTRACT',ev=('AS',r'^- Receivers:'),stmt='Supplies grant display states, grant value and scope and settings references (AS §3); named receiver in AS Receivers ("register edges pending at C1").')
add(c1='R-04-02-j',host=H,dir='DOWNSTREAM',typ='HANDOVER',tgt='DEL-09-06',kind='NEWMIR',arc='N-08',disp='DROP',route='NONE',ev=None,why='Optional supplier mirror. AS names DEL-09-06 only in version-citation lines; extraction of DEL-04-02 would not support it. Representative row is DEL-09-06 UPSTREAM (R9-6-3).')
add(c1='R-04-02-k',host=H,dir='DOWNSTREAM',typ='HANDOVER',tgt='DEL-09-09',kind='NEWMIR',arc='N-09',disp='DROP',route='NONE',ev=None,why='Optional supplier mirror. AS does not name DEL-09-09 as a receiver. Representative row is DEL-09-09 UPSTREAM (R9-9-2).')
add(c1='DEP-04-02-011/-012',host=H,kind='EDIT',row='DEP-04-02-011;DEP-04-02-012',disp='AMEND',route='EXTRACT',ev=('SOW',r'OI-001'),stmt='Notes: OI-001 ruled by DECISION-1 D2 (reserved acts stand, DECISION-4); OI-002 ruled by DECISION-1 D3; residual OI-021 (row R-04-02-l).',why='Pointer update (V1-A RF-04). Evidence drift only.')
add(c1='R-04-02-l',host=H,dir='UPSTREAM',typ='CONSTRAINT',tgt='EXT:OI-021',kind='EXT',disp='KEEP',route='EXTRACT',ev=('AS',r'OI-021'),stmt='Operation-specific reserved additions remain UNRESOLVED{OI-021} (AS U-01).')
add(c1='R-04-02-m',host=H,dir='UPSTREAM',typ='CONSTRAINT',tgt='EXT:DECISION-4-GOV',kind='EXT',disp='AMEND',route='EXTRACT',ev=('AS',r'U-16'),stmt='App-side run-hold display is governance-phase only: D6 closed for Phase 1 by DECISION-4 D4-1; re-opens with the governance phase (R8-2).',why='Retargeted from DECISION-2 D6 / SQ-02 as for R-04-01-i.')
add(c1='R8-AS-1',host=H,dir='UPSTREAM',typ='INTERFACE',tgt='DEL-05-01',kind='NEWREP',arc='R8-A',disp='ADD',route='EXTRACT',ev=('AS',r"from the host's control"),evn=2,stmt="Receives the host-agent network rules (LOOP §5.1.1 NW-8…NW-16: category switches, named entries, in-work grant scopes, always-off items) that the grant display shows (AS §3, R8-13; DECISION-5).",why='New relationship written by the R8-13 pass (DECISION-5).')

# ---------------- C1-A: DEL-04-03 (RS) ----------------
H='DEL-04-03'
add(c1='R-04-03-a',host=H,dir='UPSTREAM',typ='INTERFACE',tgt='DEL-04-01',kind='MIRROR',cp='DEP-04-01-016',disp='KEEP',route='EXTRACT',ev=('RS',r'^\| R15 \|'),stmt='Receives act names A1–A14, act-declined and run-ended events, the A12 network-destination grant subclass and content-binding/lapse rules (ACT §2, §2.5, §2.7) for the human-act and run records.')
add(c1='R-04-03-b',host=H,dir='UPSTREAM',typ='INTERFACE',tgt='DEL-03-02',kind='MIRROR',cp='DEP-03-02-019',disp='KEEP',route='EXTRACT',ev=('RS',r'^\| DEL-03-02 \| §5 evidence rules'),stmt='Receives §9 outcomes, change-item content identity, origin incl. constraint and author identity, resulting objects and item-left events from the proposal contract (RS §10).')
add(c1='R-04-03-c',host=H,dir='UPSTREAM',typ='INTERFACE',tgt='DEL-04-02',kind='MIRROR',cp='DEP-04-02-009',disp='KEEP',route='EXTRACT',ev=('RS',r'^\| DEL-04-02 \| Record-out'),stmt='Receives settings-in (RS §8; CASE-002 M3) from the autonomy and standing exchange.')
add(c1='R-04-03-d',host=H,dir='DOWNSTREAM',typ='INTERFACE',tgt='DEL-02-01',kind='MIRROR',cp='DEP-02-01-019',disp='KEEP',route='EXTRACT',ev=('RS',r'^\| DEL-02-01 \| Act names'),stmt='Supplies act names, R8 subject classes and dispositions and R2 workflow identity meanings (RS §10) to the workflow declaration contract.')
add(c1='R-04-03-e',host=H,dir='DOWNSTREAM',typ='INTERFACE',tgt='DEL-02-03',kind='MIRROR',cp='DEP-02-03-013',disp='KEEP',route='EXTRACT',ev=('RS',r'^\| DEL-02-03 \| R8 arrivals'),stmt='Supplies R8 arrivals and events, R2 transfer links, R11 and R14 (RS §10) to execution compatibility.')
add(c1='R-04-03-f',host=H,dir='DOWNSTREAM',typ='HANDOVER',tgt='DEL-05-01',kind='MIRROR',cp='DEP-05-01-019',disp='KEEP',route='EXTRACT',ev=('RS',r'^\| DEL-05-01 \| R3/R4'),stmt='Supplies R3/R4/R5/R5a/R7/R8 record meanings (RS §10) to the host-loop receiving contract.')
add(c1='R-04-03-g',host=H,dir='DOWNSTREAM',typ='HANDOVER',tgt='DEL-05-02',kind='MIRROR',cp='DEP-05-02-009',disp='KEEP',route='EXTRACT',ev=('RS',r'^\| DEL-05-02 \| Act, act-declined'),stmt='Supplies act, act-declined, lapse, supersession and annotation display meanings (RS §10) to the panel receiving contract.')
add(c1='R-04-03-h',host=H,dir='DOWNSTREAM',typ='HANDOVER',tgt='DEL-09-06',kind='MIRROR',cp='DEP-09-06-015',disp='KEEP',route='EXTRACT',ev=('RS',r'^\| DEL-09-06 \| R2 transfer'),stmt='Supplies R2 transfer links (RS §10) to the connected activity contract.')
add(c1='R-04-03-i',host=H,dir='DOWNSTREAM',typ='HANDOVER',tgt='DEL-09-09',kind='MIRROR',cp='DEP-09-09-011',disp='KEEP',route='EXTRACT',ev=None,stmt='Supplies the record meaning consumed by the external trace cases (SoW REQ-005 as revised per SC-04-03-2).',why='Optional mirror. RS names DEL-09-09 only in a version-citation line, not as a consumer; the arc is already represented by DEP-09-09-011 (consumer UPSTREAM).')
add(c1='R-04-03-j',host=H,dir='DOWNSTREAM',typ='HANDOVER',tgt='DEL-03-04',kind='MIRROR',cp='DEP-03-04-013',disp='DROP',route='NONE',ev=None,why='Optional mirror. RS names DEL-03-04 only in a version-citation line; arc represented by DEP-03-04-013.')
add(c1='R-04-03-k',host=H,dir='UPSTREAM',typ='INTERFACE',tgt='DEL-03-01',kind='NEWREP',arc='N-10',disp='KEEP',route='EXTRACT',ev=('RS',r'^\| DEL-03-01 \| R7 identity'),stmt='Receives subject content identity, method designation, exposure element and the shared fixture (C §5.3, §10) used by R7 and the lapse rules (RS §10, L-1).')
add(c1='R-04-03-l',host=H,dir='UPSTREAM',typ='INTERFACE',tgt='DEL-02-03',kind='NEWREP',arc='N-13',disp='AMEND',route='EXTRACT',ev=('RS',r'^\| DEL-02-03 \| R8 arrivals'),stmt='Receives the Phase-1 recording rules and, for the governance phase, the hold machine, resume point, re-hold and refused-A12 effect, plus compatibility reports, transfer trace and App capture requirements (EXEC §2.1, §2.2, §4, §5, §6; RS §10).',why='Amended for R8-1 phasing.')
add(c1='R-04-03-m',host=H,dir='UPSTREAM',typ='INTERFACE',tgt='DEL-03-03',kind='NEWREP',arc='N-14',disp='KEEP',route='EXTRACT',ev=('RS',r'^\| DEL-03-03 \| R5 destination'),stmt='Receives external dispatch entries, model destination class and evidence limits from the external receiving adapter (RS §10; ADAPTER §11 "Provide to DEL-04-03").')
add(c1='R-04-03-n',host=H,dir='UPSTREAM',typ='INTERFACE',tgt='DEL-01-01',kind='NEWREP',arc='N-15',disp='KEEP-CONFIRM',route='EXTRACT',ev=('RS',r'^\| DEL-01-01 \| R3, R5, R13'),stmt='Receives supplied-guidance identities, per-turn requested/effective model and re-routes (HOSTING §8.3) and A14 settlement origin for R3, R5 and R13 (RS §10).',why='Conditional in C1 (alternative: S-7 through DEL-01-02). Recommendation: keep; checkpoint 1 confirms.')
add(c1='R-04-03-o',host=H,dir='DOWNSTREAM',typ='INTERFACE',tgt='DEL-03-01',kind='NEWMIR',arc='N-11',disp='KEEP',route='EXTRACT',ev=('RS',r'^\| DEL-03-01 \| R7 identity'),stmt='Supplies R7 identity/basis meanings and c₁ for A4/A6/A7 (RS §10) to the catalog contract; resolves part of package row DEP-04-03-012.')
add(c1='R-04-03-p',host=H,dir='DOWNSTREAM',typ='INTERFACE',tgt='DEL-03-02',kind='NEWMIR',arc='N-12',disp='DROP',route='NONE',ev=None,why='Disputed arc N-12. Recommendation: not proposed (ARC_ANALYSIS §3). The RS §10 cell "DEL-03-02 consumes §5 evidence rules" goes to DEL-04-03\'s owner as a wording finding, and the DEL-04-03 extraction brief withholds this row.')
add(c1='DEP-04-03-012',host=H,kind='PKG',row='DEP-04-03-012',disp='KEEP',route='EXTRACT',ev=('SOW',r'PKG-03'),stmt='Package-level DOWNSTREAM row to PKG-03 stays ACTIVE while the SoW names the package; it is non-topological (NOT_TOPOLOGICAL). Its deliverable-level content is carried by R-04-03-o (DEL-03-01) and the existing DEP-03-04-013 arc.',why='C1 proposed retarget/split. A retire is not needed for DAG-002 and would be a register-owner choice. If P1 rewrites the SoW package reference, extraction retires it.')
add(c1='DEP-04-03-019',host=H,kind='EDIT',row='DEP-04-03-019',disp='AMEND',route='EXTRACT',ev=('SOW',r'OI-001'),stmt='Notes: OI-001/OI-002 ruled by DECISION-1 D2/D3 at App/shared level; residual OI-021.')
add(c1='R8-RS-1',host=H,dir='UPSTREAM',typ='INTERFACE',tgt='DEL-05-01',kind='NEWREP',arc='R8-B',disp='ADD',route='EXTRACT',ev=('RS',r'^\| R15 \|'),stmt='Receives host-loop events and the network rules through DEL-05-01 (LOOP §2.3, §5.1.1) for R15 network destinations, and observer-attributed unknown, run-resumed/run-ended (RS §10).',why='R15 (R8-13, DECISION-5) names DEL-05-01 as the source of destination events.')

# ---------------- C1-A: DEL-02-01 (WD) ----------------
H='DEL-02-01'
add(c1='R-02-01-a',host=H,dir='DOWNSTREAM',typ='HANDOVER',tgt='DEL-02-02',kind='MIRROR',cp='DEP-02-02-014',disp='KEEP',route='EXTRACT',ev=('WD',r'^\| DEL-02-02, DEL-02-04 \(later'),stmt='Supplies WD §3, §4.6, §6 (and §5 roles to DEL-02-04) to the later workflow-making and role-supply definitions (WD §8).')
add(c1='R-02-01-b',host=H,dir='DOWNSTREAM',typ='HANDOVER',tgt='DEL-02-03',kind='MIRROR',cp='DEP-02-03-009',disp='KEEP',route='EXTRACT',ev=('WD',r'^\| DEL-02-03 execution'),stmt='Supplies §4.2 references, constraint and pass rule, §4.3 incl. §4.3.0 Phase-1 guidance and the governed flag, §6.4 (WD §8).')
add(c1='R-02-01-c',host=H,dir='DOWNSTREAM',typ='HANDOVER',tgt='DEL-02-04',kind='MIRROR',cp='DEP-02-04-011',disp='KEEP',route='EXTRACT',ev=('WD',r'^\| DEL-02-02, DEL-02-04 \(later'),stmt='Supplies role meaning and compatible roles (WD §5) to additive role selection and supply (WD §8).')
add(c1='R-02-01-d',host=H,dir='DOWNSTREAM',typ='HANDOVER',tgt='DEL-05-01',kind='MIRROR',cp='DEP-05-01-016',disp='KEEP',route='EXTRACT',ev=('WD',r'^\| DEL-05-01 loop'),stmt='Supplies §4.3.0, reached-when, governed flag, declared subject class, binding table, dispositions and §6.1–6.2 (WD §8) to the host-loop receiving contract.')
add(c1='R-02-01-e',host=H,dir='DOWNSTREAM',typ='HANDOVER',tgt='DEL-05-02',kind='MIRROR',cp='DEP-05-02-005',disp='KEEP',route='EXTRACT',ev=('WD',r'^\| DEL-05-02 panel'),stmt='Supplies §4.2.4 outcomes and pass rule, dispositions, annotations, labels and selection (WD §8) to the panel receiving contract.')
add(c1='R-02-01-f',host=H,dir='DOWNSTREAM',typ='HANDOVER',tgt='DEL-03-04',kind='MIRROR',cp='DEP-03-04-008',disp='KEEP',route='EXTRACT',ev=('WD',r'Later: DEL-03-04'),stmt='Named later receiver for the integrated host guide (WD Receivers: DEL-03-04 (W10)).')
add(c1='R-02-01-g',host=H,dir='UPSTREAM',typ='INTERFACE',tgt='DEL-01-01',kind='NEWREP',arc='N-16',disp='KEEP',route='EXTRACT',ev=('WD',r'^\| DEL-01-01 \| Supplied-guidance'),stmt='Receives supplied-guidance identity evidence (HOSTING §8.2) and the harness capability inventory at 0.158.0 for harness-capability naming (WD §8; U-08).')
add(c1='R-02-01-h',host=H,dir='UPSTREAM',typ='INTERFACE',tgt='DEL-02-03',kind='NEWREP',arc='N-17',disp='AMEND',route='EXTRACT',ev=('WD',r'^\| DEL-02-03 \| Phase-1 statement'),stmt='Receives the Phase-1 statement (EXEC §2.1), governance-phase scope (§2.2), report and hold support (§3.6, governance phase), hold machine (§4), App capture (§5) and transfer (§6) (WD §8).',why='Amended for R8-1 phasing.')
add(c1='R-02-01-i',host=H,dir='UPSTREAM',typ='INTERFACE',tgt='DEL-03-02',kind='NEWREP',arc='N-18',disp='KEEP',route='EXTRACT',ev=('WD',r'^\| DEL-03-02 \| P §9'),stmt='Receives P §9, change-item content identity, item dispositions, all-decided and item-left events, governing checkpoint constraint and applied-outcome object identities (WD §8).')
add(c1='R-02-01-j',host=H,dir='DOWNSTREAM',typ='HANDOVER',tgt='DEL-09-06',kind='NEWMIR',arc='N-19',disp='KEEP',route='EXTRACT',ev=('WD',r'Later: DEL-03-04'),stmt='Named later receiver (WD Receivers: DEL-09-06 (W9)); supplies the declaration contract to the connected activity.')
add(c1='R-02-01-k',host=H,dir='DOWNSTREAM',typ='HANDOVER',tgt='DEL-03-03',kind='NEWMIR',arc='N-20',disp='KEEP',route='EXTRACT',ev=('WD',r'^\| A-12 \|'),stmt='Supplies the governing checkpoint constraint derivation rule to the external adapter (WD §9 A-12: consumers DEL-05-01, DEL-03-03).')
add(c1='R-02-01-k2',host=H,dir='DOWNSTREAM',typ='HANDOVER',tgt='DEL-03-02',kind='NEWMIR',arc='N-B3',disp='KEEP',route='EXTRACT',ev=('WD',r'^\| DEL-03-02 proposal'),stmt='Supplies §4.2.2 governing checkpoint constraint, §4.3.6 and §4.3.7 needs to the proposal contract (WD §8).',why='Not in C1-A; supplier side of C1-B N-B3, evidenced by WD §8.')
add(c1='R-02-01-l',host=H,dir='UPSTREAM',typ='CONSTRAINT',tgt='EXT:OI-021',kind='EXT',disp='AMEND',route='EXTRACT',ev=('WD',r'UNRESOLVED\{OI-021\}'),stmt='Operation-specific reserved additions remain UNRESOLVED{OI-021}; DECISION-1 D2/D3 carried (WD §2 S-Q/S-R/S-S).',why='C1 combined DECISION-1 and OI-021. DECISION-1 is ruled, so it is carried in Notes and not held as an open constraint.')
add(c1='R-02-01-m',host=H,dir='UPSTREAM',typ='CONSTRAINT',tgt='EXT:DECISION-4-GOV',kind='EXT',disp='AMEND',route='EXTRACT',ev=('WD',r'^\| \*\*R8-2\*\*'),stmt='Hold support and App-side holds are governance-phase only: D6 closed for Phase 1 by DECISION-4 D4-1; re-opens with the governance phase (WD U-30, U-33; R8-2).',why='Retargeted from DECISION-2 D6 / SQ-02.')
add(c1='R-02-01-n',host=H,dir='UPSTREAM',typ='CONSTRAINT',tgt='EXT:OI-018',kind='EXT',disp='KEEP',route='EXTRACT',ev=('SOW',r'OI-018'),stmt='SoW TBD-003 names OI-018; the register has no row.')

# ---------------- C1-A: DEL-02-03 (EXEC) ----------------
H='DEL-02-03'
add(c1='R-02-03-a',host=H,dir='DOWNSTREAM',typ='HANDOVER',tgt='DEL-05-01',kind='MIRROR',cp='DEP-05-01-017',disp='KEEP',route='EXTRACT',ev=('EXEC',r'^\| DEL-05-01 \| Phase 1: the host'),stmt='Supplies PH-2 (Phase 1: the host loop enforces no hold) and, for the governance phase, hold-machine semantics, enforced-by-host-loop value and RH-8/RH-9 (EXEC §9.2).')
add(c1='R-02-03-b',host=H,dir='DOWNSTREAM',typ='HANDOVER',tgt='DEL-03-04',kind='MIRROR',cp='DEP-03-04-009',disp='DROP',route='NONE',ev=None,why='Optional mirror. EXEC does not name DEL-03-04 as a receiver (only a version citation); arc represented by DEP-03-04-009.')
add(c1='R-02-03-c',host=H,dir='DOWNSTREAM',typ='HANDOVER',tgt='DEL-02-02',kind='MIRROR',cp='DEP-02-02-015',disp='KEEP',route='EXTRACT',ev=('EXEC',r'^\| Review, registration, selection policy, drafts'),stmt='Supplies the §6.5 routes for review, registration, selection policy and drafts to the workflow-making workspace (EXEC §10).')
for (c,t,a,pat,st) in [('R-02-03-d','DEL-03-02','N-21',r'^\| DEL-03-02 \(P\)','Receives per-item dispositions, item-left events, change-item content identity, applied outcomes, stale/application-error outcomes and the governing constraint with carriage assurance (governance phase) (EXEC §9.1).'),
                       ('R-02-03-e','DEL-05-01','N-22',r'^\| DEL-05-01 \(LOOP\)','Receives arrival observation, binding, events, dispatch record and retry rules, and host-loop hold support for the governance phase (EXEC §9.1).'),
                       ('R-02-03-f','DEL-04-02','N-07',r'^\| DEL-04-02 \(AS\)','Receives grant display states incl. set by person, not yet confirmed, unconfirmed and refused (EXEC §9.1; §4.10).'),
                       ('R-02-03-g','DEL-01-01','N-23',r'^\| DEL-01-01 \(HOSTING\)','Receives supplied-guidance evidence (§8.2), observed model destination per turn (§8.3), request kinds and R9, and the HP-4 scope ruling (EXEC §9.1).'),
                       ('R-02-03-h','DEL-03-03','N-24',r'^\| DEL-03-03 \(ADAPTER\)','Receives carriage assurance, GC-1…GC-5, §7.7 checkpoint observation on X and model destination in channel status (EXEC §9.1).')]:
    add(c1=c,host=H,dir='UPSTREAM',typ='INTERFACE',tgt=t,kind='NEWREP',arc=a,disp='KEEP',route='EXTRACT',ev=('EXEC',pat),stmt=st)
for (c,t,a,pat,st) in [('R-02-03-i','DEL-02-01','N-17',r'^\| DEL-02-01 \| §2.1 Phase-1','Supplies §2.1 Phase-1 statement, §2.2 governance-phase scope and governed opt-in, hold-support values (governance phase), §3.5 check result, R5-3, SP-6, AD-2 (EXEC §9.2).'),
                       ('R-02-03-j','DEL-04-03','N-13',r'^\| DEL-04-03 \| Record needs','Supplies record needs (R4-10/R4-11), per-turn destination, person\'s own operations as R7 (EXEC §9.2).'),
                       ('R-02-03-k','DEL-04-02','N-02',r'^\| DEL-05-02, DEL-04-02 \|','Supplies display meanings of the §4.3 annotations, §3.3 report and hold-support values (EXEC §9.2).'),
                       ('R-02-03-l','DEL-05-02','N-25',r'^\| DEL-05-02, DEL-04-02 \|','Supplies display meanings of the §4.3 annotations, §3.3 report and hold-support values (EXEC §9.2).'),
                       ('R-02-03-n','DEL-03-03','N-27',r'^\| DEL-03-03 \| Governance phase','Supplies governance-phase hold-support values for X and CH-22/CH-27 expectations in two parts (EXEC §9.2).')]:
    add(c1=c,host=H,dir='DOWNSTREAM',typ='HANDOVER',tgt=t,kind='NEWMIR',arc=a,disp='KEEP',route='EXTRACT',ev=('EXEC',pat),stmt=st)
add(c1='R-02-03-m',host=H,dir='DOWNSTREAM',typ='HANDOVER',tgt='DEL-09-09',kind='NEWMIR',arc='N-26',disp='DROP',route='NONE',ev=None,why='Optional supplier mirror. EXEC does not name DEL-09-09 as a receiver; representative row is DEL-09-09 UPSTREAM (R9-9-3).')
add(c1='DEP-02-03-015/-016',host=H,kind='EDIT',row='DEP-02-03-015;DEP-02-03-016',disp='AMEND',route='EXTRACT',ev=('SOW',r'OI-001'),stmt='Notes: OI-001 ruled by DECISION-1 D2 (reserved acts stand, DECISION-4); OI-002 ruled by D3; residual OI-021 already carried by DEP-02-03-019.')
add(c1='R-02-03-o',host=H,dir='UPSTREAM',typ='CONSTRAINT',tgt='EXT:DECISION-4-GOV',kind='EXT',disp='AMEND',route='EXTRACT',ev=('EXEC',r'U-E23'),stmt='App-side holds and App-only checkpoints are governance-phase only: D6 closed for Phase 1 by DECISION-4 D4-1 (EXEC U-E1, U-E23 re-pointed; R8-2).',why='Retargeted from DECISION-2 D6 / SQ-02.')

# ---------------- C1-B: DEL-03-01 (C) ----------------
H='DEL-03-01'
for (c,t,cp,pat) in [('M-01-1','DEL-05-01','DEP-05-01-014',r'^- Receivers:'),('M-01-2','DEL-05-02','DEP-05-02-006',r'^- Receivers:'),
                     ('M-01-3','DEL-02-01','DEP-02-01-017',r'^- Receivers:'),('M-01-4','DEL-02-03','DEP-02-03-011',r'^- Receivers:'),
                     ('M-01-5','DEL-03-03','DEP-03-03-006',r'^- Receivers:'),('M-01-6','DEL-03-04','DEP-03-04-005',r'^- Receivers:'),
                     ('M-01-7','DEL-09-09','DEP-09-09-007',r'^- Receivers:')]:
    add(c1=c,host=H,dir='DOWNSTREAM',typ='HANDOVER',tgt=t,kind='MIRROR',cp=cp,disp='KEEP',route='EXTRACT',ev=('C',pat),stmt='Named receiver of the catalog and read-basis contract (C Receivers).')
add(c1='M-01-8',host=H,dir='DOWNSTREAM',typ='HANDOVER',tgt='DEL-10-03',kind='MIRROR',cp='DEP-10-03-011',disp='KEEP',route='EXTRACT',ev=('C',r'DEL-10-03 account'),stmt='Supplies shared-type and placement questions for the shared commitments account (C §8 map: "DEL-10-03 account").')
add(c1='M-01-3-pkg',host=H,kind='PKG',row='DEP-03-01-022',disp='KEEP',route='EXTRACT',ev=('SOW',r'PKG-02'),stmt='Package row DOWNSTREAM → PKG-02 stays while the SoW names the package; the deliverable rows M-01-3/M-01-4 carry its content.',why='C1 proposed retiring it. Retirement is a register-owner choice with no DAG effect. Extraction retires it only if P1 changes the SoW reference.')
add(c1='DEP-03-01-024',host=H,kind='EDIT',row='DEP-03-01-024',disp='AMEND',route='EXTRACT',ev=('SOW',r'OI-001'),stmt='Notes: OI-001/OI-002 ruled by DECISION-1 D2/D3 (App/shared); adopted classes carried in ACT §6; operation-specific additions stay open (OI-021).')
add(c1='N-B1',host=H,dir='UPSTREAM',typ='INTERFACE',tgt='DEL-04-03',kind='NEWREP',arc='N-11',disp='KEEP',route='EXTRACT',ev=('C',r'^\| Human-act evidence'),stmt='Receives the DEL-04-03 §6.1 act field set and §7 lapse vocabulary carried in read-result standing (C §6.2).')
add(c1='N-01-mir',host=H,dir='DOWNSTREAM',typ='HANDOVER',tgt='DEL-04-02',kind='NEWMIR',arc='N-01',disp='KEEP',route='EXTRACT',ev=('C',r'^- Receivers:'),stmt='Supplies standing facets (C §6) to the autonomy and standing exchange (C Receivers: "DEL-04-02 (standing facets — unregistered join").',why='C1-B marked it an optional supplier mirror; C names the receiver explicitly.')
add(c1='N-10-mir',host=H,dir='DOWNSTREAM',typ='HANDOVER',tgt='DEL-04-03',kind='NEWMIR',arc='N-10',disp='KEEP',route='EXTRACT',ev=('C',r'^- Receivers:'),stmt='Supplies content identities, method designation and read basis (C Receivers: "DEL-04-03 … unregistered join").',why='Optional supplier mirror; C names the receiver explicitly.')

# ---------------- C1-B: DEL-03-02 (P) ----------------
H='DEL-03-02'
add(c1='M-02-1',host=H,dir='DOWNSTREAM',typ='INTERFACE',tgt='DEL-03-01',kind='MIRROR',cp='DEP-03-01-026',disp='KEEP',route='EXTRACT',ev=('P',r'^\| Provide to \| DEL-03-01 \|'),stmt='Supplies the M3-CP return (P §11) to the catalog contract (P §13).')
add(c1='M-02-2',host=H,dir='DOWNSTREAM',typ='HANDOVER',tgt='DEL-05-01',kind='MIRROR',cp='DEP-05-01-015',disp='KEEP',route='EXTRACT',ev=('P',r'^\| Provide to \| DEL-05-01 \|'),stmt='Supplies §9 unchanged, observer-attributed outcome unknown, retry identity and precedence, per-dispatch origin, seat role, grant in force and constraint (P §13).')
add(c1='M-02-3',host=H,dir='DOWNSTREAM',typ='HANDOVER',tgt='DEL-05-02',kind='MIRROR',cp='DEP-05-02-007',disp='KEEP',route='EXTRACT',ev=('P',r'^\| Provide to \| DEL-05-02 \|'),stmt='Supplies per-item dispositions with actors and annotations, lineage, stale indication, item-left events and "accept" wording (P §13).')
add(c1='M-02-4',host=H,dir='DOWNSTREAM',typ='HANDOVER',tgt='DEL-10-03',kind='MIRROR',cp='DEP-10-03-012',disp='DROP',route='NONE',ev=None,why='Observed-only mirror; P does not name DEL-10-03. Arc represented by DEP-10-03-012 (consumer UPSTREAM). DEL-10-03 is outside D1.')
add(c1='DEP-03-02-017',host=H,kind='EDIT',row='DEP-03-02-017',disp='AMEND',route='EXTRACT',ev=('SOW',r'OI-001'),stmt='Notes: replace "REQ-012 and TBD-001 preserve OI-001/OI-002…" with DECISION-1 D2/D3 and residual OI-021.')
add(c1='NORM-03-02',host=H,kind='NORM',row='DEP-03-02-016…026',disp='DEFER',route='DECLARE',ev=None,why='SatisfactionStatus TBD vs PENDING is a register-owner convention. Both values are valid, no row is SATISFIED, and DAG-002 is unaffected. Owner item O-6.')
add(c1='N-B2',host=H,dir='UPSTREAM',typ='INTERFACE',tgt='DEL-04-02',kind='NEWREP',arc='N-05',disp='KEEP',route='EXTRACT',ev=('P',r'^\| Expect from \| DEL-04-02 \|'),stmt='Receives grant display states incl. effective (policy default), grant value and scope per class and settings version identities (P §13).')
add(c1='N-B3',host=H,dir='UPSTREAM',typ='INTERFACE',tgt='DEL-02-01',kind='NEWREP',arc='N-B3',disp='KEEP',route='EXTRACT',ev=('P',r'^\| Expect from \| DEL-02-01 \|'),stmt='Receives workflow identity, checkpoint declarations (required act, subject class, reached-when) and the §4.3.7 item rule (P §13).')
add(c1='N-18/N-21-mir',host=H,dir='DOWNSTREAM',typ='HANDOVER',tgt='DEL-02-01',kind='NEWMIR',arc='N-18',disp='KEEP',route='EXTRACT',ev=('P',r'^\| Provide to \| DEL-02-01 / DEL-02-03'),stmt='Supplies governing constraint semantics and not permitted (governance phase), per-item dispositions, item-left events, all-items-decided and resulting objects (P §13).',why='Supplier side of N-18, concurred by C1-B; P §13 names the receiver.')
add(c1='N-21-mir',host=H,dir='DOWNSTREAM',typ='HANDOVER',tgt='DEL-02-03',kind='NEWMIR',arc='N-21',disp='KEEP',route='EXTRACT',ev=('P',r'^\| Provide to \| DEL-02-01 / DEL-02-03'),stmt='As above, to execution compatibility (P §13).',why='Supplier side of N-21; P §13 names the receiver.')

# ---------------- C1-B: DEL-03-03 (ADAPTER) ----------------
H='DEL-03-03'
add(c1='M-03-1',host=H,dir='DOWNSTREAM',typ='HANDOVER',tgt='DEL-03-04',kind='MIRROR',cp='DEP-03-04-007',disp='KEEP',route='EXTRACT',ev=('ADAPTER',r'^\| Provide to \| DEL-03-04 \|'),stmt='Supplies §§1–9 for the guide\'s "Optional external catalog access" row (ADAPTER §11).')
add(c1='DEP-03-03-008',host=H,kind='EDIT',row='DEP-03-03-008',disp='AMEND',route='EXTRACT',ev=('SOW',r'OI-001'),stmt='Notes: DECISION-1 D2/D3 pointer, as DEP-03-02-017; residual OI-021.')
for (c,t,a,pat,st) in [('N-B4','DEL-01-01','N-B4',r'^\| Expect from \| DEL-01-01/HOSTING','Receives supplier surfaces at 0.158.0 (§3.5), A14 origins (R7–R9) and native delivery (H6) from HOSTING and the pin record (ADAPTER §11).'),
                       ('N-B5','DEL-04-02','N-06',r'^\| Expect from \| DEL-04-02/AS','Receives grant display states incl. effective (policy default) and settings references (ADAPTER §11).'),
                       ('N-B6','DEL-02-01','N-20',r'^\| Expect from \| DEL-02-01 / DEL-02-03','Receives checkpoint declarations (WD §4.3, governed flag) and derived constraints (WD §4.2.2) (ADAPTER §11).'),
                       ('N-B7','DEL-02-03','N-27',r'^\| Expect from \| DEL-02-01 / DEL-02-03','Receives Phase-1 guidance and recording (EXEC §2.1) and, for the governance phase, the hold machine and per-checkpoint hold support (EXEC §2.2, §3.6) (ADAPTER §11).')]:
    add(c1=c,host=H,dir='UPSTREAM',typ='INTERFACE',tgt=t,kind='NEWREP',arc=a,disp='KEEP' if c!='N-B7' else 'AMEND',route='EXTRACT',ev=('ADAPTER',pat),stmt=st,why=('Amended for R8-1 phasing.' if c=='N-B7' else None))
add(c1='N-B8',host=H,dir='UPSTREAM',typ='INTERFACE',tgt='DEL-04-03',kind='NEWREP',arc='N-B8',disp='DROP',route='NONE',ev=None,why='C1-B conditional. ADAPTER-v0.4 §11 has no "Expect from DEL-04-03" row. RS is read "for joins only" to name where the adapter\'s evidence lands (the record destination). Dropped for the same reason as N-12; N-14 carries the relationship.')
add(c1='N-14-mir',host=H,dir='DOWNSTREAM',typ='HANDOVER',tgt='DEL-04-03',kind='NEWMIR',arc='N-14',disp='KEEP',route='EXTRACT',ev=('ADAPTER',r'^\| Provide to \| DEL-04-03 \|'),stmt='Supplies external dispatch entries for R7, faithfully recorded acts for R9, evidence limits for R11, model destination per turn and A14 observations for R13 (ADAPTER §11).',why='Supplier side of N-14 (C1-B concurred); ADAPTER §11 names it.')
add(c1='N-24-mir',host=H,dir='DOWNSTREAM',typ='HANDOVER',tgt='DEL-02-03',kind='NEWMIR',arc='N-24',disp='KEEP',route='EXTRACT',ev=('ADAPTER',r'^\| Provide to \| DEL-02-03 \|'),stmt='Supplies external-channel observations (§7.7), hold-support inputs (governance phase) and required-tool outcomes on X (ADAPTER §11).',why='Supplier side of N-24; ADAPTER §11 names it.')

# ---------------- C1-B: DEL-03-04 (GUIDE) ----------------
H='DEL-03-04'
for (c,t,cp) in [('M-04-02-04','DEL-02-04','DEP-03-04-010'),('M-04-07-01','DEL-07-01','DEP-03-04-016'),('M-04-07-02','DEL-07-02','DEP-03-04-017'),('M-04-08-01','DEL-08-01','DEP-03-04-018'),('M-04-08-02','DEL-08-02','DEP-03-04-019')]:
    add(c1=c,host=t,dir='DOWNSTREAM',typ='HANDOVER',tgt='DEL-03-04',kind='MIRROR',cp=cp,disp='DEFER',route='NONE',ev=None,why='Optional supplier-side mirror in a register outside the first increment (D1); these suppliers have no Design file. Same treatment as C1-A "noted but not proposed (D1)".')
add(c1='M-04-05-01',host='DEL-05-01',dir='DOWNSTREAM',typ='HANDOVER',tgt='DEL-03-04',kind='MIRROR',cp='DEP-03-04-014',disp='DROP',route='NONE',ev=None,why='Optional mirror. LOOP names DEL-03-04 only in a version citation. C1-C counted supplier mirrors for DEL-05-01 as optional and not proposed.')
add(c1='M-04-05-02',host='DEL-05-02',dir='DOWNSTREAM',typ='HANDOVER',tgt='DEL-03-04',kind='MIRROR',cp='DEP-03-04-015',disp='DROP',route='NONE',ev=None,why='Optional mirror. PANEL names DEL-03-04 only in a version citation (C1-C: optional, not counted).')
add(c1='DEP-03-04-011',host=H,kind='EDIT',row='DEP-03-04-011',disp='AMEND',route='EXTRACT',ev=('SOW',r'OI-001'),stmt='Notes: replace "OI-001 is needed before operation-policy production contracts; OI-002 before permission-policy implementation" with DECISION-1 D2/D3 and the OI-021 residue.')
add(c1='N-B9',host=H,dir='UPSTREAM',typ='INTERFACE',tgt='DEL-01-01',kind='NEWREP',arc='N-B9',disp='KEEP',route='EXTRACT',ev=('GUIDE',r'^\| HOSTING-v0.6 and SPIKE-v0.1'),stmt='Receives the App\'s Codex boundary facts (HOSTING §6.7, §6.8, §8.2, §8.3; SPIKE) for rows 5, 6, 8 and 9 (GUIDE §2.11).',why='Pairs with P1 SoW correction S-04-6.')
add(c1='N-B10',host=H,dir='UPSTREAM',typ='INTERFACE',tgt='DEL-09-06',kind='NEWREP',arc='N-B10',disp='KEEP',route='EXTRACT',ev=('GUIDE',r'^\| CA-v0.4 \(DEL-09-06\)'),stmt='Receives the CA step map and staging, RELAY-v0.3 question identities and the SWBPIPE answers held in DEL-09-06 (GUIDE §2.11: host column of every row).')
add(c1='N-B11',host=H,dir='UPSTREAM',typ='INTERFACE',tgt='DEL-09-09',kind='NEWREP',arc='N-B11',disp='KEEP',route='EXTRACT',ev=('GUIDE',r'^\| XT-v0.4 \(DEL-09-09\)'),stmt='Receives the V4-EXM-25 suite, extension trace and OI-003 disposition record for rows 1 and 9 (GUIDE §2.11).')

# ---------------- C1-B: DEL-01-01 (HOSTING) ----------------
H='DEL-01-01'
add(c1='M-11-1',host=H,dir='DOWNSTREAM',typ='HANDOVER',tgt='DEL-02-04',kind='MIRROR',cp='DEP-02-04-010',disp='KEEP',route='EXTRACT',ev=('HOSTING',r'^\| S-6 additive guidance'),stmt='Supplies carriage of additive guidance through the supplier\'s supported inputs and per-thread/turn content-identity evidence (HOSTING §8 seam S-6).')
for (c,t,cp) in [('M-11-2','DEL-06-01','DEP-06-01-013'),('M-11-3','DEL-09-01','DEP-09-01-019'),('M-11-4','DEL-09-02','DEP-09-02-009')]:
    add(c1=c,host=H,dir='DOWNSTREAM',typ='HANDOVER',tgt=t,kind='MIRROR',cp=cp,disp='DROP',route='NONE',ev=None,why='Observed-only optional mirror. Neither HOSTING nor the DEL-01-01 SoW names this receiver, so a CONSERVATIVE extraction would not emit it. The arc is represented by the consumer\'s UPSTREAM row, and the target is outside D1.')
add(c1='DEP-01-01-017',host=H,kind='EDIT',row='DEP-01-01-017',disp='AMEND',route='EXTRACT',ev=('SOW',r'OI-012'),stmt='Notes: "0.158.0 selected as the definition/generation pin by DECISION-1 D4; re-examined before implementation; not qualification." SatisfactionStatus unchanged.')
add(c1='DEP-01-01-018',host=H,kind='EDIT',row='DEP-01-01-018',disp='AMEND',route='EXTRACT',ev=('SOW',r'DEP-005'),stmt='Notes: "generated-type and handshake facts at 0.158.0 recorded (PIN_SPIKE-v0.1); no candidate qualification."')

# ---------------- C1-C: DEL-05-01 (LOOP) ----------------
H='DEL-05-01'
add(c1='R5-1-1',host=H,dir='UPSTREAM',typ='INTERFACE',tgt='DEL-04-02',kind='NEWREP',arc='N-03',disp='KEEP',route='EXTRACT',ev=('LOOP',r'^\| Grant states incl\. policy default'),stmt='Receive the adopted grant display states and settings references carried as the grant in force on each dispatch and in run evidence; this deliverable does not define them (LOOP §10.3).')
add(c1='R5-1-2',host=H,dir='UPSTREAM',typ='INTERFACE',tgt='DEL-01-05',kind='MIRROR',cp='DEP-01-05-014',disp='DROP',route='NONE',ev=None,why='LOOP-v0.6 does not name DEL-01-05 (C1-C: "LOOP-v0.5 does not yet consume it"). A consumer row would also replace DAG-001\'s representative with an unevidenced row. Record in DEL-05-01 Run Notes why no consumer row is kept.')
add(c1='R5-1-3',host=H,dir='DOWNSTREAM',typ='HANDOVER',tgt='EXT:DEP-001-RELAY',kind='EXT',disp='AMEND',route='EXTRACT',ev=('LOOP',r'SQ-29'),stmt='External SWBPIPE owner — loop receiving questions relayed through DEL-09-06 RELAY-v0.3; answered 2026-09-28 (SWBPIPE has no embedded loop; none selected); host joins deferred (DECISION-3).',why='C1 wording said "prepared"; the questions are now relayed and answered.')
add(c1='R5-1-5',host=H,kind='EDIT',row='DEP-05-01-024',disp='AMEND',route='EXTRACT',ev=('LOOP',r'DEP-05-01-024'),stmt='Notes: asked as RELAY SQ-29; answered 2026-09-28 (no embedded loop, none selected); the model interface stays UNKNOWN and PENDING.')
add(c1='R8-LOOP-1',host=H,dir='UPSTREAM',typ='CONSTRAINT',tgt='EXT:DECISION-5-OPEN',kind='EXT',disp='ADD',route='EXTRACT',ev=('LOOP',r'N-OPEN-4'),stmt='Owner — how a category switch combines with its named entries (LOOP N-OPEN-4) and the accepted-basis revision of V4-HOST-02 per DECISION-5; point of need before §5.1.1 implementation.',why='R8-13 (DECISION-5). Non-topological.')

# ---------------- C1-C: DEL-05-02 (PANEL) ----------------
H='DEL-05-02'
add(c1='R5-2-1',host=H,dir='UPSTREAM',typ='PREREQUISITE',tgt='DEL-04-02',kind='NEWREP',arc='N-04',disp='KEEP',route='EXTRACT',ev=('PANEL',r'^The grant is shown per class and scope, from DEL-04-02'),stmt='Panel receiving requirements consume the checked autonomy-grant display states, active scope and network-destination grants supplied by DEL-04-02 (PANEL §3.6, ND-5).')
add(c1='R5-2-2',host=H,dir='UPSTREAM',typ='PREREQUISITE',tgt='DEL-02-03',kind='NEWREP',arc='N-25',disp='AMEND',route='EXTRACT',ev=('PANEL',r'^- \*\*Phases \(R8-1; EXEC-v0.4'),stmt='Panel receiving requirements consume the Phase-1 statement and compatibility report meanings (EXEC §2.1, §3.3 CR-8/CR-9) and, for the governance phase, the hold-support values and hold-machine meanings (EXEC §2.2, §3.6, §4).',why='The condition is removed. R4 re-pointed PANEL W-5 to EXEC and R8 made PANEL read EXEC §2.1–§2.2 directly, so the "via DEL-05-01" alternative no longer describes the text.')
add(c1='R5-2-3',host=H,kind='EDIT',row='DEP-05-02-014;DEP-05-02-015',disp='AMEND',route='EXTRACT',ev=('SOW',r'OI-001'),stmt='Statement/Notes point to DECISION-1 D2 and D3; residual OI-021 and host adoption (DEP-001). Status ACTIVE; not SATISFIED.')
add(c1='R5-2-4',host=H,kind='EDIT',row='DEP-05-02-016',disp='KEEP',route='EXTRACT',ev=('SOW',r'OQ-11'),stmt='Notes: "same matter as OI-021 (Open_Issues.csv)"; TargetRefID may be retargeted to OI-021 with OQ-11 kept as source.')
add(c1='R5-2-5',host=H,kind='EDIT',row='DEP-05-02-011',disp='AMEND',route='EXTRACT',ev=('SOW',r'DEP-001'),stmt='Statement names capture-evidence reference (SQ-01), constraint handling (SQ-02) and host-loop holds (governance phase); SWBPIPE answered 2026-09-28 (none offered); host joins deferred.',why='C1 wording predates the answers and R8-1.')
add(c1='R5-2-6',host=H,kind='EDIT',row='DEP-05-02-018',disp='AMEND',route='EXTRACT',ev=('PANEL',r'DEP-05-02-018'),stmt='Notes: questions consolidated in RELAY-v0.3 (SQ-02, SQ-01, SQ-22, SQ-23/SQ-10, SQ-21, SQ-18 (a), SQ-24, SQ-05 (c)/(e), SQ-20); relayed and answered 2026-09-28.',why='"prepared, not delivered" is superseded.')

# ---------------- C1-C: DEL-09-06 (CA) ----------------
H='DEL-09-06'
for (c,t,a,pat,st) in [('R9-6-1a','DEL-02-01','N-19',r'^\| P, AS, RS, LOOP, PANEL, WD','Receives the workflow declaration (WD §4.3.0, §4.3.1, WR-1…WR-11) and WD-EX examples cited per step (CA §3.1, §4, §11.1).'),
                       ('R9-6-1b','DEL-02-02','N-C1',r'^\| DEL-02-02 \| Registration','Receives registration and drafts for the workflow round trip (CA §11.1; W14-01, W14-09); outside D1.'),
                       ('R9-6-2a','DEL-03-01','N-C2',r'^\| C, ACT \|','Receives catalog, read-basis and evidence-label meanings cited per step (CA §2.3, §7.1, §11.1).'),
                       ('R9-6-2b','DEL-03-02','N-C3',r'^\| P, AS, RS, LOOP, PANEL, WD','Receives proposal lifecycle and outcome meanings cited per step (CA-2, CA-4, CA-5; §11.1).'),
                       ('R9-6-2c','DEL-03-03','N-C4',r'^\| ADAPTER \|','Receives channel states, model destination, carriage assurance and the XF inventory (CA §11.1).'),
                       ('R9-6-3a','DEL-04-01','N-28',r'^\| C, ACT \|','Receives act and policy meanings cited per step (CA S-8, CA-2, CA-H; §11.1).'),
                       ('R9-6-3b','DEL-04-02','N-08',r'^\| P, AS, RS, LOOP, PANEL, WD','Receives grant display and standing meanings (CA-0, CA-H, CA-R; §11.1).'),
                       ('R9-6-3c','DEL-01-01','N-C5',r'^\| P, AS, RS, LOOP, PANEL, WD','Receives HOSTING supplied-guidance and model-destination facts (CA §4 supplied link, W14-08; §11.1).')]:
    add(c1=c,host=H,dir='UPSTREAM',typ='INTERFACE',tgt=t,kind='NEWREP',arc=a,disp='KEEP',route='EXTRACT',ev=('CA',pat),stmt=st)
add(c1='R9-6-1-pkg',host=H,kind='PKG',row='DEP-09-06-012;DEP-09-06-014',disp='KEEP',route='EXTRACT',ev=('SOW',r'PKG-0[23]'),stmt='Package rows to PKG-02 and PKG-03 stay ACTIVE (non-topological) while the SoW names the packages. The deliverable rows above carry their content.')
add(c1='R9-6-4',host=H,dir='UPSTREAM',typ='INTERFACE',tgt='DEL-09-01',kind='MIRROR',cp='DEP-09-01-024',disp='KEEP',route='EXTRACT',ev=('CA',r'DEL-09-01'),stmt='Receives reusable examination support and evidence interfaces (CA §5, §7).')
add(c1='R9-6-5',host=H,dir='DOWNSTREAM',typ='HANDOVER',tgt='DEL-09-07',kind='MIRROR',cp='DEP-09-07-011',disp='KEEP',route='EXTRACT',ev=('CA',r'^\| DEL-09-07 \| Step map'),stmt='Supplies the step map (§2.3) for CA/E, staging (§6) and the evidence ladder (§7) to local host qualification (CA §11.2).')
add(c1='R9-6-6',host=H,kind='EDIT',row='DEP-09-06-022;DEP-09-06-023',disp='AMEND',route='EXTRACT',ev=('SOW',r'OI-001'),stmt='Point to DECISION-1 D2/D3 with the OI-021 and DEP-001 residual; not SATISFIED.')
add(c1='R9-6-7',host=H,dir='DOWNSTREAM',typ='HANDOVER',tgt='EXT:DEP-001-RELAY',kind='EXT',disp='AMEND',route='EXTRACT',ev=('SOW',r'OUT-004'),stmt='External SWBPIPE owner — human-relayed question set (RELAY_QUESTIONS_SWBPIPE.md); relayed and answered 2026-09-28 (RELAY_ANSWERS_SWBPIPE.md); answers are not commitments (DECISION-3).',why='C1 wording predates delivery and answers.')

# ---------------- C1-C: DEL-09-09 (XT) ----------------
H='DEL-09-09'
add(c1='R9-9-1',host=H,dir='UPSTREAM',typ='PREREQUISITE',tgt='DEL-05-01',kind='NEWREP',arc='N-C6',disp='KEEP',route='EXTRACT',ev=('XT',r'^\| IN-22 \|'),stmt='Embedded-surface receiving for the V4-EXM-24 three-surface trace: App-side loop receiving (LOOP-v0.6) (XT IN-22; CMP-03).')
add(c1='R9-9-2',host=H,dir='UPSTREAM',typ='PREREQUISITE',tgt='DEL-04-02',kind='NEWREP',arc='N-09',disp='KEEP',route='EXTRACT',ev=('XT',r'^\| IN-29 \|'),stmt='Grant display and grant states (AS-v0.6) (XT IN-29; CMP-07; XC-10).')
add(c1='R9-9-3',host=H,dir='UPSTREAM',typ='PREREQUISITE',tgt='DEL-02-03',kind='NEWREP',arc='N-26',disp='AMEND',route='EXTRACT',ev=('XT',r'^\| TS-0 Baseline'),stmt='Compatibility reports per surface (EXEC EV-5, CR-7) for TS-0/CMP-01, and, for the governance phase only, hold support on X (XT IN-25).',why='Amended for R8-1: IN-25 is governance phase; the Phase-1 input is the compatibility report per surface.')
add(c1='R9-9-4',host=H,dir='DOWNSTREAM',typ='HANDOVER',tgt='DEL-03-01',kind='MIRROR',cp='DEP-03-01-030',disp='KEEP',route='EXTRACT',ev=('XT',r'^- Receivers:'),stmt='Supplies trace and work evidence before any extension claim (XT Receivers; CASE-002 M4-X).')
add(c1='R9-9-5',host=H,kind='EDIT',row='DEP-09-09-014',disp='AMEND',route='EXTRACT',ev=('XT',r'^\| IN-16 \|'),stmt='Statement adds capture-evidence reference (SQ-01), constraint handling (SQ-02) and the A13 enablement facility (SQ-28); Notes: answered 2026-09-28 (none offered); host joins deferred (DECISION-3).',why='C1 wording said "prepared, not delivered".')
add(c1='R9-9-6',host=H,kind='EDIT',row='DEP-09-09-015',disp='AMEND',route='EXTRACT',ev=('XT',r'^\| IN-15 \|'),stmt='Statement: enable access through the host\'s enablement facility with a capture-evidence reference; App-side configuration is never A13 evidence. SWBPIPE has no facility (SQ-28), so the channel stays not enabled.')

# ---------------- Found in refresh: DEL-02-03 → DEL-01-04 ----------------
add(c1='X-1',host='DEL-02-03',dir='UPSTREAM',typ='INTERFACE',tgt='DEL-01-04',kind='NEWREP',arc='X-1',disp='ADD',route='EXTRACT',ev=('EXEC',r'^\| DEL-01-04 \(later, D1\)'),stmt='Receives the App act control (CAP-2) and person identity from the later App act-control construction (EXEC §9.1; §5); outside D1.',why='Not in C1\'s 40 arcs. C1-A SC-02-03-4 adds "DEL-01-04 (later undertaking) constructs the App act control" to CLM-002, and DAG-001 extraction read CLM-002 names as UPSTREAM inputs, so applying SC-02-03-4 produces this arc. EXEC §9.1 corroborates. Both endpoints are in SCC-002.')
