from pathlib import Path
import json,hashlib,subprocess,socket
repo=Path(subprocess.check_output(['git','rev-parse','--show-toplevel'],text=True).strip());app=repo/'projects/chirality-app-dev';run=app/'execution/_Coordination/AgentRuns/APP_SHELL_RESUME_2026-09-06';o=run/'pkg09';d=app/'execution/PKG-09_Validation_Packaging_Security_and_Release/1_Working/DEL-09-04_macOS_DMG_Packaging_and_Instruction_Root_Integrity'
status=d/'_STATUS.md';memory=d/'MEMORY.md';(o/'STATUS.preimage.md').write_bytes(status.read_bytes());(o/'MEMORY.preimage.md').write_bytes(memory.read_bytes())
item='''- **DEL-09-04-D124** — Exact owner-authorized Electron compiler declaration repair is implemented and independently reviewed locally; parent final-union and scoped Git closeout remain.\n  Authority: D-APP-124 ruling 2026-09-06; direct current-execution approval, no additional main-observability gate for this exact patch.\n  Write locus: `frontend/tsconfig.electron.json` only, exact postimage `522b114f541f6b4882404069f6b4ca5553f887635948df972c07bbbed849f5b0`, plus this deliverable's status, MEMORY and run records. Eight Runtime-source aliases removed; no other compiler flags, Runtime sources, native startup repair, lifecycle or dependency change.\n  Checks: fresh read-only software-code-review PASS; typecheck, Vitest (1,774 passed / 4 skipped), build, APP-HOLD, harness self-check and pytest (379 passed) PASS. Local premerge remains FAIL at HTTP 503 without Runtime binding; service ready and cleanup passed, PR-CI rerun remains owed. Historical native startup failure is unchanged and outside this patch.\n  Return: `_run_records/D_APP_124_COMPILER_DECLARATION_REPAIR_2026-09-06.md`; run evidence `execution/_Coordination/AgentRuns/APP_SHELL_RESUME_2026-09-06/pkg09/`. A1 re-stage and fresh owner execution remain necessary for future login-proof claims.\n  Removed when: scoped integration and parent closeout are recorded; this line grants no wider repair or publication.\n\n'''
s=status.read_text();assert 'DEL-09-04-D124' not in s;s=s.replace('**Last Updated:** 2026-09-04','**Last Updated:** 2026-09-06',1).replace('## Remaining\n\n','## Remaining\n\n'+item,1).replace('## History\n','## History\n- 2026-09-06 - D-APP-124 exact compiler repair applied locally and fresh source review/checks passed, except the independently preserved local premerge Runtime-binding failure. Scoped integration remains pending; all neighboring Remaining items, lifecycle, Checking Approval SHA and dependencies are unchanged. See `_run_records/D_APP_124_COMPILER_DECLARATION_REPAIR_2026-09-06.md`.\n',1);status.write_text(s)
memory.write_text(memory.read_text()+'\n- 2026-09-06 — D-APP-124 removes only the eight Runtime-source aliases from Electron typechecking so current built public declarations are consumed. Exact source review PASS, both compiler checks, 1,774 Vitest tests (4 skipped), build and harness checks PASS. Local premerge still fails HTTP 503 without Runtime binding; native startup failure remains historical/unrepaired. Parent final-union/Git closeout and PR-CI remain pending, with no publication or lifecycle act. See `_run_records/D_APP_124_COMPILER_DECLARATION_REPAIR_2026-09-06.md`.\n')
record='''# D-APP-124 bounded compiler repair — 2026-09-06

WORKING_ITEMS /root/resume_pkg09, PKG-09 / DEL-09-04. Owner approval is recorded in D-APP-124 and run OWNER_STEER_v4.md. Parent release after coordination recording authorized the exact current repair. The run uses native delegation with instruction-asserted role; exact serving model/provider/token occupancy are not exposed.

## Applied scope

Only frontend/tsconfig.electron.json changed: preimage 8b8bfb49b7e9361cdbbcd94dbc4df31ccb16f3dda24c37b0859ef48639de23ec; postimage 522b114f541f6b4882404069f6b4ca5553f887635948df972c07bbbed849f5b0; approved patch 6497d6c374755b793fd041e360b280ebb1b6ce9deb18cc0e7d2426113f001a2d. Eight Runtime-source aliases removed; strict/skipLibCheck/baseUrl/include and all other flags preserved. No Runtime source, source suppression, native repair or dependency schema change. Existing seven App source files match their frozen identities.

## Evidence and limitations

Evidence is derivative under execution/_Coordination/AgentRuns/APP_SHELL_RESUME_2026-09-06/pkg09/. The owner and accepted live authority remain upstream; no snapshot/pointer/decomposition truth is replaced. Own APP-HOLD ALLOW and repeated git fetch confirmed origin/main=HEAD ec491aee1870a2a6a8eb2faf2919d4d5db5124b4 before Runtime reliance. Parent CHANGE sync-v2 and runtime-preparation-v1 bind current declarations; no Runtime rewrite/rebuild occurred in this manager. compiler-resolution.stdout shows public dist declaration resolution, exit0.

Fresh TASK config_review returned PASS over 100% of the config diff, no actionable findings (REVIEW_02_RETURN.md). Initial FAILED_INPUTS from missing runtime instruction-root declaration is retained in REVIEW_01_RETURN.md. Parent supplied explicit native launch configuration in REVIEW_AMENDMENT_v2.md; no inherited environment observation was fabricated. Source review had not begun before that correction. Review returned while full checks were manager-owned; manager independently read their final results below.

REGISTERED_CHECKS.json: both typechecks PASS; Vitest 1,774 passed / 4 skipped across 179 passing files / 1 skipped; build PASS; APP-HOLD integrity PASS; harness self-check PASS; pytest 379 passed. PREMERGE_CHECK.json: actual FAIL, HTTP503 on session routes without Runtime binding, service READY and stopped_after_run=true. The registered environment has no Runtime binding; this is not a compiler failure and PR-CI rerun is still owed. Historical 60-diagnostic baseline and native ERR_PACKAGE_PATH_NOT_EXPORTED remain in PKG02 final-validation-v1; neither is erased or relabelled. No native rerun or full-app acceptance is claimed.

BUILD_ASSET_COMPARISON.json binds 58 outputs before/after: 54 common assets equal, two Next build-ID manifest paths change, main.js and map differ. Retained PKG02 native-proof compiled/main.js matches the before hash. Full EMITTED_MAIN_DELTA.diff removes only a redundant inner strict directive; both complete bundles begin with strict mode. No executable import/export/payload change appears. The exact cause of this emission difference is not independently reproduced, and old map bytes were not retained for structural comparison. Renderer byte equality and no UI source change make new screenshots unnecessary for this configuration repair; this does not prove native functionality. D-APP-36 earlier shell visual proof is not expanded.

A1: frontend mutation requires a newly staged exact revision/package and fresh owner execution for any future login-proof claim. R20 historical evidence remains historical. No lifecycle, Checking Approval SHA, dependency satisfaction, release, signing, notarization, deployment or publication act.

## Handoff

Bounded compiler repair/source-review PASS. Whole-run acceptance remains pending parent union review, native proof blocker disposition and local-premerge/PR-CI obligations. DEL-09-04 remains IN_PROGRESS; D124 item retained pending scoped integration. No other Remaining item changed. No push/PR/merge authorized. Rerun checks if relevant source, config, Runtime declarations or dependency versions change; synchronize from origin/main before Runtime reliance. Run manifest provides output hashes and scripts for reproduction.
'''
(d/'_run_records/D_APP_124_COMPILER_DECLARATION_REPAIR_2026-09-06.md').write_text(record)
(o/'DELIVERABLE_DIFF.diff').write_bytes(subprocess.check_output(['git','diff','--',str(status),str(memory)]))
pre=json.loads((o/'PREMERGE_CHECK.json').read_text())['results'][0];port=pre['service']['port']
with socket.socket() as sock: cleanup={'port':port,'connect_ex':sock.connect_ex(('127.0.0.1',port)),'reported_stopped_after_run':pre['service']['stopped_after_run']}
(o/'PREMERGE_CLEANUP_CHECK.json').write_text(json.dumps(cleanup,indent=2)+'\n')
print('metadata applied; cleanup',cleanup)
