from pathlib import Path
import json,csv,hashlib,datetime
R=Path('/Users/ryan/.codex/worktrees/341e/chirality');RUN=R/'execution/_Coordination/AgentRuns/ROOT_RUNTIME_MIGRATION_GATE5_2026-09-06';O=R/'execution/_Evaluation/DecompCoverage/SCA005_MIGRATION_POST';O.mkdir(parents=True,exist_ok=False);x=json.loads((RUN/'AUDIT/root_measured.json').read_text());assert not x['failures'];A=R/'execution/_ScopeChange/SCA-005_2026-09-06_APPLICATION'
def write(n,s):(O/n).write_text(s.rstrip()+'\n')
def csvw(n,h,rs):
 with(O/n).open('w',newline='') as f:w=csv.writer(f,lineterminator='\n');w.writerow(h);w.writerows(rs)
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
jp=RUN/'INTEGRATION/APPLICATOR_APPLY/journal.json';j=json.loads(jp.read_text());assert sha(jp)=='bb38d99aac91bd6b7a7808b4760e1781b431624e0bb0754f4b08cb66d18fa203' and j['state']=='APPLIED' and len(j['entries'])==53
parity=json.loads((RUN/'INTEGRATION/LIVE_64_POSTIMAGE_PARITY.json').read_text());assert len(parity['rows'])==64 and all(sha(R/r['path'])==r['expected'] for r in parity['rows'])
for p in [jp,RUN/'INTEGRATION/LIVE_64_POSTIMAGE_PARITY.json',RUN/'INTEGRATION/GOVERNANCE_STATE_APPLIED_RECORDED.json',R/'execution/_ScopeChange/_LATEST.md']:x['inputs'][str(p.relative_to(R))]=sha(p)
handoff=(A/'Handoff_State.md').read_text();assert 'APPROVED_AMENDMENT_APPLIED_PENDING_OWNER_CONFIRMATION' in handoff and 'Gate5 is null' in handoff;write('Handoff_Observed.md',handoff)
write('Brief.md','''# Root historical post-application audit brief

Actual dispatch: HELP_HUMAN /root, supplemented by SCOPE_CHANGE INTEGRATION/ROOT_POST_AUDIT_BRIEF.md. Dedicated Agent2 AUDIT_DECOMP, delegated-harness-native, instruction-asserted; no child delegation. GPT-6, exact serving ID unavailable; Agent0 role is not mechanically enforced.

Approved write scope is this SCA005_MIGRATION_POST snapshot and newrun AUDIT evidence. The supplemental brief's differently named output folder was superseded by the explicit approved Gate4 EVIDENCE_OUTPUT_SCOPES path; parent notified. User reserves all _LATEST moves, overriding ordinary audit publication step.

Scope ALL, Root execution/_Decomposition/Chirality_Root_SOFTWARE_DECOMP_v1_0.md, SOFTWARE historical/governance mode. Expected source is approved Gate3 V3 seal547d1f3369e71aa96d1b61561f6b1603b978016c7335fca39f86df97ddd73fc3; Gate4 seal917656f3a828d7e05e2feaf22e14394f1f6dc9fbb26bb99760b633e0ceb17efd; actual owner acts published at8209bc54e0d133b19437c93b184cd50ba3d43489.

Parent released actual post-state inspection only after completed applicator journal and64postimage parity. Verify6historical parents/53RETIRED children/0activeRootproduct/46controls/7qualifiedruntime successors/104source rows, exact postimages, no orphans/duplicates/crossauthority, preserved source histories and current handoff posture. Read sibling memories before status. No source, tool, Git, status, pointer, activation or owner-confirmation writes. This is derivative coverage evidence, not final Gate5 acceptance.''')
write('Decomp_Coverage_Report.md','''# Root historical-mode post-application coverage

**Applied structural coverage PASS:500 independent checks, zero failures;64/64 canon/source/status postimage hashes independently rechecked. Overall WARNINGS** for the preserved successor-owned production-contract debt. Gate5 owner confirmation and effective transfer remain pending; the checked working branch is not a claim those acts occurred.

The approved exact Gate3 V3 subject and Gate4 propagation plan are published through PR727 merge8209bc54e0d133b19437c93b184cd50ba3d43489. Actual completed retirement journal bb38d99aac91bd6b7a7808b4760e1781b431624e0bb0754f4b08cb66d18fa203 reports APPLIED with53entries. The live reference state is applied_pending_confirmation with Gate5 null. All source histories remain intact; no source SOW/context/evidence bytes were rewritten.

| Core check | Verdict | Evidence |
|---|---|---|
| 1 Package coverage | PASS historical mode | Six exact historical parent folders and complete declared child sets. No active Root product package is inferred. |
| 2 Deliverable coverage | PASS historical mode |53 exact folders and statuses, all RETIRED; none missing. |
| 3 Reverse coverage | PASS | No undeclared Root package or direct1_Working deliverable. Successors account for all53. |
| 4 IDs | PASS | Original IDs reserved;46GOV successors and7chirality-runtime-qualified successors unique and existent. Runtime successor authority targets are directories; governance targets are files. |
| 5 Context fidelity | PASS preservation | Historical context/source contracts equal pre-cutover main; they correctly retain historical meaning instead of impersonating current successors. The one existing DEL0206 _MEMORY was read before its status and preserved. |
| 6 Artifacts/contracts | WARNING historical debt | Historical nonstatus contents equal source main byte for byte. Prior seven current-SOW warnings are not retroactively erased. Six runtime successor contracts now pass in the separate destination audit; GOV0411's inherited warning remains owned by its unassessed governance successor. No production artifacts are declared complete by retirement. |
| 7 Objectives | PASS historical mode | Seven source objectives retained in exact approved postimages. Mappings resolve to explicit successor partition; objective duties are not claimed met merely because old product carriers retired. Ordinary active-product “only RETIRED supports” logic is inapplicable to the approved governance-only mode. |
| 8 Ledger | PASS |104 original rows/fields preserved exactly,95IN/9OUT; all approved successor-map targets resolve. No deletion, orphan, duplicated active ownership or reassignment to a client. Fifteen original IN rows with blank direct objectives remain historical facts. |
| 9 Derivative parity | SKIPPED variant-owned check | DOMAIN-specific. SOFTWARE seven-source exact postimage parity and full historical conservation checked independently. |
| 9b Package shape | PASS | Root working surface is explicitly historical registration/control-plane reference, accompanied by scope/objective/trace/telemetry registers and46governance bindings. Original canon and product claims are preserved as history under named amendments, not active duplicate authority. |
| 10 Snapshot/handoff | PASS for observed in-progress phase | Completed journal and64postimages support the truthful current application handoff; an observed copy is included. Gate5/final derivative fan-in/pointer act are explicitly pending. The old SCA004 pointer is deliberately unchanged under owner reservation. The new application snapshot is still being assembled; this audit does not certify its final artifact completeness. |
| 11 Lifecycle | PASS historical mode |53RETIRED,0activeRootproduct flags. Destination audit separately proves7INITIALIZED/0activated. No generalized RETIRED transition is inferred for ordinary projects. |

`Checks.json` contains500 actual checks; `Decomp_Coverage_Matrix.csv` has53historical rows and successor paths. All six parents' child sets match, all104 original ledger fields compare equal with pre-cutover main,46 exact control hashes/authority routes match accepted bindings, and all source nonstatus tracked files are unchanged. GOV0408 has two semicolon-separated approved controlling instruments; treating that field as one filename was a parser error corrected before publication, not a source defect.

The64postimage backcheck includes four canon files in addition to the60source/status checks. This audit does not substitute for independent governance semantic concordance or guard implementation review. The approved journal-bound runtime state and pending owner act prevent operational authority from being inferred from candidate registration flags alone.

## Historical findings and remaining work

The four SCA004 filename gaps remain historical evidence under the exact Gate3-approved Historical_Findings_Disposition. This new phase uses actual pre/post audits and the supplied prior map/current approved supersessions; no missing historical audit, owner gate or map is fabricated. Final application-package completeness and any active pointer/effective act belong to SCOPE_CHANGE and the owner after fan-in.

The prior seven SOW warnings stay attributable to unchanged source contracts. New runtime initialization reconciles six successor contracts under actual workflow evidence; it does not repair the old files. GOV0411 remains OPEN_UNASSESSED and retains the remaining production-contract reconciliation duty. Root controls are obligations, not product deliverables with implied PASS evidence.

Independent dependency closure retains DEP-AUD-001 (generic bare/fullslug tool dialect) while actual topology passes six runtime plus two governance edges. Runtime coverage snapshot carries that warning; do not interpret this source audit as waiving it. Current estimates/order are new derivative evidence awaiting their owner dispositions, with remaining effort unknown. Other canon/export/receiving-loop/closure work follows actual parent fan-in.

Rerun after any pinned source/status/control/successor mapping change or a new authority application. Treat Handoff_Observed as a dated observed copy; later truthful fan-in additions do not retrospectively alter this audit. Final owner Gate5 confirmation, effective transfer and pointer movement are not supplied here.''')
write('RUN_SUMMARY.md','''# Root post-application return

RUN_STATUS = WARNINGS. Structural500/500 PASS;64/64exact applied postimages rechecked;0new structural blockers. Historical topology6parents/53RETIRED/0activeRootproduct;46controls/7runtime successors;104source rows/7historical objectives.

Actual APPLIED journal53entries pinned. Source nonstatus histories unchanged. Historical GOV0411 production-schema debt remains warning, and other derivative warnings remain with their owning audit. Gate5/effect/pointer not confirmed. This is derivative post-state coverage for SCOPE_CHANGE fan-in, not final application-package acceptance.''')
write('Decision_Log.md','''# Decisions and calibration

Use approved historical/governance semantics, not an unsupported ordinary active-product audit mode. Compare exact postimages and preserved original fields; require every source successor, qualified runtime identity, full parent set and control binding. Read existing memory before statuses; one DEL0206 memory exists and was read. Parse GOV0408's two semicolon-separated authority paths independently. Runtime authority targets are carrier directories; governance targets are files.

Parent released Root audit only after actual APPLIED journal. Waited for actual application handoff update before assessing phase truth. Old pointer intentionally untouched; no historical gap repair or owner confirmation fabricated. Preserve all old source contracts, warnings and output incompleteness. Output-root naming follows approved EVIDENCE_OUTPUT_SCOPES over supplemental alias. No source/tool/Git changes or delegation. Assembly corrections precede immutable publication only.''')
write('QA_Report.md','''# QA

500actual independent checks PASS;53unique matrix rows;6parents;46control hashes/routes;7qualifiedruntime targets;104original ledger fields conserved;64approved postimages independently rehashed; completed53entryjournal exacthash verified. All pinned input hashes rechecked at seal. One source memory read before corresponding status. CSV LF. No pointer/source/tool/Git writes.

This check covers applied branch structure and exact approved mapping semantics. It does not mechanically enforce the role, validate final unpublished owner confirmation, or certify unfinished final application artifacts. Historical production debt remains disclosed, and the ordinary product-only objective/lifecycle interpretation is not used for Root historical mode.''')
issues=[['COV-001','6','WARNING','ARTIFACT','HistoricalDeliverable','DEL-04-11_Root_Loop_Receipt_Validator','Inherited source SOW current-schema warning remains under GOV-04-11; no retrospective repair or implied product completion','execution/_ScopeChange/SCA-005_2026-09-05_2344/Historical_Findings_Disposition.md','execution/_Coordination/GovernanceControls/GOV-04-11.md']]
summary={'run_label':'SCA005_MIGRATION_POST_ROOT','timestamp':x['timestamp'],'decomp_variant':'SOFTWARE','audit_mode':'ROOT_HISTORICAL_GOVERNANCE','scope':'ALL','expected_source_snapshot':'execution/_ScopeChange/SCA-005_2026-09-05_2344/FINAL_INTEGRATION_V3/COMBINED_ARTIFACTS.sha256','expected_handoff_phase':'Applied pending owner Gate5 confirmation','decomposition_path':'execution/_Decomposition/Chirality_Root_SOFTWARE_DECOMP_v1_0.md','decomposition_revision':'Exact approved SCA005 historical postimage','repository_topology':{'packages':6,'deliverables':53,'objectives':7,'scope_items':104,'ledger_rows':104},'historical_topology':x['topology'],'partitions_declared':6,'partitions_found':6,'production_units_declared':53,'production_units_found':53,'active_root_product_deliverables':0,'forward_coverage_partitions_pct':100,'forward_coverage_production_units_pct':100,'reverse_coverage_pct':100,'context_fidelity_pct':100,'objective_coverage_pct':100,'artifact_presence_pct':None,'artifact_measurement':'Historical outputs not retested as active production','deliverables_without_objective_mapping':0,'in_ledger_rows_without_objective_mapping':15,'package_shape_conformance':'PASS','derivative_package_status':'SKIPPED','active_snapshot_status':'PASS','handoff_state_status':'PASS','snapshot_check_scope':'Observed in-progress application phase; final artifact completeness and owner confirmation excluded','objective_evidence_integrity':'PASS','issues_blocker':0,'issues_warning':1,'issues_info':0,'check_count':12,'lifecycle_distribution':{'RETIRED':53},'overall_status':'WARNINGS','closure_readiness':'WARN','structural_checks_passed':500,'exact_postimages_checked':64,'gate5_confirmed':False,'effective_transfer_confirmed':False,'concrete_labels':{'partition':'HistoricalPackage','production_unit':'HistoricalDeliverable'}}
write('coverage_summary.json',json.dumps(summary,indent=2));write('Checks.json',json.dumps(x['checks'],indent=2));write('Memory_Reads.json',json.dumps(x['source_memories_read'],indent=2));write('Postimage_Backcheck.json',json.dumps(parity,indent=2));csvw('Decomp_Coverage_Matrix.csv',list(x['matrix'][0]),[list(m.values()) for m in x['matrix']]);csvw('Decomp_Coverage_IssueLog.csv',['IssueID','CheckNumber','Severity','EntityType','ConcreteLabel','EntityID','Description','DecompositionRef','FilesystemRef'],issues);csvw('INPUT_HASHES.csv',['Path','SHA256'],sorted(x['inputs'].items()))
for path,h in x['inputs'].items():assert sha(R/path)==h,path
csvw('ARTIFACT_HASHES.csv',['Path','SHA256'],[(p.name,sha(p)) for p in sorted(O.iterdir()) if p.is_file() and p.name!='ARTIFACT_HASHES.csv']);print('SEALED',O,sha(O/'ARTIFACT_HASHES.csv'))
