#!/usr/bin/env python3
"""Adapt the accepted batch-author harness to frozen PKG-17 B1."""
import re
from pathlib import Path

root = Path(__file__).resolve().parents[8]
template = root / "execution/_Coordination/AgentRuns/SOW-STAGE2-EXEC-20260712-01/instances/WORKING-P2-PKG09/children/AUTHOR-B1/run_author.py"
source = template.read_text(encoding="utf-8")
source = source.replace("WORKING-P2-PKG09", "WORKING-P4-PKG17")
source = source.replace("candidates/W_P2/PIP-PKG09", "candidates/W_P4/PIP-PKG17")
source = source.replace("snapshots/W_P2/preflight/P2_MANIFEST.tsv", "snapshots/W_P4/preflight/P4_MANIFEST.tsv")
source = source.replace("eaad463c0d481f6f1654e6adb5ee718f566176e9", "e8f59a63372f38d9e788ac39b39995558f5aba73")
source = source.replace('DIDS=[f"DEL-09-{n:02d}" for n in range(1,6)]', 'DIDS=[f"DEL-17-{n:02d}" for n in range(1,6)]')
source = source.replace('"--package-id","PKG-09"', '"--package-id","PKG-17"')
source = source.replace("assert total_lines==total_covered==1357", "assert total_lines==total_covered==1528")
source = source.replace('  run(["python3",tool("render_scope_of_work.py"),str(prod),"--output",str(m/f"ScopeOfWork-{suffix}.html")],m/f"render-{suffix}.stdout",m/f"render-{suffix}.stderr")\n', '')
source = source.replace(', ("ScopeOfWork-a.html","ScopeOfWork-b.html")', '')
source = source.replace(',("ScopeOfWork-a.html","ScopeOfWork-b.html")', '')
source = source.replace(',["render_html",sha(m/"ScopeOfWork-a.html"),sha(m/"ScopeOfWork-b.html"),"true"]', '')
seeds = '''SEEDS={
"DEL-17-01":("A governed CAEPIPE and export-format source-basis contract with admitted sources, source-grounded findings, downstream-consumption rules, and an explicit unanswered-question register is produced.","The contract preserves official/public and project-owned source authority, best-effort locations, CAEPIPE MBF, external-run and CSV boundaries, conservative PCF and review-only GLB/glTF classifications, downstream gating, protected/proprietary-content exclusions, explicit target-behavior TBDs, and professional non-authority without implementing or claiming compatibility.","Validate the contract and review source parity, admitted-source and finding registers, source-location discipline, downstream-consumer gates, all CAEPIPE/PCF/GLB boundaries, the complete unanswered-question register, protected-content exclusions, and absence of implementation, compatibility, release, code-compliance, or professional-acceptance claims."),
"DEL-17-02":("A schema-first common export-package, target-profile, stable-ID-map, manifest, and loss-report contract for deterministic interoperability is produced.","The contract preserves source-basis identifiers, JSON Schema 2020-12 and no-bypass boundaries, export identity and hash metadata, explicit profile/version and unit/coordinate semantics, stable canonical-ID carrier and sidecar modes, exported/omitted/approximated/delegated/unsupported/TBD loss categories, diagnostics and provenance, downstream target gates, protected/private-data controls, and all carried target-specific TBDs without implying equivalence or professional acceptance.","Validate the contract and review source parity, every package/profile/ID-map/manifest/loss-report field, canonical hash and unit boundaries, source-ID carryforward, deterministic ordering and diagnostics, no-silent-loss behavior, downstream target gates, retained target/version/carrier/container TBDs, and prohibited compatibility, compliance, release, or professional-authority claims."),
"DEL-17-03":("A deterministic native open-JSON export-package contract that materializes the common interoperability contracts without target-specific or commercial dependencies is produced.","The contract preserves package, manifest, target-profile, stable-ID-map and loss-report members; canonical JSON/JCS-compatible hashing and deterministic ordering; model, unit, provenance and diagnostic metadata; complete explicit loss classification; schema validation; invented or rights-cleared fixtures; and downstream adapter boundaries without adding solver execution, target equivalence, lifecycle acceptance, or professional authority.","Validate the contract and review source parity, all native package members and implementation artifacts, common-contract conformance, deterministic serialization and hash basis, stable-ID and loss-report closure, schema and fixture evidence, target-neutral boundaries, retained residual gates, and absence of proprietary content, hidden defaults, compatibility proof, or professional claims."),
"DEL-17-04":("A versioned CAEPIPE MBF export-profile and deterministic writer contract with explicit supported, omitted, approximated, delegated, sidecar-mapped, unsupported, and TBD behavior is produced.","The contract preserves DEL-17-01 source authority and DEL-17-02 common package/profile/ID-map/loss contracts, a selected-profile gate, deterministic text generation, stable canonical-ID mapping, units and coordinates, pass-through target options without local code logic, invented/rights-cleared fixtures, diagnostics, loss reporting, and unresolved MBF record, field, version, line-ending, encoding, and external-validation questions without claiming broad compatibility or acceptance.","Validate the contract and review source parity, source/profile gates, deterministic writer and byte-output requirements, complete behavior classification and loss reporting, stable-ID carrier/sidecar treatment, unit/coordinate and encoding boundaries, fixture provenance, every retained MBF TBD, and absence of bundled/proprietary material, local code-checking logic, compatibility overclaim, or professional authority."),
"DEL-17-05":("An optional user-owned CAEPIPE external-run harness and bounded CSV-parser contract for regression and handoff evidence is produced.","The contract preserves explicit user configuration, executable and license ownership, accepted MBF package/profile inputs, run-directory and environment metadata, documented invocation with unresolved profile gates, output discovery, bounded fixture-confirmed parser coverage, canonical-ID correlation, skip-without-executable public-CI behavior, diagnostics for unknown/unmapped sections, private-user-data handling, and regression-only evidence classification without bundling CAEPIPE or implying compatibility, code compliance, formal validation, or professional acceptance.","Validate the contract and review source parity, all run-record fields, explicit configuration and skip paths, invocation/profile and parser-section TBDs and conflicts, manifest/ID-map/loss bindings, output discovery and parser diagnostics, unit/coordinate and provenance boundaries, invented/private fixture handling, no license bypass, and all prohibited compatibility, validation, compliance, and professional-authority claims.")}
'''
source, count = re.subn(r"SEEDS=\{.*?\}\n\n(?=def sha)", seeds + "\n", source, flags=re.S)
assert count == 1
for forbidden in ("DEL-09-", "PKG-09", "W_P2/PIP-PKG09", "P2_MANIFEST.tsv", "WORKING-P2-PKG09", "ScopeOfWork-a.html"):
    assert forbidden not in source, forbidden
compile(source, str(template), "exec")
exec(compile(source, str(template), "exec"), {"__name__": "__main__"})
