"""Convert EXEC's valid recorder outputs into RS entries and validate each one (R14-1).

Prototype only (R12-3); Python 3 standard library; not product code.

  python3 exec_to_rs.py [scratch-dir]

RS format 0.1 is the only record container (R14-1). DEL-02-03's recorder
emits {kind, observedAt, body}, where kind is an RS entry kind and body is a
CE body of EXEC's `checkpoint-record-entries.schema.json`. This script:

1. checks that every CE body EXEC defines has an RS entry kind whose body
   `$ref`s it by its schema identity (none without a kind), and that EXEC's
   recorder-output kinds and RS's kinds agree;
2. writes an RS `run_opened` for the fixture run (the App writer's entry,
   RS §14.1), then appends each recorder output of EXEC's committed valid
   example through the RS prototype writer (W-1 validates every entry against
   `RS_RECORD.schema.json` and refuses a nonconformant one);
3. reads the log back (R-1…R-8) and reports n of n entries valid;
4. does the same for every recorder output of EXEC's other CH scripts
   (CH-20, CH-31 (i), CH-31 (ii), CH-10, regenerated by EXEC's `run_all.py`)
   and for one sample body of each CE kind those scripts do not emit, so that
   every RS kind that references an EXEC body is written at least once.

Exit status 0 only when every entry is valid and every kind resolves.
"""

import glob
import json
import os
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

from minischema import Registry, validate                    # noqa: E402
from record_store import Reader, Writer, NonConformant, RS_ID  # noqa: E402

RS_DIR = os.path.dirname(HERE)
EXECUTION = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(RS_DIR))))
EXEC_DIR = glob.glob(os.path.join(EXECUTION, "PKG-02_*", "1_Working", "DEL-02-03_*", "Design"))[0]
WORKING = os.path.dirname(os.path.dirname(RS_DIR))
ACT_DIR = glob.glob(os.path.join(WORKING, "DEL-04-01_*", "Design"))[0]
AS_DIR = glob.glob(os.path.join(WORKING, "DEL-04-02_*", "Design"))[0]

# The fixture run of EXEC's valid example (EXEC run_all.py ch8(): run-12a, E1 rev-A2, App Codex via X).
RUN_ID = "run:12a"
RUN_OPENED = {
    "runId": RUN_ID, "startedBy": {"kind": "person", "identity": "Engineer A"}, "surface": "App run",
    "workflow": {"kind": "workflow", "origin": "project", "sourceRoot": "fx-proj", "name": "supports-adjust",
                 "revision": "rev-A2", "revisionVerification": "verified"},
    "conversationRef": "conv:run-12a",
    "declaredCheckpoints": [{"name": "CP-check", "requiredAct": "A4", "subjectClass": "objects changed by a named outcome"}],
}


def load_registry():
    reg = Registry()
    for d, f in ((ACT_DIR, "ACT_POLICY_CLASS_RECORD.schema.json"), (AS_DIR, "AS_SETTINGS_IN.schema.json"),
                 (EXEC_DIR, "checkpoint-record-entries.schema.json"), (RS_DIR, "RS_RECORD.schema.json")):
        reg.load(os.path.join(d, f))
    return reg


def kind_coverage(reg):
    """Every EXEC CE body has an RS kind that references it; EXEC's output kinds are RS kinds."""
    rs = reg.by_id[RS_ID]
    exec_schema = json.load(open(os.path.join(EXEC_DIR, "checkpoint-record-entries.schema.json"), encoding="utf-8"))
    branches = exec_schema["$defs"]["recorderOutput"]["oneOf"]
    exec_kinds = {b["properties"]["kind"]["const"]: b["properties"]["body"]["$ref"].split("/")[-1] for b in branches}
    rs_kinds = set(rs["$defs"]["entry"]["properties"]["kind"]["enum"])
    rows, problems = [], []
    for kind, body in exec_kinds.items():
        if kind not in rs_kinds:
            problems.append(f"{kind}: no RS entry kind")
            continue
        rs_def = rs["$defs"].get(body)
        refs = json.dumps(rs_def or {})
        if kind == "evidence_limit":
            ok = True                       # CE-19 is a constrained instance of RS's own evidence-limit body
            how = "RS evidenceLimit (EXEC recordWriteFailed is a constrained instance)"
        else:
            ok = rs_def is not None and exec_schema["$id"] + "#/$defs/" + body in refs
            how = "$ref EXEC #/$defs/" + body if ok else "NOT referenced"
        rows.append((kind, body, how))
        if not ok:
            problems.append(f"{kind}: RS body does not reference EXEC's {body}")
    return rows, problems


def convert(scratch, reg=None, quiet=False):
    reg = reg or load_registry()
    outputs = json.load(open(os.path.join(EXEC_DIR, "checkpoint-record-entries.example.valid.json"), encoding="utf-8"))
    out = os.path.join(scratch, "exec-to-rs.run-12a.jsonl")
    if os.path.exists(out):
        os.remove(out)
    w = Writer(out, reg, {"role": "App writer", "identity": "app-writer:local"}, {"surface": "App"}, RUN_ID)
    refused = []
    w.append("run_opened", RUN_OPENED, "rec:app:run-12a:0000")
    for i, o in enumerate(outputs, start=1):
        try:
            w.append(o["kind"], o["body"], f"rec:app:run-12a:e{i:02d}", extra={"observedAt": o["observedAt"]})
        except NonConformant as exc:
            refused.append(str(exc))
    log = Reader(reg).read_log(out)
    converted = [e for e in log["entries"] if e["recordId"] != "rec:app:run-12a:0000"]
    valid = [e for e in converted if not validate(e, {"$ref": RS_ID + "#/$defs/entry"}, reg)]
    if not quiet:
        for e in converted:
            print(f"  {e['recordId']:24} {e['kind']:20} seq {e['seq']:2} observedAt {e.get('observedAt')}")
    return {"outputs": len(outputs), "converted": len(converted), "valid": len(valid), "refused": refused,
            "limits": log["limits"], "nonconformant": log["nonconformant"],
            "kinds": sorted({e["kind"] for e in converted}), "path": out}


SAMPLES = [  # one body per CE kind the CH scripts do not emit (fixture subjects; invented)
    ("declaration_finding", "T0", {"checkpoint": "CP-x", "finding": "invalid", "code": "FB-03"}),
    ("item_decision", "T11", {"arrival": {"checkpoint": "CP-accept", "arrivalOrdinal": 1}, "item": "PR-2/2",
                              "decision": "left", "leftCause": "refused — stale"}),
    ("item_decision", "T12", {"arrival": {"checkpoint": "CP-accept", "arrivalOrdinal": 1}, "item": "PR-2/1",
                              "decision": "A5", "act": {"recordId": "rec:app:run-12a:A5-1", "actKind": "A5",
                                                        "capturedAt": "not supplied by host",
                                                        "capturingSurface": "host_act_facility"},
                              "afterDecision": "not applied: refused — stale"}),
    ("arrival_declined", "T13", {"arrival": {"checkpoint": "CP-check", "arrivalOrdinal": 2},
                                 "declinedEventRef": "rec:app:run-12a:decl-1"}),
    ("control_relation", "T15", {"arrival": {"checkpoint": "CP-grant", "arrivalOrdinal": 1},
                                 "act": {"recordId": "rec:app:run-12a:A12-1", "actKind": "A12", "capturedAt": "T15",
                                         "capturingSurface": "grant_control"}, "relation": "pending"}),
    ("observation_lost", "T13a", {"scope": "result of a submission (PR-2)", "cause": "supplier exited", "deciding": True,
                                  "arrival": {"checkpoint": "CP-accept", "arrivalOrdinal": 1}}),
    ("observation_recovered", "T13o", {"scope": "result of a submission (PR-2)",
                                       "arrival": {"checkpoint": "CP-accept", "arrivalOrdinal": 1}}),
    ("arrival_replaced", "T20", {"arrival": {"checkpoint": "CP-accept", "arrivalOrdinal": 1}, "byOrdinal": 2}),
    ("evidence_limit", "T21", {"label": "record write failed", "detail": "no entry written from T19 to T21: storage unavailable"}),
    ("act_request", "T22", {"requester": {"kind": "not established (MCP server or agent)"}, "form": "MCP elicitation",
                            "actKind": "not named by the request", "subject": "not named by the request",
                            "purpose": "not named by the request", "association": "arrival association not established",
                            "evidence": {"kind": "conversation item", "ref": "item:elicitation-4", "resolutionAtWrite": "resolved"},
                            "time": "T22"}),
    ("act_request", "T23", {"requester": {"kind": "agent", "identity": "app-agent-seat:1"}, "form": "host-recorded request",
                            "actKind": "A5", "subject": ["PR-2/1"], "purpose": "accept the adjusted support",
                            "association": "associated with the current arrival",
                            "arrival": {"checkpoint": "CP-accept", "arrivalOrdinal": 1},
                            "evidence": {"kind": "host record", "ref": "host:request/PR-2", "resolutionAtWrite": "resolved"},
                            "time": "T23"}),
]


def convert_more(scratch, reg):
    """CH-20, CH-31 (i), CH-31 (ii), CH-10 and the samples, each run into its own RS log."""
    sys.path.insert(0, os.path.join(EXEC_DIR, "prototype"))
    import run_all as ex                                        # noqa: E402  (DEL-02-03 prototype)
    exec_schema = json.load(open(os.path.join(EXEC_DIR, "checkpoint-record-entries.schema.json"), encoding="utf-8"))
    runs = [(name, fn().outputs) for name, fn in (("CH-20", ex.ch20), ("CH-31-i", ex.ch31_i),
                                                    ("CH-31-ii", ex.ch31_ii), ("CH-10", ex.ch10))]
    runs.append(("decision-package", ex.decision_package_outputs()))
    runs.append(("samples", [{"kind": k, "observedAt": t, "body": b} for k, t, b in SAMPLES]))
    total = valid = 0
    kinds, problems = set(), []
    for name, outputs in runs:
        out = os.path.join(scratch, f"exec-to-rs.{name}.jsonl")
        if os.path.exists(out):
            os.remove(out)
        w = Writer(out, reg, {"role": "App writer", "identity": "app-writer:local"}, {"surface": "App"}, "run:" + name)
        for i, o in enumerate(outputs, start=1):
            total += 1
            exec_errs = ex.validate(o, exec_schema)
            if exec_errs:
                problems.append(f"{name} #{i} not a valid EXEC recorder output: {exec_errs[:1]}")
            try:
                w.append(o["kind"], o["body"], f"rec:app:{name}:e{i:02d}", extra={"observedAt": o["observedAt"]})
            except NonConformant as exc:
                problems.append(str(exc))
            # CC-R CI-3: this file-discovery fixture observes no writer. The RS
            # recorder records the limit separately; EXEC's CE bodies stay CE bodies.
            if o["kind"] == "act_request" and o["body"].get("form") == "decision package file" and "identity" not in o["body"]["requester"]:
                total += 1
                w.append("evidence_limit", {"label": "requester identity not established",
                         "subjectRef": f"rec:app:{name}:e{i:02d}",
                         "detail": "package file observed; writer of the identified bytes not observed"},
                         f"rec:app:{name}:e{i:02d}:requester-limit")
        log = Reader(reg).read_log(out)
        good = [e for e in log["entries"] if not validate(e, {"$ref": RS_ID + "#/$defs/entry"}, reg)]
        valid += len(good)
        kinds |= {e["kind"] for e in log["entries"]}
        print(f"  {name:9} {len(outputs):2} outputs -> {len(good):2} valid RS entries")
    return total, valid, kinds, problems


def main():
    scratch = sys.argv[1] if len(sys.argv) > 1 else tempfile.mkdtemp(prefix="exec-to-rs-")
    os.makedirs(scratch, exist_ok=True)
    reg = load_registry()
    rows, problems = kind_coverage(reg)
    print("EXEC CE bodies -> RS entry kinds (R14-1):")
    for kind, body, how in rows:
        print(f"  {body:22} -> {kind:22} {how}")
    print(f"kinds without an RS kind or reference: {problems or 'none'}")
    print("\nEXEC's valid example converted into RS entries:")
    r = convert(scratch, reg)
    ok = (not problems and not r["refused"] and r["converted"] == r["outputs"] == r["valid"]
          and not r["limits"] and not r["nonconformant"])
    print(f"\n{r['valid']} of {r['outputs']} recorder outputs written and valid as RS entries; refused {len(r['refused'])}; "
          f"reader limits {r['limits'] or 'none'}; kinds {r['kinds']}")
    print("\nEXEC's other CH scripts and one sample of each remaining CE kind:")
    total, valid, kinds, more = convert_more(scratch, reg)
    all_kinds = {k for k, _, _ in rows}
    missing = sorted(all_kinds - kinds - set(r["kinds"]))
    print(f"{valid} of {total} written and valid; problems {more or 'none'}; CE-referencing kinds never written: {missing or 'none'}")
    ok = ok and not more and valid == total and not missing
    print("RESULT:", "every entry valid, none without a kind" if ok else "FAILED")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
