from pathlib import Path
import hashlib,json,datetime,subprocess
r=Path.cwd(); w=r/'projects/chirality-app-dev'; s=w/'execution/_Coordination/AgentRuns/APP_LOOP_SHELL_2026-09-05/iteration-04/instances/pkg02_t2_proposal'; d=w/'execution/PKG-02_Desktop_Shell_Navigation_and_Operator_State/1_Working/DEL-02-01_Desktop_Shell_and_Matrix_Navigation'; packet=w/'execution/_Coordination/_DECISIONS/D-APP-120_PACKET_T2_NO_FOLDER_AND_WOVEN_SEAM_2026-09-05.md'
paths=[r/'AGENTS.md',r/'agents/AGENT_TASK.md',*[r/'skills/proposal-format'/x for x in ['SKILL.md','BRIEF_SCHEMA.md','TOOL_POLICY.md','QA_CHECKS.md']],w/'AGENTS.md',w/'loop/LOOP_INIT.md',s/'AUTHOR_BRIEF_v1.md',s.parent.parent/'T2_PACKET_SCOPE_DRAFT_v1.md',d/'ScopeOfWork.md',d/'_STATUS.md',w/'plans/shell-redesign_2026-09-04/03_TARGET_SPEC.md',w/'plans/shell-redesign_2026-09-04/04_IMPLEMENTATION_PLAN.md',w/'execution/_Coordination/_DECISIONS/D-APP-64_PACKET_REASONED_SELECTION_OVERLAY_2026-07-18.md',*[w/'frontend/src'/x for x in ['components/shell/chat-panel.tsx','components/shell/shell-frame.tsx','components/woven-dialogue/woven-dialogue-shell.tsx','components/workspace/workspace-provider.tsx','app/api/harness/session/create/route.ts','app/api/harness/session/list/route.ts','app/api/working-root/validate/route.ts','lib/runtime-client/runtime-daemon-harness-port.ts']],*[r/'runtime/packages'/x for x in ['contracts/src/session.ts','contracts/src/project.ts','contracts/src/harness/types.ts','core/src/session-store.ts']]]
(s/'source-bytes').mkdir(exist_ok=True)
inv=[]
for i,p in enumerate(paths):
 b=p.read_bytes(); out=s/'source-bytes'/f'{i:02d}_{p.name}';out.write_bytes(b);inv.append(dict(path=str(p.relative_to(r)),sha256=hashlib.sha256(b).hexdigest(),bytes=len(b),snapshot=str(out.relative_to(r))))
(s/'SOURCE_IDENTITIES.json').write_text(json.dumps(inv,indent=2)+'\n')
reg=w/'execution/_Coordination/_DECISIONS/_REGISTER.md'; check={'timestamp':datetime.datetime.now(datetime.timezone.utc).isoformat(),'register_sha256':hashlib.sha256(reg.read_bytes()).hexdigest(),'row_collision':'| D-APP-120 |' in reg.read_text(),'packet_collisions':[p.name for p in packet.parent.glob('D-APP-120*')]}; assert not check['row_collision'] and not check['packet_collisions'],check
(s/'AUTHOR_ID_RECHECK.json').write_text(json.dumps(check,indent=2)+'\n')
packet.write_text('''# D-APP-120 — T2 omitted shell seam and no-folder capability

Status: PROPOSAL / AWAITING_RULING. OwnerCaseSelection: NONE. EffectStatus: HELD.

This is a derivative decision-preparation package, not accepted decomposition truth. The accepted upstream basis is DEL-02-01 ScopeOfWork.md §SCA-APP-010 Gate-5 Current Contract, pinned to decomposition content commit `dbd812a52d5ed0cb3ed173f3aaaa68703a914291`, and its seated Remaining item DEL-02-01-V3-01. No commitment or Remaining text is changed. This packet requests two independently decidable acts; either can be deferred without selecting the other. Record-only authoring is authorized by the sealed brief; proposal implementation is not.

Source identity and frozen cited bytes: `execution/_Coordination/AgentRuns/APP_LOOP_SHELL_2026-09-05/iteration-04/instances/pkg02_t2_proposal/SOURCE_IDENTITIES.json` and its `source-bytes/`. All paths below are App-root-relative except explicit `runtime/` paths, which are repository-root-relative. Mutable live code observations are evidence, not accepted snapshots. Recheck against the final T3 postimage before any future implementation.

## PROPOSAL: A — authorize the omitted woven shell presentation seam

- Evidence: DEL-02-01 `ScopeOfWork.md` §SCA-APP-010 Current responsibility/acceptance 1–2 and compound IDs OUT-001, AC-001, VER-001; `_STATUS.md` §Remaining DEL-02-01-V3-01 lists the shell/chat/persona/navigator/CSS/Electron loci but omits `frontend/src/components/woven-dialogue/woven-dialogue-shell.tsx`. `plans/shell-redesign_2026-09-04/04_IMPLEMENTATION_PLAN.md` §T2 requires no woven header/eyebrow, relocated persona, retained reconnect and settings. In the inspected woven shell, `woven-dialogue-toolbar` renders `woven-eyebrow`, the heading, and `PersonaPicker disabled={streaming}` immediately above mounted `ChatPanel`. `shell-frame.tsx` owns runtime connectivity hooks, reconnect pending/error state, the guarded bridge status call and the RuntimeSettings/ApiKeySettings disclosure. Target meaning: `03_TARGET_SPEC.md` §§4,10 and SR-10–15/18/21; this design document is not the selection queue.
- Change: App owner option A1 authorizes an exact additive T2 write-locus amendment for `frontend/src/components/woven-dialogue/woven-dialogue-shell.tsx` and its shell/reconnect render tests. Remove its visible toolbar heading/eyebrow and old PersonaPicker placement; keep its ChatPanel instance mounted with `onActiveSessionChange={setPrimarySessionId}`. ChatPanel hosts the composer context line and PersonaPicker with the same streaming prohibition, preserving persona provider ownership and session creation guards. No new session state is introduced. Preserve reconnect via an explicit presentation slot: ShellFrame retains `useRuntimeConnectivitySnapshot`, derived indicator, in-flight ref, pending/error state and `window.chiralityRuntime.status()` handler, exposing the existing rendered reconnect control through an optional `renderWorkspaceUtilities({ reconnectControl, settingsControl })` render prop. Woven shell places reconnectControl in its existing activity shelf header and settingsControl in the Navigator footer's temporary Settings disclosure; Navigator accepts an optional footer ReactNode. ShellFrame still owns the existing settings component behavior. Default/legacy shells retain existing rendering. Exact names are candidate additions, not claims that these props exist today. Tests must prove single placement and accessible reachability; no relocation may drop error feedback, aria-label, focus, or duplicate reconnect calls.
- Why: Completeness and scope clarity: the current toolbar cannot disappear by changing only the listed ShellFrame header, and removing the old header must not strand its controls.
- Risk: T3 currently writes the woven shell. Serialize any A1 implementation after its accepted frozen postimage and refresh review; never edit concurrently. Moving controls can lose keyboard focus or reconnect guard state. Pure styling would leave conflicting markup; deleting the toolbar without relocation would remove persona control. A1 does not authorize Root/runtime/API edits or make no-folder send functional.
- Status: NEEDS_HUMAN_RULING.

Owner question A: authorize A1, the exact App presentation seam addition and candidate responsibility split above, or A2, defer the omitted seam and keep DEL-02-01-V3-01 open? Recommended A1 after T3 integration; owner selection NONE. If the owner wants a different control host, return an amended bounded candidate before implementation. Future write fence: the named woven shell/tests plus already seated T2 shell/chat/persona/navigator/CSS loci; any newly named file requires its own explicit fence. No activity-shelf source addition is presumed: the shell composes its existing header/slot; if the component lacks a suitable slot, prepare an exact additional amendment rather than silently extending scope.

## PROPOSAL: B — retain current restriction while routing no-folder runtime semantics

- Evidence: DEL-02-01 `ScopeOfWork.md` §SCA-APP-010 acceptance 2–3 says a chat may have no folder and folder is fixed after first message; Remaining DEL-02-01-V3-01 traces SOW-002 and preserves DEL-07-01 validation. T2's design suggestion `clearProjectRoot` is not a runtime contract. `chat-panel.tsx` `ensureSessionBooted` throws without projectRoot; send/composer controls are disabled without it. Both session create POST and session list GET routes require a nonempty projectRoot. `runtime-daemon-harness-port.ts` constructor rejects project IDs other than `chirality-app-dev`; create/list require the candidate path inside the configured registered project's canonicalRoot; create sends that fixed projectId and list returns that project's sessions. `runtime/packages/contracts/src/session.ts` requires projectId in CreateSessionRequest and projectRoot/projectId in RuntimeSessionRecord; `runtime/packages/core/src/session-store.ts` create resolves an authorized project and writes its canonicalRoot into the session. `runtime/packages/contracts/src/project.ts` defines registration/manifest identity. `app/api/working-root/validate/route.ts` delegates to `assertProjectRootAccessible`; WorkspaceProvider invokes it before applying a candidate. DEL-07-01 remains validation owner.
- Change: B1 retains the actual current restriction: selecting no folder may clear local selection, but composer/send remain unavailable and no session is invented. Explain the unavailable capability visibly if this state is exposed; do not mark the accepted no-folder behavior complete. Route a separate bounded contract-design request through HELP_HUMAN to the Root owning loop for its own instrument/acceptance, with App consuming the result only after acceptance. The request must resolve whether a genuinely projectless session exists, how its execution/instruction context and filesystem permissions are represented, how create/list/replay/boot/turn resolve identity, how first-message binding is persisted and enforced, and how migration/compatibility/error behavior works. No specific new endpoint, authorization mode, default root, or session schema is approved here.
- Why: Source fidelity and explicit authority: UI absence of a selected folder is different from a Root session with no registered project, and the adapter currently cannot provide the latter.
- Risk: Treating an empty UI folder as the configured app-dev root conceals authority. Removing ChatPanel/API guards only exposes downstream rejection. Mapping arbitrary knownRoots to the fixed projectId duplicates the same project sessions and falsely implies multi-project discovery. Expanding project IDs, registry lookup, or runtime schema crosses owning-loop boundaries. Existing provider/security fences remain.
- Status: NEEDS_HUMAN_RULING.

Owner question B: B1 retain truthful restriction and request the separate Root contract design (recommended); B2 defer the capability and its Root request, retaining restriction and open acceptance residual; or B3 ask Root to evaluate an explicitly registered-project-bound chat with no separately selected working folder as a distinct product semantics candidate? B3 would require explicit owner acceptance of the meaning and any necessary App scope amendment; it cannot be silently substituted for projectless chat. Owner selection NONE. B1 and B3 are routing/design options, not runtime implementation grants. This author sends no Root message. The parent routes only after the appropriate owner disposition. Future App adapter/API write fences and Root write fences must be separately named by their owning instruments after design; this packet grants none. KnownRoots remains local convenience state, not identity authorization or an authoritative discovery list.

## Acceptance evidence required after owner choices

For A1: refresh APP-HOLD and source identities after T3; verify persistent primary dialogue and route/query compatibility, no woven header/toolbar/eyebrow, sole persona placement and streaming guard, reconnect success/unavailable/error/in-flight branches with unchanged aria-label, reachable settings behavior, focus/keyboard landmarks, 960px/1440px both-theme browser evidence with 480px centre wrapping, contrast evidence for any token change. Run all DEL-02-01-V3-01 registered checks and a fresh independent software-code-review over 100% frozen product diff; preserve A1 login-proof restaging discipline. No tests were run or product claims made by this record-only author.

For B1/B3 eventual implementation: accepted Root snapshot and explicit App consumption instrument first; exact schema/API/registration/permission semantics, first-message binding and invalid/instruction-root path refusal tests; create/list/boot/turn/replay consistency, no hidden fallback, multi-project authorization isolation, migration and negative cases; Root-owned checks and independent review, then App registered tests/browser proof against the accepted contract. B2 requires an explicit deferred residual, not completion.

## Decision interface and handoff

- MISSING: accepted no-folder runtime contract; owner selections A/B; independent governed verifier return (PENDING, not COMMIT-SAFE); accepted T3 postimage for future A1 source editing.
- NEEDS_HUMAN_RULING: A1 versus A2; B1 versus B2 versus B3, separately. App seam acceptance cannot decide Root semantics.
- DEPENDENCY_NOTES: DEL-02-01-V3-01 retains its actual Remaining gate; APP-HOLD CLEAR is permission to rely, not lifecycle/dependency acceptance. DEL-02-04 knownRoots and DEL-07-01 validation are consumed only under their accepted contracts. T3 is independent and keeps its current source fence.

Closure: record-only proposal authoring complete, governed effect HELD. No source, lifecycle, _STATUS, MEMORY, register, pointer, dependency, release, provider, Root, or routing-message effect. Parent must freeze/review this derivative package, integrate its proposed row if authorized, and present the separate owner choices. Re-run identity and ID checks before register integration; any changed cited source requires review calibration. The original sealed brief and manager records remain intact. D-APP-64 ten-field judgments and four-lens reasoning are in the accompanying RATIONALE.md, incorporated by reference.
''')
ra=[]
for name,outcome,rejected,lenses in [
('A','Advance A1 as an App-only owner proposal after T3 serialization','A2 deferred as less complete; CSS-only hiding retains markup; deleting controls loses existing behavior; concurrent T3 edits violate the shared-source fence.', ['Ontology: presentation seam is App-owned; session truth is not.','Epistemology: direct toolbar and ShellFrame reads identify the actual owners.','Praxeology: serialize after T3, preserve hooks/props, review a frozen diff.','Axiology: meet header-less intent while keeping reconnect/settings accessible.']),
('B','Advance B1 restriction plus separately owner-gated Root design routing proposal','B2 delays resolution; B3 is a different semantic candidate needing owner acceptance; guard removal and hidden canonicalRoot fallback contradict actual contracts.', ['Ontology: absent selected folder differs from absent registered project authority.','Epistemology: required fields and fixed project binding prove current restriction, not future semantics.','Praxeology: Root accepts its own contract before App implementation; no routing message is sent here.','Axiology: truthful capability and explicit filesystem identity outweigh apparent UI completion.'])]:
 ra.append(f'''## Judgment {name}
OwnerStandingApproval: D-APP-64 §3
AgentJudgment: SELECT_AND_ADVANCE
SelectedOutcome: {outcome}
JudgedBy: TASK Agent2 / pkg02_t2_proposal / APP_LOOP_SHELL_2026-09-05 iteration-04
OwnerCaseSelection: NONE
RejectedAlternatives: {rejected}
RationaleArtifact: execution/_Coordination/AgentRuns/APP_LOOP_SHELL_2026-09-05/iteration-04/instances/pkg02_t2_proposal/RATIONALE.md
IndependentVerifier: PENDING — parent must dispatch fresh governed verifier; no return exists or is anticipated as COMMIT-SAFE.
EffectStatus: HELD
PreservedGates: owner case selection; Root authority and contract acceptance; product write fences; T3 serialization; independent review; lifecycle/dependency/pointer acceptance; provider/network/release boundaries.

'''+ '\n'.join(lenses)+f'\n\nEvidence and exact recommendation: D-APP-120 §PROPOSAL {name}; source hashes and frozen bytes in SOURCE_IDENTITIES.json. Draft record writing has occurred under the sealed brief; selected implementation/routing effect has not.\n')
(s/'RATIONALE.md').write_text('# D-APP-64 §5.3 rationale\n\n'+'\n'.join(ra))
(s/'PROPOSED_REGISTER_ROW.md').write_text('| D-APP-120 | Separately authorize omitted T2 woven presentation seam and choose no-folder capability routing or defer | DEL-02-01-V3-01 App seam; Root no-folder contract requires separate owning instrument | AWAITING_RULING | OwnerCaseSelection NONE; proposal only; EffectStatus HELD; verifier PENDING | `execution/_Coordination/_DECISIONS/D-APP-120_PACKET_T2_NO_FOLDER_AND_WOVEN_SEAM_2026-09-05.md` |\n')
(d/'_run_records/T2_CAPABILITY_PROPOSAL_2026-09-05.md').write_text('# T2 capability proposal — record only\n\nD-APP-120 authored under sealed pkg02_t2_proposal brief. Derivative proposal: App omitted woven-shell seam and separately Root no-folder capability question. OwnerCaseSelection NONE; EffectStatus HELD; independent verifier PENDING. No implementation, state, lifecycle or acceptance claim.\n\nEvidence, APP-HOLD dispatch/reliance ALLOW JSON, source hashes, D64 judgments and return: `execution/_Coordination/AgentRuns/APP_LOOP_SHELL_2026-09-05/iteration-04/instances/pkg02_t2_proposal/`. Accepted basis: SCA-APP-010 ScopeOfWork pinned decomposition dbd812a52d5ed0cb3ed173f3aaaa68703a914291; Remaining DEL-02-01-V3-01. Parent owns register integration and governed verification. Recheck sources after T3 before future implementation.\n')
print(str(packet))
