#!/usr/bin/env python3
"""Build the DEL-01-01-V3-01 AT-053 App governed-basis evidence record (Markdown + JSON).

Deterministic generator: every citation SHA-256 is recomputed from the tree at run time;
no hash is typed by hand. Run from REPO_ROOT (or any subdirectory; the script resolves
REPO_ROOT with `git rev-parse --show-toplevel`). Live-tree checks (binding count, register
counts, accepted-byte identities) are recomputed and recorded rather than asserted.

Usage: python3 build_at053_evidence.py [--check]
  --check   exit non-zero if the generated bytes differ from the committed files.
"""
from __future__ import annotations

import csv
import hashlib
import json
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(subprocess.check_output(["git", "rev-parse", "--show-toplevel"], text=True).strip())
BASIS = "0c683fb1657706316272951e4c3a0f7781b46009"
RECORD_DATE = "2026-09-03"
RECORD_ID = "DEL-01-01-V3-01-AT-053-EVIDENCE-2026-09-03"

APP = "projects/chirality-app-dev"
D0101 = f"{APP}/execution/PKG-01_Product_Governance_and_Reliance_Boundaries/1_Working/DEL-01-01_Governance_Alignment_Human_Authority_and_Project_Truth"
OUT_MD = f"{D0101}/Evidence_AT-053_Governed_Basis_2026-09-03.md"
OUT_JSON = f"{D0101}/Evidence_AT-053_Governed_Basis_2026-09-03.json"

# ---- path constants (repo-root-relative) --------------------------------------------------
PKG02 = "execution/PKG-02_Operative_Instruction_Surface_and_Runtime_Layers/1_Working"
ROOT0206 = f"{PKG02}/DEL-02-06_Generic_Runtime_Stewardship_and_Release_Assurance"
SNAP = f"{ROOT0206}/_run_records/DEL-02-06-COMPATIBILITY-ACCEPTANCE-005/ACCEPTED_COMPATIBILITY_SNAPSHOT.md"
CAND = f"{ROOT0206}/_run_records/DEL-02-06-COMPATIBILITY-COMPLETION-004/candidate/COMPATIBILITY_COMPLETION_CANDIDATE.json"
ROOT0206_SOW = f"{ROOT0206}/ScopeOfWork.md"
ROOT0206_STATUS = f"{ROOT0206}/_STATUS.md"
ROOT0203_M2 = f"{PKG02}/DEL-02-03_Delegation_Hierarchy_and_Entry_Rules/_run_records/DEL-02-03-M2-APPLY-001/APPLICATION_RECORD.md"
ROOT0208_G2 = f"{PKG02}/DEL-02-08_Exact_Supply_and_Protocol_Pinning/_run_records/APP-SERVER-0.149.0-G2-CANDIDATE-2026-08-24/G2_ACCEPTANCE_SHEET.md"
ROOT_SCA_LATEST = "execution/_ScopeChange/_LATEST.md"
ROOT_SCA004_G5 = "execution/_ScopeChange/SCA-004_2026-08-22_1749/Gate_5_Application_Record.md"
ROOT_CONTRACT = "docs/CONTRACT.md"
ROOT_AGENTS = "AGENTS.md"
DGOV35 = "docs/governance_harness/_DECISIONS/D-GOV-35_delegated_harness_native_class.md"
ROOT_TM = "execution/_Coordination/_TaskManagement/REGISTER.csv"
ROOT_TM_CLOSED = "execution/_Coordination/_TaskManagement/REGISTER_CLOSED.csv"
ROOT_TM122_RULING = "execution/_Coordination/_TaskManagement/RULING_2026-09-03_ROOT_TM-ROOT-122_DISPOSITION.md"
ROOT_NOTICE_SCA008 = "execution/_Coordination/NOTICE_2026-08-24_APP_SCA-APP-008_GATE5_APPLIED_STATE.md"
ROOT_NOTICE_TM122 = "execution/_Coordination/NOTICE_2026-09-03_APP_TM-ROOT-122_ELECTRON_AUTHORITY_DISPOSITION.md"
PLAN = "plans/chirality_app_v3_release_execution_plan_final_2026-08-22.html"
G0 = "plans/steers/chirality_app_v3_g0_record_2026-08-22.md"
STEER_KCONTROL1 = "plans/steers/chirality_app_v3_kcontrol1_amendment_steer_root_2026-08-23.md"


def R(n: int, d: str) -> str:
    return f"plans/steers/chirality_app_v3_root_ruling_record_r{n}_{d}.md"


def A(n: int, d: str) -> str:
    return f"plans/steers/chirality_app_v3_app_ruling_record_a{n}_{d}.md"


R1, R2, R3, R4, R5, R6, R7, R8, R9 = (R(1, "2026-08-22"),) + tuple(R(i, "2026-08-23") for i in range(2, 10))
R10, R11, R12, R13, R14 = (R(i, "2026-08-24") for i in range(10, 15))
R15, R16, R17, R18 = R(15, "2026-08-25"), R(16, "2026-08-27"), R(17, "2026-08-27"), R(18, "2026-09-03")
A1, A2, A3, A4, A5, A6, A7, A8 = (A(i, "2026-08-23") for i in range(1, 9))
A9, A10, A11, A12 = A(9, "2026-08-24"), A(10, "2026-08-24"), A(11, "2026-09-03"), A(12, "2026-09-03")

APP_CONTRACT = f"{APP}/docs/CONTRACT.md"
RQG = f"{APP}/docs/RELEASE_QUALITY_GATES.md"
WORKPLAN = f"{APP}/loop/WORKPLAN_2026-09-03_app_dev_loop.md"
APP_AGENTS = f"{APP}/AGENTS.md"
SCA8 = f"{APP}/execution/_ScopeChange/SCA-APP-008_2026-08-23_1727_V3_Release_Pathway"
SCA8_CM, SCA8_IA = f"{SCA8}/Carrier_Map.md", f"{SCA8}/Impact_Assessment.md"
SCA8_ADD, SCA8_BRIEF, SCA8_CA = f"{SCA8}/Phase5/CLOSURE_ADDENDUM_2026-09-03.md", f"{SCA8}/Brief.md", f"{SCA8}/Contract_Amendments.proposed.md"
APP_SCA_LATEST = f"{APP}/execution/_ScopeChange/_LATEST.md"
DECOMP = f"{APP}/execution/_Decomposition/Chirality_App_vNext_SOFTWARE_DECOMP_v3_2.md"
SEAT = f"{APP}/execution/_Coordination/AgentRuns/APP_V3_PATHWAY_SEATING_2026-09-03"
SEAT_MAP, SEAT_COV = f"{SEAT}/MAPPING.md", f"{SEAT}/COVERAGE_MATRIX.md"
SEAT_IDL = f"{SEAT}/SOW_IDENTITY_LEDGER.md"  # per-carrier SOW/_STATUS pre/post SHA-256 at seating (the live DEL-01-01 _STATUS.md is edited by this tranche and is therefore not cited)
COORD = f"{APP}/execution/_Coordination"
NOTICE_0206 = f"{COORD}/NOTICE_2026-08-21_ROOT_DEL0206_COMPATIBILITY_ACCEPTANCE.md"
NOTICE_DGOV35 = f"{COORD}/NOTICE_D-GOV-35_DELEGATED_HARNESS_NATIVE_CLASS.md"
NOTICE_TM122_APP = f"{COORD}/NOTICE_2026-09-03_APP_TM-ROOT-122_ELECTRON_AUTHORITY_DISPOSITION.md"
NOTICE_027_028 = f"{COORD}/NOTICE_2026-08-19_ROOT_TM-APP-027_TM-APP-028_COMPATIBILITY_COMPLETION.md"
NOTICE_TM117 = f"{COORD}/NOTICE_2026-08-21_ROOT_TM117_TRIGGER_RESCOPE_AND_DEL0206_PREPARATION_AUTHORIZATION.md"
APP_TM = f"{COORD}/_TaskManagement/REGISTER.csv"
OWNER_RULING = f"{COORD}/_TaskManagement/OWNER_RULING_2026-09-03_G0_V3_TRIAGE.md"
DEC = f"{COORD}/_DECISIONS"
D103 = f"{DEC}/D-APP-103_RULING_PER_ATTEMPT_DECISION_REPLAY_PACKET_2026-08-17.md"
D98 = f"{DEC}/D-APP-98_RULING_ELECTRON_AUTHORITY_2026-08-17.md"
D97 = f"{DEC}/D-APP-97_RULING_RELEASE_PREPARATION_2026-08-17.md"
DREG = f"{DEC}/_REGISTER.md"
HOLDREG = f"{COORD}/APP_HOLD_REGISTER.csv"
CORPUS = f"{APP}/execution/_Reconciliation/References/AUTHORITY_CORPUS.json"


def ST(pkg: str, deliv: str) -> str:
    return f"{APP}/execution/{pkg}/1_Working/{deliv}/_STATUS.md"


SOW0101 = f"{D0101}/ScopeOfWork.md"
ST0202 = ST("PKG-02_Desktop_Shell_Navigation_and_Operator_State", "DEL-02-02_Workbench_and_Pipeline_Selection_UX")
ST0205 = ST("PKG-02_Desktop_Shell_Navigation_and_Operator_State", "DEL-02-05_API_Key_UI_and_Runtime_Feedback")
ST0301 = ST("PKG-03_Runtime_Engine_Contract_and_Turn_Lifecycle", "DEL-03-01_AgentEnginePort_and_Engine_Conformance_Suite")
ST0303 = ST("PKG-03_Runtime_Engine_Contract_and_Turn_Lifecycle", "DEL-03-03_Harness_API_and_SSE_Compatibility_Adapter")
ST0401 = ST("PKG-04_SDK_Adapter_Prompt_Provider_and_Settings", "DEL-04-01_SDK_Probe_and_Version_Pinned_Adoption_Decision")
ST0405 = ST("PKG-04_SDK_Adapter_Prompt_Provider_and_Settings", "DEL-04-05_Anthropic_Provider_Key_Base_URL_and_Network_Bridge")
ST0501 = ST("PKG-05_Session_Audit_Replay_and_Tool_Result_Records", "DEL-05-01_Canonical_Session_Folder_and_Legacy_Session_Migration")
ST0502 = ST("PKG-05_Session_Audit_Replay_and_Tool_Result_Records", "DEL-05-02_HarnessEvent_Schema_and_Append_Only_JSONL")
ST0503 = ST("PKG-05_Session_Audit_Replay_and_Tool_Result_Records", "DEL-05-03_Redacted_RunLogger_and_Secret_Hygiene")
ST0504 = ST("PKG-05_Session_Audit_Replay_and_Tool_Result_Records", "DEL-05-04_Runtime_Replay_and_Transcript_View")
ST0804 = ST("PKG-08_Agent_Suite_Pipeline_Dispatch_and_Subagent_Governance", "DEL-08-04_Type_2_Subagent_Governance_Bridge")
ST0805 = ST("PKG-08_Agent_Suite_Pipeline_Dispatch_and_Subagent_Governance", "DEL-08-05_Subagent_Child_Run_Records_and_Artifacts")
PKG09 = "PKG-09_Validation_Packaging_Security_and_Release"
ST0901 = ST(PKG09, "DEL-09-01_Section_8_Harness_Validation_Preservation")
ST0902 = ST(PKG09, "DEL-09-02_Section_9_Runtime_Validation_Additions")
ST0903 = ST(PKG09, "DEL-09-03_Unit_and_Integration_Test_Expansion")
ST0904 = ST(PKG09, "DEL-09-04_macOS_DMG_Packaging_and_Instruction_Root_Integrity")
ST0905 = ST(PKG09, "DEL-09-05_CI_Artifact_and_Release_Verification_Workflow")
ST0906 = ST(PKG09, "DEL-09-06_Network_Key_Attachment_and_Renderer_Security_Checks")
R21 = f"{APP}/execution/{PKG09}/1_Working/DEL-09-04_macOS_DMG_Packaging_and_Instruction_Root_Integrity/_run_records/R21_R20_OWNER_LOGIN_SESSION_PROOF_PASS_CLOSEOUT_2026-08-23.md"

# ---- helpers -------------------------------------------------------------------------------
_SHA: dict[str, str] = {}


def sha(rel: str) -> str:
    if rel not in _SHA:
        p = REPO_ROOT / rel
        if not p.is_file():
            raise SystemExit(f"cited path is not a file at basis: {rel}")
        _SHA[rel] = hashlib.sha256(p.read_bytes()).hexdigest()
    return _SHA[rel]


def size(rel: str) -> int:
    return (REPO_ROOT / rel).stat().st_size


def row(subject: str, cls: str, carrier: str, cites: list[str], note: str = "") -> dict:
    return {"subject": subject, "class": cls, "carrier_or_state": carrier, "note": note, "citations": sorted(set(cites))}


def cite_md(paths: list[str]) -> str:
    return "<br>".join(f"`{p}` @ `{sha(p)[:16]}`" for p in paths)


def esc(s: str) -> str:
    return s.replace("|", "\\|").replace("\n", " ")


# ---- live-tree checks (recomputed, not asserted) -----------------------------------------
def live_checks() -> dict:
    out: dict = {}
    cand = json.loads((REPO_ROOT / CAND).read_text(encoding="utf-8"))
    held: list[str] = []

    def walk(o, path):
        if isinstance(o, dict):
            if o.get("status") == "HELD_UNAVAILABLE":
                held.append((path.lstrip("."), o.get("identity")))
            for k, v in o.items():
                walk(v, f"{path}.{k}")
        elif isinstance(o, list):
            for i, v in enumerate(o):
                walk(v, f"{path}[{i}]")

    walk(cand, "")
    out["accepted_candidate"] = {
        "path": CAND,
        "byte_length": size(CAND),
        "sha256": sha(CAND),
        "embedded_status": cand.get("status"),
        "candidate_identity": cand.get("candidate_identity"),
        "compatibility_epoch": cand.get("compatibility_epoch"),
        "held_unavailable_count": len(held),
        "held_unavailable_all_identity_null": all(i is None for _, i in held),
        "held_unavailable_paths": [p for p, _ in held],
    }
    out["accepted_snapshot"] = {"path": SNAP, "sha256": sha(SNAP)}
    notice_txt = (REPO_ROOT / NOTICE_0206).read_text(encoding="utf-8")
    out["notice_0206_states_candidate_sha"] = sha(CAND) in notice_txt
    out["notice_0206_states_snapshot_sha"] = sha(SNAP) in notice_txt
    out["notice_0206_states_byte_length"] = "`14191`" in notice_txt and size(CAND) == 14191
    st = (REPO_ROOT / ROOT0206_STATUS).read_text(encoding="utf-8")
    out["root_0206_status_accepted_sow_sha_matches_live"] = sha(ROOT0206_SOW) in st
    out["root_0206_current_state_line"] = next(l for l in st.splitlines() if l.startswith("**Current State:**"))
    out["plan_pin_sha_matches_workplan"] = sha(PLAN) in (REPO_ROOT / WORKPLAN).read_text(encoding="utf-8")
    dg = (REPO_ROOT / NOTICE_DGOV35).read_text(encoding="utf-8")
    out["root_agents_sha_matches_dgov35_notice_post_image"] = sha(ROOT_AGENTS) in dg
    app_rows = list(csv.DictReader((REPO_ROOT / APP_TM).open(encoding="utf-8")))
    out["app_tm"] = {
        "path": APP_TM,
        "sha256": sha(APP_TM),
        "rows": len(app_rows),
        "OPEN": sorted(r["ActionItemID"] for r in app_rows if r["Status"] == "OPEN"),
        "DEFERRED": sorted(r["ActionItemID"] for r in app_rows if r["Status"] == "DEFERRED"),
        "other": sorted(r["ActionItemID"] for r in app_rows if r["Status"] not in ("OPEN", "DEFERRED")),
    }
    root_rows = list(csv.DictReader((REPO_ROOT / ROOT_TM).open(encoding="utf-8")))
    out["root_tm"] = {
        "path": ROOT_TM,
        "sha256": sha(ROOT_TM),
        "rows": len(root_rows),
        "by_status": {s: sorted(r["ActionItemID"] for r in root_rows if r["Status"] == s) for s in sorted({r["Status"] for r in root_rows})},
        "TM-ROOT-122_in_live_register": any(r["ActionItemID"] == "TM-ROOT-122" for r in root_rows),
    }
    closed = list(csv.DictReader((REPO_ROOT / ROOT_TM_CLOSED).open(encoding="utf-8")))
    r122 = next((r for r in closed if r["ActionItemID"] == "TM-ROOT-122"), None)
    out["TM-ROOT-122_closed_row"] = {k: r122[k] for k in ("Status", "Disposition", "Closed")} if r122 else None
    corpus = json.loads((REPO_ROOT / CORPUS).read_text(encoding="utf-8"))
    out["authority_corpus"] = {"path": CORPUS, "sha256": sha(CORPUS), "current_version": corpus.get("current_version")}
    out["app_contract_sha256"] = sha(APP_CONTRACT)
    rq = (REPO_ROOT / RQG).read_text(encoding="utf-8").splitlines()
    out["rqg_section13_lines"] = [i + 1 for i, l in enumerate(rq) if l.startswith("## 13") or l.startswith("## 14")]
    ac = (REPO_ROOT / APP_CONTRACT).read_text(encoding="utf-8").splitlines()

    def line_of(tag: str) -> int | None:
        for i, l in enumerate(ac):
            if l.startswith(f"| **{tag}**"):
                return i + 1
        return None

    out["app_contract_clause_lines"] = {t: line_of(t) for t in ("K-CONTROL-1", "K-ROLE-2", "K-NET-1", "K-KEY-1", "K-EVENT-3", "K-EVENT-4", "K-EVENT-6", "K-CONSENT-1", "K-UNTYPED-1", "K-ENGINE-6")}
    out["k_sdk_5_present_in"] = {
        "app_contract": "K-SDK-5" in "\n".join(ac),
        "root_contract": "K-SDK-5" in (REPO_ROOT / ROOT_CONTRACT).read_text(encoding="utf-8"),
        "sca8_contract_amendments_proposed": "K-SDK-5" in (REPO_ROOT / SCA8_CA).read_text(encoding="utf-8"),
    }
    rr = REPO_ROOT / f"{APP}/execution/PKG-08_Agent_Suite_Pipeline_Dispatch_and_Subagent_Governance/1_Working/DEL-08-04_Type_2_Subagent_Governance_Bridge/_run_records"
    out["dapp103_packet_artifacts_under_del0804_run_records"] = sorted(p.name for p in rr.iterdir() if "103" in p.name or "replay" in p.name.lower())
    succ = REPO_ROOT / f"{ROOT0206}/_run_records"
    out["root_0206_run_record_dirs"] = sorted(p.name for p in succ.iterdir())
    return out


# ---- plan extraction (meaning only) ----------------------------------------------------------
def plan_rows() -> dict:
    import re
    from html.parser import HTMLParser

    class P(HTMLParser):
        def __init__(self):
            super().__init__()
            self.rows, self.cur, self.cell = [], None, None

        def handle_starttag(self, t, a):
            if t == "tr":
                self.cur = []
            if t in ("td", "th"):
                self.cell = []

        def handle_endtag(self, t):
            if t in ("td", "th") and self.cur is not None and self.cell is not None:
                self.cur.append(" ".join("".join(self.cell).split()))
                self.cell = None
            if t == "tr" and self.cur is not None:
                self.rows.append(self.cur)
                self.cur = None

        def handle_data(self, d):
            if self.cell is not None:
                self.cell.append(d)

    q = P()
    q.feed((REPO_ROOT / PLAN).read_text(encoding="utf-8"))
    want = {}
    for r in q.rows:
        if not r:
            continue
        key = r[0]
        if key in ("AT-053", "G0", "G0.5", "G1", "WP-01") and key not in want:
            want[key] = r
        if key == "Contracts and carriers" and "AT-053" in " ".join(r):
            want["Contracts and carriers"] = r
    return want


# ---- content -------------------------------------------------------------------------------
def sections(lc: dict) -> list[dict]:
    S: list[dict] = []

    # 1. amendments
    rows1 = [
        row("D-GOV-35 — delegated-harness-native class (Root decision; supersedes D-GOV-14 item 7 for the native class only; Chirality-managed delegation preserved). R1 title: 'D-GOV-35, DEL-02-03 M2 application, SCA-004 Gate 1, TM-ROOT-107'.",
            "ROOT_DECISION",
            "ACCEPTED at Root (decision record; live Root `AGENTS.md` SHA-256 equals the post-image the routed notice states: " + ("MATCH" if lc["root_agents_sha_matches_dgov35_notice_post_image"] else "MISMATCH") + "). Routed to App as `NOTICE_D-GOV-35_...` (coordination, not App authority). App consumption seated: `docs/CONTRACT.md` v20 K-UNTYPED-1 (L" + str(lc["app_contract_clause_lines"]["K-UNTYPED-1"]) + ") and K-ROLE-2 (L" + str(lc["app_contract_clause_lines"]["K-ROLE-2"]) + "); carriers DEL-08-04-V3-01, DEL-08-05-V3-01, DEL-09-02-V3-01 — all `NOT_SELECTABLE_UNTIL` Root WP-03/WP-05 fixtures. The notice's App-local `AGENTS.md` / packaged instruction-root-mirror follow-on has no seated Remaining item and no S-row: TBD — resolves by a recorded App adopt/amend/decline act (SCOPE_CHANGE or an explicit no-change record).",
            [DGOV35, ROOT_AGENTS, NOTICE_DGOV35, APP_CONTRACT, ST0804, ST0805, ST0902, R1, APP_AGENTS]),
        row("Root DEL-02-03 M2 — root `AGENTS.md` instruction tranche (untyped delegated-harness entry, two-class evidence rule, explicit-role semantics). R1.",
            "ROOT_INSTRUCTION",
            "APPLIED at Root: `_run_records/DEL-02-03-M2-APPLY-001/APPLICATION_RECORD.md`; the live Root `AGENTS.md` 'Delegation and Entry Rules' carries the two executable classes. App consumes it only through the D-GOV-35 notice; no App carrier item is owed for the Root instruction text itself.",
            [ROOT0203_M2, ROOT_AGENTS, R1]),
        row("Root SCA-004 — Gate 1 (R1), Gate 2 (R2), Gates 3/4 (R3), Gate-5 append/execution/re-authorization/confirmation (R4, R5, R6), carrier SOW acceptance (R7), estimate snapshot (R8), schedule basis (R9), schedule-basis transcription authorization (R10).",
            "ROOT_SCOPE_CHANGE",
            "ACCEPTED and APPLIED at Root: `execution/_ScopeChange/_LATEST.md` reads `CLOSED_FOR_SCOPE_CHANGE_ONLY` (revision 1.3; Git effect PR #633 merge `6d4438d8d3a580b65d6d50ad497dadfe07f177f2`); exact implementation carriers DEL-02-07 … DEL-02-12 (+ DEL-04-11) exist with SOWs accepted at R7-A. Root pathway seating was NOT SELECTED by the owner on 2026-09-03 (A12 record): at this basis the Root carriers carry no merged v3 `Remaining` items (seating packet MAPPING). App consumes SCA-004 only as `ROOT_OWNED` dependency targets; App writes no Root surface.",
            [ROOT_SCA_LATEST, ROOT_SCA004_G5, R1, R2, R3, R4, R5, R6, R7, R8, R9, R10, A12, SEAT_MAP]),
        row("Root K-CONTROL-1 amendment (two-socket accepted design; steer 2026-08-23; accepted through R7-A via the DEL-02-07 scope contract).",
            "ROOT_CONTRACT",
            "ACCEPTED as contract text: Root `docs/CONTRACT.md` K-CONTROL-1 (design accepted, second socket not implemented; exactly one control socket live); App `docs/CONTRACT.md` v20 K-CONTROL-1 (L" + str(lc["app_contract_clause_lines"]["K-CONTROL-1"]) + ") mirrors it. Implementation HELD: DEL-02-07/WP-03 pathway and the DEL-02-06 `implementation_act` binding. App observation seat: DEL-09-04-V3-01 (`NOT_SELECTABLE_UNTIL`).",
            [ROOT_CONTRACT, APP_CONTRACT, STEER_KCONTROL1, R7, ST0904]),
        row("Root K-ROLE-2 (roles name authority, not a durable model assignment).",
            "ROOT_CONTRACT",
            "ACCEPTED as contract text in Root `docs/CONTRACT.md` and App `docs/CONTRACT.md` v20 (L" + str(lc["app_contract_clause_lines"]["K-ROLE-2"]) + "). G-ROLE proof is `ROOT_OWNED`, `OPEN`; App label seats DEL-02-05-V3-02 (`SELECTABLE`), DEL-08-04-V3-01 / DEL-08-05-V3-01 (parked); Work/Agents role-entry UX unseated (S-7).",
            [ROOT_CONTRACT, APP_CONTRACT, ST0205, ST0804, ST0805, SEAT_MAP]),
        row("R11 — routing of the SCA-APP-008 Gate-5 notice.",
            "ROOT_RULING",
            "ROUTED: Root `execution/_Coordination/NOTICE_2026-08-24_APP_SCA-APP-008_GATE5_APPLIED_STATE.md` (Root ingestion PR #668 merge `eb2ea19db5b86ad33760345d274b828d7a12e6cc` per the App closure addendum). No App carrier obligation.",
            [R11, ROOT_NOTICE_SCA008, SCA8_ADD]),
        row("R12 (C1 supply authorization: App Server 0.149.0), R13 (resumption after the upstream signing defect), R14 (egress-inventory amendment and ancillary-executable grant), R15 (App Server 0.149.0 G2 acceptance).",
            "ROOT_SUPPLY",
            "G2 ACCEPTED at Root with documented gaps (R15; PR #673 merge `baa29d22fa034784cda221b2929061213e83ec91`): Root DEL-02-08 run record `APP-SERVER-0.149.0-G2-CANDIDATE-2026-08-24/`. App consumption not yet routed: DEL-03-01-V3-01 exact-pin claims `NOT_SELECTABLE_UNTIL` consumable supply and G-WIRE; DEL-09-05-V3-02 SBOM/notices input `SELECTABLE`; the DEL-04-01 App Server probe is UNSEATED (S-1).",
            [R12, R13, R14, R15, ROOT0208_G2, ST0301, ST0905, ST0401, SEAT_MAP]),
        row("R16 — G0.5 binding routing, Tier-0 disposition, OUT-002 completion attempt, and bounded feasibility spikes.",
            "ROOT_RULING",
            "R16-A routed the ten bindings (Section 2); R16-B adopted `CONTINUE_SEPARATE_WITH_EXPLICIT_COORDINATION_ONLY`; R16-C withheld implementation; R16-E preserved TM-ROOT-106/122 as open, unruled G1 blockers; R16-D's single execution attempt was spent and retired by R17-B. G0.5 not declared passed (`source_identity`, `implementation_act` unavailable).",
            [R16, R17]),
        row("R17 — reject the R16 execution candidate (PR #676) and adopt deliverable-seated v3 RC completion; pinned plan adoption (R17-C).",
            "ROOT_RULING",
            "Pinned completion and acceptance reference: `" + PLAN + "` SHA-256 recomputed = `" + sha(PLAN) + "` (workplan pin " + ("MATCH" if lc["plan_pin_sha_matches_workplan"] else "MISMATCH") + "); meaning only, never authority/status/queue. Root seating candidate: NOT SELECTED on 2026-09-03 — Root-side seating UNSEATED at this basis. App counterpart: A12 seating ACCEPTED (PR #681 merge `" + BASIS + "`, this basis).",
            [R17, PLAN, A12, WORKPLAN, SEAT_MAP]),
        row("R18 — App Electron-authority notice ingestion and TM-ROOT-122 disposition.",
            "ROOT_RULING",
            "APPLIED at Root: App echo ingested as `ADOPTED_AS_COORDINATION_INPUT` (Root copy); TM-ROOT-122 `CLOSED` / `RESOLVED_BY_DECISION` on 2026-09-03 (PR #682 merge `fd55023e2`), archived in `REGISTER_CLOSED.csv` (live check: " + str(lc["TM-ROOT-122_closed_row"]) + "). TM-ROOT-106 untouched; G1 not passed.",
            [R18, ROOT_NOTICE_TM122, ROOT_TM122_RULING, ROOT_TM_CLOSED, ROOT_TM]),
        row("G0 record — Chirality App v3.0.0-rc.1 owner rulings of 2026-08-22 (RC scope, native delegation outcome, Codex Preview label, no App Sandbox, command-network denial, root-home posture, read-only fallback, TM-APP-025, triage instruction).",
            "APP_RULING",
            "ACCEPTED; seated through the accepted `Carrier_Map.md` 'Required owner-amendment seating' table (G0 D1, A3, A4, A5, A7, A8, A9, B1, B2, B4, D2, A1) and the A11 triage dispositions. TM-APP-030 (G0 B2) remains an owner decision at G-HELPER; TM-ROOT-122 (G0 B4) is now closed by R18.",
            [G0, SCA8_CM, A11]),
        row("A1 — G0.25 gate ruling (WP-00 closure) and the A1 re-stage rule.",
            "APP_RULING",
            "ACCEPTED: DEL-09-04 `_run_records/R21_…` records the R20 owner proof; the A1 re-stage rule is a standing Step 0 declaration in the successor workplan. This tranche touches no `frontend/` path, so the rule does not fire here.",
            [A1, R21, WORKPLAN]),
        row("SCA-APP-008 — Gate-1/2 acceptance (A2), Gate-3/4 approval (A3), concordance rulings C-01/C-02 (A4), post-concordance sequencing (A5), post-ratification concordance resolutions (A6), Phase-2b candidate approval (A7), Gate-5 authorization / register-anchor correction / pointer disposition (A8), `_LATEST.md` pointer act (A9).",
            "APP_SCOPE_CHANGE",
            "ACCEPTED and APPLIED for scope change only: App `_ScopeChange/_LATEST.md` reads `CLOSED_FOR_SCOPE_CHANGE_ONLY`; decomposition content commit `d6f6cadb2be0c6e2e9c5ba331a553a54c60a8a0f` (PR #662 merge `d5e40b3c25fe527919f1d2d2a31ea97ce2835795`); pointer act PR #665 (`4251530ec8a5d5b7abfc035cbdde63dab7fa80f3`); Root ingestion R11. App `docs/CONTRACT.md` amendment-history row `SCA-APP-008` carries the concordance-approved clauses (Section 1b). Post-application closure audit remains `WARNINGS` (one nine-node SCC surfaced, not linearized). Nineteen carriers re-pinned and seated by A12; seven obligations UNSEATED (Section 7).",
            [APP_SCA_LATEST, DECOMP, SCA8_CM, SCA8_IA, SCA8_ADD, APP_CONTRACT, A2, A3, A4, A5, A6, A7, A8, A9, ROOT_NOTICE_SCA008]),
        row("Plan §8.2 'K-SDK-5 (proposed)' — root-home isolation and exact-pin compatibility invariant.",
            "APP_CONTRACT",
            "UNSEATED: `K-SDK-5` is present in App `docs/CONTRACT.md` v20: " + str(lc["k_sdk_5_present_in"]["app_contract"]) + "; Root `docs/CONTRACT.md`: " + str(lc["k_sdk_5_present_in"]["root_contract"]) + "; SCA-APP-008 `Contract_Amendments.proposed.md`: " + str(lc["k_sdk_5_present_in"]["sca8_contract_amendments_proposed"]) + ". No carrier names it. TBD — resolves only by a later contract-amendment act (Root or App instrument) that names the clause and its carrier, or by an explicit no-change record.",
            [APP_CONTRACT, ROOT_CONTRACT, SCA8_CA, PLAN]),
        row("A10 — G0 Task-Management triage authorization; A11 — G0 triage dispositions and Electron-drift E2 authorization.",
            "APP_RULING",
            "APPLIED: `OWNER_RULING_2026-09-03_G0_V3_TRIAGE.md`; live register SHA-256 recomputed = `" + sha(APP_TM) + "` (A11 post-state `OPEN=8 DEFERRED=3`; live count OPEN=" + str(len(lc["app_tm"]["OPEN"])) + ", DEFERRED=" + str(len(lc["app_tm"]["DEFERRED"])) + "). TM-APP-025 closed `RESOLVED_BY_DECISION`; 027/028/032 `DEFERRED` `STILL_BLOCKED`; 030 `OPEN` for G-HELPER. E2 concordance executed as PR #680 (corpus v20; App `docs/CONTRACT.md` SHA-256 recomputed = `" + sha(APP_CONTRACT) + "`); combined echo prepared `READY_TO_ROUTE` on the App surface and ingested at Root by R18.",
            [A10, A11, OWNER_RULING, APP_TM, APP_CONTRACT, CORPUS, NOTICE_TM122_APP, ROOT_NOTICE_TM122, R18]),
        row("A12 — v3 pathway seating authorization (App counterpart of Root R17).",
            "APP_RULING",
            "ACCEPTED (selectability only): PR #681 merge `" + BASIS + "` = this record's basis; nineteen carriers re-pinned to `d6f6cadb2…`; thirty-one `Remaining` items seeded, nine `SELECTABLE`; successor workplan selected by `LOOP_INIT.md`; DEL-01-01-V3-01 (this record) is the AT-053 App half. No implementation, lifecycle, host-mutation, signing, release, publication, reliance, or Root act.",
            [A12, SEAT_MAP, SEAT_COV, WORKPLAN, SOW0101, SEAT_IDL]),
        row("D-APP-97 (release preparation, C1) and hard fence F-APP-2.",
            "APP_DECISION",
            "HELD through preparation: `RULED (C1)`; lift only at G6a against the exact owner-named candidate (G0 D2). Carriers DEL-09-04/05/06 preparation items; DEL-09-05-V3-05 `NOT_SELECTABLE_UNTIL` G6a.",
            [D97, DREG, WORKPLAN, ST0905]),
        row("D-APP-98 — Electron 43.2.0 App authority (D-APP-72 successor for that single fact).",
            "APP_DECISION",
            "ACCEPTED: carried in App `docs/CONTRACT.md` v20 K-ENGINE-6 (L" + str(lc["app_contract_clause_lines"]["K-ENGINE-6"]) + ") after the A11 E2 concordance; TM-ROOT-122 closed on it (R18). No pin, lockfile, or supply change (A11 E3/E4 not selected).",
            [D98, APP_CONTRACT, R18, A11]),
    ]
    S.append({"id": "1", "title": "Root and App amendments in the v3 pathway → accepted carrier or explicit unseated state", "rows": rows1})

    # 1b. contract clauses
    cl = lc["app_contract_clause_lines"]
    clause_rows = [
        ("K-CONTROL-1", "Root daemon owns `{userData}/runtime` control surfaces; one live socket; accepted second supervisor socket not implemented; no third socket, no TCP.", "DEL-09-04-V3-01 observation (`NOT_SELECTABLE_UNTIL` Root DEL-02-07 bytes + implementation act); Root DEL-02-07 implementation HELD.", [APP_CONTRACT, ROOT_CONTRACT, ST0904]),
        ("K-ROLE-2", "Roles name authority; `role not mechanically enforced` label; `instruction-asserted` evidence; actual adapter/provider/model recorded.", "DEL-02-05-V3-02 labels (`SELECTABLE`); DEL-08-04-V3-01, DEL-08-05-V3-01 (parked); Work/Agents role-entry UX unseated (S-7).", [APP_CONTRACT, ST0205, ST0804, ST0805]),
        ("K-NET-1", "Deny-by-default; enumerated transports incl. exact accepted OpenAI account/model/turn endpoints; three per-root command-network postures.", "DEL-04-05-V3-02 and DEL-09-06-V3-02 (`NOT_SELECTABLE_UNTIL` Root DEL-02-09/DEL-02-10 returns); F-APP-1 remains a hard fence.", [APP_CONTRACT, ST0405, ST0906, WORKPLAN]),
        ("K-KEY-1", "Credentials and ceremony data are private state; typed `missing` / `storageUnavailable` / `decryptFailed` / `available`; no ambient `~/.codex`.", "DEL-04-05-V3-01, DEL-02-05-V3-01, DEL-09-06-V3-01 (`SELECTABLE`); DEL-09-06-V3-03 and DEL-09-05-V3-04 (parked on owner host act).", [APP_CONTRACT, ST0405, ST0205, ST0906, ST0905]),
        ("K-EVENT-3", "Exactly one durable terminal outcome in closed `HarnessEvent` schema v2 (completed / failed / interrupted / cancelled).", "DEL-05-02-V3-01, DEL-09-03-V3-01 (`NOT_SELECTABLE_UNTIL` Root schema v2); Root TM-ROOT-108 carries the accepted-turn recovery defect.", [APP_CONTRACT, ST0502, ST0903, ROOT_TM]),
        ("K-EVENT-4", "Root-owned shared-runtime session store is the canonical audit record; project-local store is a legacy lazily-migrated source.", "DEL-05-01-V3-01 (`SELECTABLE`, lazy non-destructive access), DEL-05-01-V3-02 (parked); K-EVENT-4 live legacy path is a plan §8.4 Task Management candidate with no seated item (TBD).", [APP_CONTRACT, ST0501, PLAN]),
        ("K-EVENT-6", "Only closed-schema fields cross sinks; structural redaction before every sink; unknown types become bounded diagnostic codes.", "DEL-05-03-V3-01, DEL-03-03-V3-01 (`NOT_SELECTABLE_UNTIL` Root schema v2; G-WIRE).", [APP_CONTRACT, ST0503, ST0303]),
        ("K-CONSENT-1", "`HostedEngineConsentPort` is the sole coordinator boundary; per-root consent; revocation retires the root generation.", "DEL-02-05-V3-02 fixtures behind a fake port (`SELECTABLE`); DEL-02-05-V3-03 live consumption (`NOT_SELECTABLE_UNTIL` Root DEL-02-09 contract, G3/G-CSP/G4).", [APP_CONTRACT, ST0205]),
        ("K-UNTYPED-1", "Untyped native descent only inside the hard envelope; no role by descent; managed descendants keep their checks.", "DEL-08-04-V3-01 (`NOT_SELECTABLE_UNTIL` Root WP-03/WP-05 fixtures); `subagent-governance.ts:205-213` changes only under the accepted native ruling.", [APP_CONTRACT, ST0804, NOTICE_DGOV35]),
        ("K-ENGINE-6", "Strategic lens: governance/UI/audit/lifecycle/adapter layer over provider harness mechanics; bounded Pi 0.80.10 exception; Electron 43.2.0 prerequisite (D-APP-98 successor).", "Applied to every selection (workplan Step 1). Note: the clause's governed Pi `0.80.10` versus the shipped `0.82.0` is exactly TM-ROOT-106 (open, unruled G1 blocker) — no App carrier; Root decision plus validation evidence required.", [APP_CONTRACT, WORKPLAN, ROOT_TM]),
    ]
    rows1b = [row(f"{k} (App `docs/CONTRACT.md` v20 L{cl[k]}): {d}", "APP_CONTRACT", c, cites) for k, d, c, cites in clause_rows]
    rows1b.append(row("Enforcement-map rows added by SCA-APP-008 (delegated-harness supervisor/control sockets; `HostedEngineConsentPort`; role entry and descendant classification; event codec/sinks; renderer credential IPC; exact-candidate release validation).", "APP_CONTRACT", "Present in App `docs/CONTRACT.md` v20 §2 enforcement map; each row's runtime evidence follows the carrier items above; none is claimed proved here.", [APP_CONTRACT]))
    S.append({"id": "1b", "title": "SCA-APP-008 contract amendments present at corpus v20 → enforcement carrier items", "rows": rows1b})

    # 2. ten bindings
    routing = {
        "binding_groups.2_source_and_release_identities.source_identity": ("Remains `HELD_UNAVAILABLE` until exact proposed implementation bytes exist and the Root accountable human accepts their exact source identity.", "Root owner at G0.5. App dependants parked: DEL-09-04-V3-01; source-based conformance (DEL-03-01-V3-01)."),
        "binding_groups.2_source_and_release_identities.release_identity": ("Remains `HELD_UNAVAILABLE` for the G6a accountable-human release act.", "Owner at G6a. App dependants parked: DEL-09-05-V3-05 (WP-11); D-APP-97/F-APP-2 active."),
        "binding_groups.4_conformance_or_migration_evidence.clients[0]": ("Remains `HELD_UNAVAILABLE`; routed to the App-owned G5/G7 conformance fan-in.", "App G5/G7 fan-in carriers: DEL-09-01-V3-01, DEL-09-02-V3-01, DEL-09-03-V3-01/02, DEL-09-06-V3-02 (all parked); TM-APP-027/028/032 triggers name this acceptance lineage."),
        "binding_groups.4_conformance_or_migration_evidence.clients[1]": ("Remains `HELD_UNAVAILABLE`; routed to the Root-owned G5/G7 conformance fan-in.", "Root CLI; not an App carrier obligation."),
        "binding_groups.5_root_semantic_and_regression_evidence": ("Remains `HELD_UNAVAILABLE`; routed to accepted Root implementation followed by G5/G7 evidence acceptance.", "Root; App consumes via routed notice only."),
        "binding_groups.6_census_relationship_routing_notice_and_findings.notice": ("Remains `HELD_UNAVAILABLE`; routed to the affected owning loops before cutover/release fan-in.", "Owning loops (App included) accept the notice when routed; no such notice exists under App `NOTICE_*` at this basis."),
        "binding_groups.6_census_relationship_routing_notice_and_findings.tier_0_relationship": ("The relationship is substantively disposed by R16-B. Root may materialize an immutable successor relationship record and successor binding-disposition snapshot; it must not rewrite the previously accepted package bytes.", "Disposed `CONTINUE_SEPARATE_WITH_EXPLICIT_COORDINATION_ONLY` (R16-B; preserved by R17-B/R18-C). The accepted bytes still record the binding `HELD_UNAVAILABLE`; no successor binding-disposition snapshot exists under Root DEL-02-06 `_run_records/` at this basis (live listing: " + ", ".join(lc["root_0206_run_record_dirs"]) + ") — the R16-D N0 transcription was in the rejected PR #676. TBD: a Root successor snapshot."),
        "binding_groups.8_accountable_human_acts.implementation_act": ("Remains `HELD_UNAVAILABLE` until the feasibility results are frozen or rejected and exact sealed WP-03/WP-05 implementation briefs exist for a separate accountable-human act.", "Root owner. App dependants parked: DEL-09-04-V3-01; every WP-05 consumption item."),
        "binding_groups.8_accountable_human_acts.cutover_act": ("Remains `HELD_UNAVAILABLE` until the required G2-G5 fan-in is accepted.", "Owner; never inferred from implementation. No App carrier item."),
        "binding_groups.8_accountable_human_acts.release_act": ("Remains `HELD_UNAVAILABLE` for G6a.", "Owner at G6a; DEL-09-05-V3-05 fires only after the ruling."),
    }
    snapshot_order = [
        "binding_groups.2_source_and_release_identities.source_identity",
        "binding_groups.2_source_and_release_identities.release_identity",
        "binding_groups.4_conformance_or_migration_evidence.clients[0]",
        "binding_groups.4_conformance_or_migration_evidence.clients[1]",
        "binding_groups.5_root_semantic_and_regression_evidence",
        "binding_groups.6_census_relationship_routing_notice_and_findings.notice",
        "binding_groups.6_census_relationship_routing_notice_and_findings.tier_0_relationship",
        "binding_groups.8_accountable_human_acts.implementation_act",
        "binding_groups.8_accountable_human_acts.cutover_act",
        "binding_groups.8_accountable_human_acts.release_act",
    ]
    live_set = set(lc["accepted_candidate"]["held_unavailable_paths"])
    if live_set != set(snapshot_order):
        raise SystemExit(f"live HELD_UNAVAILABLE set differs from the snapshot enumeration: {sorted(live_set ^ set(snapshot_order))}")
    rows2 = []
    for p in snapshot_order:
        disp, app = routing[p]
        rows2.append(row(p, "HELD_BINDING", f"`HELD_UNAVAILABLE` (accepted bytes; `identity: null`). R16-A: {disp} App relation: {app} Lift inferred: NO.", [CAND, SNAP, NOTICE_0206, R16, R17, R18]))
    S.append({"id": "2", "title": "The ten held DEL-02-06 bindings (verbatim names) — current state and R16-A routing", "rows": rows2})

    # 3. RQG §13
    conds = [
        ("runtime-package promotion preserves current Claude/stub/Pi behavior", "DEL-09-01-V3-01 (`NOT_SELECTABLE_UNTIL` the first v3 product change merges; AT-037 native-engine regression); DEL-03-01-V3-01 (parked on Root API v2).", "Root DEL-02-12 (Root conformance fan-in).", "gated — no v3 §13 evidence bytes exist; DEL-09-01's baseline Section 8 preservation evidence is pre-v3 and is not a §13 v3 mapping.", [RQG, ST0901, ST0301, SEAT_MAP]),
        ("Desktop and CLI use one daemon, session store, lock system, credential owner, and interruption state", "DEL-03-01-V3-01 (client conformance), DEL-05-01-V3-02 (daemon session shape), DEL-09-01-V3-01 — all parked.", "Root DEL-02-06/DEL-02-11/DEL-02-12 (K-RUNTIME-1 owner); Root CLI evidence is the held `clients[1]` binding.", "gated (Root-owned semantics; App consumption parked). Root TM-ROOT-108 (accepted-turn recovery across restart) is an open Root defect touching interruption/terminal state.", [RQG, ST0301, ST0501, ST0901, ROOT_TM]),
        ("the control plane has correct Unix-socket permissions, project-scoped authorization, stale recovery, and no TCP listener", "DEL-09-04-V3-01 (package/fuse/entitlement observation; parked). No App item owns socket tests: K-CONTROL-1 names Root daemon ownership.", "Root DEL-02-07 (K-CONTROL-1 live single-socket tests; design-gated supervisor-socket tests).", "gated — Root-owned; App evidence absent by design (App is neither owner nor writer of control state).", [RQG, APP_CONTRACT, ROOT_CONTRACT, ST0904]),
        ("model switching obeys explicit activation, drain, timeout, no-force, `NO_MODEL`, no-helper-unload, and no-fallback rules", "DEL-03-01-V3-01 (AT-017 no automatic fallback, App-client portion; parked).", "Root DEL-02-10/DEL-02-12; TM-ROOT-106 (Pi 0.82.0 vs 0.80.10) is the open G1 blocker on the Pi limb.", "gated — no App evidence bytes; Root decision + validation evidence outstanding (TM-ROOT-106).", [RQG, ST0301, ROOT_TM, APP_CONTRACT]),
        ("the app-dev and PEC pilot paths pass with canonical evidence and actual-model attribution", "app-dev pilot: DEL-09-01-V3-01 / DEL-09-02-V3-01 (parked). PEC pilot: no seated v3 item — TM-APP-029 (`OPEN`) records that a governed live PEC daemon-consumption proof remains absent.", "Root DEL-02-12; PEC loop by notice.", "absent (PEC pilot) / gated (app-dev pilot). TBD — resolves by the TM-APP-029 bounded proof through ordinary selection plus the parked WP-10 items.", [RQG, ST0901, ST0902, APP_TM]),
        ("public export includes only generic runtime/CLI/contracts/safe adapters and excludes credentials, machine state, and private adapters", "none — no App carrier item; DEL-09-05-V3-02 (SBOM/notices) is artifact-identity evidence for the App package, not the Root public export.", "Root `exports/chirality-app/` projection; TM-ROOT-120 (`DEFERRED`, trigger: next export release act) records the export as stale; D-GOV-35 notice defers regeneration to the next Root export release.", "absent on App (not an App carrier obligation); Root-owned and deferred.", [RQG, ROOT_TM, NOTICE_DGOV35, ST0905]),
    ]
    rows3 = [row(f"RQG §13 condition {i+1}: {c}", "RQG13_CONDITION", f"App carrier(s): {a} Root/external: {r} Evidence status: {s}", cites) for i, (c, a, r, s, cites) in enumerate(conds)]
    rows3.append(row("RQG §13 preamble and closing sentence", "RQG13_CONDITION", "Preamble reads 'Before SCA-APP-003 closeout, prove:' while the active App scope-change pointer is SCA-APP-008 (`CLOSED_FOR_SCOPE_CHANGE_ONLY`); the seating packet maps §13 by condition, not by that preamble. Closing sentence: the gate is validation evidence only and grants no release, publication, signing, notarization, lifecycle, or professional-reliance authority. Recorded as an observation; not resolved here (a `docs/**` edit is outside this write locus).", [RQG, APP_SCA_LATEST, SEAT_MAP]))
    S.append({"id": "3", "title": "RQG §13 Shared Runtime Gate conditions → App carrier(s) and evidence status", "rows": rows3})

    # 4. REQ-027
    rows4 = [
        row("DEL-02-06 REQ-027 (accepted Root SOW, 'Tranche, authority, evidence, and boundary requirements')", "ROOT_SOW_REQUIREMENT",
            "Verbatim: 'The first activation shall use Context Envelope M and shall be limited to exact specification, read-only consumer inventory, evidence-matrix design, and change planning. It shall not write implementation bytes.' Accepted SOW SHA-256 recomputed = `" + sha(ROOT0206_SOW) + "`; equals the `Accepted ScopeOfWork SHA-256` line in Root DEL-02-06 `_STATUS.md`: " + ("MATCH" if lc["root_0206_status_accepted_sow_sha_matches_live"] else "MISMATCH") + ". Root DEL-02-06 lifecycle: " + lc["root_0206_current_state_line"].replace("**", "") + "; REM-002 (OUT-001…009 unproduced) and REM-003 remain.",
            [ROOT0206_SOW, ROOT0206_STATUS]),
        row("DEL-02-06 first-activation exclusion block (accepted Root SOW, Praxeology)", "ROOT_SOW_REQUIREMENT",
            "Verbatim: 'The following remain read-only and excluded from the first activation: `ScopeOfWork.md`, `_STATUS.md`, `_CONTEXT.md`, `_REFERENCES.md`, `_DEPENDENCIES.md`, `_SEMANTIC.md`, all decomposition and governance files, `runtime/**`, `agents/**`, `skills/**`, `tools/**`, App, PEC, Piping, Tier-0, and all product or release files. No client-owned write may be added by brief amendment; it requires a separate client-owned tranche.'",
            [ROOT0206_SOW]),
        row("How App consumes REQ-027 and the exclusion", "ROOT_SOW_REQUIREMENT",
            "(a) App receives DEL-02-06 outputs only through routed Root notices: the 2026-08-21 acceptance notice cites the accepted candidate JSON (byte length " + str(lc["accepted_candidate"]["byte_length"]) + ", SHA-256 recomputed = `" + sha(CAND) + "`, notice states it: " + str(lc["notice_0206_states_candidate_sha"]) + ") and the acceptance snapshot (SHA-256 recomputed = `" + sha(SNAP) + "`, notice states it: " + str(lc["notice_0206_states_snapshot_sha"]) + "). (b) Because the first activation writes no implementation bytes and keeps App read-only, every App item whose gate is 'accepted Root supervisor/runtime bytes' or the DEL-02-06 `implementation_act` (DEL-09-04-V3-01; the WP-05 consumption items) stays `NOT_SELECTABLE_UNTIL` a separate Root activation and implementation act produce and route those bytes. (c) TM-APP-027/028/032 triggers consume this acceptance lineage and are classified `STILL_BLOCKED` (A11). (d) App writes nothing to Root; the App loop consumes Root only as `ROOT_OWNED` dependency targets. (e) The candidate JSON's embedded `status` is `" + str(lc["accepted_candidate"]["embedded_status"]) + "` because acceptance does not rewrite historical bytes; the snapshot is the acceptance act.",
            [NOTICE_0206, CAND, SNAP, ST0904, ST0301, APP_TM, A11, SEAT_MAP]),
    ]
    S.append({"id": "4", "title": "DEL-02-06 REQ-027 and its exclusion, as stated in the accepted Root SOW, and App consumption", "rows": rows4})

    # 5. D-APP-103
    rows5 = [
        row("D-APP-103 — per-attempt subagent decision-replay packet (D-APP-53 §3 Option C)", "DECISION_INTERACTION",
            "Register: `RULED (B4 — packet authorized)`; 'Remaining posture is packet authorized / awaiting ruling'. Ruling file: authorizes the packet only; implementation follows a later ruling. DEL-08-04 `## Remaining` first bullet: 'Prepare the D-APP-53 §3 Option C per-attempt subagent decision-replay decision packet under D-APP-103 (packet authorized; awaiting ruling)' — it carries no `(gated: …)` suffix and no `NOT_SELECTABLE_UNTIL` state; DEL-08-04-V3-01's Depends line says 'the D-APP-103 packet item below stays separate'. SCA-APP-008 `Brief.md` interaction statement: 'D-APP-103 defers: the per-attempt decision-replay packet is prepared after SCA-APP-008 applies so it covers both descendant classes once.' Packet artifacts under DEL-08-04 `_run_records/` at this basis: " + (", ".join(lc["dapp103_packet_artifacts_under_del0804_run_records"]) or "none") + " → packet not yet prepared. TBD — resolves by (1) the DEL-08-04 packet planning node landing and (2) a later D-APP ruling on it; the native evidence model of DEL-08-04-V3-01 does not consume the authorization.",
            [DREG, D103, ST0804, SCA8_BRIEF, SCA8_CM]),
    ]
    S.append({"id": "5", "title": "D-APP-103 interaction and its seat in DEL-08-04 Remaining", "rows": rows5})

    # 6. Task Management rows
    app_map = {
        "TM-APP-027": ("DEFERRED", "Root generic-contract gate (DEL-02-06 ten bindings; expected firing G6a–G7); classified `STILL_BLOCKED` at A11 with Trigger byte-identical. Not an App carrier obligation; eventual App consumers of a ruled negotiation policy are DEL-03-01-V3-01 / DEL-03-03-V3-01 (parked).", [APP_TM, A11, NOTICE_027_028, ST0301, ST0303]),
        "TM-APP-028": ("DEFERRED", "Same Root gate; `STILL_BLOCKED`. Not an App carrier obligation; App consumer of a ruled degraded-mode contract is DEL-03-01-V3-01 (typed-unavailable consumption; parked).", [APP_TM, A11, NOTICE_027_028, ST0301]),
        "TM-APP-032": ("DEFERRED", "Root DEL-02-06 successor-identity acceptance for D-APP-48; `STILL_BLOCKED`. Not an App carrier obligation (the harness-contract pin is a coordination surface, not a seated v3 item).", [APP_TM, A11, NOTICE_TM117]),
        "TM-APP-029": ("OPEN", "Maps to RQG §13 condition 5 (PEC pilot path). No seated v3 carrier item; bounded proof through ordinary selection with PEC coordination by notice. Evidence absent.", [APP_TM, RQG]),
        "TM-APP-030": ("OPEN", "Daemon/helper bundle identity — owner decision at G-HELPER (G0 B2; A11 Step 2b). AssociatedWith DEL-09-04, but no seated item carries the decision; G-HELPER `HELD`. Not a carrier obligation.", [APP_TM, A11, SEAT_MAP]),
        "TM-APP-033": ("OPEN", "D-APP-49 focused-audit dependency/Node warnings — App maintenance; not a v3 carrier obligation.", [APP_TM]),
        "TM-APP-034": ("OPEN", "DEL-03 stable-ID reuse provenance audit (SCA-APP-007) — not a v3 carrier obligation.", [APP_TM]),
        "TM-APP-036": ("OPEN", "D-APP-86 parity residue: DEL-02-02/DEL-08-02/DEL-05-04 pointer review — not a v3 carrier obligation (DEL-02-02-V3-01 and DEL-05-04-V3-01 are distinct seated items).", [APP_TM, ST0202, ST0504]),
        "TM-APP-038": ("OPEN", "CASE-SCC-001 case-surface reconciliation on DEL-00-02 (HIGH) — discovery-integrity concern; not a v3 carrier obligation.", [APP_TM]),
        "TM-APP-040": ("OPEN", "Notice-ledger adoption / scanner scoping — no notice ledger exists; this record cites notices by path and SHA-256 instead. Not a carrier obligation; owner decision pending.", [APP_TM]),
        "TM-APP-042": ("OPEN", "Retained D-APP-94 probe-root cleanup — owner-gated disposition; not a carrier obligation.", [APP_TM]),
    }
    rows6 = []
    app_rows = list(csv.DictReader((REPO_ROOT / APP_TM).open(encoding="utf-8")))
    for r in sorted(app_rows, key=lambda r: r["ActionItemID"]):
        aid = r["ActionItemID"]
        exp_status, text, cites = app_map[aid]
        st_note = "" if r["Status"] == exp_status else f" (LIVE STATUS `{r['Status']}` DIFFERS FROM EXPECTED `{exp_status}`)"
        rows6.append(row(f"{aid} — {r['Title']}", "TM_APP_ROW", f"Live status `{r['Status']}`{st_note}. {text}", cites))
    root_rel = {
        "TM-ROOT-106": "Root/App Pi 0.82.0 concordance and supply-chain validation — open, unruled G1 blocker (R16-E, R17, R18-C); plan §8.4: resolve or isolate before G1. App `docs/CONTRACT.md` K-ENGINE-6 still governs Pi `0.80.10`. No App carrier item; closure needs a Root decision record plus validation evidence (`RESOLVED_BY_DECISION` target). App consumes via routed notice.",
        "TM-ROOT-108": "Accepted-turn recovery across daemon restart (DEL-02-06; Chirality App associated) — Root-owned; touches K-EVENT-3 exactly-one-terminal semantics consumed by DEL-05-02-V3-01 / DEL-09-03-V3-01 (parked). Not an App carrier obligation.",
        "TM-ROOT-035": "Runtime identity before code (DEL-02-06 activation ladder) — Root; not an App carrier obligation.",
        "TM-ROOT-042": "Logical composition vs physical bundling and cadence (partially decided) — Root; not an App carrier obligation.",
        "TM-ROOT-039": "Reusable work surface: Root requirement, App capability, or both — DEFERRED; App-associated; not a v3 carrier obligation.",
        "TM-ROOT-104": "Product-delivery direction: Root product-basis disposition — DEFERRED; App-associated; not a v3 carrier obligation.",
        "TM-ROOT-119": "Loop-pattern convergence options (App among the loops) — DEFERRED; not a carrier obligation.",
        "TM-ROOT-120": "Public-export derivatives stale — DEFERRED until the next export release act; maps to RQG §13 condition 6 (Root-owned).",
        "TM-ROOT-123": "TM105 evidence qualification / no-TBD successor gate — DEFERRED; Root generic-contract lineage behind TM-APP-027/028; not an App carrier obligation.",
    }
    root_rows = list(csv.DictReader((REPO_ROOT / ROOT_TM).open(encoding="utf-8")))
    for r in sorted(root_rows, key=lambda r: r["ActionItemID"]):
        aid = r["ActionItemID"]
        txt = root_rel.get(aid, "Not relevant to the App v3 pathway carriers; not a carrier obligation.")
        rows6.append(row(f"{aid} — {r['Title']}", "TM_ROOT_ROW", f"Live status `{r['Status']}`. {txt}", [ROOT_TM] + ([R16, R17, R18, APP_CONTRACT, PLAN] if aid == "TM-ROOT-106" else [])))
    rows6.append(row("TM-ROOT-122 — Electron authority drift (closed)", "TM_ROOT_ROW", "`CLOSED` / `RESOLVED_BY_DECISION` on 2026-09-03 by R18 (PR #682 merge `fd55023e2`); relocated to `REGISTER_CLOSED.csv` (live: " + str(lc["TM-ROOT-122_closed_row"]) + "; present in live register: " + str(lc["root_tm"]["TM-ROOT-122_in_live_register"]) + "). Closure of one named blocker is not a G1 ruling.", [ROOT_TM_CLOSED, ROOT_TM122_RULING, R18]))
    S.append({"id": "6", "title": "Open App Task Management rows and open Root rows relevant to the App pathway → carrier/gate or 'not a carrier obligation'", "rows": rows6})

    # 7. S-1..S-7 verbatim from MAPPING §D
    s_rows = [
        ("S-1", "DEL-04-01", "WP-02 App-side probe of the exact App Server supply/protocol/config/role behaviour with adoption evidence (AT-001/002/050 observation)", "Row L312 covers the *first Root-runtime adapter* probe (version, messages, policy inputs, hooks, MCP, session linkage, interruption, packaging, conformance); the App Server is a different adapter and the Gate-5 application did not amend this row. The Electron 43.2.0 drift observation is carried by A11 E2 (PR #680)."),
        ("S-2", "DEL-09-04", "WP-03 App-side two-job installer/migration/rollback through runtime-control IPC (AT-054 App entry; AT-035 installer half)", "Row L367 covers producing the unsigned arm64 DMG and proving instruction-root/SDK packaging posture; it does not cover installer transactions through runtime-control IPC."),
        ("S-3", "DEL-03-03", "WP-08/G0 A4 App-side resume-continuity decision logic (`thread/resume` only on exact root/account/policy match, else fresh thread)", "Row L305 covers keeping `/api/harness/*` shapes and SSE names stable while policy moves behind services; the resume decision is runtime policy. Root DEL-02-11 owns restart/fresh-thread policy and DEL-05-04-V3-01 carries truthful presentation, so the owner may find no amendment necessary."),
        ("S-4", "DEL-05-01", "WP-08 consent/root-home migration and account-change invalidation; backup-before-write and rollback for session migration (Carrier Map \"backup/rollback\", plan WP-08)", "Row L322 covers lazy non-destructive access to and migration of legacy project-local *session records* while preserving list, resume, and delete behavior; consent, root-home, and account-change semantics are Root-owned (DEL-02-09/DEL-02-11), and neither the row nor the DEL-05-01 Scope of Work states backup or rollback obligations. DEL-05-01-V3-01 is limited to lazy non-destructive access with typed failure."),
        ("S-5", "DEL-04-05", "Carrier Map \"extend … to OAuth/device-code/keyring … and root-account transitions\" beyond typed transport conformance", "Row L316 covers credential entry/status participation, safeStorage boundary participation, and verification of ruled provider/network behaviour; OAuth/device-code/keyring semantics stay Root-owned. Only the typed-transport and posture conformance portions are seated (DEL-04-05-V3-02)."),
        ("S-6", "DEL-09-05", "CI wiring of SBOM/notice tooling into repo-root `.github/workflows/**`", "Not a scope gap in the row but a write-scope limit: the loop's write scope is `projects/chirality-app-dev/**` unless the owner grants wider scope; tooling under `frontend/scripts/**` is seated (DEL-09-05-V3-02), workflow wiring is not."),
        ("S-7", "DEL-02-02", "WP-07 / G0 A3 / Carrier Map row: Codex Agent 0/1/2 role-entry UX and the `role not mechanically enforced` and `Opt-in Preview` posture labels on the Work/Agents surfaces", "Row L294 was not amended at Gate 5 and states presentation of recorded agent/session selections with provenance labels only; a role-entry offer is new UX. Gate 5 seated role entry and both labels on DEL-02-05 (L297) and DEL-08-04 (L357) only. DEL-02-02-V3-01 is limited to presenting recorded descendant records with provenance labels and is parked until those records exist (DEL-08-05-V3-01)."),
    ]
    mapping_txt = (REPO_ROOT / SEAT_MAP).read_text(encoding="utf-8")
    rows7 = []
    for sid, carrier, obl, why in s_rows:
        present = f"| {sid} | {carrier} | {obl} | {why} |" in mapping_txt
        rows7.append(row(f"{sid} — {carrier}: {obl}", "SCOPE_AMENDMENT_REQUIRED", f"UNSEATED (returned for a later SCOPE_CHANGE act). Why unseated (applied row text at `d6f6cadb2`): {why} Verbatim row present in `MAPPING.md` §D: {present}.", [SEAT_MAP, SEAT_COV, DECOMP]))
    S.append({"id": "7", "title": "SCOPE_AMENDMENT_REQUIRED list S-1..S-7 from the seating packet (unchanged)", "rows": rows7})

    # 8. not claimed
    rows8 = [row(t, "NOT_CLAIMED", s, c) for t, s, c in [
        ("G0.5", "UNRULED. Root R16 routed the ten bindings and did not declare G0.5 passed; `source_identity` and `implementation_act` remain `HELD_UNAVAILABLE`; R17-B and R18-C preserve that state. This record supplies App evidence only.", [R16, R17, R18, SNAP]),
        ("G1", "UNRULED. G1 is a REVIEW + owner gate. TM-ROOT-106 remains an open, unruled G1 blocker; TM-ROOT-122's closure is not a ruling on the gate (R18-B). This record is an input to the G1 REVIEW, not its verdict.", [R18, ROOT_TM, SEAT_MAP]),
        ("Authority", "Not claimed. The pinned plan, notices, ruling-record transcriptions, and this record are not authority; live sources govern on any disagreement (K-AUTH-1; workplan pin clause).", [WORKPLAN, PLAN]),
        ("Closure", "Not claimed. No Task Management row, held binding, SCOPE_AMENDMENT_REQUIRED obligation, dependency row, or Root item is closed, lifted, satisfied, or dispositioned by this record.", [APP_TM, ROOT_TM, SNAP]),
        ("Lifecycle", "Not claimed. DEL-01-01 `Current State`, `Checking Approval SHA`, `Authorization Basis`, and `Directive` lines are unchanged by this tranche (the live `_STATUS.md` is edited by this tranche for its Remaining/History lines and is therefore not a cited byte; its seating-time identity is in the seating packet `SOW_IDENTITY_LEDGER.md`); no `CHECKING → ISSUED` act (F-APP-4); Root DEL-02-06 remains `INITIALIZED`.", [SOW0101, SEAT_IDL, ROOT0206_STATUS]),
        ("Implementation", "Not claimed. No product, runtime, `frontend/**`, workflow, register, decision, corpus, `docs/**`, or Root byte changed in this tranche; the A1 re-stage rule did not fire.", [WORKPLAN, SOW0101, SEAT_IDL]),
        ("Release", "Not claimed. D-APP-97 and F-APP-2 remain active; no signing, notarization, publication, distribution, release-readiness, professional, or certification claim (F-APP-2); G6a and every later gate are untouched.", [D97, WORKPLAN]),
    ]]
    S.append({"id": "8", "title": "Not claimed", "rows": rows8})
    return S


# ---- render --------------------------------------------------------------------------------
def render_md(S: list[dict], lc: dict, pr: dict, manifest: list[dict]) -> str:
    L: list[str] = []
    L.append("# Evidence — AT-053 App governed-basis record — DEL-01-01-V3-01")
    L.append("")
    L.append("## Header")
    L.append("")
    L.append("| Field | Value |")
    L.append("|---|---|")
    L.append(f"| Record ID | `{RECORD_ID}` |")
    L.append("| Purpose | App evidence for the G0.5/G1 REVIEW (AT-053 'Governed basis and shared-runtime gate'): map every Root/App amendment in the v3 pathway, each held DEL-02-06 binding, each RQG §13 condition, DEL-02-06 REQ-027 and its exclusion, the D-APP-103 interaction, every open App/Root Task Management row relevant to the pathway, and the seating packet's `SCOPE_AMENDMENT_REQUIRED` list to its accepted carrier or explicit unseated state — without inferring authority or closure. |")
    L.append("| Epistemic status | **Evidence, not a verdict and not acceptance.** Every claim below is an agent finding grounded in bytes at the basis; per CONTRACT K-AUTH-1 no approval, gate pass, closure, lifecycle transition, or reliance is rendered. On any disagreement the live tree governs and this dated record is superseded, not edited. |")
    L.append(f"| Basis | `{BASIS}` (PR #681 merge; App v3 pathway seating, A12). All SHA-256 values were recomputed from this tree by `build_at053_evidence.py` in the run record; none is transcribed by hand. |")
    L.append("| Source item | DEL-01-01 `_STATUS.md` `## Remaining` **DEL-01-01-V3-01** (`SELECTABLE`), seated by A12; trace OUT-001, AC-001, VER-001; applied decomposition row L284; plan WP-01, gates G0.5/G1, AT-053. |")
    L.append("| Authority for preparation | A12 (`plans/steers/chirality_app_v3_app_ruling_record_a12_2026-09-03.md`) merged as PR #681; owner dev-slate selection of node E on 2026-09-03 recorded in the run record; workplan `WORKPLAN_2026-09-03_app_dev_loop.md` (calibrated development pressure: evidence-only work counts because this obligation is itself an evidence gate). |")
    L.append(f"| Date of findings | {RECORD_DATE} |")
    L.append("| Author | Claude Fable 5.1 (claude-fable-5-1) as ephemeral Agent 2 implementer under HELP_HUMAN (Claude Fable 5.1); RunID `APPDEV_V3_NODE_E_2026-09-03`, instance `E1_IMPLEMENTER` |")
    L.append("| Companion | `Evidence_AT-053_Governed_Basis_2026-09-03.json` (same mapping, machine-readable, with the sorted manifest); verifier `verify_citations.py` in the run record recomputes every SHA-256. |")
    L.append("| Revision rule | Revised if the G1 REVIEW returns a gap (a new dated record; this one is never edited). |")
    L.append("")
    L.append("Citation convention: each row cites repo-root-relative paths with the first 16 hex characters of the recomputed SHA-256; the full 64-hex digest of every cited path is in the sorted cited-byte inventory at the end and in the JSON companion. State vocabulary follows the seating packet: `ACCEPTED`, `OPEN`, `HELD`, `APP_OWNED`, `ROOT_OWNED`, `SCOPE_AMENDMENT_REQUIRED` / UNSEATED, plus `NOT_SELECTABLE_UNTIL` for parked items and `TBD` where a fact is unavailable in the tree (each `TBD` names what would resolve it).")
    L.append("")
    L.append("## 0. Completion meaning (pinned plan, extracted from the HTML bytes; meaning only)")
    L.append("")
    L.append(f"Extracted with a Python `html.parser` walk over `{PLAN}` (SHA-256 `{sha(PLAN)}`), not from memory. The plan is the pinned completion and acceptance reference (R17-C); it is not authority, status, or a queue.")
    L.append("")
    L.append("| Plan row | Extracted cells |")
    L.append("|---|---|")
    for k in ("AT-053", "G0", "G0.5", "G1", "WP-01", "Contracts and carriers"):
        if k in pr:
            L.append(f"| {esc(k)} | {esc(' · '.join(pr[k][1:]))} |")
    L.append("")
    L.append("Plan §8.3 states the ten held-binding fields 'are copied from the accepted DEL-02-06 compatibility snapshot' and that 'the target gate is routing, not a lift'; §8.3.1 names D-APP-103 as an interacting open item on DEL-08-04; §8.4 names TM-ROOT-106 and TM-ROOT-122 as pre-existing defects to resolve or isolate before G1 / AT-039.")
    L.append("")
    L.append("## Live-tree checks recomputed for this record")
    L.append("")
    L.append("| Check | Result |")
    L.append("|---|---|")
    ac = lc["accepted_candidate"]
    L.append(f"| Accepted DEL-02-06 candidate JSON | byte length `{ac['byte_length']}`, SHA-256 `{ac['sha256']}`, embedded `status` `{ac['embedded_status']}`, identity `{ac['candidate_identity']}` epoch `{ac['compatibility_epoch']}`; objects with `status: HELD_UNAVAILABLE` = **{ac['held_unavailable_count']}**, all `identity: null` = {ac['held_unavailable_all_identity_null']} |")
    L.append(f"| Accepted snapshot | `{SNAP}` SHA-256 `{lc['accepted_snapshot']['sha256']}` |")
    L.append(f"| 2026-08-21 Root notice states those exact identities | candidate SHA {lc['notice_0206_states_candidate_sha']}; snapshot SHA {lc['notice_0206_states_snapshot_sha']}; byte length 14191 {lc['notice_0206_states_byte_length']} |")
    L.append(f"| Root DEL-02-06 `_STATUS.md` accepted-SOW SHA equals live `ScopeOfWork.md` | {lc['root_0206_status_accepted_sow_sha_matches_live']} ({esc(lc['root_0206_current_state_line'])}) |")
    L.append(f"| Pinned plan SHA-256 equals the workplan pin | {lc['plan_pin_sha_matches_workplan']} |")
    L.append(f"| Live Root `AGENTS.md` SHA-256 equals the D-GOV-35 notice post-image | {lc['root_agents_sha_matches_dgov35_notice_post_image']} |")
    L.append(f"| App Task Management register | `{lc['app_tm']['rows']}` rows; OPEN {len(lc['app_tm']['OPEN'])} ({', '.join(lc['app_tm']['OPEN'])}); DEFERRED {len(lc['app_tm']['DEFERRED'])} ({', '.join(lc['app_tm']['DEFERRED'])}); other {lc['app_tm']['other']}; SHA-256 `{lc['app_tm']['sha256']}` |")
    L.append(f"| Root Task Management register | `{lc['root_tm']['rows']}` rows by status {esc(json.dumps({k: len(v) for k, v in lc['root_tm']['by_status'].items()}))}; TM-ROOT-122 present in live register {lc['root_tm']['TM-ROOT-122_in_live_register']}; closed row {esc(json.dumps(lc['TM-ROOT-122_closed_row']))} |")
    L.append(f"| Authority corpus | `{lc['authority_corpus']['current_version']}`; `AUTHORITY_CORPUS.json` SHA-256 `{lc['authority_corpus']['sha256']}`; `docs/CONTRACT.md` SHA-256 `{lc['app_contract_sha256']}` |")
    L.append(f"| App `docs/CONTRACT.md` clause lines | {esc(json.dumps(lc['app_contract_clause_lines']))} |")
    L.append(f"| RQG §13 line span | `## 13` at line {lc['rqg_section13_lines'][0]}; next section at {lc['rqg_section13_lines'][1] if len(lc['rqg_section13_lines']) > 1 else 'EOF'} |")
    L.append(f"| `K-SDK-5` presence | {esc(json.dumps(lc['k_sdk_5_present_in']))} |")
    L.append(f"| D-APP-103 packet artifacts under DEL-08-04 `_run_records/` | {lc['dapp103_packet_artifacts_under_del0804_run_records'] or 'none'} |")
    L.append(f"| Root DEL-02-06 `_run_records/` directories | {', '.join(lc['root_0206_run_record_dirs'])} |")
    L.append("")
    for sec in S:
        L.append(f"## {sec['id']}. {sec['title']}")
        L.append("")
        L.append("| # | Subject | Class | Carrier / state | Citations (path @ sha256[:16]) |")
        L.append("|---|---|---|---|---|")
        for i, r in enumerate(sec["rows"], 1):
            L.append(f"| {sec['id']}.{i} | {esc(r['subject'])} | `{r['class']}` | {esc(r['carrier_or_state'])} | {cite_md(r['citations'])} |")
        L.append("")
    L.append("## Summary of TBDs (facts unavailable in the tree at the basis)")
    L.append("")
    import re as _re
    tbd_re = _re.compile(r"(?<![\w-])TBD(?![\w-])")
    tbds = [(f"{sec['id']}.{i}", r["subject"]) for sec in S for i, r in enumerate(sec["rows"], 1) if tbd_re.search(r["carrier_or_state"])]
    for ref, subj in tbds:
        L.append(f"- {ref} — {esc(subj[:140]).rstrip()}")
    L.append("")
    L.append("## Cited-byte inventory (sorted manifest; full SHA-256)")
    L.append("")
    L.append("| Path | Bytes | SHA-256 |")
    L.append("|---|---:|---|")
    for m in manifest:
        L.append(f"| `{m['path']}` | {m['bytes']} | `{m['sha256']}` |")
    L.append("")
    L.append("## Rerun method")
    L.append("")
    L.append("From any checkout at the basis (or a descendant, to detect drift):")
    L.append("")
    L.append("```")
    L.append("cd \"$(git rev-parse --show-toplevel)\"")
    L.append("python3 projects/chirality-app-dev/execution/_Coordination/AgentRuns/APPDEV_V3_NODE_E_2026-09-03/build_at053_evidence.py --check")
    L.append("python3 projects/chirality-app-dev/execution/_Coordination/AgentRuns/APPDEV_V3_NODE_E_2026-09-03/verify_citations.py")
    L.append("```")
    L.append("")
    L.append("`--check` regenerates both files in memory and exits non-zero if they differ from the committed bytes; `verify_citations.py` recomputes every SHA-256 in the JSON companion and writes `VERIFY_CITATIONS_RESULT.json` beside itself. Environment and exit statuses for the recorded run are in the run record's `CHECKS.json`. No disposable or quarantine state is created by either script.")
    L.append("")
    return "\n".join(L)


def main() -> int:
    check = "--check" in sys.argv
    lc = live_checks()
    pr = plan_rows()
    S = sections(lc)
    paths = sorted({p for sec in S for r in sec["rows"] for p in r["citations"]} | {PLAN, CAND, SNAP, APP_TM, ROOT_TM, CORPUS, APP_CONTRACT})
    manifest = [{"path": p, "bytes": size(p), "sha256": sha(p)} for p in paths]
    doc = {
        "schema": "chirality-app-at053-governed-basis-evidence/v1",
        "record_id": RECORD_ID,
        "date": RECORD_DATE,
        "basis_commit": BASIS,
        "epistemic_status": "EVIDENCE_NOT_VERDICT_NOT_ACCEPTANCE",
        "plan_pin": {"path": PLAN, "sha256": sha(PLAN)},
        "plan_rows_extracted": pr,
        "live_checks": lc,
        "sections": [{"id": s["id"], "title": s["title"], "rows": [{"subject": r["subject"], "class": r["class"], "carrier_or_state": r["carrier_or_state"], "note": r["note"], "citations": [{"path": p, "sha256": sha(p)} for p in r["citations"]]} for r in s["rows"]]} for s in S],
        "manifest": manifest,
        "not_claimed": ["G0.5 unruled", "G1 unruled", "no authority", "no closure", "no lifecycle transition", "no implementation", "no release"],
    }
    js = json.dumps(doc, indent=2, ensure_ascii=False, sort_keys=False) + "\n"
    md = render_md(S, lc, pr, manifest)
    if check:
        ok = (REPO_ROOT / OUT_MD).read_text(encoding="utf-8") == md and (REPO_ROOT / OUT_JSON).read_text(encoding="utf-8") == js
        print("CHECK", "PASS" if ok else "FAIL")
        return 0 if ok else 1
    (REPO_ROOT / OUT_MD).write_text(md, encoding="utf-8")
    (REPO_ROOT / OUT_JSON).write_text(js, encoding="utf-8")
    print("wrote", OUT_MD, len(md.encode()), "bytes;", OUT_JSON, len(js.encode()), "bytes;", len(manifest), "cited paths")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
