#!/usr/bin/env python3
"""D-PEC-96 bound act: PEC loop-registry schema v2 with closed feed profiles.

Writes exactly the pinned postimages of the ruled option into
projects/pec/ of the repository given by --repo, after checking every pinned
preimage and every must-remain file. Writes nothing and exits 1 on any
failure, including a second run. Stdlib only.

  python3 apply_d96.py --repo <REPO_ROOT> [--check-only]

--check-only runs every check and reports without writing.
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import sys
from pathlib import Path

PEC = Path("projects/pec")

PREIMAGES = {
    'v2/config/loops.json': '4ce07ad061abd222acabb2afe0f619fdc840b4cc11d31e49f1dff8fcc299d32e',
    'v2/config/loops.schema.json': '1f4d1f0cf9abe5754ebb4260f588dea0d71e7f3cc37af2487b30b9c4aa39ba9b',
    'v2/src/pec_v2/core/ports/loop_registry.py': '3d5862bef122af27d61883fe5542b80daefb3418bccfba31486e4d60289b3662',
    'v2/src/pec_v2/core/ports/__init__.py': '669e1569216722509dcea0ae5ed42dc4a0ca856a196676568ee78d7a38a1edeb',
    'v2/src/pec_v2/core/__init__.py': '33c54e244e8e19b66cb2c53c81fa747979f6d512f227f7a56e3f8d57cfb9ff4a',
    'v2/src/pec_v2/adapters/config/loop_registry.py': '7101740dea837e6077e048ec2a8ef8600c7d1014bd339915aaea285b8236eb2f',
    'v2/tests/config/test_json_loop_registry.py': 'd7efb486287d3703aa9ea007eb5376eba95689286bb322c887eeca8b193ac956',
    'v2/tests/config/test_loop_registry_contract.py': '49b2f6a3b5088bceb82dc393cce050b8800af3a5ac5d34b3b6a3d7b71c01111b',
    'v2/tests/config/fixtures/duplicate_loop_id.json': '2e65c719af6c9eb7e170fb25d437b928847dc8d617c056093de213673b3e3396',
    'v2/tests/config/fixtures/missing_loop_id.json': '2155849d9419f0239dca7a69d919ca9ee46a6434106d5326d85bc8c70afc5257',
    'v2/tests/config/fixtures/schema_version_1.json': None,
}
UNCHANGED = {
    'v2/tests/config/fixtures/malformed.json': 'f37303491c50fa74756f547929f09c99900abfad5a9310cc2b46beb5027425b0',
    'v2/src/pec_v2/adapters/config/__init__.py': '7a9bdbc59b96d3c9f306af483d18d6c0b23b7071481fd6ab79204ba398513cba',
    'v2/src/pec_v2/adapters/__init__.py': '8c80e607671eef1a35dca0334503deb151418c03b618af0c4577514d0184ef22',
    'v2/src/pec_v2/__init__.py': 'ae46d431c13413d5bcbb6ab60a97f6db09510dd97903c1f2a8586a3567b17c1e',
    'software-workflow.json': '8ec9ba6dcba7ea6b935923f5b4d846b2a9ac3f3d5cc43f5e160abe0971058a8b',
    'v2/config/service_core_posture.json': '20d64ff38122fa2f7b4bbe6478e42450ce6f9c8b03dc91c90b5095393ef309ed',
}
POSTIMAGES_A = {
    'v2/config/loops.json': 'fd342b4f29edf3bece24a8d785b4a03d1a60158e62227753e4e1fa03529f53d7',
    'v2/config/loops.schema.json': '104ed64820b7a1fa6f24249cb6817653b8a624f43c52ea181ae4fd5d510cb143',
    'v2/src/pec_v2/core/ports/loop_registry.py': 'a509bfb74920172a86ac21aff6a67245cd3248c5d73ef4e7427966069099c8a9',
    'v2/src/pec_v2/core/ports/__init__.py': 'e44bf7f00c8ef2cfa5f8006ef2834feb020063df63a3b4b8d8cbd8f359174ff7',
    'v2/src/pec_v2/core/__init__.py': '0e699a54d6bc202ff7a90c25fdb355da5ed2db185709c3a399870c1b0309c42d',
    'v2/src/pec_v2/adapters/config/loop_registry.py': '620a173d19d881ef396ebb339e4097f5ee4e3a0b6ada231718ca700926832f07',
    'v2/tests/config/test_json_loop_registry.py': '8b45495fdc78eb77c12a4ebefdb064d34d40d5602fde573be4b4e817ddbe0c9b',
    'v2/tests/config/test_loop_registry_contract.py': 'b05ed8719c59258998b1c483456b66bd8d4a4d3bc4f68cdd6fb5c02541db7106',
    'v2/tests/config/fixtures/duplicate_loop_id.json': '6875f50023f1ad34a45c1af4b0a65316260c45aa05562ce45bb2d9bd8fd13c7e',
    'v2/tests/config/fixtures/missing_loop_id.json': 'f4255b2483a014b542fb7f25c4314ff75dabb5cebbcfe751a2ad3df425f29598',
    'v2/tests/config/fixtures/schema_version_1.json': '4ce07ad061abd222acabb2afe0f619fdc840b4cc11d31e49f1dff8fcc299d32e',
}
BLOBS = {
    '0e699a54d6bc202ff7a90c25fdb355da5ed2db185709c3a399870c1b0309c42d': (
        'IiIiUEVDLW93bmVkIGRvbWFpbiBhbmQgYXBwbGljYXRpb24gY29udHJhY3RzLiIiIgoKZnJvbSAu'
        'cG9ydHMubG9vcF9yZWdpc3RyeSBpbXBvcnQgRmVlZFByb2ZpbGUsIEZlZWRQcm9maWxlU3RhdGUs'
        'IExvb3BSZWdpc3RyeSwgUmVnaXN0ZXJlZExvb3AKCl9fYWxsX18gPSBbIkZlZWRQcm9maWxlIiwg'
        'IkZlZWRQcm9maWxlU3RhdGUiLCAiTG9vcFJlZ2lzdHJ5IiwgIlJlZ2lzdGVyZWRMb29wIl0K'
    ),
    '104ed64820b7a1fa6f24249cb6817653b8a624f43c52ea181ae4fd5d510cb143': (
        'ewogICIkaWQiOiAiaHR0cHM6Ly9jaGlyYWxpdHkubG9jYWwvcGVjL3YyL2NvbmZpZy9sb29wcy5z'
        'Y2hlbWEudjIuanNvbiIsCiAgIiRzY2hlbWEiOiAiaHR0cHM6Ly9qc29uLXNjaGVtYS5vcmcvZHJh'
        'ZnQvMjAyMC0xMi9zY2hlbWEiLAogICJhZGRpdGlvbmFsUHJvcGVydGllcyI6IGZhbHNlLAogICJk'
        'ZXNjcmlwdGlvbiI6ICJMb2NhbCBjb25maWd1cmF0aW9uIGZvcm1hdCBuYW1pbmcgdGhlIGxvb3Bz'
        'IFBFQyBzZXJ2ZXMgYW5kIHRoZSBjbG9zZWQsIFBFQy12ZXJzaW9uZWQgZmVlZCBwcm9maWxlcyBQ'
        'RUMgcmVhZHMgZWFjaCBsb29wIHdpdGguIFNjaGVtYSB2ZXJzaW9uIDEgaXMgbm90IGFjY2VwdGVk'
        'IGJ5IHRoZSB2ZXJzaW9uLTIgbG9hZGVyLiIsCiAgInByb3BlcnRpZXMiOiB7CiAgICAibG9vcHMi'
        'OiB7CiAgICAgICJkZXNjcmlwdGlvbiI6ICJUaGUgY29uZmlndXJlZCBsb29wcyBQRUMgbWF5IHJl'
        'YWQgYXMgbm9uLWF1dGhvcml0YXRpdmUgZmlsZS10cnV0aCBsb2NhdGlvbnMuIiwKICAgICAgIml0'
        'ZW1zIjogewogICAgICAgICJhZGRpdGlvbmFsUHJvcGVydGllcyI6IGZhbHNlLAogICAgICAgICJw'
        'cm9wZXJ0aWVzIjogewogICAgICAgICAgImZlZWRfcHJvZmlsZXMiOiB7CiAgICAgICAgICAgICJk'
        'ZXNjcmlwdGlvbiI6ICJUaGUgZmVlZCBwcm9maWxlcyBQRUMgYXBwbGllcyB0byB0aGlzIGxvb3A6'
        'IFBFQydzIHJlYWRpbmcgaHlwb3RoZXNpcywgbmV2ZXIgdGhlIGxvb3AncyB0cnV0aC4gQXQgbGVh'
        'c3Qgb25lIGVudHJ5IGFuZCBhdCBsZWFzdCBvbmUgbGl2ZSBlbnRyeTsgYSBwcm9maWxlIGlkZW50'
        'aWZpZXIgYXBwZWFycyBhdCBtb3N0IG9uY2UgcGVyIGxvb3AsIGFuZCB0aGUgcHJvZmlsZXMgb24g'
        'b25lIGxvb3AgY292ZXIgcGFpcndpc2UtZGlzam9pbnQgc3VyZmFjZXMsIHNvIG5vIHN1cmZhY2Ug'
        'aXMgcmVhZCB1bmRlciB0d28gZ3JhbW1hcnMgb3IgZGVjbGFyZWQgYm90aCBsaXZlIGFuZCBoaXN0'
        'b3JpY2FsLiIsCiAgICAgICAgICAgICJpdGVtcyI6IHsKICAgICAgICAgICAgICAiYWRkaXRpb25h'
        'bFByb3BlcnRpZXMiOiBmYWxzZSwKICAgICAgICAgICAgICAicHJvcGVydGllcyI6IHsKICAgICAg'
        'ICAgICAgICAgICJiYXNpcyI6IHsKICAgICAgICAgICAgICAgICAgImRlc2NyaXB0aW9uIjogIkNp'
        'dGF0aW9uIHRvIHRoZSBsb29wJ3Mgb3duIHJlY29yZCB0aGF0IHN1cHBvcnRzIHRoaXMgZGVjbGFy'
        'YXRpb24uIE5vcm1hbGl6ZWQgcmVwb3NpdG9yeS1yZWxhdGl2ZSBwYXRoIChubyBsZWFkaW5nICcv'
        'Jywgbm8gJy4uJyBzZWdtZW50LCBubyBiYWNrc2xhc2gpLiIsCiAgICAgICAgICAgICAgICAgICJt'
        'aW5MZW5ndGgiOiAxLAogICAgICAgICAgICAgICAgICAidHlwZSI6ICJzdHJpbmciCiAgICAgICAg'
        'ICAgICAgICB9LAogICAgICAgICAgICAgICAgInByb2ZpbGUiOiB7CiAgICAgICAgICAgICAgICAg'
        'ICJkZXNjcmlwdGlvbiI6ICJJZGVudGlmaWVyIGZyb20gUEVDJ3MgY2xvc2VkIGZlZWQtcHJvZmls'
        'ZSB2b2NhYnVsYXJ5LiBFYWNoIG9wdGlvbiBlbmRzIHdpdGggdGhlIHN1cmZhY2VzIGl0IGNvdmVy'
        'cy4gUGF0aCBjb252ZW50aW9ucyBhbmQgZ3JhbW1hcnMgZm9yIGVhY2ggcHJvZmlsZSBsaXZlIGlu'
        'IFBFQydzIGFkYXB0ZXJzLiIsCiAgICAgICAgICAgICAgICAgICJvbmVPZiI6IFsKICAgICAgICAg'
        'ICAgICAgICAgICB7CiAgICAgICAgICAgICAgICAgICAgICAiY29uc3QiOiAiYWdlbnRydW5zLWpz'
        'b24iLAogICAgICAgICAgICAgICAgICAgICAgImRlc2NyaXB0aW9uIjogIkpTT04gcnVuIGV2aWRl'
        'bmNlIGFueXdoZXJlIHVuZGVyIHRoZSBsb29wJ3MgZXhlY3V0aW9uLyB0cmVlIChXT1JLX0dSQVBI'
        'Lmpzb24sIFNUQVRVUy5qc29uLCBSVU5USU1FX1NVTU1BUlkuanNvbiksIGluY2x1ZGluZyBBZ2Vu'
        'dFJ1bnMvIGFuZCBkZWxpdmVyYWJsZSBfcnVuX3JlY29yZHMvOyB0aGUgaWRlbnRpZmllciBrZWVw'
        'cyBpdHMgU0NBLTAwNSBuYW1lLiBTdXJmYWNlczoganNvbi1ydW4tZXZpZGVuY2UuIgogICAgICAg'
        'ICAgICAgICAgICAgIH0sCiAgICAgICAgICAgICAgICAgICAgewogICAgICAgICAgICAgICAgICAg'
        'ICAgImNvbnN0IjogImxvb3AtcmVjZWlwdHMtbGVkZ2VyIiwKICAgICAgICAgICAgICAgICAgICAg'
        'ICJkZXNjcmlwdGlvbiI6ICJUaGUgbG9vcCdzIGxvb3AvTE9PUF9SRUNFSVBUUy5tZCByZWNlaXB0'
        'IGxlZGdlciwgdW5kZXIgdGhhdCBsb29wJ3MgZ3JhbW1hci4gU3VyZmFjZXM6IHJlY2VpcHQtbGVk'
        'Z2VyLiIKICAgICAgICAgICAgICAgICAgICB9LAogICAgICAgICAgICAgICAgICAgIHsKICAgICAg'
        'ICAgICAgICAgICAgICAgICJjb25zdCI6ICJzaGFyZWQtZGV2LWxvb3AiLAogICAgICAgICAgICAg'
        'ICAgICAgICAgImRlc2NyaXB0aW9uIjogIlRoZSBzaGFyZWQgZGV2ZWxvcG1lbnQtbG9vcCBtZXRo'
        'b2Q6IHVuZGVydGFraW5nIHdvcmsgZ3JhcGhzIChleGVjdXRpb24vX0Nvb3JkaW5hdGlvbi9Xb3Jr'
        'R3JhcGhzLzx1bmRlcnRha2luZz4vV09SS19HUkFQSC5tZCksIGNlbnRyYWwgcmVjZWlwdHMgKGV4'
        'ZWN1dGlvbi9fQ29vcmRpbmF0aW9uL0FnZW50UnVucy88UnVuSUQ+L1JFQ0VJUFQubWQpLCB0aGUg'
        'ZGVsaXZlcmFibGUgTUVNT1JZLm1kIHJ1biBpbmRleCwgX1NUQVRVUy5tZCBsaWZlY3ljbGUsIGRl'
        'cGVuZGVuY3kgcmVnaXN0ZXJzIGFuZCBkZWNpc2lvbiByZWdpc3RlcnMuIFN1cmZhY2VzOiBjZW50'
        'cmFsLXJlY2VpcHRzLCBkZWNpc2lvbi1yZWdpc3RlcnMsIGRlcGVuZGVuY3ktcmVnaXN0ZXJzLCBt'
        'ZW1vcnktcnVuLWluZGV4LCBzdGF0dXMtbGlmZWN5Y2xlLCB3b3JrLWdyYXBocy4iCiAgICAgICAg'
        'ICAgICAgICAgICAgfQogICAgICAgICAgICAgICAgICBdLAogICAgICAgICAgICAgICAgICAidHlw'
        'ZSI6ICJzdHJpbmciCiAgICAgICAgICAgICAgICB9LAogICAgICAgICAgICAgICAgInN0YXRlIjog'
        'ewogICAgICAgICAgICAgICAgICAiZGVzY3JpcHRpb24iOiAibGl2ZTogdGhlIGxvb3AgY3VycmVu'
        'dGx5IHdyaXRlcyB0aGlzIGdlbmVyYXRpb24uIGhpc3RvcmljYWw6IHRoZSBnZW5lcmF0aW9uIGlz'
        'IGZyb3plbiwgYW5kIGl0cyBzaWxlbmNlIGlzIG5ldmVyIHJlcG9ydGVkIGFzIHN0YWxlbmVzcy4i'
        'LAogICAgICAgICAgICAgICAgICAiZW51bSI6IFsKICAgICAgICAgICAgICAgICAgICAiaGlzdG9y'
        'aWNhbCIsCiAgICAgICAgICAgICAgICAgICAgImxpdmUiCiAgICAgICAgICAgICAgICAgIF0sCiAg'
        'ICAgICAgICAgICAgICAgICJ0eXBlIjogInN0cmluZyIKICAgICAgICAgICAgICAgIH0sCiAgICAg'
        'ICAgICAgICAgICAidmVyc2lvbiI6IHsKICAgICAgICAgICAgICAgICAgImNvbnN0IjogMSwKICAg'
        'ICAgICAgICAgICAgICAgImRlc2NyaXB0aW9uIjogIlZlcnNpb24gb2YgdGhlIHNlbGVjdGVkIHBy'
        'b2ZpbGU7IGV2ZXJ5IHByb2ZpbGUgaW4gdGhpcyB2b2NhYnVsYXJ5IGlzIGF0IHZlcnNpb24gMS4i'
        'LAogICAgICAgICAgICAgICAgICAidHlwZSI6ICJpbnRlZ2VyIgogICAgICAgICAgICAgICAgfQog'
        'ICAgICAgICAgICAgIH0sCiAgICAgICAgICAgICAgInJlcXVpcmVkIjogWwogICAgICAgICAgICAg'
        'ICAgImJhc2lzIiwKICAgICAgICAgICAgICAgICJwcm9maWxlIiwKICAgICAgICAgICAgICAgICJz'
        'dGF0ZSIsCiAgICAgICAgICAgICAgICAidmVyc2lvbiIKICAgICAgICAgICAgICBdLAogICAgICAg'
        'ICAgICAgICJ0eXBlIjogIm9iamVjdCIKICAgICAgICAgICAgfSwKICAgICAgICAgICAgIm1pbkl0'
        'ZW1zIjogMSwKICAgICAgICAgICAgInR5cGUiOiAiYXJyYXkiCiAgICAgICAgICB9LAogICAgICAg'
        'ICAgImxvb3BfaWQiOiB7CiAgICAgICAgICAgICJkZXNjcmlwdGlvbiI6ICJTdGFibGUgbG93ZXIt'
        'Y2FzZSBpZGVudGlmaWVyIGZvciBvbmUgY29uZmlndXJlZCBsb29wLiIsCiAgICAgICAgICAgICJt'
        'aW5MZW5ndGgiOiAxLAogICAgICAgICAgICAicGF0dGVybiI6ICJeW2Etel1bYS16MC05LV0qJCIs'
        'CiAgICAgICAgICAgICJ0eXBlIjogInN0cmluZyIKICAgICAgICAgIH0sCiAgICAgICAgICAibG9v'
        'cF9pbml0X3BhdGgiOiB7CiAgICAgICAgICAgICJkZXNjcmlwdGlvbiI6ICJSZXBvc2l0b3J5LXJl'
        'bGF0aXZlIHBhdGggdG8gdGhlIGxvb3AncyBnb3Zlcm5lZCBMT09QX0lOSVQubWQgc3VyZmFjZS4i'
        'LAogICAgICAgICAgICAibWluTGVuZ3RoIjogMSwKICAgICAgICAgICAgInR5cGUiOiAic3RyaW5n'
        'IgogICAgICAgICAgfQogICAgICAgIH0sCiAgICAgICAgInJlcXVpcmVkIjogWwogICAgICAgICAg'
        'ImZlZWRfcHJvZmlsZXMiLAogICAgICAgICAgImxvb3BfaWQiLAogICAgICAgICAgImxvb3BfaW5p'
        'dF9wYXRoIgogICAgICAgIF0sCiAgICAgICAgInR5cGUiOiAib2JqZWN0IgogICAgICB9LAogICAg'
        'ICAibWluSXRlbXMiOiAxLAogICAgICAidHlwZSI6ICJhcnJheSIKICAgIH0sCiAgICAic2NoZW1h'
        'X3ZlcnNpb24iOiB7CiAgICAgICJjb25zdCI6IDIsCiAgICAgICJkZXNjcmlwdGlvbiI6ICJWZXJz'
        'aW9uIG9mIHRoaXMgbG9jYWwgbG9vcC1yZWdpc3RyeSBjb25maWd1cmF0aW9uIGZvcm1hdC4iLAog'
        'ICAgICAidHlwZSI6ICJpbnRlZ2VyIgogICAgfQogIH0sCiAgInJlcXVpcmVkIjogWwogICAgInNj'
        'aGVtYV92ZXJzaW9uIiwKICAgICJsb29wcyIKICBdLAogICJ0aXRsZSI6ICJQRUMgbG9jYWwgbG9v'
        'cCByZWdpc3RyeSBjb25maWd1cmF0aW9uIHYyIiwKICAidHlwZSI6ICJvYmplY3QiCn0K'
    ),
    '4ce07ad061abd222acabb2afe0f619fdc840b4cc11d31e49f1dff8fcc299d32e': (
        'ewogICJsb29wcyI6IFsKICAgIHsKICAgICAgImxvb3BfaWQiOiAicGVjIiwKICAgICAgImxvb3Bf'
        'aW5pdF9wYXRoIjogInByb2plY3RzL3BlYy9sb29wL0xPT1BfSU5JVC5tZCIKICAgIH0KICBdLAog'
        'ICJzY2hlbWFfdmVyc2lvbiI6IDEKfQo='
    ),
    '620a173d19d881ef396ebb339e4097f5ee4e3a0b6ada231718ca700926832f07': (
        'IiIiSlNPTi1iYWNrZWQgYWRhcHRlciBmb3IgdGhlIGNvcmUtb3duZWQgbG9vcC1yZWdpc3RyeSBw'
        'b3J0LiIiIgoKZnJvbSBfX2Z1dHVyZV9fIGltcG9ydCBhbm5vdGF0aW9ucwoKaW1wb3J0IGpzb24K'
        'aW1wb3J0IHJlCmZyb20gcGF0aGxpYiBpbXBvcnQgUGF0aCwgUHVyZVBvc2l4UGF0aApmcm9tIHR5'
        'cGluZyBpbXBvcnQgQW55Cgpmcm9tIC4uLmNvcmUucG9ydHMubG9vcF9yZWdpc3RyeSBpbXBvcnQg'
        'RmVlZFByb2ZpbGUsIEZlZWRQcm9maWxlU3RhdGUsIFJlZ2lzdGVyZWRMb29wCgoKX0xPT1BfSUQg'
        'PSByZS5jb21waWxlKHIiXlthLXpdW2EtejAtOS1dKiQiKQpfU0NIRU1BX1ZFUlNJT04gPSAyCgoj'
        'IFBFQydzIGNsb3NlZCBmZWVkLXByb2ZpbGUgdm9jYWJ1bGFyeTogZWFjaCBwcm9maWxlIGlkZW50'
        'aWZpZXIgYW5kIHRoZQojIHZlcnNpb25zIHRoaXMgYWRhcHRlciBhY2NlcHRzLiBFeHRlbmRpbmcg'
        'aXQgaXMgYSBQRUMgY29kZSBjaGFuZ2UgdW5kZXIgYW4KIyBvd25lci1ydWxlZCBELVBFQyBwYWNr'
        'ZXQ7IGxvb3BzIG5ldmVyIGRlY2xhcmUgaXQuCkZFRURfUFJPRklMRV9WRVJTSU9OUzogZGljdFtz'
        'dHIsIGZyb3plbnNldFtpbnRdXSA9IHsKICAgICJhZ2VudHJ1bnMtanNvbiI6IGZyb3plbnNldCh7'
        'MX0pLAogICAgImxvb3AtcmVjZWlwdHMtbGVkZ2VyIjogZnJvemVuc2V0KHsxfSksCiAgICAic2hh'
        'cmVkLWRldi1sb29wIjogZnJvemVuc2V0KHsxfSksCn0KCiMgVGhlIGZpbGUtdHJ1dGggc3VyZmFj'
        'ZXMgZWFjaCBwcm9maWxlIHJlYWRzLiBUaGUgcHJvZmlsZXMgZGVjbGFyZWQgb24gb25lCiMgbG9v'
        'cCBtdXN0IGNvdmVyIHBhaXJ3aXNlLWRpc2pvaW50IHN1cmZhY2VzLCBzbyBubyBzdXJmYWNlIGlz'
        'IHJlYWQgdW5kZXIgdHdvCiMgZ3JhbW1hcnMgb3IgZGVjbGFyZWQgYm90aCBsaXZlIGFuZCBoaXN0'
        'b3JpY2FsLiBUaGUgdGhyZWUgcHJvZmlsZXMgaGVyZSBhcmUKIyBkaXNqb2ludCBmcm9tIG9uZSBh'
        'bm90aGVyOyB0aGUgcnVsZSBndWFyZHMgYW55IGxhdGVyIHZvY2FidWxhcnkgY2hhbmdlLgpGRUVE'
        'X1BST0ZJTEVfU1VSRkFDRVM6IGRpY3Rbc3RyLCBmcm96ZW5zZXRbc3RyXV0gPSB7CiAgICAiYWdl'
        'bnRydW5zLWpzb24iOiBmcm96ZW5zZXQoeyJqc29uLXJ1bi1ldmlkZW5jZSJ9KSwKICAgICJsb29w'
        'LXJlY2VpcHRzLWxlZGdlciI6IGZyb3plbnNldCh7InJlY2VpcHQtbGVkZ2VyIn0pLAogICAgInNo'
        'YXJlZC1kZXYtbG9vcCI6IGZyb3plbnNldCgKICAgICAgICB7CiAgICAgICAgICAgICJjZW50cmFs'
        'LXJlY2VpcHRzIiwKICAgICAgICAgICAgImRlY2lzaW9uLXJlZ2lzdGVycyIsCiAgICAgICAgICAg'
        'ICJkZXBlbmRlbmN5LXJlZ2lzdGVycyIsCiAgICAgICAgICAgICJtZW1vcnktcnVuLWluZGV4IiwK'
        'ICAgICAgICAgICAgInN0YXR1cy1saWZlY3ljbGUiLAogICAgICAgICAgICAid29yay1ncmFwaHMi'
        'LAogICAgICAgIH0KICAgICksCn0KCgpjbGFzcyBMb29wUmVnaXN0cnlDb25maWdFcnJvcihWYWx1'
        'ZUVycm9yKToKICAgICIiIkEgbG9jYXRlZCwgZXhwbGljaXQgZmFpbHVyZSBpbiB0aGUgcmVwbGFj'
        'ZWFibGUgSlNPTiBhZGFwdGVyLiIiIgoKCmNsYXNzIEpzb25Mb29wUmVnaXN0cnk6CiAgICAiIiJS'
        'ZWFkIGFuZCB2YWxpZGF0ZSBvbmUgbG9jYWwgSlNPTiBsb29wLXJlZ2lzdHJ5IGNvbmZpZ3VyYXRp'
        'b24uIiIiCgogICAgZGVmIF9faW5pdF9fKHNlbGYsIGNvbmZpZ19wYXRoOiBzdHIgfCBQYXRoKSAt'
        'PiBOb25lOgogICAgICAgIHNlbGYuX2NvbmZpZ19wYXRoID0gUGF0aChjb25maWdfcGF0aCkKCiAg'
        'ICBkZWYgcmVnaXN0ZXJlZF9sb29wcyhzZWxmKSAtPiB0dXBsZVtSZWdpc3RlcmVkTG9vcCwgLi4u'
        'XToKICAgICAgICBkb2N1bWVudCA9IHNlbGYuX3JlYWRfZG9jdW1lbnQoKQogICAgICAgIHJldHVy'
        'biBzZWxmLl92YWxpZGF0ZV9kb2N1bWVudChkb2N1bWVudCkKCiAgICBkZWYgX3JlYWRfZG9jdW1l'
        'bnQoc2VsZikgLT4gQW55OgogICAgICAgIHRyeToKICAgICAgICAgICAgd2l0aCBzZWxmLl9jb25m'
        'aWdfcGF0aC5vcGVuKGVuY29kaW5nPSJ1dGYtOCIpIGFzIGhhbmRsZToKICAgICAgICAgICAgICAg'
        'IHJldHVybiBqc29uLmxvYWQoaGFuZGxlKQogICAgICAgIGV4Y2VwdCBGaWxlTm90Rm91bmRFcnJv'
        'ciBhcyBlcnJvcjoKICAgICAgICAgICAgcmFpc2UgTG9vcFJlZ2lzdHJ5Q29uZmlnRXJyb3IoCiAg'
        'ICAgICAgICAgICAgICBmIntzZWxmLl9jb25maWdfcGF0aH06IGNvbmZpZ3VyYXRpb24gZmlsZSBk'
        'b2VzIG5vdCBleGlzdCIKICAgICAgICAgICAgKSBmcm9tIGVycm9yCiAgICAgICAgZXhjZXB0IGpz'
        'b24uSlNPTkRlY29kZUVycm9yIGFzIGVycm9yOgogICAgICAgICAgICByYWlzZSBMb29wUmVnaXN0'
        'cnlDb25maWdFcnJvcigKICAgICAgICAgICAgICAgIGYie3NlbGYuX2NvbmZpZ19wYXRofTogbWFs'
        'Zm9ybWVkIEpTT04gYXQgbGluZSB7ZXJyb3IubGluZW5vfSwgIgogICAgICAgICAgICAgICAgZiJj'
        'b2x1bW4ge2Vycm9yLmNvbG5vfSIKICAgICAgICAgICAgKSBmcm9tIGVycm9yCiAgICAgICAgZXhj'
        'ZXB0IE9TRXJyb3IgYXMgZXJyb3I6CiAgICAgICAgICAgIGRldGFpbCA9IGVycm9yLnN0cmVycm9y'
        'IG9yIGVycm9yLl9fY2xhc3NfXy5fX25hbWVfXwogICAgICAgICAgICByYWlzZSBMb29wUmVnaXN0'
        'cnlDb25maWdFcnJvcigKICAgICAgICAgICAgICAgIGYie3NlbGYuX2NvbmZpZ19wYXRofTogY29u'
        'ZmlndXJhdGlvbiBmaWxlIGlzIHVucmVhZGFibGU6IHtkZXRhaWx9IgogICAgICAgICAgICApIGZy'
        'b20gZXJyb3IKCiAgICBkZWYgX3ZhbGlkYXRlX2RvY3VtZW50KHNlbGYsIGRvY3VtZW50OiBBbnkp'
        'IC0+IHR1cGxlW1JlZ2lzdGVyZWRMb29wLCAuLi5dOgogICAgICAgIGlmIG5vdCBpc2luc3RhbmNl'
        'KGRvY3VtZW50LCBkaWN0KToKICAgICAgICAgICAgc2VsZi5fZmFpbCgiJCIsICJleHBlY3RlZCBh'
        'biBvYmplY3QiKQogICAgICAgIHNlbGYuX3JlcXVpcmVfZXhhY3RfZmllbGRzKGRvY3VtZW50LCB7'
        'InNjaGVtYV92ZXJzaW9uIiwgImxvb3BzIn0sICIkIikKCiAgICAgICAgdmVyc2lvbiA9IGRvY3Vt'
        'ZW50WyJzY2hlbWFfdmVyc2lvbiJdCiAgICAgICAgaWYgdHlwZSh2ZXJzaW9uKSBpcyBub3QgaW50'
        'IG9yIHZlcnNpb24gIT0gX1NDSEVNQV9WRVJTSU9OOgogICAgICAgICAgICBzZWxmLl9mYWlsKAog'
        'ICAgICAgICAgICAgICAgIiQuc2NoZW1hX3ZlcnNpb24iLAogICAgICAgICAgICAgICAgZiJleHBl'
        'Y3RlZCBpbnRlZ2VyIGNvbnN0YW50IHtfU0NIRU1BX1ZFUlNJT059OyBubyBvdGhlciBzY2hlbWEg'
        'dmVyc2lvbiBpcyBhY2NlcHRlZCIsCiAgICAgICAgICAgICkKCiAgICAgICAgbG9vcF9yb3dzID0g'
        'ZG9jdW1lbnRbImxvb3BzIl0KICAgICAgICBpZiBub3QgaXNpbnN0YW5jZShsb29wX3Jvd3MsIGxp'
        'c3QpOgogICAgICAgICAgICBzZWxmLl9mYWlsKCIkLmxvb3BzIiwgImV4cGVjdGVkIGFuIGFycmF5'
        'IikKICAgICAgICBpZiBub3QgbG9vcF9yb3dzOgogICAgICAgICAgICBzZWxmLl9mYWlsKCIkLmxv'
        'b3BzIiwgImV4cGVjdGVkIGF0IGxlYXN0IG9uZSBsb29wIGVudHJ5IikKCiAgICAgICAgbG9vcHM6'
        'IGxpc3RbUmVnaXN0ZXJlZExvb3BdID0gW10KICAgICAgICBzZWVuOiBkaWN0W3N0ciwgaW50XSA9'
        'IHt9CiAgICAgICAgZm9yIGluZGV4LCByb3cgaW4gZW51bWVyYXRlKGxvb3Bfcm93cyk6CiAgICAg'
        'ICAgICAgIGxvY2F0aW9uID0gZiIkLmxvb3BzW3tpbmRleH1dIgogICAgICAgICAgICBpZiBub3Qg'
        'aXNpbnN0YW5jZShyb3csIGRpY3QpOgogICAgICAgICAgICAgICAgc2VsZi5fZmFpbChsb2NhdGlv'
        'biwgImV4cGVjdGVkIGFuIG9iamVjdCIpCiAgICAgICAgICAgIHNlbGYuX3JlcXVpcmVfZXhhY3Rf'
        'ZmllbGRzKAogICAgICAgICAgICAgICAgcm93LCB7Imxvb3BfaWQiLCAibG9vcF9pbml0X3BhdGgi'
        'LCAiZmVlZF9wcm9maWxlcyJ9LCBsb2NhdGlvbgogICAgICAgICAgICApCgogICAgICAgICAgICBs'
        'b29wX2lkID0gcm93WyJsb29wX2lkIl0KICAgICAgICAgICAgaWYgbm90IGlzaW5zdGFuY2UobG9v'
        'cF9pZCwgc3RyKSBvciBub3QgX0xPT1BfSUQuZnVsbG1hdGNoKGxvb3BfaWQpOgogICAgICAgICAg'
        'ICAgICAgc2VsZi5fZmFpbCgKICAgICAgICAgICAgICAgICAgICBmIntsb2NhdGlvbn0ubG9vcF9p'
        'ZCIsCiAgICAgICAgICAgICAgICAgICAgImV4cGVjdGVkIGEgbm9uLWVtcHR5IGxvd2VyLWNhc2Ug'
        'aWRlbnRpZmllciIsCiAgICAgICAgICAgICAgICApCiAgICAgICAgICAgIGlmIGxvb3BfaWQgaW4g'
        'c2VlbjoKICAgICAgICAgICAgICAgIHNlbGYuX2ZhaWwoCiAgICAgICAgICAgICAgICAgICAgZiJ7'
        'bG9jYXRpb259Lmxvb3BfaWQiLAogICAgICAgICAgICAgICAgICAgIGYiZHVwbGljYXRlIGxvb3Ag'
        'aWRlbnRpZmllciBmaXJzdCBkZWNsYXJlZCBhdCAkLmxvb3BzW3tzZWVuW2xvb3BfaWRdfV0ubG9v'
        'cF9pZCIsCiAgICAgICAgICAgICAgICApCgogICAgICAgICAgICBsb29wX2luaXRfcGF0aCA9IHNl'
        'bGYuX3JlcG9zaXRvcnlfcGF0aCgKICAgICAgICAgICAgICAgIHJvd1sibG9vcF9pbml0X3BhdGgi'
        'XSwgZiJ7bG9jYXRpb259Lmxvb3BfaW5pdF9wYXRoIgogICAgICAgICAgICApCiAgICAgICAgICAg'
        'IGZlZWRfcHJvZmlsZXMgPSBzZWxmLl9mZWVkX3Byb2ZpbGVzKAogICAgICAgICAgICAgICAgcm93'
        'WyJmZWVkX3Byb2ZpbGVzIl0sIGYie2xvY2F0aW9ufS5mZWVkX3Byb2ZpbGVzIgogICAgICAgICAg'
        'ICApCgogICAgICAgICAgICBzZWVuW2xvb3BfaWRdID0gaW5kZXgKICAgICAgICAgICAgbG9vcHMu'
        'YXBwZW5kKAogICAgICAgICAgICAgICAgUmVnaXN0ZXJlZExvb3AoCiAgICAgICAgICAgICAgICAg'
        'ICAgbG9vcF9pZD1sb29wX2lkLAogICAgICAgICAgICAgICAgICAgIGxvb3BfaW5pdF9wYXRoPWxv'
        'b3BfaW5pdF9wYXRoLAogICAgICAgICAgICAgICAgICAgIGZlZWRfcHJvZmlsZXM9ZmVlZF9wcm9m'
        'aWxlcywKICAgICAgICAgICAgICAgICkKICAgICAgICAgICAgKQoKICAgICAgICByZXR1cm4gdHVw'
        'bGUobG9vcHMpCgogICAgZGVmIF9mZWVkX3Byb2ZpbGVzKHNlbGYsIHZhbHVlOiBBbnksIGxvY2F0'
        'aW9uOiBzdHIpIC0+IHR1cGxlW0ZlZWRQcm9maWxlLCAuLi5dOgogICAgICAgIGlmIG5vdCBpc2lu'
        'c3RhbmNlKHZhbHVlLCBsaXN0KToKICAgICAgICAgICAgc2VsZi5fZmFpbChsb2NhdGlvbiwgImV4'
        'cGVjdGVkIGFuIGFycmF5IikKICAgICAgICBpZiBub3QgdmFsdWU6CiAgICAgICAgICAgIHNlbGYu'
        'X2ZhaWwobG9jYXRpb24sICJleHBlY3RlZCBhdCBsZWFzdCBvbmUgZmVlZCBwcm9maWxlIikKCiAg'
        'ICAgICAgcHJvZmlsZXM6IGxpc3RbRmVlZFByb2ZpbGVdID0gW10KICAgICAgICBzZWVuOiBkaWN0'
        'W3N0ciwgaW50XSA9IHt9CiAgICAgICAgY292ZXJlZDogZGljdFtzdHIsIGludF0gPSB7fQogICAg'
        'ICAgIGZvciBpbmRleCwgZW50cnkgaW4gZW51bWVyYXRlKHZhbHVlKToKICAgICAgICAgICAgZW50'
        'cnlfbG9jYXRpb24gPSBmIntsb2NhdGlvbn1be2luZGV4fV0iCiAgICAgICAgICAgIGlmIG5vdCBp'
        'c2luc3RhbmNlKGVudHJ5LCBkaWN0KToKICAgICAgICAgICAgICAgIHNlbGYuX2ZhaWwoZW50cnlf'
        'bG9jYXRpb24sICJleHBlY3RlZCBhbiBvYmplY3QiKQogICAgICAgICAgICBzZWxmLl9yZXF1aXJl'
        'X2V4YWN0X2ZpZWxkcygKICAgICAgICAgICAgICAgIGVudHJ5LCB7InByb2ZpbGUiLCAidmVyc2lv'
        'biIsICJzdGF0ZSIsICJiYXNpcyJ9LCBlbnRyeV9sb2NhdGlvbgogICAgICAgICAgICApCgogICAg'
        'ICAgICAgICBwcm9maWxlID0gZW50cnlbInByb2ZpbGUiXQogICAgICAgICAgICBpZiBub3QgaXNp'
        'bnN0YW5jZShwcm9maWxlLCBzdHIpIG9yIHByb2ZpbGUgbm90IGluIEZFRURfUFJPRklMRV9WRVJT'
        'SU9OUzoKICAgICAgICAgICAgICAgIHNlbGYuX2ZhaWwoCiAgICAgICAgICAgICAgICAgICAgZiJ7'
        'ZW50cnlfbG9jYXRpb259LnByb2ZpbGUiLAogICAgICAgICAgICAgICAgICAgICJleHBlY3RlZCBh'
        'biBpZGVudGlmaWVyIGZyb20gdGhlIGNsb3NlZCBmZWVkLXByb2ZpbGUgdm9jYWJ1bGFyeSIsCiAg'
        'ICAgICAgICAgICAgICApCiAgICAgICAgICAgIGlmIHByb2ZpbGUgaW4gc2VlbjoKICAgICAgICAg'
        'ICAgICAgIHNlbGYuX2ZhaWwoCiAgICAgICAgICAgICAgICAgICAgZiJ7ZW50cnlfbG9jYXRpb259'
        'LnByb2ZpbGUiLAogICAgICAgICAgICAgICAgICAgIGYiZHVwbGljYXRlIGZlZWQgcHJvZmlsZSBm'
        'aXJzdCBkZWNsYXJlZCBhdCB7bG9jYXRpb259W3tzZWVuW3Byb2ZpbGVdfV0ucHJvZmlsZSIsCiAg'
        'ICAgICAgICAgICAgICApCgogICAgICAgICAgICB2ZXJzaW9uID0gZW50cnlbInZlcnNpb24iXQog'
        'ICAgICAgICAgICBpZiB0eXBlKHZlcnNpb24pIGlzIG5vdCBpbnQgb3IgdmVyc2lvbiBub3QgaW4g'
        'RkVFRF9QUk9GSUxFX1ZFUlNJT05TW3Byb2ZpbGVdOgogICAgICAgICAgICAgICAgc2VsZi5fZmFp'
        'bCgKICAgICAgICAgICAgICAgICAgICBmIntlbnRyeV9sb2NhdGlvbn0udmVyc2lvbiIsCiAgICAg'
        'ICAgICAgICAgICAgICAgZiJleHBlY3RlZCBhIHN1cHBvcnRlZCBpbnRlZ2VyIHZlcnNpb24gb2Yg'
        'ZmVlZCBwcm9maWxlIHtwcm9maWxlfSIsCiAgICAgICAgICAgICAgICApCgogICAgICAgICAgICBz'
        'dGF0ZSA9IGVudHJ5WyJzdGF0ZSJdCiAgICAgICAgICAgIGlmIG5vdCBpc2luc3RhbmNlKHN0YXRl'
        'LCBzdHIpIG9yIHN0YXRlIG5vdCBpbiB7CiAgICAgICAgICAgICAgICBtZW1iZXIudmFsdWUgZm9y'
        'IG1lbWJlciBpbiBGZWVkUHJvZmlsZVN0YXRlCiAgICAgICAgICAgIH06CiAgICAgICAgICAgICAg'
        'ICBzZWxmLl9mYWlsKGYie2VudHJ5X2xvY2F0aW9ufS5zdGF0ZSIsICJleHBlY3RlZCBsaXZlIG9y'
        'IGhpc3RvcmljYWwiKQoKICAgICAgICAgICAgYmFzaXMgPSBzZWxmLl9yZXBvc2l0b3J5X3BhdGgo'
        'ZW50cnlbImJhc2lzIl0sIGYie2VudHJ5X2xvY2F0aW9ufS5iYXNpcyIpCgogICAgICAgICAgICBm'
        'b3Igc3VyZmFjZSBpbiBzb3J0ZWQoRkVFRF9QUk9GSUxFX1NVUkZBQ0VTW3Byb2ZpbGVdKToKICAg'
        'ICAgICAgICAgICAgIGlmIHN1cmZhY2UgaW4gY292ZXJlZDoKICAgICAgICAgICAgICAgICAgICBz'
        'ZWxmLl9mYWlsKAogICAgICAgICAgICAgICAgICAgICAgICBmIntlbnRyeV9sb2NhdGlvbn0ucHJv'
        'ZmlsZSIsCiAgICAgICAgICAgICAgICAgICAgICAgIGYic3VyZmFjZSB7c3VyZmFjZX0gaXMgYWxy'
        'ZWFkeSBjb3ZlcmVkIGJ5ICIKICAgICAgICAgICAgICAgICAgICAgICAgZiJ7bG9jYXRpb259W3tj'
        'b3ZlcmVkW3N1cmZhY2VdfV0ucHJvZmlsZSIsCiAgICAgICAgICAgICAgICAgICAgKQogICAgICAg'
        'ICAgICBmb3Igc3VyZmFjZSBpbiBGRUVEX1BST0ZJTEVfU1VSRkFDRVNbcHJvZmlsZV06CiAgICAg'
        'ICAgICAgICAgICBjb3ZlcmVkW3N1cmZhY2VdID0gaW5kZXgKCiAgICAgICAgICAgIHNlZW5bcHJv'
        'ZmlsZV0gPSBpbmRleAogICAgICAgICAgICBwcm9maWxlcy5hcHBlbmQoCiAgICAgICAgICAgICAg'
        'ICBGZWVkUHJvZmlsZSgKICAgICAgICAgICAgICAgICAgICBwcm9maWxlPXByb2ZpbGUsCiAgICAg'
        'ICAgICAgICAgICAgICAgdmVyc2lvbj12ZXJzaW9uLAogICAgICAgICAgICAgICAgICAgIHN0YXRl'
        'PUZlZWRQcm9maWxlU3RhdGUoc3RhdGUpLAogICAgICAgICAgICAgICAgICAgIGJhc2lzPWJhc2lz'
        'LAogICAgICAgICAgICAgICAgKQogICAgICAgICAgICApCgogICAgICAgIGlmIG5vdCBhbnkoaXRl'
        'bS5zdGF0ZSBpcyBGZWVkUHJvZmlsZVN0YXRlLkxJVkUgZm9yIGl0ZW0gaW4gcHJvZmlsZXMpOgog'
        'ICAgICAgICAgICBzZWxmLl9mYWlsKGxvY2F0aW9uLCAiZXhwZWN0ZWQgYXQgbGVhc3Qgb25lIGxp'
        'dmUgZmVlZCBwcm9maWxlIikKICAgICAgICByZXR1cm4gdHVwbGUocHJvZmlsZXMpCgogICAgZGVm'
        'IF9yZXBvc2l0b3J5X3BhdGgoc2VsZiwgdmFsdWU6IEFueSwgbG9jYXRpb246IHN0cikgLT4gc3Ry'
        'OgogICAgICAgIGlmIG5vdCBpc2luc3RhbmNlKHZhbHVlLCBzdHIpIG9yIG5vdCB2YWx1ZToKICAg'
        'ICAgICAgICAgc2VsZi5fZmFpbChsb2NhdGlvbiwgImV4cGVjdGVkIGEgbm9uLWVtcHR5IHN0cmlu'
        'ZyIpCiAgICAgICAgbG9jYXRvciA9IFB1cmVQb3NpeFBhdGgodmFsdWUpCiAgICAgICAgaWYgbG9j'
        'YXRvci5pc19hYnNvbHV0ZSgpIG9yICIuLiIgaW4gbG9jYXRvci5wYXJ0cyBvciAiXFwiIGluIHZh'
        'bHVlOgogICAgICAgICAgICBzZWxmLl9mYWlsKGxvY2F0aW9uLCAiZXhwZWN0ZWQgYSBub3JtYWxp'
        'emVkIHJlcG9zaXRvcnktcmVsYXRpdmUgcGF0aCIpCiAgICAgICAgcmV0dXJuIHZhbHVlCgogICAg'
        'ZGVmIF9yZXF1aXJlX2V4YWN0X2ZpZWxkcygKICAgICAgICBzZWxmLCB2YWx1ZTogZGljdFtzdHIs'
        'IEFueV0sIGV4cGVjdGVkOiBzZXRbc3RyXSwgbG9jYXRpb246IHN0cgogICAgKSAtPiBOb25lOgog'
        'ICAgICAgIG1pc3NpbmcgPSBzb3J0ZWQoZXhwZWN0ZWQgLSB2YWx1ZS5rZXlzKCkpCiAgICAgICAg'
        'aWYgbWlzc2luZzoKICAgICAgICAgICAgc2VsZi5fZmFpbChmIntsb2NhdGlvbn0ue21pc3Npbmdb'
        'MF19IiwgInJlcXVpcmVkIGZpZWxkIGlzIG1pc3NpbmciKQogICAgICAgIHVuZXhwZWN0ZWQgPSBz'
        'b3J0ZWQodmFsdWUua2V5cygpIC0gZXhwZWN0ZWQpCiAgICAgICAgaWYgdW5leHBlY3RlZDoKICAg'
        'ICAgICAgICAgc2VsZi5fZmFpbCgKICAgICAgICAgICAgICAgIGYie2xvY2F0aW9ufS57dW5leHBl'
        'Y3RlZFswXX0iLAogICAgICAgICAgICAgICAgZiJmaWVsZCBpcyBub3QgZGVmaW5lZCBieSBzY2hl'
        'bWEgdntfU0NIRU1BX1ZFUlNJT059IiwKICAgICAgICAgICAgKQoKICAgIGRlZiBfZmFpbChzZWxm'
        'LCBsb2NhdGlvbjogc3RyLCBtZXNzYWdlOiBzdHIpIC0+IE5vbmU6CiAgICAgICAgcmFpc2UgTG9v'
        'cFJlZ2lzdHJ5Q29uZmlnRXJyb3IoZiJ7c2VsZi5fY29uZmlnX3BhdGh9Ontsb2NhdGlvbn06IHtt'
        'ZXNzYWdlfSIpCg=='
    ),
    '6875f50023f1ad34a45c1af4b0a65316260c45aa05562ce45bb2d9bd8fd13c7e': (
        'ewogICJsb29wcyI6IFsKICAgIHsKICAgICAgImZlZWRfcHJvZmlsZXMiOiBbCiAgICAgICAgewog'
        'ICAgICAgICAgImJhc2lzIjogInByb2plY3RzL3BlYy9leGVjdXRpb24vX0Nvb3JkaW5hdGlvbi9f'
        'REVDSVNJT05TL0QtUEVDLTk0X293bmVyX2RpcmVjdGlvbl9sb29wX21pZ3JhdGlvbl8yMDI2LTA5'
        'LTI1Lm1kIiwKICAgICAgICAgICJwcm9maWxlIjogInNoYXJlZC1kZXYtbG9vcCIsCiAgICAgICAg'
        'ICAic3RhdGUiOiAibGl2ZSIsCiAgICAgICAgICAidmVyc2lvbiI6IDEKICAgICAgICB9CiAgICAg'
        'IF0sCiAgICAgICJsb29wX2lkIjogInBlYyIsCiAgICAgICJsb29wX2luaXRfcGF0aCI6ICJwcm9q'
        'ZWN0cy9wZWMvbG9vcC9MT09QX0lOSVQubWQiCiAgICB9LAogICAgewogICAgICAiZmVlZF9wcm9m'
        'aWxlcyI6IFsKICAgICAgICB7CiAgICAgICAgICAiYmFzaXMiOiAicHJvamVjdHMvcGVjL2V4ZWN1'
        'dGlvbi9fQ29vcmRpbmF0aW9uL19ERUNJU0lPTlMvRC1QRUMtOTRfb3duZXJfZGlyZWN0aW9uX2xv'
        'b3BfbWlncmF0aW9uXzIwMjYtMDktMjUubWQiLAogICAgICAgICAgInByb2ZpbGUiOiAic2hhcmVk'
        'LWRldi1sb29wIiwKICAgICAgICAgICJzdGF0ZSI6ICJsaXZlIiwKICAgICAgICAgICJ2ZXJzaW9u'
        'IjogMQogICAgICAgIH0KICAgICAgXSwKICAgICAgImxvb3BfaWQiOiAicGVjIiwKICAgICAgImxv'
        'b3BfaW5pdF9wYXRoIjogInNvbWV3aGVyZS9lbHNlL0xPT1BfSU5JVC5tZCIKICAgIH0KICBdLAog'
        'ICJzY2hlbWFfdmVyc2lvbiI6IDIKfQo='
    ),
    '8b45495fdc78eb77c12a4ebefdb064d34d40d5602fde573be4b4e817ddbe0c9b': (
        'ZnJvbSBfX2Z1dHVyZV9fIGltcG9ydCBhbm5vdGF0aW9ucwoKaW1wb3J0IGNvcHkKaW1wb3J0IGpz'
        'b24KaW1wb3J0IHN5cwppbXBvcnQgdGVtcGZpbGUKaW1wb3J0IHVuaXR0ZXN0CmZyb20gcGF0aGxp'
        'YiBpbXBvcnQgUGF0aApmcm9tIHVuaXR0ZXN0IGltcG9ydCBtb2NrCgoKVjJfUk9PVCA9IFBhdGgo'
        'X19maWxlX18pLnJlc29sdmUoKS5wYXJlbnRzWzJdClNSQ19ST09UID0gVjJfUk9PVCAvICJzcmMi'
        'CkNPTkZJR19ST09UID0gVjJfUk9PVCAvICJjb25maWciCkZJWFRVUkVTID0gUGF0aChfX2ZpbGVf'
        'XykucmVzb2x2ZSgpLnBhcmVudCAvICJmaXh0dXJlcyIKc3lzLnBhdGguaW5zZXJ0KDAsIHN0cihT'
        'UkNfUk9PVCkpCgpmcm9tIHBlY192Mi5hZGFwdGVycy5jb25maWcubG9vcF9yZWdpc3RyeSBpbXBv'
        'cnQgKCAgIyBub3FhOiBFNDAyCiAgICBGRUVEX1BST0ZJTEVfU1VSRkFDRVMsCiAgICBGRUVEX1BS'
        'T0ZJTEVfVkVSU0lPTlMsCiAgICBKc29uTG9vcFJlZ2lzdHJ5LAogICAgTG9vcFJlZ2lzdHJ5Q29u'
        'ZmlnRXJyb3IsCikKZnJvbSBwZWNfdjIuY29yZS5wb3J0cy5sb29wX3JlZ2lzdHJ5IGltcG9ydCAo'
        'ICAjIG5vcWE6IEU0MDIKICAgIEZlZWRQcm9maWxlLAogICAgRmVlZFByb2ZpbGVTdGF0ZSwKICAg'
        'IFJlZ2lzdGVyZWRMb29wLAopCgoKUEVDX0xPT1BfSU5JVCA9ICJwcm9qZWN0cy9wZWMvbG9vcC9M'
        'T09QX0lOSVQubWQiClBFQ19BR0VOVFMgPSAicHJvamVjdHMvcGVjL0FHRU5UUy5tZCIKRF9QRUNf'
        'OTQgPSAoCiAgICAicHJvamVjdHMvcGVjL2V4ZWN1dGlvbi9fQ29vcmRpbmF0aW9uL19ERUNJU0lP'
        'TlMvIgogICAgIkQtUEVDLTk0X293bmVyX2RpcmVjdGlvbl9sb29wX21pZ3JhdGlvbl8yMDI2LTA5'
        'LTI1Lm1kIgopCgoKZGVmIHZhbGlkX2RvY3VtZW50KCkgLT4gZGljdDoKICAgIHJldHVybiB7CiAg'
        'ICAgICAgInNjaGVtYV92ZXJzaW9uIjogMiwKICAgICAgICAibG9vcHMiOiBbCiAgICAgICAgICAg'
        'IHsKICAgICAgICAgICAgICAgICJsb29wX2lkIjogInBlYyIsCiAgICAgICAgICAgICAgICAibG9v'
        'cF9pbml0X3BhdGgiOiBQRUNfTE9PUF9JTklULAogICAgICAgICAgICAgICAgImZlZWRfcHJvZmls'
        'ZXMiOiBbCiAgICAgICAgICAgICAgICAgICAgeyJwcm9maWxlIjogInNoYXJlZC1kZXYtbG9vcCIs'
        'ICJ2ZXJzaW9uIjogMSwgInN0YXRlIjogImxpdmUiLCAiYmFzaXMiOiBEX1BFQ185NH0sCiAgICAg'
        'ICAgICAgICAgICAgICAgeyJwcm9maWxlIjogImxvb3AtcmVjZWlwdHMtbGVkZ2VyIiwgInZlcnNp'
        'b24iOiAxLCAic3RhdGUiOiAiaGlzdG9yaWNhbCIsICJiYXNpcyI6IFBFQ19BR0VOVFN9LAogICAg'
        'ICAgICAgICAgICAgICAgIHsicHJvZmlsZSI6ICJhZ2VudHJ1bnMtanNvbiIsICJ2ZXJzaW9uIjog'
        'MSwgInN0YXRlIjogImhpc3RvcmljYWwiLCAiYmFzaXMiOiBEX1BFQ185NH0sCiAgICAgICAgICAg'
        'ICAgICBdLAogICAgICAgICAgICB9CiAgICAgICAgXSwKICAgIH0KCgpjbGFzcyBKc29uTG9vcFJl'
        'Z2lzdHJ5VGVzdHModW5pdHRlc3QuVGVzdENhc2UpOgogICAgZGVmIGxvYWQoc2VsZiwgZG9jdW1l'
        'bnQ6IG9iamVjdCkgLT4gdHVwbGVbUmVnaXN0ZXJlZExvb3AsIC4uLl06CiAgICAgICAgd2l0aCB0'
        'ZW1wZmlsZS5UZW1wb3JhcnlEaXJlY3RvcnkoKSBhcyB0ZW1wb3Jhcnk6CiAgICAgICAgICAgIHBh'
        'dGggPSBQYXRoKHRlbXBvcmFyeSkgLyAiY2FuZGlkYXRlLmpzb24iCiAgICAgICAgICAgIHBhdGgu'
        'd3JpdGVfdGV4dChqc29uLmR1bXBzKGRvY3VtZW50KSwgZW5jb2Rpbmc9InV0Zi04IikKICAgICAg'
        'ICAgICAgcmV0dXJuIEpzb25Mb29wUmVnaXN0cnkocGF0aCkucmVnaXN0ZXJlZF9sb29wcygpCgog'
        'ICAgZGVmIHRlc3RfY2hlY2tlZF9pbl9kZWZhdWx0X2hhc19leGFjdGx5X3RoZV9wZWNfbG9vcChz'
        'ZWxmKSAtPiBOb25lOgogICAgICAgIGxvb3BzID0gSnNvbkxvb3BSZWdpc3RyeShDT05GSUdfUk9P'
        'VCAvICJsb29wcy5qc29uIikucmVnaXN0ZXJlZF9sb29wcygpCiAgICAgICAgc2VsZi5hc3NlcnRF'
        'cXVhbCgKICAgICAgICAgICAgbG9vcHMsCiAgICAgICAgICAgICgKICAgICAgICAgICAgICAgIFJl'
        'Z2lzdGVyZWRMb29wKAogICAgICAgICAgICAgICAgICAgICJwZWMiLAogICAgICAgICAgICAgICAg'
        'ICAgIFBFQ19MT09QX0lOSVQsCiAgICAgICAgICAgICAgICAgICAgKAogICAgICAgICAgICAgICAg'
        'ICAgICAgICBGZWVkUHJvZmlsZSgic2hhcmVkLWRldi1sb29wIiwgMSwgRmVlZFByb2ZpbGVTdGF0'
        'ZS5MSVZFLCBEX1BFQ185NCksCiAgICAgICAgICAgICAgICAgICAgICAgIEZlZWRQcm9maWxlKCJs'
        'b29wLXJlY2VpcHRzLWxlZGdlciIsIDEsIEZlZWRQcm9maWxlU3RhdGUuSElTVE9SSUNBTCwgUEVD'
        'X0FHRU5UUyksCiAgICAgICAgICAgICAgICAgICAgICAgIEZlZWRQcm9maWxlKCJhZ2VudHJ1bnMt'
        'anNvbiIsIDEsIEZlZWRQcm9maWxlU3RhdGUuSElTVE9SSUNBTCwgRF9QRUNfOTQpLAogICAgICAg'
        'ICAgICAgICAgICAgICksCiAgICAgICAgICAgICAgICApLAogICAgICAgICAgICApLAogICAgICAg'
        'ICkKCiAgICBkZWYgdGVzdF9zY2hlbWFfZG9jdW1lbnRzX2V2ZXJ5X2ZpZWxkX2FuZF90aGVfZXhh'
        'Y3RfZGVmYXVsdChzZWxmKSAtPiBOb25lOgogICAgICAgIHNjaGVtYSA9IGpzb24ubG9hZHMoKENP'
        'TkZJR19ST09UIC8gImxvb3BzLnNjaGVtYS5qc29uIikucmVhZF90ZXh0KGVuY29kaW5nPSJ1dGYt'
        'OCIpKQogICAgICAgIGRvY3VtZW50ID0ganNvbi5sb2FkcygoQ09ORklHX1JPT1QgLyAibG9vcHMu'
        'anNvbiIpLnJlYWRfdGV4dChlbmNvZGluZz0idXRmLTgiKSkKICAgICAgICBzZWxmLmFzc2VydEVx'
        'dWFsKHNjaGVtYVsiJHNjaGVtYSJdLCAiaHR0cHM6Ly9qc29uLXNjaGVtYS5vcmcvZHJhZnQvMjAy'
        'MC0xMi9zY2hlbWEiKQogICAgICAgIHNlbGYuYXNzZXJ0RXF1YWwoc2NoZW1hWyIkaWQiXSwgImh0'
        'dHBzOi8vY2hpcmFsaXR5LmxvY2FsL3BlYy92Mi9jb25maWcvbG9vcHMuc2NoZW1hLnYyLmpzb24i'
        'KQogICAgICAgIHNlbGYuYXNzZXJ0RXF1YWwoc2NoZW1hWyJwcm9wZXJ0aWVzIl1bInNjaGVtYV92'
        'ZXJzaW9uIl1bImNvbnN0Il0sIDIpCiAgICAgICAgc2VsZi5hc3NlcnRFcXVhbChkb2N1bWVudFsi'
        'c2NoZW1hX3ZlcnNpb24iXSwgMikKICAgICAgICBzZWxmLmFzc2VydEVxdWFsKGxlbihkb2N1bWVu'
        'dFsibG9vcHMiXSksIDEpCiAgICAgICAgZm9yIGZpZWxkIGluICgic2NoZW1hX3ZlcnNpb24iLCAi'
        'bG9vcHMiKToKICAgICAgICAgICAgc2VsZi5hc3NlcnRUcnVlKHNjaGVtYVsicHJvcGVydGllcyJd'
        'W2ZpZWxkXVsiZGVzY3JpcHRpb24iXSkKICAgICAgICByb3cgPSBzY2hlbWFbInByb3BlcnRpZXMi'
        'XVsibG9vcHMiXVsiaXRlbXMiXQogICAgICAgIHNlbGYuYXNzZXJ0RXF1YWwoc29ydGVkKHJvd1si'
        'cmVxdWlyZWQiXSksIFsiZmVlZF9wcm9maWxlcyIsICJsb29wX2lkIiwgImxvb3BfaW5pdF9wYXRo'
        'Il0pCiAgICAgICAgZm9yIGZpZWxkIGluICgibG9vcF9pZCIsICJsb29wX2luaXRfcGF0aCIsICJm'
        'ZWVkX3Byb2ZpbGVzIik6CiAgICAgICAgICAgIHNlbGYuYXNzZXJ0VHJ1ZShyb3dbInByb3BlcnRp'
        'ZXMiXVtmaWVsZF1bImRlc2NyaXB0aW9uIl0pCiAgICAgICAgZW50cnkgPSByb3dbInByb3BlcnRp'
        'ZXMiXVsiZmVlZF9wcm9maWxlcyJdWyJpdGVtcyJdCiAgICAgICAgc2VsZi5hc3NlcnRGYWxzZShl'
        'bnRyeVsiYWRkaXRpb25hbFByb3BlcnRpZXMiXSkKICAgICAgICBzZWxmLmFzc2VydEVxdWFsKHNv'
        'cnRlZChlbnRyeVsicmVxdWlyZWQiXSksIFsiYmFzaXMiLCAicHJvZmlsZSIsICJzdGF0ZSIsICJ2'
        'ZXJzaW9uIl0pCiAgICAgICAgZm9yIGZpZWxkIGluICgicHJvZmlsZSIsICJ2ZXJzaW9uIiwgInN0'
        'YXRlIiwgImJhc2lzIik6CiAgICAgICAgICAgIHNlbGYuYXNzZXJ0VHJ1ZShlbnRyeVsicHJvcGVy'
        'dGllcyJdW2ZpZWxkXVsiZGVzY3JpcHRpb24iXSkKICAgICAgICBkZWNsYXJlZCA9IHtvcHRpb25b'
        'ImNvbnN0Il06IG9wdGlvblsiZGVzY3JpcHRpb24iXSBmb3Igb3B0aW9uIGluIGVudHJ5WyJwcm9w'
        'ZXJ0aWVzIl1bInByb2ZpbGUiXVsib25lT2YiXX0KICAgICAgICBzZWxmLmFzc2VydEVxdWFsKHNl'
        'dChkZWNsYXJlZCksIHNldChGRUVEX1BST0ZJTEVfVkVSU0lPTlMpKQogICAgICAgIHNlbGYuYXNz'
        'ZXJ0RXF1YWwoc2V0KEZFRURfUFJPRklMRV9TVVJGQUNFUyksIHNldChGRUVEX1BST0ZJTEVfVkVS'
        'U0lPTlMpKQogICAgICAgIGZvciBwcm9maWxlLCBkZXNjcmlwdGlvbiBpbiBkZWNsYXJlZC5pdGVt'
        'cygpOgogICAgICAgICAgICB3aXRoIHNlbGYuc3ViVGVzdChwcm9maWxlPXByb2ZpbGUpOgogICAg'
        'ICAgICAgICAgICAgXywgXywgbGlzdGVkID0gZGVzY3JpcHRpb24ucnN0cmlwKCIuIikucGFydGl0'
        'aW9uKCIgU3VyZmFjZXM6ICIpCiAgICAgICAgICAgICAgICBzZWxmLmFzc2VydEVxdWFsKHNldChs'
        'aXN0ZWQuc3BsaXQoIiwgIikpLCBzZXQoRkVFRF9QUk9GSUxFX1NVUkZBQ0VTW3Byb2ZpbGVdKSkK'
        'ICAgICAgICBzZWxmLmFzc2VydEVxdWFsKHtlbnRyeVsicHJvcGVydGllcyJdWyJ2ZXJzaW9uIl1b'
        'ImNvbnN0Il19LCBzZXQoKS51bmlvbigqRkVFRF9QUk9GSUxFX1ZFUlNJT05TLnZhbHVlcygpKSkK'
        'ICAgICAgICBzZWxmLmFzc2VydEVxdWFsKAogICAgICAgICAgICBzZXQoZW50cnlbInByb3BlcnRp'
        'ZXMiXVsic3RhdGUiXVsiZW51bSJdKSwKICAgICAgICAgICAge21lbWJlci52YWx1ZSBmb3IgbWVt'
        'YmVyIGluIEZlZWRQcm9maWxlU3RhdGV9LAogICAgICAgICkKCiAgICBkZWYgdGVzdF9zY2hlbWFf'
        'dmVyc2lvbl8xX2lzX3JlamVjdGVkX3dpdGhfbG9jYXRpb24oc2VsZikgLT4gTm9uZToKICAgICAg'
        'ICB3aXRoIHNlbGYuYXNzZXJ0UmFpc2VzUmVnZXgoCiAgICAgICAgICAgIExvb3BSZWdpc3RyeUNv'
        'bmZpZ0Vycm9yLAogICAgICAgICAgICByInNjaGVtYV92ZXJzaW9uXzFcLmpzb246XCRcLnNjaGVt'
        'YV92ZXJzaW9uOiBleHBlY3RlZCBpbnRlZ2VyIGNvbnN0YW50IDIiLAogICAgICAgICk6CiAgICAg'
        'ICAgICAgIEpzb25Mb29wUmVnaXN0cnkoRklYVFVSRVMgLyAic2NoZW1hX3ZlcnNpb25fMS5qc29u'
        'IikucmVnaXN0ZXJlZF9sb29wcygpCgogICAgZGVmIHRlc3RfbWlzc2luZ19sb29wX2lkX2lzX3Jl'
        'amVjdGVkX3dpdGhfbG9jYXRpb24oc2VsZikgLT4gTm9uZToKICAgICAgICB3aXRoIHNlbGYuYXNz'
        'ZXJ0UmFpc2VzUmVnZXgoTG9vcFJlZ2lzdHJ5Q29uZmlnRXJyb3IsIHIiXCRcLmxvb3BzXFswXF1c'
        'Lmxvb3BfaWQiKToKICAgICAgICAgICAgSnNvbkxvb3BSZWdpc3RyeShGSVhUVVJFUyAvICJtaXNz'
        'aW5nX2xvb3BfaWQuanNvbiIpLnJlZ2lzdGVyZWRfbG9vcHMoKQoKICAgIGRlZiB0ZXN0X2R1cGxp'
        'Y2F0ZV9sb29wX2lkX2lzX3JlamVjdGVkX3dpdGhfbG9jYXRpb24oc2VsZikgLT4gTm9uZToKICAg'
        'ICAgICB3aXRoIHNlbGYuYXNzZXJ0UmFpc2VzUmVnZXgoTG9vcFJlZ2lzdHJ5Q29uZmlnRXJyb3Is'
        'IHIiXCRcLmxvb3BzXFsxXF1cLmxvb3BfaWQiKToKICAgICAgICAgICAgSnNvbkxvb3BSZWdpc3Ry'
        'eShGSVhUVVJFUyAvICJkdXBsaWNhdGVfbG9vcF9pZC5qc29uIikucmVnaXN0ZXJlZF9sb29wcygp'
        'CgogICAgZGVmIHRlc3RfbWFsZm9ybWVkX2pzb25faXNfcmVqZWN0ZWRfd2l0aF9saW5lX2FuZF9j'
        'b2x1bW4oc2VsZikgLT4gTm9uZToKICAgICAgICB3aXRoIHNlbGYuYXNzZXJ0UmFpc2VzUmVnZXgo'
        'CiAgICAgICAgICAgIExvb3BSZWdpc3RyeUNvbmZpZ0Vycm9yLCByIm1hbGZvcm1lZFwuanNvbjog'
        'bWFsZm9ybWVkIEpTT04gYXQgbGluZSBbMC05XSssIGNvbHVtbiBbMC05XSsiCiAgICAgICAgKToK'
        'ICAgICAgICAgICAgSnNvbkxvb3BSZWdpc3RyeShGSVhUVVJFUyAvICJtYWxmb3JtZWQuanNvbiIp'
        'LnJlZ2lzdGVyZWRfbG9vcHMoKQoKICAgIGRlZiB0ZXN0X2Fic2VudF9maWxlX2lzX3JlamVjdGVk'
        'X2V4cGxpY2l0bHkoc2VsZikgLT4gTm9uZToKICAgICAgICB3aXRoIHRlbXBmaWxlLlRlbXBvcmFy'
        'eURpcmVjdG9yeSgpIGFzIHRlbXBvcmFyeToKICAgICAgICAgICAgbWlzc2luZyA9IFBhdGgodGVt'
        'cG9yYXJ5KSAvICJhYnNlbnQuanNvbiIKICAgICAgICAgICAgd2l0aCBzZWxmLmFzc2VydFJhaXNl'
        'c1JlZ2V4KExvb3BSZWdpc3RyeUNvbmZpZ0Vycm9yLCByImFic2VudFwuanNvbjogY29uZmlndXJh'
        'dGlvbiBmaWxlIGRvZXMgbm90IGV4aXN0Iik6CiAgICAgICAgICAgICAgICBKc29uTG9vcFJlZ2lz'
        'dHJ5KG1pc3NpbmcpLnJlZ2lzdGVyZWRfbG9vcHMoKQoKICAgIGRlZiB0ZXN0X3VucmVhZGFibGVf'
        'cGF0aF9pc19yZWplY3RlZF9leHBsaWNpdGx5KHNlbGYpIC0+IE5vbmU6CiAgICAgICAgd2l0aCB0'
        'ZW1wZmlsZS5UZW1wb3JhcnlEaXJlY3RvcnkoKSBhcyB0ZW1wb3Jhcnk6CiAgICAgICAgICAgIGRp'
        'cmVjdG9yeSA9IFBhdGgodGVtcG9yYXJ5KSAvICJub3QtYS1maWxlLmpzb24iCiAgICAgICAgICAg'
        'IGRpcmVjdG9yeS5ta2RpcigpCiAgICAgICAgICAgIHdpdGggc2VsZi5hc3NlcnRSYWlzZXNSZWdl'
        'eChMb29wUmVnaXN0cnlDb25maWdFcnJvciwgciJjb25maWd1cmF0aW9uIGZpbGUgaXMgdW5yZWFk'
        'YWJsZSIpOgogICAgICAgICAgICAgICAgSnNvbkxvb3BSZWdpc3RyeShkaXJlY3RvcnkpLnJlZ2lz'
        'dGVyZWRfbG9vcHMoKQoKICAgIGRlZiB0ZXN0X2ludmFsaWRfZmVlZF9wcm9maWxlc19hcmVfcmVq'
        'ZWN0ZWRfd2l0aF9sb2NhdGlvbihzZWxmKSAtPiBOb25lOgogICAgICAgIHJvdyA9ICIkLmxvb3Bz'
        'WzBdIgogICAgICAgIGVudHJ5ID0gZiJ7cm93fS5mZWVkX3Byb2ZpbGVzWzBdIgoKICAgICAgICBk'
        'ZWYgd2l0aG91dChtYXBwaW5nOiBkaWN0LCBrZXk6IHN0cikgLT4gZGljdDoKICAgICAgICAgICAg'
        'cmV0dXJuIHtuYW1lOiB2YWx1ZSBmb3IgbmFtZSwgdmFsdWUgaW4gbWFwcGluZy5pdGVtcygpIGlm'
        'IG5hbWUgIT0ga2V5fQoKICAgICAgICBjYXNlcyA9IHsKICAgICAgICAgICAgInJvdyBtaXNzaW5n'
        'IGZlZWRfcHJvZmlsZXMiOiAobGFtYmRhIGQ6IGRbImxvb3BzIl0uX19zZXRpdGVtX18oMCwgd2l0'
        'aG91dChkWyJsb29wcyJdWzBdLCAiZmVlZF9wcm9maWxlcyIpKSwgZiJ7cm93fS5mZWVkX3Byb2Zp'
        'bGVzIiwgInJlcXVpcmVkIGZpZWxkIGlzIG1pc3NpbmciKSwKICAgICAgICAgICAgInJvdyB1bmtu'
        'b3duIGZpZWxkIjogKGxhbWJkYSBkOiBkWyJsb29wcyJdWzBdLl9fc2V0aXRlbV9fKCJncmFtbWFy'
        'IiwgIngiKSwgZiJ7cm93fS5ncmFtbWFyIiwgImZpZWxkIGlzIG5vdCBkZWZpbmVkIGJ5IHNjaGVt'
        'YSB2MiIpLAogICAgICAgICAgICAiZmVlZF9wcm9maWxlcyBub3QgYW4gYXJyYXkiOiAobGFtYmRh'
        'IGQ6IGRbImxvb3BzIl1bMF0uX19zZXRpdGVtX18oImZlZWRfcHJvZmlsZXMiLCB7fSksIGYie3Jv'
        'd30uZmVlZF9wcm9maWxlcyIsICJleHBlY3RlZCBhbiBhcnJheSIpLAogICAgICAgICAgICAiZmVl'
        'ZF9wcm9maWxlcyBlbXB0eSI6IChsYW1iZGEgZDogZFsibG9vcHMiXVswXS5fX3NldGl0ZW1fXygi'
        'ZmVlZF9wcm9maWxlcyIsIFtdKSwgZiJ7cm93fS5mZWVkX3Byb2ZpbGVzIiwgImV4cGVjdGVkIGF0'
        'IGxlYXN0IG9uZSBmZWVkIHByb2ZpbGUiKSwKICAgICAgICAgICAgImVudHJ5IG5vdCBhbiBvYmpl'
        'Y3QiOiAobGFtYmRhIGQ6IGRbImxvb3BzIl1bMF1bImZlZWRfcHJvZmlsZXMiXS5fX3NldGl0ZW1f'
        'XygwLCAic2hhcmVkLWRldi1sb29wIiksIGVudHJ5LCAiZXhwZWN0ZWQgYW4gb2JqZWN0IiksCiAg'
        'ICAgICAgICAgICJlbnRyeSBtaXNzaW5nIGJhc2lzIjogKGxhbWJkYSBkOiBkWyJsb29wcyJdWzBd'
        'WyJmZWVkX3Byb2ZpbGVzIl0uX19zZXRpdGVtX18oMCwgd2l0aG91dChkWyJsb29wcyJdWzBdWyJm'
        'ZWVkX3Byb2ZpbGVzIl1bMF0sICJiYXNpcyIpKSwgZiJ7ZW50cnl9LmJhc2lzIiwgInJlcXVpcmVk'
        'IGZpZWxkIGlzIG1pc3NpbmciKSwKICAgICAgICAgICAgImVudHJ5IHVua25vd24gZmllbGQiOiAo'
        'bGFtYmRhIGQ6IGRbImxvb3BzIl1bMF1bImZlZWRfcHJvZmlsZXMiXVswXS5fX3NldGl0ZW1fXygi'
        'cGF0aHMiLCBbIngiXSksIGYie2VudHJ5fS5wYXRocyIsICJmaWVsZCBpcyBub3QgZGVmaW5lZCBi'
        'eSBzY2hlbWEgdjIiKSwKICAgICAgICAgICAgInVua25vd24gcHJvZmlsZSI6IChsYW1iZGEgZDog'
        'ZFsibG9vcHMiXVswXVsiZmVlZF9wcm9maWxlcyJdWzBdLl9fc2V0aXRlbV9fKCJwcm9maWxlIiwg'
        'ImFkYXB0ZXIteWFtbCIpLCBmIntlbnRyeX0ucHJvZmlsZSIsICJjbG9zZWQgZmVlZC1wcm9maWxl'
        'IHZvY2FidWxhcnkiKSwKICAgICAgICAgICAgInByb2ZpbGUgbm90IGEgc3RyaW5nIjogKGxhbWJk'
        'YSBkOiBkWyJsb29wcyJdWzBdWyJmZWVkX3Byb2ZpbGVzIl1bMF0uX19zZXRpdGVtX18oInByb2Zp'
        'bGUiLCAxKSwgZiJ7ZW50cnl9LnByb2ZpbGUiLCAiY2xvc2VkIGZlZWQtcHJvZmlsZSB2b2NhYnVs'
        'YXJ5IiksCiAgICAgICAgICAgICJkdXBsaWNhdGUgcHJvZmlsZSI6IChsYW1iZGEgZDogZFsibG9v'
        'cHMiXVswXVsiZmVlZF9wcm9maWxlcyJdWzFdLl9fc2V0aXRlbV9fKCJwcm9maWxlIiwgInNoYXJl'
        'ZC1kZXYtbG9vcCIpLCBmIntyb3d9LmZlZWRfcHJvZmlsZXNbMV0ucHJvZmlsZSIsICJkdXBsaWNh'
        'dGUgZmVlZCBwcm9maWxlIGZpcnN0IGRlY2xhcmVkIGF0IiksCiAgICAgICAgICAgICJ1bnN1cHBv'
        'cnRlZCB2ZXJzaW9uIjogKGxhbWJkYSBkOiBkWyJsb29wcyJdWzBdWyJmZWVkX3Byb2ZpbGVzIl1b'
        'MF0uX19zZXRpdGVtX18oInZlcnNpb24iLCAyKSwgZiJ7ZW50cnl9LnZlcnNpb24iLCAic3VwcG9y'
        'dGVkIGludGVnZXIgdmVyc2lvbiIpLAogICAgICAgICAgICAiYm9vbGVhbiB2ZXJzaW9uIjogKGxh'
        'bWJkYSBkOiBkWyJsb29wcyJdWzBdWyJmZWVkX3Byb2ZpbGVzIl1bMF0uX19zZXRpdGVtX18oInZl'
        'cnNpb24iLCBUcnVlKSwgZiJ7ZW50cnl9LnZlcnNpb24iLCAic3VwcG9ydGVkIGludGVnZXIgdmVy'
        'c2lvbiIpLAogICAgICAgICAgICAic3RyaW5nIHZlcnNpb24iOiAobGFtYmRhIGQ6IGRbImxvb3Bz'
        'Il1bMF1bImZlZWRfcHJvZmlsZXMiXVswXS5fX3NldGl0ZW1fXygidmVyc2lvbiIsICIxIiksIGYi'
        'e2VudHJ5fS52ZXJzaW9uIiwgInN1cHBvcnRlZCBpbnRlZ2VyIHZlcnNpb24iKSwKICAgICAgICAg'
        'ICAgInVua25vd24gc3RhdGUiOiAobGFtYmRhIGQ6IGRbImxvb3BzIl1bMF1bImZlZWRfcHJvZmls'
        'ZXMiXVswXS5fX3NldGl0ZW1fXygic3RhdGUiLCAiYWN0aXZlIiksIGYie2VudHJ5fS5zdGF0ZSIs'
        'ICJleHBlY3RlZCBsaXZlIG9yIGhpc3RvcmljYWwiKSwKICAgICAgICAgICAgInN0YXRlIG5vdCBh'
        'IHN0cmluZyI6IChsYW1iZGEgZDogZFsibG9vcHMiXVswXVsiZmVlZF9wcm9maWxlcyJdWzBdLl9f'
        'c2V0aXRlbV9fKCJzdGF0ZSIsIDEpLCBmIntlbnRyeX0uc3RhdGUiLCAiZXhwZWN0ZWQgbGl2ZSBv'
        'ciBoaXN0b3JpY2FsIiksCiAgICAgICAgICAgICJwcm9maWxlIG51bGwiOiAobGFtYmRhIGQ6IGRb'
        'Imxvb3BzIl1bMF1bImZlZWRfcHJvZmlsZXMiXVswXS5fX3NldGl0ZW1fXygicHJvZmlsZSIsIE5v'
        'bmUpLCBmIntlbnRyeX0ucHJvZmlsZSIsICJjbG9zZWQgZmVlZC1wcm9maWxlIHZvY2FidWxhcnki'
        'KSwKICAgICAgICAgICAgIm5vIGxpdmUgcHJvZmlsZSI6IChsYW1iZGEgZDogW2VudHJ5Ll9fc2V0'
        'aXRlbV9fKCJzdGF0ZSIsICJoaXN0b3JpY2FsIikgZm9yIGVudHJ5IGluIGRbImxvb3BzIl1bMF1b'
        'ImZlZWRfcHJvZmlsZXMiXV0sIGYie3Jvd30uZmVlZF9wcm9maWxlcyIsICJleHBlY3RlZCBhdCBs'
        'ZWFzdCBvbmUgbGl2ZSBmZWVkIHByb2ZpbGUiKSwKICAgICAgICAgICAgImVtcHR5IGJhc2lzIjog'
        'KGxhbWJkYSBkOiBkWyJsb29wcyJdWzBdWyJmZWVkX3Byb2ZpbGVzIl1bMF0uX19zZXRpdGVtX18o'
        'ImJhc2lzIiwgIiIpLCBmIntlbnRyeX0uYmFzaXMiLCAiZXhwZWN0ZWQgYSBub24tZW1wdHkgc3Ry'
        'aW5nIiksCiAgICAgICAgICAgICJhYnNvbHV0ZSBiYXNpcyI6IChsYW1iZGEgZDogZFsibG9vcHMi'
        'XVswXVsiZmVlZF9wcm9maWxlcyJdWzBdLl9fc2V0aXRlbV9fKCJiYXNpcyIsICIvZXRjL3Bhc3N3'
        'ZCIpLCBmIntlbnRyeX0uYmFzaXMiLCAibm9ybWFsaXplZCByZXBvc2l0b3J5LXJlbGF0aXZlIHBh'
        'dGgiKSwKICAgICAgICAgICAgInRyYXZlcnNpbmcgYmFzaXMiOiAobGFtYmRhIGQ6IGRbImxvb3Bz'
        'Il1bMF1bImZlZWRfcHJvZmlsZXMiXVswXS5fX3NldGl0ZW1fXygiYmFzaXMiLCAicHJvamVjdHMv'
        'Li4veC5tZCIpLCBmIntlbnRyeX0uYmFzaXMiLCAibm9ybWFsaXplZCByZXBvc2l0b3J5LXJlbGF0'
        'aXZlIHBhdGgiKSwKICAgICAgICAgICAgImJhY2tzbGFzaCBiYXNpcyI6IChsYW1iZGEgZDogZFsi'
        'bG9vcHMiXVswXVsiZmVlZF9wcm9maWxlcyJdWzBdLl9fc2V0aXRlbV9fKCJiYXNpcyIsICJwcm9q'
        'ZWN0c1xccGVjXFxBR0VOVFMubWQiKSwgZiJ7ZW50cnl9LmJhc2lzIiwgIm5vcm1hbGl6ZWQgcmVw'
        'b3NpdG9yeS1yZWxhdGl2ZSBwYXRoIiksCiAgICAgICAgfQogICAgICAgIGZvciBuYW1lLCAobXV0'
        'YXRlLCBsb2NhdGlvbiwgbWVzc2FnZSkgaW4gY2FzZXMuaXRlbXMoKToKICAgICAgICAgICAgd2l0'
        'aCBzZWxmLnN1YlRlc3QoY2FzZT1uYW1lKToKICAgICAgICAgICAgICAgIGRvY3VtZW50ID0gY29w'
        'eS5kZWVwY29weSh2YWxpZF9kb2N1bWVudCgpKQogICAgICAgICAgICAgICAgbXV0YXRlKGRvY3Vt'
        'ZW50KQogICAgICAgICAgICAgICAgd2l0aCBzZWxmLmFzc2VydFJhaXNlcyhMb29wUmVnaXN0cnlD'
        'b25maWdFcnJvcikgYXMgcmFpc2VkOgogICAgICAgICAgICAgICAgICAgIHNlbGYubG9hZChkb2N1'
        'bWVudCkKICAgICAgICAgICAgICAgIHRleHQgPSBzdHIocmFpc2VkLmV4Y2VwdGlvbikKICAgICAg'
        'ICAgICAgICAgIHNlbGYuYXNzZXJ0SW4oZiI6e2xvY2F0aW9ufTogIiwgdGV4dCkKICAgICAgICAg'
        'ICAgICAgIHNlbGYuYXNzZXJ0SW4obWVzc2FnZSwgdGV4dCkKCiAgICBkZWYgdGVzdF9zaGlwcGVk'
        'X3ZvY2FidWxhcnlfc3VyZmFjZXNfYXJlX3BhaXJ3aXNlX2Rpc2pvaW50KHNlbGYpIC0+IE5vbmU6'
        'CiAgICAgICAgcHJvZmlsZXMgPSBzb3J0ZWQoRkVFRF9QUk9GSUxFX1NVUkZBQ0VTKQogICAgICAg'
        'IGZvciBpbmRleCwgZmlyc3QgaW4gZW51bWVyYXRlKHByb2ZpbGVzKToKICAgICAgICAgICAgZm9y'
        'IHNlY29uZCBpbiBwcm9maWxlc1tpbmRleCArIDE6XToKICAgICAgICAgICAgICAgIHdpdGggc2Vs'
        'Zi5zdWJUZXN0KHBhaXI9KGZpcnN0LCBzZWNvbmQpKToKICAgICAgICAgICAgICAgICAgICBzZWxm'
        'LmFzc2VydEZhbHNlKEZFRURfUFJPRklMRV9TVVJGQUNFU1tmaXJzdF0gJiBGRUVEX1BST0ZJTEVf'
        'U1VSRkFDRVNbc2Vjb25kXSkKCiAgICBkZWYgdGVzdF9vdmVybGFwcGluZ19wcm9maWxlc19hcmVf'
        'cmVqZWN0ZWRfd2l0aF9sb2NhdGlvbihzZWxmKSAtPiBOb25lOgogICAgICAgICMgVGhlIHNoaXBw'
        'ZWQgcHJvZmlsZXMgYXJlIHBhaXJ3aXNlIGRpc2pvaW50LCBzbyBvdmVybGFwIG5lZWRzIGEgdm9j'
        'YWJ1bGFyeQogICAgICAgICMgdGhlIGFkYXB0ZXIgZG9lcyBub3Qgc2hpcC4gVHdvIHByb2JlIHBy'
        'b2ZpbGVzLCBlYWNoIGNvcHlpbmcgb25lIHN1cmZhY2Ugb2YKICAgICAgICAjIGEgc2hpcHBlZCBw'
        'cm9maWxlLCBleGVyY2lzZSB0aGUgcnVsZSB3aXRob3V0IGNoYW5naW5nIHRoZSBzaGlwcGVkIGZp'
        'bGVzLgogICAgICAgIHByb2Jlc192ZXJzaW9ucyA9IHsicHJvYmUtbGVkZ2VyIjogZnJvemVuc2V0'
        'KHsxfSksICJwcm9iZS1saWZlY3ljbGUiOiBmcm96ZW5zZXQoezF9KX0KICAgICAgICBwcm9iZXNf'
        'c3VyZmFjZXMgPSB7CiAgICAgICAgICAgICJwcm9iZS1sZWRnZXIiOiBmcm96ZW5zZXQoeyJyZWNl'
        'aXB0LWxlZGdlciJ9KSwKICAgICAgICAgICAgInByb2JlLWxpZmVjeWNsZSI6IGZyb3plbnNldCh7'
        'InN0YXR1cy1saWZlY3ljbGUifSksCiAgICAgICAgfQogICAgICAgIHJvdyA9ICIkLmxvb3BzWzBd'
        'IgoKICAgICAgICBkZWYgZW50cnkocHJvZmlsZTogc3RyLCBzdGF0ZTogc3RyKSAtPiBkaWN0Ogog'
        'ICAgICAgICAgICByZXR1cm4geyJwcm9maWxlIjogcHJvZmlsZSwgInZlcnNpb24iOiAxLCAic3Rh'
        'dGUiOiBzdGF0ZSwgImJhc2lzIjogUEVDX0FHRU5UU30KCiAgICAgICAgY2FzZXMgPSB7CiAgICAg'
        'ICAgICAgICJsaXZlIGFuZCBoaXN0b3JpY2FsIG9uIG9uZSBzdXJmYWNlIjogW2VudHJ5KCJwcm9i'
        'ZS1sZWRnZXIiLCAibGl2ZSIpLCBlbnRyeSgibG9vcC1yZWNlaXB0cy1sZWRnZXIiLCAiaGlzdG9y'
        'aWNhbCIpXSwKICAgICAgICAgICAgInR3byBsaXZlIHJlYWRlcnMgb2Ygb25lIHN1cmZhY2UiOiBb'
        'ZW50cnkoInNoYXJlZC1kZXYtbG9vcCIsICJsaXZlIiksIGVudHJ5KCJwcm9iZS1saWZlY3ljbGUi'
        'LCAibGl2ZSIpXSwKICAgICAgICAgICAgInR3byBoaXN0b3JpY2FsIGdyYW1tYXJzIGZvciBvbmUg'
        'c3VyZmFjZSI6IFtlbnRyeSgic2hhcmVkLWRldi1sb29wIiwgImxpdmUiKSwgZW50cnkoImxvb3At'
        'cmVjZWlwdHMtbGVkZ2VyIiwgImhpc3RvcmljYWwiKSwgZW50cnkoInByb2JlLWxlZGdlciIsICJo'
        'aXN0b3JpY2FsIildLAogICAgICAgIH0KICAgICAgICBleHBlY3RlZCA9IHsKICAgICAgICAgICAg'
        'ImxpdmUgYW5kIGhpc3RvcmljYWwgb24gb25lIHN1cmZhY2UiOiAoZiJ7cm93fS5mZWVkX3Byb2Zp'
        'bGVzWzFdLnByb2ZpbGUiLCAic3VyZmFjZSByZWNlaXB0LWxlZGdlciBpcyBhbHJlYWR5IGNvdmVy'
        'ZWQgYnkgJC5sb29wc1swXS5mZWVkX3Byb2ZpbGVzWzBdLnByb2ZpbGUiKSwKICAgICAgICAgICAg'
        'InR3byBsaXZlIHJlYWRlcnMgb2Ygb25lIHN1cmZhY2UiOiAoZiJ7cm93fS5mZWVkX3Byb2ZpbGVz'
        'WzFdLnByb2ZpbGUiLCAic3VyZmFjZSBzdGF0dXMtbGlmZWN5Y2xlIGlzIGFscmVhZHkgY292ZXJl'
        'ZCBieSAkLmxvb3BzWzBdLmZlZWRfcHJvZmlsZXNbMF0ucHJvZmlsZSIpLAogICAgICAgICAgICAi'
        'dHdvIGhpc3RvcmljYWwgZ3JhbW1hcnMgZm9yIG9uZSBzdXJmYWNlIjogKGYie3Jvd30uZmVlZF9w'
        'cm9maWxlc1syXS5wcm9maWxlIiwgInN1cmZhY2UgcmVjZWlwdC1sZWRnZXIgaXMgYWxyZWFkeSBj'
        'b3ZlcmVkIGJ5ICQubG9vcHNbMF0uZmVlZF9wcm9maWxlc1sxXS5wcm9maWxlIiksCiAgICAgICAg'
        'fQogICAgICAgIHdpdGggbW9jay5wYXRjaC5kaWN0KEZFRURfUFJPRklMRV9WRVJTSU9OUywgcHJv'
        'YmVzX3ZlcnNpb25zKSwgbW9jay5wYXRjaC5kaWN0KEZFRURfUFJPRklMRV9TVVJGQUNFUywgcHJv'
        'YmVzX3N1cmZhY2VzKToKICAgICAgICAgICAgZm9yIG5hbWUsIHByb2ZpbGVzIGluIGNhc2VzLml0'
        'ZW1zKCk6CiAgICAgICAgICAgICAgICB3aXRoIHNlbGYuc3ViVGVzdChjYXNlPW5hbWUpOgogICAg'
        'ICAgICAgICAgICAgICAgIGRvY3VtZW50ID0gY29weS5kZWVwY29weSh2YWxpZF9kb2N1bWVudCgp'
        'KQogICAgICAgICAgICAgICAgICAgIGRvY3VtZW50WyJsb29wcyJdWzBdWyJmZWVkX3Byb2ZpbGVz'
        'Il0gPSBwcm9maWxlcwogICAgICAgICAgICAgICAgICAgIHdpdGggc2VsZi5hc3NlcnRSYWlzZXMo'
        'TG9vcFJlZ2lzdHJ5Q29uZmlnRXJyb3IpIGFzIHJhaXNlZDoKICAgICAgICAgICAgICAgICAgICAg'
        'ICAgc2VsZi5sb2FkKGRvY3VtZW50KQogICAgICAgICAgICAgICAgICAgIGxvY2F0aW9uLCBtZXNz'
        'YWdlID0gZXhwZWN0ZWRbbmFtZV0KICAgICAgICAgICAgICAgICAgICBzZWxmLmFzc2VydEluKGYi'
        'Ontsb2NhdGlvbn06ICIsIHN0cihyYWlzZWQuZXhjZXB0aW9uKSkKICAgICAgICAgICAgICAgICAg'
        'ICBzZWxmLmFzc2VydEluKG1lc3NhZ2UsIHN0cihyYWlzZWQuZXhjZXB0aW9uKSkKICAgICAgICAg'
        'ICAgZGlzam9pbnQgPSBjb3B5LmRlZXBjb3B5KHZhbGlkX2RvY3VtZW50KCkpCiAgICAgICAgICAg'
        'IGRpc2pvaW50WyJsb29wcyJdWzBdWyJmZWVkX3Byb2ZpbGVzIl0gPSBbZW50cnkoInByb2JlLWxl'
        'ZGdlciIsICJsaXZlIiksIGVudHJ5KCJzaGFyZWQtZGV2LWxvb3AiLCAiaGlzdG9yaWNhbCIpXQog'
        'ICAgICAgICAgICBzZWxmLmFzc2VydEVxdWFsKGxlbihzZWxmLmxvYWQoZGlzam9pbnQpWzBdLmZl'
        'ZWRfcHJvZmlsZXMpLCAyKQogICAgICAgIHNlbGYuYXNzZXJ0Tm90SW4oInByb2JlLWxlZGdlciIs'
        'IEZFRURfUFJPRklMRV9WRVJTSU9OUykKCiAgICBkZWYgdGVzdF9mYWlsdXJlc19kb19ub3RfZWNo'
        'b19kb2N1bWVudF92YWx1ZXMoc2VsZikgLT4gTm9uZToKICAgICAgICBzZW50aW5lbCA9ICJ6enNl'
        'bnRpbmVsenoiCiAgICAgICAgY2FzZXMgPSB7CiAgICAgICAgICAgICJsb29wX2lkIjogbGFtYmRh'
        'IGQ6IGRbImxvb3BzIl1bMF0uX19zZXRpdGVtX18oImxvb3BfaWQiLCBzZW50aW5lbC51cHBlcigp'
        'KSwKICAgICAgICAgICAgImxvb3BfaW5pdF9wYXRoIjogbGFtYmRhIGQ6IGRbImxvb3BzIl1bMF0u'
        'X19zZXRpdGVtX18oImxvb3BfaW5pdF9wYXRoIiwgZiIve3NlbnRpbmVsfSIpLAogICAgICAgICAg'
        'ICAicHJvZmlsZSI6IGxhbWJkYSBkOiBkWyJsb29wcyJdWzBdWyJmZWVkX3Byb2ZpbGVzIl1bMF0u'
        'X19zZXRpdGVtX18oInByb2ZpbGUiLCBzZW50aW5lbCksCiAgICAgICAgICAgICJ2ZXJzaW9uIjog'
        'bGFtYmRhIGQ6IGRbImxvb3BzIl1bMF1bImZlZWRfcHJvZmlsZXMiXVswXS5fX3NldGl0ZW1fXygi'
        'dmVyc2lvbiIsIHNlbnRpbmVsKSwKICAgICAgICAgICAgInN0YXRlIjogbGFtYmRhIGQ6IGRbImxv'
        'b3BzIl1bMF1bImZlZWRfcHJvZmlsZXMiXVswXS5fX3NldGl0ZW1fXygic3RhdGUiLCBzZW50aW5l'
        'bCksCiAgICAgICAgICAgICJiYXNpcyI6IGxhbWJkYSBkOiBkWyJsb29wcyJdWzBdWyJmZWVkX3By'
        'b2ZpbGVzIl1bMF0uX19zZXRpdGVtX18oImJhc2lzIiwgZiIuLi97c2VudGluZWx9IiksCiAgICAg'
        'ICAgfQogICAgICAgIGZvciBuYW1lLCBtdXRhdGUgaW4gY2FzZXMuaXRlbXMoKToKICAgICAgICAg'
        'ICAgd2l0aCBzZWxmLnN1YlRlc3QoZmllbGQ9bmFtZSk6CiAgICAgICAgICAgICAgICBkb2N1bWVu'
        'dCA9IGNvcHkuZGVlcGNvcHkodmFsaWRfZG9jdW1lbnQoKSkKICAgICAgICAgICAgICAgIG11dGF0'
        'ZShkb2N1bWVudCkKICAgICAgICAgICAgICAgIHdpdGggc2VsZi5hc3NlcnRSYWlzZXMoTG9vcFJl'
        'Z2lzdHJ5Q29uZmlnRXJyb3IpIGFzIHJhaXNlZDoKICAgICAgICAgICAgICAgICAgICBzZWxmLmxv'
        'YWQoZG9jdW1lbnQpCiAgICAgICAgICAgICAgICBzZWxmLmFzc2VydE5vdEluKHNlbnRpbmVsLCBz'
        'dHIocmFpc2VkLmV4Y2VwdGlvbikubG93ZXIoKSkKCiAgICBkZWYgdGVzdF9hZGRpdGlvbmFsX2xv'
        'b3BzX25lZWRfZW50cmllc19vbmx5KHNlbGYpIC0+IE5vbmU6CiAgICAgICAgZG9jdW1lbnQgPSB2'
        'YWxpZF9kb2N1bWVudCgpCiAgICAgICAgZG9jdW1lbnRbImxvb3BzIl0uYXBwZW5kKAogICAgICAg'
        'ICAgICB7CiAgICAgICAgICAgICAgICAibG9vcF9pZCI6ICJzZWNvbmQtbG9vcCIsCiAgICAgICAg'
        'ICAgICAgICAibG9vcF9pbml0X3BhdGgiOiAicHJvamVjdHMvc2Vjb25kL2xvb3AvTE9PUF9JTklU'
        'Lm1kIiwKICAgICAgICAgICAgICAgICJmZWVkX3Byb2ZpbGVzIjogWwogICAgICAgICAgICAgICAg'
        'ICAgIHsicHJvZmlsZSI6IHByb2ZpbGUsICJ2ZXJzaW9uIjogMSwgInN0YXRlIjogc3RhdGUsICJi'
        'YXNpcyI6ICJwcm9qZWN0cy9zZWNvbmQvQUdFTlRTLm1kIn0KICAgICAgICAgICAgICAgICAgICBm'
        'b3IgcHJvZmlsZSwgc3RhdGUgaW4gKAogICAgICAgICAgICAgICAgICAgICAgICAoInNoYXJlZC1k'
        'ZXYtbG9vcCIsICJsaXZlIiksCiAgICAgICAgICAgICAgICAgICAgICAgICgibG9vcC1yZWNlaXB0'
        'cy1sZWRnZXIiLCAiaGlzdG9yaWNhbCIpLAogICAgICAgICAgICAgICAgICAgICAgICAoImFnZW50'
        'cnVucy1qc29uIiwgImhpc3RvcmljYWwiKSwKICAgICAgICAgICAgICAgICAgICApCiAgICAgICAg'
        'ICAgICAgICBdLAogICAgICAgICAgICB9CiAgICAgICAgKQogICAgICAgIGxvb3BzID0gc2VsZi5s'
        'b2FkKGRvY3VtZW50KQogICAgICAgIHNlbGYuYXNzZXJ0RXF1YWwoW2xvb3AubG9vcF9pZCBmb3Ig'
        'bG9vcCBpbiBsb29wc10sIFsicGVjIiwgInNlY29uZC1sb29wIl0pCiAgICAgICAgc2VsZi5hc3Nl'
        'cnRFcXVhbCgKICAgICAgICAgICAgW3Byb2ZpbGUucHJvZmlsZSBmb3IgcHJvZmlsZSBpbiBsb29w'
        'c1sxXS5mZWVkX3Byb2ZpbGVzXSwKICAgICAgICAgICAgWyJzaGFyZWQtZGV2LWxvb3AiLCAibG9v'
        'cC1yZWNlaXB0cy1sZWRnZXIiLCAiYWdlbnRydW5zLWpzb24iXSwKICAgICAgICApCiAgICAgICAg'
        'c2VsZi5hc3NlcnRFcXVhbChsb29wc1sxXS5mZWVkX3Byb2ZpbGVzWzJdLnN0YXRlLCBGZWVkUHJv'
        'ZmlsZVN0YXRlLkhJU1RPUklDQUwpCgogICAgZGVmIHRlc3RfaW52YWxpZF9kb2N1bWVudF9uZXZl'
        'cl9yZXR1cm5zX3BhcnRpYWxfb3JfZW1wdHlfc2V0KHNlbGYpIC0+IE5vbmU6CiAgICAgICAgZm9y'
        'IGZpeHR1cmUgaW4gKAogICAgICAgICAgICAic2NoZW1hX3ZlcnNpb25fMS5qc29uIiwKICAgICAg'
        'ICAgICAgIm1pc3NpbmdfbG9vcF9pZC5qc29uIiwKICAgICAgICAgICAgImR1cGxpY2F0ZV9sb29w'
        'X2lkLmpzb24iLAogICAgICAgICAgICAibWFsZm9ybWVkLmpzb24iLAogICAgICAgICk6CiAgICAg'
        'ICAgICAgIHdpdGggc2VsZi5zdWJUZXN0KGZpeHR1cmU9Zml4dHVyZSk6CiAgICAgICAgICAgICAg'
        'ICB3aXRoIHNlbGYuYXNzZXJ0UmFpc2VzKExvb3BSZWdpc3RyeUNvbmZpZ0Vycm9yKToKICAgICAg'
        'ICAgICAgICAgICAgICBKc29uTG9vcFJlZ2lzdHJ5KEZJWFRVUkVTIC8gZml4dHVyZSkucmVnaXN0'
        'ZXJlZF9sb29wcygpCiAgICAgICAgZG9jdW1lbnQgPSB2YWxpZF9kb2N1bWVudCgpCiAgICAgICAg'
        'ZG9jdW1lbnRbImxvb3BzIl0uYXBwZW5kKGNvcHkuZGVlcGNvcHkoZG9jdW1lbnRbImxvb3BzIl1b'
        'MF0pKQogICAgICAgIGRvY3VtZW50WyJsb29wcyJdWzFdWyJsb29wX2lkIl0gPSAic2Vjb25kLWxv'
        'b3AiCiAgICAgICAgZG9jdW1lbnRbImxvb3BzIl1bMV1bImZlZWRfcHJvZmlsZXMiXVswXVsic3Rh'
        'dGUiXSA9ICJzdGFsZSIKICAgICAgICB3aXRoIHNlbGYuYXNzZXJ0UmFpc2VzUmVnZXgoTG9vcFJl'
        'Z2lzdHJ5Q29uZmlnRXJyb3IsIHIiXCRcLmxvb3BzXFsxXF1cLmZlZWRfcHJvZmlsZXNcWzBcXVwu'
        'c3RhdGUiKToKICAgICAgICAgICAgc2VsZi5sb2FkKGRvY3VtZW50KQoKCmlmIF9fbmFtZV9fID09'
        'ICJfX21haW5fXyI6CiAgICB1bml0dGVzdC5tYWluKCkK'
    ),
    'a509bfb74920172a86ac21aff6a67245cd3248c5d73ef4e7427966069099c8a9': (
        'IiIiVHlwZWQgY29yZSBjb250cmFjdCBmb3IgZGlzY292ZXJpbmcgdGhlIGxvb3BzIFBFQyBpcyBj'
        'b25maWd1cmVkIHRvIHNlcnZlLiIiIgoKZnJvbSBfX2Z1dHVyZV9fIGltcG9ydCBhbm5vdGF0aW9u'
        'cwoKZnJvbSBkYXRhY2xhc3NlcyBpbXBvcnQgZGF0YWNsYXNzCmZyb20gZW51bSBpbXBvcnQgRW51'
        'bQpmcm9tIHR5cGluZyBpbXBvcnQgUHJvdG9jb2wKCgpjbGFzcyBGZWVkUHJvZmlsZVN0YXRlKEVu'
        'dW0pOgogICAgIiIiV2hldGhlciBhIGRlY2xhcmVkIGZlZWQtcHJvZmlsZSBnZW5lcmF0aW9uIGlz'
        'IGxpdmUgb3IgaGlzdG9yaWNhbCBmb3IgaXRzIGxvb3AuIiIiCgogICAgTElWRSA9ICJsaXZlIgog'
        'ICAgSElTVE9SSUNBTCA9ICJoaXN0b3JpY2FsIgoKCkBkYXRhY2xhc3MoZnJvemVuPVRydWUsIHNs'
        'b3RzPVRydWUpCmNsYXNzIEZlZWRQcm9maWxlOgogICAgIiIiT25lIGNsb3NlZCwgUEVDLXZlcnNp'
        'b25lZCBmZWVkIHByb2ZpbGUgZGVjbGFyZWQgZm9yIGEgcmVnaXN0ZXJlZCBsb29wLgoKICAgIEEg'
        'cHJvZmlsZSBpcyBQRUMncyByZWFkaW5nIGh5cG90aGVzaXMgYWJvdXQgdGhlIGxvb3AncyBmaWxl'
        'IHRydXRoLCBuZXZlciB0aGUKICAgIGxvb3AncyB0cnV0aC4gYGBiYXNpc2BgIGlzIHRoZSByZXBv'
        'c2l0b3J5LXJlbGF0aXZlIGxvY2F0b3Igb2YgdGhlIGxvb3AncyBvd24KICAgIHJlY29yZCB0aGF0'
        'IHN1cHBvcnRzIHRoZSBkZWNsYXJhdGlvbi4KICAgICIiIgoKICAgIHByb2ZpbGU6IHN0cgogICAg'
        'dmVyc2lvbjogaW50CiAgICBzdGF0ZTogRmVlZFByb2ZpbGVTdGF0ZQogICAgYmFzaXM6IHN0cgoK'
        'CkBkYXRhY2xhc3MoZnJvemVuPVRydWUsIHNsb3RzPVRydWUpCmNsYXNzIFJlZ2lzdGVyZWRMb29w'
        'OgogICAgIiIiT25lIGNvbmZpZ3VyZWQgbG9vcCwgdGhlIGxvY2F0b3Igb2YgaXRzIGZpbGUgdHJ1'
        'dGgsIGFuZCBpdHMgZmVlZCBwcm9maWxlcy4iIiIKCiAgICBsb29wX2lkOiBzdHIKICAgIGxvb3Bf'
        'aW5pdF9wYXRoOiBzdHIKICAgIGZlZWRfcHJvZmlsZXM6IHR1cGxlW0ZlZWRQcm9maWxlLCAuLi5d'
        'CgoKY2xhc3MgTG9vcFJlZ2lzdHJ5KFByb3RvY29sKToKICAgICIiIkNvcmUtb3duZWQgY2FwYWJp'
        'bGl0eSBwb3J0IGZvciB0aGUgY29uZmlndXJlZCByZWdpc3RlcmVkLWxvb3Agc2V0LiIiIgoKICAg'
        'IGRlZiByZWdpc3RlcmVkX2xvb3BzKHNlbGYpIC0+IHR1cGxlW1JlZ2lzdGVyZWRMb29wLCAuLi5d'
        'OgogICAgICAgICIiIlJldHVybiB0aGUgY29tcGxldGUgdmFsaWRhdGVkIHJlZ2lzdGVyZWQtbG9v'
        'cCBzZXQuIiIiCiAgICAgICAgLi4uCg=='
    ),
    'b05ed8719c59258998b1c483456b66bd8d4a4d3bc4f68cdd6fb5c02541db7106': (
        'ZnJvbSBfX2Z1dHVyZV9fIGltcG9ydCBhbm5vdGF0aW9ucwoKaW1wb3J0IGFzdAppbXBvcnQgZGF0'
        'YWNsYXNzZXMKaW1wb3J0IGluc3BlY3QKaW1wb3J0IHN5cwppbXBvcnQgc3lzY29uZmlnCmltcG9y'
        'dCB1bml0dGVzdApmcm9tIHBhdGhsaWIgaW1wb3J0IFBhdGgKCgpWMl9ST09UID0gUGF0aChfX2Zp'
        'bGVfXykucmVzb2x2ZSgpLnBhcmVudHNbMl0KU1JDX1JPT1QgPSBWMl9ST09UIC8gInNyYyIKc3lz'
        'LnBhdGguaW5zZXJ0KDAsIHN0cihTUkNfUk9PVCkpCgpmcm9tIHBlY192Mi5jb3JlLnBvcnRzLmxv'
        'b3BfcmVnaXN0cnkgaW1wb3J0ICggICMgbm9xYTogRTQwMgogICAgRmVlZFByb2ZpbGUsCiAgICBG'
        'ZWVkUHJvZmlsZVN0YXRlLAogICAgTG9vcFJlZ2lzdHJ5LAogICAgUmVnaXN0ZXJlZExvb3AsCikK'
        'CgpjbGFzcyBMb29wUmVnaXN0cnlDb250cmFjdFRlc3RzKHVuaXR0ZXN0LlRlc3RDYXNlKToKICAg'
        'IGRlZiB0ZXN0X3JlZ2lzdGVyZWRfbG9vcF9pc19pbW11dGFibGUoc2VsZikgLT4gTm9uZToKICAg'
        'ICAgICBwcm9maWxlID0gRmVlZFByb2ZpbGUoCiAgICAgICAgICAgICJzaGFyZWQtZGV2LWxvb3Ai'
        'LCAxLCBGZWVkUHJvZmlsZVN0YXRlLkxJVkUsICJwcm9qZWN0cy9wZWMvQUdFTlRTLm1kIgogICAg'
        'ICAgICkKICAgICAgICBsb29wID0gUmVnaXN0ZXJlZExvb3AoInBlYyIsICJwcm9qZWN0cy9wZWMv'
        'bG9vcC9MT09QX0lOSVQubWQiLCAocHJvZmlsZSwpKQogICAgICAgIHdpdGggc2VsZi5hc3NlcnRS'
        'YWlzZXMoZGF0YWNsYXNzZXMuRnJvemVuSW5zdGFuY2VFcnJvcik6CiAgICAgICAgICAgIGxvb3Au'
        'bG9vcF9pZCA9ICJyb290IiAgIyB0eXBlOiBpZ25vcmVbbWlzY10KICAgICAgICB3aXRoIHNlbGYu'
        'YXNzZXJ0UmFpc2VzKGRhdGFjbGFzc2VzLkZyb3plbkluc3RhbmNlRXJyb3IpOgogICAgICAgICAg'
        'ICBsb29wLmZlZWRfcHJvZmlsZXMgPSAoKSAgIyB0eXBlOiBpZ25vcmVbbWlzY10KICAgICAgICB3'
        'aXRoIHNlbGYuYXNzZXJ0UmFpc2VzKGRhdGFjbGFzc2VzLkZyb3plbkluc3RhbmNlRXJyb3IpOgog'
        'ICAgICAgICAgICBwcm9maWxlLnN0YXRlID0gRmVlZFByb2ZpbGVTdGF0ZS5ISVNUT1JJQ0FMICAj'
        'IHR5cGU6IGlnbm9yZVttaXNjXQoKICAgIGRlZiB0ZXN0X3JlZ2lzdGVyZWRfbG9vcF9jYXJyaWVz'
        'X3RoZV90eXBlZF9mZWVkX3Byb2ZpbGVfZmllbGQoc2VsZikgLT4gTm9uZToKICAgICAgICBzZWxm'
        'LmFzc2VydEVxdWFsKAogICAgICAgICAgICBbZmllbGQubmFtZSBmb3IgZmllbGQgaW4gZGF0YWNs'
        'YXNzZXMuZmllbGRzKFJlZ2lzdGVyZWRMb29wKV0sCiAgICAgICAgICAgIFsibG9vcF9pZCIsICJs'
        'b29wX2luaXRfcGF0aCIsICJmZWVkX3Byb2ZpbGVzIl0sCiAgICAgICAgKQogICAgICAgIHNlbGYu'
        'YXNzZXJ0RXF1YWwoCiAgICAgICAgICAgIFtmaWVsZC5uYW1lIGZvciBmaWVsZCBpbiBkYXRhY2xh'
        'c3Nlcy5maWVsZHMoRmVlZFByb2ZpbGUpXSwKICAgICAgICAgICAgWyJwcm9maWxlIiwgInZlcnNp'
        'b24iLCAic3RhdGUiLCAiYmFzaXMiXSwKICAgICAgICApCiAgICAgICAgc2VsZi5hc3NlcnRFcXVh'
        'bCgKICAgICAgICAgICAge21lbWJlci52YWx1ZSBmb3IgbWVtYmVyIGluIEZlZWRQcm9maWxlU3Rh'
        'dGV9LCB7ImxpdmUiLCAiaGlzdG9yaWNhbCJ9CiAgICAgICAgKQoKICAgIGRlZiB0ZXN0X3BvcnRf'
        'aGFzX29ubHlfdGhlX3R5cGVkX2NhcGFiaWxpdHlfbWV0aG9kKHNlbGYpIC0+IE5vbmU6CiAgICAg'
        'ICAgcHVibGljID0gW25hbWUgZm9yIG5hbWUgaW4gdmFycyhMb29wUmVnaXN0cnkpIGlmIG5vdCBu'
        'YW1lLnN0YXJ0c3dpdGgoIl8iKV0KICAgICAgICBzZWxmLmFzc2VydEVxdWFsKHB1YmxpYywgWyJy'
        'ZWdpc3RlcmVkX2xvb3BzIl0pCiAgICAgICAgc2lnbmF0dXJlID0gc3RyKGluc3BlY3Quc2lnbmF0'
        'dXJlKExvb3BSZWdpc3RyeS5yZWdpc3RlcmVkX2xvb3BzKSkKICAgICAgICBzZWxmLmFzc2VydElu'
        'KCJ0dXBsZVtSZWdpc3RlcmVkTG9vcCwgLi4uXSIsIHNpZ25hdHVyZSkKICAgICAgICBmb3IgZm9y'
        'YmlkZGVuIGluICgiUGF0aCIsICJqc29uIiwgImNvbmZpZyIsICJzZXJpYWxpemF0aW9uIiwgIkVy'
        'cm9yIik6CiAgICAgICAgICAgIHNlbGYuYXNzZXJ0Tm90SW4oZm9yYmlkZGVuLCBzaWduYXR1cmUp'
        'CgogICAgZGVmIHRlc3RfY29yZV9pbXBvcnRzX25vX2FkYXB0ZXJfb3Jfb3V0ZXJfaW9fbW9kdWxl'
        'KHNlbGYpIC0+IE5vbmU6CiAgICAgICAgY29yZV9yb290ID0gU1JDX1JPT1QgLyAicGVjX3YyIiAv'
        'ICJjb3JlIgogICAgICAgIGZvcmJpZGRlbiA9IHsicGVjX3YyLmFkYXB0ZXJzIiwgImpzb24iLCAi'
        'cGF0aGxpYiIsICJzb2NrZXQiLCAic3FsaXRlMyIsICJ1cmxsaWIifQogICAgICAgIGZvciBwYXRo'
        'IGluIGNvcmVfcm9vdC5yZ2xvYigiKi5weSIpOgogICAgICAgICAgICB0cmVlID0gYXN0LnBhcnNl'
        'KHBhdGgucmVhZF90ZXh0KGVuY29kaW5nPSJ1dGYtOCIpLCBmaWxlbmFtZT1zdHIocGF0aCkpCiAg'
        'ICAgICAgICAgIGltcG9ydHM6IHNldFtzdHJdID0gc2V0KCkKICAgICAgICAgICAgZm9yIG5vZGUg'
        'aW4gYXN0LndhbGsodHJlZSk6CiAgICAgICAgICAgICAgICBpZiBpc2luc3RhbmNlKG5vZGUsIGFz'
        'dC5JbXBvcnQpOgogICAgICAgICAgICAgICAgICAgIGltcG9ydHMudXBkYXRlKGFsaWFzLm5hbWUg'
        'Zm9yIGFsaWFzIGluIG5vZGUubmFtZXMpCiAgICAgICAgICAgICAgICBlbGlmIGlzaW5zdGFuY2Uo'
        'bm9kZSwgYXN0LkltcG9ydEZyb20pIGFuZCBub2RlLm1vZHVsZToKICAgICAgICAgICAgICAgICAg'
        'ICBpbXBvcnRzLmFkZChub2RlLm1vZHVsZSkKICAgICAgICAgICAgc2VsZi5hc3NlcnRGYWxzZSgK'
        'ICAgICAgICAgICAgICAgIGFueShuYW1lID09IGl0ZW0gb3IgbmFtZS5zdGFydHN3aXRoKGYie2l0'
        'ZW19LiIpIGZvciBuYW1lIGluIGltcG9ydHMgZm9yIGl0ZW0gaW4gZm9yYmlkZGVuKSwKICAgICAg'
        'ICAgICAgICAgIGYiZm9yYmlkZGVuIGNvcmUgaW1wb3J0IGluIHtwYXRofToge3NvcnRlZChpbXBv'
        'cnRzKX0iLAogICAgICAgICAgICApCgogICAgZGVmIHRlc3RfaW1wbGVtZW50YXRpb25fdXNlc19v'
        'bmx5X3N0ZGxpYl9hbmRfbm9fbmV0d29ya19tb2R1bGUoc2VsZikgLT4gTm9uZToKICAgICAgICBz'
        'b3VyY2Vfcm9vdCA9IFNSQ19ST09UIC8gInBlY192MiIKICAgICAgICBzdGRsaWIgPSBzZXQoc3lz'
        'LnN0ZGxpYl9tb2R1bGVfbmFtZXMpCiAgICAgICAgbmV0d29ya19tb2R1bGVzID0geyJhc3luY2lv'
        'IiwgImh0dHAiLCAic29ja2V0IiwgInVybGxpYiJ9CiAgICAgICAgdGhpcmRfcGFydHlfcm9vdCA9'
        'IFBhdGgoc3lzY29uZmlnLmdldF9wYXRocygpWyJwdXJlbGliIl0pCiAgICAgICAgZm9yIHBhdGgg'
        'aW4gc291cmNlX3Jvb3Qucmdsb2IoIioucHkiKToKICAgICAgICAgICAgdHJlZSA9IGFzdC5wYXJz'
        'ZShwYXRoLnJlYWRfdGV4dChlbmNvZGluZz0idXRmLTgiKSwgZmlsZW5hbWU9c3RyKHBhdGgpKQog'
        'ICAgICAgICAgICBmb3Igbm9kZSBpbiBhc3Qud2Fsayh0cmVlKToKICAgICAgICAgICAgICAgIGlm'
        'IGlzaW5zdGFuY2Uobm9kZSwgYXN0LkltcG9ydCk6CiAgICAgICAgICAgICAgICAgICAgbmFtZXMg'
        'PSBbYWxpYXMubmFtZSBmb3IgYWxpYXMgaW4gbm9kZS5uYW1lc10KICAgICAgICAgICAgICAgIGVs'
        'aWYgaXNpbnN0YW5jZShub2RlLCBhc3QuSW1wb3J0RnJvbSkgYW5kIG5vZGUubGV2ZWwgPT0gMCBh'
        'bmQgbm9kZS5tb2R1bGU6CiAgICAgICAgICAgICAgICAgICAgbmFtZXMgPSBbbm9kZS5tb2R1bGVd'
        'CiAgICAgICAgICAgICAgICBlbHNlOgogICAgICAgICAgICAgICAgICAgIGNvbnRpbnVlCiAgICAg'
        'ICAgICAgICAgICBmb3IgbmFtZSBpbiBuYW1lczoKICAgICAgICAgICAgICAgICAgICByb290ID0g'
        'bmFtZS5zcGxpdCgiLiIsIDEpWzBdCiAgICAgICAgICAgICAgICAgICAgc2VsZi5hc3NlcnROb3RJ'
        'bihyb290LCBuZXR3b3JrX21vZHVsZXMsIGYibmV0d29yayBpbXBvcnQgaW4ge3BhdGh9OiB7bmFt'
        'ZX0iKQogICAgICAgICAgICAgICAgICAgIHNlbGYuYXNzZXJ0VHJ1ZSgKICAgICAgICAgICAgICAg'
        'ICAgICAgICAgcm9vdCBpbiBzdGRsaWIgb3Igcm9vdCA9PSAicGVjX3YyIiwKICAgICAgICAgICAg'
        'ICAgICAgICAgICAgZiJub24tc3RkbGliIGltcG9ydCBpbiB7cGF0aH06IHtuYW1lfSAoc2l0ZSBy'
        'b290IHt0aGlyZF9wYXJ0eV9yb290fSkiLAogICAgICAgICAgICAgICAgICAgICkKCgppZiBfX25h'
        'bWVfXyA9PSAiX19tYWluX18iOgogICAgdW5pdHRlc3QubWFpbigpCg=='
    ),
    'e44bf7f00c8ef2cfa5f8006ef2834feb020063df63a3b4b8d8cbd8f359174ff7': (
        'IiIiQ29yZS1vd25lZCBwb3J0cyBmb3IgcmVwbGFjZWFibGUgUEVDIGFkYXB0ZXJzLiIiIgoKZnJv'
        'bSAubG9vcF9yZWdpc3RyeSBpbXBvcnQgRmVlZFByb2ZpbGUsIEZlZWRQcm9maWxlU3RhdGUsIExv'
        'b3BSZWdpc3RyeSwgUmVnaXN0ZXJlZExvb3AKCl9fYWxsX18gPSBbIkZlZWRQcm9maWxlIiwgIkZl'
        'ZWRQcm9maWxlU3RhdGUiLCAiTG9vcFJlZ2lzdHJ5IiwgIlJlZ2lzdGVyZWRMb29wIl0K'
    ),
    'f4255b2483a014b542fb7f25c4314ff75dabb5cebbcfe751a2ad3df425f29598': (
        'ewogICJsb29wcyI6IFsKICAgIHsKICAgICAgImZlZWRfcHJvZmlsZXMiOiBbCiAgICAgICAgewog'
        'ICAgICAgICAgImJhc2lzIjogInByb2plY3RzL3BlYy9leGVjdXRpb24vX0Nvb3JkaW5hdGlvbi9f'
        'REVDSVNJT05TL0QtUEVDLTk0X293bmVyX2RpcmVjdGlvbl9sb29wX21pZ3JhdGlvbl8yMDI2LTA5'
        'LTI1Lm1kIiwKICAgICAgICAgICJwcm9maWxlIjogInNoYXJlZC1kZXYtbG9vcCIsCiAgICAgICAg'
        'ICAic3RhdGUiOiAibGl2ZSIsCiAgICAgICAgICAidmVyc2lvbiI6IDEKICAgICAgICB9CiAgICAg'
        'IF0sCiAgICAgICJsb29wX2luaXRfcGF0aCI6ICJwcm9qZWN0cy9wZWMvbG9vcC9MT09QX0lOSVQu'
        'bWQiCiAgICB9CiAgXSwKICAic2NoZW1hX3ZlcnNpb24iOiAyCn0K'
    ),
    'fd342b4f29edf3bece24a8d785b4a03d1a60158e62227753e4e1fa03529f53d7': (
        'ewogICJsb29wcyI6IFsKICAgIHsKICAgICAgImZlZWRfcHJvZmlsZXMiOiBbCiAgICAgICAgewog'
        'ICAgICAgICAgImJhc2lzIjogInByb2plY3RzL3BlYy9leGVjdXRpb24vX0Nvb3JkaW5hdGlvbi9f'
        'REVDSVNJT05TL0QtUEVDLTk0X293bmVyX2RpcmVjdGlvbl9sb29wX21pZ3JhdGlvbl8yMDI2LTA5'
        'LTI1Lm1kIiwKICAgICAgICAgICJwcm9maWxlIjogInNoYXJlZC1kZXYtbG9vcCIsCiAgICAgICAg'
        'ICAic3RhdGUiOiAibGl2ZSIsCiAgICAgICAgICAidmVyc2lvbiI6IDEKICAgICAgICB9LAogICAg'
        'ICAgIHsKICAgICAgICAgICJiYXNpcyI6ICJwcm9qZWN0cy9wZWMvQUdFTlRTLm1kIiwKICAgICAg'
        'ICAgICJwcm9maWxlIjogImxvb3AtcmVjZWlwdHMtbGVkZ2VyIiwKICAgICAgICAgICJzdGF0ZSI6'
        'ICJoaXN0b3JpY2FsIiwKICAgICAgICAgICJ2ZXJzaW9uIjogMQogICAgICAgIH0sCiAgICAgICAg'
        'ewogICAgICAgICAgImJhc2lzIjogInByb2plY3RzL3BlYy9leGVjdXRpb24vX0Nvb3JkaW5hdGlv'
        'bi9fREVDSVNJT05TL0QtUEVDLTk0X293bmVyX2RpcmVjdGlvbl9sb29wX21pZ3JhdGlvbl8yMDI2'
        'LTA5LTI1Lm1kIiwKICAgICAgICAgICJwcm9maWxlIjogImFnZW50cnVucy1qc29uIiwKICAgICAg'
        'ICAgICJzdGF0ZSI6ICJoaXN0b3JpY2FsIiwKICAgICAgICAgICJ2ZXJzaW9uIjogMQogICAgICAg'
        'IH0KICAgICAgXSwKICAgICAgImxvb3BfaWQiOiAicGVjIiwKICAgICAgImxvb3BfaW5pdF9wYXRo'
        'IjogInByb2plY3RzL3BlYy9sb29wL0xPT1BfSU5JVC5tZCIKICAgIH0KICBdLAogICJzY2hlbWFf'
        'dmVyc2lvbiI6IDIKfQo='
    ),
}


def sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def fail(message: str) -> int:
    print(f"FAIL {message}; nothing written")
    return 1


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo", required=True)
    parser.add_argument("--check-only", action="store_true")
    args = parser.parse_args()

    root = Path(args.repo).resolve() / PEC
    if not root.is_dir():
        return fail(f"{root} is not a directory")
    postimages = POSTIMAGES_A
    if set(postimages) != set(PREIMAGES):
        return fail("postimage set differs from the grant")

    for rel, expected in sorted(UNCHANGED.items()):
        path = root / rel
        if not path.is_file() or sha(path.read_bytes()) != expected:
            return fail(f"must-remain file differs: {rel}")
        print(f"UNCHANGED {rel} {expected}")

    for rel, expected in sorted(PREIMAGES.items()):
        path = root / rel
        if expected is None:
            if path.exists():
                return fail(f"path to create already exists: {rel}")
            print(f"READ {rel} absent")
            continue
        if not path.is_file():
            return fail(f"preimage missing: {rel}")
        actual = sha(path.read_bytes())
        if actual != expected:
            return fail(f"preimage mismatch {rel}: {actual} != {expected}")
        print(f"READ {rel} {actual}")

    rendered: dict[str, bytes] = {}
    for rel, digest in sorted(postimages.items()):
        data = base64.b64decode("".join(BLOBS[digest]))
        if sha(data) != digest:
            return fail(f"embedded postimage corrupt: {rel}")
        rendered[rel] = data

    for rel, data in sorted(rendered.items()):
        if args.check_only:
            print(f"RENDER {rel} {sha(data)}")
            continue
        path = root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)

    if not args.check_only:
        for rel, digest in sorted(postimages.items()):
            actual = sha((root / rel).read_bytes())
            if actual != digest:
                print(f"FAIL postimage mismatch after write {rel}: {actual}")
                return 1
            print(f"WRITE {rel} {actual}")
    print(f"OK option=A files={len(rendered)} "
          f"mode={'check-only' if args.check_only else 'written'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
