import {readFile} from "node:fs/promises";
import {describe,expect,it} from "vitest";
import {createFakeRuntimeAdmissionNativeAdapter} from "../packages/core/src/runtime-admission-lock.js";
import {HOST_XPC_SERVICE,loadNativeAdmissionBinding,wrapNativeAdmissionBinding} from "../packages/native-admission/src/index.js";
import {retireNativeSupplier} from "../packages/daemon/src/codex-transport-lifecycle.js";
describe("native admission fake and wrapper (native behavior unqualified)",()=>{
 it("is default-off without consulting the injected addon path and models opaque single ownership",()=>{expect(loadNativeAdmissionBinding(false,"relative-or-untrusted.node")).toEqual({state:"unavailable",reason:"native-package-unqualified"});const a=createFakeRuntimeAdmissionNativeAdapter(),l=a.acquire("x","runtime-admission-authority.lock");expect(l.held).toBe(true);expect(()=>a.acquire("x","runtime-admission-authority.lock")).toThrow("lock-contended");l.close();expect(l.held).toBe(false);expect(()=>l.close()).toThrow();});
 it("requires an explicit safe absolute addon path before attempting a native load",()=>{expect(loadNativeAdmissionBinding(true)).toEqual({state:"unavailable",reason:"native-package-unqualified"});for(const value of ["relative.node","/private/tmp/../unsafe.node","/private/tmp/unsafe\n.node"])expect(loadNativeAdmissionBinding(true,value)).toEqual({state:"unavailable",reason:"path-unsafe"});});
 it("rejects inode mismatch",()=>expect(()=>createFakeRuntimeAdmissionNativeAdapter({pathMatches:false}).acquire("x","runtime-admission-authority.lock")).toThrow("inode-mismatch"));
 it("strictly translates lease getters and known/unknown native errors",()=>{let held=true,closes=0;const adapter=wrapNativeAdmissionBinding({acquire:()=>({device:1n,inode:2n,created:true,get held(){return held;},close(){held=false;closes++;}})});const result=adapter.acquire("/private/tmp");expect(result.state).toBe("available");if(result.state!=="available")throw Error();expect(Object.keys(result.value).sort()).toEqual(["close","created","device","held","inode"]);result.value.close();expect(result.value.held).toBe(false);expect(()=>result.value.close()).toThrow();expect(closes).toBe(1);for(const code of ["lock-contended","unknown"]){const r=wrapNativeAdmissionBinding({acquire(){throw Object.assign(Error(),{code});}}).acquire("/private/tmp");expect(r).toEqual({state:"unavailable",reason:code==="unknown"?"native-package-unqualified":code});}});
 it("rejects every non-32-byte bootstrap before invoking native",()=>{let calls=0;const binding=wrapNativeAdmissionBinding({spawnSupplier(){calls++;}});for(const size of [0,31,33,64])expect(binding.spawnSupplier("/private/fake",[],Buffer.alloc(size)).state).toBe("unavailable");expect(calls).toBe(0);});
 it("rejects raw descriptors and malformed native lease contracts",()=>{for(const value of [7,{device:1n,inode:2n,close(){}},{device:1n,inode:2n,created:true,held:false,close(){}}])expect(wrapNativeAdmissionBinding({acquire:()=>value}).acquire("/private/tmp").state).toBe("unavailable");});
 it("orders EOF/TERM/KILL and accepts only exact wait completion",async()=>{const events:string[]=[];let finish!:()=>void;const waited=new Promise<void>(r=>finish=r);await retireNativeSupplier({wait:()=>{events.push("wait");return waited;},closeInput:()=>events.push("eof"),terminate:()=>events.push("term"),kill:()=>{events.push("kill");finish();}},async phase=>{events.push("deadline:"+phase);});expect(events.slice(0,6)).toEqual(["wait","eof","deadline:eof","term","deadline:term","kill"]);});
 it("supplier hang remains unverified after the deterministic deadlines",async()=>{const events:string[]=[];await expect(retireNativeSupplier({wait:()=>new Promise(()=>{}),closeInput:()=>events.push("eof"),terminate:()=>events.push("term"),kill:()=>events.push("kill")},async()=>{})).rejects.toThrow("unverified");expect(events).toEqual(["eof","term","kill"]);});
});

describe("native wrapper exact bootstrap and child translation",()=>{
 it("passes exactly the 32 bootstrap bytes and translates one opaque child wait",async()=>{let nativeCalls=0,waitCalls=0;const secret=Buffer.alloc(32,4);const adapter=wrapNativeAdmissionBinding({spawnSupplier(executable:string,args:string[],received:Buffer){nativeCalls++;expect(executable).toBe("/private/supplier");expect(args).toEqual(["--private"]);expect(received.equals(secret)).toBe(true);return{read:async()=>Buffer.alloc(0),write:async()=>{},closeInput(){},terminate(){},kill(){},wait:async()=>{waitCalls++;return{exitCode:0,signal:null};}};}});const r=adapter.spawnSupplier("/private/supplier",["--private"],secret);expect(r.state).toBe("available");if(r.state!=="available")throw Error();expect(Object.keys(r.value).sort()).toEqual(["closeInput","kill","stdin","stdout","terminate","wait"]);expect(await r.value.wait()).toEqual({exitCode:0,signal:null});await r.value.wait();expect(nativeCalls).toBe(1);expect(waitCalls).toBe(1);});
 it("passes only the strict canonical cwd, closed environment and process-group request",()=>{const calls:unknown[][]=[];const adapter=wrapNativeAdmissionBinding({spawnSupplier(...args:unknown[]){calls.push(args);return{pid:4312,read:async()=>Buffer.alloc(0),write:async()=>{},closeInput(){},terminate(){},kill(){},wait:async()=>({exitCode:0,signal:null}),observeLeader:async()=>({exitCode:0,signal:null}),reapLeader:async()=>({exitCode:0,signal:null}),groupRetired:()=>true};}});const environment={HOME:"/private/supplier",CODEX_HOME:"/private/supplier/home",TMPDIR:"/private/supplier/tmp",PATH:"/usr/bin:/bin:/usr/sbin:/sbin",LANG:"en_US.UTF-8"};const result=adapter.spawnGroupedSupplier("/usr/bin/sandbox-exec",["-f","/private/supplier/outer.sb","/private/supplier/codex","app-server"],Buffer.alloc(32,7),{cwd:"/project",environment,processGroup:true});expect(result.state).toBe("available");if(result.state!=="available")throw Error();expect(result.value.pid).toBe(4312);expect(Object.keys(result.value).sort()).toEqual(["closeInput","groupRetired","kill","observeLeader","pid","reapLeader","stdin","stdout","terminate"]);expect(calls[0]!.slice(3)).toEqual(["/project",["CODEX_HOME=/private/supplier/home","HOME=/private/supplier","LANG=en_US.UTF-8","PATH=/usr/bin:/bin:/usr/sbin:/sbin","TMPDIR=/private/supplier/tmp"],true]);});
 it("rejects incomplete environments and requires a pid for strict launches before returning pipes",()=>{let calls=0;const raw={spawnSupplier(){calls++;return{read:async()=>Buffer.alloc(0),write:async()=>{},closeInput(){},terminate(){},kill(){},wait:async()=>({exitCode:0,signal:null})};}};const adapter=wrapNativeAdmissionBinding(raw);const environment={HOME:"/private/supplier",CODEX_HOME:"/private/supplier/home",TMPDIR:"/private/supplier/tmp",PATH:"/usr/bin:/bin:/usr/sbin:/sbin",LANG:"en_US.UTF-8"};expect(adapter.spawnGroupedSupplier("/usr/bin/sandbox-exec",[],Buffer.alloc(32),{cwd:"/project",environment:{...environment,PATH:"/untrusted/bin"},processGroup:true}).state).toBe("unavailable");expect(calls).toBe(0);expect(adapter.spawnGroupedSupplier("/usr/bin/sandbox-exec",[],Buffer.alloc(32),{cwd:"/project",environment,processGroup:true})).toEqual({state:"unavailable",reason:"native-package-unqualified"});});
 it("keeps fd3, canonical cwd, exact closed env, WNOWAIT and owned process-group behavior in the native source contract",async()=>{const source=await readFile(new URL("../packages/native-admission/src/addon.cc",import.meta.url),"utf8");for(const fragment of ["posix_spawn_file_actions_adddup2(&actions,pipes[2][0],3)","canonical_file(executable)","canonical_directory(cwd)","posix_spawn_file_actions_addchdir_np(&actions,cwd)","POSIX_SPAWN_SETPGROUP","posix_spawnattr_setpgroup(&attr,0)","strict?environment:empty_environment","en_US.UTF-8","/usr/bin:/bin:/usr/sbin:/sbin","WEXITED|WNOWAIT","c->process_group?-c->pid:c->pid","group_retired"])expect(source).toContain(fragment);});
 it("keeps finalizer fallback nonblocking and reaps only an exactly observed exited leader",async()=>{const source=await readFile(new URL("../packages/native-admission/src/addon.cc",import.meta.url),"utf8");const finalizer=source.slice(source.indexOf("static void child_final"),source.indexOf("static void* unwrap"));for(const fragment of ["WEXITED|WNOHANG|WNOWAIT","observed.si_pid==c->pid","waitpid(c->pid,&status,WNOHANG)","if(reaped==c->pid)c->reaped=true"])expect(finalizer).toContain(fragment);expect(finalizer).not.toContain("waitpid(c->pid,nullptr,0)");});
});

describe("opaque HOST-P2 wrapper protocol",()=>{
 it("uses bounded public XPC fields and a reserved once-only TSFN terminal slot",async()=>{const source=await readFile(new URL("../packages/native-admission/src/host-xpc.mm",import.meta.url),"utf8"),addon=await readFile(new URL("../packages/native-admission/src/addon.cc",import.meta.url),"utf8"),gyp=await readFile(new URL("../packages/native-admission/binding.gyp",import.meta.url),"utf8");expect(source).toContain('xpc_connection_set_peer_code_signing_requirement(port->endpoint,requirement)');expect(source.indexOf("xpc_connection_set_peer_code_signing_requirement")).toBeLessThan(source.indexOf("xpc_connection_activate(port->endpoint)"));expect(source).toContain("xpc_connection_get_euid");for(const forbidden of ["xpc_connection_get_pid","audit_token","LOCAL_PEERTOKEN","xpc_copy_description"])expect(source).not.toContain(forbidden);for(const fragment of ["dictionary_count(value)","bounded_literal", "n==32", "canonical_uuid", "pending.request_kind!=expected", "pending.request_id!=request_id", "retain_port(port)", "release_port(port)"])expect(source).toContain(fragment);expect(addon).toContain("napi_create_threadsafe_function(e,args[3],nullptr,name,64");expect(addon).toContain("queued<63");expect(addon).toContain("terminal_queued.exchange(true)");expect(addon).toContain("napi_tsfn_nonblocking");expect(addon).toContain("release_tsfn_once");expect(gyp).toContain('"NAPI_VERSION=6"');expect(gyp).toContain('"src/host-xpc.mm"');expect(gyp).not.toContain("-lxpc");});
 it("round trips UUID generation, provision grant and daemon-owned ping while zeroing bridge copies",async()=>{
  const generation="9da2fe68-639c-40d3-9c10-3ff80f496560",requestId="provision-0001",challenge=Buffer.alloc(32,1),nonce=Buffer.alloc(32,2),proof=Buffer.alloc(32,3),bearer=Buffer.alloc(32,4),zeroed:Buffer[]=[];let serverEvent:(event:any)=>void=()=>{},clientEvent:(event:any)=>void=()=>{},closes=0;
  const makeRaw=(server:boolean)=>({
   serverChallenge(token:bigint,id:string,bytes:Buffer,gen:string){expect([token,id,gen]).toEqual([1n,requestId,generation]);const snapshot=Buffer.from(bytes);zeroed.push(bytes);queueMicrotask(()=>clientEvent({type:"challenge",requestId:id,ok:true,challenge:snapshot,generation:gen}));},
   serverGrant(token:bigint,id:string,bytes:Buffer,gen:string){expect([token,id,gen]).toEqual([2n,requestId,generation]);const snapshot=Buffer.from(bytes);zeroed.push(bytes);queueMicrotask(()=>clientEvent({type:"grant",requestId:id,ok:true,bearer:snapshot,generation:gen}));},
   clientPong(token:bigint,id:string,sequence:bigint){queueMicrotask(()=>serverEvent({type:"pong",requestId:id,sequence,ok:true}));},
   clientOpen(id:string){queueMicrotask(()=>serverEvent({type:"open",connectionId:"host-1",requestId:id,replyToken:1n}));},
   clientFinish(id:string,hostNonce:Buffer,hmac:Buffer){expect(hostNonce.equals(nonce)).toBe(true);expect(hmac.equals(proof)).toBe(true);const nonceSnapshot=Buffer.from(hostNonce),proofSnapshot=Buffer.from(hmac);zeroed.push(hostNonce,hmac);queueMicrotask(()=>serverEvent({type:"finish",connectionId:"host-1",requestId:id,replyToken:2n,hostNonce:nonceSnapshot,proof:proofSnapshot}));},
   serverPing(connectionId:string,id:string,sequence:bigint){expect(connectionId).toBe("host-1");queueMicrotask(()=>clientEvent({type:"ping",requestId:id,replyToken:3n,sequence}));},closeConnection(){},async close(){closes++;}
  });
  const binding=wrapNativeAdmissionBinding({hostXpcService:HOST_XPC_SERVICE,createHostXpcPort(server:boolean,_requirement:string,_euid:number,callback:(event:any)=>void){if(server)serverEvent=callback;else clientEvent=callback;return makeRaw(server);}});
  const serverResult=binding.createHostXpcServer({peerRequirement:'anchor apple generic and identifier "com.chirality.app"',expectedEuid:501,onAdmitted(){},onInvalidated(){},onCeremonyOpen:({requestId:id})=>({requestId:id,challenge,generation}),onCeremonyFinish:({requestId:id,hostNonce,proof:receivedProof})=>{expect(hostNonce.equals(nonce)).toBe(true);expect(receivedProof.equals(proof)).toBe(true);return{requestId:id,bearer,generation,scopes:["account:read","account:control"] as const};}});
  const clientResult=binding.createHostXpcClient({peerRequirement:'anchor apple generic and identifier "com.chirality.app"',expectedEuid:501,onInvalidated(){},onPing:input=>input});expect(serverResult.state).toBe("available");expect(clientResult.state).toBe("available");if(serverResult.state!=="available"||clientResult.state!=="available")throw Error();serverEvent({type:"admitted",connectionId:"host-1"});
  const grant=await clientResult.value.provision({requestId,onChallenge:received=>{expect(received.generation).toBe(generation);expect(received.challenge.equals(challenge)).toBe(true);return{requestId,hostNonce:nonce,proof};}});expect(grant).toEqual({requestId,bearer,generation,scopes:["account:read","account:control"]});
  await expect(serverResult.value.ping("host-1",{requestId:"ping-0001",sequence:7n})).resolves.toEqual({requestId:"ping-0001",sequence:7n});expect(zeroed.every(value=>value.every(byte=>byte===0))).toBe(true);
  const serverClose=serverResult.value.close();expect(serverResult.value.close()).toBe(serverClose);await Promise.all([serverClose,clientResult.value.close(),clientResult.value.close()]);expect(closes).toBe(2);
 });
 it("fails closed for missing raw host ABI and invalid shared bounds",()=>{const binding=wrapNativeAdmissionBinding({hostXpcService:HOST_XPC_SERVICE});const config={peerRequirement:"requirement",expectedEuid:501,onInvalidated(){},onPing:(input:any)=>input};expect(binding.createHostXpcClient(config)).toEqual({state:"unavailable",reason:"host-xpc-unavailable"});expect(wrapNativeAdmissionBinding({hostXpcService:HOST_XPC_SERVICE,createHostXpcPort(){throw Object.assign(Error(),{code:"host-xpc-requirement-invalid"});}}).createHostXpcClient(config)).toEqual({state:"unavailable",reason:"host-xpc-requirement-invalid"});});
 it.each(["generation","9DA2FE68-639C-40D3-9C10-3FF80F496560","9da2fe68-639c-40d3-9c10-3ff80f49656"])("rejects noncanonical generation %s before challenge delivery",async bad=>{let emit:(event:any)=>void=()=>{};const raw:any={clientOpen(id:string){queueMicrotask(()=>emit({type:"challenge",requestId:id,ok:true,challenge:Buffer.alloc(32),generation:bad}));},clientFinish(){},clientPong(){},serverChallenge(){},serverGrant(){},serverPing(){},closeConnection(){},async close(){}};const binding=wrapNativeAdmissionBinding({hostXpcService:HOST_XPC_SERVICE,createHostXpcPort(_server:boolean,_requirement:string,_euid:number,callback:(event:any)=>void){emit=callback;return raw;}}),result=binding.createHostXpcClient({peerRequirement:"requirement",expectedEuid:501,onInvalidated(){},onPing:input=>input});if(result.state!=="available")throw Error();await expect(result.value.provision({requestId:"uuid-negative",onChallenge(){throw Error("must-not-deliver");}})).rejects.toThrow("Host XPC unavailable");});
 it("rejects a grant whose generation differs from its challenge",async()=>{let emit:(event:any)=>void=()=>{};const first="9da2fe68-639c-40d3-9c10-3ff80f496560",changed="aaaaaaaa-639c-40d3-9c10-3ff80f496560",raw:any={clientOpen(id:string){queueMicrotask(()=>emit({type:"challenge",requestId:id,ok:true,challenge:Buffer.alloc(32),generation:first}));},clientFinish(id:string){queueMicrotask(()=>emit({type:"grant",requestId:id,ok:true,bearer:Buffer.alloc(32),generation:changed}));},clientPong(){},serverChallenge(){},serverGrant(){},serverPing(){},closeConnection(){},async close(){}};const binding=wrapNativeAdmissionBinding({hostXpcService:HOST_XPC_SERVICE,createHostXpcPort(_server:boolean,_requirement:string,_euid:number,callback:(event:any)=>void){emit=callback;return raw;}}),result=binding.createHostXpcClient({peerRequirement:"requirement",expectedEuid:501,onInvalidated(){},onPing:input=>input});if(result.state!=="available")throw Error();await expect(result.value.provision({requestId:"generation-mismatch",onChallenge:()=>({requestId:"generation-mismatch",hostNonce:Buffer.alloc(32),proof:Buffer.alloc(32)})})).rejects.toThrow("Host XPC unavailable");});
 it.each(["reply-first","invalidation-first"] as const)("preserves a validated negative challenge when events arrive %s",async order=>{
  let emit:(event:any)=>void=()=>{},openCalls=0,challengeCalls=0;const reasons:string[]=[];
  const raw:any={clientOpen(){openCalls++;},clientFinish(){},clientPong(){},serverChallenge(){},serverGrant(){},serverPing(){},closeConnection(){},async close(){}};
  const binding=wrapNativeAdmissionBinding({hostXpcService:HOST_XPC_SERVICE,createHostXpcPort(_server:boolean,_requirement:string,_euid:number,callback:(event:any)=>void){emit=callback;return raw;}});
  const result=binding.createHostXpcClient({peerRequirement:"requirement",expectedEuid:501,onInvalidated:value=>reasons.push(value),onPing:input=>input});if(result.state!=="available")throw Error();
  const pending=result.value.provision({requestId:"negative-challenge",onChallenge(){challengeCalls++;return{requestId:"negative-challenge",hostNonce:Buffer.alloc(32),proof:Buffer.alloc(32)};}});
  const reply={type:"challenge",requestId:"negative-challenge",ok:false,reason:"peer-requirement-rejected"};const invalidated={type:"invalidated",reason:"peer-requirement-rejected"};
  if(order==="reply-first"){emit(reply);emit(invalidated);}else{emit(invalidated);emit(reply);}emit(reply);emit(invalidated);
  await expect(pending).rejects.toMatchObject({code:"peer-requirement-rejected"});expect(challengeCalls).toBe(0);expect(reasons).toEqual(["peer-requirement-rejected"]);
  await expect(result.value.provision({requestId:"late-provision",onChallenge(){throw Error();}})).rejects.toMatchObject({code:"host-xpc-closed"});expect(openCalls).toBe(1);
 });
 it.each(["reply-first","invalidation-first"] as const)("preserves a validated negative grant when events arrive %s",async order=>{
  const generation="9da2fe68-639c-40d3-9c10-3ff80f496560";let emit:(event:any)=>void=()=>{},challengeCalls=0,finishCalls=0;const reasons:string[]=[];
  const raw:any={clientOpen(id:string){queueMicrotask(()=>emit({type:"challenge",requestId:id,ok:true,challenge:Buffer.alloc(32),generation}));},clientFinish(){finishCalls++;},clientPong(){},serverChallenge(){},serverGrant(){},serverPing(){},closeConnection(){},async close(){}};
  const binding=wrapNativeAdmissionBinding({hostXpcService:HOST_XPC_SERVICE,createHostXpcPort(_server:boolean,_requirement:string,_euid:number,callback:(event:any)=>void){emit=callback;return raw;}});
  const result=binding.createHostXpcClient({peerRequirement:"requirement",expectedEuid:501,onInvalidated:value=>reasons.push(value),onPing:input=>input});if(result.state!=="available")throw Error();
  const pending=result.value.provision({requestId:"negative-grant",onChallenge(){challengeCalls++;return{requestId:"negative-grant",hostNonce:Buffer.alloc(32),proof:Buffer.alloc(32)};}});for(let turn=0;turn<5&&!finishCalls;turn++)await Promise.resolve();expect(finishCalls).toBe(1);
  const reply={type:"grant",requestId:"negative-grant",ok:false,reason:"peer-interrupted"};const invalidated={type:"invalidated",reason:"peer-interrupted"};
  if(order==="reply-first"){emit(reply);emit(invalidated);}else{emit(invalidated);emit(reply);}emit(reply);
  await expect(pending).rejects.toMatchObject({code:"peer-interrupted"});expect(challengeCalls).toBe(1);expect(reasons).toEqual(["peer-interrupted"]);
 });
 it.each([{requestId:"wrong-request",reason:"peer-requirement-rejected"},{requestId:"expected-request",reason:"delivery-unavailable"}])("maps malformed negative reply $requestId/$reason to protocol invalid",async malformed=>{
  let emit:(event:any)=>void=()=>{},challengeCalls=0;const reasons:string[]=[];const raw:any={clientOpen(){},clientFinish(){},clientPong(){},serverChallenge(){},serverGrant(){},serverPing(){},closeConnection(){},async close(){}};
  const binding=wrapNativeAdmissionBinding({hostXpcService:HOST_XPC_SERVICE,createHostXpcPort(_server:boolean,_requirement:string,_euid:number,callback:(event:any)=>void){emit=callback;return raw;}}),result=binding.createHostXpcClient({peerRequirement:"requirement",expectedEuid:501,onInvalidated:value=>reasons.push(value),onPing:input=>input});if(result.state!=="available")throw Error();
  const pending=result.value.provision({requestId:"expected-request",onChallenge(){challengeCalls++;throw Error();}});emit({type:"challenge",requestId:malformed.requestId,ok:false,reason:malformed.reason});
  await expect(pending).rejects.toMatchObject({code:"protocol-invalid"});expect(challengeCalls).toBe(0);expect(reasons).toEqual(["protocol-invalid"]);
 });
 it("drops deferred ping completion after close and keeps public close sticky",async()=>{let emit:(event:any)=>void=()=>{},pongCalls=0,openCalls=0,finish!:()=>void;const delayed=new Promise<{requestId:string;sequence:bigint}>(resolve=>{finish=()=>resolve({requestId:"late-ping",sequence:4n});}),raw:any={clientOpen(){openCalls++;},clientFinish(){},clientPong(){pongCalls++;},serverChallenge(){},serverGrant(){},serverPing(){},closeConnection(){},async close(){}};const binding=wrapNativeAdmissionBinding({hostXpcService:HOST_XPC_SERVICE,createHostXpcPort(_server:boolean,_requirement:string,_euid:number,callback:(event:any)=>void){emit=callback;return raw;}}),result=binding.createHostXpcClient({peerRequirement:"requirement",expectedEuid:501,onInvalidated(){},onPing:()=>delayed});if(result.state!=="available")throw Error();emit({type:"ping",requestId:"late-ping",replyToken:9n,sequence:4n});const closed=result.value.close();expect(result.value.close()).toBe(closed);finish();await closed;await Promise.resolve();expect(pongCalls).toBe(0);await expect(result.value.provision({requestId:"after-close",onChallenge(){throw Error();}})).rejects.toThrow("Host XPC unavailable");expect(openCalls).toBe(0);});
 it("drops deferred server ceremony callbacks after connection and port retirement",async()=>{let emit:(event:any)=>void=()=>{},challenges=0,grants=0,finishOpen!:()=>void,finishGrant!:()=>void;const open=new Promise<any>(resolve=>{finishOpen=()=>resolve({requestId:"open-race",challenge:Buffer.alloc(32),generation:"9da2fe68-639c-40d3-9c10-3ff80f496560"});}),grant=new Promise<any>(resolve=>{finishGrant=()=>resolve({requestId:"finish-race",bearer:Buffer.alloc(32),generation:"9da2fe68-639c-40d3-9c10-3ff80f496560",scopes:["account:read","account:control"]});}),raw:any={clientOpen(){},clientFinish(){},clientPong(){},serverChallenge(){challenges++;},serverGrant(){grants++;},serverPing(){},closeConnection(){},async close(){}};const binding=wrapNativeAdmissionBinding({hostXpcService:HOST_XPC_SERVICE,createHostXpcPort(_server:boolean,_requirement:string,_euid:number,callback:(event:any)=>void){emit=callback;return raw;}}),result=binding.createHostXpcServer({peerRequirement:"requirement",expectedEuid:501,onAdmitted(){},onInvalidated(){},onCeremonyOpen:()=>open,onCeremonyFinish:()=>grant});if(result.state!=="available")throw Error();emit({type:"admitted",connectionId:"host-open"});emit({type:"open",connectionId:"host-open",requestId:"open-race",replyToken:1n});await result.value.closeConnection("host-open","lease-closed");finishOpen();await Promise.resolve();await Promise.resolve();expect(challenges).toBe(0);emit({type:"admitted",connectionId:"host-finish"});emit({type:"open",connectionId:"host-finish",requestId:"finish-race",replyToken:2n});await Promise.resolve();emit({type:"finish",connectionId:"host-finish",requestId:"finish-race",replyToken:3n,hostNonce:Buffer.alloc(32),proof:Buffer.alloc(32)});const closed=result.value.close();finishGrant();await closed;await Promise.resolve();expect(grants).toBe(0);});
});
