import {describe,expect,it} from "vitest";
import {createFakeRuntimeAdmissionNativeAdapter} from "../packages/core/src/runtime-admission-lock.js";
import {loadNativeAdmissionBinding,wrapNativeAdmissionBinding} from "../packages/native-admission/src/index.js";
import {retireNativeSupplier} from "../packages/daemon/src/codex-transport-lifecycle.js";
describe("native admission fake and wrapper (native behavior unqualified)",()=>{
 it("is default-off and models opaque single ownership",()=>{expect(loadNativeAdmissionBinding(false)).toEqual({state:"unavailable",reason:"native-package-unqualified"});const a=createFakeRuntimeAdmissionNativeAdapter(),l=a.acquire("x","runtime-admission-authority.lock");expect(l.held).toBe(true);expect(()=>a.acquire("x","runtime-admission-authority.lock")).toThrow("lock-contended");l.close();expect(l.held).toBe(false);expect(()=>l.close()).toThrow();});
 it("rejects inode mismatch",()=>expect(()=>createFakeRuntimeAdmissionNativeAdapter({pathMatches:false}).acquire("x","runtime-admission-authority.lock")).toThrow("inode-mismatch"));
 it("strictly translates lease getters and known/unknown native errors",()=>{let held=true,closes=0;const adapter=wrapNativeAdmissionBinding({acquire:()=>({device:1n,inode:2n,created:true,get held(){return held;},close(){held=false;closes++;}})});const result=adapter.acquire("/private/tmp");expect(result.state).toBe("available");if(result.state!=="available")throw Error();expect(Object.keys(result.value).sort()).toEqual(["close","created","device","held","inode"]);result.value.close();expect(result.value.held).toBe(false);expect(()=>result.value.close()).toThrow();expect(closes).toBe(1);for(const code of ["lock-contended","unknown"]){const r=wrapNativeAdmissionBinding({acquire(){throw Object.assign(Error(),{code});}}).acquire("/private/tmp");expect(r).toEqual({state:"unavailable",reason:code==="unknown"?"native-package-unqualified":code});}});
 it("rejects every non-32-byte bootstrap before invoking native",()=>{let calls=0;const binding=wrapNativeAdmissionBinding({spawnSupplier(){calls++;}});for(const size of [0,31,33,64])expect(binding.spawnSupplier("/private/fake",[],Buffer.alloc(size)).state).toBe("unavailable");expect(calls).toBe(0);});
 it("rejects raw descriptors and malformed native lease contracts",()=>{for(const value of [7,{device:1n,inode:2n,close(){}},{device:1n,inode:2n,created:true,held:false,close(){}}])expect(wrapNativeAdmissionBinding({acquire:()=>value}).acquire("/private/tmp").state).toBe("unavailable");});
 it("orders EOF/TERM/KILL and accepts only exact wait completion",async()=>{const events:string[]=[];let finish!:()=>void;const waited=new Promise<void>(r=>finish=r);await retireNativeSupplier({wait:()=>{events.push("wait");return waited;},closeInput:()=>events.push("eof"),terminate:()=>events.push("term"),kill:()=>{events.push("kill");finish();}},async phase=>{events.push("deadline:"+phase);});expect(events.slice(0,6)).toEqual(["wait","eof","deadline:eof","term","deadline:term","kill"]);});
 it("supplier hang remains unverified after the deterministic deadlines",async()=>{const events:string[]=[];await expect(retireNativeSupplier({wait:()=>new Promise(()=>{}),closeInput:()=>events.push("eof"),terminate:()=>events.push("term"),kill:()=>events.push("kill")},async()=>{})).rejects.toThrow("unverified");expect(events).toEqual(["eof","term","kill"]);});
});

describe("native wrapper exact bootstrap and child translation",()=>{
 it("passes exactly the 32 bootstrap bytes and translates one opaque child wait",async()=>{let nativeCalls=0,waitCalls=0;const secret=Buffer.alloc(32,4);const adapter=wrapNativeAdmissionBinding({spawnSupplier(executable:string,args:string[],received:Buffer){nativeCalls++;expect(executable).toBe("/private/supplier");expect(args).toEqual(["--private"]);expect(received.equals(secret)).toBe(true);return{read:async()=>Buffer.alloc(0),write:async()=>{},closeInput(){},terminate(){},kill(){},wait:async()=>{waitCalls++;return{exitCode:0,signal:null};}};}});const r=adapter.spawnSupplier("/private/supplier",["--private"],secret);expect(r.state).toBe("available");if(r.state!=="available")throw Error();expect(Object.keys(r.value).sort()).toEqual(["closeInput","kill","stdin","stdout","terminate","wait"]);expect(await r.value.wait()).toEqual({exitCode:0,signal:null});await r.value.wait();expect(nativeCalls).toBe(1);expect(waitCalls).toBe(1);});
});
