import {readFile} from "node:fs/promises";
import {describe,expect,it} from "vitest";
import {createFakeRuntimeAdmissionNativeAdapter} from "../packages/core/src/runtime-admission-lock.js";
import {loadNativeAdmissionBinding,wrapNativeAdmissionBinding} from "../packages/native-admission/src/index.js";
import {retireNativeSupplier} from "../packages/daemon/src/codex-transport-lifecycle.js";
describe("native admission fake and wrapper (native behavior unqualified)",()=>{
 it("is default-off without consulting the injected addon path and models opaque single ownership",()=>{expect(loadNativeAdmissionBinding(false,"relative-or-untrusted.node")).toEqual({state:"unavailable",reason:"native-package-unqualified"});const a=createFakeRuntimeAdmissionNativeAdapter(),l=a.acquire("x","runtime-admission-authority.lock");expect(l.held).toBe(true);expect(()=>a.acquire("x","runtime-admission-authority.lock")).toThrow("lock-contended");l.close();expect(l.held).toBe(false);expect(()=>l.close()).toThrow();});
 it("requires an explicit safe absolute addon path before attempting a native load",()=>{expect(loadNativeAdmissionBinding(true)).toEqual({state:"unavailable",reason:"native-package-unqualified"});for(const value of ["relative.node","/private/tmp/../unsafe.node","/private/tmp/unsafe\n.node"])expect(loadNativeAdmissionBinding(true,value)).toEqual({state:"unavailable",reason:"path-unsafe"});});
 it("rejects inode mismatch",()=>expect(()=>createFakeRuntimeAdmissionNativeAdapter({pathMatches:false}).acquire("x","runtime-admission-authority.lock")).toThrow("inode-mismatch"));
 it("strictly translates lease getters and known/unknown native errors",()=>{let held=true,closes=0;const adapter=wrapNativeAdmissionBinding({acquire:()=>({device:1n,inode:2n,created:true,get held(){return held;},close(){held=false;closes++;}})});const result=adapter.acquire("/private/tmp");expect(result.state).toBe("available");if(result.state!=="available")throw Error();expect(Object.keys(result.value).sort()).toEqual(["close","created","device","held","inode"]);result.value.close();expect(result.value.held).toBe(false);expect(()=>result.value.close()).toThrow();expect(closes).toBe(1);for(const code of ["lock-contended","unknown"]){const r=wrapNativeAdmissionBinding({acquire(){throw Object.assign(Error(),{code});}}).acquire("/private/tmp");expect(r).toEqual({state:"unavailable",reason:code==="unknown"?"native-package-unqualified":code});}});
 it("rejects every non-32-byte bootstrap before invoking native",()=>{let calls=0;const binding=wrapNativeAdmissionBinding({spawnSupplier(){calls++;}});for(const size of [0,31,33,64])expect(binding.spawnSupplier("/private/fake",[],Buffer.alloc(size)).state).toBe("unavailable");expect(calls).toBe(0);});
 it("rejects raw descriptors and malformed native lease contracts",()=>{for(const value of [7,{device:1n,inode:2n,close(){}},{device:1n,inode:2n,created:true,held:false,close(){}}])expect(wrapNativeAdmissionBinding({acquire:()=>value}).acquire("/private/tmp").state).toBe("unavailable");});
 it("orders EOF/TERM/KILL and accepts only exact wait completion",async()=>{const events:string[]=[];let finish!:()=>void;const waited=new Promise<void>(r=>finish=r);await retireNativeSupplier({wait:()=>{events.push("wait");return waited;},closeInput:()=>events.push("eof"),terminate:()=>events.push("term"),kill:()=>{events.push("kill");finish();}},async phase=>{events.push("deadline:"+phase);});expect(events.slice(0,6)).toEqual(["wait","eof","deadline:eof","term","deadline:term","kill"]);});
 it("supplier hang remains unverified after the deterministic deadlines",async()=>{const events:string[]=[];await expect(retireNativeSupplier({wait:()=>new Promise(()=>{}),closeInput:()=>events.push("eof"),terminate:()=>events.push("term"),kill:()=>events.push("kill")},async()=>{})).rejects.toThrow("unverified");expect(events).toEqual(["eof","term","kill"]);});
});

describe("native wrapper exact bootstrap and child translation",()=>{
 it("passes exactly the 32 bootstrap bytes and translates one opaque child wait",async()=>{let nativeCalls=0,waitCalls=0;const secret=Buffer.alloc(32,4);const adapter=wrapNativeAdmissionBinding({spawnSupplier(executable:string,args:string[],received:Buffer){nativeCalls++;expect(executable).toBe("/private/supplier");expect(args).toEqual(["--private"]);expect(received.equals(secret)).toBe(true);return{read:async()=>Buffer.alloc(0),write:async()=>{},closeInput(){},terminate(){},kill(){},wait:async()=>{waitCalls++;return{exitCode:0,signal:null};}};}});const r=adapter.spawnSupplier("/private/supplier",["--private"],secret);expect(r.state).toBe("available");if(r.state!=="available")throw Error();expect(Object.keys(r.value).sort()).toEqual(["closeInput","kill","stdin","stdout","terminate","wait"]);expect(await r.value.wait()).toEqual({exitCode:0,signal:null});await r.value.wait();expect(nativeCalls).toBe(1);expect(waitCalls).toBe(1);});
 it("passes only the strict canonical cwd, closed environment and process-group request",()=>{const calls:unknown[][]=[];const adapter=wrapNativeAdmissionBinding({spawnSupplier(...args:unknown[]){calls.push(args);return{pid:4312,read:async()=>Buffer.alloc(0),write:async()=>{},closeInput(){},terminate(){},kill(){},wait:async()=>({exitCode:0,signal:null}),observeLeader:async()=>({exitCode:0,signal:null}),reapLeader:async()=>({exitCode:0,signal:null}),groupRetired:()=>true};}});const environment={HOME:"/private/supplier",CODEX_HOME:"/private/supplier/home",TMPDIR:"/private/supplier/tmp",PATH:"/usr/bin:/bin:/usr/sbin:/sbin",LANG:"en_US.UTF-8"};const result=adapter.spawnGroupedSupplier("/usr/bin/sandbox-exec",["-f","/private/supplier/outer.sb","/private/supplier/codex","app-server"],Buffer.alloc(32,7),{cwd:"/project",environment,processGroup:true});expect(result.state).toBe("available");if(result.state!=="available")throw Error();expect(result.value.pid).toBe(4312);expect(Object.keys(result.value).sort()).toEqual(["closeInput","groupRetired","kill","observeLeader","pid","reapLeader","stdin","stdout","terminate"]);expect(calls[0]!.slice(3)).toEqual(["/project",["CODEX_HOME=/private/supplier/home","HOME=/private/supplier","LANG=en_US.UTF-8","PATH=/usr/bin:/bin:/usr/sbin:/sbin","TMPDIR=/private/supplier/tmp"],true]);});
 it("rejects incomplete environments and requires a pid for strict launches before returning pipes",()=>{let calls=0;const raw={spawnSupplier(){calls++;return{read:async()=>Buffer.alloc(0),write:async()=>{},closeInput(){},terminate(){},kill(){},wait:async()=>({exitCode:0,signal:null})};}};const adapter=wrapNativeAdmissionBinding(raw);const environment={HOME:"/private/supplier",CODEX_HOME:"/private/supplier/home",TMPDIR:"/private/supplier/tmp",PATH:"/usr/bin:/bin:/usr/sbin:/sbin",LANG:"en_US.UTF-8"};expect(adapter.spawnGroupedSupplier("/usr/bin/sandbox-exec",[],Buffer.alloc(32),{cwd:"/project",environment:{...environment,PATH:"/untrusted/bin"},processGroup:true}).state).toBe("unavailable");expect(calls).toBe(0);expect(adapter.spawnGroupedSupplier("/usr/bin/sandbox-exec",[],Buffer.alloc(32),{cwd:"/project",environment,processGroup:true})).toEqual({state:"unavailable",reason:"native-package-unqualified"});});
 it("keeps fd3, canonical cwd, exact closed env, WNOWAIT and owned process-group behavior in the native source contract",async()=>{const source=await readFile(new URL("../packages/native-admission/src/addon.cc",import.meta.url),"utf8");for(const fragment of ["posix_spawn_file_actions_adddup2(&actions,pipes[2][0],3)","canonical_file(executable)","canonical_directory(cwd)","posix_spawn_file_actions_addchdir_np(&actions,cwd)","POSIX_SPAWN_SETPGROUP","posix_spawnattr_setpgroup(&attr,0)","strict?environment:empty_environment","en_US.UTF-8","/usr/bin:/bin:/usr/sbin:/sbin","WEXITED|WNOWAIT","c->process_group?-c->pid:c->pid","group_retired"])expect(source).toContain(fragment);});
 it("keeps finalizer fallback nonblocking and reaps only an exactly observed exited leader",async()=>{const source=await readFile(new URL("../packages/native-admission/src/addon.cc",import.meta.url),"utf8");const finalizer=source.slice(source.indexOf("static void child_final"),source.indexOf("static void* unwrap"));for(const fragment of ["WEXITED|WNOHANG|WNOWAIT","observed.si_pid==c->pid","waitpid(c->pid,&status,WNOHANG)","if(reaped==c->pid)c->reaped=true"])expect(finalizer).toContain(fragment);expect(finalizer).not.toContain("waitpid(c->pid,nullptr,0)");});
});
