import { describe,expect,it } from "vitest";
import { createHmac } from "node:crypto";
import { AuthorityTranscript, SupplierAuthorityController, AUTHORITY_CONTRACT, ZERO_TRANSCRIPT_MAC, canonicalBytes, asciiField, sequenceField, transcriptMac, decodeAuthorityBody, parseAuthorityJson, parseSequence20, nextSequence20, type AuthorityBody, type AuthorityEnvelope, type AuthorityTransport } from "../packages/daemon/src/supplier-authority-controller.js";
import { createFakeRuntimeAdmissionNativeAdapter } from "../packages/core/src/runtime-admission-lock.js";
const secret=Buffer.alloc(32,7),identity={runtimeProcessIncarnationId:"11111111-1111-1111-1111-111111111111",supplierGeneration:"s"};
function pair(mutate?:(frames:AuthorityEnvelope[])=>AuthorityEnvelope[]){const events:string[]=[];let accept!:(raw:string)=>void,failed!:()=>void;const peerIn=new AuthorityTranscript(secret,identity,"runtime-to-supplier"),peerOut=new AuthorityTranscript(secret,identity,"supplier-to-runtime");const transport:AuthorityTransport={subscribe(a,f){accept=a;failed=f;return()=>{};},async send(frame){const b=peerIn.accept(JSON.stringify(frame));if(b.kind!=="request")throw Error();events.push(b.op);const base=b.op==="chirality/admissionAcquire"?{requestId:b.requestId,operationId:b.operationId,leaseId:"lease",supplierGeneration:"s",identityGeneration:"i",snapshotDigest:"a".repeat(64)}:{requestId:b.requestId,leaseId:b.leaseId,disposition:b.disposition};const release=b.op==="chirality/admissionRelease",acquire=b.op==="chirality/admissionAcquire";const result={kind:"result",op:b.op,state:acquire?"acquired":release?"released":"aborted",...base} as AuthorityBody;const notification={kind:"notification",op:acquire?"chirality/admissionAcquired":release?"chirality/admissionReleased":"chirality/admissionAborted",...base} as AuthorityBody;const frames=[peerOut.encode(result),peerOut.encode(notification)];for(const f of mutate?mutate(frames):frames)accept(JSON.stringify(f));},async close(){events.push("close");}};const c=new SupplierAuthorityController({enabled:true,kernelLease:createFakeRuntimeAdmissionNativeAdapter().acquire("","runtime-admission-authority.lock"),transport,authoritySecret:secret,...identity,identityGeneration:"i",snapshotDigest:"a".repeat(64)});return{c,events,crash:()=>failed(),raw:(raw:string)=>accept(raw),revoke:()=>accept(JSON.stringify(peerOut.encode({kind:"notification",op:"chirality/admissionRevoked",reason:"identity-transition",revokedThroughRuntimeSequence:"00000000000000000001"}))) };}
describe("supplier authority strict transport",()=>{
 it("holds one operation-bound lease and releases only after commit",async()=>{const {c,events}=pair();await c.acquire("regular:w");await expect(c.acquire("regular:x")).rejects.toThrow("lease-busy");c.assertCommit("regular:w");await c.release("regular:w");expect(events).toEqual(["chirality/admissionAcquire","chirality/admissionRelease"]);await expect(c.release("regular:w")).rejects.toThrow();});
 it("aborts a single operation and rejects its reuse",async()=>{const {c,events}=pair();await c.acquire("manager:m");await c.abort("manager:m");await expect(c.abort("manager:m")).rejects.toThrow();expect(events).toEqual(["chirality/admissionAcquire","chirality/admissionAbort"]);});
 for(const variant of ["missing","interleaved","replay","gap","direction","generation","mac","unknown","wrong-body","wrong-tuple"]){it(`fails closed on ${variant}`,async()=>{const {c,events,crash}=pair(frames=>{const a=frames[0]!,b=frames[1]!;if(variant==="missing")return[a];if(variant==="interleaved")return[b,a];if(variant==="replay")return[a,a];if(variant==="gap")a.sequence="00000000000000000002";if(variant==="direction")a.direction="runtime-to-supplier";if(variant==="generation")a.supplierGeneration="other";if(variant==="mac")a.transcriptMac=ZERO_TRANSCRIPT_MAC;if(variant==="unknown")(a as any).extra=true;if(variant==="wrong-body")(a.body as any).state="released";if(variant==="wrong-tuple"){(a.body as any).identityGeneration="other";a.transcriptMac=transcriptMac(secret,a);(b.body as any).identityGeneration="other";b.previousTranscriptMac=a.transcriptMac;b.transcriptMac=transcriptMac(secret,b);}return frames;});const acquiring=c.acquire("regular:w");if(variant==="missing")crash();await expect(acquiring).rejects.toThrow();expect(c.projection()).toEqual({state:"unavailable",reason:"revoking"});expect(events.filter(x=>x==="close")).toHaveLength(1);});}
 it("invalidates a held expectation on an authenticated revoke",async()=>{const {c,revoke}=pair();await c.acquire("w");revoke();expect(()=>c.assertCommit("w")).toThrow();await expect(c.acquire("next")).rejects.toThrow();});
 it("rejects duplicate and escaped duplicate JSON keys and invalid UTF-8",()=>{for(const raw of ['{"a":1,"a":2}','{"a":1,"\\u0061":2}','{"n":1e999}'])expect(()=>parseAuthorityJson(raw)).toThrow();expect(()=>parseAuthorityJson(Buffer.from([0xff]))).toThrow();});
 it("rejects illegal union fields, discriminants and error pairs",()=>{for(const body of [{kind:"result",op:"error",state:"error",requestId:null,class:"busy",reason:"authority-revoked"},{kind:"request",op:"chirality/admissionRelease",requestId:"r",leaseId:"l",disposition:"worker-not-accepted"},{kind:"notification",op:"chirality/admissionRevoked",reason:"protocol-failure",revokedThroughRuntimeSequence:1}])expect(()=>decodeAuthorityBody(body)).toThrow();});
 it("accepts every exact legal error pair",()=>{const pairs={"authority-unavailable":"unavailable","authority-revoked":"authorization","generation-mismatch":"protocol","sequence-invalid":"protocol","transcript-invalid":"protocol","snapshot-stale":"stale","lease-busy":"busy","lease-unknown":"malformed","lease-state-invalid":"malformed","request-malformed":"malformed","internal-failure":"internal"};for(const [reason,kind]of Object.entries(pairs))expect(decodeAuthorityBody({kind:"result",op:"error",state:"error",requestId:null,class:kind,reason})).toHaveProperty("reason",reason);});
 it("preserves exact U64 sequences and exhausts independently in both directions",()=>{for(const direction of ["runtime-to-supplier","supplier-to-runtime"] as const){const sender=new AuthorityTranscript(secret,identity,direction),receiver=new AuthorityTranscript(secret,identity,direction);(sender as any).next="18446744073709551615";(receiver as any).next="18446744073709551615";const body:AuthorityBody=direction==="runtime-to-supplier"?{kind:"request",op:"chirality/admissionRelease",requestId:"r",leaseId:"l",disposition:"worker-accepted"}:{kind:"notification",op:"chirality/admissionRevoked",reason:"protocol-failure",revokedThroughRuntimeSequence:"09007199254740993001"};const frame=sender.encode(body);expect(receiver.accept(JSON.stringify(frame))).toEqual(body);expect(()=>sender.encode(body)).toThrow("sequence-invalid");expect(()=>receiver.accept(JSON.stringify(frame))).toThrow("sequence-invalid");}});
 it("checks independently encoded direction MAC vectors including eight-byte payloads",()=>{const lp=(b:Buffer)=>{const n=Buffer.alloc(4);n.writeUInt32BE(b.length);return Buffer.concat([n,b]);};for(const direction of ["runtime-to-supplier","supplier-to-runtime"] as const){const frame={contract:AUTHORITY_CONTRACT,...identity,direction,sequence:"09007199254740993001",previousTranscriptMac:ZERO_TRANSCRIPT_MAC,body:{kind:"notification",op:"chirality/admissionRevoked",reason:"protocol-failure",revokedThroughRuntimeSequence:"18446744073709551615"}} as const;const seq=Buffer.alloc(8);seq.writeBigUInt64BE(9007199254740993001n);const max=Buffer.alloc(8,255);const fields=[frame.contract,identity.runtimeProcessIncarnationId,"s",direction,seq,ZERO_TRANSCRIPT_MAC,"notification","chirality/admissionRevoked","protocol-failure",max].map(x=>lp(typeof x==="string"?Buffer.from(x,"ascii"):x));const count=Buffer.alloc(4);count.writeUInt32BE(fields.length);const bytes=Buffer.concat([Buffer.from("chirality-local-admission-mac\0"),Buffer.from([1]),lp(Buffer.from("transcript/"+direction)),count,...fields]);expect(bytes.toString("hex")).toContain("00000008ffffffffffffffff");expect(transcriptMac(secret,frame)).toBe(createHmac("sha256",secret).update(bytes).digest("base64url"));}});
 it("closes admission when an outgoing sequence would overflow",async()=>{const {c}=pair();(c as any).outgoing.next=undefined;await expect(c.acquire("w")).rejects.toThrow("sequence-invalid");expect(c.projection().state).toBe("unavailable");});
});
