import {describe,expect,it} from "vitest";
import {mkdtemp,rm,writeFile,readdir,readFile} from "node:fs/promises";
import {join} from "node:path";
import {tmpdir} from "node:os";
import {SupplierAuthorityJournal,SupplierAuthorityLifecycle,type AuthorityJournalEvent} from "../packages/daemon/src/supplier-authority-journal.js";
import {SupplierAuthorityController} from "../packages/daemon/src/supplier-authority-controller.js";
import {createFakeRuntimeAdmissionNativeAdapter} from "../packages/core/src/runtime-admission-lock.js";
const first="11111111-1111-1111-1111-111111111111",second="22222222-2222-2222-2222-222222222222",lockIdentity={device:"1",inode:"2"};
async function directory(fn:(p:string)=>Promise<void>){const d=await mkdtemp(join(tmpdir(),"authority-journal-"));try{await fn(join(d,"journal"));}finally{await rm(d,{recursive:true,force:true});}}
const record=(event:AuthorityJournalEvent,incarnation=first)=>({event,runtimeProcessIncarnationId:incarnation,supplierGeneration:null,lockIdentity});
describe("authority durable journal",()=>{
 it("fsyncs and verifies a hash-linked recovery fence",async()=>directory(async p=>{const j=new SupplierAuthorityJournal(p);await j.recover();await j.append(record("LOCK_ACQUIRED"));await j.append(record("UNCLEAN_PREDECESSOR_RECOVERY",second));await j.append(record("AUTHORITY_FENCED",second));expect((await new SupplierAuthorityJournal(p).recover()).map(r=>r.event)).toEqual(["LOCK_ACQUIRED","UNCLEAN_PREDECESSOR_RECOVERY","AUTHORITY_FENCED"]);}));
 for(const damage of ["torn","unknown","duplicate","fork","reordered"]){it(`quarantines ${damage} evidence without repairing the journal`,async()=>directory(async p=>{const j=new SupplierAuthorityJournal(p);await j.recover();await j.append(record("LOCK_ACQUIRED"));let text=await readFile(p,"utf8");if(damage==="torn")text+='{"';if(damage==="unknown")text=text.replace('"details":{}','"details":{"secret":"x"}');if(damage==="duplicate")text=text.replace('"details":{}','"details":{},"details":{}');if(damage==="fork")text=text.replace('"priorDigest":"'+"0".repeat(64),'"priorDigest":"'+"f".repeat(64));if(damage==="reordered")text=text.replace('"sequence":"1"','"sequence":"2"');await writeFile(p,text);await expect(new SupplierAuthorityJournal(p).recover()).rejects.toThrow("blocked");expect((await readdir(join(p,".."))).filter(n=>n.startsWith("journal.quarantine-"))).toHaveLength(1);await expect(readFile(p)).rejects.toHaveProperty("code","ENOENT");}));}
 it("rejects out-of-order lifecycle events and private details",async()=>directory(async p=>{const j=new SupplierAuthorityJournal(p);await j.recover();await expect(j.append(record("ACTIVE"))).rejects.toThrow("order");await j.append(record("LOCK_ACQUIRED"));await expect(j.append(record("ACTIVE"))).rejects.toThrow("order");}));
 for(const cutoff of ["LOCK_ACQUIRED","STARTING","PROVING","ACTIVE","REVOKING","SUPPLIER_RETIRING","SUPPLIER_RETIRED","AUTHORITY_FENCED"] as const){it(`fences an incomplete prefix ending at ${cutoff} before fresh supplier start`,async()=>directory(async p=>{const j=new SupplierAuthorityJournal(p);await j.recover();for(const event of ["LOCK_ACQUIRED","STARTING","PROVING","ACTIVE","REVOKING","SUPPLIER_RETIRING","SUPPLIER_RETIRED","AUTHORITY_FENCED"] as const){await j.append(record(event));if(event===cutoff)break;}const trace:string[]=[];const successor=new SupplierAuthorityLifecycle({journal:new SupplierAuthorityJournal(p),acquire:async()=>createFakeRuntimeAdmissionNativeAdapter({inode:2n,created:false}).acquire("","runtime-admission-authority.lock"),retire:async()=>{trace.push("cleanup");return{retired:true,cleanupVerified:true};},establish:async context=>{const records=await new SupplierAuthorityJournal(p).recover();expect(records.slice(-5).map(r=>r.event)).toEqual(["UNCLEAN_PREDECESSOR_RECOVERY","AUTHORITY_FENCED","SUPPLIER_RETIRED","LOCK_ACQUIRED","STARTING"]);trace.push("spawn");await context.spawned();return {projection:()=>({state:"ready"}),revoke:context.durableRevoke} as unknown as SupplierAuthorityController;}});await successor.start(second);expect(trace).toEqual(["cleanup","spawn"]);expect(successor.projection()).toEqual({state:"ready"});}));}
 it("holds fresh supplier startup when separate custody cleanup is ambiguous",async()=>directory(async p=>{const j=new SupplierAuthorityJournal(p);await j.recover();await j.append(record("LOCK_ACQUIRED"));let spawned=0;const lifecycle=new SupplierAuthorityLifecycle({journal:new SupplierAuthorityJournal(p),acquire:async()=>createFakeRuntimeAdmissionNativeAdapter({inode:2n,created:false}).acquire("","runtime-admission-authority.lock"),retire:async()=>({retired:true,cleanupVerified:false}),establish:async()=>{spawned++;throw Error();}});await expect(lifecycle.start(second)).rejects.toThrow("blocked");expect(spawned).toBe(0);expect((await new SupplierAuthorityJournal(p).recover()).at(-1)?.event).toBe("CUSTODY_BLOCKED_AMBIGUOUS");}));
 it("blocks a preexisting unrecorded lock and a replaced inode",async()=>{for(const existing of [false,true])await directory(async p=>{if(existing){const j=new SupplierAuthorityJournal(p);await j.recover();await j.append(record("LOCK_ACQUIRED"));}const lifecycle=new SupplierAuthorityLifecycle({journal:new SupplierAuthorityJournal(p),acquire:async()=>createFakeRuntimeAdmissionNativeAdapter({inode:3n,created:false}).acquire("","runtime-admission-authority.lock"),retire:async()=>({retired:true,cleanupVerified:true}),establish:async()=>{throw Error("must not spawn");}});await expect(lifecycle.start(second)).rejects.toThrow(existing?"inode-mismatch":"blocked");});});
});

describe("planned revocation and crash-before-sync ordering",()=>{
 it("drains the authority guard and records cleanup/fence before closing the lock",async()=>directory(async p=>{const trace:string[]=[];const lease=createFakeRuntimeAdmissionNativeAdapter({inode:2n}).acquire("","runtime-admission-authority.lock");const lifecycle=new SupplierAuthorityLifecycle({journal:new SupplierAuthorityJournal(p),acquire:async()=>lease,establish:async c=>{await c.spawned();return{projection:()=>({state:"ready"}),revoke:c.durableRevoke,close:async()=>{trace.push("guard-drained");}} as unknown as SupplierAuthorityController;},retire:async()=>{trace.push("supplier-cleanup");expect(lease.held).toBe(true);return{retired:true,cleanupVerified:true};}});await lifecycle.start(first);await lifecycle.close();expect(trace).toEqual(["guard-drained","supplier-cleanup"]);expect(lease.held).toBe(false);expect((await new SupplierAuthorityJournal(p).recover()).map(r=>r.event)).toEqual(["LOCK_ACQUIRED","STARTING","PROVING","ACTIVE","REVOKING","SUPPLIER_RETIRING","SUPPLIER_RETIRED","AUTHORITY_FENCED"]);}));
 it("a failed REVOKING append leaves the lock held and never treats the old active prefix as live recovery",async()=>directory(async p=>{class CrashJournal extends SupplierAuthorityJournal {override append(input:Parameters<SupplierAuthorityJournal["append"]>[0]){if(input.event==="REVOKING")return Promise.reject(new Error("simulated-crash-before-revoking-sync"));return super.append(input);}}const lease=createFakeRuntimeAdmissionNativeAdapter({inode:2n}).acquire("","runtime-admission-authority.lock");let cleanups=0;const lifecycle=new SupplierAuthorityLifecycle({journal:new CrashJournal(p),acquire:async()=>lease,establish:async c=>{await c.spawned();return{projection:()=>({state:"ready"}),revoke:c.durableRevoke,close:async()=>{}} as unknown as SupplierAuthorityController;},retire:async()=>{cleanups++;return{retired:true,cleanupVerified:true};}});await lifecycle.start(first);await expect(lifecycle.close()).rejects.toThrow("simulated-crash");expect(lease.held).toBe(true);expect(cleanups).toBe(0);expect((await new SupplierAuthorityJournal(p).recover()).at(-1)?.event).toBe("ACTIVE");expect(lifecycle.projection()).toEqual({state:"unavailable",reason:"blocked"});}));
});

// Cut real lifecycle operations, then model process death by releasing only the
// fake kernel lease. A fresh lifecycle must recover/fence before establishing.
describe("integrated crash recovery and fence cuts",()=>{
 for(const cut of ["after-lock","before-recovery-sync","after-recovery-sync","before-fence-sync","after-fence-sync","after-revoking-sync"] as const)it(`recovers ${cut} with no authority publication across the cut`,async()=>directory(async p=>{
  let lease=createFakeRuntimeAdmissionNativeAdapter({inode:2n}).acquire("","runtime-admission-authority.lock");
  const establish=async(c:Parameters<ConstructorParameters<typeof SupplierAuthorityLifecycle>[0]["establish"]>[0])=>{await c.spawned();return{projection:()=>({state:"ready"}),revoke:c.durableRevoke,close:async()=>{}} as unknown as SupplierAuthorityController;};
  const original=new SupplierAuthorityLifecycle({journal:new SupplierAuthorityJournal(p),acquire:async()=>lease,establish,retire:async()=>({retired:true,cleanupVerified:true})});await original.start(first);const prefix=await readFile(p,"utf8");lease.close();
  class CutJournal extends SupplierAuthorityJournal {override async append(input:Parameters<SupplierAuthorityJournal["append"]>[0]){const target=cut.includes("recovery")?"UNCLEAN_PREDECESSOR_RECOVERY":cut.includes("fence")?"AUTHORITY_FENCED":"REVOKING";if(input.event===target&&cut.startsWith("before"))throw Error(`cut:${cut}`);const result=await super.append(input);if(input.event===target&&cut.startsWith("after"))throw Error(`cut:${cut}`);return result;}}
  lease=createFakeRuntimeAdmissionNativeAdapter({inode:2n,created:false}).acquire("","runtime-admission-authority.lock");let starts=0,cleanups=0;
  const interrupted=new SupplierAuthorityLifecycle({journal:new CutJournal(p),acquire:async()=>{if(cut==="after-lock")throw Error(`cut:${cut}`);return lease;},establish:async c=>{starts++;return establish(c);},retire:async()=>{cleanups++;return{retired:true,cleanupVerified:true};}});
  if(cut==="after-revoking-sync"){await interrupted.start(second);await expect(interrupted.close()).rejects.toThrow(`cut:${cut}`);expect(starts).toBe(1);expect(cleanups).toBe(1);}else{await expect(interrupted.start(second)).rejects.toThrow(`cut:${cut}`);expect(starts).toBe(0);expect(cleanups).toBe(0);}
  expect(interrupted.projection()).toEqual({state:"unavailable",reason:"blocked"});expect(lease.held).toBe(true);expect((await readFile(p,"utf8")).startsWith(prefix)).toBe(true);const cutRecords=await new SupplierAuthorityJournal(p).recover();expect(cutRecords.at(-1)?.event).toBe(cut==="after-revoking-sync"?"REVOKING":cut==="after-fence-sync"?"AUTHORITY_FENCED":cut==="after-recovery-sync"||cut==="before-fence-sync"?"UNCLEAN_PREDECESSOR_RECOVERY":"ACTIVE");lease.close();
  const retryLease=createFakeRuntimeAdmissionNativeAdapter({inode:2n,created:false}).acquire("","runtime-admission-authority.lock"),trace:string[]=[];
  const retry=new SupplierAuthorityLifecycle({journal:new SupplierAuthorityJournal(p),acquire:async()=>retryLease,retire:async()=>{trace.push("cleanup");return{retired:true,cleanupVerified:true};},establish:async c=>{expect((await new SupplierAuthorityJournal(p).recover()).slice(-5).map(r=>r.event)).toEqual(["UNCLEAN_PREDECESSOR_RECOVERY","AUTHORITY_FENCED","SUPPLIER_RETIRED","LOCK_ACQUIRED","STARTING"]);trace.push("establish");return establish(c);}});await retry.start("33333333-3333-3333-3333-333333333333");expect(trace).toEqual(["cleanup","establish"]);expect(retry.projection()).toEqual({state:"ready"});await retry.close();expect(retryLease.held).toBe(false);
 }));
});
