#include <node_api.h>
#include <spawn.h>
#include <unistd.h>
#include <fcntl.h>
#include <errno.h>
#include <signal.h>
#include <stdint.h>
#include <stddef.h>
#include <limits.h>
#include <stdlib.h>
#include <string.h>
#include <sys/file.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <atomic>

// Source candidate only. No native build or filesystem/process qualification is claimed.
struct Lease { int fd; dev_t device; ino_t inode; bool held; bool created; };
struct Child { pid_t pid; int input; int output; bool observed; bool reaped; bool waiting; bool process_group; siginfo_t leader; };
static napi_value fail(napi_env e,const char* reason){napi_throw_error(e,reason,"Native admission unavailable");return nullptr;}
static napi_value undefined(napi_env e){napi_value v;napi_get_undefined(e,&v);return v;}
static void lease_final(napi_env,void* data,void*){Lease* l=(Lease*)data;if(l->held)close(l->fd);free(l);}
static void child_final(napi_env,void* data,void*){Child* c=(Child*)data;if(c->input>=0)close(c->input);if(c->output>=0)close(c->output);if(!c->reaped){int signaled;do{signaled=kill(c->process_group?-c->pid:c->pid,SIGKILL);}while(signaled<0&&errno==EINTR);siginfo_t observed={};int waited;do{waited=waitid(P_PID,(id_t)c->pid,&observed,WEXITED|WNOHANG|WNOWAIT);}while(waited<0&&errno==EINTR);if(waited==0&&observed.si_pid==c->pid){int status=0;pid_t reaped;do{reaped=waitpid(c->pid,&status,WNOHANG);}while(reaped<0&&errno==EINTR);if(reaped==c->pid)c->reaped=true;}(void)signaled;}free(c);}
static void* unwrap(napi_env e,napi_callback_info info,napi_value* self){size_t n=0;void* data=nullptr;napi_get_cb_info(e,info,&n,nullptr,self,nullptr);if(napi_unwrap(e,*self,&data)!=napi_ok)return nullptr;return data;}
static napi_value lease_held(napi_env e,napi_callback_info info){napi_value self,v;Lease* l=(Lease*)unwrap(e,info,&self);if(!l)return fail(e,"native-package-unqualified");napi_get_boolean(e,l->held,&v);return v;}
static napi_value lease_close(napi_env e,napi_callback_info info){napi_value self;Lease* l=(Lease*)unwrap(e,info,&self);if(!l||!l->held)return fail(e,"native-package-unqualified");l->held=false;int fd=l->fd;l->fd=-1;if(close(fd))return fail(e,"native-package-unqualified");return undefined(e);}
static bool string_arg(napi_env e,napi_value v,char* out,size_t capacity){napi_valuetype t;size_t n=0;if(napi_typeof(e,v,&t)!=napi_ok||t!=napi_string||napi_get_value_string_utf8(e,v,nullptr,0,&n)!=napi_ok||n>=capacity)return false;size_t copied=0;if(napi_get_value_string_utf8(e,v,out,capacity,&copied)!=napi_ok||copied!=n||strlen(out)!=n)return false;for(size_t i=0;i<n;i++)if((unsigned char)out[i]<32)return false;return true;}
static napi_value acquire(napi_env e,napi_callback_info info){size_t n=3;napi_value args[3];napi_get_cb_info(e,info,&n,args,nullptr,nullptr);char directory[4096],name[128];if(n!=2||!string_arg(e,args[0],directory,sizeof(directory))||directory[0]!='/'||!string_arg(e,args[1],name,sizeof(name))||strcmp(name,"runtime-admission-authority.lock"))return fail(e,"path-unsafe");int parent=open(directory,O_RDONLY|O_DIRECTORY|O_CLOEXEC|O_NOFOLLOW);if(parent<0)return fail(e,"path-unsafe");struct stat ds;if(fstat(parent,&ds)||!S_ISDIR(ds.st_mode)||ds.st_uid!=geteuid()||(ds.st_mode&0777)!=0700){close(parent);return fail(e,"path-unsafe");}
  bool created=true;int fd=openat(parent,name,O_RDWR|O_CREAT|O_EXCL|O_CLOEXEC|O_NOFOLLOW,0600);if(fd<0&&errno==EEXIST){created=false;fd=openat(parent,name,O_RDWR|O_CLOEXEC|O_NOFOLLOW);}if(fd<0){close(parent);return fail(e,"path-unsafe");}struct stat before,after,linked;
  if(fstat(fd,&before)||!S_ISREG(before.st_mode)||before.st_uid!=geteuid()||(before.st_mode&0777)!=0600||before.st_nlink!=1){close(fd);close(parent);return fail(e,"path-unsafe");}
  if(flock(fd,LOCK_EX|LOCK_NB)){int saved=errno;close(fd);close(parent);return fail(e,saved==EWOULDBLOCK?"lock-contended":"api-unavailable");}
  if(fstat(fd,&after)||fstatat(parent,name,&linked,AT_SYMLINK_NOFOLLOW)||before.st_dev!=after.st_dev||before.st_ino!=after.st_ino||after.st_dev!=linked.st_dev||after.st_ino!=linked.st_ino||!S_ISREG(linked.st_mode)||linked.st_nlink!=1||linked.st_uid!=geteuid()||(linked.st_mode&0777)!=0600){close(fd);close(parent);return fail(e,"inode-mismatch");}close(parent);
  Lease* l=(Lease*)calloc(1,sizeof(Lease));if(!l){close(fd);return fail(e,"native-package-unqualified");}*l={fd,after.st_dev,after.st_ino,true,created};napi_value obj,v;napi_create_object(e,&obj);if(napi_wrap(e,obj,l,lease_final,nullptr,nullptr)!=napi_ok){close(fd);free(l);return fail(e,"native-package-unqualified");}napi_create_bigint_uint64(e,(uint64_t)l->device,&v);napi_set_named_property(e,obj,"device",v);napi_create_bigint_uint64(e,(uint64_t)l->inode,&v);napi_set_named_property(e,obj,"inode",v);napi_get_boolean(e,created,&v);napi_set_named_property(e,obj,"created",v);napi_property_descriptor properties[]={{"held",nullptr,nullptr,lease_held,nullptr,nullptr,napi_default,nullptr},{"close",nullptr,lease_close,nullptr,nullptr,nullptr,napi_default,nullptr}};napi_define_properties(e,obj,2,properties);return obj;
}
struct Work {napi_async_work work;napi_deferred deferred;napi_ref owner;Child* child;int operation;int error;char* bytes;size_t length;ssize_t count;int status;siginfo_t observed;};
static void execute(napi_env,void* data){Work* w=(Work*)data;w->error=0;if(w->operation==0){do{w->count=read(w->child->output,w->bytes,w->length);}while(w->count<0&&errno==EINTR);if(w->count<0)w->error=errno;}else if(w->operation==1){size_t written=0;while(written<w->length){ssize_t n=write(w->child->input,w->bytes+written,w->length-written);if(n<0&&errno==EINTR)continue;if(n<=0){w->error=errno;break;}written+=(size_t)n;}}else if(w->operation==3){pid_t reaped;do{reaped=waitpid(w->child->pid,&w->status,0);}while(reaped<0&&errno==EINTR);if(reaped!=w->child->pid)w->error=errno?errno:ECHILD;}else{int result;do{result=waitid(P_PID,(id_t)w->child->pid,&w->observed,WEXITED|WNOWAIT);}while(result<0&&errno==EINTR);if(result<0||w->observed.si_pid!=w->child->pid)w->error=errno?errno:ECHILD;}}
static void complete(napi_env e,napi_status status,void* data){Work* w=(Work*)data;napi_value result;if(status==napi_ok&&!w->error&&(w->operation==2||w->operation==4)){w->child->leader=w->observed;w->child->observed=true;}if(status==napi_ok&&!w->error&&w->operation==2){pid_t reaped;do{reaped=waitpid(w->child->pid,&w->status,WNOHANG);}while(reaped<0&&errno==EINTR);if(reaped!=w->child->pid)w->error=ECHILD;else w->child->reaped=true;}if(status==napi_ok&&!w->error&&w->operation==3)w->child->reaped=true;w->child->waiting=false;if(status!=napi_ok||w->error){napi_value message;napi_create_string_utf8(e,"Native child operation unavailable",NAPI_AUTO_LENGTH,&message);napi_create_error(e,nullptr,message,&result);napi_reject_deferred(e,w->deferred,result);}else{if(w->operation==0){napi_create_buffer_copy(e,(size_t)w->count,w->bytes,nullptr,&result);}else if(w->operation==1){result=undefined(e);}else{napi_create_object(e,&result);napi_value code,signal;napi_get_null(e,&code);napi_get_null(e,&signal);if(w->operation==3){if(WIFEXITED(w->status))napi_create_int32(e,WEXITSTATUS(w->status),&code);else if(WIFSIGNALED(w->status))napi_create_int32(e,WTERMSIG(w->status),&signal);}else{if(w->observed.si_code==CLD_EXITED)napi_create_int32(e,w->observed.si_status,&code);else napi_create_int32(e,w->observed.si_status,&signal);}napi_set_named_property(e,result,"exitCode",code);napi_set_named_property(e,result,"signal",signal);}napi_resolve_deferred(e,w->deferred,result);}if(w->bytes){memset(w->bytes,0,w->length);free(w->bytes);}napi_delete_reference(e,w->owner);napi_delete_async_work(e,w->work);free(w);}
static napi_value operation(napi_env e,napi_callback_info info,int operation){size_t n=1;napi_value arg,self;void* data=nullptr;napi_get_cb_info(e,info,&n,&arg,&self,nullptr);if(napi_unwrap(e,self,&data)!=napi_ok||!data)return fail(e,"native-package-unqualified");Child* child=(Child*)data;if((operation==1&&child->input<0)||(operation==0&&child->output<0)||((operation==2||operation==4)&&(child->reaped||child->waiting))||(operation==3&&(!child->observed||child->reaped||child->waiting)))return fail(e,"wait-unavailable");Work* w=(Work*)calloc(1,sizeof(Work));if(!w)return fail(e,"native-package-unqualified");w->child=child;w->operation=operation;if(operation>=2)child->waiting=true;w->length=65536;if(operation==1){bool is_buffer=false;void* input=nullptr;if(n!=1||napi_is_buffer(e,arg,&is_buffer)!=napi_ok||!is_buffer||napi_get_buffer_info(e,arg,&input,&w->length)!=napi_ok||w->length>1048576){free(w);return fail(e,"native-package-unqualified");}w->bytes=(char*)malloc(w->length?w->length:1);if(w->bytes)memcpy(w->bytes,input,w->length);}else if(operation==0)w->bytes=(char*)malloc(w->length);if(operation<2&&!w->bytes){free(w);return fail(e,"native-package-unqualified");}napi_value promise,name;napi_create_promise(e,&w->deferred,&promise);napi_create_reference(e,self,1,&w->owner);napi_create_string_utf8(e,"native-child-operation",NAPI_AUTO_LENGTH,&name);if(napi_create_async_work(e,nullptr,name,execute,complete,w,&w->work)!=napi_ok||napi_queue_async_work(e,w->work)!=napi_ok){child->waiting=false;napi_delete_reference(e,w->owner);free(w->bytes);free(w);return fail(e,"native-package-unqualified");}return promise;}
static napi_value child_read(napi_env e,napi_callback_info i){return operation(e,i,0);}static napi_value child_write(napi_env e,napi_callback_info i){return operation(e,i,1);}static napi_value child_wait(napi_env e,napi_callback_info i){return operation(e,i,2);}static napi_value observe_leader(napi_env e,napi_callback_info i){return operation(e,i,4);}static napi_value reap_leader(napi_env e,napi_callback_info i){return operation(e,i,3);}
static napi_value group_retired(napi_env e,napi_callback_info info){napi_value self,result;Child* c=(Child*)unwrap(e,info,&self);if(!c||!c->process_group||!c->reaped)return fail(e,"wait-unavailable");errno=0;int status=kill(-c->pid,0);napi_get_boolean(e,status<0&&errno==ESRCH,&result);return result;}
static napi_value close_input(napi_env e,napi_callback_info i){napi_value self;Child* c=(Child*)unwrap(e,i,&self);if(!c)return fail(e,"native-package-unqualified");if(c->input>=0){int fd=c->input;c->input=-1;close(fd);}return undefined(e);}
static napi_value signal_child(napi_env e,napi_callback_info i,int signal){napi_value self;Child* c=(Child*)unwrap(e,i,&self);if(!c||c->reaped)return fail(e,"wait-unavailable");if(kill(c->process_group?-c->pid:c->pid,signal)&&errno!=ESRCH)return fail(e,"wait-unavailable");return undefined(e);}
static napi_value terminate(napi_env e,napi_callback_info i){return signal_child(e,i,SIGTERM);}static napi_value kill_child(napi_env e,napi_callback_info i){return signal_child(e,i,SIGKILL);}
static bool private_pipe(int pair[2]){int original[2];if(pipe(original))return false;pair[0]=fcntl(original[0],F_DUPFD_CLOEXEC,4);pair[1]=fcntl(original[1],F_DUPFD_CLOEXEC,4);close(original[0]);close(original[1]);if(pair[0]<0||pair[1]<0){if(pair[0]>=0)close(pair[0]);if(pair[1]>=0)close(pair[1]);pair[0]=pair[1]=-1;return false;}return true;}
static bool canonical_directory(const char* value){char resolved[PATH_MAX];struct stat metadata;return value[0]=='/'&&realpath(value,resolved)&&!strcmp(value,resolved)&&!stat(value,&metadata)&&S_ISDIR(metadata.st_mode);}
static bool canonical_file(const char* value){char resolved[PATH_MAX];struct stat metadata;return value[0]=='/'&&realpath(value,resolved)&&!strcmp(value,resolved)&&!stat(value,&metadata)&&S_ISREG(metadata.st_mode);}
static bool allowed_environment(char* value,int index){const char* names[]={"CODEX_HOME=","HOME=","LANG=","PATH=","TMPDIR="};size_t n=strlen(names[index]);if(strncmp(value,names[index],n)||!value[n])return false;if(index==0||index==1||index==4)return canonical_directory(value+n);if(index==2)return !strcmp(value+n,"en_US.UTF-8");return !strcmp(value+n,"/usr/bin:/bin:/usr/sbin:/sbin");}
static napi_value spawn_supplier(napi_env e,napi_callback_info info){
#if !defined(__APPLE__) || !defined(POSIX_SPAWN_CLOEXEC_DEFAULT)
  return fail(e,"descriptor-closure-unqualified");
#else
  size_t count=7;napi_value args[7];napi_get_cb_info(e,info,&count,args,nullptr,nullptr);char executable[4096],cwd[4096];bool array=false,buffer=false,strict=count==6,process_group=false;uint32_t length=0,environment_length=0;void* secret=nullptr;size_t secret_length=0;if((count!=3&&count!=6)||!string_arg(e,args[0],executable,sizeof(executable))||executable[0]!='/'||napi_is_array(e,args[1],&array)!=napi_ok||!array||napi_get_array_length(e,args[1],&length)!=napi_ok||length>128||napi_is_buffer(e,args[2],&buffer)!=napi_ok||!buffer||napi_get_buffer_info(e,args[2],&secret,&secret_length)!=napi_ok||secret_length!=32)return fail(e,"spawn-failed");
  char* environment[6]={nullptr};
  if(strict){array=false;if(!canonical_file(executable)||!string_arg(e,args[3],cwd,sizeof(cwd))||!canonical_directory(cwd)||napi_is_array(e,args[4],&array)!=napi_ok||!array||napi_get_array_length(e,args[4],&environment_length)!=napi_ok||environment_length!=5||napi_get_value_bool(e,args[5],&process_group)!=napi_ok||!process_group)return fail(e,"spawn-failed");for(uint32_t j=0;j<environment_length;j++){environment[j]=(char*)malloc(4097);napi_value v;napi_get_element(e,args[4],j,&v);if(!environment[j]||!string_arg(e,v,environment[j],4097)||!allowed_environment(environment[j],(int)j)){for(uint32_t k=0;k<=j;k++)free(environment[k]);return fail(e,"spawn-failed");}}}
  char* argv[130]={};argv[0]=executable;bool valid=true;for(uint32_t j=0;j<length;j++){argv[j+1]=(char*)malloc(4097);napi_value v;napi_get_element(e,args[1],j,&v);if(!argv[j+1]||!string_arg(e,v,argv[j+1],4097)){valid=false;break;}}
  int pipes[3][2]={{-1,-1},{-1,-1},{-1,-1}};posix_spawn_file_actions_t actions;posix_spawnattr_t attr;bool have_actions=false,have_attr=false;pid_t pid=-1;int error=0;
  if(!valid)error=EINVAL;for(int j=0;j<3&&!error;j++)if(!private_pipe(pipes[j]))error=errno;
  // Bootstrap is exactly 32 bytes and EOF, delivered only on the private pipe.
  if(!error){ssize_t wrote;do{wrote=write(pipes[2][1],secret,32);}while(wrote<0&&errno==EINTR);if(wrote!=32)error=EIO;close(pipes[2][1]);pipes[2][1]=-1;}
  if(!error){error=posix_spawn_file_actions_init(&actions);have_actions=!error;}if(!error){error=posix_spawnattr_init(&attr);have_attr=!error;}
  if(!error)error=posix_spawnattr_setflags(&attr,POSIX_SPAWN_CLOEXEC_DEFAULT|(process_group?POSIX_SPAWN_SETPGROUP:0));if(!error&&process_group)error=posix_spawnattr_setpgroup(&attr,0);
  if(!error&&strict)error=posix_spawn_file_actions_addchdir_np(&actions,cwd);
  if(!error)error=posix_spawn_file_actions_adddup2(&actions,pipes[0][0],0);if(!error)error=posix_spawn_file_actions_adddup2(&actions,pipes[1][1],1);if(!error)error=posix_spawn_file_actions_addopen(&actions,2,"/dev/null",O_WRONLY,0);if(!error)error=posix_spawn_file_actions_adddup2(&actions,pipes[2][0],3);
  // Explicitly close every pipe source after mapping. CLOEXEC_DEFAULT closes all
  // unmentioned descriptors, including the opaque lock. No enumeration/PID proof.
  for(int j=0;j<3&&!error;j++)for(int k=0;k<2&&!error;k++)if(pipes[j][k]>=4)error=posix_spawn_file_actions_addclose(&actions,pipes[j][k]);
  char* empty_environment[]={nullptr};if(!error)error=posix_spawn(&pid,executable,&actions,&attr,argv,strict?environment:empty_environment);if(have_actions)posix_spawn_file_actions_destroy(&actions);if(have_attr)posix_spawnattr_destroy(&attr);for(uint32_t j=0;j<length;j++)free(argv[j+1]);for(uint32_t j=0;j<environment_length;j++)free(environment[j]);
  if(error){for(int j=0;j<3;j++)for(int k=0;k<2;k++)if(pipes[j][k]>=0)close(pipes[j][k]);return fail(e,"spawn-failed");}
  close(pipes[0][0]);close(pipes[1][1]);close(pipes[2][0]);Child* child=(Child*)calloc(1,sizeof(Child));if(!child){close(pipes[0][1]);close(pipes[1][0]);kill(process_group?-pid:pid,SIGKILL);while(waitpid(pid,nullptr,0)<0&&errno==EINTR){}return fail(e,"spawn-failed");}*child={pid,pipes[0][1],pipes[1][0],false,false,false,process_group,{}};napi_value object,pid_value;napi_create_object(e,&object);napi_wrap(e,object,child,child_final,nullptr,nullptr);napi_create_int32(e,pid,&pid_value);napi_set_named_property(e,object,"pid",pid_value);napi_property_descriptor methods[]={{"read",nullptr,child_read,nullptr,nullptr,nullptr,napi_default,nullptr},{"write",nullptr,child_write,nullptr,nullptr,nullptr,napi_default,nullptr},{"wait",nullptr,child_wait,nullptr,nullptr,nullptr,napi_default,nullptr},{"observeLeader",nullptr,observe_leader,nullptr,nullptr,nullptr,napi_default,nullptr},{"reapLeader",nullptr,reap_leader,nullptr,nullptr,nullptr,napi_default,nullptr},{"groupRetired",nullptr,group_retired,nullptr,nullptr,nullptr,napi_default,nullptr},{"closeInput",nullptr,close_input,nullptr,nullptr,nullptr,napi_default,nullptr},{"terminate",nullptr,terminate,nullptr,nullptr,nullptr,napi_default,nullptr},{"kill",nullptr,kill_child,nullptr,nullptr,nullptr,napi_default,nullptr}};napi_define_properties(e,object,9,methods);return object;
#endif
}
enum hx_event_kind { HX_ADMITTED=1,HX_INVALIDATED=2,HX_OPEN=3,HX_FINISH=4,HX_PING=5,HX_CHALLENGE=6,HX_GRANT=7,HX_PONG=8,HX_CLOSED=9 };
struct hx_event { hx_event_kind kind;uint64_t token,sequence;bool ok;char connection_id[97],request_id[97],generation[97],reason[40];uint8_t first[32],second[32]; };
struct hx_port;
extern "C" const char* hx_service_name();
extern "C" hx_port* hx_create(bool,const char*,uid_t,void(*)(void*,hx_event*),void*,int*);
extern "C" int hx_server_challenge(hx_port*,uint64_t,const char*,const uint8_t[32],const char*);
extern "C" int hx_server_grant(hx_port*,uint64_t,const char*,const uint8_t[32],const char*);
extern "C" int hx_client_pong(hx_port*,uint64_t,const char*,uint64_t);
extern "C" int hx_client_open(hx_port*,const char*);
extern "C" int hx_client_finish(hx_port*,const char*,const uint8_t[32],const uint8_t[32]);
extern "C" int hx_server_ping(hx_port*,const char*,const char*,uint64_t);
extern "C" void hx_close_peer(hx_port*,const char*);
extern "C" void hx_close(hx_port*);

struct HostPort {hx_port* native;napi_threadsafe_function events;napi_deferred close_deferred;napi_ref close_promise;std::atomic<bool> closing{false},delivery_failed{false},terminal_queued{false},terminal_complete{false},tsfn_released{false};std::atomic<unsigned> references{0},ordinary_queued{0};};
static bool exact_buffer(napi_env e,napi_value value,uint8_t out[32]){bool buffer=false;void* bytes=nullptr;size_t length=0;if(napi_is_buffer(e,value,&buffer)!=napi_ok||!buffer||napi_get_buffer_info(e,value,&bytes,&length)!=napi_ok||length!=32)return false;memcpy(out,bytes,32);return true;}
static bool opaque_arg(napi_env e,napi_value value,char out[97]){if(!string_arg(e,value,out,97)||!out[0])return false;for(size_t i=0;out[i];i++)if((unsigned char)out[i]<0x21||(unsigned char)out[i]>0x7e)return false;return true;}
static bool uuid_arg(napi_env e,napi_value value,char out[97]){if(!opaque_arg(e,value,out)||strlen(out)!=36)return false;for(size_t i=0;i<36;i++){if(i==8||i==13||i==18||i==23){if(out[i]!='-')return false;}else if(!((out[i]>='0'&&out[i]<='9')||(out[i]>='a'&&out[i]<='f')))return false;}return true;}
static bool uint64_arg(napi_env e,napi_value value,uint64_t* out){napi_valuetype type;if(napi_typeof(e,value,&type)!=napi_ok)return false;if(type==napi_bigint){bool lossless=false;return napi_get_value_bigint_uint64(e,value,out,&lossless)==napi_ok&&lossless;}double number=0;return type==napi_number&&napi_get_value_double(e,value,&number)==napi_ok&&number>=0&&number<=9007199254740991.0&&number==(uint64_t)number&&(*out=(uint64_t)number,true);}
static napi_value host_error(napi_env e,const char* code){napi_value message,error;napi_create_string_utf8(e,"Host XPC unavailable",NAPI_AUTO_LENGTH,&message);napi_create_error(e,nullptr,message,&error);napi_create_string_utf8(e,code,NAPI_AUTO_LENGTH,&message);napi_set_named_property(e,error,"code",message);napi_throw(e,error);return nullptr;}
static void release_host(HostPort* host){if(host->references.fetch_sub(1,std::memory_order_acq_rel)==1)delete host;}
static void release_tsfn_once(HostPort* host){if(!host->tsfn_released.exchange(true))napi_release_threadsafe_function(host->events,napi_tsfn_abort);}
static void host_tsfn_final(napi_env,void*,void* data){release_host((HostPort*)data);}
static void set_string(napi_env e,napi_value object,const char* key,const char* value){napi_value text;napi_create_string_utf8(e,value,NAPI_AUTO_LENGTH,&text);napi_set_named_property(e,object,key,text);}
static void set_bigint(napi_env e,napi_value object,const char* key,uint64_t value){napi_value number;napi_create_bigint_uint64(e,value,&number);napi_set_named_property(e,object,key,number);}
static void settle_host_close(napi_env e,HostPort* host){if(!host->close_deferred)return;napi_value result;if(host->delivery_failed.load()){napi_value message,code;napi_create_string_utf8(e,"Host XPC unavailable",NAPI_AUTO_LENGTH,&message);napi_create_error(e,nullptr,message,&result);napi_create_string_utf8(e,"delivery-unavailable",NAPI_AUTO_LENGTH,&code);napi_set_named_property(e,result,"code",code);napi_reject_deferred(e,host->close_deferred,result);}else{napi_get_undefined(e,&result);napi_resolve_deferred(e,host->close_deferred,result);}host->close_deferred=nullptr;}
static void call_host_js(napi_env e,napi_value callback,void* context,void* data){
  HostPort* host=(HostPort*)context;hx_event* event=(hx_event*)data;
  if(event->kind!=HX_CLOSED)host->ordinary_queued.fetch_sub(1);
  if(!e){memset(event,0,sizeof(*event));delete event;release_tsfn_once(host);return;}
  napi_value object;napi_create_object(e,&object);
  const char* type=event->kind==HX_ADMITTED?"admitted":event->kind==HX_INVALIDATED?"invalidated":event->kind==HX_OPEN?"open":event->kind==HX_FINISH?"finish":event->kind==HX_PING?"ping":event->kind==HX_CHALLENGE?"challenge":event->kind==HX_GRANT?"grant":event->kind==HX_PONG?"pong":"closed";
  set_string(e,object,"type",type);if(event->connection_id[0])set_string(e,object,"connectionId",event->connection_id);if(event->request_id[0])set_string(e,object,"requestId",event->request_id);if(event->generation[0])set_string(e,object,"generation",event->generation);if(event->reason[0])set_string(e,object,"reason",event->reason);if(event->token)set_bigint(e,object,"replyToken",event->token);if(event->kind==HX_PING||event->kind==HX_PONG)set_bigint(e,object,"sequence",event->sequence);
  if(event->kind>=HX_CHALLENGE&&event->kind<=HX_PONG){napi_value ok;napi_get_boolean(e,event->ok,&ok);napi_set_named_property(e,object,"ok",ok);}
  napi_value bytes;if(event->kind==HX_FINISH){napi_create_buffer_copy(e,32,event->first,nullptr,&bytes);napi_set_named_property(e,object,"hostNonce",bytes);napi_create_buffer_copy(e,32,event->second,nullptr,&bytes);napi_set_named_property(e,object,"proof",bytes);}else if(event->kind==HX_CHALLENGE){napi_create_buffer_copy(e,32,event->first,nullptr,&bytes);napi_set_named_property(e,object,"challenge",bytes);}else if(event->kind==HX_GRANT){napi_create_buffer_copy(e,32,event->first,nullptr,&bytes);napi_set_named_property(e,object,"bearer",bytes);}
  napi_value global,result;napi_get_global(e,&global);if((event->kind!=HX_CLOSED&&!host->closing.load())||(event->kind==HX_CLOSED&&host->delivery_failed.load()))napi_call_function(e,global,callback,1,&object,&result);
  if(event->kind==HX_CLOSED){host->terminal_complete=true;settle_host_close(e,host);release_tsfn_once(host);}
  memset(event,0,sizeof(*event));delete event;
}
static void deliver_host_event(void* context,hx_event* event){
  HostPort* host=(HostPort*)context;
  if(event->kind==HX_CLOSED){if(host->terminal_queued.exchange(true)){memset(event,0,sizeof(*event));delete event;return;}napi_status terminal=napi_call_threadsafe_function(host->events,event,napi_tsfn_nonblocking);if(terminal!=napi_ok){memset(event,0,sizeof(*event));delete event;release_tsfn_once(host);}return;}
  unsigned queued=host->ordinary_queued.fetch_add(1);napi_status status=queued<63?napi_call_threadsafe_function(host->events,event,napi_tsfn_nonblocking):napi_queue_full;
  if(status!=napi_ok){host->ordinary_queued.fetch_sub(1);host->delivery_failed=true;bool was=host->closing.exchange(true);memset(event,0,sizeof(*event));delete event;if(!was)hx_close(host->native);}
}
static HostPort* unwrap_host(napi_env e,napi_callback_info info,napi_value* self,size_t* argc,napi_value* argv){void* data=nullptr;napi_get_cb_info(e,info,argc,argv,self,nullptr);if(napi_unwrap(e,*self,&data)!=napi_ok||!data)return nullptr;return (HostPort*)data;}
static void host_final(napi_env e,void* data,void*){HostPort* host=(HostPort*)data;if(!host->closing.exchange(true))hx_close(host->native);if(host->close_promise){napi_delete_reference(e,host->close_promise);host->close_promise=nullptr;}release_host(host);}
static napi_value host_close(napi_env e,napi_callback_info info){napi_value self;size_t n=0;HostPort* host=unwrap_host(e,info,&self,&n,nullptr);if(!host)return host_error(e,"host-xpc-unavailable");if(host->close_promise){napi_value promise;napi_get_reference_value(e,host->close_promise,&promise);return promise;}napi_value promise;napi_create_promise(e,&host->close_deferred,&promise);napi_create_reference(e,promise,1,&host->close_promise);if(host->terminal_complete.load())settle_host_close(e,host);else if(!host->closing.exchange(true))hx_close(host->native);return promise;}
static napi_value host_call(napi_env e,napi_callback_info info,int operation){napi_value self,args[4];size_t n=4;HostPort* host=unwrap_host(e,info,&self,&n,args);if(!host||host->closing.load())return host_error(e,"host-xpc-closed");char id[97]={},request[97]={},generation[97]={};uint64_t token=0,number=0;uint8_t first[32]={},second[32]={};int result=EINVAL;
  if(operation<=2){if((operation<2&&n!=4)||(operation==2&&n!=3)||!uint64_arg(e,args[0],&token)||!opaque_arg(e,args[1],request))return host_error(e,"host-xpc-frame-invalid");if(operation<2&&(!exact_buffer(e,args[2],first)||!uuid_arg(e,args[3],generation)))return host_error(e,"host-xpc-frame-invalid");if(operation==2&&!uint64_arg(e,args[2],&number))return host_error(e,"host-xpc-frame-invalid");result=operation==0?hx_server_challenge(host->native,token,request,first,generation):operation==1?hx_server_grant(host->native,token,request,first,generation):hx_client_pong(host->native,token,request,number);
  }else if(operation==3){if(n!=1||!opaque_arg(e,args[0],request))return host_error(e,"host-xpc-frame-invalid");result=hx_client_open(host->native,request);
  }else if(operation==4){if(n!=3||!opaque_arg(e,args[0],request)||!exact_buffer(e,args[1],first)||!exact_buffer(e,args[2],second))return host_error(e,"host-xpc-frame-invalid");result=hx_client_finish(host->native,request,first,second);
  }else if(operation==5){if(n!=3||!opaque_arg(e,args[0],id)||!opaque_arg(e,args[1],request)||!uint64_arg(e,args[2],&number))return host_error(e,"host-xpc-frame-invalid");result=hx_server_ping(host->native,id,request,number);
  }else{if(n!=1||!opaque_arg(e,args[0],id))return host_error(e,"host-xpc-frame-invalid");hx_close_peer(host->native,id);result=0;}
  memset(first,0,sizeof(first));memset(second,0,sizeof(second));if(result)return host_error(e,result==EBUSY?"host-xpc-busy":"host-xpc-unavailable");return undefined(e);
}
static napi_value server_challenge(napi_env e,napi_callback_info i){return host_call(e,i,0);}static napi_value server_grant(napi_env e,napi_callback_info i){return host_call(e,i,1);}static napi_value client_pong(napi_env e,napi_callback_info i){return host_call(e,i,2);}static napi_value client_open(napi_env e,napi_callback_info i){return host_call(e,i,3);}static napi_value client_finish(napi_env e,napi_callback_info i){return host_call(e,i,4);}static napi_value server_ping(napi_env e,napi_callback_info i){return host_call(e,i,5);}static napi_value close_peer(napi_env e,napi_callback_info i){return host_call(e,i,6);}
static napi_value create_host_port(napi_env e,napi_callback_info info){size_t n=4;napi_value args[4];napi_get_cb_info(e,info,&n,args,nullptr,nullptr);bool server=false;uint32_t euid=0;char requirement[4097];napi_valuetype type;if(n!=4||napi_get_value_bool(e,args[0],&server)!=napi_ok||!string_arg(e,args[1],requirement,sizeof(requirement))||!requirement[0]||napi_get_value_uint32(e,args[2],&euid)!=napi_ok||napi_typeof(e,args[3],&type)!=napi_ok||type!=napi_function)return host_error(e,"host-xpc-config-invalid");HostPort* host=new HostPort{};host->native=nullptr;host->events=nullptr;host->close_deferred=nullptr;host->close_promise=nullptr;host->closing=false;host->references=2;napi_value name;napi_create_string_utf8(e,"chirality-host-xpc-events",NAPI_AUTO_LENGTH,&name);if(napi_create_threadsafe_function(e,args[3],nullptr,name,64,1,host,host_tsfn_final,host,call_host_js,&host->events)!=napi_ok){delete host;return host_error(e,"host-xpc-unavailable");}int error=0;host->native=hx_create(server,requirement,(uid_t)euid,deliver_host_event,host,&error);if(!host->native){host->closing=true;napi_release_threadsafe_function(host->events,napi_tsfn_abort);release_host(host);return host_error(e,error?"host-xpc-requirement-invalid":"host-xpc-unavailable");}napi_value object;napi_create_object(e,&object);if(napi_wrap(e,object,host,host_final,nullptr,nullptr)!=napi_ok){host->closing=true;hx_close(host->native);release_host(host);return host_error(e,"host-xpc-unavailable");}napi_property_descriptor methods[]={{"serverChallenge",nullptr,server_challenge,nullptr,nullptr,nullptr,napi_default,nullptr},{"serverGrant",nullptr,server_grant,nullptr,nullptr,nullptr,napi_default,nullptr},{"clientPong",nullptr,client_pong,nullptr,nullptr,nullptr,napi_default,nullptr},{"clientOpen",nullptr,client_open,nullptr,nullptr,nullptr,napi_default,nullptr},{"clientFinish",nullptr,client_finish,nullptr,nullptr,nullptr,napi_default,nullptr},{"serverPing",nullptr,server_ping,nullptr,nullptr,nullptr,napi_default,nullptr},{"closeConnection",nullptr,close_peer,nullptr,nullptr,nullptr,napi_default,nullptr},{"close",nullptr,host_close,nullptr,nullptr,nullptr,napi_default,nullptr}};napi_define_properties(e,object,8,methods);return object;}
static napi_value init(napi_env e,napi_value exports){napi_property_descriptor methods[]={{"acquire",nullptr,acquire,nullptr,nullptr,nullptr,napi_default,nullptr},{"spawnSupplier",nullptr,spawn_supplier,nullptr,nullptr,nullptr,napi_default,nullptr},{"createHostXpcPort",nullptr,create_host_port,nullptr,nullptr,nullptr,napi_default,nullptr}};napi_define_properties(e,exports,3,methods);napi_value service;napi_create_string_utf8(e,hx_service_name(),NAPI_AUTO_LENGTH,&service);napi_set_named_property(e,exports,"hostXpcService",service);return exports;}
NAPI_MODULE(NODE_GYP_MODULE_NAME,init)
