#include <xpc/xpc.h>
#include <dispatch/dispatch.h>
#include <sys/types.h>
#include <map>
#include <string>
#include <cstring>
#include <cstdlib>
#include <cerrno>
#include <atomic>

// Public-XPC-only transport. Code identity is enforced by XPC before activation;
// no PID or private audit-token surface participates in authority.
static constexpr const char *kService="com.chirality.app.runtime.account-host";
static constexpr size_t kMaxFrameBytes=4096;
static constexpr size_t kMaxIdentifierBytes=96;

enum hx_event_kind { HX_ADMITTED=1,HX_INVALIDATED=2,HX_OPEN=3,HX_FINISH=4,HX_PING=5,HX_CHALLENGE=6,HX_GRANT=7,HX_PONG=8,HX_CLOSED=9 };
struct hx_event { hx_event_kind kind;uint64_t token,sequence;bool ok;char connection_id[97],request_id[97],generation[97],reason[40];uint8_t first[32],second[32]; };
typedef void (*hx_event_fn)(void *,hx_event *);
struct hx_peer { xpc_connection_t connection;bool invalidated;unsigned char ceremony_phase;std::string generation; };
struct hx_pending_reply { xpc_connection_t connection;xpc_object_t reply;hx_event_kind request_kind;std::string request_id,connection_id; };
struct hx_port {
  dispatch_queue_t queue;xpc_connection_t endpoint;std::map<std::string,hx_peer> peers;std::map<uint64_t,hx_pending_reply> replies;
  hx_event_fn deliver;void *context;uid_t expected_euid;bool server,closing,client_invalidated;uint64_t next_connection,next_token;std::string client_generation;std::atomic<unsigned> references{1};
};
static void retain_port(hx_port *port){port->references.fetch_add(1,std::memory_order_relaxed);}
static void release_port(hx_port *port){if(port->references.fetch_sub(1,std::memory_order_acq_rel)==1){dispatch_release(port->queue);delete port;}}
static void connection_finalizer(void *context){release_port((hx_port *)context);}
static void bind_lifetime(xpc_connection_t connection,hx_port *port){retain_port(port);xpc_connection_set_context(connection,port);xpc_connection_set_finalizer_f(connection,connection_finalizer);}

static bool bounded_string(xpc_object_t object,const char *key,char out[97]){const char *value=xpc_dictionary_get_string(object,key);if(!value)return false;size_t n=strnlen(value,97);if(!n||n>96)return false;for(size_t i=0;i<n;i++)if((unsigned char)value[i]<0x21||(unsigned char)value[i]>0x7e)return false;memcpy(out,value,n);out[n]=0;return true;}
static bool bounded_literal(xpc_object_t object,const char *key,const char *expected){const char *value=xpc_dictionary_get_string(object,key);if(!value)return false;size_t n=strlen(expected);return strnlen(value,n+1)==n&&!memcmp(value,expected,n);}
static bool array_literal(xpc_object_t array,size_t index,const char *expected){const char *value=xpc_array_get_string(array,index);if(!value)return false;size_t n=strlen(expected);return strnlen(value,n+1)==n&&!memcmp(value,expected,n);}
static size_t dictionary_count(xpc_object_t object){__block size_t count=0;xpc_dictionary_apply(object,^(const char *,xpc_object_t){count++;return true;});return count;}
static bool uint64_field(xpc_object_t object,const char *key,uint64_t *out){xpc_object_t value=xpc_dictionary_get_value(object,key);if(!value||xpc_get_type(value)!=XPC_TYPE_UINT64)return false;*out=xpc_uint64_get_value(value);return true;}
static bool canonical_uuid(const char *value){if(!value||strlen(value)!=36)return false;for(size_t i=0;i<36;i++){if(i==8||i==13||i==18||i==23){if(value[i]!='-')return false;}else if(!((value[i]>='0'&&value[i]<='9')||(value[i]>='a'&&value[i]<='f')))return false;}return true;}
static void reason_for(xpc_object_t error,char out[40]){const char *reason="peer-invalidated";if(error==XPC_ERROR_CONNECTION_INTERRUPTED)reason="peer-interrupted";else if(error==XPC_ERROR_PEER_CODE_SIGNING_REQUIREMENT)reason="peer-requirement-rejected";strlcpy(out,reason,40);}
static void emit(hx_port *port,hx_event *event){if(port->closing&&event->kind!=HX_INVALIDATED&&event->kind!=HX_CLOSED){memset(event,0,sizeof(*event));delete event;return;}port->deliver(port->context,event);}
static bool base(xpc_object_t value,const char *type,hx_event *event){uint64_t version=0;return xpc_get_type(value)==XPC_TYPE_DICTIONARY&&uint64_field(value,"v",&version)&&version==1&&bounded_literal(value,"type",type)&&bounded_string(value,"requestId",event->request_id);}
static xpc_object_t message(const char *type,const char *request_id){xpc_object_t value=xpc_dictionary_create_empty();xpc_dictionary_set_uint64(value,"v",1);xpc_dictionary_set_string(value,"type",type);xpc_dictionary_set_string(value,"requestId",request_id);return value;}
static void invalidate(hx_port *port,const std::string &id,const char *reason){auto found=port->peers.find(id);if(found==port->peers.end()||found->second.invalidated)return;found->second.invalidated=true;found->second.ceremony_phase=0;for(auto reply=port->replies.begin();reply!=port->replies.end();){if(reply->second.connection==found->second.connection){xpc_release(reply->second.reply);xpc_release(reply->second.connection);reply=port->replies.erase(reply);}else ++reply;}auto *event=new hx_event{};event->kind=HX_INVALIDATED;strlcpy(event->connection_id,id.c_str(),97);strlcpy(event->reason,reason,40);emit(port,event);xpc_connection_cancel(found->second.connection);xpc_release(found->second.connection);port->peers.erase(found);}
static void reject_client(hx_port *port,const char *reason){if(port->closing||port->client_invalidated)return;port->client_invalidated=true;port->client_generation.clear();auto *event=new hx_event{};event->kind=HX_INVALIDATED;strlcpy(event->reason,reason,40);emit(port,event);xpc_connection_cancel(port->endpoint);}

static void server_message(hx_port *port,const std::string &id,xpc_object_t value){
  if(xpc_get_type(value)==XPC_TYPE_ERROR){char reason[40];reason_for(value,reason);invalidate(port,id,reason);return;}
  if(xpc_get_type(value)!=XPC_TYPE_DICTIONARY){invalidate(port,id,"protocol-invalid");return;}
  auto peer=port->peers.find(id);if(peer==port->peers.end())return;size_t count=dictionary_count(value);if(count!=3&&count!=5){invalidate(port,id,"protocol-invalid");return;}auto *event=new hx_event{};
  if(count==3&&base(value,"ceremony.open",event)&&peer->second.ceremony_phase==0){event->kind=HX_OPEN;peer->second.ceremony_phase=1;}
  else if(count==5&&base(value,"ceremony.finish",event)&&peer->second.ceremony_phase==1){size_t a=0,b=0;const void *nonce=xpc_dictionary_get_data(value,"hostNonce",&a),*proof=xpc_dictionary_get_data(value,"proof",&b);if(!nonce||!proof||a!=32||b!=32){delete event;invalidate(port,id,"protocol-invalid");return;}event->kind=HX_FINISH;memcpy(event->first,nonce,32);memcpy(event->second,proof,32);peer->second.ceremony_phase=2;}
  else{delete event;invalidate(port,id,"protocol-invalid");return;}
  xpc_object_t reply=xpc_dictionary_create_reply(value);if(!reply){delete event;invalidate(port,id,"protocol-invalid");return;}event->token=port->next_token++;strlcpy(event->connection_id,id.c_str(),97);xpc_retain(peer->second.connection);port->replies.emplace(event->token,hx_pending_reply{peer->second.connection,reply,event->kind,event->request_id,id});emit(port,event);
}
static void accept(hx_port *port,xpc_connection_t peer){if(port->closing||xpc_connection_get_euid(peer)!=port->expected_euid){xpc_connection_cancel(peer);return;}std::string id="host-"+std::to_string(port->next_connection++);xpc_retain(peer);bind_lifetime(peer,port);port->peers.emplace(id,hx_peer{peer,false,0,{}});xpc_connection_set_target_queue(peer,port->queue);xpc_connection_set_event_handler(peer,^(xpc_object_t value){server_message(port,id,value);});xpc_connection_activate(peer);auto *event=new hx_event{};event->kind=HX_ADMITTED;strlcpy(event->connection_id,id.c_str(),97);emit(port,event);}
static bool client_peer_ok(hx_port *port){return xpc_connection_get_euid(port->endpoint)==port->expected_euid;}
static void client_message(hx_port *port,xpc_object_t value){if(xpc_get_type(value)==XPC_TYPE_ERROR){char reason[40];reason_for(value,reason);reject_client(port,reason);return;}if(!client_peer_ok(port)){reject_client(port,"peer-invalidated");return;}auto *event=new hx_event{};if(xpc_get_type(value)!=XPC_TYPE_DICTIONARY||dictionary_count(value)!=4||!base(value,"lease.ping",event)||!uint64_field(value,"sequence",&event->sequence)){delete event;reject_client(port,"protocol-invalid");return;}event->kind=HX_PING;xpc_object_t reply=xpc_dictionary_create_reply(value);if(!reply){delete event;reject_client(port,"protocol-invalid");return;}event->token=port->next_token++;xpc_retain(port->endpoint);port->replies.emplace(event->token,hx_pending_reply{port->endpoint,reply,HX_PING,event->request_id,{}});emit(port,event);}
static void client_reply(hx_port *port,xpc_object_t value,hx_event_kind kind,const char *request_id,uint64_t expected_sequence,const char *peer_id){
  if(port->closing)return;auto *event=new hx_event{};event->kind=kind;strlcpy(event->request_id,request_id,97);if(peer_id)strlcpy(event->connection_id,peer_id,97);
  if(xpc_get_type(value)==XPC_TYPE_ERROR){char failure_reason[40];reason_for(value,failure_reason);event->ok=false;strlcpy(event->reason,failure_reason,40);emit(port,event);if(peer_id)invalidate(port,peer_id,failure_reason);else reject_client(port,failure_reason);return;}
  size_t expected_count=kind==HX_CHALLENGE?5:kind==HX_GRANT?6:4;bool dictionary=xpc_get_type(value)==XPC_TYPE_DICTIONARY;size_t count=dictionary?dictionary_count(value):0;char echoed[97];event->ok=dictionary&&count==expected_count&&(port->server||client_peer_ok(port))&&bounded_string(value,"requestId",echoed)&&!strcmp(echoed,request_id);
  if(kind==HX_CHALLENGE){size_t n=0;const void *challenge=event->ok?xpc_dictionary_get_data(value,"challenge",&n):nullptr;event->ok=event->ok&&bounded_literal(value,"type","ceremony.challenge")&&challenge&&n==32&&bounded_string(value,"generation",event->generation)&&canonical_uuid(event->generation);if(event->ok){port->client_generation=event->generation;memcpy(event->first,challenge,32);}}
  else if(kind==HX_GRANT){size_t n=0;const void *bearer=event->ok?xpc_dictionary_get_data(value,"bearer",&n):nullptr;xpc_object_t scopes=event->ok?xpc_dictionary_get_value(value,"scopes"):nullptr;bool array=scopes&&xpc_get_type(scopes)==XPC_TYPE_ARRAY;event->ok=event->ok&&bounded_literal(value,"type","ceremony.grant")&&bearer&&n==32&&bounded_string(value,"generation",event->generation)&&canonical_uuid(event->generation)&&event->generation==port->client_generation&&array&&xpc_array_get_count(scopes)==2&&array_literal(scopes,0,"account:read")&&array_literal(scopes,1,"account:control");if(event->ok){port->client_generation.clear();memcpy(event->first,bearer,32);}}
  else{event->ok=event->ok&&uint64_field(value,"sequence",&event->sequence)&&bounded_literal(value,"type","lease.pong")&&event->sequence==expected_sequence;}
  const bool ok=event->ok;if(!ok)strlcpy(event->reason,"protocol-invalid",40);emit(port,event);if(!ok){if(peer_id)invalidate(port,peer_id,"protocol-invalid");else reject_client(port,"protocol-invalid");}
}

extern "C" const char *hx_service_name(){return kService;}
extern "C" hx_port *hx_create(bool server,const char *requirement,uid_t expected_euid,hx_event_fn deliver,void *context,int *error_out){
  if(error_out)*error_out=EINVAL;if(!requirement||!requirement[0]||strnlen(requirement,kMaxFrameBytes+1)>kMaxFrameBytes||!deliver)return nullptr;
  auto *port=new hx_port{};port->deliver=deliver;port->context=context;port->expected_euid=expected_euid;port->server=server;port->next_connection=1;port->next_token=1;port->queue=dispatch_queue_create("com.chirality.runtime.account-host.serial",DISPATCH_QUEUE_SERIAL);port->endpoint=xpc_connection_create_mach_service(kService,port->queue,server?XPC_CONNECTION_MACH_SERVICE_LISTENER:0);if(!port->endpoint){release_port(port);return nullptr;}bind_lifetime(port->endpoint,port);
  int configured=xpc_connection_set_peer_code_signing_requirement(port->endpoint,requirement);if(configured){xpc_connection_set_event_handler(port->endpoint,^(xpc_object_t){});xpc_connection_activate(port->endpoint);xpc_connection_cancel(port->endpoint);xpc_release(port->endpoint);release_port(port);if(error_out)*error_out=configured;return nullptr;}
  if(server)xpc_connection_set_event_handler(port->endpoint,^(xpc_object_t value){if(xpc_get_type(value)==XPC_TYPE_CONNECTION)accept(port,(xpc_connection_t)value);});else xpc_connection_set_event_handler(port->endpoint,^(xpc_object_t value){client_message(port,value);});
  xpc_connection_activate(port->endpoint);if(error_out)*error_out=0;return port;
}
static int server_reply(hx_port *port,uint64_t token,const char *type,const char *request_id,const uint8_t *bytes,const char *generation,uint64_t){if(!port||!port->server||port->closing||!request_id||!generation||!canonical_uuid(generation))return EINVAL;__block int result=ENOENT;dispatch_sync(port->queue,^{auto found=port->replies.find(token);if(found==port->replies.end())return;hx_pending_reply pending=found->second;port->replies.erase(found);hx_event_kind expected=!strcmp(type,"ceremony.challenge")?HX_OPEN:HX_FINISH;auto peer=port->peers.find(pending.connection_id);bool generation_ok=peer!=port->peers.end()&&((expected==HX_OPEN&&peer->second.ceremony_phase==1&&peer->second.generation.empty())||(expected==HX_FINISH&&peer->second.ceremony_phase==2&&peer->second.generation==generation));if(pending.request_kind!=expected||pending.request_id!=request_id||!generation_ok){xpc_release(pending.reply);xpc_release(pending.connection);result=EPROTO;invalidate(port,pending.connection_id,"protocol-invalid");return;}if(expected==HX_OPEN)peer->second.generation=generation;xpc_object_t reply=pending.reply;xpc_dictionary_set_uint64(reply,"v",1);xpc_dictionary_set_string(reply,"type",type);xpc_dictionary_set_string(reply,"requestId",request_id);if(expected==HX_OPEN){xpc_dictionary_set_data(reply,"challenge",bytes,32);xpc_dictionary_set_string(reply,"generation",generation);}else{xpc_dictionary_set_data(reply,"bearer",bytes,32);xpc_dictionary_set_string(reply,"generation",generation);xpc_object_t scopes=xpc_array_create_empty();xpc_array_set_string(scopes,XPC_ARRAY_APPEND,"account:read");xpc_array_set_string(scopes,XPC_ARRAY_APPEND,"account:control");xpc_dictionary_set_value(reply,"scopes",scopes);xpc_release(scopes);}xpc_connection_send_message(pending.connection,reply);result=0;xpc_release(reply);xpc_release(pending.connection);});return result;}
extern "C" int hx_server_challenge(hx_port *p,uint64_t t,const char *r,const uint8_t c[32],const char *g){return server_reply(p,t,"ceremony.challenge",r,c,g,0);}
extern "C" int hx_server_grant(hx_port *p,uint64_t t,const char *r,const uint8_t b[32],const char *g){return server_reply(p,t,"ceremony.grant",r,b,g,0);}
extern "C" int hx_client_pong(hx_port *port,uint64_t token,const char *request_id,uint64_t sequence){if(!port||port->server||port->closing||!request_id)return EINVAL;__block int result=ENOENT;dispatch_sync(port->queue,^{auto found=port->replies.find(token);if(found==port->replies.end())return;hx_pending_reply pending=found->second;port->replies.erase(found);if(pending.request_kind!=HX_PING||pending.request_id!=request_id){xpc_release(pending.reply);xpc_release(pending.connection);result=EPROTO;reject_client(port,"protocol-invalid");return;}xpc_object_t reply=pending.reply;xpc_dictionary_set_uint64(reply,"v",1);xpc_dictionary_set_string(reply,"type","lease.pong");xpc_dictionary_set_string(reply,"requestId",request_id);xpc_dictionary_set_uint64(reply,"sequence",sequence);xpc_connection_send_message(pending.connection,reply);result=0;xpc_release(reply);xpc_release(pending.connection);});return result;}
static int client_request(hx_port *port,const char *type,const char *request_id,const uint8_t *first,const uint8_t *second,uint64_t number,hx_event_kind reply_kind){if(!port||port->server||port->closing||!request_id||!request_id[0]||strnlen(request_id,97)>96)return EINVAL;std::string request_id_copy(request_id);xpc_object_t request=message(type,request_id);if(!strcmp(type,"ceremony.finish")){xpc_dictionary_set_data(request,"hostNonce",first,32);xpc_dictionary_set_data(request,"proof",second,32);}retain_port(port);xpc_connection_send_message_with_reply(port->endpoint,request,port->queue,^(xpc_object_t reply){client_reply(port,reply,reply_kind,request_id_copy.c_str(),number,nullptr);release_port(port);});xpc_release(request);return 0;}
extern "C" int hx_client_open(hx_port *p,const char *r){return client_request(p,"ceremony.open",r,nullptr,nullptr,0,HX_CHALLENGE);}
extern "C" int hx_client_finish(hx_port *p,const char *r,const uint8_t n[32],const uint8_t h[32]){return client_request(p,"ceremony.finish",r,n,h,0,HX_GRANT);}
extern "C" int hx_server_ping(hx_port *port,const char *connection_id,const char *request_id,uint64_t sequence){if(!port||!port->server||port->closing||!connection_id||!request_id)return EINVAL;std::string id(connection_id),request_id_copy(request_id);__block int result=ENOENT;dispatch_sync(port->queue,^{auto peer=port->peers.find(id);if(peer==port->peers.end()||peer->second.invalidated)return;xpc_object_t request=message("lease.ping",request_id_copy.c_str());xpc_dictionary_set_uint64(request,"sequence",sequence);retain_port(port);xpc_connection_send_message_with_reply(peer->second.connection,request,port->queue,^(xpc_object_t reply){client_reply(port,reply,HX_PONG,request_id_copy.c_str(),sequence,id.c_str());release_port(port);});xpc_release(request);result=0;});return result;}
extern "C" void hx_close_peer(hx_port *p,const char *id){if(!p||!id)return;std::string value(id);dispatch_async(p->queue,^{invalidate(p,value,"lease-closed");});}
extern "C" void hx_close(hx_port *port){if(!port)return;dispatch_async(port->queue,^{if(port->closing)return;port->closing=true;for(auto &entry:port->peers){xpc_connection_cancel(entry.second.connection);xpc_release(entry.second.connection);}port->peers.clear();for(auto &entry:port->replies){xpc_release(entry.second.reply);xpc_release(entry.second.connection);}port->replies.clear();xpc_connection_cancel(port->endpoint);xpc_release(port->endpoint);auto *event=new hx_event{};event->kind=HX_CLOSED;port->deliver(port->context,event);release_port(port);});}
