import { createRequire } from "node:module";
import { isAbsolute, normalize } from "node:path";
import { Readable, Writable } from "node:stream";
import type { RuntimeAdmissionLease } from "@chirality/runtime-core";
export type NativeUnavailableReason="platform-unsupported"|"api-unavailable"|"filesystem-unqualified"|"path-unsafe"|"lock-contended"|"inode-mismatch"|"descriptor-closure-unqualified"|"spawn-failed"|"wait-unavailable"|"native-package-unqualified";
export type NativeAuthorityResult<T>={state:"available";value:T}|{state:"unavailable";reason:NativeUnavailableReason};
interface RawLease {device:bigint;inode:bigint;held:boolean;created:boolean;close():void}
interface RawChild {read():Promise<Buffer>;write(bytes:Buffer):Promise<void>;closeInput():void;terminate():void;kill():void;wait():Promise<{exitCode:number|null;signal:number|null}>}
interface Binding {acquire(directory:string,name:string):RawLease;spawnSupplier(executable:string,args:readonly string[],secret:Buffer):RawChild}
export interface NativeSupplierChild {readonly stdin:Writable;readonly stdout:Readable;terminate():void;kill():void;wait():Promise<{exitCode:number|null;signal:number|null}>;closeInput():void}
function unavailable<T>(reason:NativeUnavailableReason):NativeAuthorityResult<T>{return{state:"unavailable",reason};}
const reasons:readonly string[]=["platform-unsupported","api-unavailable","filesystem-unqualified","path-unsafe","lock-contended","inode-mismatch","descriptor-closure-unqualified","spawn-failed","wait-unavailable","native-package-unqualified"];
function translate<T>(fn:()=>T):NativeAuthorityResult<T>{try{return{state:"available",value:fn()};}catch(error){const reason=error&&typeof error==="object"&&"code"in error?error.code:undefined;return unavailable(typeof reason==="string"&&reasons.includes(reason)?reason as NativeUnavailableReason:"native-package-unqualified");}}
function path(value:unknown):asserts value is string {if(typeof value!=="string"||!isAbsolute(value)||normalize(value)!==value||Buffer.byteLength(value)>4095||/[\x00-\x1f]/.test(value))throw new Error("invalid-native-path");}
/** Test injection proves wrapper behavior only; it never establishes native qualification. */
export function wrapNativeAdmissionBinding(raw:unknown):{acquire(directory:string):NativeAuthorityResult<RuntimeAdmissionLease>;spawnSupplier(executable:string,args:readonly string[],secret:Buffer):NativeAuthorityResult<NativeSupplierChild>}{
  const binding=raw as Binding;
  return {acquire(directory){return translate(()=>{path(directory);if(!binding||typeof binding.acquire!=="function")throw new Error("invalid-native-binding");const lease=binding.acquire(directory,"runtime-admission-authority.lock");if(!lease||typeof lease.device!=="bigint"||lease.device<0n||typeof lease.inode!=="bigint"||lease.inode<0n||lease.held!==true||typeof lease.created!=="boolean"||typeof lease.close!=="function")throw new Error("invalid-native-lease");let closed=false;return Object.freeze({device:lease.device,inode:lease.inode,created:lease.created,get held(){return !closed&&lease.held===true;},close(){if(closed)throw new Error("native-lease-already-closed");closed=true;lease.close();}});});},
    spawnSupplier(executable,args,secret){return translate(()=>{path(executable);if(!Array.isArray(args)||args.length>128||args.some(a=>typeof a!=="string"||Buffer.byteLength(a)>4096||/[\x00-\x1f]/.test(a))||!Buffer.isBuffer(secret)||secret.length!==32||typeof binding?.spawnSupplier!=="function")throw new Error("invalid-native-bootstrap");const child=binding.spawnSupplier(executable,args,secret);if(!child||["read","write","closeInput","terminate","kill","wait"].some(k=>typeof(child as unknown as Record<string,unknown>)[k]!=="function"))throw new Error("invalid-native-child");let reading=false,wait:Promise<{exitCode:number|null;signal:number|null}>|undefined;const stdout=new Readable({read(){if(reading)return;reading=true;void child.read().then(bytes=>{reading=false;if(!Buffer.isBuffer(bytes))throw new Error("invalid-native-read");this.push(bytes.length?bytes:null);},()=>{reading=false;this.destroy(new Error("native-read-unavailable"));});}});const stdin=new Writable({write(chunk:Buffer,_encoding,callback){void child.write(Buffer.from(chunk)).then(()=>callback(),()=>callback(new Error("native-write-unavailable")));},final(callback){try{child.closeInput();callback();}catch{callback(new Error("native-input-unavailable"));}}});return Object.freeze({stdin,stdout,closeInput:()=>{stdin.end();},terminate:()=>child.terminate(),kill:()=>child.kill(),wait:()=>wait??=child.wait().then(result=>{if(!result||Object.keys(result).sort().join(",")!=="exitCode,signal"||!(result.exitCode===null||Number.isInteger(result.exitCode))||!(result.signal===null||Number.isInteger(result.signal))||(result.exitCode===null)===(result.signal===null))throw new Error("wait-unavailable");return result;},()=>{throw new Error("wait-unavailable");})});});}}
}
/** Importing the package never loads the addon. A later qualified composition must own this call. */
export function loadNativeAdmissionBinding(enabled:boolean):NativeAuthorityResult<ReturnType<typeof wrapNativeAdmissionBinding>> {if(!enabled)return unavailable("native-package-unqualified");if(process.platform!=="darwin"||!["arm64","x64"].includes(process.arch))return unavailable("platform-unsupported");return translate(()=>wrapNativeAdmissionBinding(createRequire(import.meta.url)("../build/Release/chirality_native_admission.node")));}
