from pathlib import Path
import json,csv,hashlib,platform,sys,shutil
O=Path(__file__).resolve().parent
s=json.loads((O/'coverage_summary.json').read_text());raw=json.loads((O/'raw_checks.json').read_text());issues=list(csv.DictReader((O/'Decomp_Coverage_IssueLog.csv').open()))
checks=[('1','Forward packages','PASS','18/18 packages materialized.'),('2','Forward deliverables','PASS','106/106 deliverables materialized.'),('3','Reverse folders','PASS','No orphan folders; all declared and materialized sets equal.'),('4','ID consistency','PASS','No duplicate or reused IDs; old 102 deliverables and 77 scope IDs retained; exactly four deliverables and SOW-078/079 added.'),('5','Context fidelity','PASS','106 identity/name/package/type/envelope records match; four new descriptions and finite boundaries match source registers.'),('6','Artifact presence','INCOMPLETE','All core packages present: 97 validated SOW_V1, eight D-43 architecture references and one accepted DEL-07-09 OPEN custom contract. Anticipated implementation-artifact realization is not recounted.'),('7','Objective mapping','PASS','All 18 objective identities/statements preserved and supported. All displayed deliverable support sets agree; OBJ-018 baseline discrepancy resolved.'),('8','Ledger integrity','WARNING','79 markdown/CSV scope mappings agree and resolve. Stock local-register quality result remains nonzero; see explicit baseline delta below.'),('9','Derivative package parity','SKIPPED','DOMAIN-specific check not variant-owned; SOFTWARE register/decomposition parity is explicitly checked under 5, 7 and 8.'),('9b','Package shape','WARNING','Baseline absence of explicit companion inventory and heavy inline duplication remains; no new derived artifact substituted for amendment authority.'),('10','Snapshot and handoff','PASS','Accepted SCA-010 compact contract remains active; decomposition 0.13 applied pending Group 3; DAG-011 staged and unapproved; active pointers byte-identical to accepted basis.'),('11','Lifecycle distribution','PASS','102 existing lifecycle states unchanged; all four additions OPEN. Whole corpus: 100 IN_PROGRESS, one ISSUED, five OPEN. No lifecycle promotion.')]
text='# SCA-011 actual postchange decomposition audit\n\nOverall: **'+s['overall_status']+'**. Closure-readiness verdict: **'+s['closure_readiness']+'**. This is derivative structural audit evidence for Group 3 preparation, not Group-3 acceptance or product readiness.\n\nThe audit binds the actual working files to the owner’s Group-2 snapshot `execution/_ScopeChange/checkpoint_snapshots/SCA-011_GROUP-2_2026-09-22/` and exact accepted package commit `3e18334eca72509475684cc86786b3eeade83572`. The initial applied state matches all 83 accepted postimage hashes; all 58 carrier and 20 dependency-local targets are covered by that enumeration. Source hashes and per-file checks are retained.\n\n| Check | Name | Verdict | Evidence / limit |\n|---|---|---|---|\n'
text+=''.join('|'+ '|'.join(x)+'|\n'for x in checks)
text+='''\n## Actual-versus-baseline comparison

Whole decomposition: 18 packages / 102 deliverables / 77 scope items / 18 objectives → 18 / 106 / 79 / 18. Existing identifiers are retained; new identities are DEL-04-07, DEL-07-11, DEL-07-12, DEL-16-06 and SOW-078/079. The four control sets are complete, OPEN, and semantically PLACEHOLDER, with three L envelopes and one M. Descriptions and boundaries constrain solve integration, workspace shell, finite interoperability review, and the sole controlled-operation mutation seam; no ownership of underlying mathematics, schema meaning, feature panels, storage policy or professional acceptance is inferred.

Baseline matrix scope was 14 packages / 80 deliverables; this audit expands to all 18 / 106. Raw lifecycle totals therefore have different denominators. The audit compares each of the 102 existing current states directly with accepted-source bytes and recognizes the existing eight architecture-reference contracts under D-43. Memory/status pairs were read; memory is continuity evidence only.

The baseline objective-summary warning is resolved: OBJ-018’s displayed support set now agrees with the companion deliverable register, including DEL-13-02 and the new DEL-07-12, without the erroneous prior DEL-12-02 support. All 18 objective statements and identities remain unchanged; authorized support mappings were updated.

The package-shape warning remains. Canonical machine truth is in `docs/_Registers/{Deliverables,ScopeLedger,ContextBudgetQA}.csv`, while the main document duplicates substantial tables and lacks an explicit companion inventory. The exact amendment preserves that baseline structure and the audit verifies parity rather than requiring unrelated restructuring.

The stock validator exits 1 and reports **2,265 errors**, versus **2,097 baseline errors**. All 2,097 original finding keys remain; 168 are new: 84 EVQ-003 blank inline EvidenceQuote findings and 84 DRB-006 ID-prefix findings on accepted SCA011-E001..084 rows. The stock tool also skips cross-register checks because companions are in docs/_Registers. This audit independently parses those actual companions and confirms parity; it never treats the stock result as a pass.

Each added dependency row has a separate actual-source backcheck with a nonblank literal quote and SHA-256 identity; all 84 were independently rechecked here. The selected dependency extraction method makes EvidenceQuote optional and preserves existing row IDs; these accepted bytes and separate evidence explain the mismatch but do not erase the stock quality findings. These are newly materialized findings, not mislabeled baseline debt. The parent subsequently authorized a bounded correction to those new dependency fields; this initial evidence is preserved and a distinct final audit must bind the corrected bytes.

## Stable claims and retained boundaries

All 24 affected ScopeOfWork documents pass the repository validator. Existing CLM/AC/VER/OUT identifiers are retained as subsets of the actual identifier sets, and the validator checks local references and output/evaluation hooks. The whole corpus contains 97 validated SoWs; the remaining nine use established alternate reference/control contracts. This establishes document structure and traceability, not claim satisfaction.

The applied decomposition status is `applied_group3_pending`. `_ScopeChange/_LATEST.md` remains SCA-010 and `_DAG/_LATEST.md` remains DAG-010. SCA-010 is assessed against its own accepted compact contract, not retroactively rejected against a newer full template. Current SCA-011 handoff truthfully describes derivative/audit work still completing. Group 3 is the existing human checkpoint, not a new blocker manufactured by this audit.

Canonical product core, apps, schemas and tests; DAG-010; SCA-009; and the original whole-corpus R6 reconciliation paths show no changes from the accepted package commit. Draft result wire schemas are absent from the 83-target manifest and remain unpromoted. No product tests, numerical/engineering conformance, private-data authorization, external activation, original satisfaction evidence, lifecycle issuance or release acceptance is claimed. Concurrent App and Root-owned changes are outside this Piping audit’s containment claim.

## Material findings and next action

See `Decomp_Coverage_IssueLog.csv` for the two grouped warnings and two informational findings, with source paths. There is no mismatch in the initial exact application or structural inventory. Preserve this initial audit, complete the newly authorized dependency-field correction, then re-audit corrected hashes, source quotes, row identity crosswalk, unchanged relation semantics and baseline preservation. The manager’s separate fresh complete-poststate review remains required before the Group-3 package is presented.
'''
(O/'Decomp_Coverage_Report.md').write_text(text)
(O/'Brief.md').write_text('''# Bounded audit brief

Caller: `/root/piping_scope_manager`; executor: `/root/piping_scope_manager/piping_postchange_audit`; role: TASK; actual mechanism: Codex delegated-harness-native collaboration. No child delegation, canonical writes or Git mutations.

Owner Group-2 words, verbatim: “Meanwhile, I accept this exact amenment for Piping. Apply it and prepare the audited result (delegate this work).” Group-2 snapshot binds reviewed commit 3e18334eca72509475684cc86786b3eeade83572.

Assignment: fresh post-change audit-decomp of actual Piping decomposition/registers, 58 carriers, four new OPEN control sets, exact 83 APPLY_MANIFEST targets and staged dependency successor; compare preserved prechange audit 18/102/77 with expected 18/106/79. Check stable IDs/hooks on 24 affected SoWs, finite 3L+1M envelopes, objective identity preservation and restored OBJ-018 support summary; distinguish baseline validator issues from actual regressions. Preserve lifecycle, code/schema, privacy, numerical/professional and release holds; no product tests or engineering acceptance claims. Active SCA010/DAG010 pointers remain, Group3 pending is intentional. Read status/memory pairs; memory is not authority. Return source-bound findings to parent, which owns separate independent full-poststate review and Git.

Normalized inputs: EXECUTION_ROOT=projects/chirality-piping/execution; DECOMPOSITION_PATH=execution/_Decomposition/SOFTWARE_DECOMP.md; DECOMP_VARIANT=SOFTWARE; SCOPE=ALL; EXPECTED_HANDOFF_PHASE=APPLIED_GROUP3_PENDING. Selected workflow: bundled:chirality-root/audit-decomp. Output override mandated by caller: only SCA-011/application/postchange_audit/. No _Evaluation/_LATEST pointer write is authorized.
''')
(O/'Decision_Log.md').write_text('''# Audit decisions

- Use source-qualified bundled:chirality-root/audit-decomp; bind semantic headings by text/rank, not fixed numbering. All required bindings resolve without ambiguity.
- Caller-specific write boundary overrides the workflow default _Evaluation snapshot/pointer placement. This artifact is derivative evidence under the SCA package; no canonical audit pointer is changed.
- Expand to whole-corpus structural inventory and explicitly disclose the 80→106 matrix denominator difference; preserve baseline metrics without inventing equality of scope.
- Read Git only to bind immutable source bytes, compare prior lifecycle and verify protected Piping paths. Parent explicitly confirmed this interpretation of “no Git”; no Git mutations occur.
- Distinguish accepted exact file application from stock local-quality conformance. Retain every stock finding and source-keyed delta, with no fabricated pass or waiver.
- Consult dependency-extract Functions 1/3 read-only to assess optional quote and ID-preservation semantics; audit-decomp remains this TASK’s selected method.
- First exploratory objective-statement check included mapped-scope columns and failed on authorized mapping changes. Corrected it to ObjectiveID and Statement only; objective mappings are independently parity-checked. No canonical bytes were changed to satisfy checks.
- Recognize existing PKG-00 D-43 architecture references and DEL-07-09 accepted OPEN custom contract. Do not require a current SoW template retroactively or infer implementation absence from alternative core contracts.
- Preserve initial exact-application audit before the parent-authorized correction of 84 new dependency fields; final corrected evidence belongs to a distinct audit snapshot.
''')
(O/'QA_Report.md').write_text('''# QA and limits

All 12 workflow checks are reported; check 9 is variant-skipped and check 6 explicitly limits core-contract checking versus incomplete full production-artifact realization. 106 matrix rows and unique identities, 18 materialized package identities, 79 scope-ledger rows, 18 objective identities, 83 manifest postimages, 24 affected SoWs, 97 whole-corpus SoWs, 84 actual dependency evidence quotes, 102 preserved lifecycle states and four new OPEN controls were checked. See raw_checks.json, sow_validation.json, register_validation.json, register_comparison.json and SOURCES.json.

The stock validator exits nonzero; its companion discovery limitation and 168 new findings are disclosed. Dedicated actual-file companion parity supplements the skipped stock family but does not rewrite its result. Finite envelopes are bounded scopes, not measured token-budget performance. Full semantic intent, every anticipated implementation artifact, product behavior and original satisfaction evidence are outside this structural audit. New controls remain placeholders.

Source hashes bind actual consulted bytes. Current handoff may be refined by the manager after this return; the later independent review must cover final metadata. Writes are restricted by instructions and scoped scripts in a shared filesystem, not an isolated per-file host sandbox. Model/effort are inherited; exact settings were not exposed and no override was requested. The initial invalid descriptor-path probe found no workflow.json; execution.json was then read as the actual descriptor. No failed or unavailable product check is represented as passing.
''')
(O/'RUN_SUMMARY.md').write_text('# Postchange audit return\n\nRUN_STATUS = WARNINGS\n\nInitial exact Group-2 application: 83/83 accepted hashes, 18 packages, 106 deliverables, 79 scope items and 18 unchanged objective identities/statements. Four new OPEN controls (3L+1M); all97 SoWs validate and all24 affected SoWs retain stable local IDs/hooks. OBJ018 support parity restored. Existing lifecycle unchanged.\n\nTwo grouped warnings: retained package-shape debt and +168 stock local-quality findings (84 blank inline quotes,84 row-ID prefixes), against unchanged2097 baseline errors. Separate84 actual-source quotes/hashes pass. No application/structural blocker; closure-readiness WARN.\n\nThe parent has authorized correction of only the84 new dependency fields. Preserve this initial audit and re-run independently against corrected bytes before final Group3 preparation. Group3 acceptance, active-pointer promotion and product/engineering claims remain outstanding or out of scope.\n')
meta={'python':sys.version,'platform':platform.platform(),'raw_check_count':len(raw['checks']),'failed_raw_checks':[x['check']for x in raw['checks']if not x['pass']],'matrix_rows':len(list(csv.DictReader((O/'Decomp_Coverage_Matrix.csv').open()))),'artifact_sha256':{p.name:hashlib.sha256(p.read_bytes()).hexdigest()for p in O.iterdir()if p.is_file()and p.name!='CHECKS.json'}}
(O/'CHECKS.json').write_text(json.dumps(meta,indent=2)+'\n')
