import { PassThrough } from 'node:stream';
import { expect, it } from 'vitest';
import { CodexTurnSession } from '/Users/ryan/.codex/worktrees/341e/chirality/projects/chirality-runtime/packages/daemon/src/codex-session.ts';
const uuid='12345678-1234-4abc-8def-123456789abc';
const networkItem=(environment='local',protocol='http',host='example.com',port='80',id=uuid)=>`network#${environment}#${protocol}#${host}#${port}#${id}`;
async function harness() {
 const stdin=new PassThrough(), stdout=new PassThrough(); const replies:unknown[]=[];
 const send=(frame:unknown)=>stdout.write(JSON.stringify(frame)+'\n');
 stdin.on('data',chunk=>{for(const line of String(chunk).trim().split('\n')){const frame=JSON.parse(line); if(!frame.method){replies.push(frame);continue;} if(frame.method==='initialized')continue; send({id:frame.id,result:frame.method==='thread/start'?{thread:{id:'review-thread'}}:frame.method==='turn/start'?{turn:{id:'review-turn'}}:{}});}});
 const actor=new CodexTurnSession({requestTimeoutMs:500,turnTimeoutMs:1000,commandNetworkPosture:'ask-per-destination',transport:{stdin,stdout,async close(){}}});
 await actor.initialize();await actor.startThread({cwd:'/private/tmp',model:'pure-review',continuityChecked:true});await actor.startTurn({threadId:'review-thread',text:'pure-review',model:'pure-review'});
 const prompt=(changes:Record<string,unknown>={},id:string|number=1)=>send({id,method:'item/commandExecution/requestApproval',params:{threadId:'review-thread',turnId:'review-turn',itemId:networkItem(),environmentId:'local',startedAtMs:0,networkApprovalContext:{host:'example.com',protocol:'http'},availableDecisions:['accept','acceptForSession',{applyNetworkPolicyAmendment:{network_policy_amendment:{host:'example.com',action:'allow'}}},'cancel'],...changes}});
 return {actor,prompt,send,replies};
}
const invalidItems=[null,123,'network#local#http#example.com#080#'+uuid,networkItem('local','http','example.com','65536'),networkItem('local','http','example.com','-1'),networkItem('local','http','example.com','1.0'),networkItem('local','HTTP'),networkItem('local','http','EXAMPLE.COM'),networkItem('other'),networkItem('local','https'),networkItem('local','http','foreign.com'),networkItem('local','http','example.com','80',uuid.toUpperCase()),networkItem('local','http','example.com','80',uuid.replace('4abc','1abc')),networkItem('local','http','example.com','80',uuid.replace('8def','7def')),networkItem()+'#extra',networkItem()+'\n',networkItem('x'.repeat(129)),networkItem('bad space')];
it.each(invalidItems.map((value,index)=>({value,index})))('rejects unsupported network token case $index without reply',async({value})=>{const f=await harness();try{f.prompt({itemId:value});expect(()=>f.actor.pendingNetworkApprovals()).toThrow();await expect(f.actor.waitTurn('review-turn')).rejects.toThrow();expect(f.replies).toEqual([]);}finally{await f.actor.close();}});
const badChoices=[{foreign:{}},{applyNetworkPolicyAmendment:{network_policy_amendment:{host:'foreign.com',action:'allow'}}},{applyNetworkPolicyAmendment:{network_policy_amendment:{host:'example.com',action:'ALLOW'}}},{applyNetworkPolicyAmendment:{network_policy_amendment:{host:'example.com',action:'allow',extra:true}}},{applyNetworkPolicyAmendment:{network_policy_amendment:{host:'example.com',action:'allow'},extra:true}},{applyNetworkPolicyAmendment:{network_policy_amendment:{host:'example.com',action:'allow'}},extra:true},{acceptWithExecpolicyAmendment:{execpolicy_amendment:['curl']}},[],null,'futureChoice'];
it.each(badChoices.map((value,index)=>({value,index})))('rejects unsupported choice case $index without reply',async({value})=>{const f=await harness();try{f.prompt({availableDecisions:['accept',value]});expect(()=>f.actor.pendingNetworkApprovals()).toThrow();await expect(f.actor.waitTurn('review-turn')).rejects.toThrow();expect(f.replies).toEqual([]);}finally{await f.actor.close();}});
it('supports exact default choices without synthetic decline or automatic response',async()=>{const f=await harness();try{f.prompt();const [prompt]=f.actor.pendingNetworkApprovals();expect(prompt?.availableDecisions).toEqual(['allow','acceptForSession']);expect(f.replies).toEqual([]);await expect(f.actor.replyNetworkApproval(prompt!.approvalId,'deny')).rejects.toThrow();expect(f.replies).toEqual([]);await f.actor.replyNetworkApproval(prompt!.approvalId,'allow');expect(f.replies).toEqual([{id:1,result:{decision:'accept'}}]);}finally{await f.actor.close();}});
it('preserves typed request identities and exact replay signatures',async()=>{const f=await harness();try{f.prompt({},1);f.prompt({},'1');f.prompt({},1);expect(f.actor.pendingNetworkApprovals()).toHaveLength(2);f.prompt({itemId:networkItem('local','http','example.com','81')},1);await expect(f.actor.waitTurn('review-turn')).rejects.toThrow();expect(f.replies).toEqual([]);}finally{await f.actor.close();}});
it('accepts the full local bound and canonical socks label without changing global IDs',async()=>{const f=await harness();try{const environment='e'.repeat(128),host=[63,63,63,61].map(n=>'a'.repeat(n)).join('.');const itemId=networkItem(environment,'socks5-tcp',host,'65535');expect(itemId.length).toBe(444);f.prompt({itemId,environmentId:environment,networkApprovalContext:{host,protocol:'socks5Tcp'},availableDecisions:['accept','cancel']});expect(f.actor.pendingNetworkApprovals()).toHaveLength(1);expect(f.replies).toEqual([]);}finally{await f.actor.close();}});
it.each([{threadId:networkItem()},{turnId:networkItem()},{threadId:'foreign'},{turnId:'foreign'},{additionalPermissions:{}},{command:'curl http://example.com'},{environmentId:'foreign'}])('preserves existing attribution and combined-grant barriers %j',async changes=>{const f=await harness();try{f.prompt(changes);expect(()=>f.actor.pendingNetworkApprovals()).toThrow();await expect(f.actor.waitTurn('review-turn')).rejects.toThrow();expect(f.replies).toEqual([]);}finally{await f.actor.close();}});
