from pathlib import Path
import csv,json,hashlib,re,subprocess,os,collections
repo=Path.cwd(); out=Path(__file__).resolve().parent; pkg=out.parent.parent
base='2be412ccea62bdc4bd96deb082c46d7a792076ea'; did='DEL-02-03'
run=pkg.parent.parent; rootrun=run.parent
local=Path('projects/pec/execution/PKG-02_File_Truth_Parsers/1_Working/DEL-02-03_Receipts_ledger_parser_per_loop_grammars')
sow=local/'ScopeOfWork.md'; upstream=Path('projects/pec/execution/PKG-01_Service_Core_Store/1_Working/DEL-01-01_Record_tier_schema_entity_model')
sha=lambda b:hashlib.sha256(b).hexdigest()
sources=set(local.rglob('*')); sources={p for p in sources if p.is_file()}
for x in ['AGENTS.md','projects/pec/AGENTS.md','agents/AGENT_RECONCILIATION.md','docs/DELIVERABLE_CONCORDANCE_METHOD.md','projects/pec/docs/PRD.md','projects/pec/loop/LOOP_INIT.md','projects/pec/execution/_Scripts/pec_reliance_hold.py','projects/pec/execution/_Coordination/ACTIVE_RELIANCE_HOLDS.csv','projects/pec/execution/_Coordination/_DECISIONS/_REGISTER.md','projects/pec/execution/_Coordination/PLAN_2026-07-25_project_setup_dag_gate.md','projects/pec/execution/_Coordination/WORKING_ITEMS_SCA004_CURRENCY_SWEEP_2026-08-03/HANDOFF_STATE.md']:
 sources.add(Path(x))
for name in ['ScopeLedger.csv','Deliverables.csv','SOFTWARE_DECOMP.md','ContextBudgetQA.csv','_LATEST.md']:sources.add(Path('projects/pec/execution/_Decomposition')/name)
for name in ['ScopeOfWork.md','_STATUS.md']:sources.add(upstream/name)
for prefix in ['D-PEC-81','D-PEC-82','D-PEC-65','D-PEC-62','D-PEC-63']:
 sources.update(Path('projects/pec/execution/_Coordination/_DECISIONS').glob(prefix+'*.md'))
sources.add(Path('projects/pec/execution/_ScopeChange/SCA-002_2026-07-25_1042/Decision_Log.md'))
for n in ['RUN_BASIS.md','SOURCE_MANIFEST.json','SCOPE_CENSUS.csv','AGENT0_GRAPH.md','BRIEF_CLARIFICATION_01.md']:sources.add(run/'COMMON'/n)
for n in ['PACKAGE_BASIS.md','SOURCE_MANIFEST.json','validate_members.py','BRIEFS/DEL-02-03.md']:sources.add(pkg/n)
sources.add(rootrun/'CONVENTIONS.md')
sources.update(p for p in Path('projects/pec/v2').rglob('*') if p.is_file() and '__pycache__' not in p.parts)
contents={str(p.relative_to(repo) if p.is_absolute() else p):p.read_bytes() for p in sources}
hashes={p:sha(b) for p,b in sorted(contents.items())}
checks=[]
def check(args):
 r=subprocess.run(args,capture_output=True,text=True,env={**os.environ,'PYTHONDONTWRITEBYTECODE':'1','PYTHONPYCACHEPREFIX':'/tmp/pec-del0203-cache'})
 checks.append(dict(command=' '.join(args),cwd='.',environment={'PYTHONDONTWRITEBYTECODE':'1','PYTHONPYCACHEPREFIX':'/tmp/pec-del0203-cache'},exit_code=r.returncode,result=r.stdout+r.stderr));return r
for name in ['ScopeOfWork.md','_STATUS.md','Dependencies.csv']:
 r=check(['python3','projects/pec/execution/_Scripts/pec_reliance_hold.py','--register','projects/pec/execution/_Coordination/ACTIVE_RELIANCE_HOLDS.csv','--target',str(local/ name).removeprefix('projects/pec/'),'--operation','candidate-validation']);assert r.returncode==0,r.stdout+r.stderr
common=json.loads((run/'COMMON/SOURCE_MANIFEST.json').read_text())
cm=common.get('hashes',{}); mismatches=[p for p,h in hashes.items() if p in cm and cm[p]!=h]; assert not mismatches,mismatches
checks.append(dict(command='compare read-source hashes with COMMON/SOURCE_MANIFEST.json',cwd='.',environment={},exit_code=0,result={'matched':sum(p in cm for p in hashes),'mismatches':mismatches}))
s=sow.read_text(); defs=[(m.group(1),m.group(2)) for m in re.finditer(r'^- \*\*([A-Z]+-\d{3})\*\* — (.*)',s,re.M)]
assert len(defs)==79;assert sum(i.startswith(('REQ-','AC-','VER-')) for i,_ in defs)==40
C='ClaimID,DeliverableID,ClaimClass,NormativeSource,ScopeItemIDs,DeclaredSource,CurrentState,ImplementationEvidence,VerificationEvidence,ValidationOrProvenanceEvidence,LifecycleEvidence,ExistingRemaining,Disposition,ProposedResidualID,ProposedResidualText,Depends,ExactGate,AuthorityNeeded,Selectability,SourceCommit,SourceHashes,EvidenceReferences,Notes'.split(',')
R='ResidualID,DeliverableID,ClaimIDs,ProposedText,Depends,ExactGate,ClosureEvidence,AuthorityNeeded,Selectability,Notes'.split(',')
gate='NOT_SELECTABLE_UNTIL: separately accepted exact Remaining application and owner-ruled packet naming paths, acts, verification and rollback; no D82 source opening'
texts={1:'Establish current source-bound evidence for the accepted SOW-013 receipts parser, per-loop grammar table and fixture suite against OUT-001..003, REQ-001..013 and AC-001..013. If evidence establishes a production gap, route a bounded owner-ruled implementation packet; do not infer implementation absence from the current-source inventory.',2:'Obtain an accepted parser loop-coverage basis if production cannot derive it from accepted scope; preserve OI-008 per-loop adoption as separately owner-ruled and non-blocking for P0–P2. Do not import registry coverage as parser scope.',3:'Obtain or locate an exact source-bound REVIEW record for AC-014, preserving the accepted SCA-002 Q2 AFFIRM objective ruling and its indirect warrant; no new objective-confirmation act is implied.',4:'Retain the dated CLM-017 ledger census as author observation only; establish fresh scoped evidence before any current reliance on its foreign-loop counts or classification. No foreign-loop inspection or mutation is authorized by this proposal.'}
rows=[]
def add(i,quote,cls='documentary alignment',disp='ALIGNED',note='',res=None,depends='NONE',source=None):
 source=source or str(sow); loc=source+'#'+i
 row=dict.fromkeys(C,'NONE');row.update(ClaimID=did+'::'+i,DeliverableID=did,ClaimClass=cls,NormativeSource='projects/pec/execution/_Decomposition/ScopeLedger.csv#SOW-013;'+loc,ScopeItemIDs='SOW-013',DeclaredSource=loc+' quote-sha256='+sha(quote.encode()),CurrentState=quote,ImplementationEvidence='No claim-relevant implementation established by bounded current v2 inventory; this is not proof of absence.' if disp=='UNKNOWN' else 'Not asserted by this documentary claim.',VerificationEvidence=('UNEXECUTED declared method; source defines the finite method, with no parser PASS claimed.' if i.startswith('VER-') else 'Source comparison in CLAIM_AUDIT.md; no parser behavior test executed.'),ValidationOrProvenanceEvidence='Accepted revision 1.4 scope; D-PEC-63 contract-authoring/status history; D-PEC-65 dependency evidence repair; historical author run is not product acceptance.',LifecycleEvidence=str(local/'_STATUS.md')+'#Current State=INITIALIZED',ExistingRemaining='No ## Remaining section; no recorded selectable scope; not warranted NONE.',Disposition=disp,Depends=depends,ExactGate=gate,AuthorityNeeded='Exact application/source or REVIEW act by owning workflow as applicable; D82 discovery only.',Selectability='NON_SELECTABLE_PENDING_OWNER_APPLICATION',SourceCommit=base,SourceHashes=json.dumps({source:hashes[source],str(local/'_STATUS.md'):hashes[str(local/'_STATUS.md')],'projects/pec/execution/_Decomposition/ScopeLedger.csv':hashes['projects/pec/execution/_Decomposition/ScopeLedger.csv']},sort_keys=True),EvidenceReferences='CLAIM_AUDIT.md#'+i+';READ_MANIFEST.json',Notes=note)
 if res:row.update(ProposedResidualID=did+f'-REM-{res:03}',ProposedResidualText=texts[res])
 rows.append(row)
for i,q in defs:
 if i.startswith(('REQ-','OUT-')) or (i.startswith('AC-') and i!='AC-014'):
  add(i,q,'behavioral obligation','UNKNOWN','Accepted future-production obligation. Current v2 sources implement loop registry and other slices, not affirmative evidence for this parser; authoring run reports a contract only. No DOCUMENTED_UNIMPLEMENTED inference.',1,'DEL-01-01')
 elif i=='AC-014':add(i,q,'human acceptance','UNKNOWN','SCA-002 Q2 is an actual accepted objective ruling; it is not the exact current contract REVIEW demanded here. No DEL-02-03 REVIEW located in bounded review inventory; no prior act reversed.',3)
 elif i.startswith('VER-'):add(i,q,'finite test method','ALIGNED','ALIGNED only as a declared method linked to the matching AC in the matrix. No executing suite or finite PASS established. Does not discharge REQ/AC.')
 elif i in ['TBD-003','CON-002']:add(i,q,'documentary alignment','UNKNOWN','Coverage-set limitation is explicitly documented. Registry configuration and later OI-003 ruling do not silently choose this parser coverage or add an edge to DEL-01-06.',2)
 elif i=='CLM-017':add(i,q,'historical author observation','UNKNOWN','July25 run attributes five-ledger counts and classifies its search as observation. Foreign-ledger scope excluded; counts not refreshed and not represented as current.',4)
 elif i=='CLM-008':add(i,q,'documentary provenance','ACCEPTED_DIVERGENCE','Edge identity and PENDING prerequisite survive. D-PEC-65 repaired EvidenceFile/SourceRef/EvidenceQuote; literal old cells in contract are historical, not current register truth. No register flip or new repair inferred.')
 elif i in ['CLM-016','AX-012']:add(i,q,'historical lifecycle declaration','ACCEPTED_DIVERGENCE','OPEN refers to authoring-time NO_STATUS_TOUCH basis; current authoritative status is INITIALIZED under separate D-PEC-63 status act. No stale wording rewrite or lifecycle reversal inferred; no current implementation absence claimed.')
 elif i in ['CLM-009','AX-007']:add(i,q,'documentary alignment','ALIGNED','Upstream INITIALIZED contract remains documentary input. The historical no-schema/no-code observation is not a fresh all-repository implementation verdict or a dependency SatisfactionStatus flip.')
 elif i=='TBD-001':add(i,q,'documentary alignment','ALIGNED','Truthful ResponsibleParty=TBD agrees with current register/context. No product implementation residual or automatic assignment task.')
 elif i in ['TBD-002','TBD-004']:add(i,q,'documentary alignment','ALIGNED','Production grammar choices remain expressly undetermined within declared grammar/content-minimal scope. Documentary truth, not a completed grammar artifact.')
 elif i=='CON-001':add(i,q,'documentary alignment','ALIGNED','SOW-082 remains TBD and OI-008 per-loop owner ruling remains separate; none blocks P0–P2. No blanket owner-adoption gate placed on unrelated work.')
 elif i=='AX-001':add(i,q,'documentary alignment','ALIGNED','Normative files-govern/read-only limit aligns with PRD. Statement about every foreign ledger is retained as author provenance, not independently surveyed current behavior.')
 else:add(i,q,note='Compared to accepted scope/PRD, local context and source-bound dependency/objective records. Alignment is documentary and does not assert implemented behavior or new human acceptance.')
add('SOW-013','Parse LOOP_RECEIPTS.md ledgers under per-loop grammar, including the D-APP-57 contract where a ledger has adopted it','behavioral obligation','UNKNOWN','Accepted ledger row is exact scope basis; CLM-001 separately assesses documentary transcription.',1,'DEL-01-01','projects/pec/execution/_Decomposition/ScopeLedger.csv')
add('BASIS-001','Contract cites revision 1.2; current accepted decomposition and context/reference pointers are revision 1.4','documentary provenance','ACCEPTED_DIVERGENCE','SOW-013 scope unchanged; historical frontmatter is provenance. Completed ordinary SCA004 currency must not be reopened by old _LATEST prose.')
add('LIFECYCLE-001','Current State INITIALIZED; no ## Remaining section','lifecycle','ALIGNED','Status is the current lifecycle home. Empty work selection does not prove closure; UNKNOWN population prevents NONE.',source=str(local/'_STATUS.md'))
res=[]
for n,t in texts.items():
 linked=[r['ClaimID'] for r in rows if r['ProposedResidualID']==did+f'-REM-{n:03}']
 res.append(dict(zip(R,[did+f'-REM-{n:03}',did,';'.join(linked),t,'DEL-01-01' if n==1 else 'NONE',gate,'Exact source-bound evidence and relevant owner acceptance; re-audit linked claim population without changing authoritative sources.','Owner application; source activation/SCOPE_CHANGE/REVIEW only as relevant.','NON_SELECTABLE_PENDING_OWNER_APPLICATION','Evidence candidate' if n==1 else 'Held scope/acceptance/historical routing concern; no automatic product Remaining mirror.'])))
for name,data,fields in [('CLAIMS.csv',rows,C),('RESIDUALS.csv',res,R)]:
 with (out/name).open('w',newline='') as f:w=csv.DictWriter(f,fieldnames=fields,lineterminator='\n');w.writeheader();w.writerows(data)
audit=['# Claim audit — DEL-02-03','All locators refer to the frozen base; current-source search is bounded evidence, never proof of global implementation absence.','## Current source inventory','\n'.join('- '+p for p in hashes if p.startswith('projects/pec/v2/')),'## Current controls','Dependency DEP-02-03-003 is ACTIVE PREREQUISITE/PENDING to DEL-01-01. Only proposed evidence/production item REM-001 names that target. Discovery proceeds; ordinary observed maturity does not flip the register.','No local REVIEW file exists. D-PEC-63 records contract INITIALIZED, not product acceptance; SCA-002 Q2 acceptance is preserved.','## Authority and historical boundaries','D82 and D81 acceptance are current base records; effectiveness is inherited from COMMON source-bound mainline evidence, not a newly performed fetch. D65 is the source of the repaired evidence cells. Current v2 source text and the local two run records do not establish receipts-parser execution. Frozen legacy corpus was not used as current implementation.']
for row in rows:audit+=['## '+row['ClaimID'].split('::')[1],row['CurrentState'],row['Disposition']+' / '+row['ClaimClass']+'. '+row['Notes'],row['VerificationEvidence']]
(out/'CLAIM_AUDIT.md').write_text('\n\n'.join(audit)+'\n')
counts=dict(collections.Counter(r['Disposition'] for r in rows));summary={'claims':len(rows),'local_definitions':79,'REQ_AC_VER':40,'additional_scope_control_claims':3,'dispositions':counts,'residuals':len(res),'verdict':'ASSESSED_UNKNOWN'}
(out/'COVERAGE.md').write_text('# Coverage\n\n'+json.dumps(summary,indent=2)+'\n\n79/79 local definitions covered exactly once: CLM17, OUT3, TBD4, REQ13, AC14, CON3, VER13, AX12. Quoted upstream REQ-008/AC-007 are context, not local definitions. Three explicit scope/control rows supplement those definitions. No local material ID excluded.\n\nVER rows are declared finite methods, not executed tests. AC-014 is exact REVIEW evidence, separate from accepted Q2. All UNKNOWNs retained; no warranted NONE. Four proposals comprise one evidence candidate and three held scope/acceptance/historical concerns.\n\nR0: DEL-02-03 was not a selected calibration sample; conventions reused only. No old finite test borrowed. Shared and package authorities are derivative context; accepted revision1.4 and decisions remain authority.\n')
manifest=dict(source_commit=base,hashes=hashes,historical_sources=[],checks=checks,source_unchanged=all(sha(Path(p).read_bytes())==h for p,h in hashes.items()))
(out/'READ_MANIFEST.json').write_text(json.dumps(manifest,indent=2)+'\n')
(out/'RETURN.md').write_text('# Terminal worker return\n\n'+json.dumps(summary,indent=2)+'\n\nCOMPLETE_FOR_INDEPENDENT_PACKAGE_VERIFICATION. Native Agent2 /root/pec_pkg02_reconciliation/del0203, instruction-asserted role, no delegation. Output scope: '+str(out.relative_to(repo))+'/** only.\n\nClosure is read-only claim evidence readiness; not Remaining application, product completion, lifecycle or release. Exact source/hold or accepted authority changes require affected claim rerun. Parent supplies independent verifier and immutable package aggregation. No source changed. Hold checks ALLOW for exact three file targets, not production permission.\n\nEvidence files: CLAIMS.csv, RESIDUALS.csv, CLAIM_AUDIT.md, COVERAGE.md, READ_MANIFEST.json; structural result in VALIDATION.json and output hashes in OUTPUT_MANIFEST.json.\n')
print(json.dumps(summary))
