#!/usr/bin/env python3
"""Step 8: PACKAGE_SUMMARY.md for PKG-00, by script from the accepted (sealed) ledgers, errata,
CORRECTIONS.csv, verifier shards and reverse files. The hand-written R3 section is appended verbatim
from _scripts/R3_OBSERVATIONS.md (evidence, not rulings)."""
import csv, glob, io, os, re, hashlib, collections
PKG = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
UNITS = ["DEL-00-01", "DEL-00-02"]
def rows(p):
    if not os.path.exists(p): return []
    t = open(p, encoding="utf-8").read().rstrip("\n")
    recs = [r for r in csv.reader(io.StringIO(t)) if r and r != ["#END"]]
    return [dict(zip(recs[0], r)) for r in recs[1:]]
def reach(r):
    t = re.findall(r"REACH=(LIVE|LEGACY_ONLY|TEST_ONLY)", r["ImplementationEvidence"])
    return ",".join(sorted(set(t))) if t else "no code evidence"
def hdn(r): return [x.strip() for x in r["HumanDecisionNeeded"].split(";") if x.strip()]
corr = rows(os.path.join(PKG, "CORRECTIONS.csv"))
L = {}; E = {}; C = {}
for u in UNITS:
    L[u] = rows(os.path.join(PKG, u, f"{u}_claims.csv"))
    E[u] = rows(os.path.join(PKG, u, f"{u}_errata.csv"))
    ap = [dict(r) for r in L[u]]; ix = {r["ClaimKey"]: r for r in ap}
    for e in E[u]:
        if e["ClaimKey"] in ix: ix[e["ClaimKey"]][e["Field"]] = e["ProposedValue"]
    ea = [dict(r) for r in ap]; ix2 = {r["ClaimKey"]: r for r in ea}
    for c in corr:
        if c["ClaimKey"] in ix2 and " || " not in c["CorrectedValue"]: ix2[c["ClaimKey"]][c["Field"]] = c["CorrectedValue"]
    E[u] = (ap, len(E[u])); C[u] = ea
out = ["# PKG-00 — R2 package summary", "",
       "> Generated by `_scripts/summary.py` from the sealed ledgers, errata, `CORRECTIONS.csv`, verifier shards and",
       "> reverse files. Columns: **sealed** / **errata-applied** / **corrected** (errata then CORRECTIONS.csv, R3 order;",
       "> CONTESTED corrections with two readings are not applied). Evidence, not rulings.", ""]
out += ["## Ledgers", "", "| Unit | Rows | SEE rows | Split units | Claims SHA-256 | Errata rows |", "|---|---:|---:|---:|---|---:|"]
for u in UNITS:
    see = sum(1 for r in L[u] if "SEE:" in r["Notes"])
    split = len({r["ClaimKey"].rsplit(".", 1)[0] for r in L[u] if re.search(r"#\w+-\d+\.\d+$", r["ClaimKey"])})
    sha = hashlib.sha256(open(os.path.join(PKG, u, f"{u}_claims.csv"), "rb").read()).hexdigest()
    out.append(f"| {u} | {len(L[u])} | {see} | {split} | `{sha}` | {E[u][1]} |")
def census(field, fn=None):
    fn = fn or (lambda r: r[field])
    out.extend(["", f"## Census by {field}", "", "| Value | " + " | ".join(f"{u} sealed / errata / corrected" for u in UNITS) + " | Package sealed / corrected |", "|---|" + "---|" * (len(UNITS) + 1)])
    cs = {u: (collections.Counter(map(fn, L[u])), collections.Counter(map(fn, E[u][0])), collections.Counter(map(fn, C[u]))) for u in UNITS}
    keys = sorted(set().union(*[set(a) | set(b) | set(c) for a, b, c in cs.values()]))
    for k in keys:
        cells = [f"{cs[u][0][k]} / {cs[u][1][k]} / {cs[u][2][k]}" for u in UNITS]
        out.append(f"| {k} | " + " | ".join(cells) + f" | {sum(cs[u][0][k] for u in UNITS)} / {sum(cs[u][2][k] for u in UNITS)} |")
for f in ["ClaimType", "Disposition", "CauseTag", "AuthorityTier"]: census(f)
census("REACH", reach)
out += ["", "## HumanDecisionNeeded tallies (tokens; `;`-separated values counted per token)", "", "| Token | " + " | ".join(f"{u} sealed / corrected" for u in UNITS) + " |", "|---|" + "---|" * len(UNITS)]
hs = {u: (collections.Counter(t for r in L[u] for t in hdn(r)), collections.Counter(t for r in C[u] for t in hdn(r))) for u in UNITS}
for k in sorted(set().union(*[set(a) | set(b) for a, b in hs.values()]) | {"R4", "R4-Q1", "R4-Q2", "R4-Q3", "R4-Q4", "R4-Q5"}):
    out.append(f"| {k} | " + " | ".join(f"{hs[u][0][k]} / {hs[u][1][k]}" for u in UNITS) + " |")
others = sorted({r["CauseTag"] for u in UNITS for r in L[u] if r["CauseTag"].startswith("OTHER:")})
out += ["", f"**OTHER CauseTag tokens:** {', '.join(others) if others else 'none'}.", ""]
out += ["## Verifier outcomes", "", "| Shard | Items | CONFIRMED | REFUTED | CONTESTED | Verdict-field REFUTED (distinct) |", "|---|---:|---:|---:|---:|---:|"]
for f in sorted(glob.glob(os.path.join(PKG, "_verify", "V-*.csv"))):
    vr = rows(f); items = {}
    for r in vr:
        k = (r["Class"], r["ClaimKey"], r["CapabilityID"]); v = r["Verdict"]
        prev = items.get(k); rank = {"CONFIRMED": 0, "CONTESTED": 1, "REFUTED": 2}
        items[k] = v if prev is None or rank[v] > rank[prev] else prev
    vc = collections.Counter(items.values())
    vf = len({(r["ClaimKey"], r["CapabilityID"]) for r in vr if r["Verdict"] == "REFUTED" and r["Field"] in ("Disposition", "Response")})
    out.append(f"| {os.path.basename(f)[2:-4]} | {len(items)} | {vc['CONFIRMED']} | {vc['REFUTED']} | {vc['CONTESTED']} | {vf} |")
fc = collections.Counter(c["Field"] for c in corr)
out += ["", f"**CORRECTIONS.csv:** {len(corr)} rows" + (f" ({', '.join(f'{k} {v}' for k, v in sorted(fc.items()))})" if corr else "") + ".", ""]
out += ["## Capability responses (reverse pass)", "", "| Unit | Areas | CLAIMED_BY | PARTIAL | NOT_MINE |", "|---|---|---:|---:|---:|"]
for u in UNITS:
    rv = collections.Counter(r["Response"] for r in rows(os.path.join(PKG, u, f"{u}_reverse.csv")))
    am = open(os.path.join(PKG, u, "REVERSE_INPUT", "AREAS.md")).read()
    ar = re.search(r"\*\*Selected areas:\*\* ([^;]+);", am).group(1)
    out.append(f"| {u} | {ar} | {rv['CLAIMED_BY']} | {rv['PARTIAL']} | {rv['NOT_MINE']} |")
obs = os.path.join(PKG, "_scripts", "R3_OBSERVATIONS.md")
out += ["", open(obs).read().rstrip("\n") if os.path.exists(obs) else "## Cross-package observations for R3\n\n(pending)"]
open(os.path.join(PKG, "PACKAGE_SUMMARY.md"), "w").write("\n".join(out) + "\n")
print("written")
