#!/usr/bin/env python3
"""Build R2/EXT/EXT_SUMMARY.md by script from the accepted EXT ledgers, errata,
CORRECTIONS.csv and the verifier verdicts. The hand-written R3 section is read from
R2/EXT/R3_OBSERVATIONS.md and embedded unchanged."""
import collections, os, re, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from extlib import EXT, LEDGERS, ledger_path, read_rows, sha, rel

ITEMS = {"3": "Item 3 — RULED decisions D-APP-86..127 (DEC)",
         "4": "Item 4 — release and validation documents (DOC)",
         "5": "Item 5 — decomposition scope ledger (SOW)",
         "6": "Item 6 — packaged product guidance `instructions/AGENTS.md` (audit-only)",
         "7": "Item 7 — harness developer docs `frontend/docs/harness/*.md` (audit-only)"}
HDN_TOKENS = ["NO", "R4", "R4-Q1", "R4-Q2", "R4-Q3", "R4-Q4", "R4-Q5"]

led = {}
for stem, item, folder in LEDGERS:
    p = ledger_path(stem, folder); _, rs = read_rows(p)
    ep = ledger_path(stem, folder, "errata")
    errata = read_rows(ep)[1] if os.path.exists(ep) else []
    led[stem] = dict(item=item, folder=folder, path=p, rows=rs, errata=errata)
corr_path = os.path.join(EXT, "CORRECTIONS.csv")
corr = read_rows(corr_path)[1] if os.path.exists(corr_path) else []
vp = os.path.join(EXT, "_verify", "VERDICTS.csv")
verdicts = read_rows(vp)[1] if os.path.exists(vp) else []


def apply(rows, patches, fld_key="Field", val_key="ProposedValue"):
    idx = {r["ClaimKey"]: dict(r) for r in rows}
    for e in patches:
        if e["ClaimKey"] in idx and e[fld_key] in idx[e["ClaimKey"]]:
            idx[e["ClaimKey"]][e[fld_key]] = e[val_key]
    return list(idx.values())


def reach(r):
    t = re.findall(r"REACH=(LIVE|LEGACY_ONLY|TEST_ONLY)", r["ImplementationEvidence"])
    return "+".join(sorted(set(t))) if t else "(no code tag)"


def hdn(r):
    return [t.strip() for t in r["HumanDecisionNeeded"].split(";") if t.strip()]


def census(rows, fn):
    c = collections.Counter()
    for r in rows:
        v = fn(r)
        for x in (v if isinstance(v, list) else [v]): c[x] += 1
    return c


def table(title, sealed, alt=None, alt_name=None):
    keys = sorted(set(sealed) | set(alt or {}), key=lambda k: (-sealed.get(k, 0), k))
    out = [f"**{title}**", ""]
    if alt is None:
        out += ["| Value | Rows |", "|---|---:|"] + [f"| `{k}` | {sealed.get(k, 0)} |" for k in keys]
    else:
        out += [f"| Value | Sealed | {alt_name} |", "|---|---:|---:|"]
        out += [f"| `{k}` | {sealed.get(k, 0)} | {alt.get(k, 0)} |" for k in keys]
    return out + [""]


def block(rows, errata_rows, corr_rows, label):
    out = []
    er = apply(rows, errata_rows) if errata_rows else None
    cr = apply(er or rows, corr_rows, "Field", "CorrectedValue") if corr_rows else None
    alt = cr or er
    alt_name = ("errata+corrections applied" if (er and cr) else "corrections applied" if cr else "errata applied" if er else None)
    for title, fn in [("Disposition", lambda r: r["Disposition"]), ("ClaimType", lambda r: r["ClaimType"]),
                      ("CauseTag", lambda r: r["CauseTag"]), ("AuthorityTier", lambda r: r["AuthorityTier"]),
                      ("REACH (code-evidence tags)", reach), ("HumanDecisionNeeded (tokens)", hdn),
                      ("Confidence", lambda r: r["Confidence"])]:
        out += table(f"{label}: {title}", census(rows, fn), census(alt, fn) if alt else None, alt_name)
    see = sum(1 for r in rows if "SEE:" in r["Notes"])
    split = sum(1 for r in rows if re.search(r"#?[A-Z0-9_-]+\d\.\d+$", r["ClaimKey"]) or re.search(r"\.\d+$", r["ClaimKey"]))
    out += [f"- Rows {len(rows)}; split sub-rows {split}; SEE rows {see}; errata rows {len(errata_rows)}; corrections {len(corr_rows)}.", ""]
    return out


def tokrows(rows, tok):
    return [r for r in rows if tok in r["Notes"]]


L = ["# EXT summary — R2 scope extension (items 3–7)", "",
     "> Generated by `R2/EXT/_scripts/summary.py` from the accepted EXT ledgers, errata,",
     "> `CORRECTIONS.csv` and `_verify/VERDICTS.csv`. Evidence, not rulings. The last section is",
     "> hand-written (`R3_OBSERVATIONS.md`, embedded unchanged).", ""]
L += ["## 1. Ledgers", "", "| Ledger | Item | Rows | Units covered | Errata | Corrections | SHA-256 |", "|---|---|---:|---:|---:|---:|---|"]
for stem, v in led.items():
    base = {re.sub(r"\.\d+$", "", r["ClaimKey"]) for r in v["rows"] if "STATE-" not in r["ClaimKey"] and "REGISTER-" not in r["ClaimKey"]}
    nc = sum(1 for c in corr if c["ClaimKey"] in {r["ClaimKey"] for r in v["rows"]})
    L.append(f"| `{rel(v['path'])}` | {v['item']} | {len(v['rows'])} | {len(base)} | {len(v['errata'])} | {nc} | `{sha(v['path'])}` |")
idx = [r for r in read_rows(os.path.join(os.path.dirname(os.path.dirname(EXT)), "R1_INVENTORY", "EXTENSION_INDEX.csv"))[1]]
units = {r["UnitKey"] for r in idx}
got = {re.sub(r"\.\d+$", "", r["ClaimKey"]) for v in led.values() for r in v["rows"]}
L += ["", f"- Total rows {sum(len(v['rows']) for v in led.values())}; EXTENSION_INDEX units covered "
      f"{len(units & got)} of {len(units)}; missing: {sorted(units - got) or 'none'}.", ""]

L += ["## 2. Censuses per item", ""]
for item, title in ITEMS.items():
    rows = [r for v in led.values() if v["item"] == item for r in v["rows"]]
    er = [e for v in led.values() if v["item"] == item for e in v["errata"]]
    keys = {r["ClaimKey"] for r in rows}
    cr = [c for c in corr if c["ClaimKey"] in keys]
    L += [f"### {title}", ""] + block(rows, er, cr, f"Item {item}")

L += ["## 3. Censuses per ledger (Disposition and HumanDecisionNeeded)", ""]
for stem, v in led.items():
    keys = {r["ClaimKey"] for r in v["rows"]}
    cr = [c for c in corr if c["ClaimKey"] in keys]
    d = census(v["rows"], lambda r: r["Disposition"]); hh = census(v["rows"], hdn)
    dc = census(apply(v["rows"], cr, "Field", "CorrectedValue"), lambda r: r["Disposition"]) if cr else None
    L.append(f"- `{stem}` ({len(v['rows'])} rows). Disposition: " + ", ".join(f"{k} {n}" for k, n in d.most_common())
             + (f". Corrected: " + ", ".join(f"{k} {n}" for k, n in dc.most_common()) if dc and dc != d else "")
             + ". HDN: " + ", ".join(f"{k} {n}" for k, n in hh.most_common()) + ".")
L += [""]

L += ["## 4. Verifier outcomes", ""]
if verdicts:
    per = collections.defaultdict(collections.Counter)
    for x in verdicts: per[x["Ledger"]][x["Verdict"]] += 1
    L += ["| Ledger | Verdict lines | CONFIRMED | REFUTED | CONTESTED | Distinct items |", "|---|---:|---:|---:|---:|---:|"]
    for stem in led:
        c = per.get(stem, collections.Counter()); n = len({x["ClaimKey"] for x in verdicts if x["Ledger"] == stem})
        L.append(f"| `{stem}` | {sum(c.values())} | {c['CONFIRMED']} | {c['REFUTED']} | {c['CONTESTED']} | {n} |")
    fc = collections.Counter(x["Field"] for x in verdicts if x["Verdict"] == "REFUTED")
    L += ["", "- REFUTED by field: " + ", ".join(f"{k} {n}" for k, n in fc.most_common()) + ".", ""]
else:
    L += ["- No verifier verdicts found.", ""]

allrows = [r | {"_stem": s} for s, v in led.items() for r in v["rows"]]
others = sorted({r["CauseTag"] for r in allrows if r["CauseTag"].startswith("OTHER:")} |
                {m for r in allrows for m in re.findall(r"CAUSE2:(OTHER:[A-Z0-9_]+)", r["Notes"])})
L += ["## 5. Tagged rows for R3", "", "- `OTHER:` cause tokens used: " + (", ".join(f"`{o}`" for o in others) or "none") + ".", ""]
for tok, title in [("EFFECT_NOT_LANDED", "Item 3: RULED decisions whose effect did not (fully) land"),
                   ("NO_LIVE_DELIVERABLE", "Item 5: SOW rows with no live deliverable"),
                   ("NO_CODE_NO_DEFERRAL", "Item 5: SOW IN rows with neither code nor an explicit deferral"),
                   ("RELEASE_PROCESS_NOT_RUN", "Item 4: sections describing a release or validation process that did not run")]:
    rs = tokrows(allrows, tok)
    L += [f"**{title}** ({len(rs)} rows)", "", "| ClaimKey | Disposition | HDN | Note token |", "|---|---|---|---|"]
    for r in rs:
        m = re.search(tok + r"(:[^;|]*)?", r["Notes"]); t = (m.group(0) if m else tok).strip().replace("|", "/")
        L.append(f"| `{r['ClaimKey']}` | {r['Disposition']} | {r['HumanDecisionNeeded']} | {t[:160]} |")
    L += [""]

plain = [r for r in allrows if "R4" in hdn(r)]
L += [f"**Plain `R4` rows (sealed before or without a named question; R3 maps them, e.g. to R4-Q6 under RUN_BASIS Addendum 9)** ({len(plain)} rows)", "",
      "| ClaimKey | Disposition | HDN |", "|---|---|---|"] + [f"| `{r['ClaimKey']}` | {r['Disposition']} | {r['HumanDecisionNeeded']} |" for r in plain] + [""]

obs = os.path.join(EXT, "R3_OBSERVATIONS.md")
L += ["## 6. Cross-package observations for R3 (hand-written)", ""]
L += [open(obs, encoding="utf-8").read().strip() if os.path.exists(obs) else "_(not yet written)_", ""]
open(os.path.join(EXT, "EXT_SUMMARY.md"), "w", encoding="utf-8").write("\n".join(L))
print("wrote EXT_SUMMARY.md", len(L), "lines")
