#!/usr/bin/env python3
"""Build R2/EXT/VERIFICATION.md by script: structural validator results, the per-ledger
recheck table and rerun test (RUN_BASIS Addendum 3), every REFUTED and CONTESTED verdict
line with its evidence (including lines graded against the superseded attempt), and the
hand-written patterns section from _verify/PATTERNS.md (embedded unchanged)."""
import collections, glob, os, subprocess, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from extlib import EXT, RUN, LEDGERS, SUPERSEDED, ledger_path, read_rows, sha, rel

VAL = os.path.join(RUN, "_scripts", "validate_ledger.py")


def validate(path, extra=()):
    r = subprocess.run(["python3", VAL, "ledger", *extra, path], capture_output=True, text=True)
    res = [l for l in r.stdout.splitlines() if l.startswith("RESULT")]
    return res[-1].replace("RESULT ", "") if res else "?"


L = ["# EXT verification — R2 scope extension (items 3–7)", "",
     "> Generated by `R2/EXT/_scripts/verification.py`. Verifier shards are fresh TASK agents that",
     "> share one grading key (`BRIEFS/V_SHARD.md`). Selection is `_scripts/select_verify.py`",
     "> (`_verify/SELECTION.csv`). CORRECTIONS.csv is built by `_scripts/corrections.py`.", ""]

L += ["## 1. Structural result", "", "| Ledger | Status | Validator | SHA-256 |", "|---|---|---|---|"]
for stem, item, folder in LEDGERS:
    p = ledger_path(stem, folder)
    L.append(f"| `{rel(p)}` | of record | {validate(p)} | `{sha(p)}` |")
for h in ("SOW_A", "SOW_B"):
    p = os.path.join(EXT, h, "SOW_claims.csv")
    L.append(f"| `{rel(p)}` | merge input | {validate(p, ['--extension-index', os.path.join(EXT, '_inputs', f'EXTENSION_INDEX_SOW_{h[-1]}.csv')])} (half index) | `{sha(p)}` |")
p = os.path.join(EXT, "DOC_DEV", "DOC-ADDING_A_TOOL_claims.csv")
L.append(f"| `{rel(p)}` | superseded (rerun, §4) | {validate(p)} | `{sha(p)}` |")
L += ["", "- No errata files were filed. Every forward ledger reached 0 errors and 0 warnings before return;",
      "  no structural send-back was needed.", ""]

_, sel = read_rows(os.path.join(EXT, "_verify", "SELECTION.csv"))
alllines = []
for p in sorted(glob.glob(os.path.join(EXT, "_verify", "V-*.csv"))):
    alllines += read_rows(p)[1]
cur = [x for x in alllines if (x["Shard"], x["Ledger"]) not in SUPERSEDED]
sup = [x for x in alllines if (x["Shard"], x["Ledger"]) in SUPERSEDED]
supsel = [s for s in read_rows(os.path.join(EXT, "_verify", "SELECTION_DOC67_snapshot.csv"))[1]
          if ("DOC67", s["Ledger"]) in SUPERSEDED]

cls = collections.Counter(s["Class"] for s in sel)
L += ["## 2. Selection", "",
      f"- {len(sel)} items on the ledgers of record: class a {cls['a']} (all LOW, self-flagged, AUTHORITY_CONFLICT, "
      f"UNKNOWN and REMAINING_WORK rows), b {cls['b']} (30% of other non-ALIGNED), c {cls['c']} (15% of ALIGNED), "
      f"r {cls['r']} (manager addition: the rerun ledger checked in full), e {cls['e']} (errata rows).",
      f"- Shards: " + ", ".join(f"`{k}` {v}" for k, v in sorted(collections.Counter(s['Shard'] for s in sel).items()))
      + f"; plus {len(supsel)} items graded on the superseded DOC-ADDING_A_TOOL attempt in shard `DOC67`.",
      "- Shard CSVs: " + ", ".join(f"`_verify/{os.path.basename(p)}` (`{sha(p)[:16]}…`)" for p in sorted(glob.glob(os.path.join(EXT, "_verify", "V-*.csv")))) + ".", ""]


def recheck(lines, selrows, label):
    out = [f"| Ledger | Items checked | Verdict lines | CONFIRMED | REFUTED | CONTESTED | Disposition REFUTED (items) | Rate | Rerun |",
           "|---|---:|---:|---:|---:|---:|---:|---:|---|"]
    by = collections.defaultdict(list)
    for x in lines: by[x["Ledger"]].append(x)
    chk = collections.defaultdict(set)
    for s in selrows: chk[s["Ledger"]].add(s["ClaimKey"])
    tot = collections.Counter()
    for stem in [l[0] for l in LEDGERS]:
        if stem not in chk: continue
        ls = by.get(stem, []); c = collections.Counter(x["Verdict"] for x in ls)
        dr = {x["ClaimKey"] for x in ls if x["Verdict"] == "REFUTED" and x["Field"] == "Disposition"}
        n = len(chk[stem]); rate = len(dr) / n if n else 0
        out.append(f"| `{stem}`{label} | {n} | {len(ls)} | {c['CONFIRMED']} | {c['REFUTED']} | {c['CONTESTED']} | {len(dr)} | {rate:.1%} | {'YES' if rate > 0.10 else 'no'} |")
        tot.update({"n": n, "lines": len(ls), "dr": len(dr), **c})
    return out, tot


t, tot = recheck(cur, sel, "")
L += ["## 3. Recheck table (ledgers of record)", ""] + t
L += ["", f"- Totals: {tot['n']} items, {tot['lines']} verdict lines: CONFIRMED {tot['CONFIRMED']}, REFUTED {tot['REFUTED']}, "
      f"CONTESTED {tot['CONTESTED']}. Disposition refutations {tot['dr']} of {tot['n']} items ({tot['dr']/max(tot['n'],1):.1%}).",
      "- Rerun rule (RUN_BASIS Addendum 3): structural failure, or > 10% of checked distinct rows REFUTED on Disposition.",
      "  Non-verdict refutations go to `CORRECTIONS.csv`.", ""]
t2, _ = recheck(sup, supsel, " (superseded attempt)")
L += ["**Superseded attempt** (`DOC_DEV/DOC-ADDING_A_TOOL_claims.csv`, graded in shard DOC67):", ""] + t2 + [""]


def listing(lines, title):
    out = [f"### {title}", "", "| Shard | ClaimKey | Verdict | Field | RowValue | CorrectReading | Evidence | ConventionIssue |",
           "|---|---|---|---|---|---|---|---|"]
    esc = lambda s: (s or "").replace("|", "/").replace("\n", " ")
    for x in lines:
        if x["Verdict"] in ("REFUTED", "CONTESTED"):
            out.append(f"| {x['Shard']} | `{x['ClaimKey']}` | {x['Verdict']} | {x['Field']} | {esc(x['RowValue'])} | "
                       f"{esc(x['CorrectReading'])} | {esc(x['Evidence'])} | {esc(x['ConventionIssue'])} |")
    return out + [""]


L += ["## 4. Every REFUTED and CONTESTED item", ""]
L += listing(cur, "Ledgers of record")
L += listing(sup, "Superseded attempt (DOC_DEV/DOC-ADDING_A_TOOL), verdict refutation that triggered the rerun")
_, corr = read_rows(os.path.join(EXT, "CORRECTIONS.csv"))
L += [f"- `CORRECTIONS.csv`: {len(corr)} rows (non-verdict fields), SHA-256 `{sha(os.path.join(EXT, 'CORRECTIONS.csv'))}`.",
      "- A verdict-field refutation below the rerun threshold (SOW:SOW-045.2) is not a correction: the sealed Disposition",
      "  stands and R3 sees the verifier's reading here.", ""]
pat = os.path.join(EXT, "_verify", "PATTERNS.md")
L += ["## 5. Reruns and patterns (hand-written)", "", open(pat, encoding="utf-8").read().strip() if os.path.exists(pat) else "_(pending)_", ""]
open(os.path.join(EXT, "VERIFICATION.md"), "w", encoding="utf-8").write("\n".join(L))
print("wrote VERIFICATION.md", len(L))
