// Builds the static frames, the contact page and the sample-model document (second pass, MOCKS-02:
// design system V1.1, tokens.json 1.1). Reads the design system's tokens.json (read-only) and
// writes only under instances/MOCKS/.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { frames } from "./frames.mjs";
import { sprite } from "./ui.mjs";
import * as M from "./model.mjs";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "..");
const framesDir = path.join(root, "frames");
const tokensFile = path.resolve(root, "..", "DESIGN-SYSTEM", "tokens.json");
const T = JSON.parse(fs.readFileSync(tokensFile, "utf8"));

// ---- tokens.css, with the mapping of the design system's gen.mjs ----
function tokensCss() {
  const v = (k) => "--" + k.replace(/\./g, "-");
  const px = (n) => (typeof n === "number" ? n + "px" : n);
  const plain = [];
  for (const [k, val] of Object.entries(T.type)) {
    if (k.startsWith("family.")) plain.push(`  --font-${k.slice(7)}: ${val};`);
    else if (k === "numeric.feature") continue;
    else if (k.startsWith("weight.")) plain.push(`  ${v("type." + k)}: ${val};`);
    else plain.push(`  ${v("type." + k)}: ${px(val)};`);
  }
  for (const [k, val] of Object.entries(T.space)) plain.push(`  --space-${k}: ${px(val)};`);
  for (const [k, val] of Object.entries(T.radius)) plain.push(`  --radius-${k}: ${px(val)};`);
  for (const [k, val] of Object.entries(T.border)) plain.push(`  --border-width-${k}: ${px(val)};`);
  for (const [k, val] of Object.entries(T.layout)) { if (Array.isArray(val)) continue; plain.push(`  ${v("layout." + k)}: ${px(val)};`); }
  for (const [k, val] of Object.entries(T.motion)) {
    if (k.endsWith(".ms")) plain.push(`  ${v("motion." + k)}: ${val}ms;`);
    else if (k.startsWith("easing.")) plain.push(`  --easing-${k.slice(7)}: ${val};`);
  }
  plain.push(`  --icon-stroke: ${px(T.icon.stroke)};`);
  const themed = (theme) => {
    const out = [];
    for (const [k, val] of Object.entries(T.color)) out.push(`  ${v(k)}: ${val[theme]};`);
    for (const [k, val] of Object.entries(T.elevation)) if (typeof val === "object") out.push(`  --elevation-${k}: ${val[theme]};`);
    return out.join("\n");
  };
  const n = Object.keys(T.color).length;
  return `/* Generated by tools/build.mjs from ../DESIGN-SYSTEM/tokens.json (${n} colour tokens, version ${T.version}) with the mapping of the design system's gen.mjs. Do not edit by hand. */
:root {
${plain.join("\n")}
}
:root, :root[data-theme="light"] {
  color-scheme: light;
${themed("light")}
}
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
    color-scheme: dark;
${themed("dark").replace(/^/gm, "  ")}
  }
}
:root[data-theme="dark"] {
  color-scheme: dark;
${themed("dark")}
}
`;
}

// ---- the page around a frame ----
// Each HTML file is self-contained: the generated tokens.css and the shared mocks.css are inlined
// into a <style> block, because the owner's review surface renders a local HTML file from its
// bytes alone and would not resolve a relative <link>.
let TOKENS_CSS = "", MOCKS_CSS = "";
const styleBlock = () => `<style>\n/* tokens.css, inlined */\n${TOKENS_CSS}\n/* mocks.css, inlined */\n${MOCKS_CSS}</style>`;
function page(f, inner) {
  return `<!doctype html>
<html lang="en" data-theme="${f.theme}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>SWBPIPE mock · ${f.file}</title>
${styleBlock()}
</head>
<body>
<div class="mockbar"><b>SWB Piping Designer · mock frame ${f.file}</b>${f.aid ? `<span class="aid">${f.aid}</span>` : ""}<span>State ${f.state} · ${f.stateName}</span><span>${f.stage} · ${f.view} view · ${f.theme}</span><span class="grow"></span><span>Theme</span><div class="seg" id="themeseg" role="group" aria-label="Theme"><span data-theme="light">Light</span><span data-theme="dark">Dark</span><span data-theme="system">System</span></div><a href="index.html">All frames</a></div>
<div class="viewport"><div class="scalebox" id="scalebox"><div class="scaler" id="scaler"><div class="stage" id="stage">${sprite()}${inner}</div></div></div></div>
<script>
(function () {
  // Only the theme switch and the scaling: nothing else in a frame is live.
  var root = document.documentElement, seg = document.getElementById("themeseg");
  function setTheme(t) {
    if (t === "system") root.removeAttribute("data-theme"); else root.setAttribute("data-theme", t);
    var spans = seg.querySelectorAll("span"); for (var i = 0; i < spans.length; i++) spans[i].setAttribute("aria-pressed", String(spans[i].getAttribute("data-theme") === t));
  }
  seg.addEventListener("click", function (e) { var s = e.target.closest("span[data-theme]"); if (s) setTheme(s.getAttribute("data-theme")); });
  setTheme("${f.theme}");
  var box = document.getElementById("scalebox"), sc = document.getElementById("scaler"), vp = box.parentNode;
  function fit() {
    var w = vp.clientWidth - 32, h = window.innerHeight - vp.getBoundingClientRect().top - 32;
    var s = Math.min(1, w / 1440, h / 900); if (!(s > 0.1)) s = 0.1;
    sc.style.transform = "scale(" + s + ")";
    box.style.width = Math.round(1440 * s) + "px"; box.style.height = Math.round(900 * s) + "px";
    root.setAttribute("data-scale", s.toFixed(3));
  }
  window.addEventListener("resize", fit); fit();
})();
</script>
</body>
</html>
`;
}

// ---- index.html ----
function index() {
  const rows = frames.map((f) => `<tr><td class="n">${f.state}</td><td><a href="${f.file}.html">${f.file}</a>${f.aid ? `<div class="aid" style="margin-top:4px">${f.aid}</div>` : ""}</td><td>${f.stage}</td><td>${f.view}</td><td>${f.theme}</td><td>${f.tests}</td><td>${f.look}</td></tr>`).join("\n");
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>SWBPIPE mock frames</title>
${styleBlock()}
<style>
  .wrap { max-width: 1320px; margin: 0 auto; padding: 24px 16px 48px; }
  h1 { font-size: var(--type-size-heading); line-height: var(--type-lineHeight-heading); font-weight: 600; margin: 0 0 4px; }
  h2 { font-size: var(--type-size-title); line-height: var(--type-lineHeight-title); font-weight: 600; margin: 24px 0 8px; }
  .wrap p { margin: 0 0 8px; max-width: 820px; }
  table.ds td { white-space: normal; height: auto; padding: 6px 8px; vertical-align: top; }
  table.ds th.n, table.ds td.n { text-align: right; }
  table.ds td a { font-weight: 500; overflow-wrap: anywhere; }
  table.ds td .aid { display: inline-block; height: auto; white-space: normal; line-height: 14px; padding: 2px 6px; }
</style>
</head>
<body>
<div class="wrap">
<h1>SWB Piping Designer · mock frames</h1>
<p class="sec">Second pass (MOCKS-02): eighteen static frames of the nine workflow states, drawn from design system V1.1 (tokens.json 1.1, specimen.html V1.1) with the fourteen decisions of the direction record §11 applied and the UX specification's behaviour, on one sample model. Sixteen frames draw the design; the two frames labelled "Decision aid" draw alternatives for decision packet D-71 items 1 and 2 and are not the design system's rule. Each frame is the whole 1440 × 900 window and scales down as a whole in a narrower pane. Nothing in a frame works except the theme switch in the caption bar. Every value is a placeholder: the sample model and its results are illustrative, not engine output.</p>
<p><a href="../sample_model.md">The sample model</a> · <a href="../MOCKS_V2.md">MOCKS_V2.md</a> (what changed per frame, departures, questions, gaps) · <a href="../MOCKS_V1.md">MOCKS_V1.md</a> (the first pass, history) · <a href="../RETURN.md">RETURN.md</a></p>
<h2>Frames</h2>
<table class="ds"><colgroup><col style="width:44px"><col style="width:200px"><col style="width:66px"><col style="width:56px"><col style="width:62px"><col style="width:300px"><col></colgroup><thead><tr><th class="n">State</th><th>Frame</th><th>Stage</th><th>View</th><th>Theme</th><th>What it tests</th><th>What to look at</th></tr></thead><tbody>
${rows}
</tbody></table>
<h2>Reading a frame</h2>
<p>The caption bar above the window is not product chrome. The window is the toolbar band, the stage rail, the surfaces in the named view, the agent column or strip and the status bar, at the geometry of design system §0; in Both view the inspector docks on the canvas's right edge and the canvas shrinks while it is open (decision 1). The canvas in a frame is a schematic figure drawn in the design system's figure language and labelled as a mock rendering. A frame carrying the label "Decision aid · D-71 item n · option A" in its caption bar and its toolbar band draws one option of the owner's decision packet and not the design's rule.</p>
</div>
</body>
</html>
`;
}

// ---- sample_model.md ----
function sampleModel() {
  const t = (heads, rows) => `| ${heads.join(" | ")} |\n| ${heads.map((h) => /\[/.test(h) || ["Node", "From", "Ratio", "Friction μ", "μ", "Row"].includes(h) ? "---:" : "---").join(" | ")} |\n${rows.map((r) => `| ${r.join(" | ")} |`).join("\n")}\n`;
  const C = M.coordinates();
  const n0 = (v) => (v < 0 ? "−" : "") + Math.abs(v);
  const pv = (r, k, v) => (v == null ? "—" : v + (r.entered.includes(k) ? "" : " ↓"));
  const rows = M.rows.map((r) => [r.node, r.from ?? "—", r.type ?? "—", n0(r.dx), n0(r.dy), n0(r.dz), pv(r, "section", r.section), pv(r, "material", r.material), pv(r, "load", r.load), `${C[r.node].x}, ${C[r.node].y}, ${C[r.node].z}`, r.branch ? "branch from the tee at 70" : r.bendR ? `bend R ${r.bendR}` : r.valveWeight ? `valve, ${r.valveWeight} N` : r.reducer ? "reducer P1→P2" : ""]);
  const exp1 = M.stressRows("EXP1");
  const env = M.envelopeRows();
  return `# Sample model — Loop 4 header

**Sample.** One small fictional piping system used in every mock frame so that the nine states read as one project. Every number is a placeholder chosen to be plausible to a stress engineer; nothing here is engine output, and the result values are illustrative, not computed. Units: SI (mm, °C, bar, N, kN, kN·m, MPa, N/mm). Vertical axis Y. Engineer in the frames: ${M.project.engineer}. Project file: "${M.project.name}".

${M.project.description}

## Node rows (the layout grammar)

One row per node; the row carries the element that arrives at the node (From → Node), its length as DX DY DZ from the From node, and the section, material and load set in force on that element. A value marked ↓ is propagated from the row above by connectivity; the rest were typed (entered). Node 140 is a branch: its From names the tee at 70.

${t(["Node", "From", "Type", "DX [mm]", "DY [mm]", "DZ [mm]", "Section", "Material", "Load set", "X, Y, Z [mm]", "Note"], rows)}
Bends are at nodes 30, 50, 110 and 150 (bend nodes carry their radius); the valve is element 80–90 (1 200 N); the reducer 90–100 goes from P1 to P2; the welding tee at 70 is node data, not a row.

## Sections

${t(["Section", "Nominal", "OD [mm]", "Wall [mm]", "Corrosion [mm]", "Mill tol. [%]", "Insulation [mm]", "Bend R [mm]", "Origin"], M.sections.map((s) => [s.name, s.nominal, s.od, s.wall, s.ca, s.millTol, s.insThk, s.bendR, s.origin]))}
## Materials

${t(["Material", "Description", "E 20 °C [MPa]", "E 150 °C [MPa]", "α [µm/m·K]", "Density [kg/m³]", "Sc [MPa]", "Sh [MPa]", "Source"], M.materials.map((m) => [m.name, m.desc, m.E20, m.E150, m.alpha, m.density, m.Sc, m.Sh150, m.source]))}
CS-B's provenance is deliberately unrecorded: it produces the one Provenance warning (node 140) that stays open through states 4 to 9.

## Load sets (read through on the node row)

${t(["Set", "T1 [°C]", "P1 [bar]", "T2 [°C]", "P2 [bar]", "Note"], M.loadSets.map((s) => [s.name, s.T1, s.P1.toFixed(2), s.T2, s.P2.toFixed(2), s.note]))}
## Restraints

${t(["Node", "Tag", "Type", "Direction", "Gap [mm]", "μ", "Stiffness", "Library", "Max variation [%]", "Origin", "Note"], M.restraints.map((r) => [r.node, r.tag, r.type, r.direction, r.gap ?? "—", r.mu != null ? r.mu.toFixed(2) : "—", r.stiffness, r.library || "—", r.maxVar ?? "—", r.origin === "accepted" ? `accepted from ${r.proposal}` : "entered", r.note]))}
## Loads

${t(["Node", "Kind", "Direction", "Value", "Unit", "Case", "Note"], M.loads.map((l) => [l.node, l.kind, l.direction, n0(l.value), l.unit, l.case, l.note]))}
Seismic: ${M.seismic.map((s) => `${s.name} = ${s.g} g in ${s.direction} (${s.note})`).join("; ")}.

## Node data

${t(["Node", "Kind", "Value", "Detail"], M.nodeData.map((n) => [n.node, n.kind, n.value, n.detail]))}
## Rule pack (sample)

\`${M.rulePack.name} ${M.rulePack.version}\` · ${M.rulePack.sha} · ${M.rulePack.source}. The rule expressions below are rendered display-only in the product; the allowables are invented for this sample.

${t(["Rule", "Name", "Expression (display only)", "Allowable CS-A [MPa]", "Allowable CS-B [MPa]"], M.rules.map((r) => [r.id, r.name, r.expr, r.allowable["CS-A"], r.allowable["CS-B"]]))}
## Load cases

Generated from the rule pack on 2026-09-17 10:05, one row edited and one authored:

${t(["Case", "Expression", "Stress type", "Rule", "Origin"], M.cases.map((c) => [c.name, c.expr, c.type, c.rule || "—", c.origin === "generated" ? `generated · ${c.who}` : c.origin === "edited" ? `edited by ${c.who} · was ${c.was} (generated)` : `authored by ${c.who}`]))}
## Runs

${t(["Run", "When", "Outcome", "Settings", "Note"], M.runs.map((r) => [r.id, r.when, r.outcome, r.settings || "—", r.note]))}
Run 03 is the solved run of state 7 (evidence label INTERNALLY_VERIFIED, ${M.runs[2].sha}, solver ${M.runs[2].solver}); Run 02 is the failed run of state 6; Run 04 is the run the Review page (state 9) reports after proposal P-12 row 1 was accepted.

## Results of Run 03 (state 7) — sample values

Stresses at the To node of each element for case EXP1, sorted by ratio; the ratio is stress over the rule allowable for the element's material, and every ratio is shown with its rule ID and pack version.

${t(["Node", "Element", "Case", "Stress [MPa]", "Allowable [MPa]", "Ratio", "Rule", "Pack"], exp1.map((r) => [r.node, r.element, r.case, r.stress.toFixed(1), r.allowable.toFixed(1), r.ratio.toFixed(2), r.rule, r.pack]))}
Envelope (governing case per element):

${t(["Node", "Element", "Governing case", "Stress [MPa]", "Allowable [MPa]", "Ratio", "Rule", "Pack"], env.map((r) => [r.node, r.element, r.case, r.stress.toFixed(1), r.allowable.toFixed(1), r.ratio.toFixed(2), r.rule, r.pack]))}
Governing: node ${M.governing.node}, element ${M.governing.element}, ${M.governing.case}, ${M.governing.stress} / ${M.governing.allowable} MPa = ${M.governing.ratio.toFixed(2)} · ${M.governing.rule} · pack ${M.governing.pack}.

Restraint loads used in the story (Run 03): node 80 W +4.18 kN, OPE1 −9.8 kN; node 130 OPE1 7.4 kN, Mz 3.1 kN·m. OPE1 vertical displacements: node 40 +3.9, 50 +6.2, 60 +5.9, 70 +4.1, 80 0.0, 120 +4.3, 130 +4.0 mm.

## Hanger design (state 8)

Library: ${M.hangerLibrary.name} (${M.hangerLibrary.provenance}, ${M.hangerLibrary.sizes} sizes, imported ${M.hangerLibrary.imported}).

${t(["Node", "Tag", "Type", "Design load [N]", "Travel [mm]", "Library", "Size", "Rate [N/mm]", "Cold load [N]", "Hot load [N]", "Variation [%]"], M.hangers.map((h) => [h.node, h.tag, h.type, h.designLoad, "+" + h.travel.toFixed(1), h.library, h.size, h.rate, h.coldLoad, h.hotLoad, h.variation.toFixed(1)]))}
## Proposals

${M.proposals.map((p) => `**${p.id} — ${p.title}** (${p.when}${p.state ? `, ${p.state}` : ""})${p.asked ? `\nAsked by ${p.asked.who} at ${p.asked.when}: "${p.asked.text}"` : ""}\n\n${t(["Row", "Table", "Node", "Field", "Old", "New"], p.rows.flatMap((r, i) => r.fields.map((f, j) => [j === 0 ? i + 1 : "", j === 0 ? r.table : "", j === 0 ? r.node : "", f[0], f[1], f[2]])))}${p.rationale ? `Rationale: ${p.rationale}\n` : ""}${p.constraints ? `\nConstraints considered: ${p.constraints.join("; ")}.\n` : ""}${p.tbd ? `\nTBD: ${p.tbd.join("; ")}.\n` : ""}`).join("\n")}
In the frames, P-12 row 1 is accepted at 16:31 (state 8, Table) and row 2 is still pending on the Review page (state 9).

## Run 04 envelope (state 9, the Review page's live table)

${t(["Node", "Element", "Governing case", "Stress [MPa]", "Allowable [MPa]", "Ratio", "Rule", "Pack"], M.run04Envelope.map((r) => [r.node, r.element, r.case, r.stress.toFixed(1), r.allowable.toFixed(1), r.ratio.toFixed(2), r.rule, r.pack]))}
Sample. These values illustrate the screens; they are not the output of any solver or rule check.
`;
}

fs.mkdirSync(framesDir, { recursive: true });
TOKENS_CSS = tokensCss();
fs.writeFileSync(path.join(framesDir, "tokens.css"), TOKENS_CSS);
MOCKS_CSS = fs.readFileSync(path.join(framesDir, "mocks.css"), "utf8");
for (const f of frames) fs.writeFileSync(path.join(framesDir, `${f.file}.html`), page(f, f.body()));
fs.writeFileSync(path.join(framesDir, "index.html"), index());
fs.writeFileSync(path.join(root, "sample_model.md"), sampleModel());
console.log(`built ${frames.length} self-contained frames, index.html, tokens.css (${Object.keys(T.color).length} colour tokens, version ${T.version}), sample_model.md`);
