from pathlib import Path
import csv,json,hashlib,re
root=Path.cwd(); b=Path('projects/pec/execution/_Reconciliation/DeliverableConcordance/PEC_REMAINING_CONCORDANCE_2026-09-05'); run=b/'R1_R4_2026-09-05'; pkg=run/'PACKAGES/PKG-06';w=pkg/'WORKERS/DEL-06-02';d=Path('projects/pec/execution/PKG-06_Presence_Git_Observation/1_Working/DEL-06-02_Git_worktree_scanner');decomp=Path('projects/pec/execution/_Decomposition');dec=Path('projects/pec/execution/_Coordination/_DECISIONS');commit='2be412ccea62bdc4bd96deb082c46d7a792076ea'
H=lambda x:hashlib.sha256(x).hexdigest()
inputs={Path(x) for x in ['AGENTS.md','agents/AGENT_TASK.md','projects/pec/AGENTS.md','docs/DELIVERABLE_CONCORDANCE_METHOD.md','projects/pec/docs/PRD.md','projects/pec/docs/STATUS.md','projects/pec/execution/_Scripts/pec_reliance_hold.py','projects/pec/execution/_Coordination/ACTIVE_RELIANCE_HOLDS.csv']}
inputs.update(p for p in d.rglob('*') if p.is_file())
inputs.update(decomp/x for x in ['_LATEST.md','SOFTWARE_DECOMP.md','Deliverables.csv','ScopeLedger.csv'])
inputs.update([b/'CONVENTIONS.md',pkg/'PACKAGE_BASIS.md',pkg/'SOURCE_MANIFEST.json',pkg/'BRIEFS/DEL-06-02.md',run/'COMMON/BRIEFS/PKG-06.md',run/'COMMON/BRIEF_CLARIFICATION_01.md',run/'COMMON/RUN_BASIS.md',run/'COMMON/SOURCE_MANIFEST.json',run/'COMMON/SCOPE_CENSUS.csv',run/'COMMON/AGENT0_GRAPH.md'])
# rg consumed these bounded search corpora; retain all scanned file identities, not just matches.
for directory in [dec,Path('projects/pec/v2'),Path('projects/pec/execution/_Evaluation/Reviews')]:inputs.update(p for p in directory.rglob('*') if p.is_file() and '__pycache__' not in p.parts)
hashes={str(p):H(p.read_bytes()) for p in sorted(inputs)}
frozen=json.loads((run/'COMMON/SOURCE_MANIFEST.json').read_text())['hashes']; mismatches={p:[h,frozen[p]] for p,h in hashes.items() if p in frozen and h!=frozen[p]};assert not mismatches,mismatches
checks=json.loads((w/'preflights.json').read_text())+[json.loads((w/'discovery.json').read_text())]
checks.append({'command':'compare every input available in COMMON/SOURCE_MANIFEST.json','cwd':str(root),'environment':{},'exit_code':0,'result':{'matched':sum(p in frozen for p in hashes),'mismatches':mismatches,'unfrozen_inputs':'Operational briefs/manifests or discovery-only search identities; not silently promoted to accepted scope.'}})
fields='ClaimID,DeliverableID,ClaimClass,NormativeSource,ScopeItemIDs,DeclaredSource,CurrentState,ImplementationEvidence,VerificationEvidence,ValidationOrProvenanceEvidence,LifecycleEvidence,ExistingRemaining,Disposition,ProposedResidualID,ProposedResidualText,Depends,ExactGate,AuthorityNeeded,Selectability,SourceCommit,SourceHashes,EvidenceReferences,Notes'.split(',')
rfields='ResidualID,DeliverableID,ClaimIDs,ProposedText,Depends,ExactGate,ClosureEvidence,AuthorityNeeded,Selectability,Notes'.split(',')
prd='projects/pec/docs/PRD.md';scope=str(decomp/'SOFTWARE_DECOMP.md');ledger=str(decomp/'ScopeLedger.csv');dels=str(decomp/'Deliverables.csv');context=str(d/'_CONTEXT.md');status=str(d/'_STATUS.md');deps=str(d/'Dependencies.csv')
quote='Scan Git for worktrees, branches, HEAD, ahead/behind counts, and dirty path names/counts';qh=H(quote.encode());scope_map=f'{scope} §2.1 SOW-027; quote={quote}; quote_sha256={qh}; {ledger} row SOW-027 → DEL-06-02 → OBJ-003'
basegate='(gated: later exact owner Remaining application; D82 authorizes reporting only; product/source acts require separately ruled F-PEC-1 scope)'
resid='DEL-06-02-REM-001';proposal='Establish source-bound evidence for accepted SOW-027 Git/worktree scanning and its tests: identify the current authorized implementation and claim-relevant verification for worktrees, branches, HEAD, ahead/behind, dirty path names/counts, read-only Git operation and never capturing file/diff content; return unresolved scope or implementation questions for owner disposition.'
impl='Current projects/pec/v2/src files inspected: loop-registry port and JSON adapter; no claim-specific scanner identified in this bounded corpus. This is not proof of global implementation absence.'
verify='No DEL-06-02/PEC-PRS-002/SOW-027 match in bounded current v2 and PEC review search (discovery.json exit 1). No scanner test method executed or PASS claimed.'
rows=[]
def add(local,cls,norm,statement,disp='UNKNOWN',notes='',depends='NONE'):
 unknown=disp=='UNKNOWN'; sources=[prd,scope,ledger,dels,context,status,deps]
 row=dict.fromkeys(fields,'NONE');row.update(ClaimID='DEL-06-02::'+local,DeliverableID='DEL-06-02',ClaimClass=cls,NormativeSource=norm,ScopeItemIDs='SOW-027',DeclaredSource=context+'; '+status,CurrentState=statement,ImplementationEvidence=impl if unknown else 'Not an implementation claim',VerificationEvidence=verify if unknown else 'Direct documentary comparison; no product test claim',ValidationOrProvenanceEvidence=scope_map,LifecycleEvidence=status+' Current State OPEN; 2026-07-25 PREPARATION',ExistingRemaining=status+' has no ## Remaining; emptiness is not warranted NONE',Disposition=disp,ProposedResidualID=resid if unknown else 'NONE',ProposedResidualText=proposal if unknown else 'NONE',Depends=depends,ExactGate=basegate,AuthorityNeeded='Later exact owner application; any source production requires its own ruled paths/acts',Selectability='NON_SELECTABLE_PENDING_OWNER_APPLICATION',SourceCommit=commit,SourceHashes=json.dumps({p:hashes[p] for p in sources},sort_keys=True),EvidenceReferences='; '.join(sources)+('; '+str(w/'discovery.json') if unknown else ''),Notes=notes+(' Evidence-gap candidate only; not an accepted assertion of unimplemented product work. No assignment, lifecycle, release, runtime or external consumer authority transferred.' if unknown else ' Documentary alignment only; no product completion inferred.'))
 rows.append(row)
add('PEC-PRS-002','observed behavior',prd+' §9.4 PEC-PRS-002; '+scope+' §2.1 SOW-027','UNKNOWN whether current v2 scans Git worktrees. Stable source requirement retained; other atomic clauses mapped below.',notes='PEC-PRS-002 is decomposed into the following clause rows rather than treated as one all-input guarantee.')
for i,(word,text) in enumerate([('branches','scan Git branches'),('HEAD','observe HEAD'),('ahead','report ahead counts'),('behind','report behind counts'),('dirty-names','report dirty path names'),('dirty-counts','report dirty path counts')],1):
 add('SOW-027-C%02d'%i,'observed behavior',scope+' §2.1 SOW-027; '+prd+' §9.4 PEC-PRS-002','UNKNOWN whether current authorized v2 can '+text+'.',notes=f'Run-local fallback C{i:02d} maps exact SOW-027 phrase {word}; full exact quote/hash in provenance.')
add('PEC-K-06','observed behavior',prd+' §6 PEC-K-06; '+dels+' row DEL-06-02','UNKNOWN whether the scanner performs read-only Git observation without leases, claim arbitration, merge opinions or dispatch.',notes='Scanner-specific boundary; this does not audit runtime confinement or confer runtime session ownership.')
add('PEC-K-10','observed behavior',prd+' §6 PEC-K-10 and §9.4 PEC-PRS-002; '+ledger+' row SOW-027 Notes C6','UNKNOWN whether scanner capture excludes all file and diff content; names/counts only.',notes='Material SOW-027 constraint C6. Do not mistake content-minimal scope text for tested universal behavior.')
add('ARTIFACT-TESTS','finite test method',dels+' row DEL-06-02 AnticipatedArtifacts Scanner + tests','UNKNOWN scanner-specific test artifacts/method coverage; no finite PASS or failed test claimed.',notes='Fallback artifact claim mapped to exact Scanner + tests text; quote_sha256='+H(b'Scanner + tests'))
add('SOW-027','documentary alignment',scope+' §2.1 SOW-027; '+ledger+' row SOW-027','Accepted SOW-027 IN maps to PKG-06 / DEL-06-02 / OBJ-003; local context restates this scope.','ALIGNED','ScopeOfWork.md absent; 0 local REQ/AC/VER IDs defined. Accepted decomposition fallback used, not invented contract.')
add('RESPONSIBLE-PARTY','documentary alignment',dels+' row DEL-06-02 ResponsibleParty; '+context,'ResponsibleParty truthfully TBD (assignment at WORKING_ITEMS activation).','ALIGNED','Fallback metadata ID; administrative assignment does not create a product residual. No automatic TM mirror.')
add('LIFECYCLE-OPEN','lifecycle',status,'Local lifecycle remains OPEN, set by PREPARATION on 2026-07-25.','ALIGNED','Records the existing declaration only; no release/issuance acceptance or reversal inferred.')
add('DEP-06-02-003','documentary alignment',deps+' row DEP-06-02-003','ACTIVE EXECUTION PREREQUISITE → DEL-01-02; RequiredMaturity INITIALIZED; SatisfactionStatus PENDING; original PROPOSAL provenance preserved.','ALIGNED','Only a future item naming DEL-01-02 in Depends is dependency-blocked by this row. Discovery evidence does not wait, satisfy, or flip this register. Repair run changed evidence cells only. Human-view CONSUMES is historical graph wording; structured row governs actual Depends semantics.',depends='DEL-01-02')
res=[dict(zip(rfields,[resid,'DEL-06-02',';'.join(r['ClaimID'] for r in rows if r['Disposition']=='UNKNOWN'),proposal,'NONE',basegate,'Exact current implementation locator and hashes plus scanner-relevant tests/results for each linked claim, or explicit owner disposition of unresolved evidence; preserve scope and acceptance history.','Later exact owner Remaining application; source repair/production requires separately opened F-PEC-1 paths','NON_SELECTABLE_PENDING_OWNER_APPLICATION','Candidacy=EVIDENCE_GAP; routing=OWNER_EVIDENCE_RECONCILIATION_CANDIDATE; not DOCUMENTED_UNIMPLEMENTED, not executable production. Depends NONE because this is evidence discovery; subsequent production item naming DEL-01-02 retains ACTIVE/PENDING prerequisite. No automatic administrative/release/TM mirror.']))]
for name,columns,data in [('CLAIMS.csv',fields,rows),('RESIDUALS.csv',rfields,res)]:
 with (w/name).open('w',newline='') as f:wr=csv.DictWriter(f,fieldnames=columns,lineterminator='\n');wr.writeheader();wr.writerows(data)
assert len(rows)==14 and sum(r['Disposition']=='UNKNOWN' for r in rows)==10
assert all(r['Depends'] and '(gated:' in r['ExactGate'] for r in rows+res)
assert set(res[0]['ClaimIDs'].split(';'))=={r['ClaimID'] for r in rows if r['ProposedResidualID']==resid}
checks.append({'command':'CSV exact columns, unique IDs, canonical residual sequence, reciprocal links, gate/Depends markers, LF and counts','cwd':str(root),'environment':{},'exit_code':0,'result':'PASS: 14 claims, 10 UNKNOWN, 4 ALIGNED, 1 residual; ASSESSED_UNKNOWN; warranted NONE false'})
source_unchanged=all(H(Path(p).read_bytes())==h for p,h in hashes.items());assert source_unchanged
(w/'READ_MANIFEST.json').write_text(json.dumps(dict(source_commit=commit,hashes=hashes,historical_sources=[],checks=checks,source_unchanged=source_unchanged),indent=2)+'\n')
(w/'COVERAGE.md').write_text(f'''# DEL-06-02 coverage

Derivative R1–R4 report under effective D82, source base `{commit}`; accepted revision 1.4 scope and accepted D81 conventions. Status ASSESSED_UNKNOWN. 14 claims: 10 UNKNOWN / 4 documentary-or-lifecycle ALIGNED. One evidence-gap residual; zero asserted product repairs and no warranted NONE.

## Claim census and mapping

ScopeOfWork.md is absent (actual exact-file candidate-validation ALLOW recorded). No local REQ/AC/VER IDs are defined in the seven present deliverable files. No missing contract was invented. Stable PEC-PRS-002 covers worktree scanning, SOW-027-C01..06 atomize branches, HEAD, ahead, behind, dirty names and dirty counts. PEC-K-06 and PEC-K-10 cover read-only and content-minimal constraints; ARTIFACT-TESTS maps the accepted Scanner + tests artifact statement. SOW-027, RESPONSIBLE-PARTY, LIFECYCLE-OPEN and DEP-06-02-003 map scope, truthful TBD, lifecycle and prerequisite metadata. All fallback IDs are run-local labels, never new normative requirements.

Exact missing-contract mapping: {scope_map}. Deliverables.csv row DEL-06-02 adds `Read-only scan of worktrees, branches, HEAD, ahead/behind, dirty path names/counts; never content.` and `Scanner + tests`; exact file hashes are in every row and READ_MANIFEST.

DEP-06-02-001 and -002 are structural package/scope anchors covered by SOW-027, not independent product requirements. E-P40 is the graph lineage of DEP-06-02-003; E-P42 is informational downstream consumption by DEL-06-03, not a prerequisite of this worker. C-04 is phase ordering; C-10 is provenance classification, neither becomes an automatic blocker. Type, envelope M, phase P3 and OBJ-003 are descriptive planning metadata covered by context/scope mapping, not separate executable acceptance claims. Empty _SEMANTIC.md contains no claims.

## Evidence boundaries

Current v2/src was read directly; it exposes loop-registry contracts/adapter and does not identify this scanner. Bounded v2/review ID search returned no matches. An initial `_Review` search path was absent; corrected search used actual `_Evaluation/Reviews` and is recorded. Neither search result proves unimplemented scope. Local run evidence only repairs dependency evidence under D-PEC-65 and asserts no product implementation/test acceptance. No frozen old source is used as current implementation. No live service, Git mutation, product CLI or scanner test ran. Foreign/root runtime observations remain outside this bounded evidence; session observation cannot confer runtime authority.

No DEL-06-02 exact product acceptance record is established in the declared evidence, and no new acceptance claim is made. Finite tests of unrelated detectors/loop-registry do not establish Git-scanner behavior. OPEN remains OPEN. Truthful TBD assignment stays ALIGNED and is not mirrored into Remaining. Current _REFERENCES and _CONTEXT already name revision1.4; historical _LATEST downstream-currency prose does not reopen ordinary completed SCA004 currency. No release or administrative residual is invented.

## Routing and handoff

DEL-06-02-REM-001 is an evidence-gap candidate linking all 10 UNKNOWN rows, not selected product work. Exact application requires a later owner act; source execution also requires F-PEC-1 paths/acts. Its Depends NONE reflects ungated discovery. Any future production item naming DEL-01-02 remains blocked while DEP-06-02-003 is ACTIVE PREREQUISITE/PENDING; no maturity is flipped from observation. All proposals NON_SELECTABLE_PENDING_OWNER_APPLICATION.

R0 sample artifacts are not reused for this deliverable. Required worker derivatives are complete; fresh independent verifier and package fan-in remain. Closure means worker evidence ready, not product, Remaining or lifecycle closure. Rerun on any read-source hash/hold drift, newly located scanner evidence or new owner application/scope act. Parent supplies shared-main authority visibility; no prohibited Git inspection was performed by this worker. Source comparisons matched every available frozen common hash, with additional search identities recorded solely as bounded discovery evidence.
''')
(w/'RETURN.md').write_text(f'''# Bounded Agent2 return — DEL-06-02

SUCCESS for evidence production; ASSESSED_UNKNOWN for deliverable concordance. 14 claims, 10 UNKNOWN, 4 ALIGNED, 1 canonical residual, 0 warranted NONE. All defined local REQ/AC/VER IDs: zero; accepted SOW-027 and material clauses mapped explicitly. Required artifacts CLAIMS.csv, RESIDUALS.csv, COVERAGE.md, READ_MANIFEST.json and this RETURN.md are complete. Supplementary preflights.json, discovery.json and build_evidence.py preserve probes/reproducibility.

Accepted upstream: effective D82 base `{commit}`, revision1.4 decomposition and D81 calibration conventions. This is a derivative report, not authoritative decomposition. Source unchanged across read-hash recheck; exact hold checks ALLOW, including absent ScopeOfWork.md. CSV structural/reciprocity checks PASS. No product suite run; missing current scanner evidence remains UNKNOWN. Pending DEL-01-02 production dependency is preserved.

Residual DEL-06-02-REM-001 is a nonselectable evidence-gap candidate only. No source/Remaining/lifecycle/assignment/Root/foreign-loop change or production selection. Fresh independent verifier and manager fan-in are outstanding; source/hold/owner changes trigger revalidation. Worker closure is report readiness only.

Sole write allowlist: `{w}/**`. Tools: scoped Python file evidence writes, read-only cat/rg/sed and Python hold preflights. No network, service, Git action or delegation. Role: ephemeral Agent2 under /root/pec_pkg06_reconciliation, actual native child /root/pec_pkg06_reconciliation/del06_02; instruction-asserted, not mechanically enforced; no model identity asserted. TASK base contract read for boundaries; sealed ephemeral brief controls execution and output scope.
''')
print(json.dumps({'claims':len(rows),'unknown':10,'aligned':4,'residuals':1,'hashed_inputs':len(hashes),'frozen_matches':sum(p in frozen for p in hashes),'source_unchanged':source_unchanged,'output_hashes':{p.name:H(p.read_bytes()) for p in w.iterdir() if p.is_file() and p.name!='build_evidence.py'}},indent=2))
