#!/usr/bin/env python3
"""Build the scripted part of R2/PKG-07/PACKAGE_SUMMARY.md from the accepted ledgers (brief step 8).
Hand-written cross-package observations are read from _scripts/observations.md (appended verbatim)."""
import csv, collections, glob, hashlib, io, json, os, re
P = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
UNITS = ["DEL-07-01", "DEL-07-02_A", "DEL-07-03", "DEL-07-04", "DEL-07-05", "DEL-07-06"]  # ledgers of record (RUN_BASIS Addendum 3)
SUPERSEDED = []
def rows(p):
    t = open(p, encoding="utf-8").read().rstrip()
    t = t[:-6] if t.endswith('"#END"') else (t[:-4] if t.endswith("#END") else t)
    return list(csv.DictReader(io.StringIO(t)))
def sha(p): return hashlib.sha256(open(p, "rb").read()).hexdigest()
def f(u, s): d = u.split("_")[0]; return os.path.join(P, u, d + s)
L = {u: rows(f(u, "_claims.csv")) for u in UNITS}
E = {u: (rows(f(u, "_errata.csv")) if os.path.exists(f(u, "_errata.csv")) else []) for u in UNITS}
def applied(u):
    rs = [dict(r) for r in L[u]]; ix = {r["ClaimKey"]: r for r in rs}
    for e in E[u]:
        if e["ClaimKey"] in ix: ix[e["ClaimKey"]][e["Field"]] = e["ProposedValue"]
    return rs
A = {u: applied(u) for u in UNITS}
C = [r for r in rows(os.path.join(P, "CORRECTIONS.csv"))] if os.path.exists(os.path.join(P, "CORRECTIONS.csv")) else []
def corrected(u):
    rs = [dict(r) for r in A[u]]; ix = {r["ClaimKey"]: r for r in rs}
    for c in C:
        if c["ClaimKey"] in ix: ix[c["ClaimKey"]][c["Field"]] = c["CorrectedValue"]
    return rs
K = {u: corrected(u) for u in UNITS}
out = ["# PACKAGE_SUMMARY — PKG-07 (RUN_D128_CONCORDANCE_2026-09-21_1614Z, R2 wave 3)", "",
       "> Sections 1–7 are generated by `R2/PKG-07/_scripts/package_summary.py` from the sealed ledgers, errata,",
       "> reverse files and verifier shards. They are agent evidence, not rulings. Section 8 is hand-written.", ""]
out += ["## 1. Ledgers of record", "", "| Unit | Rows | SEE rows | Split keys | Errata rows | Sealed claims SHA-256 |", "|---|---:|---:|---:|---:|---|"]
for u in UNITS:
    see = sum(1 for r in L[u] if "SEE:" in r["Notes"])
    sp = len({r["ClaimKey"].rsplit(".", 1)[0] for r in L[u] if re.search(r"#[A-Z]+-\d+\.\d+$", r["ClaimKey"])})
    out.append(f"| {u} | {len(L[u])} | {see} | {sp} | {len(E[u])} | `{sha(f(u, '_claims.csv'))}` |")
tot = sum(len(v) for v in L.values())
out += ["", f"Total rows: {tot}. Ledgers of record per RUN_BASIS Addendum 3 (most recent attempt passing the verdict-field rule): "
        "No ledger was rerun. DEL-07-02's ledger of record is double-blind worker A; worker B is compared in `DOUBLE_BLIND_DEL-07-02.md`.", ""]
def census(field, data, title, fn=None):
    keys = collections.Counter()
    per = {}
    for u in UNITS:
        c = collections.Counter()
        for r in data[u]:
            for v in (fn(r) if fn else [r[field]]): c[v] += 1
        per[u] = c; keys.update(c)
    ks = [k for k, _ in keys.most_common()]
    o = [f"### {title}", "", "| " + field + " | " + " | ".join(u.replace("DEL-", "") for u in UNITS) + " | Total |", "|---|" + "---:|" * (len(UNITS) + 1)]
    for k in ks: o.append(f"| {k} | " + " | ".join(str(per[u][k]) for u in UNITS) + f" | {keys[k]} |")
    return o + [""], keys
out += ["## 2. Censuses (sealed)", ""]
for fld in ["ClaimType", "Disposition", "CauseTag", "AuthorityTier", "Confidence"]:
    o, _ = census(fld, L, fld); out += o
def reach(r):
    t = sorted(set(re.findall(r"REACH=([A-Z_]+)", r["ImplementationEvidence"])))
    return ["+".join(t) if t else ("NONE_FOUND" if r["ImplementationEvidence"].startswith("NONE_FOUND") else "no-code-evidence")]
o, _ = census("REACH", L, "REACH (set of tags per row's ImplementationEvidence)", reach); out += o
unr = sum(1 for u in UNITS for r in L[u] if "UNREACHED" in r["Notes"])
out += [f"Rows noting `UNREACHED`: {unr}.", ""]
oth = collections.Counter(re.findall(r"OTHER:[A-Z0-9_]+", " ".join(r["CauseTag"] + " " + r["Notes"] for u in UNITS for r in L[u])))
out += [f"`OTHER:` cause tokens: {dict(oth) if oth else 'none'}. `CAUSE2:` secondaries: " +
        str(dict(collections.Counter(re.findall(r"CAUSE2:([A-Z_0-9:]+)", " ".join(r["Notes"] for u in UNITS for r in L[u]))))), ""]
out += ["## 3. HumanDecisionNeeded", ""]
o, hk = census("HumanDecisionNeeded", L, "Token tally (a row with several tokens counts once per token)",
               lambda r: [t.strip() for t in r["HumanDecisionNeeded"].split(";") if t.strip()]); out += o
r4 = {u: sum(1 for r in L[u] if re.search(r"\bR4\b|R4-Q", r["HumanDecisionNeeded"])) for u in UNITS}
out += [f"Rows needing any R4 decision: {sum(r4.values())} ({', '.join(f'{u} {n}' for u, n in r4.items())}). "
        f"R4-Q1 {hk['R4-Q1']}, R4-Q2 {hk['R4-Q2']}, R4-Q3 {hk['R4-Q3']}, R4-Q4 {hk['R4-Q4']}, R4-Q5 {hk['R4-Q5']}, plain R4 {hk['R4']}.", ""]
out += ["## 4. Sealed vs errata-applied vs corrected (CORRECTIONS.csv, RUN_BASIS Addendum 3)", "",
        f"Errata rows: {sum(len(v) for v in E.values())}. CORRECTIONS.csv rows: {len(C)} (by field: {dict(collections.Counter(c['Field'] for c in C))}). "
        "R3 applies errata first, then CORRECTIONS.csv. Corrections carry non-verdict fields only, so Disposition figures are identical in all three columns.", "",
        "| Column | Value | Sealed | Errata-applied | Corrected |", "|---|---|---:|---:|---:|"]
for fld in ["Disposition", "PostReleaseBasis", "AuthorityTier", "HumanDecisionNeeded", "CauseTag"]:
    sc = collections.Counter(r[fld] for u in UNITS for r in L[u]); ac = collections.Counter(r[fld] for u in UNITS for r in A[u]); cc = collections.Counter(r[fld] for u in UNITS for r in K[u])
    for v in sorted(set(sc) | set(ac) | set(cc)):
        if sc[v] != ac[v] or ac[v] != cc[v] or fld in ("PostReleaseBasis",): out.append(f"| {fld} | {v} | {sc[v]} | {ac[v]} | {cc[v]} |")
out += ["", "Rows are shown only where a figure differs (PostReleaseBasis always shown). Field-level corrections to DirectionEvidence and AssessmentEvidence change no census.", ""]
for u in UNITS:
    if not E[u]: continue
    fc = collections.Counter(e["Field"] for e in E[u])
    ch = []
    for fld in ["Disposition", "CauseTag", "HumanDecisionNeeded", "ClaimType", "AuthorityTier"]:
        s = collections.Counter(r[fld] for r in L[u]); a = collections.Counter(r[fld] for r in A[u])
        if s != a: ch.append(f"{fld}: sealed {dict(s)} → applied {dict(a)}")
    out.append(f"- **{u}**: {len(E[u])} errata rows by field {dict(fc)}. " + ("; ".join(ch) if ch else "No census column changes: sealed and errata-applied censuses are identical."))
if not any(E.values()): out.append("- No errata.")
out += ["", "## 5. Capability responses (reverse pass)", "", "| Unit | Areas | Capabilities answered | CLAIMED_BY | PARTIAL | NOT_MINE |", "|---|---|---:|---:|---:|---:|"]
allc = collections.defaultdict(list)
for u in UNITS + ["DEL-07-02_B"] + SUPERSEDED:
    rv = rows(f(u, "_reverse.csv")); c = collections.Counter(r["Response"] for r in rv)
    ar = sorted({r["CapabilityID"].split("-")[1] for r in rv})
    out.append(f"| {u} | {','.join(ar)} | {len(rv)} | {c['CLAIMED_BY']} | {c['PARTIAL']} | {c['NOT_MINE']} |")
    if u in UNITS:
        for r in rv:
            if r["Response"] != "NOT_MINE": allc[r["CapabilityID"]].append(f"{u.split('_')[0]}:{r['Response'][0]}")
multi = {k: v for k, v in allc.items() if len(v) > 1}
out += ["", "Rows below the ledgers of record (DEL-07-02_B) are shown for comparison and are not counted.", "", f"Capabilities claimed or partly covered by the package (ledgers of record): {len(allc)}; by more than one PKG-07 deliverable: {len(multi)}.", ""]
if multi:
    out += ["| CapabilityID | Responses (C=CLAIMED_BY, P=PARTIAL) |", "|---|---|"] + [f"| {k} | {', '.join(v)} |" for k, v in sorted(multi.items())] + [""]
out += ["## 6. Verifier outcomes", "", "Rerun trigger (RUN_BASIS Addendum 3): structural failure, or > 10% of checked distinct rows REFUTED on a verdict field (Disposition, reverse Response).", "",
        "| Shard | Status | Checked | CONFIRMED | REFUTED | CONTESTED | Distinct rows REFUTED (any field) | Verdict-field REFUTED | Verdict share |", "|---|---|---:|---:|---:|---:|---:|---:|---:|"]
T = collections.Counter()
for v in sorted(glob.glob(os.path.join(P, "_verify", "V-*.csv"))):
    vr = rows(v); c = collections.Counter(r["Verdict"] for r in vr); T.update(c)
    keys = {r["ClaimKey"] + "|" + r["CapabilityID"] for r in vr}; nm = os.path.basename(v)[2:-4]
    ref = {r["ClaimKey"] for r in vr if r["Verdict"] == "REFUTED"}
    vref = {r["ClaimKey"] + "|" + r["CapabilityID"] for r in vr if r["Verdict"] == "REFUTED" and ({x.strip() for x in r["Field"].split(";")} & {"Disposition", "Response", "ClaimKey"})}
    st = "ledger of record" if nm in UNITS else ("superseded" if nm in SUPERSEDED else "?")
    out.append(f"| V-{nm} | {st} | {len(vr)} | {c['CONFIRMED']} | {c['REFUTED']} | {c['CONTESTED']} | {len(ref)} | {len(vref)} | {100*len(vref)/max(len(keys),1):.1f}% |")
n = sum(T.values())
out += ["", f"Total (all shards): {n} checked — CONFIRMED {T['CONFIRMED']}, REFUTED {T['REFUTED']}, CONTESTED {T['CONTESTED']}. "
        "Verdict share = verdict-field refuted items / distinct items checked (rows and capability responses). The verdict-field refutations are listed in `VERIFICATION.md` §2 for R3.", ""]
db = os.path.join(P, "DOUBLE_BLIND_DEL-07-02.md")
if os.path.exists(db):
    t = open(db).read(); m = re.search(r"\| Disposition \| ([^|]+)\|", t); m2 = re.search(r"Exact Response agreement: ([^\n]+)", t)
    out += ["## 7. Double-blind (DEL-07-02)", "", f"- Disposition exact agreement on indexed base keys: {m.group(1).strip() if m else 'n/a'}; reverse Response agreement: {m2.group(1) if m2 else 'n/a'}. See `DOUBLE_BLIND_DEL-07-02.md`.", ""]
obs = os.path.join(P, "_scripts", "observations.md")
if os.path.exists(obs): out += [open(obs).read().rstrip(), ""]
out.append("*End of PACKAGE_SUMMARY.md. Agent evidence for R3; not a ruling.*")
open(os.path.join(P, "PACKAGE_SUMMARY.md"), "w").write("\n".join(out) + "\n")
print(sha(os.path.join(P, "PACKAGE_SUMMARY.md")))
