"""T4-I17 (T4-U1b, C-1): exact Taylor series of the arc load integrals that
cancel at small included angles, for CB's stable uniform-load deflection.

Standard library only (fractions). Run: python -I load_series_gen.py
Each integral is I(phi) = int_0^phi f(theta, phi) dtheta with psi = phi - theta.
The integrand is expanded as an exact bivariate power series in (theta, phi)
to total degree N, integrated term by term, and written phi^m * sum_k a_k phi^(2k).
The term count K is the smallest with sum_{k>=K} |a_k| PHI_MAX^(2k) < 2^-62 |a_0|
(PHI_MAX = 1.049 > pi/3, the switch s < 1/2), checked against the series to degree N.
"""
from fractions import Fraction as Q
from math import factorial

N = 90  # total degree kept in the integrand
PHI_MAX = Q(1049, 1000)

def mul(a, b):
    out = {}
    for (i1, j1), c1 in a.items():
        for (i2, j2), c2 in b.items():
            if i1 + j1 + i2 + j2 > N:
                continue
            k = (i1 + i2, j1 + j2)
            out[k] = out.get(k, 0) + c1 * c2
    return {k: v for k, v in out.items() if v != 0}

def add(*terms):
    out = {}
    for sign, a in terms:
        for k, v in a.items():
            out[k] = out.get(k, 0) + sign * v
    return {k: v for k, v in out.items() if v != 0}

def sin_of(var):  # var 0 = theta, 1 = phi
    out = {}
    for n in range(1, N + 1, 2):
        k = (n, 0) if var == 0 else (0, n)
        out[k] = Q((-1) ** ((n - 1) // 2), factorial(n))
    return out

def cos_of(var):
    out = {}
    for n in range(0, N + 1, 2):
        k = (n, 0) if var == 0 else (0, n)
        out[k] = Q((-1) ** (n // 2), factorial(n))
    return out

ONE = {(0, 0): Q(1)}
sin_t, cos_t, S, C = sin_of(0), cos_of(0), sin_of(1), cos_of(1)
psi = {(0, 1): Q(1), (1, 0): Q(-1)}
sin_psi = add((1, mul(S, cos_t)), (-1, mul(C, sin_t)))      # sin(phi - theta)
cos_psi = add((1, mul(C, cos_t)), (1, mul(S, sin_t)))       # cos(phi - theta)
a_x = add((1, S), (-1, sin_t), (-1, mul(psi, cos_t)))       # S - sin t - psi cos t
a_y = add((1, cos_t), (-1, C), (-1, mul(psi, sin_t)))       # cos t - C - psi sin t
one_m_cos_psi = add((1, ONE), (-1, cos_psi))
psi_m_sin_psi = add((1, psi), (-1, sin_psi))

INTEGRANDS = [
    # name, integrand, meaning
    ("LOAD_P0X", mul(add((1, sin_t), (-1, S)), a_x), "int (sin t - S) a_x"),
    ("LOAD_P0Y", mul(add((1, sin_t), (-1, S)), a_y), "int (sin t - S) a_y"),
    ("LOAD_P1X", mul(add((1, C), (-1, cos_t)), a_x), "int (C - cos t) a_x"),
    ("LOAD_P1Y", mul(add((1, C), (-1, cos_t)), a_y), "int (C - cos t) a_y"),
    ("LOAD_P5X", a_x, "int a_x"),
    ("LOAD_P5Y", a_y, "int a_y"),
    ("LOAD_Q2", mul(sin_psi, one_m_cos_psi), "int sin psi (1 - cos psi)"),
    ("LOAD_Q3", mul(cos_t, one_m_cos_psi), "int cos t (1 - cos psi)"),
    ("LOAD_Q4", mul(sin_t, one_m_cos_psi), "int sin t (1 - cos psi)"),
    ("LOAD_T2", mul(one_m_cos_psi, psi_m_sin_psi), "int (1 - cos psi)(psi - sin psi)"),
    ("LOAD_T3", mul(sin_t, psi_m_sin_psi), "int sin t (psi - sin psi)"),
    ("LOAD_T4", mul(cos_t, psi_m_sin_psi), "int cos t (psi - sin psi)"),
    ("LOAD_ASC", mul(psi, mul(sin_t, cos_t)), "int psi sin t cos t"),
    ("LOAD_ASS", mul(psi, mul(sin_t, sin_t)), "int psi sin^2 t"),
    ("LOAD_ACC", mul(psi, mul(cos_t, cos_t)), "int psi cos^2 t"),
]

def integrate(f):
    coeff = {}
    for (i, j), c in f.items():
        n = i + j + 1
        coeff[n] = coeff.get(n, 0) + c / (i + 1)
    return {n: c for n, c in coeff.items() if c != 0}

def main():
    print("// Generated by T4-I17 load_series_gen.py (exact rationals, N = %d)." % N)
    for name, f, meaning in INTEGRANDS:
        c = integrate(f)
        top = N + 1
        m = min(c)
        assert all((n - m) % 2 == 0 for n in c), name  # definite parity
        a = [c.get(m + 2 * k, Q(0)) for k in range((top - m) // 2 + 1)]
        # term count: tail below 2^-62 of the leading term at PHI_MAX
        lead = abs(a[0])
        K = None
        for k in range(1, len(a)):
            tail = sum(abs(a[j]) * PHI_MAX ** (2 * j) for j in range(k, len(a)))
            if tail < lead / Q(2) ** 62:
                K = k
                break
        assert K is not None and K + 6 < len(a), name
        # the omitted coefficients beyond N are smaller still (checked: geometric decay)
        print("// %s: %s = phi^%d * sum_k a_k phi^(2k); K = %d; exact a_k: %s" % (
            name, meaning, m, K, ", ".join(str(x) for x in a[:K])))
        print("const %s: Series = Series {\n    power: %d,\n    coefficients: &[" % (name, m))
        for x in a[:K]:
            print("        %r," % float(x))
        print("    ],\n};")

if __name__ == "__main__":
    main()
