const fs=require('fs'),path=require('path'),crypto=require('crypto'),Module=require('module');
const root='/Users/ryan/.codex/worktrees/8728/chirality-rendering-product-8468a33c/projects/chirality-piping';
const inst='/Users/ryan/.codex/worktrees/8728/chirality-rendering-instrument-20260917/projects/chirality-piping';
const ts=require(root+'/node_modules/typescript'),THREE=require(root+'/node_modules/three');
const hashes={};const read=f=>{const s=fs.readFileSync(f);hashes[f]=crypto.createHash('sha256').update(s).digest('hex');return s.toString()};
require.extensions['.ts']=(m,f)=>m._compile(ts.transpileModule(read(f),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,f);
const source=root+'/apps/desktop/src/features/viewport/viewportSelection.ts';
const prod=require(source),idx=require(root+'/apps/desktop/src/features/workspace/modelIndex.ts');
const src=read(source).replace('return missGroup[0]?.primitive.ref ?? null;','return {winner:missGroup[0]?.primitive.ref ?? null,broadPhaseKeys:[...broadPhaseKeys],candidates:candidates.map(c=>({ref:c.primitive.ref,entry:c.entry,miss:c.miss})),front:front.map(c=>({ref:c.primitive.ref,entry:c.entry,miss:c.miss})),missGroup:missGroup.map(c=>({ref:c.primitive.ref,entry:c.entry,miss:c.miss}))};');
const detail=new Module(source,module);detail.filename=source;detail.paths=Module._nodeModulePaths(path.dirname(source));detail._compile(ts.transpileModule(src,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,source);
(async()=>{const op=inst+'/apps/desktop/e2e/ui-foundation/point-hit-oracle.mjs';let os=read(op);const oracle=await import('file://'+op);os=os.replace('winner: { clippedEntry:', 'details: { candidates: candidates.map(c=>({type:c.type,id:c.id,entry:c.clippedEntry,miss:c.normalizedMiss})), front: frontGroup.map(c=>({type:c.type,id:c.id,entry:c.clippedEntry,miss:c.normalizedMiss})), missGroup: missGroup.map(c=>({type:c.type,id:c.id,entry:c.clippedEntry,miss:c.normalizedMiss})) }, winner: { clippedEntry:');fs.writeFileSync(__dirname+'/oracle-detail.mjs',os);const od=await import('file://'+__dirname+'/oracle-detail.mjs');
const model=JSON.parse(read(inst+'/apps/desktop/e2e/ui-foundation/fixtures/ui-foundation-10000.model.json'));const index=idx.buildModelIndex(model,1,1);const rows=[];
for(const attempt of [1,2,4,5]){const d=`/Users/ryan/.codex/task-runtime-cache/chirality-d70-baseline-20260917/instances/VERIFY/continuation-01/10000.${attempt}/raw/run-0${attempt}/10000/point-selection-058`;const stopped=JSON.parse(read(d+'/point-stopped.json')),act=JSON.parse(read(d+'/action-stopped.json')).active;const intended=act.actionIdentity.expectedClientPoint,delivered={x:act.actionMarker.clientX,y:act.actionMarker.clientY};const canvas=stopped.before.viewport.canvas;const origin=stopped.before.viewport.camera.localRenderOrigin;const prim=prod.pointPickPrimitives(index,model,{x:origin[0],y:origin[1],z:origin[2]});
for(const phase of ['before','after'])for(const pointKind of ['intended','delivered','xOnly','yOnly']){const c=stopped[phase].viewport.camera;const point=pointKind==='intended'?intended:pointKind==='delivered'?delivered:pointKind==='xOnly'?{x:delivered.x,y:intended.y}:{x:intended.x,y:delivered.y};const cam=new THREE.PerspectiveCamera(c.fovDegrees,c.aspect,c.near,c.far);cam.position.fromArray(c.position.map((v,i)=>v-origin[i]));cam.up.fromArray(c.up);cam.lookAt(...c.target.map((v,i)=>v-origin[i]));cam.updateMatrixWorld();const opts={index,renderOrigin:{x:origin[0],y:origin[1],z:origin[2]},camera:cam,canvas:{getBoundingClientRect:()=>({left:canvas.cssLeft,top:canvas.cssTop,width:canvas.cssWidth,height:canvas.cssHeight})},clientX:point.x,clientY:point.y};const actual=prod.pickPointPrimitive(prim,opts),pd=detail.exports.pickPointPrimitive(prim,opts);const ndc=[2*(point.x-canvas.cssLeft)/canvas.cssWidth-1,1-2*(point.y-canvas.cssTop)/canvas.cssHeight];const oc={position:c.position,target:c.target,up:c.up,fovDegrees:c.fovDegrees,near:c.near,far:c.far,aspect:c.aspect};const oh=oracle.expectedHitForProbe(model,oc,canvas.cssHeight,ndc),dd=od.expectedHitForProbe(model,oc,canvas.cssHeight,ndc);rows.push({attempt,phase,pointKind,point,ndc,product:actual,oracle:oh,productDetails:{...pd,broadPhaseCount:pd.broadPhaseKeys.length,broadPhaseKeys:pd.broadPhaseKeys.filter(k=>k.includes('08786')),candidates:pd.candidates.filter(c=>c.ref.id.includes('08786'))},oracleDetails:{...dd.details,candidates:dd.details.candidates.filter(c=>c.id.includes('08786'))},detailMatchesActual:JSON.stringify(pd.winner)===JSON.stringify(actual)});}
rows.push({attempt,float32:{intended,delivered,rounded:{x:Math.fround(intended.x),y:Math.fround(intended.y)},matches:Math.fround(intended.x)===delivered.x&&Math.fround(intended.y)===delivered.y}});}
fs.writeFileSync(__dirname+'/matrix.json',JSON.stringify({rows,inputHashes:hashes},null,2)+'\n');console.log(rows.map(r=>r.float32?r:({attempt:r.attempt,phase:r.phase,point:r.pointKind,product:r.product,oracle:r.oracle.expectedHitRef,detailMatchesActual:r.detailMatchesActual})));})();
