from pathlib import Path
import re,json
E=Path('execution/_Coordination/AgentRuns/FOUR_ROLE_OVERHAUL_20260909/implementation/document_workflows')
items=json.loads((E/'COVERAGE.json').read_text())['assignments']
for item in items:
 for p in Path(item['destination']).parent.rglob('*.md'):
  s=p.read_text()
  # Remove schema-free metadata assertions replaced by execution.json.
  s=re.sub(r'^- The `allowed-tools` frontmatter field.*\n','',s,flags=re.M)
  s=s.replace('It has no deterministic tool requirement and therefore omits `allowed-tools`.','Its execution configuration permits no shell commands.')
  s=s.replace('The frontmatter `allowed-tools` constrains TASK whitelisting:','The command restrictions in `execution.json` cover these operations; effective permission also depends on the role, brief, and host:')
  s=s.replace('TASK hydration already loads the authoritative contract from the workflow folder.','The brief declares the selected workflow and required CONTRACT.md resource; record the loading mechanism actually used.')
  s=s.replace('TaskWorkflow','Workflow')
  s=s.replace('strong-model consolidation','review consolidation').replace('Strong-model consolidation','Review consolidation').replace('smaller-model over-collection','preliminary over-collection')
  s=re.sub(r'Two-tier model guidance:\n.*?(?=\nAlways look)', 'Review stages:\n- Preliminary over-collection remains `NEEDS_REVIEW`.\n- A bounded consolidation review checks cross-section evidence before candidates become `READY_FOR_FREEZE`.\n- Risk-class sweeps require the full cross-section and multi-KTY context identified by their brief.\n',s,flags=re.S)
  s=s.replace('AGENT_TASK.md','docs/AGENT_WORKFLOW_RUNTIME.md')
  s=s.replace('`AGENT_REVIEW:<brief description>`','`AGENT_REVIEW:<brief description>`') # output vocabulary intentionally preserved
  s=s.replace('SKILL contract','workflow contract')
  s=s.replace('this agent directly','WORKING_ITEMS directly').replace('this agent','WORKING_ITEMS')
  # No dedicated persona remains; the role executing orchestration is explicit.
  s=re.sub(r'\b[Tt]he persona\b','WORKING_ITEMS',s)
  s=s.replace('the persona\'s','WORKING_ITEMS\'s').replace('persona\'s','manager\'s')
  s=s.replace('`equation-audit` persona','WORKING_ITEMS using `equation-audit`')
  s=s.replace('`pdf2md-orchestration` persona','WORKING_ITEMS using `pdf2md-orchestration`')
  s=s.replace('pdf2md-orchestration persona','WORKING_ITEMS using pdf2md-orchestration')
  s=s.replace('loaded by the persona','loaded by TASK under WORKING_ITEMS')
  s=s.replace('review agent compatibility','review workflow compatibility')
  # Per-input boundary excludes runtime-supplied instructions from the dataset restriction.
  s=s.replace('MUST NOT read any file other than `IMAGE_PATH`.','Read task data only from `IMAGE_PATH`; role, workflow, and brief context are supplied separately.')
  s=s.replace('No files other than `IMAGE_PATH` were read.','No task data outside `IMAGE_PATH` were read.')
  s=s.replace('{SOURCE_AUDIT_ROOT}/equations/','{SOURCE_AUDIT_ROOT}/')
  s=re.sub(r' +\n','\n',s)
  p.write_text(s)

p=Path('workflows/pdf2md-orchestration/PROCEDURE.md');s=p.read_text()
s=re.sub(r' \(model: as specified by the user.*?\)\. Use',' with vision capability. Use',s)
s=s.replace('the merged workflow rewrites both deterministically','the worker regenerates both outputs within the same bounded assignment')
s=re.sub(r'Page-worker dispatches MUST use.*?(?=\n\nEach dispatch brief)', 'Page-worker dispatches use TASK with `Workflow: pdf2md-page-full`. Declare `WORKFLOW.md` and the selected package\'s `CONTRACT.md` as context. Record actual supplied files and fingerprints when the harness exposes them; otherwise identify loading as instruction-asserted.',s,flags=re.S)
s=s.replace('and follows the INIT-TASK shape documented in `docs/AGENT_WORKFLOW_RUNTIME.md` § INIT-TASK brief format','and follows the bounded brief contract in `docs/AGENT_WORKFLOW_RUNTIME.md`')
s=s.replace('Omit `AllowedTools` — this is a VLM-reasoning-only workflow with no deterministic tool dependencies.','The worker execution configuration denies shell commands; its brief permits only the page-image read and the two output writes needed for this stage.')
s=s.replace("equation-audit is a separate Type 1 persona with its own gated loop (extract → human review → interpret prose notes → apply fixes → re-extract → backcheck → close). pdf2md-orchestration does NOT drive that loop. pdf2md-orchestration's job ends at the assembled Markdown; equation-audit picks up from there with its own pre-flight Gate 0.","WORKING_ITEMS continues with the separate `equation-audit` workflow when selected. Freeze its review basis and begin its Gate 0; conversion completion alone does not establish equation verification.")
s=s.replace('To start: `equation-audit` with','To start: WORKING_ITEMS using `Workflow: equation-audit` with')
s=s.replace('AND Phase 0 confirmed source-identity match: skip (resume).','AND Phase 0 confirmed source-identity match AND the pair passes the selected worker\'s output/schema checks: skip (resume). Invalid JSON, failed run_status, missing output correspondence, or placeholder-only Markdown requeues the page.')
p.write_text(s)
p=Path('workflows/drawing-extract/PROCEDURE.md');s=p.read_text()
s=re.sub(r'Worker dispatches MUST use.*?(?=\n\nEach dispatch brief)',"WORKING_ITEMS dispatches TASK with the `Workflow` from the target registry and explicitly supplies the selected package's `WORKFLOW.md` and `CONTRACT.md`. Record actual supplied context when available; instruction-mediated loading remains instruction-asserted.",s,flags=re.S)
s=s.replace('the INIT-TASK shape documented in `docs/AGENT_WORKFLOW_RUNTIME.md` § INIT-TASK brief format','the bounded brief contract in `docs/AGENT_WORKFLOW_RUNTIME.md`')
s=s.replace("in workflows/drawing-extract/WORKFLOW.md","in workflows/drawing-extract/PROCEDURE.md")
s=s.replace('create or resolve immutable run folder','create or resolve working run folder')
s=s.replace('### Phase 4 — Report','### Phase 4 — Report')
p.write_text(s)
p=Path('workflows/drawing-extract/CONTRACT.md');s=p.read_text().replace("below.`","in PROCEDURE.md.`")
s=s.replace('Workers emit locations as `A1..E5`, not pixel coordinates.','Optional visual aid. Current symbol-instance outputs require page-global pixel centers and bounding boxes; grid labels do not substitute for geometry.')
s=s.replace('Run-scoped P&ID and drawing-set artifacts are written under immutable run folders:','Run-scoped P&ID and drawing-set artifacts are assembled in working run folders and frozen at closure:')
s=s.replace('A persistent dedicated Agent 2 requires separate evidence and approval.','')
p.write_text(s)
p=Path('workflows/equation-audit/PROCEDURE.md');s=p.read_text()
s=s.replace('leave the entry in `flagged.json` with its original prose and surface the `reason` at Gate 5.','preserve the original entry and immediately obtain human clarification using the Gate 5 review surface. Return to Phase 3a with that clarification before attempting Phase 3b. The schema gate remains closed while unresolved prose exists.')
s=s.replace('or escalate to Gate 5 if unresolvable','or obtain human clarification through the Gate 5 review surface before returning to Phase 3a')
s=s.replace('If any check fails, surface the discrepancy to the human and offer to either loop back to Phase 2 (if unreviewed remains) or override via `ALLOW_UNREVIEWED`.','If flags, backcheck, or overlaps remain, return to the corresponding review/fix stage. If only unreviewed coverage exceeds the allowance, return to Phase 2 or record an explicit human revision to `ALLOW_UNREVIEWED`. That allowance changes coverage only; it cannot waive flags, backcheck, or overlaps.')
s=s.replace('Create `{SOURCE_AUDIT_ROOT}/snapshots/EQ_{book}_{YYYY-MM-DD}_{HHMM}/`.','Create a fresh `{SOURCE_AUDIT_ROOT}/snapshots/EQ_{book}_{YYYY-MM-DD}_{HHMM}/`; if that name already exists, choose a new timestamp or unique suffix. Assemble all closure files before freezing the directory. Never reuse an existing closed snapshot.')
p.write_text(s)
p=Path('workflows/equation-audit/ACCEPTANCE.md');s=p.read_text().replace('Once created, files under','Once closed, files under')
s+='\n### S11 — Review states are disjoint\nThe closure scan reports `overlaps == 0`. The permitted-unreviewed allowance never waives flags, current backcheck entries, or overlapping states.\n'
p.write_text(s)
p=Path('workflows/equation-flag-interpret/WORKFLOW.md');s=p.read_text()
s=re.sub(r'This workflow replaces.*?\n\n','',s,count=1,flags=re.S)
s=s.replace('surfaces the ambiguity to the human at Gate 5 (Verify backcheck) rather than applying a guessed fix.','surfaces the ambiguity immediately through the review surface and returns to interpretation with human clarification before any fix is applied.')
p.write_text(s)
p=Path('workflows/pdf2md/WORKFLOW.md');s=p.read_text()
s=re.sub(r'^description:.*$', 'description: "Convert a bounded PDF to Markdown in one TASK assignment, using vision and deterministic cleanup and assembly tools."',s,flags=re.M)
s=re.sub(r'This split is the same.*?\n\n','For parallel page production and asset materialization, WORKING_ITEMS uses `pdf2md-orchestration` with TASK and `pdf2md-page-full`. This bounded workflow performs its own transcription and invokes its own deterministic tools.\n\n',s,flags=re.S)
s=s.replace('`TASK + pdf2md-page`','`TASK + pdf2md-page-full`').replace('`Workflow: pdf2md-page`','`Workflow: pdf2md-page-full`')
s=s.replace('WORKING_ITEMS using `pdf2md-orchestration` via','WORKING_ITEMS using `pdf2md-orchestration`, which dispatches')
s=s.replace("that's the manager's Phase 3.5 work","that's the orchestration workflow's Phase 3.5 work")
s=s.replace('Reads `manifest.json` after the run; it records `pdf_sha256` + `dpi` (for resume-safety) and the canonical page list.','Before rasterization, compare any existing manifest with the current PDF SHA256 and DPI. Reject reuse on mismatch and select a fresh work directory or explicitly authorized cleanup. After rasterization, read `manifest.json` for the canonical selected page list; prior page files alone do not establish reusable output.')
s=s.replace('where `page_{NNNN}.md` does not already exist:','whose current-source `page_{NNNN}.md` is missing, empty, a failure placeholder, or fails the transcription checks:')
s=s.replace('The rasterizer + manifest model handles this.','Validate the source identity before rasterization and validate each reused transcription; the manifest alone does not establish semantic completeness.')
p.write_text(s)
# Historical page worker descriptions remain explicit; new-run guidance is merged worker.
p=Path('workflows/pdf2md-page/WORKFLOW.md');s=p.read_text().replace('The two workflows compose: the WORKING_ITEMS using pdf2md-orchestration rasterizes the PDF, spawns one `TASK` + `pdf2md-page` invocation per page image, collects the per-page Markdown outputs, then runs its own post-processing and assembly phases.','For a legacy resume contract, WORKING_ITEMS may dispatch this Markdown-only worker and the legacy asset worker separately. New orchestration uses `pdf2md-page-full` for the paired outputs.')
p.write_text(s)
print('Refined',len(items),'workflow packages')
