from pathlib import Path
import subprocess,os,json,hashlib,re,sys,io,zipfile
ROOT=Path(sys.argv[1]).resolve();WT=ROOT.parent;ENV=dict(os.environ,GIT_OPTIONAL_LOCKS='0',PYTHONDONTWRITEBYTECODE='1');T3=Path('projects/chirality-piping/execution/_Coordination/AgentRuns/HELP-HUMAN-PIPING-20260918-UI-IMPLEMENTATION/instances/CONTINUATION_2026-09-24/NUMERICAL_INTEGRITY_T3');RV=WT/'numerics'/T3/'REVIEW/RESUME_RECORDS_RV27';OUT=RV/'gatecheck_729e80b5';OUT.mkdir(exist_ok=True);(OUT/'evidence').mkdir(exist_ok=True)
S=WT/'scratch/sweep_resume_records_729e80b5';B=WT/'scratch/sweep_kf2';CONTROL=WT/'scratch/root-resume-20260930';HEAD='729e80b5c2a33b278623a850d9c75c25372b688c';inputs=[]
def cmd(a,cwd=ROOT):return subprocess.check_output(a,cwd=cwd,env=ENV)
def sha(b):return hashlib.sha256(b).hexdigest()
def read(p):
 b=p.read_bytes();inputs.append({'origin':'<wt>/'+str(p.relative_to(WT)),'sha256':sha(b),'bytes':len(b)});return b.decode()
def suite(p):
 s=read(p);m=re.findall(r'^test result:.*?(\d+) passed; (\d+) failed; (\d+) ignored;',s,re.M)
 return {'counts': [sum(int(x[i]) for x in m) for i in range(3)] if m else None,'failures':sorted(re.findall(r'^test (\S+) \.\.\. FAILED$',s,re.M))}
def inventory(folder):return {p.name.split('_',1)[1]:suite(p) for p in sorted((folder/'suites').glob('*.log'))}
base=inventory(B);cand=inventory(S);diff=[{'manifest_key':k,'base':base.get(k),'candidate':cand.get(k)} for k in sorted(base.keys()|cand.keys()) if base.get(k)!=cand.get(k)]
isolated=S/'self_weight_wasm_isolated';recovered=suite(isolated/'run.log');effective=dict(cand);effective['core_loads_self_weight_wasm_Cargo.toml.log']=recovered
res={'candidate':HEAD,'actual_head':cmd(['git','rev-parse','HEAD']).decode().strip(),'candidate_status':cmd(['git','status','--porcelain=v1']).decode(),'sweep_head':cmd(['git','rev-parse','HEAD'],WT/'sweep-skewpin').decode().strip(),'sweep_tracked_diff':cmd(['git','diff','--name-only',HEAD],WT/'sweep-skewpin').decode(),'sweep_status':cmd(['git','status','--porcelain=v1'],WT/'sweep-skewpin').decode(),'base_suite_keys':len(base),'candidate_suite_keys':len(cand),'original_keyed_delta':diff,'isolated_counts':recovered,'effective_keyed_delta':[{'key':k,'base':base.get(k),'effective':effective.get(k)} for k in sorted(base.keys()|effective.keys()) if base.get(k)!=effective.get(k)],'candidate_failures':{k:v['failures'] for k,v in cand.items() if v['failures']},'baseline_failures':{k:v['failures'] for k,v in base.items() if v['failures']}}
res['stored_comparison']=read(S/'suites_vs_baseline.txt');res['disposition']=json.loads(read(isolated/'DISPOSITION.json'));res['disposition_log_hash_matches']=res['disposition']['log_sha256']==sha((isolated/'run.log').read_bytes())
res['tree_serde_versions']=sorted(set(re.findall(r'serde_json v([0-9.]+)',read(isolated/'tree.txt'))));failure=read(S/'suites/004_core_loads_self_weight_wasm_Cargo.toml.log');res['original_compiler_versions']=sorted(set(re.findall(r'serde_json-(1\.0\.\d+)',failure)));res['original_tests_executed']=bool(re.search(r'^test result:|^running \d+ tests',failure,re.M));res['original_compile_failed']='could not compile' in failure
res['sweep_summary']=json.loads(read(S/'SWEEP_20261001T052810Z_729e80b5c2a3.json'));res['surfaces']=read(S/'surfaces.txt').replace(str(WT),'<wt>').replace(str(Path.home()),'<home>');res['surface_exits']=re.findall(r'exit (\d+)',res['surfaces']);res['meta']=read(S/'meta.txt')
for n in ['python_pytest.log','desktop_vitest_build_wasm.log','desktop_vitest.log','desktop_production_build.log']:
 s=read(S/n);res[n+'_summary']=[x for x in s.splitlines() if re.search(r'\d+ passed|Test Files|Tests +\d|✓ built|OK —',x)][-4:]
res['practitioner_summary']=read(CONTROL/'records-harness-729e80b5.log').strip().splitlines()[-1]
res['invocation_disposition']=json.loads(read(CONTROL/'DEC025_INVOCATION.json'));read(CONTROL/'dec025_mac_4x2.sh');read(CONTROL/'run_suites_nff_4x2.sh')
raw=cmd(['gh','run','view','36819769945','--repo','sgttomas/chirality','--json','headSha,event,status,conclusion,workflowName,jobs']);(OUT/'evidence/ci_run.json').write_bytes(raw);run=json.loads(raw);res['ci']={k:v for k,v in run.items() if k!='jobs'};res['ci_jobs']=[{'name':j['name'],'conclusion':j['conclusion']} for j in run['jobs']]
archive=cmd(['gh','api','repos/sgttomas/chirality/actions/artifacts/11142633927/zip']);z=zipfile.ZipFile(io.BytesIO(archive));planb=z.read('piping-e2e-plan.json');plan=json.loads(planb);localplan=(CONTROL/'ci_36819769945/piping-e2e-plan.json').read_bytes();res['ci_plan']={'artifact':11142633927,'archive_sha256':sha(archive),'plan_sha256':sha(planb),'local_bytes_match_download':planb==localplan,'mode':plan['mode'],'coverage_full':plan['coverage_full'],'numerical_required':plan['numerical_required'],'head':plan['head'],'base':plan['base'],'target_base':plan['target_base'],'selected_equals_inventory':plan['selected_specs']==plan['inventory']};(OUT/'evidence/piping-e2e-plan.json').write_bytes(planb)
pr=cmd(['gh','pr','view','1068','--repo','sgttomas/chirality','--json','state,headRefOid,baseRefOid,url,statusCheckRollup']);(OUT/'evidence/pr1068.json').write_bytes(pr)
portable=json.dumps(res,indent=2).replace(str(WT.parent.parent/'projects/chirality-piping/.venv'),'<VENV>').replace(str(WT),'<wt>').replace(str(Path.home()),'<home>');(OUT/'evidence/CHECKS.json').write_text(portable+'\n');(OUT/'evidence/INPUT_HASHES.json').write_text(json.dumps(inputs,indent=2)+'\n');print(json.dumps({k:v for k,v in res.items() if k not in ['sweep_summary','invocation_disposition','ci_jobs','stored_comparison','surfaces']},indent=2))
