#!/usr/bin/env python3
"""Fill gen_d95.template.py's pinned block from a git-archive export of the preimage commit.

Usage: python3 build_gen_d95.py <export_root> <template> <out>
"""
import glob, hashlib, sys
from pathlib import Path
root, tpl, out = Path(sys.argv[1]), Path(sys.argv[2]), Path(sys.argv[3])
def sha(p): return hashlib.sha256((root / p).read_bytes()).hexdigest()
EX = "projects/pec/execution"
rel = lambda ps: sorted(str(Path(p).relative_to(root)) for p in ps)
ctx = [p for p in rel(glob.glob(str(root / EX / "PKG-*/1_Working/DEL-*/_CONTEXT.md")))
       if "then by revision 1.4 (`current_basis`, SCA-004 successor).\n" in (root / p).read_text(encoding="utf-8")]
ref = [p for p in rel(glob.glob(str(root / EX / "PKG-*/1_Working/DEL-*/_REFERENCES.md")))
       if "(revision 1.4, accepted `current_basis`; SCA-004 successor)" in (root / p).read_text(encoding="utf-8")]
regs = sorted(f"{EX}/{d}/Dependencies.csv" for d in [
    "PKG-03_Reconciliation_Parity/1_Working/DEL-03-01_Full_rebuild_reconciler_one_command",
    "PKG-05_Gate_Evaluation_Decision_Slate/1_Working/DEL-05-01_Gate_precondition_evaluators_Explain_shaped",
    "PKG-05_Gate_Evaluation_Decision_Slate/1_Working/DEL-05-02_Cross_loop_decision_slate",
    "PKG-06_Presence_Git_Observation/1_Working/DEL-06-03_Session_worktree_scope_correlation",
    "PKG-08_API_Access/1_Working/DEL-08-04_Orientation_latency_budget_p95_100_ms",
    "PKG-08_API_Access/1_Working/DEL-08-05_SSE_delta_presence_subscription",
    "PKG-09_Dashboards/1_Working/DEL-09-05_Presence_board",
    "PKG-10_Validation_Measurement/1_Working/DEL-10-05_Owner_consultation_logging",
    "PKG-10_Validation_Measurement/1_Working/DEL-10-10_Directed_bootstrap_self_ingest_validation",
    "PKG-10_Validation_Measurement/1_Working/DEL-10-12_Poll_adoption_measurement"])
n1 = [f"{EX}/_Decomposition/_LATEST.md", f"{EX}/_ScopeChange/_LATEST.md",
      f"{EX}/_ScopeChange/SCA-005_2026-09-23_2139/Handoff_State.md",
      f"{EX}/_ScopeChange/SCA-005_2026-09-23_2139/RUN_SUMMARY.md", f"{EX}/_Coordination/_COORDINATION.md"]
basis = ["projects/pec/docs/PRD.md", f"{EX}/_Decomposition/Deliverables.csv", f"{EX}/_Decomposition/ScopeLedger.csv"]
assert (len(ctx), len(ref), len(regs)) == (42, 64, 10), (len(ctx), len(ref), len(regs))
lines = ["# Pinned at origin/main 13df8b795e47ab2284018eeefc9d5473d00c232d (generated by build_gen_d95.py).",
         "# Read-only basis: PRD.md, Deliverables.csv, ScopeLedger.csv. Every other entry is a write target.",
         "PREIMAGES = {"]
for p in basis + n1 + regs + ctx + ref:
    lines.append(f'    "{p}": "{sha(p)}",')
lines.append("}")
for name, ps in (("CTX_PATHS", ctx), ("REF_PATHS", ref), ("REG_PATHS", regs)):
    lines.append(f"{name} = [")
    lines += [f'    "{p}",' for p in ps]
    lines.append("]")
text = tpl.read_text(encoding="utf-8").replace("# @@PINNED@@", "\n".join(lines))
out.write_text(text, encoding="utf-8")
print(out, hashlib.sha256(out.read_bytes()).hexdigest())
