#!/usr/bin/env python3
"""D-PEC-95 exact generator: revision-1.5 currency packet (N1 records, N2 re-pin, N3 quotes).

Deterministic. Stdlib only. Run from any directory against a repository root
whose bytes equal origin/main 13df8b795e47ab2284018eeefc9d5473d00c232d for
every path listed in PREIMAGES. Every postimage is computed and every check
passes before the first byte is written; on any failure it exits 1 and writes
nothing.

Fail-closed checks before any write:
  * every PREIMAGES path hashes to its pinned SHA-256 (targets and basis);
  * N2 population: the _CONTEXT.md files carrying the revision-1.4 tail are
    exactly the pinned 42, and the _REFERENCES.md files naming revision 1.4
    are exactly the pinned 64; every anchor occurs exactly once;
  * N3: each of the 19 rows exists once, is ACTIVE EXECUTION, carries the
    pinned EvidenceFile, SourceRef and old EvidenceQuote; the new quote is a
    verbatim substring of its cited locus (the named register cell or PRD
    requirement row); every CSV row round-trips byte-exactly, so only
    EvidenceQuote, LastSeen and Notes of the 19 rows change;
  * after rendering, every ACTIVE EXECUTION row of every Dependencies.csv
    under projects/pec/execution has a verbatim EvidenceQuote (111/111);
  * N1: every replacement anchor occurs exactly once; appended notes land
    after a single trailing newline;
  * the local date equals --act-date, unless --reproduction is given (a
    verifier re-running the recorded act date on a scratch export).

Usage:
  python3 gen_d95.py --repo <REPO_ROOT> --act-date YYYY-MM-DD
      [--option A|P] [--retired-covers] [--check-only] [--reproduction]

Option A (recommended) = N1 including dated notes appended to the SCA-005
Handoff_State.md and RUN_SUMMARY.md, plus N2 and N3.
Option P (narrower) = the same without touching the two SCA-005 snapshot
files; _COORDINATION.md records their superseding pointers instead.
Add-on R (--retired-covers, not recommended by default) also rewrites the "covers" bullet
of the four retired deliverables' _REFERENCES.md (same files, different postimages).
The only varying bytes are the act-date slot {D} (N1 text; N3 LastSeen) and
the one hash of RUN_SUMMARY.md cited in the Handoff_State.md note.
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import io
import re
import sys
import time
from pathlib import Path

PEC = "projects/pec"
EX = f"{PEC}/execution"
PRD = f"{PEC}/docs/PRD.md"
DELIVERABLES = f"{EX}/_Decomposition/Deliverables.csv"
LEDGER = f"{EX}/_Decomposition/ScopeLedger.csv"
DECOMP_LATEST = f"{EX}/_Decomposition/_LATEST.md"
SC_LATEST = f"{EX}/_ScopeChange/_LATEST.md"
SCA5 = f"{EX}/_ScopeChange/SCA-005_2026-09-23_2139"
HANDOFF = f"{SCA5}/Handoff_State.md"
RUNSUM = f"{SCA5}/RUN_SUMMARY.md"
COORD = f"{EX}/_Coordination/_COORDINATION.md"

# Pinned at origin/main 13df8b795e47ab2284018eeefc9d5473d00c232d (generated by build_gen_d95.py).
# Read-only basis: PRD.md, Deliverables.csv, ScopeLedger.csv. Every other entry is a write target.
PREIMAGES = {
    "projects/pec/docs/PRD.md": "fff27a66cd23c758cf50609ee028c58f4fb643f23ee7f6f801eb2362dfffdc32",
    "projects/pec/execution/_Decomposition/Deliverables.csv": "b8628fc4c7b32b66eae373e19eb943ccaa866125e79119172b82614a01d3d65a",
    "projects/pec/execution/_Decomposition/ScopeLedger.csv": "83152a94d91c75da1205f98aec712f901529af4da562f02f5f1124b3ba3fd9df",
    "projects/pec/execution/_Decomposition/_LATEST.md": "1f2cdcba31b3db2fd8818b16202d2bbc89c3f4a20702a962d133a73e10f556b6",
    "projects/pec/execution/_ScopeChange/_LATEST.md": "a2b5b789d996d52aa43c86419c9a4f02d1aa01f438f1616f3d51921e34f84268",
    "projects/pec/execution/_ScopeChange/SCA-005_2026-09-23_2139/Handoff_State.md": "a86ae910d0c9ae7bf20a7ebb47de3edb345d1a6067cb1988fc04d5c1d213328a",
    "projects/pec/execution/_ScopeChange/SCA-005_2026-09-23_2139/RUN_SUMMARY.md": "e9a0224ec0152bba75c78b84e2c9abe7a5996014eec602b46de4fe3153c1e518",
    "projects/pec/execution/_Coordination/_COORDINATION.md": "8da03a2f0157ba097e4db5b34dff4cd68c03e69c5d0ec72f8a8f49c23d38879c",
    "projects/pec/execution/PKG-03_Reconciliation_Parity/1_Working/DEL-03-01_Full_rebuild_reconciler_one_command/Dependencies.csv": "833fbfe0c2a09ab8b564866dff8e55327fb005d5c4993973ef93408d2e2a436b",
    "projects/pec/execution/PKG-05_Gate_Evaluation_Decision_Slate/1_Working/DEL-05-01_Gate_precondition_evaluators_Explain_shaped/Dependencies.csv": "affd7d783e4fb3a44cb45dc4e79011d6afd7509545c0bc3119a779ca07c5bf98",
    "projects/pec/execution/PKG-05_Gate_Evaluation_Decision_Slate/1_Working/DEL-05-02_Cross_loop_decision_slate/Dependencies.csv": "dcf99c85eeb91c50eb1fa93869e448dcf9c5f568f9287dffd1614eec530eb74a",
    "projects/pec/execution/PKG-06_Presence_Git_Observation/1_Working/DEL-06-03_Session_worktree_scope_correlation/Dependencies.csv": "7b4d78c8d9411f2de916ec6510186baecd79f7f5790d9afa97c7cd7d4fc56b76",
    "projects/pec/execution/PKG-08_API_Access/1_Working/DEL-08-04_Orientation_latency_budget_p95_100_ms/Dependencies.csv": "1770f6fa3b2e740fff44f85c24d6d256e32ad50ba61e37c4495be9455fef6a4a",
    "projects/pec/execution/PKG-08_API_Access/1_Working/DEL-08-05_SSE_delta_presence_subscription/Dependencies.csv": "58b97ea5d8df6124ac6b94baa922983e82e05cadf8892404b174e6c4a262f1ba",
    "projects/pec/execution/PKG-09_Dashboards/1_Working/DEL-09-05_Presence_board/Dependencies.csv": "9811343ccb1f9e6820a03ebdac5aa53f163d355049508815438befb35db032d5",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-05_Owner_consultation_logging/Dependencies.csv": "324e0d6b1d420bf2be50f1f138d4924e57f2b36139add83e3335a5f26b41fc24",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-10_Directed_bootstrap_self_ingest_validation/Dependencies.csv": "9efe23791eda63ea5ec44e477bb800276812a98a51f5c594d27a49f5cdebca97",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-12_Poll_adoption_measurement/Dependencies.csv": "9fc8fb4993a6e9bcfbd0a88b5b6e4220def243a0d41b0362c5e3be8d008b4985",
    "projects/pec/execution/PKG-00_Architecture_Runway_Contracts/1_Working/DEL-00-01_v2_first_ADRs_core_isolation_carried_postures/_CONTEXT.md": "70e70f495817dbab5c25c67c4b4bd5aac756816d3df9103e57ad991c286817c5",
    "projects/pec/execution/PKG-00_Architecture_Runway_Contracts/1_Working/DEL-00-03_v2_SPEC_seed/_CONTEXT.md": "59fec8afea9544061dcd9fb0a6510c5492b2480e7d71b35624cf64ced9b81a8c",
    "projects/pec/execution/PKG-01_Service_Core_Store/1_Working/DEL-01-02_Presence_tier_schema_entity_model/_CONTEXT.md": "4d49f17b8a6aadb9961780ac3fc425df3e4fccd10f9321bb2c84427b32214337",
    "projects/pec/execution/PKG-01_Service_Core_Store/1_Working/DEL-01-03_Store_bootstrap_content_minimal_guard/_CONTEXT.md": "ed453eaa112e1c8af9b1c201d0e4c3b5bb00b11e776c7658cbd333d430a6e058",
    "projects/pec/execution/PKG-01_Service_Core_Store/1_Working/DEL-01-04_Self_observability_logging/_CONTEXT.md": "b479ce57949d78b9db78a54c8b77eae418d8e345843d303c69fc54087e694afa",
    "projects/pec/execution/PKG-01_Service_Core_Store/1_Working/DEL-01-05_Zero_dependency_locality_enforcement/_CONTEXT.md": "4bf394696c386f6a5f792a8f9967abc03e1d1339dc6715de09647f296ad25da1",
    "projects/pec/execution/PKG-02_File_Truth_Parsers/1_Working/DEL-02-01_STATUS_md_parser/_CONTEXT.md": "6829fef13bd2b65dbb79ced9225cb91b806016d5d363a1135e194901311d7746",
    "projects/pec/execution/PKG-02_File_Truth_Parsers/1_Working/DEL-02-02_Decision_register_packet_parser/_CONTEXT.md": "8cfabfe6bffb9325246e4d94be47c2da2b65a22eebae8e01dde7292f48aec382",
    "projects/pec/execution/PKG-03_Reconciliation_Parity/1_Working/DEL-03-01_Full_rebuild_reconciler_one_command/_CONTEXT.md": "fcf60b19d2be414dbf6d1572b035ceb5404aa86ac8240709c5e6405762af3346",
    "projects/pec/execution/PKG-03_Reconciliation_Parity/1_Working/DEL-03-02_Incremental_reconcile_on_Git_delta/_CONTEXT.md": "0d9ccb791028d4d59c345612fd27e7e755882899161be15076875bc7a78b0271",
    "projects/pec/execution/PKG-03_Reconciliation_Parity/1_Working/DEL-03-04_Practitioner_harness_parity_diff/_CONTEXT.md": "006c508a849aa2b5316166029aa5f737494e781ca9b2d12594dbca9ed53e5c5c",
    "projects/pec/execution/PKG-03_Reconciliation_Parity/1_Working/DEL-03-06_Rebuild_performance_bounds/_CONTEXT.md": "bfe3b987d85cd13dde55cc0db22caddf68c8525180b026a2bb3977cbeac5855a",
    "projects/pec/execution/PKG-04_Orientation_Services/1_Working/DEL-04-02_Delta_service_since_SHA/_CONTEXT.md": "242107d811521e1ae2b6645b6ce12a198e8b2ca91c4d53298a1c5f5e804807f6",
    "projects/pec/execution/PKG-04_Orientation_Services/1_Working/DEL-04-03_Citation_freshness_stamping/_CONTEXT.md": "0b56862a83014d469cc00ddd663dc2e60cb93ac4249eeed169480b88e7ec9b21",
    "projects/pec/execution/PKG-04_Orientation_Services/1_Working/DEL-04-04_Scope_parameterization/_CONTEXT.md": "3f068736b91bfdb60681e9019f5c936edd2d74b29e0f918989f0122015b1e700",
    "projects/pec/execution/PKG-04_Orientation_Services/1_Working/DEL-04-05_Measurement_limitation_honesty/_CONTEXT.md": "20710c09a9524586b9efd61bcd20a768df4ffe37b33862c80a00e069e189bed6",
    "projects/pec/execution/PKG-05_Gate_Evaluation_Decision_Slate/1_Working/DEL-05-02_Cross_loop_decision_slate/_CONTEXT.md": "ab427727f5e9049f9e2b341b201929b2485d1a97654b51bab7d2391605defaed",
    "projects/pec/execution/PKG-06_Presence_Git_Observation/1_Working/DEL-06-02_Git_worktree_scanner/_CONTEXT.md": "7ae79b2138fb458203f7105cd863419769f60308e17072ab4e2b0a13b610ba40",
    "projects/pec/execution/PKG-06_Presence_Git_Observation/1_Working/DEL-06-03_Session_worktree_scope_correlation/_CONTEXT.md": "1ed76ac629d33bad7d077b50a70026f90d25fba858df9b93a0084711f7490071",
    "projects/pec/execution/PKG-06_Presence_Git_Observation/1_Working/DEL-06-05_TTL_heartbeat_discipline_citation_exclusion/_CONTEXT.md": "ad7fe45e8b9b2b2f541ea97607625af108700dc7228077a8ef0701e6d03f9ec1",
    "projects/pec/execution/PKG-06_Presence_Git_Observation/1_Working/DEL-06-06_Advisory_overlap_detection/_CONTEXT.md": "3db26dc1456daa09654fca7d88186563611db462a5788d46e2e0b84fa4538f95",
    "projects/pec/execution/PKG-07_Event_Ingest_Bridges/1_Working/DEL-07-01_Idempotent_event_ingest_durable_message_store/_CONTEXT.md": "e20c22ee0d6fb78e54519194a8e1eb1e0ef9594b96fa5854525a0006df13a986",
    "projects/pec/execution/PKG-08_API_Access/1_Working/DEL-08-02_Versioned_additive_API_schema/_CONTEXT.md": "375f46713bd275576a8343feb6a1768abbe0c1f5cfd61e888bb60111abe44cc9",
    "projects/pec/execution/PKG-08_API_Access/1_Working/DEL-08-03_Compact_citation_bearing_response_format/_CONTEXT.md": "d9b84e656c69f09de9f3b0cc55fa87663ad39cb3236200493ca0720a46da1c58",
    "projects/pec/execution/PKG-08_API_Access/1_Working/DEL-08-04_Orientation_latency_budget_p95_100_ms/_CONTEXT.md": "787d462878730161f667e6c8edb928f2248a8ab460c409566f826ed9c6265a6d",
    "projects/pec/execution/PKG-09_Dashboards/1_Working/DEL-09-01_Overview_dashboard/_CONTEXT.md": "2ed591ad9008ebfa144e9c5b9a7f0a1d5f2ff858002c9b6a49939dbe46b3ccb0",
    "projects/pec/execution/PKG-09_Dashboards/1_Working/DEL-09-02_Lifecycle_census_dashboard/_CONTEXT.md": "f757ca97a8f822bd74876b03ef3cbb4f5a61846cef0b369487cf730b680d4832",
    "projects/pec/execution/PKG-09_Dashboards/1_Working/DEL-09-03_Register_views/_CONTEXT.md": "e53497585ebce826bd16244f924a9164f5cb46334e935daae50a55ebed1a9996",
    "projects/pec/execution/PKG-09_Dashboards/1_Working/DEL-09-04_Decision_slate_view_waiting_on_you/_CONTEXT.md": "1e5957cd85780fa5dbb4b6f6353564a49ec79c4cf436b62726e17bf269d0d01f",
    "projects/pec/execution/PKG-09_Dashboards/1_Working/DEL-09-06_Universal_drill_down_to_cited_source/_CONTEXT.md": "a146fc6acb4fe5da4d513312f11c8c2db3c3d2cff77aa4720b484b260a1f86bf",
    "projects/pec/execution/PKG-09_Dashboards/1_Working/DEL-09-07_Explain_shaped_pressure_rules/_CONTEXT.md": "21c858156a5f4636bc3d79765f9c88a5438efa0e90254097e30b77603e9dd54d",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-01_Step_0_cost_baseline_pre_P1/_CONTEXT.md": "b216baa191be3309f98f938b06f2a9df1204b8d02d20088705e70c41561845ba",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-02_Kill_test_standing_release_gate/_CONTEXT.md": "43a5587fa48498909290540492de137c38ab3c82a96c4caea035ce6831a9edca",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-03_No_ruling_write_verification/_CONTEXT.md": "244b635d3864c91d768c0dba6874168fb851062fdaa309587af1240ea0a6248d",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-04_Orientation_defect_rate_spot_check/_CONTEXT.md": "c57966413a2174ad2d979d31de4fee08e7e9b02a6e53c2e157fb4c19f577ddc4",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-05_Owner_consultation_logging/_CONTEXT.md": "ccbbfb44c7143aea9067d1d0cf38247aee71dd4cb07fb97249d1fa121bab4d33",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-06_Seeded_conflict_overlap_test/_CONTEXT.md": "1898159dc8cfb1f33e75a4e1330b63f533a5acc4775ffea7a97e192376a4f657",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-07_Presence_TTL_honesty_tests/_CONTEXT.md": "88bdda5d9c590df9969d22bfddeafa441cec74a11e31e2e27e9488d66af50af9",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-09_Collision_incident_measurement/_CONTEXT.md": "0fd365a5b1f86bbc1e5f596ee0ea945275e3693f4c78d68cfcf6a6fed02f55cd",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-10_Directed_bootstrap_self_ingest_validation/_CONTEXT.md": "7ad8761a61727297478eaaac5737af6cea9bc0cc7e1f146c70ff4966d52154c7",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-11_Parity_metric_DriftFindings_per_reconcile/_CONTEXT.md": "6bfde0e0f01a12c3d4d48cf067872b2752a41dd334def4bdc339af9e83e0b6aa",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-12_Poll_adoption_measurement/_CONTEXT.md": "c7e16840930fb534e9591364a9cc772aa00d74f8441d196d07323b83495fd222",
    "projects/pec/execution/PKG-00_Architecture_Runway_Contracts/1_Working/DEL-00-01_v2_first_ADRs_core_isolation_carried_postures/_REFERENCES.md": "21560f41e7fb075fb72fcbe419ce0c7136941622134cecfdf125d7ed4b904fd4",
    "projects/pec/execution/PKG-00_Architecture_Runway_Contracts/1_Working/DEL-00-02_Event_contract_schema_v1/_REFERENCES.md": "d4bee4effb1c47744438f691d1821ce7953f4da40aa17eecd200cdc88386fa74",
    "projects/pec/execution/PKG-00_Architecture_Runway_Contracts/1_Working/DEL-00-03_v2_SPEC_seed/_REFERENCES.md": "481b34847cbbc9bb15d792e0990b0b8f0b2a5750c82a041d65bb50bff4ff615f",
    "projects/pec/execution/PKG-01_Service_Core_Store/1_Working/DEL-01-01_Record_tier_schema_entity_model/_REFERENCES.md": "e72764eb33fe0deadb9d7f4e33b43e3a3e10e44949f5cd7aa46fc7c56e6611b2",
    "projects/pec/execution/PKG-01_Service_Core_Store/1_Working/DEL-01-02_Presence_tier_schema_entity_model/_REFERENCES.md": "e323c6a086b2ed7907fc5c80d502197b56c1983cb14e0fd67f24aa33ba319774",
    "projects/pec/execution/PKG-01_Service_Core_Store/1_Working/DEL-01-03_Store_bootstrap_content_minimal_guard/_REFERENCES.md": "8a661ac88c3047e1c6892a6e24544f2714329579c6717f0c05ac840e4f468bcc",
    "projects/pec/execution/PKG-01_Service_Core_Store/1_Working/DEL-01-04_Self_observability_logging/_REFERENCES.md": "53ffa97f12951dd4086fc80ce3e907cf57ca273381b30018b922644f100e3dd9",
    "projects/pec/execution/PKG-01_Service_Core_Store/1_Working/DEL-01-05_Zero_dependency_locality_enforcement/_REFERENCES.md": "20c53f9b060f24c5278199c8357c64cc5f1a36fabf218da6d855f2f12a40647a",
    "projects/pec/execution/PKG-01_Service_Core_Store/1_Working/DEL-01-06_Loop_registry_local_config_default/_REFERENCES.md": "a4da999cef5d3c94d9ed61f2cddca297481be7ebdde52d13d2f8a9e213a35693",
    "projects/pec/execution/PKG-02_File_Truth_Parsers/1_Working/DEL-02-01_STATUS_md_parser/_REFERENCES.md": "42c74660a51bd92fb8df13d0b1c3109651d2304b35413b25ac5b6b281d7cd882",
    "projects/pec/execution/PKG-02_File_Truth_Parsers/1_Working/DEL-02-02_Decision_register_packet_parser/_REFERENCES.md": "25ba5e5b64588948a5c5e66e083367fd696e9d36a6fc109fe4b5f5ea51db1c5d",
    "projects/pec/execution/PKG-02_File_Truth_Parsers/1_Working/DEL-02-03_Receipts_ledger_parser_per_loop_grammars/_REFERENCES.md": "b5e3211557729e3eaeca9d257417a1fccd64374aea66833639bb011b67c771f8",
    "projects/pec/execution/PKG-02_File_Truth_Parsers/1_Working/DEL-02-04_Run_evidence_JSON_parser/_REFERENCES.md": "9275945f28d5722112a20e2329c5b6723f13c28cc1431942bbcfb463d9946125",
    "projects/pec/execution/PKG-02_File_Truth_Parsers/1_Working/DEL-02-05_Dependency_register_parser/_REFERENCES.md": "57cdc7bc7e6229c19e144352b8de2f8868c0039d6faaa025caf08b46008e4843",
    "projects/pec/execution/PKG-02_File_Truth_Parsers/1_Working/DEL-02-06_Workplan_LOOP_INIT_parser/_REFERENCES.md": "5c3ddbf2269e91165e8a2df5cd1eb3c88aa4a8e219afeda65a12530d2215f82c",
    "projects/pec/execution/PKG-02_File_Truth_Parsers/1_Working/DEL-02-07_adapter_yaml_feed_manifest_consumer/_REFERENCES.md": "228c49f4b1ff8a54f99e58510e8f145535b6ffba69c922aeb88493cfdcabaf25",
    "projects/pec/execution/PKG-03_Reconciliation_Parity/1_Working/DEL-03-01_Full_rebuild_reconciler_one_command/_REFERENCES.md": "682edec873d4771213845ed35ce2afe2b8b6ed218bcc920e63bf08abe79a937f",
    "projects/pec/execution/PKG-03_Reconciliation_Parity/1_Working/DEL-03-02_Incremental_reconcile_on_Git_delta/_REFERENCES.md": "8a5a1e1824365c365024fb08f0333d2ea0fd0bef80e0b99cc57d068342491ec5",
    "projects/pec/execution/PKG-03_Reconciliation_Parity/1_Working/DEL-03-03_Drift_classification/_REFERENCES.md": "8d12f602e86792c6ebd02db6e540b41e219201adae8bab8a6dd2d79f3abbe9b5",
    "projects/pec/execution/PKG-03_Reconciliation_Parity/1_Working/DEL-03-04_Practitioner_harness_parity_diff/_REFERENCES.md": "f0ff68a4c268e11f9d9d32d87a377d3b2877832eb9b3ea21d438115aaec177c9",
    "projects/pec/execution/PKG-03_Reconciliation_Parity/1_Working/DEL-03-05_Stream_loss_recovery_guarantee/_REFERENCES.md": "7200cda06600495b7b5321fcfadcdbfbc27762ba7521d3513e4e56a5647e9224",
    "projects/pec/execution/PKG-03_Reconciliation_Parity/1_Working/DEL-03-06_Rebuild_performance_bounds/_REFERENCES.md": "73b4e4cc9116a115201f23a5296edf0e905355d6ac2e2b0da558609ec5c9d4ab",
    "projects/pec/execution/PKG-04_Orientation_Services/1_Working/DEL-04-01_Loop_orientation_return/_REFERENCES.md": "fb2348289bbd2da6df823a1c9dc001bf62fa460aea8132e413c0266d322d7e0d",
    "projects/pec/execution/PKG-04_Orientation_Services/1_Working/DEL-04-02_Delta_service_since_SHA/_REFERENCES.md": "55eea82370f608dd7ea75418004af9a77cc1417d08d7b8baaf55db2b22eeebab",
    "projects/pec/execution/PKG-04_Orientation_Services/1_Working/DEL-04-03_Citation_freshness_stamping/_REFERENCES.md": "d3a41d79d4687fd15052d95186626c4dc6db3f45d1c900d1cbc835b977920058",
    "projects/pec/execution/PKG-04_Orientation_Services/1_Working/DEL-04-04_Scope_parameterization/_REFERENCES.md": "873889e0812dc9e0f808f75ebe0425b82ebfa6cdb2b04ff63c2388805f213038",
    "projects/pec/execution/PKG-04_Orientation_Services/1_Working/DEL-04-05_Measurement_limitation_honesty/_REFERENCES.md": "bd866c34c6c7d5daffd3a136cdd2541da8f1c2585a8890cca466743a27b3a71a",
    "projects/pec/execution/PKG-05_Gate_Evaluation_Decision_Slate/1_Working/DEL-05-01_Gate_precondition_evaluators_Explain_shaped/_REFERENCES.md": "fd226572dd115a54fed3bf651d6b58fead77b86777165d7a27331c402c1886a8",
    "projects/pec/execution/PKG-05_Gate_Evaluation_Decision_Slate/1_Working/DEL-05-02_Cross_loop_decision_slate/_REFERENCES.md": "6beaa2761fb978ba07a4b6e1259b51bf939dfe6a67bc4a0053e7dc02c55368b8",
    "projects/pec/execution/PKG-06_Presence_Git_Observation/1_Working/DEL-06-01_Session_presence_records/_REFERENCES.md": "d052d61c1b38925f298bc659bb796c8a5eb796811558cdefd8139e4361fe01a9",
    "projects/pec/execution/PKG-06_Presence_Git_Observation/1_Working/DEL-06-02_Git_worktree_scanner/_REFERENCES.md": "d00ed531a857aa0ca172e3dc3f17cefda433e7073b189610615938d026e44ece",
    "projects/pec/execution/PKG-06_Presence_Git_Observation/1_Working/DEL-06-03_Session_worktree_scope_correlation/_REFERENCES.md": "a38bc032d32d811e10db9ec2dfe8359c5b1192e811d16341aa0efd25747ed182",
    "projects/pec/execution/PKG-06_Presence_Git_Observation/1_Working/DEL-06-04_Live_hierarchy_edges/_REFERENCES.md": "93303124d4e8db243c0b6f95753a0887d22b35e32cb8e8b756bd96d1dc0bd407",
    "projects/pec/execution/PKG-06_Presence_Git_Observation/1_Working/DEL-06-05_TTL_heartbeat_discipline_citation_exclusion/_REFERENCES.md": "68f93f33b49245085d8726226f0f60b5dff2a8e33504505eceb3d971e81dc80f",
    "projects/pec/execution/PKG-06_Presence_Git_Observation/1_Working/DEL-06-06_Advisory_overlap_detection/_REFERENCES.md": "11bfe2a700df99ae0d963c28b1733e2f636039337944fb34748d3624ee4709d3",
    "projects/pec/execution/PKG-07_Event_Ingest_Bridges/1_Working/DEL-07-01_Idempotent_event_ingest_durable_message_store/_REFERENCES.md": "7db708f869b0579b009238744fbece05b43275c960f3c0ae544da233f6a34860",
    "projects/pec/execution/PKG-07_Event_Ingest_Bridges/1_Working/DEL-07-02_Daemon_SSE_subscriber_bridge/_REFERENCES.md": "69d76c3e9eba29d2c160fd68c024ff21fcbcebe7833c726244c2876e993c9c74",
    "projects/pec/execution/PKG-07_Event_Ingest_Bridges/1_Working/DEL-07-03_Hooks_CLI_bridge/_REFERENCES.md": "896c1f6926360a9ae5db919f8506794ca2e2890d817dbf2c592e99733bb416fe",
    "projects/pec/execution/PKG-07_Event_Ingest_Bridges/1_Working/DEL-07-04_cmux_socket_adapter_optional/_REFERENCES.md": "2289938931aaacc4cd29fdfdb3fc49cbc02b6e7f7f281d10c45f401082713dc4",
    "projects/pec/execution/PKG-07_Event_Ingest_Bridges/1_Working/DEL-07-05_Shared_runtime_client_seam_v2/_REFERENCES.md": "5d4cdd94f23b89411fcd4b16d4ae6e7f25258390cafb63c0e7ddbf798cbe821f",
    "projects/pec/execution/PKG-08_API_Access/1_Working/DEL-08-01_Unix_socket_server_token_scoped_access/_REFERENCES.md": "83e25138dc8ebf7e7102c651742c77e1ea9748b9417c9ac89d166f81bdfb39fe",
    "projects/pec/execution/PKG-08_API_Access/1_Working/DEL-08-02_Versioned_additive_API_schema/_REFERENCES.md": "734258088c76a48636751b5f7bdd7e5467e2e939e2158dff7037d1833a8396ca",
    "projects/pec/execution/PKG-08_API_Access/1_Working/DEL-08-03_Compact_citation_bearing_response_format/_REFERENCES.md": "ae13d4f030682b0d90db4f2a7884cc01a1f47abd2baed9dbb4646cf6346111f8",
    "projects/pec/execution/PKG-08_API_Access/1_Working/DEL-08-04_Orientation_latency_budget_p95_100_ms/_REFERENCES.md": "9948422bcf701bb31d4738c4d2655fa7975178fa87c14264a2f0f23c6d089fb4",
    "projects/pec/execution/PKG-08_API_Access/1_Working/DEL-08-05_SSE_delta_presence_subscription/_REFERENCES.md": "66489416f3dfe9c61f7a25865238cf1bf4a54c9e398b53c076e1fcc56af86b1d",
    "projects/pec/execution/PKG-09_Dashboards/1_Working/DEL-09-01_Overview_dashboard/_REFERENCES.md": "7cc4faf411a85a3cf17a33a0a50f5065aace83ef3eef003298dc721bbe6dac0d",
    "projects/pec/execution/PKG-09_Dashboards/1_Working/DEL-09-02_Lifecycle_census_dashboard/_REFERENCES.md": "0d34444f7faaa91e4e5aa8b4a16cb05707d491a353c863bb12387fedd9c08487",
    "projects/pec/execution/PKG-09_Dashboards/1_Working/DEL-09-03_Register_views/_REFERENCES.md": "78ab3bb0f5957b152a05bd712b6f55fe900ebd4f47234bfa1c878daa8a620537",
    "projects/pec/execution/PKG-09_Dashboards/1_Working/DEL-09-04_Decision_slate_view_waiting_on_you/_REFERENCES.md": "3275cdc25d61bdab3baa276ac917af67a666b7091dfe73078391c41f544c9f55",
    "projects/pec/execution/PKG-09_Dashboards/1_Working/DEL-09-05_Presence_board/_REFERENCES.md": "57c637d457886cda3c23a51b02167484eef670f4bcb7d41dae98547a61721145",
    "projects/pec/execution/PKG-09_Dashboards/1_Working/DEL-09-06_Universal_drill_down_to_cited_source/_REFERENCES.md": "7d814916e089a74cfc54c330e4041af2c40b7339b774b10d1062b4a6004f8580",
    "projects/pec/execution/PKG-09_Dashboards/1_Working/DEL-09-07_Explain_shaped_pressure_rules/_REFERENCES.md": "d74fa83df09a07d1a96b7407c2a748b7e9821861e3556a54d0d0eb9ad859d168",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-01_Step_0_cost_baseline_pre_P1/_REFERENCES.md": "c50bb2b69a39901a60866c2b2bb3d652f570ae10b827f7845b4b3e3fd1542c7c",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-02_Kill_test_standing_release_gate/_REFERENCES.md": "106baf2082bd0b82e1475f56b15f1bf0d2280a83188f017d7c261b2ad2ec1181",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-03_No_ruling_write_verification/_REFERENCES.md": "99b871635d9a3a4ec61393c63138211f9ff8bfaae0a4175596b3b85644a847d4",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-04_Orientation_defect_rate_spot_check/_REFERENCES.md": "0dc254ab57227b1fbf0109d2ebfc14a41654ec0c85c1eda3050ac569671d5b58",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-05_Owner_consultation_logging/_REFERENCES.md": "6e64cb640b394c931f1c20306b28fc5f95fa60d8f5dd4280911c739c825b8f02",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-06_Seeded_conflict_overlap_test/_REFERENCES.md": "1052ada927f89b19705ec27e9de9701cb9024cb08d4ec71210e4ef7de63b4944",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-07_Presence_TTL_honesty_tests/_REFERENCES.md": "bdc61af4db54085784362cd33149c4ec90ce60c09b5df5fcecda62add0f15e45",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-08_Stream_loss_recovery_demonstration/_REFERENCES.md": "7884c0402107ed45b37e170094f83c0dac26d276439604b70e3c9b86cfc67fed",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-09_Collision_incident_measurement/_REFERENCES.md": "a52cbe5b267ead64a733aa3383e14b7761ab2fa6bb0523c4257e68a6bad60a52",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-10_Directed_bootstrap_self_ingest_validation/_REFERENCES.md": "d8efe5e540b8b0ae32ca1e9c26b85d8abdbcc01898c31694165934fa9958a20b",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-11_Parity_metric_DriftFindings_per_reconcile/_REFERENCES.md": "94d1fd3dae2d8453907db80eb2368cac713889e940d97bb846f329b97e01202d",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-12_Poll_adoption_measurement/_REFERENCES.md": "9f0d557bda938e1a9180af89c5b98bed308fbdaa19032fa12c90eb0067beb151",
}
CTX_PATHS = [
    "projects/pec/execution/PKG-00_Architecture_Runway_Contracts/1_Working/DEL-00-01_v2_first_ADRs_core_isolation_carried_postures/_CONTEXT.md",
    "projects/pec/execution/PKG-00_Architecture_Runway_Contracts/1_Working/DEL-00-03_v2_SPEC_seed/_CONTEXT.md",
    "projects/pec/execution/PKG-01_Service_Core_Store/1_Working/DEL-01-02_Presence_tier_schema_entity_model/_CONTEXT.md",
    "projects/pec/execution/PKG-01_Service_Core_Store/1_Working/DEL-01-03_Store_bootstrap_content_minimal_guard/_CONTEXT.md",
    "projects/pec/execution/PKG-01_Service_Core_Store/1_Working/DEL-01-04_Self_observability_logging/_CONTEXT.md",
    "projects/pec/execution/PKG-01_Service_Core_Store/1_Working/DEL-01-05_Zero_dependency_locality_enforcement/_CONTEXT.md",
    "projects/pec/execution/PKG-02_File_Truth_Parsers/1_Working/DEL-02-01_STATUS_md_parser/_CONTEXT.md",
    "projects/pec/execution/PKG-02_File_Truth_Parsers/1_Working/DEL-02-02_Decision_register_packet_parser/_CONTEXT.md",
    "projects/pec/execution/PKG-03_Reconciliation_Parity/1_Working/DEL-03-01_Full_rebuild_reconciler_one_command/_CONTEXT.md",
    "projects/pec/execution/PKG-03_Reconciliation_Parity/1_Working/DEL-03-02_Incremental_reconcile_on_Git_delta/_CONTEXT.md",
    "projects/pec/execution/PKG-03_Reconciliation_Parity/1_Working/DEL-03-04_Practitioner_harness_parity_diff/_CONTEXT.md",
    "projects/pec/execution/PKG-03_Reconciliation_Parity/1_Working/DEL-03-06_Rebuild_performance_bounds/_CONTEXT.md",
    "projects/pec/execution/PKG-04_Orientation_Services/1_Working/DEL-04-02_Delta_service_since_SHA/_CONTEXT.md",
    "projects/pec/execution/PKG-04_Orientation_Services/1_Working/DEL-04-03_Citation_freshness_stamping/_CONTEXT.md",
    "projects/pec/execution/PKG-04_Orientation_Services/1_Working/DEL-04-04_Scope_parameterization/_CONTEXT.md",
    "projects/pec/execution/PKG-04_Orientation_Services/1_Working/DEL-04-05_Measurement_limitation_honesty/_CONTEXT.md",
    "projects/pec/execution/PKG-05_Gate_Evaluation_Decision_Slate/1_Working/DEL-05-02_Cross_loop_decision_slate/_CONTEXT.md",
    "projects/pec/execution/PKG-06_Presence_Git_Observation/1_Working/DEL-06-02_Git_worktree_scanner/_CONTEXT.md",
    "projects/pec/execution/PKG-06_Presence_Git_Observation/1_Working/DEL-06-03_Session_worktree_scope_correlation/_CONTEXT.md",
    "projects/pec/execution/PKG-06_Presence_Git_Observation/1_Working/DEL-06-05_TTL_heartbeat_discipline_citation_exclusion/_CONTEXT.md",
    "projects/pec/execution/PKG-06_Presence_Git_Observation/1_Working/DEL-06-06_Advisory_overlap_detection/_CONTEXT.md",
    "projects/pec/execution/PKG-07_Event_Ingest_Bridges/1_Working/DEL-07-01_Idempotent_event_ingest_durable_message_store/_CONTEXT.md",
    "projects/pec/execution/PKG-08_API_Access/1_Working/DEL-08-02_Versioned_additive_API_schema/_CONTEXT.md",
    "projects/pec/execution/PKG-08_API_Access/1_Working/DEL-08-03_Compact_citation_bearing_response_format/_CONTEXT.md",
    "projects/pec/execution/PKG-08_API_Access/1_Working/DEL-08-04_Orientation_latency_budget_p95_100_ms/_CONTEXT.md",
    "projects/pec/execution/PKG-09_Dashboards/1_Working/DEL-09-01_Overview_dashboard/_CONTEXT.md",
    "projects/pec/execution/PKG-09_Dashboards/1_Working/DEL-09-02_Lifecycle_census_dashboard/_CONTEXT.md",
    "projects/pec/execution/PKG-09_Dashboards/1_Working/DEL-09-03_Register_views/_CONTEXT.md",
    "projects/pec/execution/PKG-09_Dashboards/1_Working/DEL-09-04_Decision_slate_view_waiting_on_you/_CONTEXT.md",
    "projects/pec/execution/PKG-09_Dashboards/1_Working/DEL-09-06_Universal_drill_down_to_cited_source/_CONTEXT.md",
    "projects/pec/execution/PKG-09_Dashboards/1_Working/DEL-09-07_Explain_shaped_pressure_rules/_CONTEXT.md",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-01_Step_0_cost_baseline_pre_P1/_CONTEXT.md",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-02_Kill_test_standing_release_gate/_CONTEXT.md",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-03_No_ruling_write_verification/_CONTEXT.md",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-04_Orientation_defect_rate_spot_check/_CONTEXT.md",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-05_Owner_consultation_logging/_CONTEXT.md",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-06_Seeded_conflict_overlap_test/_CONTEXT.md",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-07_Presence_TTL_honesty_tests/_CONTEXT.md",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-09_Collision_incident_measurement/_CONTEXT.md",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-10_Directed_bootstrap_self_ingest_validation/_CONTEXT.md",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-11_Parity_metric_DriftFindings_per_reconcile/_CONTEXT.md",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-12_Poll_adoption_measurement/_CONTEXT.md",
]
REF_PATHS = [
    "projects/pec/execution/PKG-00_Architecture_Runway_Contracts/1_Working/DEL-00-01_v2_first_ADRs_core_isolation_carried_postures/_REFERENCES.md",
    "projects/pec/execution/PKG-00_Architecture_Runway_Contracts/1_Working/DEL-00-02_Event_contract_schema_v1/_REFERENCES.md",
    "projects/pec/execution/PKG-00_Architecture_Runway_Contracts/1_Working/DEL-00-03_v2_SPEC_seed/_REFERENCES.md",
    "projects/pec/execution/PKG-01_Service_Core_Store/1_Working/DEL-01-01_Record_tier_schema_entity_model/_REFERENCES.md",
    "projects/pec/execution/PKG-01_Service_Core_Store/1_Working/DEL-01-02_Presence_tier_schema_entity_model/_REFERENCES.md",
    "projects/pec/execution/PKG-01_Service_Core_Store/1_Working/DEL-01-03_Store_bootstrap_content_minimal_guard/_REFERENCES.md",
    "projects/pec/execution/PKG-01_Service_Core_Store/1_Working/DEL-01-04_Self_observability_logging/_REFERENCES.md",
    "projects/pec/execution/PKG-01_Service_Core_Store/1_Working/DEL-01-05_Zero_dependency_locality_enforcement/_REFERENCES.md",
    "projects/pec/execution/PKG-01_Service_Core_Store/1_Working/DEL-01-06_Loop_registry_local_config_default/_REFERENCES.md",
    "projects/pec/execution/PKG-02_File_Truth_Parsers/1_Working/DEL-02-01_STATUS_md_parser/_REFERENCES.md",
    "projects/pec/execution/PKG-02_File_Truth_Parsers/1_Working/DEL-02-02_Decision_register_packet_parser/_REFERENCES.md",
    "projects/pec/execution/PKG-02_File_Truth_Parsers/1_Working/DEL-02-03_Receipts_ledger_parser_per_loop_grammars/_REFERENCES.md",
    "projects/pec/execution/PKG-02_File_Truth_Parsers/1_Working/DEL-02-04_Run_evidence_JSON_parser/_REFERENCES.md",
    "projects/pec/execution/PKG-02_File_Truth_Parsers/1_Working/DEL-02-05_Dependency_register_parser/_REFERENCES.md",
    "projects/pec/execution/PKG-02_File_Truth_Parsers/1_Working/DEL-02-06_Workplan_LOOP_INIT_parser/_REFERENCES.md",
    "projects/pec/execution/PKG-02_File_Truth_Parsers/1_Working/DEL-02-07_adapter_yaml_feed_manifest_consumer/_REFERENCES.md",
    "projects/pec/execution/PKG-03_Reconciliation_Parity/1_Working/DEL-03-01_Full_rebuild_reconciler_one_command/_REFERENCES.md",
    "projects/pec/execution/PKG-03_Reconciliation_Parity/1_Working/DEL-03-02_Incremental_reconcile_on_Git_delta/_REFERENCES.md",
    "projects/pec/execution/PKG-03_Reconciliation_Parity/1_Working/DEL-03-03_Drift_classification/_REFERENCES.md",
    "projects/pec/execution/PKG-03_Reconciliation_Parity/1_Working/DEL-03-04_Practitioner_harness_parity_diff/_REFERENCES.md",
    "projects/pec/execution/PKG-03_Reconciliation_Parity/1_Working/DEL-03-05_Stream_loss_recovery_guarantee/_REFERENCES.md",
    "projects/pec/execution/PKG-03_Reconciliation_Parity/1_Working/DEL-03-06_Rebuild_performance_bounds/_REFERENCES.md",
    "projects/pec/execution/PKG-04_Orientation_Services/1_Working/DEL-04-01_Loop_orientation_return/_REFERENCES.md",
    "projects/pec/execution/PKG-04_Orientation_Services/1_Working/DEL-04-02_Delta_service_since_SHA/_REFERENCES.md",
    "projects/pec/execution/PKG-04_Orientation_Services/1_Working/DEL-04-03_Citation_freshness_stamping/_REFERENCES.md",
    "projects/pec/execution/PKG-04_Orientation_Services/1_Working/DEL-04-04_Scope_parameterization/_REFERENCES.md",
    "projects/pec/execution/PKG-04_Orientation_Services/1_Working/DEL-04-05_Measurement_limitation_honesty/_REFERENCES.md",
    "projects/pec/execution/PKG-05_Gate_Evaluation_Decision_Slate/1_Working/DEL-05-01_Gate_precondition_evaluators_Explain_shaped/_REFERENCES.md",
    "projects/pec/execution/PKG-05_Gate_Evaluation_Decision_Slate/1_Working/DEL-05-02_Cross_loop_decision_slate/_REFERENCES.md",
    "projects/pec/execution/PKG-06_Presence_Git_Observation/1_Working/DEL-06-01_Session_presence_records/_REFERENCES.md",
    "projects/pec/execution/PKG-06_Presence_Git_Observation/1_Working/DEL-06-02_Git_worktree_scanner/_REFERENCES.md",
    "projects/pec/execution/PKG-06_Presence_Git_Observation/1_Working/DEL-06-03_Session_worktree_scope_correlation/_REFERENCES.md",
    "projects/pec/execution/PKG-06_Presence_Git_Observation/1_Working/DEL-06-04_Live_hierarchy_edges/_REFERENCES.md",
    "projects/pec/execution/PKG-06_Presence_Git_Observation/1_Working/DEL-06-05_TTL_heartbeat_discipline_citation_exclusion/_REFERENCES.md",
    "projects/pec/execution/PKG-06_Presence_Git_Observation/1_Working/DEL-06-06_Advisory_overlap_detection/_REFERENCES.md",
    "projects/pec/execution/PKG-07_Event_Ingest_Bridges/1_Working/DEL-07-01_Idempotent_event_ingest_durable_message_store/_REFERENCES.md",
    "projects/pec/execution/PKG-07_Event_Ingest_Bridges/1_Working/DEL-07-02_Daemon_SSE_subscriber_bridge/_REFERENCES.md",
    "projects/pec/execution/PKG-07_Event_Ingest_Bridges/1_Working/DEL-07-03_Hooks_CLI_bridge/_REFERENCES.md",
    "projects/pec/execution/PKG-07_Event_Ingest_Bridges/1_Working/DEL-07-04_cmux_socket_adapter_optional/_REFERENCES.md",
    "projects/pec/execution/PKG-07_Event_Ingest_Bridges/1_Working/DEL-07-05_Shared_runtime_client_seam_v2/_REFERENCES.md",
    "projects/pec/execution/PKG-08_API_Access/1_Working/DEL-08-01_Unix_socket_server_token_scoped_access/_REFERENCES.md",
    "projects/pec/execution/PKG-08_API_Access/1_Working/DEL-08-02_Versioned_additive_API_schema/_REFERENCES.md",
    "projects/pec/execution/PKG-08_API_Access/1_Working/DEL-08-03_Compact_citation_bearing_response_format/_REFERENCES.md",
    "projects/pec/execution/PKG-08_API_Access/1_Working/DEL-08-04_Orientation_latency_budget_p95_100_ms/_REFERENCES.md",
    "projects/pec/execution/PKG-08_API_Access/1_Working/DEL-08-05_SSE_delta_presence_subscription/_REFERENCES.md",
    "projects/pec/execution/PKG-09_Dashboards/1_Working/DEL-09-01_Overview_dashboard/_REFERENCES.md",
    "projects/pec/execution/PKG-09_Dashboards/1_Working/DEL-09-02_Lifecycle_census_dashboard/_REFERENCES.md",
    "projects/pec/execution/PKG-09_Dashboards/1_Working/DEL-09-03_Register_views/_REFERENCES.md",
    "projects/pec/execution/PKG-09_Dashboards/1_Working/DEL-09-04_Decision_slate_view_waiting_on_you/_REFERENCES.md",
    "projects/pec/execution/PKG-09_Dashboards/1_Working/DEL-09-05_Presence_board/_REFERENCES.md",
    "projects/pec/execution/PKG-09_Dashboards/1_Working/DEL-09-06_Universal_drill_down_to_cited_source/_REFERENCES.md",
    "projects/pec/execution/PKG-09_Dashboards/1_Working/DEL-09-07_Explain_shaped_pressure_rules/_REFERENCES.md",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-01_Step_0_cost_baseline_pre_P1/_REFERENCES.md",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-02_Kill_test_standing_release_gate/_REFERENCES.md",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-03_No_ruling_write_verification/_REFERENCES.md",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-04_Orientation_defect_rate_spot_check/_REFERENCES.md",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-05_Owner_consultation_logging/_REFERENCES.md",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-06_Seeded_conflict_overlap_test/_REFERENCES.md",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-07_Presence_TTL_honesty_tests/_REFERENCES.md",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-08_Stream_loss_recovery_demonstration/_REFERENCES.md",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-09_Collision_incident_measurement/_REFERENCES.md",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-10_Directed_bootstrap_self_ingest_validation/_REFERENCES.md",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-11_Parity_metric_DriftFindings_per_reconcile/_REFERENCES.md",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-12_Poll_adoption_measurement/_REFERENCES.md",
]
REG_PATHS = [
    "projects/pec/execution/PKG-03_Reconciliation_Parity/1_Working/DEL-03-01_Full_rebuild_reconciler_one_command/Dependencies.csv",
    "projects/pec/execution/PKG-05_Gate_Evaluation_Decision_Slate/1_Working/DEL-05-01_Gate_precondition_evaluators_Explain_shaped/Dependencies.csv",
    "projects/pec/execution/PKG-05_Gate_Evaluation_Decision_Slate/1_Working/DEL-05-02_Cross_loop_decision_slate/Dependencies.csv",
    "projects/pec/execution/PKG-06_Presence_Git_Observation/1_Working/DEL-06-03_Session_worktree_scope_correlation/Dependencies.csv",
    "projects/pec/execution/PKG-08_API_Access/1_Working/DEL-08-04_Orientation_latency_budget_p95_100_ms/Dependencies.csv",
    "projects/pec/execution/PKG-08_API_Access/1_Working/DEL-08-05_SSE_delta_presence_subscription/Dependencies.csv",
    "projects/pec/execution/PKG-09_Dashboards/1_Working/DEL-09-05_Presence_board/Dependencies.csv",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-05_Owner_consultation_logging/Dependencies.csv",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-10_Directed_bootstrap_self_ingest_validation/Dependencies.csv",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-12_Poll_adoption_measurement/Dependencies.csv",
]

CTX_OLD = "then by revision 1.4 (`current_basis`, SCA-004 successor).\n"
CTX_NEW = ("then by revision 1.4 (`current_basis`, SCA-004 successor),\n"
           "then by revision 1.5 (`current_basis`, SCA-005 successor).\n")
CTX_DONE_RE = re.compile(r"revision 1\.5 \(`current_basis`,\s+SCA-005 successor")
REF_PAIRS = [
    ("- `execution/_Decomposition/SOFTWARE_DECOMP.md` (revision 1.4, accepted `current_basis`; SCA-004 successor)\n",
     "- `execution/_Decomposition/SOFTWARE_DECOMP.md` (revision 1.5, accepted `current_basis`; SCA-005 successor)\n"),
    ("- `docs/PRD.md` v2.2 (accepted source corpus; see SourceRef column of the ledger)\n",
     "- `docs/PRD.md` v2.3 (accepted source corpus; see SourceRef column of the ledger)\n"),
]

# Optional add-on R (--retired-covers): the four retired deliverables' reference packets stop
# claiming coverage of scope items that revision 1.5 moved OUT (their register cells are blank).
RETIRED_COVERS = {
    "DEL-06-04": "SOW-029", "DEL-07-02": "SOW-035", "DEL-07-04": "SOW-037", "DEL-07-05": "SOW-087",
}
COVERS_OLD = "- `execution/_Decomposition/ScopeLedger.csv` (SOW→PKG→DEL→OBJ ledger; covers {S})\n"
COVERS_NEW = ("- `execution/_Decomposition/ScopeLedger.csv` (SOW→PKG→DEL→OBJ ledger; covers none — "
              "retired under SCA-005, formerly {S})\n")

V31 = ["RegisterSchemaVersion", "DependencyID", "FromPackageID", "FromDeliverableID",
       "FromDeliverableName", "DependencyClass", "AnchorType", "Direction",
       "DependencyType", "TargetType", "TargetPackageID", "TargetDeliverableID",
       "TargetRefID", "TargetName", "TargetLocation", "Statement",
       "EvidenceFile", "SourceRef", "EvidenceQuote", "Explicitness",
       "RequiredMaturity", "ProposedMaturity", "SatisfactionStatus", "Confidence",
       "Origin", "FirstSeen", "LastSeen", "Status", "Notes"]

DCSV, LCSV = "execution/_Decomposition/Deliverables.csv", "execution/_Decomposition/ScopeLedger.csv"
RCN = "PRD.md §9.2 requirement PEC-RCN-002"
Q_DEL0101_CEN = "16 entity types (DL-14's 14 plus WorkGraph and WorkNode) and the schema every derivation package depends on"
Q_DEL0601 = ("Harness-reported session records (kind, engine/model attribution, role, loop/package binding, "
             "declared write scopes), arriving only from an explicitly authorized hooks consumer; "
             "identity/lifecycle are Runtime-owned per application (C13).")
Q_DEL0905 = ("Sessions (when hook-reported) x worktrees x graph-declared activity with heartbeat/scan age "
             "and advisory overlap warnings")
OLD_RCN = "The reconciler shall ingest, at minimum: `_STATUS.md` (declared parser dialect)"
OLD_RCN_TAIL = [
    "",
    ", decision registers and packets",
    ", decision registers and packets, `LOOP_RECEIPTS.md` (per-loop grammar; the D-APP-57 contract where a ledger has adopted it)",
    ", decision registers and packets, `LOOP_RECEIPTS.md` (per-loop grammar; the D-APP-57 contract where a ledger has adopted it), `WORK_GRAPH.json` / `STATUS.json` / `RUNTIME_SUMMARY.json`",
    ", decision registers and packets, `LOOP_RECEIPTS.md` (per-loop grammar; the D-APP-57 contract where a ledger has adopted it), `WORK_GRAPH.json` / `STATUS.json` / `RUNTIME_SUMMARY.json`, dependency registers",
    ", decision registers and packets, `LOOP_RECEIPTS.md` (per-loop grammar; the D-APP-57 contract where a ledger has adopted it), `WORK_GRAPH.json` / `STATUS.json` / `RUNTIME_SUMMARY.json`, dependency registers, workplans/LOOP_INIT",
]

# DependencyID -> (register folder under EX, EvidenceFile, SourceRef, old quote, new quote,
#                  locus (kind, key, column), reason prefix for Notes)
QUOTES = {
    "DEP-03-01-005": ("PKG-03_Reconciliation_Parity/1_Working/DEL-03-01_Full_rebuild_reconciler_one_command", DCSV,
                      "Deliverables.csv row DEL-01-01 ContextEnvelopeNotes",
                      "14 entity types and the schema every derivation package depends on", Q_DEL0101_CEN,
                      ("D", "DEL-01-01", "ContextEnvelopeNotes"), "SCA-005 A-12: DEL-01-01 envelope notes name 16 entity types"),
    "DEP-03-01-008": ("PKG-03_Reconciliation_Parity/1_Working/DEL-03-01_Full_rebuild_reconciler_one_command", "docs/PRD.md", RCN,
                      OLD_RCN + OLD_RCN_TAIL[0], "at minimum: `_STATUS.md` (declared parser dialect)",
                      ("P", "PEC-RCN-002", None), "SCA-005 A-75: PRD v2.3 PEC-RCN-002 wording"),
    "DEP-03-01-009": ("PKG-03_Reconciliation_Parity/1_Working/DEL-03-01_Full_rebuild_reconciler_one_command", "docs/PRD.md", RCN,
                      OLD_RCN + OLD_RCN_TAIL[1], "decision registers and packets (row identity and status only)",
                      ("P", "PEC-RCN-002", None), "SCA-005 A-75: PRD v2.3 PEC-RCN-002 wording"),
    "DEP-03-01-010": ("PKG-03_Reconciliation_Parity/1_Working/DEL-03-01_Full_rebuild_reconciler_one_command", "docs/PRD.md", RCN,
                      OLD_RCN + OLD_RCN_TAIL[2],
                      "receipts — `LOOP_RECEIPTS.md` ledgers (per-loop grammar; the `receipt-contract-v2` marker where a "
                      "ledger carries it; live or declared historical per profile) and central "
                      "`execution/_Coordination/AgentRuns/<RunID>/RECEIPT.md`",
                      ("P", "PEC-RCN-002", None), "SCA-005 A-75: PRD v2.3 PEC-RCN-002 wording"),
    "DEP-03-01-011": ("PKG-03_Reconciliation_Parity/1_Working/DEL-03-01_Full_rebuild_reconciler_one_command", "docs/PRD.md", RCN,
                      OLD_RCN + OLD_RCN_TAIL[3],
                      "`STATUS.json` / `RUNTIME_SUMMARY.json` as declared historical grammar or current evidence per profile",
                      ("P", "PEC-RCN-002", None), "SCA-005 A-75: PRD v2.3 PEC-RCN-002 wording"),
    "DEP-03-01-012": ("PKG-03_Reconciliation_Parity/1_Working/DEL-03-01_Full_rebuild_reconciler_one_command", "docs/PRD.md", RCN,
                      OLD_RCN + OLD_RCN_TAIL[4],
                      "dependency registers (`Dependencies.csv`; `WORK_GRAPH.json` as declared historical grammar)",
                      ("P", "PEC-RCN-002", None), "SCA-005 A-75: PRD v2.3 PEC-RCN-002 wording"),
    "DEP-03-01-013": ("PKG-03_Reconciliation_Parity/1_Working/DEL-03-01_Full_rebuild_reconciler_one_command", "docs/PRD.md", RCN,
                      OLD_RCN + OLD_RCN_TAIL[5],
                      "`LOOP_INIT.md` loop identity, entrypoint and procedure SHA only (workplans as declared historical grammar)",
                      ("P", "PEC-RCN-002", None), "SCA-005 A-75: PRD v2.3 PEC-RCN-002 wording"),
    "DEP-05-01-004": ("PKG-05_Gate_Evaluation_Decision_Slate/1_Working/DEL-05-01_Gate_precondition_evaluators_Explain_shaped", DCSV,
                      "Deliverables.csv row DEL-01-01 (ContextEnvelopeNotes)",
                      "14 entity types and the schema every derivation package depends on", Q_DEL0101_CEN,
                      ("D", "DEL-01-01", "ContextEnvelopeNotes"), "SCA-005 A-12: DEL-01-01 envelope notes name 16 entity types"),
    "DEP-05-02-003": ("PKG-05_Gate_Evaluation_Decision_Slate/1_Working/DEL-05-02_Cross_loop_decision_slate", DCSV,
                      "Deliverables.csv row DEL-01-01 (ContextEnvelopeNotes)",
                      "14 entity types and the schema every derivation package depends on", Q_DEL0101_CEN,
                      ("D", "DEL-01-01", "ContextEnvelopeNotes"), "SCA-005 A-12: DEL-01-01 envelope notes name 16 entity types"),
    "DEP-06-03-003": ("PKG-06_Presence_Git_Observation/1_Working/DEL-06-03_Session_worktree_scope_correlation", DCSV,
                      "Deliverables.csv row DEL-06-01 (Description)",
                      "Harness-reported session records (kind, engine/model attribution, role, loop/package binding, "
                      "declared write scopes); identity/lifecycle stay daemon-owned.", Q_DEL0601,
                      ("D", "DEL-06-01", "Description"), "SCA-005 A-37: DEL-06-01 description re-expressed"),
    "DEP-08-04-005": ("PKG-08_API_Access/1_Working/DEL-08-04_Orientation_latency_budget_p95_100_ms", "docs/PRD.md",
                      "PRD.md §9.6 requirement PEC-API-002",
                      "Orientation reads shall complete in ≤100 ms at p95 against the current corpus (session-start critical path).",
                      "Orientation reads shall complete in ≤100 ms at p95 against the current corpus (latency-sensitive pull "
                      "path; any session-start use requires a separately adopted consumer duty).",
                      ("P", "PEC-API-002", None), "PRD v2.2 PEC-API-002 wording, D-PEC-68; stale before SCA-005"),
    "DEP-08-05-004": ("PKG-08_API_Access/1_Working/DEL-08-05_SSE_delta_presence_subscription", DCSV,
                      "Deliverables.csv row DEL-06-01 Description",
                      "Harness-reported session records (kind, engine/model attribution, role, loop/package binding, "
                      "declared write scopes); identity/lifecycle stay daemon-owned.", Q_DEL0601,
                      ("D", "DEL-06-01", "Description"), "SCA-005 A-37: DEL-06-01 description re-expressed"),
    "DEP-09-05-006": ("PKG-09_Dashboards/1_Working/DEL-09-05_Presence_board", DCSV, "Deliverables.csv row DEL-09-05",
                      "Sessions x worktrees x live hierarchy with heartbeat age and advisory overlap warnings.", Q_DEL0905,
                      ("D", "DEL-09-05", "Description"), "SCA-005 A-38: DEL-09-05 description re-expressed"),
    "DEP-09-05-007": ("PKG-09_Dashboards/1_Working/DEL-09-05_Presence_board", LCSV, "ScopeLedger.csv row SOW-049",
                      "Dashboard — presence board: sessions × worktrees × live hierarchy with heartbeat age and advisory overlap warnings",
                      "Dashboard — presence board: sessions (when hook-reported) × worktrees × graph-declared activity, "
                      "with heartbeat/scan age and advisory overlap warnings",
                      ("L", "SOW-049", "ScopeItemStatement"), "SCA-005 A-33: SOW-049 statement re-expressed"),
    "DEP-09-05-008": ("PKG-09_Dashboards/1_Working/DEL-09-05_Presence_board", DCSV, "Deliverables.csv row DEL-09-05",
                      "Sessions x worktrees x live hierarchy with heartbeat age and advisory overlap warnings.", Q_DEL0905,
                      ("D", "DEL-09-05", "Description"), "SCA-005 A-38: DEL-09-05 description re-expressed"),
    "DEP-10-05-004": ("PKG-10_Validation_Measurement/1_Working/DEL-10-05_Owner_consultation_logging", DCSV,
                      "Deliverables.csv row DEL-10-05 Description column",
                      "Orientation-read and dashboard-consultation logging sufficient to evaluate the P2 exit test",
                      "Owner use or non-use logging sufficient for the P2-B uptake observation and falsification evidence",
                      ("D", "DEL-10-05", "Description"), "SCA-003 revision 1.3: DEL-10-05 description re-expressed; stale before SCA-005"),
    "DEP-10-05-005": ("PKG-10_Validation_Measurement/1_Working/DEL-10-05_Owner_consultation_logging", LCSV,
                      "ScopeLedger.csv row SOW-085",
                      "Log orientation-read and dashboard-consultation activity sufficient to evaluate the §12 P2 exit test",
                      "Log owner use or non-use of PEC orientation and dashboard surfaces sufficient to evaluate the §12 "
                      "P2-B uptake observation and the §11 falsification clause",
                      ("L", "SOW-085", "ScopeItemStatement"), "SCA-003 revision 1.3: SOW-085 statement re-expressed; stale before SCA-005"),
    "DEP-10-10-003": ("PKG-10_Validation_Measurement/1_Working/DEL-10-10_Directed_bootstrap_self_ingest_validation", DCSV,
                      "Deliverables.csv row DEL-02-05 (Description column)",
                      "`Dependencies.csv` and `WORK_GRAPH.json` into DependencyEdge.",
                      "`Dependencies.csv`, and `WORK_GRAPH.json` as a declared historical grammar for App/Piping, into DependencyEdge",
                      ("D", "DEL-02-05", "Description"), "SCA-005 A-16: DEL-02-05 description re-expressed"),
    "DEP-10-12-003": ("PKG-10_Validation_Measurement/1_Working/DEL-10-12_Poll_adoption_measurement", LCSV,
                      "ScopeLedger.csv row SOW-004 (ScopeItemStatement; DeliverableIDs names DEL-04-01)",
                      "Serve per-loop orientation: newest applicable receipt, examined-through SHA, gate states, owner "
                      "directions of record, open tranches/candidate briefs, parked lanes each with its unparking owner action",
                      "Serve per-loop orientation: newest applicable receipt over central receipts and ledgers, "
                      "examined-through SHA, gate states from decisions, scope-change state and graph BLOCKED nodes, owner "
                      "directions of record, open tranches/candidate briefs and parked lanes over graph READY/ACTIVE/BLOCKED "
                      "nodes, each parked lane with its unparking owner action",
                      ("L", "SOW-004", "ScopeItemStatement"), "SCA-005 A-02: SOW-004 statement re-sourced"),
}

# ------------------------------------------------------------------ N1 text

DECOMP_LATEST_OLD = """- **Audit:**
  `_Evaluation/DecompCoverage/COV_SCA005_POSTCHANGE_2026-09-25_1344/`;
  `BLOCKERS` by the method's count rule (2 / 6 / 74). Both blockers are the
  absent DEL-02-08/09 folders, an expected consequence of the owner's
  deferral of Lane A4; excluding expected consequences, 0 blockers / 4
  warnings. The audit folder's own `_LATEST.md` still names the SCA-004
  audit; moving it was not part of this act.
- **Scope-change snapshot:** `_ScopeChange/SCA-005_2026-09-23_2139/`.
- **Derivative state:** `INCOMPLETE`; `DownstreamRerunState = FROZEN`;
  `MetadataAlignmentState = IN_PROGRESS`; `ReadyForNextPhase = NO`. The
  SCA-004 downstream repairs closed on 2026-08-09
  (`_Coordination/PEC_CURRENCY_REPAIR_CLOSEOUT_2026-08-09/HANDOFF_STATE.md`).
  Open SCA-005 work, each separately gated, is listed in the SCA-005
  `Handoff_State.md` and `RUN_SUMMARY.md`: DEL-02-08/09 preparation with
  the dependency rerun (PROJECT_SETUP, own packet), context and reference
  re-pinning, SOW currency, derivative-artifact review, the registry source
  packet, fixtures, TM-PEC-023 disposition, the `projects/pec/AGENTS.md`
  instruction tranche, the D-PEC-90 reliance amendment, a re-audit after the
  DEL-02-08/09 preparation, and (under its own grant) moving the audit
  folder's `_LATEST.md` to the SCA-005 audit.
"""
DECOMP_LATEST_NEW = """- **Audit:**
  `_Evaluation/DecompCoverage/COV_SCA005_POSTSETUP_2026-09-25_1606/`, which
  the audit folder's `_LATEST.md` names: `WARNINGS`, 0 blockers / 3
  warnings / 70 info, run after PROJECT_SETUP created DEL-02-08/09 and
  applied the dependency rerun under `D-PEC-93`. The three warnings are
  pre-existing (v2 artifacts held outside their deliverable folders). Its
  INFO findings COV-068/069 (context and reference pins), COV-072
  (evidence-quote currency) and COV-073 (stale handoff text) were addressed
  on {D} under `D-PEC-95` without a further audit. The checkpoint-3 audit
  `COV_SCA005_POSTCHANGE_2026-09-25_1344/` is superseded.
- **Scope-change snapshot:** `_ScopeChange/SCA-005_2026-09-23_2139/`.
- **Derivative state:** `INCOMPLETE`; `DownstreamRerunState = IN_PROGRESS`;
  `MetadataAlignmentState = COMPLETE`; `ReadyForNextPhase = NO`. Done under
  their own packets: DEL-02-08/09 preparation with the dependency rerun, the
  re-audit and the audit-pointer move (`D-PEC-93`; closeout
  `_Coordination/PROJECT_SETUP_SCA005_A4_B3_2026-09-25/HANDOFF_STATE.md`);
  context and reference re-pinning and the evidence-quote refresh
  (`D-PEC-95`). `projects/pec/AGENTS.md` names PRD v2.3 and the D-GOV-43
  Runtime boundary since `D-PEC-94`. Open, each separately gated: SOW
  currency, derivative-artifact review, the registry source packet,
  fixtures and the D-PEC-90 reliance amendment; TM-PEC-023's state is in
  the Task Management register. Undertaking
  `HELP-HUMAN-PEC-20260925-POST-SCA005` plans the open items in
  `_Coordination/WorkGraphs/HELP-HUMAN-PEC-20260925-POST-SCA005/WORK_GRAPH.md`.
  The SCA-004 downstream repairs closed on 2026-08-09
  (`_Coordination/PEC_CURRENCY_REPAIR_CLOSEOUT_2026-08-09/HANDOFF_STATE.md`).
"""

SC_LATEST_ROWS = [
    ("| DerivativePackageState | `INCOMPLETE` — Lane B and the deferred A4 remain open |\n",
     "| DerivativePackageState | `INCOMPLETE` — A4 and B3 done under `D-PEC-93`, B1 under `D-PEC-95`; B4–B7 and the D-PEC-90 reliance amendment remain open |\n"),
    ("| DownstreamRerunState | `FROZEN` — no Lane B rerun authorized by checkpoint 3 |\n",
     "| DownstreamRerunState | `IN_PROGRESS` — B1 and B3 applied under their own packets; each other Lane B rerun is separately gated |\n"),
    ("| MetadataAlignmentState | `IN_PROGRESS` — 22 direct context mirrors done; 42 contexts and 64 references await re-pinning |\n",
     "| MetadataAlignmentState | `COMPLETE` — 22 direct context mirrors, the two new deliverables' files, and 42 contexts and 64 references re-pinned to revision 1.5 on {D} (`D-PEC-95`) |\n"),
    ("| AuditState | **`BLOCKED`** by the count rule — `COV_SCA005_POSTCHANGE_2026-09-25_1344`, 2 blockers (both the A4 deferral's expected consequence) / 6 warnings / 74 info; excluding expected consequences 0 blockers / 4 warnings |\n",
     "| AuditState | `WARNINGS` — `COV_SCA005_POSTSETUP_2026-09-25_1606`, 0 blockers / 3 pre-existing warnings / 70 info; its INFO findings COV-068/069/072/073 addressed on {D} under `D-PEC-95` without a further audit |\n"),
]
SC_LATEST_BOUNDARY_OLD = """Checkpoint 3 authorizes no downstream repair. `SCA-005_2026-09-23_2139/Handoff_State.md`
and `RUN_SUMMARY.md` name every open item and owner: DEL-02-08/09 folders
with the dependency rerun (PROJECT_SETUP under its own packet), context and
reference re-pinning, SOW currency, DEL-00-01/00-03 derivative review, the
registry source packet, P1 fixtures, TM-PEC-023 disposition, the D-PEC-90
reliance amendment, and the `projects/pec/AGENTS.md` instruction tranche.
Each is separately gated.
"""
SC_LATEST_BOUNDARY_NEW = """Checkpoint 3 authorized no downstream repair; each downstream item is
separately gated. Done: the DEL-02-08/09 folders with the dependency
rerun, the post-setup re-audit and the audit-pointer move (`D-PEC-93`;
closeout `_Coordination/PROJECT_SETUP_SCA005_A4_B3_2026-09-25/HANDOFF_STATE.md`),
and context and reference re-pinning with the evidence-quote refresh
(`D-PEC-95`, {D}). `projects/pec/AGENTS.md` names PRD v2.3 and the D-GOV-43
Runtime boundary since `D-PEC-94`. Open: SOW currency, DEL-00-01/00-03
derivative review, the registry source packet, P1 fixtures and the D-PEC-90
reliance amendment; TM-PEC-023's state is in the Task Management register.
Undertaking `HELP-HUMAN-PEC-20260925-POST-SCA005` plans the open items in
`_Coordination/WorkGraphs/HELP-HUMAN-PEC-20260925-POST-SCA005/WORK_GRAPH.md`.
"""

COORD_BASIS_OLD = """- Accepted upstream basis: `execution/_Decomposition/SOFTWARE_DECOMP.md`
  revision **1.4** (`current_basis`, SCA-004 successor, accepted
  2026-08-03 under D-PEC-78 O-A; evidence
  `execution/_ScopeChange/SCA-004_2026-08-02_2325/`). Historical:
  revision 1.1 was the basis at this gate's ruling, revision 1.2 was accepted
  through SCA-002, and revision 1.3 through SCA-003; read
  `execution/_Decomposition/_LATEST.md` first, always.
"""
COORD_BASIS_NEW = """- Accepted upstream basis: `execution/_Decomposition/SOFTWARE_DECOMP.md`
  revision **1.5** (`current_basis`, SCA-005 successor, accepted
  2026-09-25 at SCA-005 checkpoint 3 after the checkpoint-2 ruling
  `D-PEC-92`; evidence `execution/_ScopeChange/SCA-005_2026-09-23_2139/`).
  Historical: revision 1.1 was the basis at this gate's ruling, revision 1.2
  was accepted through SCA-002, revision 1.3 through SCA-003, and revision
  1.4 through SCA-004 (2026-08-03, D-PEC-78 O-A); read
  `execution/_Decomposition/_LATEST.md` first, always.
"""
COORD_ITEM14_ANCHOR = """    separate TASK_MANAGEMENT disposition; this item records no row closure.

## Notes (human-owned)
"""
COORD_ITEM14 = """    separate TASK_MANAGEMENT disposition; this item records no row closure.

14. **SCA-005 feed-model rebaseline and downstream currency (2026-09-25):**
    revision **1.5** is accepted `current_basis` and PRD v2.3 is the
    product definition of record (SCA-005 checkpoint 3, after the
    checkpoint-2 ruling `D-PEC-92`). The owner's TM-PEC-023 selections are
    applied in revision 1.5: every IN scope item and active deliverable maps
    to an objective. Four deliverables are retired (DEL-06-04, DEL-07-02,
    DEL-07-04, DEL-07-05) and two added (DEL-02-08, DEL-02-09). `D-PEC-93`
    prepared the two new folders and applied the dependency rerun: 66
    registers, 263 rows, strict validator 0 errors / 0 warnings; 111
    execution edges over 66 nodes, 0 SCCs, 0 bidirectional pairs. Evidence:
    `PROJECT_SETUP_SCA005_A4_B3_2026-09-25/HANDOFF_STATE.md` and the audit
    `execution/_Evaluation/DecompCoverage/COV_SCA005_POSTSETUP_2026-09-25_1606/`.
    `D-PEC-95` ({D}) re-pinned the remaining 42 contexts and 64 reference
    packets to revision 1.5 and refreshed 19 stale dependency evidence
    quotes. {SNAPSHOT_SENTENCE}
    This item supersedes the present-tense statements of items 12 and 13
    (revision 1.4 as `current_basis`, TM-PEC-023 held for a mapping
    session, and the two-category derivative state). Remaining
    downstream work is planned in
    `WorkGraphs/HELP-HUMAN-PEC-20260925-POST-SCA005/WORK_GRAPH.md`. No
    source, lifecycle, release, or reliance act is inferred.

## Notes (human-owned)
"""
SNAPSHOT_SENTENCE = {
    "A": ("The SCA-005 snapshot's `Handoff_State.md` and `RUN_SUMMARY.md` carry\n"
          "    dated post-closure notes; their earlier sections are unchanged."),
    "P": ("The SCA-005 snapshot's `Handoff_State.md` (SHA-256\n"
          "    `a86ae910d0c9ae7bf20a7ebb47de3edb345d1a6067cb1988fc04d5c1d213328a`) and\n"
          "    `RUN_SUMMARY.md` (SHA-256\n"
          "    `e9a0224ec0152bba75c78b84e2c9abe7a5996014eec602b46de4fe3153c1e518`)\n"
          "    stay byte-identical; for current state they are superseded by this\n"
          "    item and the two `_LATEST.md` pointers."),
}
COORD_NOTE_OLD = """  (revision 1.1 at seeding; revision 1.4 is `current_basis` since
  SCA-004, with topology and execution-dependency bytes preserved) and are never a
  substitute for decomposition truth.
"""
COORD_NOTE_NEW = """  (revision 1.1 at seeding; revision 1.5 is `current_basis` since
  SCA-005, whose dependency rerun under `D-PEC-93` retired, refreshed and
  added register rows) and are never a substitute for decomposition truth.
"""

HANDOFF_NOTE = (
    "\nAmendment {D} (post-closure outcome note, `D-PEC-95`; append-only): this note records "
    "later downstream acts and rewrites nothing above; the checkpoint-3 state fields above remain "
    "the record of that acceptance. After checkpoint 3, PROJECT_SETUP ran A4 with B3 under `D-PEC-93` "
    "(PR #914, merge `961ee1054210fbae7ef5b403547e7a397fb18c95`; closeout "
    "`_Coordination/PROJECT_SETUP_SCA005_A4_B3_2026-09-25/HANDOFF_STATE.md`): the DEL-02-08 and "
    "DEL-02-09 folders exist at `OPEN`; 20 dependency rows were retired, 1 refreshed and 8 added; the "
    "strict register validator reads 0 errors / 0 warnings; the dependency graph has 111 execution "
    "edges and 0 SCCs. The re-audit `COV_SCA005_POSTSETUP_2026-09-25_1606` reads `WARNINGS` "
    "(0 blockers / 3 warnings / 70 info), and `_Evaluation/DecompCoverage/_LATEST.md` names it. On {D}, "
    "under `D-PEC-95`, B1 re-pinned the remaining 42 `_CONTEXT.md` and 64 `_REFERENCES.md` to "
    "revision 1.5, and 19 stale `EvidenceQuote` cells in 10 `Dependencies.csv` registers were "
    "refreshed (that re-audit's COV-072). `projects/pec/AGENTS.md` names PRD v2.3 and the D-GOV-43 "
    "Runtime boundary since `D-PEC-94` (PR #917). State fields now: `DecompositionTruthState` "
    "`COMPLETE`; `DerivativePackageState` `INCOMPLETE`; `ContentRemediationState` `NOT_REQUIRED`; "
    "`DownstreamRerunState` `IN_PROGRESS`; `MetadataAlignmentState` `COMPLETE`; `AuditState` "
    "`WARNINGS`; `ReadyForNextPhase` `NO`; closure verdict `CLOSED_FOR_SCOPE_CHANGE_ONLY` (unchanged). "
    "Open, each separately gated: B4–B7 and the D-PEC-90 reliance amendment; TM-PEC-023's state "
    "is in the Task Management register. `RUN_SUMMARY.md` gains a dated section with the same facts "
    "and now hashes `{RUNSUM_POST}`.\n")

RUNSUM_SECTION = """
## Post-closure outcome ({D}, `D-PEC-95`; append-only)

This section adds later facts. Nothing above is rewritten; the sections above
remain the record of checkpoint 3. Audit IDs below are those of
`COV_SCA005_POSTSETUP_2026-09-25_1606`, not of the checkpoint-3 audit.

| Item | State on {D} | Record |
|---|---|---|
| A4 — DEL-02-08/09 folders | DONE — both `OPEN` | `D-PEC-93`, PR #914; `_Coordination/PROJECT_SETUP_SCA005_A4_B3_2026-09-25/HANDOFF_STATE.md` |
| B3 — dependency rerun | DONE — 20 rows retired, 1 refreshed, 8 added; 111 execution edges, 0 SCCs; strict validator 0 / 0 | same |
| Re-audit after A4 and B3 | DONE — `WARNINGS`, 0 blockers / 3 warnings / 70 info; `_Evaluation/DecompCoverage/_LATEST.md` names it | same |
| B1 — re-pin 42 `_CONTEXT.md` and 64 `_REFERENCES.md` | DONE | `D-PEC-95` |
| Evidence-quote currency, 19 rows in 10 registers (COV-072) | DONE — every ACTIVE execution quote is verbatim in its cited file | `D-PEC-95` |
| B4–B7 | OPEN — each separately gated | undertaking `HELP-HUMAN-PEC-20260925-POST-SCA005` work graph |
| B8 — D-PEC-90 reliance amendment | OPEN — next PEC scope change | same |
| B8 — `projects/pec/AGENTS.md` L28/L170 and Shared Runtime Boundary | DONE — PRD v2.3 and the D-GOV-43 Runtime boundary | `D-PEC-94`, PR #917 |
| B8 — TM-PEC-023 | see the Task Management register | task-management |

State fields now: `DecompositionTruthState` `COMPLETE`; `DerivativePackageState` `INCOMPLETE`; `ContentRemediationState` `NOT_REQUIRED`; `DownstreamRerunState` `IN_PROGRESS`; `MetadataAlignmentState` `COMPLETE`; `AuditState` `WARNINGS`; `ReadyForNextPhase` `NO`; closure verdict `CLOSED_FOR_SCOPE_CHANGE_ONLY` (unchanged).
"""


class Fail(Exception):
    pass


def sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def replace_once(text: str, old: str, new: str, where: str) -> str:
    n = text.count(old)
    if n != 1:
        raise Fail(f"anchor count {n} != 1 in {where}: {old[:80]!r}")
    return text.replace(old, new)


def append_note(text: str, note: str, where: str) -> str:
    if not text.endswith("\n") or text.endswith("\n\n"):
        raise Fail(f"{where}: does not end with exactly one newline")
    return text + note


def csv_line(values: list[str]) -> str:
    out = io.StringIO()
    csv.writer(out, lineterminator="\r\n").writerow(values)
    return out.getvalue()


def split_register(raw: bytes, where: str) -> tuple[str, list[str]]:
    text = raw.decode("utf-8")
    lines = text.split("\r\n")
    if lines[-1] != "" or any("\n" in ln for ln in lines):
        raise Fail(f"{where}: not uniformly CRLF-terminated single-line rows")
    lines = lines[:-1]
    if next(csv.reader([lines[0]])) != V31:
        raise Fail(f"{where}: header is not exact v3.1")
    return lines[0], lines[1:]


def locus_text(kind, key, col, prd_text, dels, ledger) -> str:
    if kind == "P":
        rows = [ln for ln in prd_text.splitlines() if ln.startswith(f"| {key} |")]
        if len(rows) != 1:
            raise Fail(f"PRD requirement row {key} found {len(rows)} times")
        return rows[0]
    if kind == "D":
        return dels[key][col]
    if kind == "L":
        return ledger[key][col]
    raise Fail(f"unknown locus kind {kind}")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", required=True, type=Path)
    ap.add_argument("--act-date", required=True)
    ap.add_argument("--option", choices=["A", "P"], default="A")
    ap.add_argument("--check-only", action="store_true")
    ap.add_argument("--reproduction", action="store_true")
    ap.add_argument("--retired-covers", action="store_true")
    a = ap.parse_args()
    repo, act = a.repo.resolve(), a.act_date
    report: list[tuple[str, str, str, str]] = []
    try:
        if not re.fullmatch(r"\d{4}-\d{2}-\d{2}", act):
            raise Fail("act-date must be YYYY-MM-DD")
        today = time.strftime("%Y-%m-%d")
        if today != act and not a.reproduction:
            raise Fail(f"local date {today} != --act-date {act}; nothing written")
        # 0. preimages (targets and basis)
        for rel, want in PREIMAGES.items():
            got = sha((repo / rel).read_bytes())
            if got != want:
                raise Fail(f"preimage mismatch {rel}: {got} != {want}")
            report.append(("READ", rel, got, ""))
        prd_text = (repo / PRD).read_text(encoding="utf-8")
        with open(repo / DELIVERABLES, newline="", encoding="utf-8") as f:
            dels = {r["DeliverableID"]: r for r in csv.DictReader(f)}
        with open(repo / LEDGER, newline="", encoding="utf-8") as f:
            ledger = {r["ScopeItemID"]: r for r in csv.DictReader(f)}

        writes: dict[str, bytes] = {}
        # 1. N2 population (fail closed on any drift) and re-pin
        work = repo / EX
        all_ctx = sorted(str(p.relative_to(repo)) for p in work.glob("PKG-*/1_Working/DEL-*/_CONTEXT.md"))
        all_ref = sorted(str(p.relative_to(repo)) for p in work.glob("PKG-*/1_Working/DEL-*/_REFERENCES.md"))
        ctext = {p: (repo / p).read_text(encoding="utf-8") for p in all_ctx}
        rtext = {p: (repo / p).read_text(encoding="utf-8") for p in all_ref}
        need_ctx = [p for p in all_ctx if CTX_OLD in ctext[p]]
        need_ref = [p for p in all_ref if REF_PAIRS[0][0] in rtext[p]]
        if (len(all_ctx), len(all_ref)) != (66, 66):
            raise Fail(f"deliverable population {len(all_ctx)} contexts / {len(all_ref)} references, expected 66 / 66")
        for p in all_ctx:  # each context is pending (1.4 tail) or already names revision 1.5, never both or neither
            if (CTX_OLD in ctext[p]) == bool(CTX_DONE_RE.search(ctext[p])):
                raise Fail(f"context provenance is both or neither pending and current: {p}")
        for p in all_ref:
            if (REF_PAIRS[0][0] in rtext[p]) == (REF_PAIRS[0][1] in rtext[p]):
                raise Fail(f"reference packet is both or neither at revision 1.4 and 1.5: {p}")
        if need_ctx != sorted(CTX_PATHS) or need_ref != sorted(REF_PATHS):
            raise Fail(f"re-pin population {len(need_ctx)} / {len(need_ref)} differs from the pinned 42 / 64 lists")
        for p in need_ctx:
            writes[p] = replace_once(ctext[p], CTX_OLD, CTX_NEW, p).encode("utf-8")
        for p in need_ref:
            t = rtext[p]
            for old, new in REF_PAIRS:
                t = replace_once(t, old, new, p)
            if a.retired_covers:
                folder = Path(p).parent.name
                for del_id, sow in RETIRED_COVERS.items():
                    if folder.startswith(del_id + "_"):
                        if dels[del_id]["CoversScopeItems"] or ledger[sow]["InOutStatus"] != "OUT":
                            raise Fail(f"{del_id}/{sow}: register no longer shows the retirement")
                        t = replace_once(t, COVERS_OLD.replace("{S}", sow), COVERS_NEW.replace("{S}", sow), p)
            writes[p] = t.encode("utf-8")

        # 2. N3 quote refresh
        by_reg: dict[str, dict[str, tuple]] = {}
        for dep, spec in QUOTES.items():
            by_reg.setdefault(f"{EX}/{spec[0]}/Dependencies.csv", {})[dep] = spec
        if sorted(by_reg) != sorted(REG_PATHS):
            raise Fail("register set differs from the pinned 10")
        for reg, specs in sorted(by_reg.items()):
            header, lines = split_register((repo / reg).read_bytes(), reg)
            out, seen = [header + "\r\n"], set()
            for ln in lines:
                values = next(csv.reader([ln]))
                if csv_line(values) != ln + "\r\n":
                    raise Fail(f"{reg}: row does not round-trip byte-exactly: {values[1]}")
                dep = values[1]
                if dep not in specs:
                    out.append(ln + "\r\n")
                    continue
                if dep in seen:
                    raise Fail(f"{reg}: duplicate {dep}")
                _, evfile, srcref, old_q, new_q, (kind, key, col), why = specs[dep]
                row = dict(zip(V31, values))
                if (row["DependencyClass"], row["Status"]) != ("EXECUTION", "ACTIVE"):
                    raise Fail(f"{dep}: not ACTIVE EXECUTION")
                if (row["EvidenceFile"], row["SourceRef"], row["EvidenceQuote"]) != (evfile, srcref, old_q):
                    raise Fail(f"{dep}: EvidenceFile/SourceRef/EvidenceQuote differ from the pinned preimage")
                if new_q not in locus_text(kind, key, col, prd_text, dels, ledger):
                    raise Fail(f"{dep}: new quote not verbatim in its locus {kind}:{key}:{col}")
                row["EvidenceQuote"] = new_q
                row["LastSeen"] = act
                row["Notes"] = f"Evidence refreshed under D-PEC-95 ({why}); {row['Notes']}"
                out.append(csv_line([row[k] for k in V31]))
                seen.add(dep)
            if seen != set(specs):
                raise Fail(f"{reg}: rows not found {sorted(set(specs) - seen)}")
            writes[reg] = "".join(out).encode("utf-8")

        # 3. corpus-wide quote currency on the rendered state (ACTIVE EXECUTION rows)
        n_active = n_ok = 0
        for p in sorted(work.glob("PKG-*/1_Working/DEL-*/Dependencies.csv")):
            rel = str(p.relative_to(repo))
            data = writes.get(rel, p.read_bytes()).decode("utf-8")
            for r in csv.DictReader(io.StringIO(data, newline="")):
                if (r["DependencyClass"], r["Status"]) != ("EXECUTION", "ACTIVE"):
                    continue
                n_active += 1
                ev = repo / PEC / r["EvidenceFile"]
                if ev.is_file() and r["EvidenceQuote"] in ev.read_text(encoding="utf-8"):
                    n_ok += 1
                else:
                    raise Fail(f"quote not verbatim after rendering: {r['DependencyID']} in {r['EvidenceFile']}")
        report.append(("CHECK", "active_execution_quotes_verbatim", str(n_ok), str(n_active)))

        # 4. N1 records currency
        t = (repo / DECOMP_LATEST).read_text(encoding="utf-8")
        writes[DECOMP_LATEST] = replace_once(t, DECOMP_LATEST_OLD, DECOMP_LATEST_NEW.replace("{D}", act),
                                             DECOMP_LATEST).encode("utf-8")
        t = (repo / SC_LATEST).read_text(encoding="utf-8")
        for old, new in SC_LATEST_ROWS:
            t = replace_once(t, old, new.replace("{D}", act), SC_LATEST)
        t = replace_once(t, SC_LATEST_BOUNDARY_OLD, SC_LATEST_BOUNDARY_NEW.replace("{D}", act), SC_LATEST)
        writes[SC_LATEST] = t.encode("utf-8")
        t = (repo / COORD).read_text(encoding="utf-8")
        t = replace_once(t, COORD_BASIS_OLD, COORD_BASIS_NEW, COORD)
        t = replace_once(t, COORD_ITEM14_ANCHOR,
                         COORD_ITEM14.replace("{D}", act).replace("{SNAPSHOT_SENTENCE}", SNAPSHOT_SENTENCE[a.option]),
                         COORD)
        t = replace_once(t, COORD_NOTE_OLD, COORD_NOTE_NEW, COORD)
        writes[COORD] = t.encode("utf-8")
        if a.option == "A":
            rs = append_note((repo / RUNSUM).read_text(encoding="utf-8"), RUNSUM_SECTION.replace("{D}", act), RUNSUM)
            writes[RUNSUM] = rs.encode("utf-8")
            note = HANDOFF_NOTE.replace("{D}", act).replace("{RUNSUM_POST}", sha(writes[RUNSUM]))
            writes[HANDOFF] = append_note((repo / HANDOFF).read_text(encoding="utf-8"), note, HANDOFF).encode("utf-8")

        expected = set(CTX_PATHS) | set(REF_PATHS) | set(REG_PATHS) | {DECOMP_LATEST, SC_LATEST, COORD}
        if a.option == "A":
            expected |= {HANDOFF, RUNSUM}
        if set(writes) != expected:
            raise Fail(f"write set differs from the grant: {sorted(set(writes) ^ expected)[:5]}")
        for rel in writes:
            if rel not in PREIMAGES:
                raise Fail(f"write target without a pinned preimage: {rel}")

        # 5. write (all postimages computed and checked above)
        agg_pre, agg_post = hashlib.sha256(), hashlib.sha256()
        for rel in sorted(writes):
            pre = (repo / rel).read_bytes()
            agg_pre.update(pre)
            agg_post.update(writes[rel])
            if not a.check_only:
                (repo / rel).write_bytes(writes[rel])
            report.append(("WRITE" if not a.check_only else "RENDER", rel, sha(pre), sha(writes[rel])))
        paths = "".join(r + "\n" for r in sorted(writes)).encode("utf-8")
        tag = a.option + ("+R" if a.retired_covers else "")
        report.append(("AGGREGATE", f"option={tag} files={len(writes)}", agg_pre.hexdigest(), agg_post.hexdigest()))
        report.append(("PATHLIST", f"option={tag}", sha(paths), ""))
    except Fail as exc:
        print(f"FAIL: {exc}", file=sys.stderr)
        return 1
    for row in report:
        print("\t".join(row))
    return 0


if __name__ == "__main__":
    sys.exit(main())
