#!/usr/bin/env python3
"""Fill gen_d101_k1.template.py's pinned block from a git-archive export of the preimage commit.

Usage: python3 build_gen_d101_k1.py <export_root> <template> <out>
Preparation aid only; the bound generator is its output.
"""
import glob, hashlib, sys
from pathlib import Path
root, tpl, out = Path(sys.argv[1]), Path(sys.argv[2]), Path(sys.argv[3])
EX = "projects/pec/execution"
def sha(p): return hashlib.sha256((root / p).read_bytes()).hexdigest()
def folder(did):
    hits = glob.glob(str(root / EX / f"PKG-*/1_Working/{did}_*"))
    assert len(hits) == 1, (did, hits)
    return str(Path(hits[0]).relative_to(root))
MIRRORS = ["DEL-02-01", "DEL-02-02", "DEL-02-03", "DEL-02-04", "DEL-02-05", "DEL-02-06", "DEL-02-08", "DEL-02-09",
           "DEL-03-04", "DEL-04-01", "DEL-04-03", "DEL-04-05", "DEL-08-01", "DEL-08-02", "DEL-08-03", "DEL-10-02"]
REGS = ["DEL-04-03", "DEL-08-03", "DEL-09-06", "DEL-10-03"]
dirs = {d: folder(d) for d in sorted(set(MIRRORS) | set(REGS))}
targets = sorted([f"{dirs[d]}/_DEPENDENCIES.md" for d in MIRRORS] + [f"{dirs[d]}/Dependencies.csv" for d in REGS])
basis = [f"{EX}/_Decomposition/Deliverables.csv", f"{EX}/_Decomposition/ScopeLedger.csv",
         f"{EX}/_Decomposition/SOFTWARE_DECOMP.md", "projects/pec/docs/PRD.md",
         "tools/scaffolding/write_status.sh", "tools/scaffolding/scaffold_deliverable.sh",
         "tools/validation/check_min_viable_fileset.sh"]
assert len(targets) == 20
L = ["# Pinned at origin/main aca930622ba167689881416044ba0feaee3ef003 (generated by build_gen_d101_k1.py).",
     "# Read-only basis: the four decomposition/PRD files and three tools. Every other entry is a write target.",
     "DIRS = {"] + [f'    "{d}": "{p}",' for d, p in dirs.items()] + ["}", "PREIMAGES = {"]
L += [f'    "{p}": "{sha(p)}",' for p in basis + targets] + ["}", "GRANT_MODIFY = ["]
L += [f'    "{p}",' for p in targets] + ["]"]
text = tpl.read_text(encoding="utf-8").replace("# @@PINNED@@", "\n".join(L))
out.write_text(text, encoding="utf-8")
print(out, hashlib.sha256(out.read_bytes()).hexdigest())
