import {it,expect,vi,afterEach} from 'vitest';
import {readFileSync,writeFileSync} from 'node:fs';
import {invoke} from '@tauri-apps/api/core';
import {runPreviewMechanics,hasNativeMechanicsInvocation,retainedNativeMechanicsInvocation} from "/private/tmp/piping-source-recovery-20260924/projects/chirality-piping/apps/desktop/src/services/previewService.ts";
import {numericalResultStanding} from "/private/tmp/piping-source-recovery-20260924/projects/chirality-piping/apps/desktop/src/features/results/numericalResultQuality.ts";
import {sourceBlockStanding} from "/private/tmp/piping-source-recovery-20260924/projects/chirality-piping/apps/desktop/src/features/results/sourceBlockRecovery.ts";
import {buildCurrentSessionInputManifest} from "/private/tmp/piping-source-recovery-20260924/projects/chirality-piping/apps/desktop/src/services/inputManifestService.ts";
vi.mock('@tauri-apps/api/core',()=>({invoke:vi.fn()}));
afterEach(()=>{delete (window as any).__TAURI_INTERNALS__;vi.resetAllMocks();});
const request=JSON.parse(readFileSync("/private/tmp/piping-source-recovery-20260924/projects/chirality-piping/fixtures/product_preview/source_blocks/ui/n05-dense_scrutiny.request.json",'utf8'));
const raw=JSON.parse(readFileSync("/private/tmp/piping-source-recovery-20260924/projects/chirality-piping/fixtures/product_preview/source_blocks/ui/n05-dense_scrutiny.raw.json",'utf8'));
const observed:any[]=[];
for(const initialNegativeZero of [false,true])it(`actual serialized positive request; initial UI negative zero=${initialNegativeZero}`,async()=>{
 const model=structuredClone(request.model);if(initialNegativeZero)model.nodes[0].position.x=-0;
 Object.defineProperty(window,'__TAURI_INTERNALS__',{value:{},configurable:true});
 vi.mocked(invoke).mockResolvedValueOnce(structuredClone(raw));
 const source=await runPreviewMechanics(model,'dense_scrutiny');
 const args=vi.mocked(invoke).mock.calls[0][1] as any;
 const native=hasNativeMechanicsInvocation(source,model,'dense_scrutiny');
 const captured=retainedNativeMechanicsInvocation(source,model)!;
 const originalStanding=numericalResultStanding(source,model);
 const capturedStanding=sourceBlockStanding(source,captured.request.model);
 const manifest=await buildCurrentSessionInputManifest({model,solver:{solver_name:source.producer!.component_name,solver_version:source.producer!.component_version,solver_build_ref:'independent-review-existing-genuine-pair-via-mocked-IPC',solver_mode:'dense_scrutiny',settings:{}},active_rule_packs:[],external_assets:[]});
 observed.push({initialNegativeZero,callerStillNegativeZero:Object.is(model.nodes[0].position.x,-0),sentNegativeZero:Object.is(args.model.nodes[0].position.x,-0),actualRequestEqualsUnchangedProducerRequest:JSON.stringify({model:args.model,materials:[]})===JSON.stringify(request),native,originalStanding,capturedStanding,manifestModelNegativeZero:Object.is(manifest.manifest.model_basis.model_payload.nodes[0].position.x,-0)});
 writeFileSync("/private/tmp/piping-source-recovery-20260924/projects/chirality-piping/execution/_Coordination/AgentRuns/HELP-HUMAN-PIPING-20260918-UI-IMPLEMENTATION/instances/CONTINUATION_2026-09-24/SOLVER_MANAGER/ORDINARY_NUMERICAL_CUT/SOURCE_RECOVERY_IMPLEMENTATION_01/FRONTEND_READERS/INDEPENDENT_REVIEW/SIGNED_ZERO_OBSERVATIONS.json",JSON.stringify({scope:'Existing unchanged genuine producer request/raw pair through mocked actual frontend IPC. No producer solve. Only initial in-memory caller zero sign differs; recorded sent request equality verifies actual input unchanged.',observed},null,2)+'\n');
 expect(JSON.stringify({model:args.model,materials:[]})).toBe(JSON.stringify(request));
 expect(native).toBe(true);expect(capturedStanding.eligible).toBe(true);
 expect(originalStanding.eligible).toBe(true);
},30000);
