#!/usr/bin/env python3
"""Writes R2/PKG-04/PACKAGE_SUMMARY.md from the accepted ledgers (brief step 8). No judgment.
The hand-written cross-package section is included verbatim from _summary/CROSS_PACKAGE_OBSERVATIONS.md."""
import sys; sys.path.insert(0, __import__("os").path.dirname(__file__))
from common import *
L = ["# PACKAGE_SUMMARY — PKG-04 (RUN_D128 R2, wave 1)", "",
     "> Script-generated by `_scripts/package_summary.py` from the accepted ledgers (sealed forward ledgers, errata, reverse files, verifier shards). Agent dispositions are evidence, not rulings. The final section is hand-written and included verbatim.", ""]
L += ["## 1. Accepted ledgers", "", "| Unit | Rows | Base keys | SEE rows | Sealed SHA-256 | Ledger validator | Errata rows | Reverse validator |", "|---|---:|---:|---:|---|---|---:|---|"]
S = {}; A = {}; C = {}
for u in UNITS:
    s, a = applied(u); S[u], A[u] = s, a; C[u] = corrected(u)
    base = {re.sub(r"\.\d+$", "", r["ClaimKey"]) for r in s}
    see = sum("SEE:" in r["Notes"] for r in s)
    ne = len(rows(f(u, "_errata.csv"))) if os.path.exists(f(u, "_errata.csv")) else 0
    cap = os.path.join(P, "_reverse_inputs", u + "_capabilities.csv")
    rv = val("reverse", ["--capabilities", cap], f(u, "_reverse.csv")) if os.path.exists(f(u, "_reverse.csv")) else "n/a"
    L.append(f"| {u} | {len(s)} | {len(base)} | {see} | `{sha(f(u, '_claims.csv'))}` | {val('ledger', [], f(u, '_claims.csv'))} | {ne} | {rv} |")
allS = [r for u in UNITS for r in S[u]]; allA = [r for u in UNITS for r in A[u]]; allC = [r for u in UNITS for r in C[u]]
def census(title, key):
    cs = collections.Counter(key(r) for r in allS); ca = collections.Counter(key(r) for r in allA); cc = collections.Counter(key(r) for r in allC)
    per = {u: collections.Counter(key(r) for r in S[u]) for u in UNITS}
    out = [f"### {title}", "", "| Value | " + " | ".join(u[4:] for u in UNITS) + " | Sealed total | Errata-applied | Errata + CORRECTIONS applied |", "|---|" + "---:|" * (len(UNITS) + 3)]
    for k in sorted(set(cs) | set(ca) | set(cc), key=lambda k: (-cs.get(k, 0), k)):
        out.append(f"| {k} | " + " | ".join(str(per[u].get(k, 0)) for u in UNITS) + f" | {cs.get(k, 0)} | {ca.get(k, 0)}{' (Δ)' if cs.get(k, 0) != ca.get(k, 0) else ''} | {cc.get(k, 0)}{' (Δ)' if ca.get(k, 0) != cc.get(k, 0) else ''} |")
    return out + [""]
L += ["", "## 2. Censuses (per unit sealed; totals sealed, errata-applied, and errata + CORRECTIONS.csv applied)", "",
      "REACH = the set of `REACH=` tags in the row's ImplementationEvidence (`NO_CODE_TAG` = documentary or NONE_FOUND evidence).", ""]
L += census("ClaimType", lambda r: r["ClaimType"]) + census("Disposition", lambda r: r["Disposition"]) + census("CauseTag", lambda r: r["CauseTag"])
L += census("AuthorityTier", lambda r: r["AuthorityTier"]) + census("REACH", reach) + census("Confidence", lambda r: r["Confidence"])
L += census("PostReleaseBasis", lambda r: r["PostReleaseBasis"])
others = sorted({r["CauseTag"] for r in allS + allA if r["CauseTag"].startswith("OTHER:")})
L += [f"OTHER CauseTag tokens: {', '.join(others) if others else 'none'}.", ""]
c2 = collections.Counter(m for r in allS for m in re.findall(r"CAUSE2:([A-Z0-9_:]+)", r["Notes"]))
L += [f"CAUSE2 secondaries (sealed): " + (", ".join(f"{k} {v}" for k, v in c2.most_common()) or "none"), ""]
L += ["## 3. HumanDecisionNeeded", "", "Token tallies (a row with `a; b` counts under each token).", ""]
hs = collections.Counter(t for r in allS for t in hdn(r)); ha = collections.Counter(t for r in allA for t in hdn(r)); hc = collections.Counter(t for r in allC for t in hdn(r))
per = {u: collections.Counter(t for r in S[u] for t in hdn(r)) for u in UNITS}
L += ["| Token | " + " | ".join(u[4:] for u in UNITS) + " | Sealed | Errata-applied | + CORRECTIONS |", "|---|" + "---:|" * (len(UNITS) + 3)]
for k in sorted(set(hs) | set(ha) | set(hc), key=lambda k: (-hs.get(k, 0), k)):
    L.append(f"| {k} | " + " | ".join(str(per[u].get(k, 0)) for u in UNITS) + f" | {hs.get(k, 0)} | {ha.get(k, 0)} | {hc.get(k, 0)} |")
rows_needing = sum(1 for r in allS if hdn(r) != ["NO"])
L += ["", f"Rows with HumanDecisionNeeded ≠ NO (sealed): {rows_needing} of {len(allS)}. Named R4 questions: " + ", ".join(f"{q} {hs.get(q, 0)}" for q in ["R4-Q1", "R4-Q2", "R4-Q3", "R4"]) + ".", ""]
L += ["## 4. Errata applied", "", "| Unit | ClaimKey | Field | Sealed | Proposed |", "|---|---|---|---|---|"]
for u in UNITS:
    if os.path.exists(f(u, "_errata.csv")):
        for e in rows(f(u, "_errata.csv")):
            L.append(f"| {u} | {e['ClaimKey']} | {e['Field']} | {e['SealedValue'][:90].replace('|', '/')} | {e['ProposedValue'][:90].replace('|', '/')} |")
cp = os.path.join(P, "CORRECTIONS.csv")
L += ["", "### CORRECTIONS.csv (RUN_BASIS Addendum 3; non-verdict refutations, applied by R3 after errata)", "", "| ClaimKey | Field | Sealed | Corrected |", "|---|---|---|---|"]
for c in (rows(cp) if os.path.exists(cp) else []):
    L.append(f"| {c['ClaimKey']} | {c['Field']} | {c['SealedValue'][:90].replace('|', '/')} | {c['CorrectedValue'][:90].replace('|', '/')} |")
L += ["", "## 5. Verifier outcomes", "", "| Unit | Checked | CONFIRMED | REFUTED | CONTESTED | REFUTED % | Verdict-field REFUTED (distinct rows) | Verdict-field % | Refuted keys (verdict field) |", "|---|---:|---:|---:|---:|---:|---:|---:|---|"]
tot = collections.Counter()
for u in UNITS:
    p = os.path.join(P, "_verify", f"V-{u}.csv")
    if not os.path.exists(p): L.append(f"| {u} | pending | | | | | | | |"); continue
    vr = rows(p); c = collections.Counter(r["Verdict"].strip() for r in vr); tot.update(c); tot["n"] += len(vr)
    dl = sorted({r["ClaimKey"] for r in vr if r["Verdict"].strip() == "REFUTED" and r["Field"].strip() in ("Disposition", "Response")})
    nd = len({(r["ClaimKey"], r["CapabilityID"]) for r in vr})
    L.append(f"| {u} | {len(vr)} | {c['CONFIRMED']} | {c['REFUTED']} | {c['CONTESTED']} | {100 * c['REFUTED'] / len(vr):.1f} | {len(dl)} of {nd} | {100 * len(dl) / nd:.1f} | {', '.join(dl) or '—'} |")
L.append(f"| **Total** | {tot['n']} | {tot['CONFIRMED']} | {tot['REFUTED']} | {tot['CONTESTED']} | {100 * tot['REFUTED'] / max(tot['n'], 1):.1f} | | | |")
L += ["", "Rerun trigger (RUN_BASIS Addendum 3): structural failure, or > 10% of checked distinct rows REFUTED on a verdict field (Disposition, including errata that change it, or a reverse Response)."]
L += ["", "Full verifier record: `VERIFICATION.md`.", "", "## 6. Capability responses (reverse pass)", "",
      "| Unit | Areas | Capability rows | CLAIMED_BY | PARTIAL | NOT_MINE |", "|---|---|---:|---:|---:|---:|"]
claimed = collections.defaultdict(list)
for u in UNITS:
    if not os.path.exists(f(u, "_reverse.csv")): continue
    rv = rows(f(u, "_reverse.csv")); c = collections.Counter(r["Response"] for r in rv)
    am = open(os.path.join(P, "_reverse_inputs", u + "_AREAS.md")).read()
    areas = re.search(r"\*\*Union \(\d+\):\*\* (.*)", am).group(1)
    L.append(f"| {u} | {areas} | {len(rv)} | {c['CLAIMED_BY']} | {c['PARTIAL']} | {c['NOT_MINE']} |")
    for r in rv:
        if r["Response"] != "NOT_MINE": claimed[r["CapabilityID"]].append(f"{u}:{r['Response']}:{r['ClaimKey'].split('#')[1]}")
L += ["", "Capabilities claimed or partly covered by a PKG-04 deliverable:", ""]
L += [f"- `{k}`: " + "; ".join(v) for k, v in sorted(claimed.items())]
multi = {k: v for k, v in claimed.items() if len({x.split(':')[0] for x in v}) > 1}
L += ["", f"Capabilities answered CLAIMED_BY/PARTIAL by more than one PKG-04 deliverable: {len(multi)}" + (" — " + ", ".join(sorted(multi)) if multi else ""), ""]
hand = os.path.join(P, "_summary", "CROSS_PACKAGE_OBSERVATIONS.md")
L += ["## 7. Cross-package observations for R3 (hand-written; evidence, not rulings)", ""]
L += [open(hand).read().rstrip("\n")] if os.path.exists(hand) else ["(pending)"]
open(os.path.join(P, "PACKAGE_SUMMARY.md"), "w").write("\n".join(L) + "\n")
print(sha(os.path.join(P, "PACKAGE_SUMMARY.md")))
