#!/usr/bin/env python3
"""Writes R2/PKG-04/VERIFICATION.md (brief step 7) from validator runs, _verify/SELECTION.csv and the
V-*.csv shards. Patterns and the rerun record are included verbatim from _summary/VERIFICATION_PATTERNS.md."""
import sys; sys.path.insert(0, __import__("os").path.dirname(__file__))
from common import *
L = ["# VERIFICATION — PKG-04 (RUN_D128 R2, wave 1)", "",
     "> Script-generated by `_scripts/verification.py`. Verifiers are fresh evidence-only TASK shards (≤ 50 items each) that never edit ledgers; one shared grading key (`_verify/GRADING_KEY.md`).", "",
     f"- Selection: `_scripts/select_rechecks.py` → `_verify/SELECTION.csv` (`{sha(os.path.join(P, '_verify', 'SELECTION.csv'))}`); class a = LOW, self-flag, AUTHORITY_CONFLICT, UNKNOWN, REMAINING_WORK; n = 30% other non-ALIGNED; b = 15% ALIGNED; c = 20% CLAIMED_BY/PARTIAL; e = every errata row. Sampling by `sha256(key)` as in R0.",
     f"- Grading key SHA-256 `{sha(os.path.join(P, '_verify', 'GRADING_KEY.md'))}`; shard brief `_BRIEFS/VERIFIER_SHARD.md` `{sha(os.path.join(P, '_BRIEFS', 'VERIFIER_SHARD.md'))}`.", "",
     "## 1. Structural result (validator v2, run from `projects/chirality-app-dev`)", "", "| File | Mode | SHA-256 | Result |", "|---|---|---|---|"]
for u in UNITS:
    cap = os.path.join(P, "_reverse_inputs", u + "_capabilities.csv")
    for suf, mode, ex in [("_claims.csv", "ledger", []), ("_errata.csv", "errata", []), ("_reverse.csv", "reverse", ["--capabilities", cap])]:
        p = f(u, suf)
        if os.path.exists(p): L.append(f"| {u}/{u}{suf} | {mode} | `{sha(p)}` | {val(mode, ex, p)} |")
    L.append(f"| _reverse_inputs/{u}_capabilities.csv | capabilities | `{sha(cap)}` | {val('capabilities', [], cap)} |")
sel = rows(os.path.join(P, "_verify", "SELECTION.csv")); selc = collections.Counter((r["Unit"], r["Class"]) for r in sel)
L += ["", "## 2. Recheck table per deliverable", "", "| Unit | Class | Selected | Checked | CONFIRMED | REFUTED | CONTESTED |", "|---|---|---:|---:|---:|---:|---:|"]
allv = []; tot = collections.Counter()
for u in UNITS:
    p = os.path.join(P, "_verify", f"V-{u}.csv")
    vr = rows(p) if os.path.exists(p) else []; allv += vr
    by = collections.defaultdict(collections.Counter)
    for r in vr: by[r["Class"]][r["Verdict"].strip()] += 1
    for cl in ["a", "n", "b", "c", "e"]:
        if selc.get((u, cl)) or by.get(cl):
            c = by[cl]; n = sum(c.values()); tot.update(c); tot["n"] += n
            L.append(f"| {u} | {cl} | {selc.get((u, cl), 0)} | {n} | {c['CONFIRMED']} | {c['REFUTED']} | {c['CONTESTED']} |")
    c = collections.Counter(r["Verdict"].strip() for r in vr)
    if vr:
        vf = len({r["ClaimKey"] for r in vr if r["Verdict"].strip() == "REFUTED" and r["Field"].strip() in ("Disposition", "Response")}); nd = len({(r["ClaimKey"], r["CapabilityID"]) for r in vr})
        L.append(f"| **{u}** | all | {sum(v for k, v in selc.items() if k[0] == u)} | {len(vr)} | {c['CONFIRMED']} | {c['REFUTED']} ({100 * c['REFUTED'] / len(vr):.1f}%; verdict-field {vf} of {nd} distinct = {100 * vf / nd:.1f}%) | {c['CONTESTED']} |")
L.append(f"| **PKG-04** | all | {len(sel)} | {tot['n']} | {tot['CONFIRMED']} | {tot['REFUTED']} | {tot['CONTESTED']} |")
fc = collections.Counter((r["Verdict"].strip(), r["Field"].strip()) for r in allv if r["Verdict"].strip() != "CONFIRMED")
L += ["", "Field at issue (REFUTED + CONTESTED): " + "; ".join(f"{k[0]}/{k[1]} {v}" for k, v in sorted(fc.items(), key=lambda x: -x[1])), ""]
L += ["## 3. Every REFUTED and CONTESTED item", "", "| Unit | Class | ClaimKey | CapabilityID | Verdict | Field | RowValue | CorrectReading | Evidence | ConventionIssue |", "|---|---|---|---|---|---|---|---|---|---|"]
for r in allv:
    if r["Verdict"].strip() != "CONFIRMED":
        L.append("| " + " | ".join(r[c].replace("|", "/").replace("\n", " ") for c in ["Unit", "Class", "ClaimKey", "CapabilityID", "Verdict", "Field", "RowValue", "CorrectReading", "Evidence", "ConventionIssue"]) + " |")
L += ["", f"Shard CSVs: " + "; ".join(f"`V-{u}.csv` `{sha(os.path.join(P, '_verify', f'V-{u}.csv'))}`" for u in UNITS if os.path.exists(os.path.join(P, "_verify", f"V-{u}.csv"))), ""]
L += ["## 3a. Earlier attempts (superseded; RUN_BASIS Addendum 3 wave-1 transition)", "",
      "Files were moved to `_superseded/<unit>_runN/` before Addendum 3 (their `SHA256SUMS.txt` records every file). Their REFUTED and CONTESTED items are listed so R3 can compare attempts.", "",
      "| Attempt | Sealed SHA-256 | Checked | CONFIRMED | REFUTED | CONTESTED | Verdict-field REFUTED |", "|---|---|---:|---:|---:|---:|---|"]
sup = []
for d in sorted(glob.glob(os.path.join(P, "_superseded", "*"))):
    for vp in sorted(glob.glob(os.path.join(d, "V-*.csv"))):
        vr = rows(vp); c = collections.Counter(r["Verdict"].strip() for r in vr)
        cl = glob.glob(os.path.join(d, "*_claims.csv"))[0]
        vf = sorted({r["ClaimKey"] for r in vr if r["Verdict"].strip() == "REFUTED" and r["Field"].strip() in ("Disposition", "Response")})
        L.append(f"| {os.path.basename(d)} | `{sha(cl)}` | {len(vr)} | {c['CONFIRMED']} | {c['REFUTED']} | {c['CONTESTED']} | {', '.join(vf) or 'none'} |")
        sup += [(os.path.basename(d), r) for r in vr if r["Verdict"].strip() != "CONFIRMED"]
L += ["", "| Attempt | Class | ClaimKey | Verdict | Field | RowValue | CorrectReading | Evidence |", "|---|---|---|---|---|---|---|---|"]
for a, r in sup:
    L.append("| " + " | ".join([a] + [r[c].replace("|", "/").replace("\n", " ") for c in ["Class", "ClaimKey", "Verdict", "Field", "RowValue", "CorrectReading", "Evidence"]]) + " |")
L += [""]
hand = os.path.join(P, "_summary", "VERIFICATION_PATTERNS.md")
L += [open(hand).read().rstrip("\n")] if os.path.exists(hand) else ["## 4. Patterns", "", "(pending)"]
open(os.path.join(P, "VERIFICATION.md"), "w").write("\n".join(L) + "\n")
print(sha(os.path.join(P, "VERIFICATION.md")))
