import csv,json,re,hashlib,subprocess
from pathlib import Path
root=Path(subprocess.check_output(['git','rev-parse','--show-toplevel'],text=True).strip()); base='2be412ccea62bdc4bd96deb082c46d7a792076ea'
run='projects/pec/execution/_Reconciliation/DeliverableConcordance/PEC_REMAINING_CONCORDANCE_2026-09-05'; pkg=run+'/R1_R4_2026-09-05/PACKAGES/PKG-03'; out=root/pkg/'WORKERS/DEL-03-02'; did='DEL-03-02'
d='projects/pec/execution/PKG-03_Reconciliation_Parity/1_Working/DEL-03-02_Incremental_reconcile_on_Git_delta'; sow=d+'/ScopeOfWork.md'; up='projects/pec/execution/PKG-03_Reconciliation_Parity/1_Working/DEL-03-01_Full_rebuild_reconciler_one_command'; decomp='projects/pec/execution/_Decomposition/'
checks=[]; hashes={}
def read(p):
 b=(root/p).read_bytes(); hashes[p]=hashlib.sha256(b).hexdigest(); return b.decode()
def check(cmd):
 r=subprocess.run(cmd,cwd=root,text=True,capture_output=True,env=__import__('os').environ|{'PYTHONDONTWRITEBYTECODE':'1'}); checks.append(dict(command=' '.join(cmd),cwd='.',environment={'PYTHONDONTWRITEBYTECODE':'1'},exit_code=r.returncode,result=(r.stdout+r.stderr).strip())); return r
for target in ['ScopeOfWork.md','_STATUS.md']:
 r=check(['python3','projects/pec/execution/_Scripts/pec_reliance_hold.py','--register','projects/pec/execution/_Coordination/ACTIVE_RELIANCE_HOLDS.csv','--target',d.removeprefix('projects/pec/')+'/'+target,'--operation','candidate-validation']); assert r.returncode==0
sources=['AGENTS.md','projects/pec/AGENTS.md','agents/AGENT_RECONCILIATION.md','docs/DELIVERABLE_CONCORDANCE_METHOD.md','projects/pec/loop/LOOP_INIT.md','projects/pec/docs/PRD.md','projects/pec/execution/_Scripts/pec_reliance_hold.py','projects/pec/execution/_Coordination/ACTIVE_RELIANCE_HOLDS.csv','projects/pec/execution/_Coordination/_DECISIONS/_REGISTER.md','projects/pec/execution/_Coordination/_DECISIONS/D-PEC-81_remaining_concordance_activation_2026-09-05.md','projects/pec/execution/_Coordination/_DECISIONS/D-PEC-81_CALIBRATION_ACCEPTANCE_2026-09-05.md','projects/pec/execution/_Coordination/_DECISIONS/D-PEC-82_remaining_corpus_reporting_2026-09-05.md',run+'/CONVENTIONS.md',pkg+'/BRIEFS/DEL-03-02.md',pkg+'/PACKAGE_BASIS.md',pkg+'/SOURCE_MANIFEST.json',pkg+'/validate_worker.py',run+'/R1_R4_2026-09-05/COMMON/BRIEFS/PKG-03.md',run+'/R1_R4_2026-09-05/COMMON/BRIEF_CLARIFICATION_01.md',run+'/R1_R4_2026-09-05/COMMON/RUN_BASIS.md',run+'/R1_R4_2026-09-05/COMMON/SOURCE_MANIFEST.json',run+'/R1_R4_2026-09-05/COMMON/SCOPE_CENSUS.csv',run+'/R1_R4_2026-09-05/COMMON/AGENT0_GRAPH.md',decomp+'_LATEST.md',decomp+'SOFTWARE_DECOMP.md',decomp+'ScopeLedger.csv',decomp+'Deliverables.csv',up+'/ScopeOfWork.md',up+'/_STATUS.md',up+'/_REVIEW.md','projects/pec/execution/_Coordination/PEC_CURRENCY_REPAIR_CLOSEOUT_2026-08-09/HANDOFF_STATE.md','projects/pec/execution/_Coordination/PLAN_2026-07-25_project_setup_dag_gate.md']
sources += [str(p.relative_to(root)) for p in (root/d).rglob('*') if p.is_file()]
sources += [str(p.relative_to(root)) for p in (root/'projects/pec/v2').rglob('*') if p.is_file() and '__pycache__' not in str(p)]
sources += [str(p.relative_to(root)) for p in (root/'projects/pec/execution/_Coordination/_DECISIONS').glob('D-PEC-6[25]_*.md')]
sources += [str(p.relative_to(root)) for p in (root/'projects/pec/execution/PKG-01_Core_State_Store').glob('1_Working/DEL-01-01*/ScopeOfWork.md')]
for name in ['Brief.md','Amendment_Preview.md','Decision_Log.md','Handoff_State.md']: sources.append('projects/pec/execution/_ScopeChange/SCA-002_2026-07-25_1042/'+name)
sources.append('projects/pec/execution/_ScopeChange/SCA-004_2026-08-02_2325/Handoff_State.md')
for p in sorted(set(sources)):
 if (root/p).is_file(): read(p)
# Discover exact entity-model path using tracked PEC corpus only.
for p in (root/'projects/pec/execution').glob('PKG-01*/1_Working/DEL-01-01*/ScopeOfWork.md'): read(str(p.relative_to(root)))
text=read(sow); matches=list(re.finditer(r'^- \*\*((?:REQ|AC|VER|OUT|CLM|AX|TBD|CON)-\d{3})\*\* — (.*)$',text,re.M)); claims={}
for i,m in enumerate(matches):
 end=matches[i+1].start() if i+1<len(matches) else text.index('**Quotation record.**')
 claims[m[1]]={'quote':m[2],'line':text[:m.start()].count('\n')+1,'block':text[m.start():end]}
assert len(claims)==81,len(claims)
# Bounded source content inventory, not an implementation absence proof.
v2files=sorted(p for p in hashes if p.startswith('projects/pec/v2/')); hits=[]
for p in v2files:
 for n,line in enumerate((root/p).read_text().splitlines(),1):
  if re.search(r'incremental|reconcil|baseline|examined',line,re.I): hits.append(f'{p}:{n}: {line}')
(out/'SOURCE_OBSERVATIONS.md').write_text('# Source observations\n\nCurrent v2 files inspected: '+str(len(v2files))+'. Current source exposes loop registry/configuration, API schema and posture enforcement. No identified executing incremental engine or DEL-03-02 claim-specific test evidence in this bounded corpus. This is UNKNOWN, not an implementation-absence proof. Frozen PEC is not carried as v2 implementation.\n\n'+ '\n'.join(hits)+'\n\nLocal run records are SOW authoring and D65 dependency-evidence repair, not product runs. No local REVIEW file is present. Status INITIALIZED and no Remaining section do not discharge future production claims.\n\nDEP-03-02-003 is ACTIVE/PREREQUISITE/PENDING, Target DEL-03-01. It blocks only proposed items naming DEL-03-01 after lawful owner application. Upstream contract availability never flips PENDING.\n\nD65 repaired EvidenceFile=docs/PRD.md, SourceRef=PRD.md §9.2 requirement PEC-RCN-003, EvidenceQuote=the full PEC-RCN-003 sentence. CLM-007 still describes prior empty evidence. CLM-015 and AX-012 reproduce OPEN while live status is INITIALIZED; historical authoring remains preserved. Purpose section describes revision1.2 and superseded local pointer wording while _REFERENCES and _CONTEXT now show rev1.4. Scope item SOW-018 and OBJ-002 remain unchanged. This proposed documentary alignment does not reopen completed ordinary SCA004 currency.\n\nCON-001 package-wide shared baseline ownership remains an explicit scope question; local REQ-004 already obliges this engine to establish its baseline. CON-003 carries upstream full-coverage ambiguity; no new upstream assignment. DEL-04-02 and DEL-03-03 receive only coordination concern through the manager. No blanket TM023 gate.\n')
C='ClaimID,DeliverableID,ClaimClass,NormativeSource,ScopeItemIDs,DeclaredSource,CurrentState,ImplementationEvidence,VerificationEvidence,ValidationOrProvenanceEvidence,LifecycleEvidence,ExistingRemaining,Disposition,ProposedResidualID,ProposedResidualText,Depends,ExactGate,AuthorityNeeded,Selectability,SourceCommit,SourceHashes,EvidenceReferences,Notes'.split(','); R='ResidualID,DeliverableID,ClaimIDs,ProposedText,Depends,ExactGate,ClosureEvidence,AuthorityNeeded,Selectability,Notes'.split(',')
select='NON_SELECTABLE_PENDING_OWNER_APPLICATION'; gate='(gated: exact owner-approved Remaining application and a separate owner-ruled PEC packet naming production paths, acts, verification, rollback and applicable fence opening; source and reliance gates preserved)'; docgate='(gated: exact owner-approved Remaining application and separately authorized bounded SOW documentary correction; no lifecycle or source change)'; owner='PEC owner; D82 reporting grant excludes application and repair'
res=[]; linked={}
def residual(ids,txt,depends='NONE',g=gate,closure='Source-bound evidence addressing every linked claim and exact method; owner acceptance where named',note='Evidence-gap proposal; not an automatic implementation task'):
 rid=f'{did}-REM-{len(res)+1:03}'; ids=[did+'::'+i for i in ids]; res.append(dict(zip(R,[rid,did,';'.join(ids),txt,depends,g,closure,owner,select,note])))
 for i in ids: linked[i]=res[-1]
labels=['delta-selected changed-source derivation','read-only Git state preservation','content-minimal delta reduction','completed-run baseline and no-baseline fallback','incremental/full-rebuild equivalence and fallback','upstream-only rebuild/feed/loop boundary','upstream-only write set','selected-feed limitations and baseline holdback','determinism and empty-delta idempotence','file-derived provenance and tier separation','adjacent-deliverable scope exclusion','upstream entity-type boundary','zero runtime dependencies and external egress','contract-derived executing automated tests']
for n,label in enumerate(labels,1):
 ids=[f'REQ-{n:03}',f'AC-{n:03}',f'VER-{n:03}']
 if n==1:ids+=['OUT-001']
 if n==14:ids+=['OUT-002']
 residual(ids,f'Locate and bind current DEL-03-02 implementation and claim-specific verification for {label}; if unavailable, route the established evidence gap for an exact owner-scoped production packet. Preserve the contract scope and finite-method limits.',depends='DEL-03-01',closure=f'Current implementation locus and executing VER-{n:03} evidence meeting REQ-{n:03}/AC-{n:03}, with exact source hashes and method limits')
residual(['AC-015'],'Obtain source-bound REVIEW traceability evidence for AC-015 under its declared gate; do not re-ratify the register-direct SOW-018 to OBJ-002 mapping.',g='(gated: exact owner-approved Remaining application and separately declared REVIEW basis; human acceptance remains owner-held)',closure='REVIEW record for current exact contract bytes confirming AC-015 traceability and scope containment',note='Human-review evidence gap; upstream exact acceptance is not acceptance of this contract')
residual(['CLM-007','CLM-015','AX-012','BASIS-001'],'Prepare bounded documentary alignment of CLM-007 dependency evidence, CLM-015/AX-012 lifecycle citations and purpose-section current-pointer prose to live accepted registers; retain dated authoring and D65/SCA history.',g=docgate,closure='Exact owner-approved SOW postimage and multiset/semantic backcheck; unchanged status/dependency registers and product requirements',note='Documentary candidate; no lifecycle reversal and no reopening ordinary SCA004 currency')
residual(['CON-001'],'Route the explicitly recorded shared reconcile-side baseline ownership question for owner scope disposition; preserve local REQ-004 baseline obligation and make no upstream assignment.',g='(gated: owner scope disposition and separately ruled SCOPE_CHANGE if shared package obligation is selected; exact Remaining application required)',closure='Owner decision preserving or amending baseline ownership and exact affected contracts',note='Held authority question, not automatic Remaining; may affect DEL-03-01/DEL-03-03/DEL-04-02')
residual(['CON-003'],'Carry the upstream full-rebuild coverage-limitation interpretation question to its owner while preserving DEL-03-02 REQ-008 baseline prohibition.',g='(gated: exact upstream owner disposition of full-rebuild coverage meaning and exact Remaining application; no scope transfer)',closure='Source-bound owner interpretation of upstream completeness and explicit local impact assessment',note='Held upstream interpretation; no production assignment to sibling')
rows=[]
for local,cl in list(claims.items())+[('BASIS-001',{'quote':'Purpose section current basis and reference-pointer assertions','line':20,'block':''})]:
 cid=did+'::'+local; prefix=local.split('-')[0]; rr=linked.get(cid); behavioral=prefix in ['REQ','AC','VER','OUT']; disp='UNKNOWN' if behavioral or local in ['CON-001','CON-003'] else 'ALIGNED'; kind={'REQ':'PRODUCT_REQUIREMENT','AC':'FINITE_ACCEPTANCE_CRITERION','VER':'FINITE_TEST_METHOD','OUT':'PRODUCT_OUTPUT','CLM':'DOCUMENTARY_ALIGNMENT','AX':'DOCUMENTARY_ALIGNMENT','TBD':'DOCUMENTARY_ALIGNMENT','CON':'DOCUMENTARY_ALIGNMENT','BASIS':'DOCUMENTARY_ALIGNMENT'}[prefix]
 if local=='AC-015':kind='HUMAN_ACCEPTANCE'
 if local in ['CLM-015','AX-012']:kind='LIFECYCLE'
 if local in ['CLM-007','CLM-015','AX-012','BASIS-001']:disp='STALE_INPUT'
 if local in ['CON-001','CON-003']:kind='AUTHORITY_QUESTION'
 note='Documentary ALIGNED only: verifies contract identity/boundary or truthful unresolved design state; no implemented-behavior or acceptance claim.'
 if behavioral:note='Current implementation/execution evidence not established in bounded v2 corpus. UNKNOWN is not absence proof; future contract framing is preserved. Finite method is declared, not executed, and cannot establish an all-input guarantee.'
 if prefix=='TBD':note+=' Production choices/assignment stay explicit; no invented separate obligation or owner assignment.'
 if local in ['CLM-015','AX-012']:note='OPEN was accurate at authoring; the live contract now repeats it against INITIALIZED. Historical run is preserved; proposal corrects citation only, never lifecycle.'
 if rr:note+=' '+rr['Notes']
 srcrefs=[sow,d+'/_STATUS.md',d+'/Dependencies.csv',decomp+'ScopeLedger.csv',decomp+'Deliverables.csv',up+'/ScopeOfWork.md']
 row=dict(zip(C,[cid,did,kind,sow+f':{cl["line"]} ({local}); '+decomp+'ScopeLedger.csv SOW-018','SOW-018',cl['quote'],'INITIALIZED; no ## Remaining section; future production contract','Bounded current v2 inventory in SOURCE_OBSERVATIONS.md; no claim-specific implementation established' if behavioral else 'Not used to establish documentary truth','No local executing '+(local if prefix=='VER' else 'claim-specific')+' test evidence identified' if behavioral else 'Source/register comparison; no product test pass asserted','Local INIT and D65 run records are documentary evidence; current rev1.4 ledger preserves SOW-018/OBJ-002',d+'/_STATUS.md: INITIALIZED; upstream acceptance excludes lifecycle/product acceptance','MISSING_SECTION; no selectable scope',disp,rr['ResidualID'] if rr else 'NONE',rr['ProposedText'] if rr else '',rr['Depends'] if rr else 'NONE',rr['ExactGate'] if rr else '(gated: no application or production authorized by this documentary assessment)',owner,select,base,json.dumps({p:hashes[p] for p in srcrefs},sort_keys=True),pkg+'/WORKERS/DEL-03-02/SOURCE_OBSERVATIONS.md; '+sow+f':{cl["line"]}',note]));rows.append(row)
for filename,data,fields in [('CLAIMS.csv',rows,C),('RESIDUALS.csv',res,R)]:
 with (out/filename).open('w',newline='') as f:
  wr=csv.DictWriter(f,fieldnames=fields,lineterminator='\n');wr.writeheader();wr.writerows(data)
# Compare immutable base bytes for every tracked read source; run-local brief/manifest explicitly derivative.
base_mismatch=[]; derivative=[]
for p,h in hashes.items():
 r=subprocess.run(['git','show',base+':'+p],cwd=root,capture_output=True)
 if r.returncode: derivative.append(p)
 elif hashlib.sha256(r.stdout).hexdigest()!=h:base_mismatch.append(p)
assert not base_mismatch,base_mismatch
checks.append(dict(command='git show BASE:SOURCE for every read source',cwd='.',environment={},exit_code=0,result={'base_mismatches':base_mismatch,'run_local_derivatives':derivative}))
assert all(hashlib.sha256((root/p).read_bytes()).hexdigest()==h for p,h in hashes.items())
manifest=dict(source_commit=base,hashes=hashes,historical_sources=[],checks=checks,source_unchanged=True)
(out/'READ_MANIFEST.json').write_text(json.dumps(manifest,indent=2)+'\n')
from collections import Counter
counts=Counter(x['Disposition'] for x in rows); classes=Counter(k.split('-')[0] for k in claims)
(out/'COVERAGE.md').write_text('# DEL-03-02 coverage\n\n82 rows: all 81 locally defined SOW IDs plus explicit fallback BASIS-001 at ScopeOfWork.md purpose/current-basis paragraph (line20). All 14 REQ, 15 AC and 14 VER IDs included exactly once. Additional local IDs: '+json.dumps(dict(classes))+'; all covered, no material local definition omitted. Quoted upstream IDs are not local definitions; matrix repeats are backlinks, not additional claims.\n\nScope: SOW-018 / OBJ-002; canonical ScopeOfWork.md hash '+hashes[sow]+'. BASIS-001 quoted block hash '+hashlib.sha256(text[text.index('The accepted basis is'):text.index('**Objective warrant.')].encode()).hexdigest()+'.\n\nDisposition counts '+json.dumps(dict(counts))+'. 18 linked proposals; summary ASSESSED_UNKNOWN; warranted NONE prohibited. Fourteen product/method evidence-gap proposals, one human-review evidence proposal, one documentary candidate and two held scope/interpretation routes. No tests were rerun because no current executing DEL-03-02 suite was established. Adjacent enforcement is not local behavioral proof.\n\nUpstream contract and source hashes are current base evidence; prior authoring records are read as dated provenance. August9 ordinary currency closure survives. Native role instruction-asserted, not mechanically enforced; no delegation; only assigned worker subtree written.\n')
(out/'CLAIM_SOURCE_EXCERPTS.md').write_text('# Local claim excerpts\n\n'+''.join(f'## {did}::{k}\n\n{sow}:{v["line"]}\n\n{v["quote"]}\n\n' for k,v in claims.items()))
print(json.dumps({'claims':len(rows),'residuals':len(res),'dispositions':dict(counts),'hashes':len(hashes)}))
