from pathlib import Path
import os,subprocess,hashlib,json,sys
r=Path('projects/chirality-piping/execution/_Coordination/AgentRuns/HELP-HUMAN-PIPING-20260918-UI-IMPLEMENTATION/instances/CONTINUATION_2026-09-24/NUMERICAL_INTEGRITY_T3/RESUME_2026-09-30');rr=r/'REVIEW_RV61/product_refusal_01/_run_records';src=r/'I46/product_refusal_01/_run_records/original';E=dict(os.environ,GIT_OPTIONAL_LOCKS='0');rev='6ba653451f9fd27cdb852b7974753a3921f1c483';records=[]
def record(path,scope):
 b=Path(path).read_bytes();records.append({'origin':str(path),'sha256':hashlib.sha256(b).hexdigest(),'bytes':len(b),'read_scope':scope})
for path,scope in [('AGENTS.md','full'),('agents/AGENT_TASK.md','full'),('projects/chirality-piping/AGENTS.md','full'),('.agents/skills/software-defect-diagnosis/SKILL.md','full'),(r/'BRIEFS/RV61_PRODUCT_REFUSAL_REVIEW.md','full'),(r/'I46/product_refusal_01/RETURN.md','full'),(r/'I46/product_refusal_01/RELOCATION.json','full'),(r/'I33/f2a_source_action_bridge_01/RETURN.md','selected source and sections1/5 refusal/availability warrants'),(r/'I33/f2a_source_action_bridge_01/INTERFACE_AND_COST.md','selected source/custody/refusal context'),(r/'I35/f2a_certificate_integration_02/NEXT_CODE_AND_WITNESS.md','selected integration and section3 W0/W1/refusal/availability'),(r/'I35/f2a_certificate_integration_02/INTEGRATION.md','selected source/represented, scale, final predicate and refusal sections'),(r/'I36/f2a_ordinary_coefficients_02/RETURN.md','selected ordinary coefficient and represented/source sections'),(r/'ROOT_CURRENT.md','full')]:record(path,scope)
base=r.parent/'DESIGN_NUMERICS'
record(base/'DESIGN.md','4.1.6.1 scales and failure, lines456-518 plus heading discovery')
record(base/'REV_5A3_CANDIDATE/D1_REV_5A3_SSTAR_RESOLUTION_R7.md','5.3 precision512 floor;6.3 G5a;focused heading/term discovery')
for path in sorted(src.iterdir()):record(path,'fully parsed/checksummed; analyze.py and RETURN inspected; records independently decoded; large exact fractions consumed arithmetically')
source_specs={'projects/chirality-piping/core/solver/frame_kernel/src/structural/retained/adaptive.rs':[[2981,3010],[3237,3271],[3308,3336]],'projects/chirality-piping/core/solver/frame_kernel/src/structural/retained/source.rs':[[775,888]],'projects/chirality-piping/core/product_physics/src/lib.rs':[[3984,3987],[4478,4509],[9436,9510],[11203,11232]],'projects/chirality-piping/core/product_physics/src/preview_physics.rs':[[480,521]]}
for path,ranges in source_specs.items():
 b=subprocess.check_output(['git','show',rev+':'+path],env=E);records.append({'origin':path,'git_revision':rev,'sha256':hashlib.sha256(b).hexdigest(),'bytes':len(b),'read_ranges':ranges})
sealed='330dc2e405de87f451189616d2d5b73aaac86de7'
for path in sorted(src.iterdir()):
 b=subprocess.check_output(['git','show',sealed+':'+str(path)],env=E);assert b==path.read_bytes(),path.name
brief=subprocess.check_output(['git','show','8e0971413396f5ea376364fd53432ee9695ee0d0:'+str(r/'BRIEFS/RV61_PRODUCT_REFUSAL_REVIEW.md')],env=E);assert brief==(r/'BRIEFS/RV61_PRODUCT_REFUSAL_REVIEW.md').read_bytes()
info={'task':'/root/rv61_product_refusal','role':'TASK Type2','parent':'ROOT HELP_HUMAN /root','mechanism':'delegated-harness-native','receipt_utc':'2026-10-03 03:34:38 UTC','checkpoint_due':'2026-10-03 03:44:38 UTC','cutoff':'2026-10-03 03:54:38 UTC','final_due':'2026-10-03 03:59:38 UTC','early_checkpoint':'2026-10-03 03:39:43 UTC','source_pin':rev,'subject_pin':sealed,'brief_pin':'8e0971413396f5ea376364fd53432ee9695ee0d0','write_scope':str(r/'REVIEW_RV61/product_refusal_01'),'cwd':str(Path.cwd()),'python':sys.version,'all_Git_reads_GIT_OPTIONAL_LOCKS':'0','original_10_files_match_sealed_commit':True,'brief_matches_dispatch_pin':True,'read_correction':'Initial git-show lookup under pre-relocation paths failed; bounded ls-tree confirmed subject pin already includes _run_records/original; corrected all ten comparisons passed. No mutation resulted.','limits':['No descendants','No maintained source, Git/index, API, tooling changes','No compiler, solver/model, native producer or network execution','Only standard-library exact algebra and owned evidence writes','No implementation or public availability acceptance'],'origins':records}
(rr/'ORIGINS.json').write_text(json.dumps(info,indent=2)+'\n')
print('Origins recorded; all10 relocated original files equal sealed330dc2e bytes and brief equals pin8e09714.')
