//! K-D5 tests (T3 D1 revision 5a.2 §4.3.1 and the §6 K-D5 row) for the
//! adapter's linear entry `solve_with_formation_check`, both solve modes.
//!
//! Every behavioural assertion first shows that the two paths differ where
//! the assertion depends on it (RV1's S1 lesson): the ordinary `solve`
//! publishes Passed, and the actual error of its own u against the exact
//! intended solution (`kd5_models.rs`, generated by the run record
//! `kd5_models.py`) is above, or below, half the criterion.
use super::*;
use crate::{
    solve_active_set_frame_with_mode_and_springs, ConvergenceControl, ConvergencePolicyStatus,
    CurvedBendStiffnessElement, NonlinearFrameSolveInput,
};
use open_pipe_stress_frame_kernel::structural::{FormationCheckReason, SolveQuality};
use open_pipe_stress_frame_kernel::{FrameDof, FrameNode, FrameSection};
use open_pipe_stress_nonlinear_supports::{
    ActiveSetState, GapDirection, NonlinearSupport, SupportStateRecord,
};

#[path = "kd5_models.rs"]
mod kd5_models;
use kd5_models::*;

pub(super) struct SectionData {
    pub(super) e: f64,
    pub(super) g: f64,
    pub(super) a: f64,
    pub(super) i: f64,
    pub(super) j: f64,
}
pub(super) struct MemberData {
    pub(super) i: usize,
    pub(super) j: usize,
    pub(super) y_reference: [f64; 3],
    /// (the product's binary64 arc centre, flexibility factor) for a realized bend.
    pub(super) bend: Option<([f64; 3], f64)>,
}
pub(super) struct ModelData {
    pub(super) name: &'static str,
    pub(super) section: SectionData,
    pub(super) nodes: &'static [[f64; 3]],
    pub(super) members: &'static [MemberData],
    pub(super) rigid: &'static [usize],
    pub(super) springs: &'static [(usize, f64)],
    pub(super) loads: &'static [(usize, f64)],
    /// Exact intended free displacements (empty where not computed).
    pub(super) u_int: &'static [(usize, f64)],
}

const MODES: [LinearSolveMode; 2] = [
    LinearSolveMode::DenseScrutiny,
    LinearSolveMode::SparseInteractive,
];

struct Built {
    frames: Vec<FrameElement>,
    users: Vec<UserStiffnessElement>,
    macros: Vec<CurvedBendMacroElement>,
    slots: Vec<CurvedBendStiffnessElement>,
    springs: Vec<(usize, f64)>,
    node_count: usize,
    k: Vec<Vec<f64>>,
    f: Vec<f64>,
    free: Vec<usize>,
    prescribed: Vec<(usize, f64)>,
}

impl Built {
    fn from_model(m: &ModelData) -> Self {
        let node_count = m.nodes.len();
        let n = 6 * node_count;
        let node = |i: usize| FrameNode::new(i, m.nodes[i]).unwrap();
        let s = &m.section;
        let section = FrameSection::new(s.e, s.g, s.a, s.i, s.i, s.j).unwrap();
        let mut built = Built {
            frames: Vec::new(),
            users: Vec::new(),
            macros: Vec::new(),
            slots: Vec::new(),
            springs: m.springs.to_vec(),
            node_count,
            k: vec![vec![0.0; n]; n],
            f: vec![0.0; n],
            free: Vec::new(),
            prescribed: Vec::new(),
        };
        for (index, member) in m.members.iter().enumerate() {
            let matrix = match member.bend {
                None => {
                    let e = FrameElement::new(
                        node(member.i),
                        node(member.j),
                        section,
                        member.y_reference,
                    )
                    .unwrap();
                    built.frames.push(e);
                    e.global_stiffness().unwrap()
                }
                Some((center, factor)) => {
                    let e = CurvedBendMacroElement::new(
                        node(member.i),
                        node(member.j),
                        center,
                        s.e,
                        s.g,
                        s.a,
                        s.i,
                        s.j,
                        factor,
                        factor,
                    )
                    .unwrap();
                    let slot =
                        CurvedBendStiffnessElement::from_macro_element(format!("bend-{index}"), &e)
                            .unwrap();
                    built.macros.push(e);
                    let matrix = slot.global_stiffness;
                    built.slots.push(slot);
                    matrix
                }
            };
            built.scatter(member.i, member.j, &matrix);
        }
        for &(dof, value) in m.springs {
            built.k[dof][dof] += value;
        }
        for &(dof, value) in m.loads {
            built.f[dof] += value;
        }
        built.set_boundary(m.rigid);
        built
    }
    fn scatter(&mut self, a: usize, b: usize, matrix: &Matrix12) {
        let map = element_dof_map(a, b);
        for r in 0..12 {
            for c in 0..12 {
                self.k[map[r]][map[c]] += matrix[r][c];
            }
        }
    }
    fn set_boundary(&mut self, rigid: &[usize]) {
        let n = self.f.len();
        self.prescribed = rigid.iter().map(|&d| (d, 0.0)).collect();
        self.free = (0..n).filter(|d| !rigid.contains(d)).collect();
    }
    fn assembly(&self) -> AssemblyEvidence {
        AssemblyEvidence::new(
            self.node_count,
            &self.frames,
            &self.users,
            &self.slots,
            &self.springs,
        )
        .unwrap()
    }
    fn plain(&self, mode: LinearSolveMode) -> StructuralSolution {
        self.assembly()
            .solve(&self.k, &self.f, &self.free, &self.prescribed, mode)
            .unwrap()
    }
    fn checked_with(
        &self,
        mode: LinearSolveMode,
        macros: &[CurvedBendMacroElement],
    ) -> StructuralSolution {
        self.assembly()
            .solve_with_formation_check(
                &self.k,
                &self.f,
                &self.free,
                &self.prescribed,
                mode,
                macros,
                true,
            )
            .unwrap()
    }
    fn checked(&self, mode: LinearSolveMode) -> StructuralSolution {
        self.checked_with(mode, &self.macros)
    }
}

/// max over free rows of |u − u_int| / (1e-9·max(|u_int|, S*_kind(u_int))),
/// one body, S* per D1 §4.1.6.1 items 4–6 (the design's actual-error measure).
fn actual_ratio(m: &ModelData, u: &[f64]) -> f64 {
    assert!(!m.u_int.is_empty(), "{}: no reference", m.name);
    let (mut st, mut sr) = (0.0_f64, 0.0_f64);
    for &(d, v) in m.u_int {
        if d % 6 < 3 {
            st = st.max(v.abs());
        } else {
            sr = sr.max(v.abs());
        }
    }
    let mut d = [0.0; 3];
    for (k, dk) in d.iter_mut().enumerate() {
        let hi = m.nodes.iter().map(|p| p[k]).fold(f64::MIN, f64::max);
        let lo = m.nodes.iter().map(|p| p[k]).fold(f64::MAX, f64::min);
        *dk = hi - lo;
    }
    let l_b = ((d[0] * d[0] + d[1] * d[1]) + d[2] * d[2]).sqrt();
    let (tr, ro) = (st.max(l_b * sr), sr.max(st / l_b));
    m.u_int
        .iter()
        .map(|&(dof, v)| {
            let scale = v.abs().max(if dof % 6 < 3 { tr } else { ro });
            (u[dof] - v).abs() / (1e-9 * scale)
        })
        .fold(0.0, f64::max)
}

fn bits(u: &[f64]) -> Vec<u64> {
    u.iter().map(|v| v.to_bits()).collect()
}

/// A demoted solution differs from the ordinary one only in `quality` and
/// the separate record; values and every other report field are identical.
fn assert_demoted_only_in_quality(plain: &StructuralSolution, checked: &StructuralSolution) {
    assert_eq!(plain.report.quality, SolveQuality::Passed);
    assert_eq!(checked.report.quality, SolveQuality::Sensitive);
    assert_eq!(bits(&plain.displacements), bits(&checked.displacements));
    let mut report = checked.report.clone();
    report.quality = SolveQuality::Passed;
    assert_eq!(format!("{:?}", report), format!("{:?}", plain.report));
    assert!(checked.formation_check.is_some());
}

/// Not demoted: the solution is the ordinary one, byte for byte (D5C-3).
fn assert_unchanged(plain: &StructuralSolution, checked: &StructuralSolution) {
    assert_eq!(checked.formation_check, None);
    assert_eq!(bits(&plain.displacements), bits(&checked.displacements));
    assert_eq!(
        format!("{:?}", plain.report),
        format!("{:?}", checked.report)
    );
}

/// Records the measured numbers (visible with `--nocapture`, kept in the run records).
fn record(name: &str, mode: LinearSolveMode, actual: Option<f64>, checked: &StructuralSolution) {
    let trigger = checked
        .formation_check
        .as_ref()
        .map(|r| (r.ratio, r.global_dof));
    eprintln!(
        "kd5 {name} {mode:?} actual={actual:?} demoted={} trigger={trigger:?}",
        checked.formation_check.is_some()
    );
}

fn estimate(checked: &StructuralSolution) -> f64 {
    let record = checked.formation_check.as_ref().expect("demoted");
    assert_eq!(record.reason, FormationCheckReason::Estimate);
    record.ratio
}

fn unavailable_detail(checked: &StructuralSolution) -> String {
    match &checked.formation_check.as_ref().expect("demoted").reason {
        FormationCheckReason::FormationCheckUnavailable { detail } => detail.clone(),
        other => panic!("expected formation_check_unavailable, got {other:?}"),
    }
}

#[test]
fn kd5_required_true_positive_skew_cantilever_122_demotes_in_both_modes() {
    let built = Built::from_model(&F122);
    for mode in MODES {
        let plain = built.plain(mode);
        let actual = actual_ratio(&F122, &plain.displacements);
        // Precondition: main publishes Passed with a breach of the criterion.
        assert_eq!(plain.report.quality, SolveQuality::Passed, "{mode:?}");
        assert!(actual > 1.0, "{mode:?}: actual {actual}");
        let checked = built.checked(mode);
        record("F122", mode, Some(actual), &checked);
        assert_demoted_only_in_quality(&plain, &checked);
        // EF tracks the actual error (the quoted EF is half the trigger value).
        let ef = estimate(&checked) / 2.0;
        assert!(
            (ef / actual - 1.0).abs() < 1e-3,
            "{mode:?}: EF {ef} actual {actual}"
        );
    }
}

#[test]
fn kd5_skew_345_and_invented_m11_do_not_demote() {
    for model in [&F345, &M11] {
        let built = Built::from_model(model);
        for mode in MODES {
            let plain = built.plain(mode);
            assert_eq!(
                plain.report.quality,
                SolveQuality::Passed,
                "{} {mode:?}",
                model.name
            );
            let actual =
                (!model.u_int.is_empty()).then(|| actual_ratio(model, &plain.displacements));
            assert!(actual.is_none_or(|a| a < 0.5));
            let checked = built.checked(mode);
            record(model.name, mode, actual, &checked);
            assert_unchanged(&plain, &checked);
        }
    }
}

#[test]
fn kd5_d5c1_controls_demote_exactly_where_the_actual_error_exceeds_half_the_criterion() {
    // V1's probe D (solve error only: the spring sum is exact), probe C (a soft
    // spring partly absorbed by G*J/L) and an axis-aligned bending-soft member.
    let mut demoted = Vec::new();
    for model in [&PROBE_D, &PROBE_C, &BENDING_SOFT] {
        let built = Built::from_model(model);
        for mode in MODES {
            let plain = built.plain(mode);
            assert_eq!(
                plain.report.quality,
                SolveQuality::Passed,
                "{} {mode:?}",
                model.name
            );
            let actual = actual_ratio(model, &plain.displacements);
            let checked = built.checked(mode);
            record(model.name, mode, Some(actual), &checked);
            assert!(
                (actual - 0.5).abs() > 0.05,
                "{} {mode:?}: control too close to the boundary ({actual})",
                model.name
            );
            if actual > 0.5 {
                assert_demoted_only_in_quality(&plain, &checked);
                let ef = estimate(&checked) / 2.0;
                assert!(
                    (ef / actual - 1.0).abs() < 1e-3,
                    "{} {mode:?}: EF {ef} actual {actual}",
                    model.name
                );
                demoted.push(model.name);
            } else {
                assert_unchanged(&plain, &checked);
            }
        }
    }
    // Each class demotes in at least one mode (the controls are not vacuous).
    for name in ["PROBE_D", "PROBE_C", "BENDING_SOFT"] {
        assert!(demoted.contains(&name), "{name} never demoted: {demoted:?}");
    }
}

#[test]
fn kd5_realistic_elbows_e1_and_e6_do_not_demote() {
    for model in [&E1, &E6] {
        let built = Built::from_model(model);
        assert!(!built.macros.is_empty());
        for mode in MODES {
            let plain = built.plain(mode);
            assert_eq!(
                plain.report.quality,
                SolveQuality::Passed,
                "{} {mode:?}",
                model.name
            );
            let actual = actual_ratio(model, &plain.displacements);
            assert!(actual < 0.5);
            let checked = built.checked(mode);
            record(model.name, mode, Some(actual), &checked);
            assert_unchanged(&plain, &checked);
        }
    }
}

#[test]
fn kd5_skew_plane_elbow_cantilever_at_kx_8_5_demotes_in_both_modes() {
    let built = Built::from_model(&CSKEW_8_5);
    for mode in MODES {
        let plain = built.plain(mode);
        let actual = actual_ratio(&CSKEW_8_5, &plain.displacements);
        assert_eq!(plain.report.quality, SolveQuality::Passed, "{mode:?}");
        assert!(actual > 1.0, "{mode:?}: actual {actual}");
        let checked = built.checked(mode);
        record("CSKEW_8_5", mode, Some(actual), &checked);
        assert_demoted_only_in_quality(&plain, &checked);
        let ef = estimate(&checked) / 2.0;
        assert!(
            (ef / actual - 1.0).abs() < 1e-3,
            "{mode:?}: EF {ef} actual {actual}"
        );
    }
}

#[test]
fn kd5_curved_intended_element_uses_the_actual_chord() {
    // The k_X = 30 skew elbow with its binary64 centre moved 6.5e-10 R along
    // the chord: admissible to the product (radius mismatch 9.2e-10, tolerance
    // 1e-9), but the product's trigonometric chord R(cos φ − 1, R sin φ) is no
    // longer x_j − x_i, which adds about 0.4 of the criterion in both modes.
    // The check's H uses the actual chord, so EF tracks the actual error
    // (mutation 31b builds H from the product's chord and misses it). The
    // stiffness defect here is ~1e-9 relative, so EF's first-order agreement
    // is to a few per cent rather than 1e-3.
    let model = &CSKEW_30_RADIUS_MISMATCH;
    let built = Built::from_model(model);
    for mode in MODES {
        let plain = built.plain(mode);
        let actual = actual_ratio(model, &plain.displacements);
        assert_eq!(plain.report.quality, SolveQuality::Passed, "{mode:?}");
        assert!(actual > 0.7, "{mode:?}: actual {actual}");
        let checked = built.checked(mode);
        record(model.name, mode, Some(actual), &checked);
        assert_demoted_only_in_quality(&plain, &checked);
        let ef = estimate(&checked) / 2.0;
        assert!(
            (ef / actual - 1.0).abs() < 0.05,
            "{mode:?}: EF {ef} actual {actual}"
        );
    }
}

#[test]
fn kd5_curved_matching_is_order_independent() {
    let built = Built::from_model(&E6);
    assert_eq!(built.macros.len(), 4);
    let mut reversed = built.macros.clone();
    reversed.reverse();
    for mode in MODES {
        let forward = built.checked(mode);
        let backward = built.checked_with(mode, &reversed);
        assert_eq!(forward.formation_check, None);
        assert_eq!(backward.formation_check, None);
        assert_eq!(bits(&forward.displacements), bits(&backward.displacements));
        assert_eq!(
            format!("{:?}", forward.report),
            format!("{:?}", backward.report)
        );
    }
}

#[test]
fn kd5_unmatched_explicit_and_one_ulp_curved_slots_fail_closed() {
    let base = Built::from_model(&E1);
    for mode in MODES {
        // Precondition: matched, E1 publishes Passed and is not demoted.
        let plain = base.plain(mode);
        assert_unchanged(&plain, &base.checked(mode));
        // (a) No macro element supplied for the slot.
        let unmatched = base.checked_with(mode, &[]);
        assert_demoted_only_in_quality(&plain, &unmatched);
        assert!(unavailable_detail(&unmatched).starts_with("curved_bend_source_unmatched:"));
        // (b) An explicit slot with the same matrix (no traced macro source).
        let mut explicit = Built::from_model(&E1);
        explicit.slots = explicit
            .slots
            .iter()
            .map(|s| {
                CurvedBendStiffnessElement::new(
                    s.element_id.clone(),
                    s.node_i,
                    s.node_j,
                    s.global_stiffness,
                )
                .unwrap()
            })
            .collect();
        let explicit_result = explicit.checked(mode);
        assert_demoted_only_in_quality(&explicit.plain(mode), &explicit_result);
        assert!(unavailable_detail(&explicit_result).starts_with("curved_bend_explicit_matrix:"));
        // (c) A slot whose matrix differs by one ulp from its macro element's.
        let mut ulp = Built::from_model(&E1);
        let slot = &mut ulp.slots[0];
        let old = slot.global_stiffness[2][2];
        let new = f64::from_bits(old.to_bits() + 1);
        slot.global_stiffness[2][2] = new;
        let map = element_dof_map(slot.node_i, slot.node_j);
        ulp.k[map[2]][map[2]] = ulp.k[map[2]][map[2]] - old + new;
        let ulp_plain = ulp.plain(mode);
        assert_eq!(ulp_plain.report.quality, SolveQuality::Passed);
        let ulp_result = ulp.checked(mode);
        assert_demoted_only_in_quality(&ulp_plain, &ulp_result);
        assert!(unavailable_detail(&ulp_result).starts_with("curved_bend_source_unmatched:"));
    }
}

/// Two collinear frames joined by an expansion joint (a user-stiffness
/// element), anchors at both ends, an axial pull and a transverse load.
fn joint_model(lateral: f64) -> Built {
    let section = FrameSection::new(
        F122.section.e,
        F122.section.g,
        F122.section.a,
        F122.section.i,
        F122.section.i,
        F122.section.j,
    )
    .unwrap();
    let points = [
        [0.0, 0.0, 0.0],
        [3.0, 1.5, 0.0],
        [3.2, 1.6, 0.0],
        [6.2, 3.1, 0.0],
    ];
    let node = |i: usize| FrameNode::new(i, points[i]).unwrap();
    let y = [0.0, 0.0, 1.0];
    let frames = vec![
        FrameElement::new(node(0), node(1), section, y).unwrap(),
        FrameElement::new(node(2), node(3), section, y).unwrap(),
    ];
    // Struct literal: `UserStiffnessElement::new` refuses lateral = 0, the only
    // form the ordinary route realizes (lateral ≠ 0 is refused in the product).
    let joint = UserStiffnessElement {
        node_i: node(1),
        node_j: node(2),
        y_reference: y,
        axial_stiffness: 2.5e6,
        lateral_stiffness: lateral,
        angular_stiffness: 4.0e4,
        torsional_stiffness: 6.0e4,
    };
    let mut built = Built {
        frames: frames.clone(),
        users: vec![joint],
        macros: Vec::new(),
        slots: Vec::new(),
        springs: Vec::new(),
        node_count: 4,
        k: vec![vec![0.0; 24]; 24],
        f: vec![0.0; 24],
        free: Vec::new(),
        prescribed: Vec::new(),
    };
    for e in &frames {
        built.scatter(
            e.node_i.index,
            e.node_j.index,
            &e.global_stiffness().unwrap(),
        );
    }
    built.scatter(1, 2, &joint.global_stiffness().unwrap());
    built.f[6] = 1000.0;
    built.f[6 + 2] = -500.0;
    built.f[12 + 1] = 300.0;
    built.f[12 + 2] = -500.0;
    built.set_boundary(&[0, 1, 2, 3, 4, 5, 18, 19, 20, 21, 22, 23]);
    built
}

#[test]
fn kd5_expansion_joint_with_zero_lateral_does_not_demote_and_nonzero_lateral_fails_closed() {
    let zero = joint_model(0.0);
    let nonzero = joint_model(1.0e5);
    for mode in MODES {
        let plain = zero.plain(mode);
        assert_eq!(plain.report.quality, SolveQuality::Passed, "{mode:?}");
        assert_unchanged(&plain, &zero.checked(mode));
        let plain = nonzero.plain(mode);
        assert_eq!(plain.report.quality, SolveQuality::Passed, "{mode:?}");
        let checked = nonzero.checked(mode);
        assert_demoted_only_in_quality(&plain, &checked);
        assert!(unavailable_detail(&checked).starts_with("user_stiffness_lateral_nonzero:"));
    }
}

#[test]
fn kd5_not_selected_invocation_runs_the_unchanged_solve() {
    // ROOT: an invocation with a nonlinear support is never selected. The
    // selected path demotes 122; the unselected path is `solve`, bit for bit.
    let built = Built::from_model(&F122);
    for mode in MODES {
        let plain = built.plain(mode);
        assert_eq!(built.checked(mode).report.quality, SolveQuality::Sensitive);
        let unselected = built
            .assembly()
            .solve_with_formation_check(
                &built.k,
                &built.f,
                &built.free,
                &built.prescribed,
                mode,
                &built.macros,
                false,
            )
            .unwrap();
        assert_eq!(unselected, plain);
    }
}

#[test]
fn kd5_force_terms_entry_uses_the_identified_terms() {
    let built = Built::from_model(&F122);
    let terms: Vec<ForceTerm> = F122
        .loads
        .iter()
        .map(|&(dof, v)| ForceTerm {
            source: format!("load:{dof}"),
            dof,
            kind: open_pipe_stress_frame_kernel::load_ledger::ForceTermKind::Term(v),
        })
        .collect();
    for mode in MODES {
        let assembly = built.assembly().with_force_terms(&terms);
        let plain = assembly
            .solve(&built.k, &built.f, &built.free, &built.prescribed, mode)
            .unwrap();
        assert_eq!(plain.load_fidelity, None);
        let checked = assembly
            .solve_with_formation_check(
                &built.k,
                &built.f,
                &built.free,
                &built.prescribed,
                mode,
                &[],
                true,
            )
            .unwrap();
        assert_demoted_only_in_quality(&plain, &checked);
        assert!(estimate(&checked) > 1.0);
    }
}

// ------------------------------------------------ nonlinear-loop pins (mutation 32)

/// Removes comments and blanks string/char literal contents (line structure
/// kept), then blanks every `#[cfg(test)]` item.
fn lexed_non_test(src: &str) -> String {
    let b: Vec<char> = src.chars().collect();
    let mut out = String::with_capacity(b.len());
    let mut i = 0;
    while i < b.len() {
        let c = b[i];
        if c == '/' && b.get(i + 1) == Some(&'/') {
            while i < b.len() && b[i] != '\n' {
                i += 1;
            }
            continue;
        }
        if c == '/' && b.get(i + 1) == Some(&'*') {
            let mut depth = 1;
            i += 2;
            while i < b.len() && depth > 0 {
                if b[i] == '/' && b.get(i + 1) == Some(&'*') {
                    depth += 1;
                    i += 2;
                } else if b[i] == '*' && b.get(i + 1) == Some(&'/') {
                    depth -= 1;
                    i += 2;
                } else {
                    i += 1;
                }
            }
            continue;
        }
        if c == '"' {
            i += 1;
            while i < b.len() && b[i] != '"' {
                if b[i] == '\\' {
                    i += 1;
                }
                i += 1;
            }
            out.push_str("\"\"");
            i += 1;
            continue;
        }
        if c == '\'' && i + 2 < b.len() && b[i + 1] != '\\' && b[i + 2] == '\'' {
            out.push_str("' '");
            i += 3;
            continue;
        }
        out.push(c);
        i += 1;
    }
    let mut code = String::with_capacity(out.len());
    let mut rest = out.as_str();
    const ATTR: &str = "#[cfg(test)]";
    while let Some(at) = rest.find(ATTR) {
        code.push_str(&rest[..at]);
        let item = &rest[at + ATTR.len()..];
        let (mut depth, mut started, mut end) = (0usize, false, item.len());
        for (k, ch) in item.char_indices() {
            match ch {
                '{' => {
                    depth += 1;
                    started = true;
                }
                '}' => {
                    depth -= 1;
                    if started && depth == 0 {
                        end = k + 1;
                        break;
                    }
                }
                ';' if !started => {
                    end = k + 1;
                    break;
                }
                _ => {}
            }
        }
        rest = &item[end..];
    }
    code.push_str(rest);
    code
}

const FORMATION_ENTRY_POINTS: [&str; 7] = [
    "solve_assembled_with_formation_check",
    "solve_with_formation_check",
    "with_formation_source",
    "prepare_formation_checked_structural",
    "solve_formation_checked_structural_dense",
    "FormationSource",
    "FormationCheckedSystem",
];

#[test]
fn kd5_nonlinear_sources_name_no_formation_check_entry_point() {
    let lexer_control = lexed_non_test(
        "fn a() { b.solve_binary64(); } // solve_with_formation_check(\n\
         const S: &str = \"solve_with_formation_check\";\n\
         #[cfg(test)]\nmod t { fn c() { d.solve_with_formation_check(); } }\n",
    );
    assert!(lexer_control.contains("solve_binary64("));
    assert!(!lexer_control.contains("solve_with_formation_check"));
    for (name, text) in [
        (
            "nonlinear_integration/src/lib.rs",
            include_str!("../lib.rs"),
        ),
        (
            "nonlinear_integration/src/product_equilibrium.rs",
            include_str!("../product_equilibrium.rs"),
        ),
    ] {
        let code = lexed_non_test(text);
        for entry in FORMATION_ENTRY_POINTS {
            assert!(!code.contains(entry), "{name} reaches {entry}");
        }
    }
    // The loop's structural solve stays the named binary64 variant.
    let lib = lexed_non_test(include_str!("../lib.rs"));
    assert!(lib.contains("assembly.solve_binary64("));
}

/// The 122 cantilever with an open gap support at the tip: the loop solves the
/// same linear system in its first (and only) iteration.
fn loop_input() -> (NonlinearFrameSolveInput, Built) {
    let built = Built::from_model(&F122);
    let input = NonlinearFrameSolveInput {
        node_count: 2,
        elements: built.frames.clone(),
        user_stiffness_elements: vec![],
        curved_bend_elements: vec![],
        force: built.f.clone(),
        base_restrained_dofs: F122.rigid.to_vec(),
        nonlinear_supports: vec![NonlinearSupport::gap(
            "kd5-open-gap",
            1,
            FrameDof::Uz,
            1.0,
            GapDirection::PositiveDisplacement,
        )
        .unwrap()],
        initial_states: vec![SupportStateRecord::new(
            "kd5-open-gap",
            ActiveSetState::Inactive,
        )],
        friction_normal_reactions: vec![],
        derived_friction_normal_reactions: vec![],
        convergence: ConvergenceControl::new(
            "DEC-046-fixture-active-set-count-tightening",
            ConvergencePolicyStatus::Accepted,
            0.0,
            0.0,
            4,
        )
        .unwrap(),
    };
    (input, built)
}

#[test]
fn kd5_nonlinear_loop_reaches_no_formation_check() {
    let (input, built) = loop_input();
    for mode in MODES {
        // Precondition: the same linear system demotes through the formation
        // check, so the two paths differ observably.
        let checked = built.checked(mode);
        assert_eq!(checked.report.quality, SolveQuality::Sensitive, "{mode:?}");
        let plain = built.plain(mode);
        assert_eq!(plain.report.quality, SolveQuality::Passed, "{mode:?}");
        // The loop: its solve is the unchanged binary64 path, never the check.
        let result =
            solve_active_set_frame_with_mode_and_springs(&input, mode, &built.springs).unwrap();
        assert!(result.converged, "{mode:?}");
        let first = result.iterations.first().expect("iteration");
        assert_eq!(
            first.structural_report.quality,
            SolveQuality::Passed,
            "{mode:?}"
        );
        let binary64 = built
            .assembly()
            .solve_binary64(&built.k, &built.f, &built.free, &built.prescribed, mode)
            .unwrap();
        assert_eq!(binary64.formation_check, None);
        assert_eq!(
            bits(&first.displacements),
            bits(&binary64.displacements),
            "{mode:?}"
        );
        assert_eq!(
            format!("{:?}", first.structural_report),
            format!("{:?}", binary64.report),
            "{mode:?}"
        );
    }
}

#[test]
fn kd5_typed_entry_demotes_122_and_unselected_is_solve_assembled() {
    let built = Built::from_model(&F122);
    let mut ledger = open_pipe_stress_frame_kernel::load_ledger::LoadLedger::new();
    for &(dof, v) in F122.loads {
        ledger.push(format!("load:{dof}"), dof, v);
    }
    let force = ledger.finish(built.f.len()).unwrap();
    assert_eq!(bits(force.values()), bits(&built.f));
    for mode in MODES {
        let assembly = built.assembly();
        let plain = assembly
            .solve_assembled(&built.k, &force, &built.free, &built.prescribed, mode)
            .unwrap();
        assert_eq!(plain.report.quality, SolveQuality::Passed, "{mode:?}");
        assert!(actual_ratio(&F122, &plain.displacements) > 1.0);
        let checked = assembly
            .solve_assembled_with_formation_check(
                &built.k,
                &force,
                &built.free,
                &built.prescribed,
                mode,
                &built.macros,
                true,
            )
            .unwrap();
        record(
            "F122-typed",
            mode,
            Some(actual_ratio(&F122, &plain.displacements)),
            &checked,
        );
        assert_demoted_only_in_quality(&plain, &checked);
        let unselected = assembly
            .solve_assembled_with_formation_check(
                &built.k,
                &force,
                &built.free,
                &built.prescribed,
                mode,
                &built.macros,
                false,
            )
            .unwrap();
        assert_eq!(unselected, plain);
    }
}
