//! K-D5 tests (T3 D1 revision 5a.2 §4.3.1 and the §6 K-D5 row) for the
//! adapter's typed linear entry `solve_assembled_with_formation_check`, both
//! solve modes. The nonlinear-loop pins live in `crate::s11k_tests` beside
//! I1's option-(c) pins and use this module's builders.
//!
//! Every behavioural assertion first shows that the two paths differ where
//! the assertion depends on it (RV1's S1 lesson): the ordinary typed
//! `solve_assembled` publishes Passed, and the actual error of its own u against the exact
//! intended solution (`kd5_models.rs`, generated by the run record
//! `kd5_models.py`) is above, or below, half the criterion.
use super::*;
use crate::CurvedBendStiffnessElement;
use open_pipe_stress_frame_kernel::load_ledger::LoadLedger;
use open_pipe_stress_frame_kernel::structural::{FormationCheckReason, SolveQuality};
use open_pipe_stress_frame_kernel::{FrameNode, FrameSection};

#[path = "kd5_models.rs"]
pub(crate) mod kd5_models;
use kd5_models::*;

pub(super) struct SectionData {
    pub(super) e: f64,
    pub(super) g: f64,
    pub(super) a: f64,
    pub(super) i: f64,
    pub(super) j: f64,
}
pub(super) struct MemberData {
    pub(super) i: usize,
    pub(super) j: usize,
    pub(super) y_reference: [f64; 3],
    /// (R, y_reference of the arc's plane on its bow side, flexibility
    /// factor) for a realized bend: T4-U1's element inputs.
    pub(super) bend: Option<(f64, [f64; 3], f64)>,
}
pub(super) struct ModelData {
    pub(super) name: &'static str,
    pub(super) section: SectionData,
    pub(super) nodes: &'static [[f64; 3]],
    pub(super) members: &'static [MemberData],
    pub(super) rigid: &'static [usize],
    pub(super) springs: &'static [(usize, f64)],
    pub(super) loads: &'static [(usize, f64)],
    /// Exact intended free displacements (empty where not computed).
    pub(super) u_int: &'static [(usize, f64)],
}

pub(crate) const MODES: [LinearSolveMode; 2] = [
    LinearSolveMode::DenseScrutiny,
    LinearSolveMode::SparseInteractive,
];

pub(crate) struct Built {
    pub(crate) frames: Vec<FrameElement>,
    users: Vec<UserStiffnessElement>,
    macros: Vec<CurvedBendMacroElement>,
    slots: Vec<CurvedBendStiffnessElement>,
    pub(crate) springs: Vec<(usize, f64)>,
    node_count: usize,
    pub(crate) k: Vec<Vec<f64>>,
    pub(crate) f: Vec<f64>,
    pub(crate) free: Vec<usize>,
    pub(crate) prescribed: Vec<(usize, f64)>,
}

impl Built {
    fn from_model(m: &ModelData) -> Self {
        let node_count = m.nodes.len();
        let n = 6 * node_count;
        let node = |i: usize| FrameNode::new(i, m.nodes[i]).unwrap();
        let s = &m.section;
        let section = FrameSection::new(s.e, s.g, s.a, s.i, s.i, s.j).unwrap();
        let mut built = Built {
            frames: Vec::new(),
            users: Vec::new(),
            macros: Vec::new(),
            slots: Vec::new(),
            springs: m.springs.to_vec(),
            node_count,
            k: vec![vec![0.0; n]; n],
            f: vec![0.0; n],
            free: Vec::new(),
            prescribed: Vec::new(),
        };
        for (index, member) in m.members.iter().enumerate() {
            let matrix = match member.bend {
                None => {
                    let e = FrameElement::new(
                        node(member.i),
                        node(member.j),
                        section,
                        member.y_reference,
                    )
                    .unwrap();
                    built.frames.push(e);
                    e.global_stiffness().unwrap()
                }
                Some((radius, y_reference, factor)) => {
                    let e = CurvedBendMacroElement::new(
                        node(member.i),
                        node(member.j),
                        radius,
                        y_reference,
                        s.e,
                        s.g,
                        s.a,
                        s.i,
                        s.j,
                        factor,
                        factor,
                    )
                    .unwrap();
                    let slot =
                        CurvedBendStiffnessElement::from_macro_element(format!("bend-{index}"), &e)
                            .unwrap();
                    built.macros.push(e);
                    let matrix = slot.global_stiffness;
                    built.slots.push(slot);
                    matrix
                }
            };
            built.scatter(member.i, member.j, &matrix);
        }
        for &(dof, value) in m.springs {
            built.k[dof][dof] += value;
        }
        for &(dof, value) in m.loads {
            built.f[dof] += value;
        }
        built.set_boundary(m.rigid);
        built
    }
    fn scatter(&mut self, a: usize, b: usize, matrix: &Matrix12) {
        let map = element_dof_map(a, b);
        for r in 0..12 {
            for c in 0..12 {
                self.k[map[r]][map[c]] += matrix[r][c];
            }
        }
    }
    fn set_boundary(&mut self, rigid: &[usize]) {
        let n = self.f.len();
        self.prescribed = rigid.iter().map(|&d| (d, 0.0)).collect();
        self.free = (0..n).filter(|d| !rigid.contains(d)).collect();
    }
    pub(crate) fn assembly(&self) -> AssemblyEvidence {
        AssemblyEvidence::new(
            self.node_count,
            &self.frames,
            &self.users,
            &self.slots,
            &self.springs,
        )
        .unwrap()
    }
    /// The ledger-built force: one term per nonzero load, bit-equal to `f`.
    pub(crate) fn ledger(&self) -> AssembledForce {
        let mut ledger = LoadLedger::new();
        for (dof, &v) in self.f.iter().enumerate() {
            if v != 0.0 {
                ledger.push(format!("load:{dof}"), dof, v);
            }
        }
        let force = ledger.finish(self.f.len()).unwrap();
        assert_eq!(bits(force.values()), bits(&self.f));
        force
    }
    /// The ordinary typed solve (the product's path before K-D5).
    pub(crate) fn plain(&self, mode: LinearSolveMode) -> StructuralSolution {
        self.assembly()
            .solve_assembled(&self.k, &self.ledger(), &self.free, &self.prescribed, mode)
            .unwrap()
    }
    pub(crate) fn checked_selected(
        &self,
        mode: LinearSolveMode,
        macros: &[CurvedBendMacroElement],
        selected: bool,
    ) -> StructuralSolution {
        self.assembly()
            .solve_assembled_with_formation_check(
                &self.k,
                &self.ledger(),
                &self.free,
                &self.prescribed,
                mode,
                macros,
                selected,
            )
            .unwrap()
    }
    fn checked_with(
        &self,
        mode: LinearSolveMode,
        macros: &[CurvedBendMacroElement],
    ) -> StructuralSolution {
        self.checked_selected(mode, macros, true)
    }
    pub(crate) fn checked(&self, mode: LinearSolveMode) -> StructuralSolution {
        self.checked_with(mode, &self.macros)
    }
}

/// max over free rows of |u − u_int| / (1e-9·max(|u_int|, S*_kind(u_int))),
/// one body, S* per D1 §4.1.6.1 items 4–6 (the design's actual-error measure).
fn actual_ratio(m: &ModelData, u: &[f64]) -> f64 {
    assert!(!m.u_int.is_empty(), "{}: no reference", m.name);
    let (mut st, mut sr) = (0.0_f64, 0.0_f64);
    for &(d, v) in m.u_int {
        if d % 6 < 3 {
            st = st.max(v.abs());
        } else {
            sr = sr.max(v.abs());
        }
    }
    let mut d = [0.0; 3];
    for (k, dk) in d.iter_mut().enumerate() {
        let hi = m.nodes.iter().map(|p| p[k]).fold(f64::MIN, f64::max);
        let lo = m.nodes.iter().map(|p| p[k]).fold(f64::MAX, f64::min);
        *dk = hi - lo;
    }
    let l_b = ((d[0] * d[0] + d[1] * d[1]) + d[2] * d[2]).sqrt();
    let (tr, ro) = (st.max(l_b * sr), sr.max(st / l_b));
    m.u_int
        .iter()
        .map(|&(dof, v)| {
            let scale = v.abs().max(if dof % 6 < 3 { tr } else { ro });
            (u[dof] - v).abs() / (1e-9 * scale)
        })
        .fold(0.0, f64::max)
}

/// The required true positive's model (P1's 122 skew cantilever), for the
/// nonlinear-loop pins in `crate::s11k_tests`.
pub(crate) fn skew_122() -> Built {
    Built::from_model(&F122)
}
pub(crate) fn skew_122_rigid() -> &'static [usize] {
    F122.rigid
}

pub(crate) fn bits(u: &[f64]) -> Vec<u64> {
    u.iter().map(|v| v.to_bits()).collect()
}

/// A demoted solution differs from the ordinary one only in `quality` and
/// the separate record; values and every other report field are identical.
fn assert_demoted_only_in_quality(plain: &StructuralSolution, checked: &StructuralSolution) {
    assert_eq!(plain.report.quality, SolveQuality::Passed);
    assert_eq!(checked.report.quality, SolveQuality::Sensitive);
    assert_eq!(bits(&plain.displacements), bits(&checked.displacements));
    let mut report = checked.report.clone();
    report.quality = SolveQuality::Passed;
    assert_eq!(format!("{:?}", report), format!("{:?}", plain.report));
    assert!(checked.formation_check.is_some());
}

/// Not demoted: the solution is the ordinary one, byte for byte (D5C-3).
fn assert_unchanged(plain: &StructuralSolution, checked: &StructuralSolution) {
    assert_eq!(checked.formation_check, None);
    assert_eq!(bits(&plain.displacements), bits(&checked.displacements));
    assert_eq!(
        format!("{:?}", plain.report),
        format!("{:?}", checked.report)
    );
}

/// Records the measured numbers (visible with `--nocapture`, kept in the run records).
fn record(name: &str, mode: LinearSolveMode, actual: Option<f64>, checked: &StructuralSolution) {
    let trigger = checked
        .formation_check
        .as_ref()
        .map(|r| (r.ratio, r.global_dof));
    eprintln!(
        "kd5 {name} {mode:?} actual={actual:?} demoted={} trigger={trigger:?}",
        checked.formation_check.is_some()
    );
}

fn estimate(checked: &StructuralSolution) -> f64 {
    let record = checked.formation_check.as_ref().expect("demoted");
    assert_eq!(record.reason, FormationCheckReason::Estimate);
    record.ratio
}

fn unavailable_detail(checked: &StructuralSolution) -> String {
    match &checked.formation_check.as_ref().expect("demoted").reason {
        FormationCheckReason::FormationCheckUnavailable { detail } => detail.clone(),
        other => panic!("expected formation_check_unavailable, got {other:?}"),
    }
}

#[test]
fn kd5_required_true_positive_skew_cantilever_122_demotes_in_both_modes() {
    let built = Built::from_model(&F122);
    for mode in MODES {
        let plain = built.plain(mode);
        let actual = actual_ratio(&F122, &plain.displacements);
        // Precondition: main publishes Passed with a breach of the criterion.
        assert_eq!(plain.report.quality, SolveQuality::Passed, "{mode:?}");
        assert!(actual > 1.0, "{mode:?}: actual {actual}");
        let checked = built.checked(mode);
        record("F122", mode, Some(actual), &checked);
        assert_demoted_only_in_quality(&plain, &checked);
        // EF tracks the actual error (the quoted EF is half the trigger value).
        let ef = estimate(&checked) / 2.0;
        assert!(
            (ef / actual - 1.0).abs() < 1e-3,
            "{mode:?}: EF {ef} actual {actual}"
        );
    }
}

#[test]
fn kd5_skew_345_and_invented_m11_do_not_demote() {
    for model in [&F345, &M11] {
        let built = Built::from_model(model);
        for mode in MODES {
            let plain = built.plain(mode);
            assert_eq!(
                plain.report.quality,
                SolveQuality::Passed,
                "{} {mode:?}",
                model.name
            );
            let actual =
                (!model.u_int.is_empty()).then(|| actual_ratio(model, &plain.displacements));
            assert!(actual.is_none_or(|a| a < 0.5));
            let checked = built.checked(mode);
            record(model.name, mode, actual, &checked);
            assert_unchanged(&plain, &checked);
        }
    }
}

#[test]
fn kd5_d5c1_controls_demote_exactly_where_the_actual_error_exceeds_half_the_criterion() {
    // V1's probe D (solve error only: the spring sum is exact), probe C (a soft
    // spring partly absorbed by G*J/L) and an axis-aligned bending-soft member.
    let mut demoted = Vec::new();
    for model in [&PROBE_D, &PROBE_C, &BENDING_SOFT] {
        let built = Built::from_model(model);
        for mode in MODES {
            let plain = built.plain(mode);
            assert_eq!(
                plain.report.quality,
                SolveQuality::Passed,
                "{} {mode:?}",
                model.name
            );
            let actual = actual_ratio(model, &plain.displacements);
            let checked = built.checked(mode);
            record(model.name, mode, Some(actual), &checked);
            assert!(
                (actual - 0.5).abs() > 0.05,
                "{} {mode:?}: control too close to the boundary ({actual})",
                model.name
            );
            if actual > 0.5 {
                assert_demoted_only_in_quality(&plain, &checked);
                let ef = estimate(&checked) / 2.0;
                assert!(
                    (ef / actual - 1.0).abs() < 1e-3,
                    "{} {mode:?}: EF {ef} actual {actual}",
                    model.name
                );
                demoted.push(model.name);
            } else {
                assert_unchanged(&plain, &checked);
            }
        }
    }
    // Each class demotes in at least one mode (the controls are not vacuous).
    for name in ["PROBE_D", "PROBE_C", "BENDING_SOFT"] {
        assert!(demoted.contains(&name), "{name} never demoted: {demoted:?}");
    }
}

#[test]
fn kd5_realistic_elbows_e1_and_e6_do_not_demote() {
    for model in [&E1, &E6] {
        let built = Built::from_model(model);
        assert!(!built.macros.is_empty());
        for mode in MODES {
            let plain = built.plain(mode);
            assert_eq!(
                plain.report.quality,
                SolveQuality::Passed,
                "{} {mode:?}",
                model.name
            );
            let actual = actual_ratio(model, &plain.displacements);
            assert!(actual < 0.5);
            let checked = built.checked(mode);
            record(model.name, mode, Some(actual), &checked);
            assert_unchanged(&plain, &checked);
        }
    }
}

/// The D5C-1 rule on one solve: demoted exactly when the published error
/// exceeds half the criterion (a Passed breach, actual > 1, is therefore
/// never published), with EF tracking the actual error when demoted.
fn assert_d5c1(
    name: &str,
    mode: LinearSolveMode,
    actual: f64,
    plain: &StructuralSolution,
    checked: &StructuralSolution,
) {
    assert_eq!(
        plain.report.quality,
        SolveQuality::Passed,
        "{name} {mode:?}"
    );
    if actual > 0.5 {
        assert_demoted_only_in_quality(plain, checked);
        let ef = estimate(checked) / 2.0;
        assert!(
            (ef / actual - 1.0).abs() < 1e-3,
            "{name} {mode:?}: EF {ef} actual {actual}"
        );
    } else {
        assert_unchanged(plain, checked);
    }
}

#[test]
fn kd5_conditioning_driven_curved_true_positive_demotes_in_both_modes() {
    // RV131 B-1 / T4-I6 round 01 item 1: F122 with its member realized as
    // one bend, R = 10 m in the plane of y = (1, 0, 0) (φ = 0.301 rad, cond₁
    // 3.9e7 < 1/√ε). The breach is conditioning-driven: an accurate element
    // (crK 0.77) and the solve's own error, not a small-angle or chord
    // defect. Selection (WI ruling): the first of round 01's frozen
    // candidates, in its rank order, that publishes Passed and is demoted in
    // both modes with actual > 0.55 and EF/actual within 1e-3. The first,
    // C122K120-R100-Y100, publishes DenseScrutiny actual 0.518 (demoted, but
    // not above 0.55), so this second candidate is the true positive.
    let model = &C122_R10_Y100;
    let built = Built::from_model(model);
    assert_eq!(built.macros.len(), 1);
    for mode in MODES {
        let plain = built.plain(mode);
        let actual = actual_ratio(model, &plain.displacements);
        assert_eq!(plain.report.quality, SolveQuality::Passed, "{mode:?}");
        assert!(actual > 0.55, "{mode:?}: actual {actual}");
        let checked = built.checked(mode);
        record(model.name, mode, Some(actual), &checked);
        assert_demoted_only_in_quality(&plain, &checked);
        let ef = estimate(&checked) / 2.0;
        assert!(
            (ef / actual - 1.0).abs() < 1e-3,
            "{mode:?}: EF {ef} actual {actual}"
        );
    }
}

#[test]
fn kd5_curved_candidates_demote_exactly_where_the_actual_error_exceeds_half_the_criterion() {
    // Round 01's other frozen candidates as D5C-1 controls (round 01 §1).
    // C122K120-R100-Y100 is left out: its DenseScrutiny actual (0.518) lies
    // in the ±0.05 guard band around the boundary.
    let mut demoted = Vec::new();
    for model in [
        &C122_R10_YM100,
        &C122_R100_Y011,
        &C122_R100_Y01M1,
        &C122_R100_Y100,
        &C122_R10_Y01M1,
    ] {
        let built = Built::from_model(model);
        for mode in MODES {
            let plain = built.plain(mode);
            let actual = actual_ratio(model, &plain.displacements);
            let checked = built.checked(mode);
            record(model.name, mode, Some(actual), &checked);
            assert!(
                (actual - 0.5).abs() > 0.05,
                "{} {mode:?}: control too close to the boundary ({actual})",
                model.name
            );
            assert_d5c1(model.name, mode, actual, &plain, &checked);
            if checked.formation_check.is_some() {
                demoted.push((model.name, mode));
            }
        }
    }
    assert!(!demoted.is_empty());
}

#[test]
fn kd5_skew_plane_elbow_cantilever_publishes_no_breach_and_demotes_exactly_above_half() {
    // The CSKEW rule (DEL-04-01 Design; T4-I6 round 01 item 2): with the
    // objective element CSKEW_8_5 no longer has to demote. In each mode there
    // is no Passed breach (actual > 1 is demoted), it is demoted exactly when
    // actual > 0.5 (EF/actual within 1e-3), otherwise unchanged, and actual
    // keeps 0.05 from the boundary. If a mode lands within the guard band,
    // CSKEW_9 and then CSKEW_10 substitute for it (u_int frozen by T4-I6,
    // round 00 t3_models[14] and [13]); the condition is not relaxed.
    for mode in MODES {
        let mut chosen = None;
        for model in [&CSKEW_8_5, &CSKEW_9, &CSKEW_10] {
            let built = Built::from_model(model);
            let plain = built.plain(mode);
            let actual = actual_ratio(model, &plain.displacements);
            let checked = built.checked(mode);
            record(model.name, mode, Some(actual), &checked);
            assert_eq!(
                plain.report.quality,
                SolveQuality::Passed,
                "{} {mode:?}",
                model.name
            );
            // No Passed breach for any of the three.
            if actual > 1.0 {
                assert_demoted_only_in_quality(&plain, &checked);
            }
            if chosen.is_none() && (actual - 0.5).abs() > 0.05 {
                chosen = Some((model.name, actual, plain, checked));
            }
        }
        let (name, actual, plain, checked) = chosen.expect(
            "CSKEW_8_5, CSKEW_9 and CSKEW_10 all within 0.05 of the boundary: report to T3",
        );
        assert_d5c1(name, mode, actual, &plain, &checked);
    }
}

#[test]
fn kd5_skew_plane_elbow_at_kx_30_is_an_ordinary_control() {
    // Formerly CSKEW_30_RADIUS_MISMATCH (a binary64 centre moved 6.5e-10 R
    // along the chord, the M31a/M31b kill). A centre mismatch cannot be
    // expressed in T4-U1's (R, y) inputs, so the model is regenerated as the
    // ordinary k_X = 30 elbow (u_int frozen by T4-I6, round 00 t3_models[3])
    // and is a D5C-1 control; M31a's kill is K2's (FK
    // `kd5_k2_formula_chord_system_demotes_against_the_actual_chord`).
    let model = &CSKEW_30;
    let built = Built::from_model(model);
    for mode in MODES {
        let plain = built.plain(mode);
        let actual = actual_ratio(model, &plain.displacements);
        let checked = built.checked(mode);
        record(model.name, mode, Some(actual), &checked);
        assert!((actual - 0.5).abs() > 0.05, "{mode:?}: actual {actual}");
        assert_d5c1(model.name, mode, actual, &plain, &checked);
    }
}

#[test]
fn kd5_k1_stable_form_at_1e_8_rad_is_published_accurately_and_not_demoted() {
    // K1 and K1F (T4-I6 round 01 item 4; RV131 S-1): the cantilever bend at
    // φ = 1e-8 rad (R ≈ 3e7 m, chord 0.3 m), in-plane and skew, with a tip
    // moment (K1) and a tip force plus moment (K1F, which reaches every
    // column of the end flexibility). The stable small-angle form publishes
    // an accurate u (a cancelling form misses K1 by about 0.5 and K1F by
    // 1e6 criteria) and a correct K-D5 leaves it unchanged; K-D5 with the
    // binary64 formula chord (M31b) demotes it (trigger ≈ 12).
    for model in [&K1_IP, &K1_SK, &K1F_IP, &K1F_SK] {
        let built = Built::from_model(model);
        for mode in MODES {
            let plain = built.plain(mode);
            let actual = actual_ratio(model, &plain.displacements);
            assert_eq!(
                plain.report.quality,
                SolveQuality::Passed,
                "{} {mode:?}",
                model.name
            );
            assert!(actual < 0.5, "{} {mode:?}: actual {actual}", model.name);
            let checked = built.checked(mode);
            record(model.name, mode, Some(actual), &checked);
            assert_unchanged(&plain, &checked);
        }
    }
}

#[test]
fn kd5_acceptance_range_from_1e_8_rad_to_pi_at_ordinary_and_utm_coordinates() {
    // DEL-04-01 Design (acceptance range; T4-I6 round 01 item 8): K-D5's
    // margin from φ = 1e-8 to π − 1e-7 rad. Round 01's ten frozen sample
    // points (1e-3, 1e-2, 0.1, 1, 2, 3, π − 1e-3, π − 1e-4, π − 1e-5,
    // π − 1e-7; ACC model: tip force and moment) in the in-plane and skew
    // planes at X = 0 and X = 7.3e6 m, and round 00's K1 cantilevers at
    // 1e-4 and 1e-8 rad at X = 0 and X = 5e6 m: Passed, the published u
    // within half the criterion, not demoted, in both modes.
    let mut worst: f64 = 0.0;
    for model in ACC_SAMPLES.iter().chain(K1_RANGE_SAMPLES) {
        let built = Built::from_model(model);
        for mode in MODES {
            let plain = built.plain(mode);
            let actual = actual_ratio(model, &plain.displacements);
            assert_eq!(
                plain.report.quality,
                SolveQuality::Passed,
                "{} {mode:?}",
                model.name
            );
            assert!(actual < 0.5, "{} {mode:?}: actual {actual}", model.name);
            let checked = built.checked(mode);
            record(model.name, mode, Some(actual), &checked);
            assert_unchanged(&plain, &checked);
            worst = worst.max(actual);
        }
    }
    eprintln!("kd5 acceptance range: worst actual {worst:e}");
    assert_eq!(ACC_SAMPLES.len() + K1_RANGE_SAMPLES.len(), 48);
}

#[test]
#[ignore = "M31b0 equivalence pending ROOT ruling (DEL-04-01 Design); see K1/K2 for M31b"]
fn kd5_admissible_centre_mismatch_demotes_where_the_product_chord_hides_the_error() {
    // RV5-B1 (the M31b counterexample, RV5's admissible inputs): one realized
    // bend on a cantilever with stiff root springs and a tip moment (1, 1, 1),
    // its binary64 centre moved along the chord to the edge of the product's
    // radius-match tolerance (1e-9). Planar 60° and skew 30°. The chord error
    // gives a first-order translation error at node 1 above the criterion,
    // which the check sees because its H uses the actual chord x_j − x_i.
    // Mutation 31b (H from the product's chord R(cos φ − 1), R sin φ) sees
    // none of it and fails the demotion assertion below.
    for model in [&CPLANAR_60, &CSKEW_30_N122] {
        let built = Built::from_model(model);
        for mode in MODES {
            let plain = built.plain(mode);
            let actual = actual_ratio(model, &plain.displacements);
            // Preconditions: main publishes Passed, and its published error
            // against the exact intended solution is above the criterion.
            assert_eq!(
                plain.report.quality,
                SolveQuality::Passed,
                "{} {mode:?}",
                model.name
            );
            assert!(actual > 1.0, "{} {mode:?}: actual {actual}", model.name);
            let checked = built.checked(mode);
            record(model.name, mode, Some(actual), &checked);
            assert_demoted_only_in_quality(&plain, &checked);
            let ef = estimate(&checked) / 2.0;
            assert!(
                (ef / actual - 1.0).abs() < 0.05,
                "{} {mode:?}: EF {ef} actual {actual}",
                model.name
            );
        }
    }
}

#[test]
fn kd5_large_coordinate_pp_route_elbow_does_not_demote() {
    // RV5-B1's PP-route elbow at X = 5e5 m (R = 0.3 m, φ = 2°, y = +y as PP
    // states it): no designed mismatch. Against the exact
    // intended solution (exact binary64 inputs) the product's published error
    // is about 0.04 of the criterion, so a correct check leaves it Passed and
    // unchanged (ordinary large-coordinate elbows are not falsely demoted).
    let model = &PP_UTM_2;
    let built = Built::from_model(model);
    for mode in MODES {
        let plain = built.plain(mode);
        let actual = actual_ratio(model, &plain.displacements);
        assert_eq!(plain.report.quality, SolveQuality::Passed, "{mode:?}");
        assert!(actual < 0.5, "{mode:?}: actual {actual}");
        let checked = built.checked(mode);
        record(model.name, mode, Some(actual), &checked);
        assert_unchanged(&plain, &checked);
    }
}

#[test]
fn kd5_curved_matching_is_order_independent() {
    let built = Built::from_model(&E6);
    assert_eq!(built.macros.len(), 4);
    let mut reversed = built.macros.clone();
    reversed.reverse();
    for mode in MODES {
        let forward = built.checked(mode);
        let backward = built.checked_with(mode, &reversed);
        assert_eq!(forward.formation_check, None);
        assert_eq!(backward.formation_check, None);
        assert_eq!(bits(&forward.displacements), bits(&backward.displacements));
        assert_eq!(
            format!("{:?}", forward.report),
            format!("{:?}", backward.report)
        );
    }
}

#[test]
fn kd5_unmatched_explicit_and_one_ulp_curved_slots_fail_closed() {
    let base = Built::from_model(&E1);
    for mode in MODES {
        // Precondition: matched, E1 publishes Passed and is not demoted.
        let plain = base.plain(mode);
        assert_unchanged(&plain, &base.checked(mode));
        // (a) No macro element supplied for the slot.
        let unmatched = base.checked_with(mode, &[]);
        assert_demoted_only_in_quality(&plain, &unmatched);
        assert!(unavailable_detail(&unmatched).starts_with("curved_bend_source_unmatched:"));
        // (b) An explicit slot with the same matrix (no traced macro source).
        let mut explicit = Built::from_model(&E1);
        explicit.slots = explicit
            .slots
            .iter()
            .map(|s| {
                CurvedBendStiffnessElement::new(
                    s.element_id.clone(),
                    s.node_i,
                    s.node_j,
                    s.global_stiffness,
                )
                .unwrap()
            })
            .collect();
        let explicit_result = explicit.checked(mode);
        assert_demoted_only_in_quality(&explicit.plain(mode), &explicit_result);
        assert!(unavailable_detail(&explicit_result).starts_with("curved_bend_explicit_matrix:"));
        // (c) A slot whose matrix differs by one ulp from its macro element's.
        let mut ulp = Built::from_model(&E1);
        let slot = &mut ulp.slots[0];
        let old = slot.global_stiffness[2][2];
        let new = f64::from_bits(old.to_bits() + 1);
        slot.global_stiffness[2][2] = new;
        let map = element_dof_map(slot.node_i, slot.node_j);
        ulp.k[map[2]][map[2]] = ulp.k[map[2]][map[2]] - old + new;
        let ulp_plain = ulp.plain(mode);
        assert_eq!(ulp_plain.report.quality, SolveQuality::Passed);
        let ulp_result = ulp.checked(mode);
        assert_demoted_only_in_quality(&ulp_plain, &ulp_result);
        assert!(unavailable_detail(&ulp_result).starts_with("curved_bend_source_unmatched:"));
    }
}

/// Two collinear frames joined by an expansion joint (a user-stiffness
/// element), anchors at both ends, an axial pull and a transverse load.
fn joint_model(lateral: f64) -> Built {
    let section = FrameSection::new(
        F122.section.e,
        F122.section.g,
        F122.section.a,
        F122.section.i,
        F122.section.i,
        F122.section.j,
    )
    .unwrap();
    let points = [
        [0.0, 0.0, 0.0],
        [3.0, 1.5, 0.0],
        [3.2, 1.6, 0.0],
        [6.2, 3.1, 0.0],
    ];
    let node = |i: usize| FrameNode::new(i, points[i]).unwrap();
    let y = [0.0, 0.0, 1.0];
    let frames = vec![
        FrameElement::new(node(0), node(1), section, y).unwrap(),
        FrameElement::new(node(2), node(3), section, y).unwrap(),
    ];
    // Struct literal: `UserStiffnessElement::new` refuses lateral = 0, the only
    // form the ordinary route realizes (lateral ≠ 0 is refused in the product).
    let joint = UserStiffnessElement {
        node_i: node(1),
        node_j: node(2),
        y_reference: y,
        axial_stiffness: 2.5e6,
        lateral_stiffness: lateral,
        angular_stiffness: 4.0e4,
        torsional_stiffness: 6.0e4,
    };
    let mut built = Built {
        frames: frames.clone(),
        users: vec![joint],
        macros: Vec::new(),
        slots: Vec::new(),
        springs: Vec::new(),
        node_count: 4,
        k: vec![vec![0.0; 24]; 24],
        f: vec![0.0; 24],
        free: Vec::new(),
        prescribed: Vec::new(),
    };
    for e in &frames {
        built.scatter(
            e.node_i.index,
            e.node_j.index,
            &e.global_stiffness().unwrap(),
        );
    }
    built.scatter(1, 2, &joint.global_stiffness().unwrap());
    built.f[6] = 1000.0;
    built.f[6 + 2] = -500.0;
    built.f[12 + 1] = 300.0;
    built.f[12 + 2] = -500.0;
    built.set_boundary(&[0, 1, 2, 3, 4, 5, 18, 19, 20, 21, 22, 23]);
    built
}

#[test]
fn kd5_expansion_joint_with_zero_lateral_does_not_demote_and_nonzero_lateral_fails_closed() {
    let zero = joint_model(0.0);
    let nonzero = joint_model(1.0e5);
    for mode in MODES {
        let plain = zero.plain(mode);
        assert_eq!(plain.report.quality, SolveQuality::Passed, "{mode:?}");
        assert_unchanged(&plain, &zero.checked(mode));
        let plain = nonzero.plain(mode);
        assert_eq!(plain.report.quality, SolveQuality::Passed, "{mode:?}");
        let checked = nonzero.checked(mode);
        assert_demoted_only_in_quality(&plain, &checked);
        assert!(unavailable_detail(&checked).starts_with("user_stiffness_lateral_nonzero:"));
    }
}

#[test]
fn kd5_not_selected_invocation_runs_the_unchanged_solve_assembled() {
    // ROOT: an invocation with a nonlinear support is never selected. The
    // selected path demotes 122 (precondition: the paths differ); the
    // unselected path is `solve_assembled`, bit for bit.
    let built = Built::from_model(&F122);
    for mode in MODES {
        let plain = built.plain(mode);
        assert_eq!(plain.report.quality, SolveQuality::Passed, "{mode:?}");
        let selected = built.checked_selected(mode, &built.macros, true);
        assert_eq!(selected.report.quality, SolveQuality::Sensitive, "{mode:?}");
        let unselected = built.checked_selected(mode, &built.macros, false);
        assert_eq!(unselected, plain);
    }
}
