//! K-D5 tests (T3 D1 revision 5a.2 §4.3.1 and the §6 K-D5 row) for the
//! adapter's typed linear entry `solve_assembled_with_formation_check`, both
//! solve modes. The nonlinear-loop pins live in `crate::s11k_tests` beside
//! I1's option-(c) pins and use this module's builders.
//!
//! Every behavioural assertion first shows that the two paths differ where
//! the assertion depends on it (RV1's S1 lesson): the ordinary typed
//! `solve_assembled` publishes Passed, and the actual error of its own u against the exact
//! intended solution (`kd5_models.rs`, generated by the run record
//! `kd5_models.py`) is above, or below, half the criterion.
use super::*;
use crate::CurvedBendStiffnessElement;
use open_pipe_stress_frame_kernel::load_ledger::LoadLedger;
use open_pipe_stress_frame_kernel::structural::{FormationCheckReason, SolveQuality};
use open_pipe_stress_frame_kernel::{FrameNode, FrameSection};

#[path = "kd5_models.rs"]
pub(crate) mod kd5_models;
use kd5_models::*;

pub(super) struct SectionData {
    pub(super) e: f64,
    pub(super) g: f64,
    pub(super) a: f64,
    pub(super) i: f64,
    pub(super) j: f64,
}
pub(super) struct MemberData {
    pub(super) i: usize,
    pub(super) j: usize,
    pub(super) y_reference: [f64; 3],
    /// (the product's binary64 arc centre, flexibility factor) for a realized bend.
    pub(super) bend: Option<([f64; 3], f64)>,
}
pub(super) struct ModelData {
    pub(super) name: &'static str,
    pub(super) section: SectionData,
    pub(super) nodes: &'static [[f64; 3]],
    pub(super) members: &'static [MemberData],
    pub(super) rigid: &'static [usize],
    pub(super) springs: &'static [(usize, f64)],
    pub(super) loads: &'static [(usize, f64)],
    /// Exact intended free displacements (empty where not computed).
    pub(super) u_int: &'static [(usize, f64)],
}

pub(crate) const MODES: [LinearSolveMode; 2] = [
    LinearSolveMode::DenseScrutiny,
    LinearSolveMode::SparseInteractive,
];

pub(crate) struct Built {
    pub(crate) frames: Vec<FrameElement>,
    connectors: Vec<ObjectiveConnector>,
    macros: Vec<CurvedBendMacroElement>,
    slots: Vec<CurvedBendStiffnessElement>,
    pub(crate) springs: Vec<(usize, f64)>,
    node_count: usize,
    pub(crate) k: Vec<Vec<f64>>,
    pub(crate) f: Vec<f64>,
    pub(crate) free: Vec<usize>,
    pub(crate) prescribed: Vec<(usize, f64)>,
}

impl Built {
    fn from_model(m: &ModelData) -> Self {
        let node_count = m.nodes.len();
        let n = 6 * node_count;
        let node = |i: usize| FrameNode::new(i, m.nodes[i]).unwrap();
        let s = &m.section;
        let section = FrameSection::new(s.e, s.g, s.a, s.i, s.i, s.j).unwrap();
        let mut built = Built {
            frames: Vec::new(),
            connectors: Vec::new(),
            macros: Vec::new(),
            slots: Vec::new(),
            springs: m.springs.to_vec(),
            node_count,
            k: vec![vec![0.0; n]; n],
            f: vec![0.0; n],
            free: Vec::new(),
            prescribed: Vec::new(),
        };
        for (index, member) in m.members.iter().enumerate() {
            let matrix = match member.bend {
                None => {
                    let e = FrameElement::new(
                        node(member.i),
                        node(member.j),
                        section,
                        member.y_reference,
                    )
                    .unwrap();
                    built.frames.push(e);
                    e.global_stiffness().unwrap()
                }
                Some((center, factor)) => {
                    let e = CurvedBendMacroElement::new(
                        node(member.i),
                        node(member.j),
                        center,
                        s.e,
                        s.g,
                        s.a,
                        s.i,
                        s.j,
                        factor,
                        factor,
                    )
                    .unwrap();
                    let slot =
                        CurvedBendStiffnessElement::from_macro_element(format!("bend-{index}"), &e)
                            .unwrap();
                    built.macros.push(e);
                    let matrix = slot.global_stiffness;
                    built.slots.push(slot);
                    matrix
                }
            };
            built.scatter(member.i, member.j, &matrix);
        }
        for &(dof, value) in m.springs {
            built.k[dof][dof] += value;
        }
        for &(dof, value) in m.loads {
            built.f[dof] += value;
        }
        built.set_boundary(m.rigid);
        built
    }
    fn scatter(&mut self, a: usize, b: usize, matrix: &Matrix12) {
        let map = element_dof_map(a, b);
        for r in 0..12 {
            for c in 0..12 {
                self.k[map[r]][map[c]] += matrix[r][c];
            }
        }
    }
    fn set_boundary(&mut self, rigid: &[usize]) {
        let n = self.f.len();
        self.prescribed = rigid.iter().map(|&d| (d, 0.0)).collect();
        self.free = (0..n).filter(|d| !rigid.contains(d)).collect();
    }
    pub(crate) fn assembly(&self) -> AssemblyEvidence {
        AssemblyEvidence::new(
            self.node_count,
            &self.frames,
            &self.connectors,
            &self.slots,
            &self.springs,
        )
        .unwrap()
    }
    /// The ledger-built force: one term per nonzero load, bit-equal to `f`.
    pub(crate) fn ledger(&self) -> AssembledForce {
        let mut ledger = LoadLedger::new();
        for (dof, &v) in self.f.iter().enumerate() {
            if v != 0.0 {
                ledger.push(format!("load:{dof}"), dof, v);
            }
        }
        let force = ledger.finish(self.f.len()).unwrap();
        assert_eq!(bits(force.values()), bits(&self.f));
        force
    }
    /// The ordinary typed solve (the product's path before K-D5).
    pub(crate) fn plain(&self, mode: LinearSolveMode) -> StructuralSolution {
        self.assembly()
            .solve_assembled(&self.k, &self.ledger(), &self.free, &self.prescribed, mode)
            .unwrap()
    }
    pub(crate) fn checked_selected(
        &self,
        mode: LinearSolveMode,
        macros: &[CurvedBendMacroElement],
        selected: bool,
    ) -> StructuralSolution {
        self.assembly()
            .solve_assembled_with_formation_check(
                &self.k,
                &self.ledger(),
                &self.free,
                &self.prescribed,
                mode,
                macros,
                selected,
            )
            .unwrap()
    }
    fn checked_with(
        &self,
        mode: LinearSolveMode,
        macros: &[CurvedBendMacroElement],
    ) -> StructuralSolution {
        self.checked_selected(mode, macros, true)
    }
    pub(crate) fn checked(&self, mode: LinearSolveMode) -> StructuralSolution {
        self.checked_with(mode, &self.macros)
    }
}

/// max over free rows of |u − u_int| / (1e-9·max(|u_int|, S*_kind(u_int))),
/// one body, S* per D1 §4.1.6.1 items 4–6 (the design's actual-error measure).
fn actual_ratio(m: &ModelData, u: &[f64]) -> f64 {
    assert!(!m.u_int.is_empty(), "{}: no reference", m.name);
    let (mut st, mut sr) = (0.0_f64, 0.0_f64);
    for &(d, v) in m.u_int {
        if d % 6 < 3 {
            st = st.max(v.abs());
        } else {
            sr = sr.max(v.abs());
        }
    }
    let mut d = [0.0; 3];
    for (k, dk) in d.iter_mut().enumerate() {
        let hi = m.nodes.iter().map(|p| p[k]).fold(f64::MIN, f64::max);
        let lo = m.nodes.iter().map(|p| p[k]).fold(f64::MAX, f64::min);
        *dk = hi - lo;
    }
    let l_b = ((d[0] * d[0] + d[1] * d[1]) + d[2] * d[2]).sqrt();
    let (tr, ro) = (st.max(l_b * sr), sr.max(st / l_b));
    m.u_int
        .iter()
        .map(|&(dof, v)| {
            let scale = v.abs().max(if dof % 6 < 3 { tr } else { ro });
            (u[dof] - v).abs() / (1e-9 * scale)
        })
        .fold(0.0, f64::max)
}

/// The required true positive's model (P1's 122 skew cantilever), for the
/// nonlinear-loop pins in `crate::s11k_tests`.
pub(crate) fn skew_122() -> Built {
    Built::from_model(&F122)
}
pub(crate) fn skew_122_rigid() -> &'static [usize] {
    F122.rigid
}

pub(crate) fn bits(u: &[f64]) -> Vec<u64> {
    u.iter().map(|v| v.to_bits()).collect()
}

/// A demoted solution differs from the ordinary one only in `quality` and
/// the separate record; values and every other report field are identical.
fn assert_demoted_only_in_quality(plain: &StructuralSolution, checked: &StructuralSolution) {
    assert_eq!(plain.report.quality, SolveQuality::Passed);
    assert_eq!(checked.report.quality, SolveQuality::Sensitive);
    assert_eq!(bits(&plain.displacements), bits(&checked.displacements));
    let mut report = checked.report.clone();
    report.quality = SolveQuality::Passed;
    assert_eq!(format!("{:?}", report), format!("{:?}", plain.report));
    assert!(checked.formation_check.is_some());
}

/// Not demoted: the solution is the ordinary one, byte for byte (D5C-3).
fn assert_unchanged(plain: &StructuralSolution, checked: &StructuralSolution) {
    assert_eq!(checked.formation_check, None);
    assert_eq!(bits(&plain.displacements), bits(&checked.displacements));
    assert_eq!(
        format!("{:?}", plain.report),
        format!("{:?}", checked.report)
    );
}

/// Records the measured numbers (visible with `--nocapture`, kept in the run records).
fn record(name: &str, mode: LinearSolveMode, actual: Option<f64>, checked: &StructuralSolution) {
    let trigger = checked
        .formation_check
        .as_ref()
        .map(|r| (r.ratio, r.global_dof));
    eprintln!(
        "kd5 {name} {mode:?} actual={actual:?} demoted={} trigger={trigger:?}",
        checked.formation_check.is_some()
    );
}

fn estimate(checked: &StructuralSolution) -> f64 {
    let record = checked.formation_check.as_ref().expect("demoted");
    assert_eq!(record.reason, FormationCheckReason::Estimate);
    record.ratio
}

fn unavailable_detail(checked: &StructuralSolution) -> String {
    match &checked.formation_check.as_ref().expect("demoted").reason {
        FormationCheckReason::FormationCheckUnavailable { detail } => detail.clone(),
        other => panic!("expected formation_check_unavailable, got {other:?}"),
    }
}

#[test]
fn kd5_required_true_positive_skew_cantilever_122_demotes_in_both_modes() {
    let built = Built::from_model(&F122);
    for mode in MODES {
        let plain = built.plain(mode);
        let actual = actual_ratio(&F122, &plain.displacements);
        // Precondition: main publishes Passed with a breach of the criterion.
        assert_eq!(plain.report.quality, SolveQuality::Passed, "{mode:?}");
        assert!(actual > 1.0, "{mode:?}: actual {actual}");
        let checked = built.checked(mode);
        record("F122", mode, Some(actual), &checked);
        assert_demoted_only_in_quality(&plain, &checked);
        // EF tracks the actual error (the quoted EF is half the trigger value).
        let ef = estimate(&checked) / 2.0;
        assert!(
            (ef / actual - 1.0).abs() < 1e-3,
            "{mode:?}: EF {ef} actual {actual}"
        );
    }
}

#[test]
fn kd5_skew_345_and_invented_m11_do_not_demote() {
    for model in [&F345, &M11] {
        let built = Built::from_model(model);
        for mode in MODES {
            let plain = built.plain(mode);
            assert_eq!(
                plain.report.quality,
                SolveQuality::Passed,
                "{} {mode:?}",
                model.name
            );
            let actual =
                (!model.u_int.is_empty()).then(|| actual_ratio(model, &plain.displacements));
            assert!(actual.is_none_or(|a| a < 0.5));
            let checked = built.checked(mode);
            record(model.name, mode, actual, &checked);
            assert_unchanged(&plain, &checked);
        }
    }
}

#[test]
fn kd5_d5c1_controls_demote_exactly_where_the_actual_error_exceeds_half_the_criterion() {
    // V1's probe D (solve error only: the spring sum is exact), probe C (a soft
    // spring partly absorbed by G*J/L) and an axis-aligned bending-soft member.
    let mut demoted = Vec::new();
    for model in [&PROBE_D, &PROBE_C, &BENDING_SOFT] {
        let built = Built::from_model(model);
        for mode in MODES {
            let plain = built.plain(mode);
            assert_eq!(
                plain.report.quality,
                SolveQuality::Passed,
                "{} {mode:?}",
                model.name
            );
            let actual = actual_ratio(model, &plain.displacements);
            let checked = built.checked(mode);
            record(model.name, mode, Some(actual), &checked);
            assert!(
                (actual - 0.5).abs() > 0.05,
                "{} {mode:?}: control too close to the boundary ({actual})",
                model.name
            );
            if actual > 0.5 {
                assert_demoted_only_in_quality(&plain, &checked);
                let ef = estimate(&checked) / 2.0;
                assert!(
                    (ef / actual - 1.0).abs() < 1e-3,
                    "{} {mode:?}: EF {ef} actual {actual}",
                    model.name
                );
                demoted.push(model.name);
            } else {
                assert_unchanged(&plain, &checked);
            }
        }
    }
    // Each class demotes in at least one mode (the controls are not vacuous).
    for name in ["PROBE_D", "PROBE_C", "BENDING_SOFT"] {
        assert!(demoted.contains(&name), "{name} never demoted: {demoted:?}");
    }
}

#[test]
fn kd5_realistic_elbows_e1_and_e6_do_not_demote() {
    for model in [&E1, &E6] {
        let built = Built::from_model(model);
        assert!(!built.macros.is_empty());
        for mode in MODES {
            let plain = built.plain(mode);
            assert_eq!(
                plain.report.quality,
                SolveQuality::Passed,
                "{} {mode:?}",
                model.name
            );
            let actual = actual_ratio(model, &plain.displacements);
            assert!(actual < 0.5);
            let checked = built.checked(mode);
            record(model.name, mode, Some(actual), &checked);
            assert_unchanged(&plain, &checked);
        }
    }
}

#[test]
fn kd5_skew_plane_elbow_cantilever_at_kx_8_5_demotes_in_both_modes() {
    let built = Built::from_model(&CSKEW_8_5);
    for mode in MODES {
        let plain = built.plain(mode);
        let actual = actual_ratio(&CSKEW_8_5, &plain.displacements);
        assert_eq!(plain.report.quality, SolveQuality::Passed, "{mode:?}");
        assert!(actual > 1.0, "{mode:?}: actual {actual}");
        let checked = built.checked(mode);
        record("CSKEW_8_5", mode, Some(actual), &checked);
        assert_demoted_only_in_quality(&plain, &checked);
        let ef = estimate(&checked) / 2.0;
        assert!(
            (ef / actual - 1.0).abs() < 1e-3,
            "{mode:?}: EF {ef} actual {actual}"
        );
    }
}

#[test]
fn kd5_curved_intended_element_uses_the_actual_chord() {
    // The k_X = 30 skew elbow with its binary64 centre moved 6.5e-10 R along
    // the chord: admissible to the product (radius mismatch 9.2e-10, tolerance
    // 1e-9), but the product's trigonometric chord R(cos φ − 1, R sin φ) is no
    // longer x_j − x_i, which adds about 0.4 of the criterion in both modes.
    // The check's H uses the actual chord, so EF tracks the actual error
    // (mutation 31b builds H from the product's chord and misses it). The
    // stiffness defect here is ~1e-9 relative, so EF's first-order agreement
    // is to a few per cent rather than 1e-3.
    let model = &CSKEW_30_RADIUS_MISMATCH;
    let built = Built::from_model(model);
    for mode in MODES {
        let plain = built.plain(mode);
        let actual = actual_ratio(model, &plain.displacements);
        assert_eq!(plain.report.quality, SolveQuality::Passed, "{mode:?}");
        assert!(actual > 0.7, "{mode:?}: actual {actual}");
        let checked = built.checked(mode);
        record(model.name, mode, Some(actual), &checked);
        assert_demoted_only_in_quality(&plain, &checked);
        let ef = estimate(&checked) / 2.0;
        assert!(
            (ef / actual - 1.0).abs() < 0.05,
            "{mode:?}: EF {ef} actual {actual}"
        );
    }
}

#[test]
fn kd5_admissible_centre_mismatch_demotes_where_the_product_chord_hides_the_error() {
    // RV5-B1 (the M31b counterexample, RV5's admissible inputs): one realized
    // bend on a cantilever with stiff root springs and a tip moment (1, 1, 1),
    // its binary64 centre moved along the chord to the edge of the product's
    // radius-match tolerance (1e-9). Planar 60° and skew 30°. The chord error
    // gives a first-order translation error at node 1 above the criterion,
    // which the check sees because its H uses the actual chord x_j − x_i.
    // Mutation 31b (H from the product's chord R(cos φ − 1), R sin φ) sees
    // none of it and fails the demotion assertion below.
    for model in [&CPLANAR_60, &CSKEW_30_N122] {
        let built = Built::from_model(model);
        for mode in MODES {
            let plain = built.plain(mode);
            let actual = actual_ratio(model, &plain.displacements);
            // Preconditions: main publishes Passed, and its published error
            // against the exact intended solution is above the criterion.
            assert_eq!(
                plain.report.quality,
                SolveQuality::Passed,
                "{} {mode:?}",
                model.name
            );
            assert!(actual > 1.0, "{} {mode:?}: actual {actual}", model.name);
            let checked = built.checked(mode);
            record(model.name, mode, Some(actual), &checked);
            assert_demoted_only_in_quality(&plain, &checked);
            let ef = estimate(&checked) / 2.0;
            assert!(
                (ef / actual - 1.0).abs() < 0.05,
                "{} {mode:?}: EF {ef} actual {actual}",
                model.name
            );
        }
    }
}

#[test]
fn kd5_large_coordinate_pp_route_elbow_does_not_demote() {
    // RV5-B1's PP-route elbow at X = 5e5 m (R = 0.3 m, φ = 2°), its centre
    // computed as PP computes it: no designed mismatch. Against the exact
    // intended solution (exact binary64 inputs) the product's published error
    // is about 0.04 of the criterion, so a correct check leaves it Passed and
    // unchanged (ordinary large-coordinate elbows are not falsely demoted).
    let model = &PP_UTM_2;
    let built = Built::from_model(model);
    for mode in MODES {
        let plain = built.plain(mode);
        let actual = actual_ratio(model, &plain.displacements);
        assert_eq!(plain.report.quality, SolveQuality::Passed, "{mode:?}");
        assert!(actual < 0.5, "{mode:?}: actual {actual}");
        let checked = built.checked(mode);
        record(model.name, mode, Some(actual), &checked);
        assert_unchanged(&plain, &checked);
    }
}

#[test]
fn kd5_curved_matching_is_order_independent() {
    let built = Built::from_model(&E6);
    assert_eq!(built.macros.len(), 4);
    let mut reversed = built.macros.clone();
    reversed.reverse();
    for mode in MODES {
        let forward = built.checked(mode);
        let backward = built.checked_with(mode, &reversed);
        assert_eq!(forward.formation_check, None);
        assert_eq!(backward.formation_check, None);
        assert_eq!(bits(&forward.displacements), bits(&backward.displacements));
        assert_eq!(
            format!("{:?}", forward.report),
            format!("{:?}", backward.report)
        );
    }
}

#[test]
fn kd5_unmatched_explicit_and_one_ulp_curved_slots_fail_closed() {
    let base = Built::from_model(&E1);
    for mode in MODES {
        // Precondition: matched, E1 publishes Passed and is not demoted.
        let plain = base.plain(mode);
        assert_unchanged(&plain, &base.checked(mode));
        // (a) No macro element supplied for the slot.
        let unmatched = base.checked_with(mode, &[]);
        assert_demoted_only_in_quality(&plain, &unmatched);
        assert!(unavailable_detail(&unmatched).starts_with("curved_bend_source_unmatched:"));
        // (b) An explicit slot with the same matrix (no traced macro source).
        let mut explicit = Built::from_model(&E1);
        explicit.slots = explicit
            .slots
            .iter()
            .map(|s| {
                CurvedBendStiffnessElement::new(
                    s.element_id.clone(),
                    s.node_i,
                    s.node_j,
                    s.global_stiffness,
                )
                .unwrap()
            })
            .collect();
        let explicit_result = explicit.checked(mode);
        assert_demoted_only_in_quality(&explicit.plain(mode), &explicit_result);
        assert!(unavailable_detail(&explicit_result).starts_with("curved_bend_explicit_matrix:"));
        // (c) A slot whose matrix differs by one ulp from its macro element's.
        let mut ulp = Built::from_model(&E1);
        let slot = &mut ulp.slots[0];
        let old = slot.global_stiffness[2][2];
        let new = f64::from_bits(old.to_bits() + 1);
        slot.global_stiffness[2][2] = new;
        let map = element_dof_map(slot.node_i, slot.node_j);
        ulp.k[map[2]][map[2]] = ulp.k[map[2]][map[2]] - old + new;
        let ulp_plain = ulp.plain(mode);
        assert_eq!(ulp_plain.report.quality, SolveQuality::Passed);
        let ulp_result = ulp.checked(mode);
        assert_demoted_only_in_quality(&ulp_plain, &ulp_result);
        assert!(unavailable_detail(&ulp_result).starts_with("curved_bend_source_unmatched:"));
    }
}

#[test]
fn kd5_not_selected_invocation_runs_the_unchanged_solve_assembled() {
    // ROOT: an invocation with a nonlinear support is never selected. The
    // selected path demotes 122 (precondition: the paths differ); the
    // unselected path is `solve_assembled`, bit for bit.
    let built = Built::from_model(&F122);
    for mode in MODES {
        let plain = built.plain(mode);
        assert_eq!(plain.report.quality, SolveQuality::Passed, "{mode:?}");
        let selected = built.checked_selected(mode, &built.macros, true);
        assert_eq!(selected.report.quality, SolveQuality::Sensitive, "{mode:?}");
        let unselected = built.checked_selected(mode, &built.macros, false);
        assert_eq!(unselected, plain);
    }
}

// ------------------------------------------------------------------ T4-U3 (S10, S-3)

/// T4-I12 round 02 U3-KD5-UTM-SKEW-OFFSET-COUPLED (case 22) at X0: binary64
/// offsets with tails below the UTM grid, the binary64 rounding of a
/// rational skew rotation, U3-GENERIC's coupled PD H at Ls = 1/4 m.
fn case22(x0: f64) -> ObjectiveConnector {
    use open_pipe_stress_frame_kernel::connector::{ConnectorAttachment, ScaledWorkMatrix};
    let (third, two_thirds) = (1.0 / 3.0, 2.0 / 3.0);
    ObjectiveConnector::new(
        FrameNode::new(0, [x0 + 0.5, -1.25, 2.0]).unwrap(),
        FrameNode::new(1, [x0 + 1.8125, 0.8125, 3.375]).unwrap(),
        ConnectorAttachment::global([0.2, 0.4, -0.2]),
        ConnectorAttachment::global([-0.1, 0.3625, 0.44999999999999996]),
        [
            [third, two_thirds, -two_thirds],
            [two_thirds, third, two_thirds],
            [two_thirds, -two_thirds, -third],
        ],
        ScaledWorkMatrix {
            upper_triangle: [
                12500.0, 625.0, 0.0, 0.0, 500.0, 0.0, 9375.0, 312.5, 0.0, 0.0, -750.0, 7500.0,
                250.0, 0.0, 0.0, 800.0, 50.0, 0.0, 900.0, 100.0, 1200.0,
            ],
            translation_scale: 0.25,
        },
        [
            0.0009765625,
            -0.00048828125,
            0.000244140625,
            0.001953125,
            0.0,
            -0.0009765625,
        ],
    )
    .unwrap()
}

/// The connector alone, end j held, loads at end i; with `perturbed`, the
/// assembled matrix only gets δ = 2^-20·max|Ke| at its largest diagonal
/// (k = 3), never the evidence or K-D5's re-formation.
fn connector_model(x0: f64, perturbed: bool) -> Built {
    let connector = case22(x0);
    let ke = connector.global_stiffness().unwrap();
    let max = ke.iter().flatten().fold(0.0_f64, |m, v| m.max(v.abs()));
    assert_eq!(ke[3][3], max);
    let mut built = Built {
        frames: Vec::new(),
        connectors: vec![connector],
        macros: Vec::new(),
        slots: Vec::new(),
        springs: Vec::new(),
        node_count: 2,
        k: vec![vec![0.0; 12]; 12],
        f: vec![0.0; 12],
        free: Vec::new(),
        prescribed: Vec::new(),
    };
    built.scatter(0, 1, &ke);
    if perturbed {
        built.k[3][3] += max * 2f64.powi(-20);
    }
    built.f[..6].copy_from_slice(&[1000.0, -2000.0, 1500.0, 300.0, -200.0, 100.0]);
    built.set_boundary(&[6, 7, 8, 9, 10, 11]);
    built
}

/// S-3 (RV130), case 22: undemoted at X0 = 0 (the ordinary twin), 5e6 and
/// 7.3e6 m in both modes. Perturbing only the assembled matrix is refused
/// here before K-D5 runs: the adapter's M03 contribution audit sees the
/// matrix differ from its own contributions. (K-D5's demotion of the same
/// perturbation, with no contribution evidence, is pinned in FK
/// `formation_check_tests` (dense) and SD `k1_tests` (sparse).)
#[test]
fn kd5_connector_case_22_is_not_demoted_at_utm_and_its_perturbed_matrix_is_refused() {
    for x0 in [0.0, 5.0e6, 7.3e6] {
        let control = connector_model(x0, false);
        let perturbed = connector_model(x0, true);
        for mode in MODES {
            let plain = control.plain(mode);
            assert_eq!(
                plain.report.quality,
                SolveQuality::Passed,
                "X0 {x0} {mode:?}"
            );
            let checked = control.checked(mode);
            record("connector-22", mode, None, &checked);
            assert_unchanged(&plain, &checked);
            let refused = perturbed.assembly().solve_assembled_with_formation_check(
                &perturbed.k,
                &perturbed.ledger(),
                &perturbed.free,
                &perturbed.prescribed,
                mode,
                &[],
                true,
            );
            assert!(refused.is_err(), "X0 {x0} {mode:?}: {refused:?}");
        }
    }
}
