import pathlib,csv,json,hashlib,collections
P=pathlib.Path(__file__).parent
def sha(q):return hashlib.sha256(q.read_bytes()).hexdigest()
def read(q):return list(csv.DictReader(q.open()))
def write(q,rs):
 with q.open('w') as f:
  w=csv.DictWriter(f,fieldnames=list(rs[0]),lineterminator='\n');w.writeheader();w.writerows(rs)
inv={x['DeliverableID']:x for x in json.loads((P/'MANAGER_INVENTORY.json').read_text())}
res=read(P/'PACKAGE_RESIDUALS.csv');summary=read(P/'PACKAGE_SUMMARY.csv');claims=read(P/'PACKAGE_CLAIMS.csv');cids={x['ClaimID'] for x in claims}
held={'DEL-10-02-REM-003':'HELD_OWNER_RELEASE_AUTHORITY','DEL-10-02-REM-004':'HELD_UPSTREAM_INTERPRETATION','DEL-10-03-REM-002':'HELD_OWNER_RELEASE_AUTHORITY','DEL-10-03-REM-003':'HELD_OWNER_ATTRIBUTION_CONFIRMATION','DEL-10-03-REM-004':'HELD_DOCUMENTARY_AUTHORITY_CORRECTION','DEL-10-05-REM-002':'HELD_DOCUMENTARY_DEPENDENCY_CORRECTION','DEL-10-08-REM-002':'HELD_DUPLICATIVE_CONTRACT_ADMIN_ROUTE','DEL-10-10-REM-003':'HELD_OWNER_RELEASE_AUTHORITY','DEL-10-10-REM-004':'HELD_UPSTREAM_INTERPRETATION','DEL-10-10-REM-005':'HELD_FUTURE_REVIEW_ACCEPTANCE','DEL-10-10-REM-006':'HELD_DOCUMENTARY_PROVENANCE_CORRECTION','DEL-10-11-REM-002':'HELD_OWNER_INPUT_DENOMINATOR_READINGS','DEL-10-11-REM-003':'HELD_OWNER_PURPOSE_PUBLICATION_READINGS'}
rows=[]
for r in res:
 d=r['DeliverableID'];target=pathlib.Path(inv[d]['DeliverablePath'])/'_STATUS.md';group=held.get(r['ResidualID'],'RECOMMENDED_EVIDENCE_CANDIDATE')
 rows.append({'ResidualID':r['ResidualID'],'DeliverableID':d,'ClaimIDs':r['ClaimIDs'],'RoutingGroup':group,'RecommendedForRemainingProposal':'NO' if r['ResidualID'] in held else 'YES_EVIDENCE_FIRST_ONLY','TargetStatusPath':str(target),'CurrentStatusSHA256':sha(target),'ProposedText':r['ProposedText'],'Depends':r['Depends'],'ExactGate':r['ExactGate'],'ClosureEvidence':r['ClosureEvidence'],'AuthorityNeeded':r['AuthorityNeeded'],'Selectability':r['Selectability'],'Notes':'Raw source-bound proposal retained. UNKNOWN is not proven absence. No application authority; source/contract/owner/lifecycle grants remain. '+r['Notes']})
write(P/'R4_ROUTING.csv',rows)
lines=['# PKG-10 R4 decision candidates','', 'Derivative proposal basis: D82 effective2be412ccea62bdc4bd96deb082c46d7a792076ea, accepted D81 conventions, current revision1.4 decomposition and selected independently verified ledgers. This report neither replaces accepted scope nor applies Remaining.','',f'{len(rows)} raw proposals retained: {sum(r["RecommendedForRemainingProposal"].startswith("YES") for r in rows)} recommended evidence-first Remaining candidates and {len(held)} held owner/interpretive/documentary/admin/future-review routes. No unconditional implementation task is inferred from UNKNOWN. The exact candidate texts, carrier paths/current hashes, claim populations, Depends, gates, closure evidence and authority are in R4_ROUTING.csv.','', 'The evidence candidates first locate and bind existing artifacts or establish their current evidence boundary. Production follows only a separate exact source grant if needed. Later application must use exact pre/post status bytes and rollback under owner ruling; no source, lifecycle, history or Last Updated edits are authorized here. Synthesis owns the cross-package exact application packet; this package supplies exact candidate rows, not an applied status image.','', 'Held rows remain visible and nonselectable. Documentary current-assertion findings do not reopen ordinary SCA004 currency. Historical authoring/measurement/acceptance statements are preserved as historical; future owner review is not a failed current acceptance. No automatic Task Management mirror. TM023 dedicated mapping held, TM022 deferred, PRDv2.3/DPEC79 adopted-not-applied.','', 'DEL10-01 warranted NONE is limited to its accepted before-leg baseline scope; it creates neither a Remaining section nor an issue/release state. The other eleven members remain ASSESSED_UNKNOWN even when known proposal rows are present.','']
for r in rows:
 lines += [f'## {r["ResidualID"]} — {r["RoutingGroup"]}', '',r['ProposedText'],'',f'Depends: {r["Depends"]}. {r["ExactGate"]}', '',f'Carrier: `{r["TargetStatusPath"]}` SHA256 `{r["CurrentStatusSHA256"]}`. Claims: {r["ClaimIDs"]}.','']
(P/'R4_DECISION_CANDIDATES.md').write_text('\n'.join(lines)+'\n')
cf=[]
def add(id,own,other,scope,src,finding,route):
 assert all(x in cids for x in own.split(';')),own
 cf.append({'FindingID':id,'PackageID':'PKG-10','ClaimIDs':own,'RelatedDeliverables':other,'ScopeItemIDs':scope,'SourceReferences':src,'Finding':finding,'Routing':route,'Selectability':'NON_SELECTABLE_PENDING_OWNER_APPLICATION'})
base='projects/pec/execution/_Decomposition/'
add('PKG10-X001','DEL-10-01::AC-008;DEL-10-01::CLM-010;DEL-10-01::CLM-011','DEL-04-01;DEL-08-04','SOW-058',base+'ScopeLedger.csv:SOW-058; D-PEC-72 accepted exact baseline/telemetry and C05 closure','Historical accepted before-leg baseline and separate C05 closure remain; consumers do not create a new after-measurement obligation for DEL10-01.','HELP_HUMAN preserve accepted chronology; no downstream dependency-register flip.')
add('PKG10-X002','DEL-10-02::AC-013;DEL-10-03::AC-009;DEL-10-10::AC-015','DEL-01-05','SOW-055;SOW-025;SOW-064','Each exact ScopeOfWork AC; D77 policy','Exact release force for kill/no-ruling-write/bootstrap checks is not supplied by DEL01-05-specific G-A policy; finite checks and owner gating distinct.','HELP_HUMAN held owner decisions; no invented release process.')
add('PKG10-X003','DEL-10-03::REQ-002;DEL-10-03::AC-002','DEL-08-01;DEL-08-02','SOW-025',base+'ScopeLedger.csv:SOW-025; exact DEL10-03 contract; D74 schema acceptance','Accepted API schema compatibility bytes do not establish listener/runtime no-ruling-write negative tests; named pending prerequisites preserved.','HELP_HUMAN source/evidence candidate; no accepted-byte or lifecycle reversal.')
add('PKG10-X004','DEL-10-05::SOW-085.NO_DUTY;DEL-10-12::SOW-060-01;DEL-10-12::SOW-060-02','DEL-01-04;DEL-04-01;DEL-07-03;DEL-08-01;DEL-09-01','SOW-085;SOW-060',base+'ScopeLedger.csv:SOW-085/SOW-060; current PRD v2.2','Owner use/non-use and consumer enablement/conditional use preserve consumer-owned contact opportunities; legacy labels/quotes cannot impose polling or consultation duties.','HELP_HUMAN preserve SCA003/current consumer boundary; held exact documentary correction separate.')
add('PKG10-X005','DEL-10-08::SOW-063-DEMONSTRATION','DEL-03-05;DEL-07-01','SOW-038;SOW-063',base+'ScopeLedger.csv:SOW-038/SOW-063; Deliverables.csv:DEL-03-05/DEL-10-08','Recovery mechanism DEL03-05 is distinct from PKG10 P4 demonstration. One does not discharge the other; current demonstration remains UNKNOWN.','HELP_HUMAN cross-package evidence mapping; no new upstream duties.')
add('PKG10-X006','DEL-10-11::CLM-008;DEL-10-11::CLM-015;DEL-10-11::AC-014;DEL-10-11::AC-015','DEL-03-03;DEL-03-04','SOW-019;SOW-020;SOW-093',base+'ScopeLedger.csv:SOW-020/SOW-093; exact DEL10-11 contract','Parity behavior DEL03-04 and successive-snapshot classification DEL03-03 are distinct producers; PKG10 metric cannot invent input discriminator, denominator, purpose or gate force.','HELP_HUMAN held owner readings plus evidence-first metric candidate.')
add('PKG10-X007','DEL-10-10::REQ-007;DEL-10-10::REQ-008;DEL-10-10::REQ-009;DEL-10-10::CLM-009','DEL-02-05;DEL-03-01','SOW-064',base+'ScopeLedger.csv:SOW-064; DEL10-10 ScopeOfWork/Dependencies.csv','Bootstrap record evidence remains UNKNOWN; predecessor-only accepted capability use and friction/negative dispositions create no scope or authority. Narrow CLM009 provenance mismatch does not change pending prerequisites.','HELP_HUMAN evidence-first candidate; exact documentary route held.')
write(P/'CROSS_PACKAGE_FINDINGS.csv',cf)
print(json.dumps({'raw':len(rows),'recommended':sum(r['RecommendedForRemainingProposal'].startswith('YES') for r in rows),'held':len(held),'cross_package_findings':len(cf)},indent=2))
