#!/usr/bin/env python3
"""Build the curated chirality-app release-projection staging tree."""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import re
import shutil
import sys
from pathlib import Path


PROFILE_DIR = Path(__file__).resolve().parent
REPO_ROOT = PROFILE_DIR.parents[1]
DEFAULT_STAGE = PROFILE_DIR / "staging"
MANIFEST_PATH = PROFILE_DIR / "export-manifest.csv"
REPORT_PATH = PROFILE_DIR / "export-report.md"

ROOT_FILES = [
    ".gitignore",
    "AGENTS.md",
    "CLAUDE.md",
    "LICENSE.md",
]

PUBLIC_ROOT_FILES = {
    "README.md": PROFILE_DIR / "PUBLIC_README.md",
    "execution/_Coordination/AgentRuns/CHIRALITY_V3_ADOPTION_20260909/skill-execution-provenance.json": (
        REPO_ROOT
        / "execution/_Coordination/AgentRuns/CHIRALITY_V3_ADOPTION_20260909/skill-execution-provenance.json"
    ),
}

ROOT_DIRS = [
    ".github",
    "agents",
    "workflows",
    "tools",
    "docs",
    "init",
]

# Preserve the public runtime/ projection while its canonical workspace lives
# in a project. Only software workspace members export, never project custody.
RUNTIME_ROOT = REPO_ROOT / "projects" / "chirality-runtime"
RUNTIME_FILES = ["README.md", "package.json", "package-lock.json", "tsconfig.json", "tsconfig.base.json"]
RUNTIME_DIRS = ["packages", "tests"]

EXCLUDED_PUBLIC_PATHS = {
    ".github/workflows/harness-premerge.yml",
    "tools/practitioner_harness/BACKLOG.md",
    # Non-release loop entrypoints: the release init prompt is generated by
    # write_public_init_prompt; loop launchers never export.
    "init/dev-loop-init-prompt.md",
    "init/taskmgmt-init-prompt.md",
    "init/piping-resume-one-time.md",
}

EXCLUDED_PUBLIC_PREFIXES = (
    "docs/governance_harness/briefs/",
    ".agents/skills/chirality-change/",
)

BUNDLED_SKILL_NAMES = {
    "deliverable-consistency",
    "drawing-titleblock-page",
    "preparation",
    "proposal-format",
    "researcher",
    "software-code-review",
    "software-defect-diagnosis",
}
EXCLUDED_SKILL_NAMES = {"chirality-change"}

SKIP_DIRS = {
    ".git",
    ".Archive",
    ".archive",
    ".claude",
    ".chirality",
    ".checkpoints",
    ".pytest_cache",
    "__pycache__",
    ".mypy_cache",
    ".ruff_cache",
    "node_modules",
    ".next",
    "dist",
    "dist-electron",
    "build",
    "target",
    "out",
    "artifacts",
    "_Sources",
    "_LocalIndexes",
    "migration",
    "projects",
    "domains",
    "plans",
    "exports",
}

SKIP_FILE_NAMES = {
    ".DS_Store",
}

SKIP_SUFFIXES = {
    ".pyc",
    ".pyo",
    ".zip",
    ".pdf",
    ".PDF",
    ".tsbuildinfo",
}

TEXT_SUFFIXES = {
    ".cjs",
    ".css",
    ".csv",
    ".html",
    ".js",
    ".json",
    ".jsx",
    ".md",
    ".mjs",
    ".plist",
    ".py",
    ".sh",
    ".toml",
    ".ts",
    ".tsx",
    ".txt",
    ".yaml",
    ".yml",
}

PUBLIC_REPLACEMENTS = [
    ("/Users/ryan/ai-env/projects/chirality-app-test/test/", "examples/"),
    ("/Users/ryan/ai-env/projects/chirality-app-test/", "<legacy-chirality-app-test>/"),
    ("/Users/ryan/ai-env/projects/chirality-app-dev/", "<legacy-chirality-app-dev>/"),
    ("/Users/ryan/ai-env/projects/chirality-piping/", "<legacy-chirality-piping>/"),
    ("/Users/ryan/ai-env/projects/chirality-app", "<chirality-app-root>"),
    ("/Users/ryan/ai-env/projects/chirality", "<chirality-root>"),
]

PUBLIC_README_REQUIRED_MARKERS = (
    "https://github.com/sgttomas/chirality-app/releases/latest",
    "The desktop application source is not currently included",
    "curated Chirality desktop release projection",
    "runtime/",
)

PUBLIC_README_FORBIDDEN_MARKERS = (
    "This repository is the private canonical source tree",
    "## Private Canonical Repository",
    "Private maintainer and development roots",
    "projects/chirality-app-dev",
    "exports/chirality-app",
)


def should_skip(path: Path) -> bool:
    if any(part in SKIP_DIRS for part in path.parts):
        return True
    if path.name in SKIP_FILE_NAMES:
        return True
    if path.suffix in SKIP_SUFFIXES:
        return True
    if path.name.startswith(".env"):
        return True
    return False


def resolve_potential_path(value: Path) -> Path:
    cursor = value.absolute()
    suffix: list[str] = []
    while not cursor.exists() and not cursor.is_symlink():
        parent = cursor.parent
        if parent == cursor:
            break
        suffix.append(cursor.name)
        cursor = parent
    return cursor.resolve(strict=True).joinpath(*reversed(suffix))


def paths_overlap(left: Path, right: Path) -> bool:
    return left == right or left in right.parents or right in left.parents


def require_source_path(source: Path, *, expect_directory: bool) -> Path:
    lexical_repo = REPO_ROOT.absolute()
    lexical_source = source.absolute()
    try:
        relative_source = lexical_source.relative_to(lexical_repo)
    except ValueError as exc:
        raise SystemExit(f"export source escapes canonical repository: {source}") from exc
    cursor = lexical_repo
    if cursor.is_symlink():
        raise SystemExit(f"refusing symlinked canonical repository root: {REPO_ROOT}")
    for segment in relative_source.parts:
        cursor /= segment
        if cursor.is_symlink():
            raise SystemExit(f"refusing export source with symlinked path component: {cursor}")
    canonical_repo = REPO_ROOT.resolve(strict=True)
    canonical_source = source.resolve(strict=True)
    if not canonical_source.is_relative_to(canonical_repo):
        raise SystemExit(f"export source escapes canonical repository: {source}")
    if expect_directory and not canonical_source.is_dir():
        raise SystemExit(f"export source is not a directory: {source}")
    if not expect_directory and not canonical_source.is_file():
        raise SystemExit(f"export source is not a regular file: {source}")
    return canonical_source


def admit_stage_path(stage: Path) -> None:
    lexical_stage = stage.absolute()
    canonical_stage = resolve_potential_path(stage)
    lexical_default = DEFAULT_STAGE.absolute()
    canonical_default = resolve_potential_path(DEFAULT_STAGE)
    if stage.is_symlink():
        raise SystemExit(f"refusing symlinked export stage: {stage}")
    if stage.exists() and not stage.is_dir():
        raise SystemExit(f"export stage is not a directory: {stage}")
    if lexical_stage == lexical_default and canonical_stage == canonical_default:
        return
    if paths_overlap(lexical_stage, REPO_ROOT.absolute()) or paths_overlap(
        canonical_stage, REPO_ROOT.resolve(strict=True)
    ):
        raise SystemExit(f"refusing export stage that overlaps the canonical repository: {stage}")


def admit_fixed_profile_output(output: Path, expected: Path) -> None:
    lexical_profile = PROFILE_DIR.absolute()
    lexical_output = output.absolute()
    if lexical_output != expected.absolute():
        raise SystemExit(f"refusing unexpected export metadata output: {output}")
    try:
        relative_output = lexical_output.relative_to(lexical_profile)
    except ValueError as exc:
        raise SystemExit(f"export metadata output escapes profile: {output}") from exc
    cursor = lexical_profile
    if cursor.is_symlink():
        raise SystemExit(f"refusing symlinked export profile root: {PROFILE_DIR}")
    for segment in relative_output.parts:
        cursor /= segment
        if cursor.is_symlink():
            raise SystemExit(f"refusing export metadata output with symlinked path component: {cursor}")
    if output.parent.resolve(strict=True) != PROFILE_DIR.resolve(strict=True):
        raise SystemExit(f"export metadata output parent escapes profile: {output}")
    if output.exists() and not output.is_file():
        raise SystemExit(f"export metadata output is not a regular file: {output}")


def copy_source_file(src: Path, dest: Path) -> None:
    canonical_src = require_source_path(src, expect_directory=False)
    dest.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(canonical_src, dest)


def copy_tree(src: Path, dest: Path, root_name: str) -> None:
    canonical_src = require_source_path(src, expect_directory=True)
    for path in src.rglob("*"):
        if path.is_symlink():
            raise SystemExit(f"refusing symlinked export source entry: {path}")
        canonical_path = path.resolve(strict=True)
        if not canonical_path.is_relative_to(canonical_src):
            raise SystemExit(f"export source entry escapes its declared root: {path}")
        rel = path.relative_to(src)
        public_rel = (Path(root_name) / rel).as_posix()
        if public_rel in EXCLUDED_PUBLIC_PATHS or public_rel.startswith(EXCLUDED_PUBLIC_PREFIXES):
            continue
        if should_skip(rel):
            if path.is_dir():
                continue
            continue
        target = dest / rel
        if path.is_dir():
            target.mkdir(parents=True, exist_ok=True)
        elif path.is_file():
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(path, target)
        else:
            raise SystemExit(f"refusing unsupported export source entry: {path}")


def write_public_init_prompt(stage: Path) -> None:
    target = stage / "init" / "init-prompt.md"
    # All non-release launchers are excluded from the wholesale init/ copy, so
    # the staged directory may not exist yet.
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(
        """# Public session init prompt

This release projection does not include project loop entrypoints. Start
from the target workspace and select an Agent 0 or Agent 1 role from
`AGENTS.md`.

<init-prompt>
Resolve `REPO_ROOT` with `git rev-parse --show-toplevel`.

Read `{REPO_ROOT}/AGENTS.md`, then read the selected instruction package under
`{REPO_ROOT}/agents/`.

State the target workspace, objective, accepted basis, authority, read scope,
write scope, tools, expected return, and human decision points before acting.
</init-prompt>
""",
        encoding="utf-8",
    )


def sanitize_text_files(stage: Path) -> int:
    changed = 0
    for path in stage.rglob("*"):
        if not path.is_file() or path.suffix not in TEXT_SUFFIXES:
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        updated = text
        for old, new in PUBLIC_REPLACEMENTS:
            updated = updated.replace(old, new)
        if updated != text:
            path.write_text(updated, encoding="utf-8")
            changed += 1
    return changed


def build_stage(stage: Path) -> int:
    missing = [name for name in ROOT_FILES + ROOT_DIRS if not (REPO_ROOT / name).exists()]
    missing.extend(
        str((RUNTIME_ROOT / name).relative_to(REPO_ROOT))
        for name in RUNTIME_FILES + RUNTIME_DIRS
        if not (RUNTIME_ROOT / name).exists()
    )
    if not (REPO_ROOT / ".agents" / "skills").is_dir():
        missing.append(".agents/skills")
    missing.extend(
        str(source.relative_to(REPO_ROOT))
        for source in PUBLIC_ROOT_FILES.values()
        if not source.exists()
    )
    if missing:
        raise SystemExit(
            "allowlisted roots missing from repo root: "
            + ", ".join(missing)
            + "; update ROOT_FILES/ROOT_DIRS to match the tree"
        )

    claude_contract = require_source_path(
        REPO_ROOT / "CLAUDE.md", expect_directory=False
    ).read_text(encoding="utf-8")
    if claude_contract != "@AGENTS.md\n":
        raise SystemExit("CLAUDE.md must contain exactly '@AGENTS.md\\n'")

    admit_stage_path(stage)
    if stage.exists():
        shutil.rmtree(stage)
    stage.mkdir(parents=True)

    for name in ROOT_FILES:
        copy_source_file(REPO_ROOT / name, stage / name)

    for public_name, source in PUBLIC_ROOT_FILES.items():
        copy_source_file(source, stage / public_name)

    for name in ROOT_DIRS:
        copy_tree(REPO_ROOT / name, stage / name, name)

    skill_root = REPO_ROOT / ".agents" / "skills"
    require_source_path(skill_root, expect_directory=True)
    actual_skills = {path.name for path in skill_root.iterdir() if path.is_dir()}
    expected_skills = BUNDLED_SKILL_NAMES | EXCLUDED_SKILL_NAMES
    if actual_skills != expected_skills:
        raise SystemExit(
            "canonical skill membership mismatch: "
            f"missing={sorted(expected_skills - actual_skills)}, "
            f"unexpected={sorted(actual_skills - expected_skills)}"
        )
    for name in sorted(BUNDLED_SKILL_NAMES):
        copy_tree(skill_root / name, stage / ".agents" / "skills" / name, f".agents/skills/{name}")
    index_path = stage / "workflows" / "index.json"
    index = json.loads(index_path.read_text(encoding="utf-8"))
    if index.get("schema") != "chirality-method-index/v1" or not isinstance(index.get("methods"), list):
        raise SystemExit("workflows/index.json must use chirality-method-index/v1")
    filtered_methods = [
        item for item in index["methods"]
        if not (item.get("kind") == "skill" and item.get("name") == "chirality-change")
    ]
    if len(filtered_methods) != len(index["methods"]):
        index["methods"] = filtered_methods
        index_path.write_text(json.dumps(index, indent=2) + "\n", encoding="utf-8")

    runtime_stage = stage / "runtime"
    runtime_stage.mkdir(parents=True)
    for name in RUNTIME_FILES:
        copy_source_file(RUNTIME_ROOT / name, runtime_stage / name)
    for name in RUNTIME_DIRS:
        copy_tree(RUNTIME_ROOT / name, runtime_stage / name, f"runtime/{name}")

    (stage / 'ADOPTION_HOLD.json').write_text(json.dumps({
        'schema_version': 1, 'status': 'HELD',
        'basis': 'D-GOV-41 four-role replacement',
        'reason': 'App and Runtime must adopt registry, workflow loading, role routing and compatibility together.',
        'required_consumers': ['chirality-app', 'chirality-runtime']
    }, indent=2) + '\n')
    write_public_init_prompt(stage)

    return sanitize_text_files(stage)


def iter_files(root: Path):
    for path in sorted(root.rglob("*")):
        if path.is_file():
            yield path


def write_manifest(stage: Path, output: Path) -> int:
    admit_fixed_profile_output(output, MANIFEST_PATH)
    rows = []
    for path in iter_files(stage):
        rel = path.relative_to(stage).as_posix()
        data = path.read_bytes()
        rows.append(
            {
                "path": rel,
                "size_bytes": str(len(data)),
                "sha256": hashlib.sha256(data).hexdigest(),
            }
        )
    with output.open("w", encoding="utf-8", newline="") as fh:
        writer = csv.DictWriter(
            fh,
            fieldnames=["path", "size_bytes", "sha256"],
            lineterminator="\n",
        )
        writer.writeheader()
        writer.writerows(rows)
    return len(rows)


def boundary_findings(stage: Path) -> list[str]:
    findings: list[str] = []
    public_readme = stage / "README.md"
    if not public_readme.is_file():
        findings.append("public README is missing: README.md")
    else:
        public_readme_text = public_readme.read_text(encoding="utf-8")
        for marker in PUBLIC_README_REQUIRED_MARKERS:
            if marker not in public_readme_text:
                findings.append(f"public README missing required marker: {marker}")
        for marker in PUBLIC_README_FORBIDDEN_MARKERS:
            if marker.casefold() in public_readme_text.casefold():
                findings.append(f"private canonical README marker in public README: {marker}")

    forbidden_top = {"projects", "domains", "migration", "plans", "exports"}
    for path in stage.rglob("*"):
        rel = path.relative_to(stage).as_posix()
        parts = path.relative_to(stage).parts
        if parts and parts[0] in forbidden_top:
            findings.append(f"forbidden top-level path: {rel}")
        if path.is_dir() and path.name in SKIP_DIRS:
            findings.append(f"forbidden directory: {rel}")
        if path.is_file():
            if path.name in SKIP_FILE_NAMES or path.name.startswith(".env") or path.suffix in {".pyc", ".zip", ".pdf", ".PDF", ".tsbuildinfo"}:
                findings.append(f"forbidden file: {rel}")
            if path.suffix in TEXT_SUFFIXES:
                try:
                    text = path.read_text(encoding="utf-8")
                except UnicodeDecodeError:
                    continue
                private_home = re.search(
                    r"(?:/Users/|/home/)(?!<|example(?:/|\b)|fixture(?:/|\b))[^/\s`]+/",
                    text,
                ) or re.search(
                    r"[A-Za-z]:\\Users\\(?!example(?:\\|\b)|fixture(?:\\|\b))[^\\\s`]+\\",
                    text,
                )
                if private_home:
                    findings.append(f"private absolute path reference: {rel}")
    return findings


def write_report(stage: Path, manifest_count: int, sanitized_count: int, findings: list[str], output: Path) -> None:
    admit_fixed_profile_output(output, REPORT_PATH)
    top_counts: dict[str, int] = {}
    for path in iter_files(stage):
        rel = path.relative_to(stage)
        top = rel.parts[0] if rel.parts else rel.as_posix()
        top_counts[top] = top_counts.get(top, 0) + 1

    try:
        stage_display = stage.relative_to(REPO_ROOT).as_posix()
    except ValueError:
        stage_display = str(stage)

    lines = [
        "# chirality-app Release Projection Report",
        "",
        "Generated from the public `chirality` source profile `exports/chirality-app`.",
        "",
        f"- Staging path: `{stage_display}`",
        f"- Manifest rows: {manifest_count}",
        f"- Text files sanitized for machine-absolute paths: {sanitized_count}",
        f"- Boundary findings: {len(findings)}",
        "",
        "## Top-Level File Counts",
        "",
        "| Path | Files |",
        "|---|---:|",
    ]
    for key in sorted(top_counts):
        lines.append(f"| `{key}` | {top_counts[key]} |")
    lines.extend(["", "## Boundary Findings", ""])
    if findings:
        lines.extend(f"- {item}" for item in findings[:500])
        if len(findings) > 500:
            lines.append(f"- ... {len(findings) - 500} additional findings omitted")
    else:
        lines.append("No boundary findings.")
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")


def apply_target(stage: Path, target: Path) -> None:
    hold = stage / 'ADOPTION_HOLD.json'
    if hold.is_file() and json.loads(hold.read_text()).get('status') == 'HELD':
        raise SystemExit('public export adoption held: owning App and Runtime loops must adopt the four-role interface')
    if not (target / ".git").exists():
        raise SystemExit(f"refusing to apply: target has no .git directory: {target}")
    for item in target.iterdir():
        if item.name == ".git":
            continue
        if item.is_dir():
            shutil.rmtree(item)
        else:
            item.unlink()
    for item in stage.iterdir():
        dest = target / item.name
        if item.is_dir():
            shutil.copytree(item, dest)
        else:
            shutil.copy2(item, dest)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--stage-dir", default=str(DEFAULT_STAGE))
    parser.add_argument("--apply-target", help="Replace a local chirality-app worktree from the clean staging tree")
    args = parser.parse_args()

    stage = Path(args.stage_dir).absolute()
    sanitized_count = build_stage(stage)
    manifest_count = write_manifest(stage, MANIFEST_PATH)
    findings = boundary_findings(stage)
    write_report(stage, manifest_count, sanitized_count, findings, REPORT_PATH)

    if findings:
        print(f"export failed boundary scan with {len(findings)} findings", file=sys.stderr)
        print(f"see {REPORT_PATH}", file=sys.stderr)
        return 2

    if args.apply_target:
        apply_target(stage, Path(args.apply_target).resolve())
        print(f"applied public export to {args.apply_target}")
    print(f"staged {manifest_count} files at {stage}")
    print(f"wrote {MANIFEST_PATH}")
    print(f"wrote {REPORT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
