from pathlib import Path
import re,json,csv,hashlib,subprocess,os,collections,ast
R=Path(subprocess.check_output(['git','rev-parse','--show-toplevel'],text=True).strip()); BASE='2be412ccea62bdc4bd96deb082c46d7a792076ea'
P='projects/pec/'; E=P+'execution/'; RUN=E+'_Reconciliation/DeliverableConcordance/PEC_REMAINING_CONCORDANCE_2026-09-05/'; PACK=RUN+'R1_R4_2026-09-05/PACKAGES/PKG-08/'; O=R/(PACK+'WORKERS/DEL-08-03'); D=E+'PKG-08_API_Access/1_Working/DEL-08-03_Compact_citation_bearing_response_format/'; S=D+'ScopeOfWork.md'; U=E+'PKG-08_API_Access/1_Working/DEL-08-02_Versioned_additive_API_schema/'; C=E+'PKG-04_Orientation_Services/1_Working/DEL-04-03_Citation_freshness_stamping/'; L=E+'PKG-04_Orientation_Services/1_Working/DEL-04-05_Measurement_limitation_honesty/'
sha=lambda b:hashlib.sha256(b).hexdigest()
sources=set(['AGENTS.md',P+'AGENTS.md','agents/AGENT_RECONCILIATION.md','docs/DELIVERABLE_CONCORDANCE_METHOD.md',P+'loop/LOOP_INIT.md',P+'docs/PRD.md',RUN+'CONVENTIONS.md',PACK+'PACKAGE_BASIS.md',PACK+'SOURCE_MANIFEST.json',PACK+'BRIEFS/DEL-08-03.md',RUN+'R1_R4_2026-09-05/COMMON/BRIEFS/PKG-08.md',RUN+'R1_R4_2026-09-05/COMMON/BRIEF_CLARIFICATION_01.md',RUN+'R1_R4_2026-09-05/COMMON/RUN_BASIS.md',RUN+'R1_R4_2026-09-05/COMMON/SOURCE_MANIFEST.json',RUN+'R1_R4_2026-09-05/COMMON/SCOPE_CENSUS.csv',RUN+'R1_R4_2026-09-05/COMMON/AGENT0_GRAPH.json',E+'_Scripts/pec_reliance_hold.py',E+'_Coordination/ACTIVE_RELIANCE_HOLDS.csv',E+'_Coordination/_DECISIONS/D-PEC-81_CALIBRATION_ACCEPTANCE_2026-09-05.md',E+'_Coordination/_DECISIONS/D-PEC-82_remaining_corpus_reporting_2026-09-05.md',E+'_Coordination/_DECISIONS/_REGISTER.md',E+'_Coordination/_TaskManagement/REGISTER.csv',E+'_Coordination/PEC_CURRENCY_REPAIR_CLOSEOUT_2026-08-09/HANDOFF_STATE.md',E+'_Decomposition/_LATEST.md',E+'_Decomposition/SOFTWARE_DECOMP.md',E+'_Decomposition/ScopeLedger.csv',E+'_Decomposition/Deliverables.csv',E+'_Decomposition/ContextBudgetQA.csv',E+'_Coordination/PLAN_2026-07-25_project_setup_dag_gate.md',E+'_ScopeChange/SCA-002_2026-07-25_1042/Brief.md',E+'_ScopeChange/SCA-002_2026-07-25_1042/Amendment_Preview.md',E+'_ScopeChange/SCA-002_2026-07-25_1042/Decision_Log.md',U+'ScopeOfWork.md',U+'_STATUS.md',C+'ScopeOfWork.md',C+'_STATUS.md',L+'ScopeOfWork.md',L+'Dependencies.csv',E+'_Coordination/D-PEC-74_FIRST_P1_SOURCE_SLICE_2026-08-01/DEL0802_FINAL_ACCEPTANCE_RULING_2026-08-01.md'])
# Include every local file read and every inventoried current product byte; no old product source.
sources.update(str(p.relative_to(R)) for p in (R/D).rglob('*') if p.is_file())
sources.update(str(p.relative_to(R)) for p in (R/(P+'v2')).rglob('*') if p.is_file() and '__pycache__' not in p.parts)
missing=sorted(p for p in sources if not (R/p).is_file());sources-=set(missing)
contents={p:(R/p).read_bytes() for p in sources}; hashes={p:sha(b) for p,b in sorted(contents.items())}; checks=json.loads((O/'PREFLIGHT.json').read_text())
def check(cmd):
 x=subprocess.run(cmd,cwd=R,text=True,capture_output=True,env={**os.environ,'PYTHONDONTWRITEBYTECODE':'1'});c=dict(command=cmd,cwd=str(R),environment={'PYTHONDONTWRITEBYTECODE':'1'},exit_code=x.returncode,result=x.stdout+x.stderr);checks.append(c);return x
check(['git','rev-parse','HEAD']);check(['git','merge-base','--is-ancestor',BASE,'origin/main'])
bind=[]; runlocal=[]
for p,b in contents.items():
 x=subprocess.run(['git','show',BASE+':'+p],cwd=R,capture_output=True)
 if x.returncode==0:
  assert x.stdout==b,p;bind.append(p)
 else:
  assert p.startswith(RUN+'R1_R4_2026-09-05/'),p
  runlocal.append(p)
checks.append(dict(command='Compare every read-source byte to git show '+BASE+':<path>',cwd=str(R),environment={},exit_code=0,result={'base_equal':sorted(bind),'run_local_instruction_or_derivative_not_product_authority':sorted(runlocal),'missing_requested_paths':missing}))
text=contents[S].decode(); lines=text.splitlines(); defs=[]
for i,line in enumerate(lines,1):
 m=re.match(r'^- \*\*((?:CLM|OUT|TBD|REQ|AC|CON|VER|AX)-\d{3})\*\* — (.*)',line)
 if m: defs.append((m[1],i,m[2]))
assert len(defs)==71 and len({x[0] for x in defs})==71
inventory=json.loads((O/'V2_INVENTORY.json').read_text()); assert all(hashes[x['path']]==x['sha256'] for x in inventory)
modules={}
for p,b in contents.items():
 if p.startswith(P+'v2/src/') and p.endswith('.py'):
  modules[p]=[{'kind':type(n).__name__,'name':getattr(n,'name','')} for n in ast.parse(b.decode()).body]
# Exact accepted upstream bytes verified without treating upstream suite as this deliverable's tests.
ruling=E+'_Coordination/D-PEC-74_FIRST_P1_SOURCE_SLICE_2026-08-01/DEL0802_FINAL_ACCEPTANCE_RULING_2026-08-01.md'
api=[p for p in hashes if p.startswith(P+'v2/contracts/api/') or p.startswith(P+'v2/tests/contracts/api/')]
assert len(api)==5
for p in api: assert hashes[p] in contents[ruling].decode(),p
scope_rows=list(csv.DictReader(contents[E+'_Decomposition/ScopeLedger.csv'].decode().splitlines()));scope=next(x for x in scope_rows if x['ScopeItemID']=='SOW-043');assert scope['DeliverableIDs']=='DEL-08-03' and scope['ObjectiveIDs']=='OBJ-001'
dep=list(csv.DictReader(contents[D+'Dependencies.csv'].decode().splitlines()));prod=[x for x in dep if x['DependencyClass']=='EXECUTION'];assert [x['TargetDeliverableID'] for x in prod]==['DEL-08-02','DEL-04-03']
observations={'source_commit':BASE,'scope_contract_present':True,'scope_row':scope,'defined_local_ids':defs,'v2_modules':modules,'v2_inventory_count':len(inventory),'deliverable_inventory':sorted(p for p in sources if p.startswith(D)),'upstream_accepted_bytes_reproduced':{p:hashes[p] for p in api},'future_production_prerequisites':prod,'limits':'Current v2 inventory has loop-registry production modules, generic API schema, config/enforcement/schema tests; no DEL08-03 serializer artifact or fixture result is identified. Unassigned artifact locations preclude repository-wide absence or acceptance inference. No runtime claim asserted.'}
(O/'OBSERVATIONS.json').write_text(json.dumps(observations,indent=2)+'\n')
checks.append(dict(command='Inspect full v2 file inventory, AST module declarations, exact D74 artifact hashes, local definitions, scope/dependency rows',cwd=str(R),environment={},exit_code=0,result={'definitions':71,'v2_files':len(inventory),'accepted_upstream_bytes':5,'behavior_tests_run':0,'reason':'No claimed DEL08-03 test surface; upstream finite suite cannot verify serialization.'}))
CH='ClaimID,DeliverableID,ClaimClass,NormativeSource,ScopeItemIDs,DeclaredSource,CurrentState,ImplementationEvidence,VerificationEvidence,ValidationOrProvenanceEvidence,LifecycleEvidence,ExistingRemaining,Disposition,ProposedResidualID,ProposedResidualText,Depends,ExactGate,AuthorityNeeded,Selectability,SourceCommit,SourceHashes,EvidenceReferences,Notes'.split(',')
RH='ResidualID,DeliverableID,ClaimIDs,ProposedText,Depends,ExactGate,ClosureEvidence,AuthorityNeeded,Selectability,Notes'.split(',')
select='NON_SELECTABLE_PENDING_OWNER_APPLICATION';gate='(gated: later exact PEC owner application ruling; no product or lifecycle act under D82)';pre='Future production only: ACTIVE PREREQUISITE DEP-08-03-003 -> DEL-08-02 and DEP-08-03-004 -> DEL-04-03 remain PENDING at RequiredMaturity INITIALIZED. An item is blocked only when its Depends names these targets; evidence-only proposals use NONE. No dependency status flip; D74 authorizes no other P1 node.'
resdefs={
'001':('Establish a current, source-bound evidence disposition for DEL-08-03 format specification, serializer and tests: locate each actual artifact or explicitly record unavailable evidence, then map every production requirement and finite verification method. Do not infer absence or passing behavior from INITIALIZED, missing Remaining, generic upstream schema or search misses.',gate,'Exact artifact paths/SHAs, claim-specific implementation and verification mapping, honest pending/unknown results; a separate owner source packet if production is later selected.'),
'002':('Route the current-use limits of historical SOW provenance to the owner: CLM-004 dependency evidence was repaired under D65; CLM-006/AX-006 predecessor-absence framing predates D74 schema acceptance and CHECKING. Preserve dated source text unless an exact owner-ruled contract currency amendment is selected; confirm the pinned revision1.3 basis against accepted revision1.4 without reopening completed ordinary currency.',gate,'Owner disposition preserving original history, exact current dependency and upstream acceptance citations, and only if selected an authorized contract postimage/backcheck.'),
'003':('Resolve evidence for the declared AC-014 human REVIEW criterion against this exact contract hash, including how historical dependency observations are read after D65. Preserve lifecycle INITIALIZED; do not infer human acceptance from SOW initialization validators.', '(gated: separately authorized exact REVIEW and owner acceptance act; D82 evidence discovery creates no acceptance)', 'A located current-hash REVIEW record and exact owner disposition or explicit pending record, without changing lifecycle by inference.'),
'004':('Route TM-PEC-005 limitation-inventory/response-format seam to the owning PEC human decision process: retain DEL-04-05 limitation semantics and DEL-08-03 lossless carriage, and identify whether any production declaration or scope amendment is needed. Do not invent a dependency edge or mirror the TM concern into executable product work.', '(gated: owner triage of TM-PEC-005 and separately ruled production choice or SCOPE_CHANGE if scope changes)', 'Owner disposition of inventory home/shape, residence/rendering and trigger-set questions with exact instruments; no edge created by this report.')}
rows=[]
base_ev=[S,D+'_STATUS.md',D+'Dependencies.csv',E+'_Decomposition/ScopeLedger.csv',E+'_Decomposition/Deliverables.csv',P+'docs/PRD.md']
stale={'CLM-004','CLM-006','AX-006','AX-007'}
for local,ln,quote in defs:
 kind=local.split('-')[0];cls={'REQ':'PRODUCT_OBLIGATION','OUT':'PRODUCT_OUTPUT','AC':'FINITE_ACCEPTANCE_CRITERION','VER':'FINITE_TEST_METHOD','CLM':'DOCUMENTARY_ALIGNMENT','TBD':'DOCUMENTARY_UNRESOLVED_FIELD','CON':'DOCUMENTARY_OPEN_READING','AX':'DOCUMENTARY_RATIONALE'}[kind]
 disp='ALIGNED';res=''; note='Documentary alignment only; no product completion, test PASS, acceptance, release or assignment inferred.'
 state='Declared scope/constraint remains traceable in inspected accepted records.';impl='Not a behavioral assertion; source and scope comparison only.';ver='Source comparison, OBSERVATIONS.json; no product test run.'
 evidence=list(base_ev)
 if kind in {'REQ','OUT','AC','VER'} or local in {'CLM-011','AX-010'}:
  disp='UNKNOWN';res='001';state='INITIALIZED; contract declares future production. Current sufficient implementation/verification evidence is not established.'
  impl='V2_INVENTORY.json and OBSERVATIONS.json inspect current modules and deliverable files; generic upstream schema exists but is not the DEL08-03 envelope/serializer. Artifact locations remain undecided (TBD-002).'
  ver='No current DEL08-03 method execution result identified; specified fixture/inspection method is pending, not PASS. Current absence is bounded to inspected surfaces.'
  note='Evidence-gap proposal only. Required future criterion retained exactly in DeclaredSource. '+pre
 if local=='AC-014': cls='HUMAN_ACCEPTANCE';res='003';note='Human REVIEW is separately required. INIT/REVISE validator/checklist history cannot establish this current exact-hash acceptance; dependency observation context must be qualified.'
 if local in stale:
  disp='STALE_INPUT';res='002';state='Historical contract framing is preserved; it is stale if consumed as a present-current description, not proof of current dependency/artifact absence.'
  impl='D65 local run record and current Dependencies.csv repair both evidence cells; D74 current schema/test/fixtures reproduce five exact accepted hashes; DEL08-02 is CHECKING.'
  ver='Current source comparison and exact upstream accepted-byte reproduction in OBSERVATIONS.json. No broader schema guarantee inferred.'
  note='Temporal qualification, not an automatic stale-text repair. Dated INIT and revised contract basis remain historical truth. Owner decides whether a current-use annotation/amendment is needed. '+pre
  evidence += [ruling,U+'_STATUS.md',P+'v2/contracts/api/v1/schema.json',D+'_run_records/TASK_RUN_2026-07-25_repair_D-PEC-65.md']
 if local in {'CLM-007','CLM-008','CON-002','CON-004'}: evidence += [C+'ScopeOfWork.md',C+'_STATUS.md'];note+=' Upstream claim granularity and SHA representation/origin are carried open; no choice made here.'
 if local=='TBD-001':state='ResponsibleParty remains literal TBD in live Deliverables.csv and _CONTEXT.md.';note+=' Truthful unassigned state is not invented product work.'
 if kind in {'CON','TBD'}:note+=' Declarative open record remains ALIGNED as documentation; production resolution/completeness is not asserted.'
 if local in {'CLM-001','CLM-002','CLM-003','CLM-009','CLM-010'}:evidence+=[E+'_Decomposition/SOFTWARE_DECOMP.md',E+'_Decomposition/ContextBudgetQA.csv']
 if local in {'CLM-004','CLM-005','AX-007'}:evidence+=[D+'_DEPENDENCIES.md',E+'_Coordination/PLAN_2026-07-25_project_setup_dag_gate.md']
 if kind in {'AX'} and local not in stale|{'AX-010'}:note+=' Normative rationale, not measured behavior.'
 row=dict(zip(CH,['']*len(CH)));row.update(ClaimID='DEL-08-03::'+local,DeliverableID='DEL-08-03',ClaimClass=cls,NormativeSource=S+'#'+local+'; '+E+'_Decomposition/ScopeLedger.csv#SOW-043',ScopeItemIDs='SOW-043',DeclaredSource=f'{S}:{ln} {local} — {quote}',CurrentState=state,ImplementationEvidence=impl,VerificationEvidence=ver,ValidationOrProvenanceEvidence='Base-bound source comparison; D81 accepted calibration/D82 reporting only. No new acceptance.',LifecycleEvidence=D+'_STATUS.md: INITIALIZED preserved; upstream CHECKING preserved',ExistingRemaining='No ## Remaining section in current _STATUS.md; not warranted NONE',Disposition=disp,ProposedResidualID='DEL-08-03-REM-'+res if res else '',ProposedResidualText=resdefs[res][0] if res else '',Depends='NONE',ExactGate=resdefs[res][1] if res else gate,AuthorityNeeded='Exact later owner ruling for application; production/source/REVIEW/lifecycle gates separate',Selectability=select,SourceCommit=BASE,SourceHashes=json.dumps({p:hashes[p] for p in sorted(set(evidence))},sort_keys=True),EvidenceReferences='; '.join(sorted(set(evidence)))+'; '+PACK+'WORKERS/DEL-08-03/OBSERVATIONS.json',Notes=note)
 rows.append(row)
# Material unnumbered current-basis, lifecycle, Remaining and seam claims receive explicit run-local mappings.
extras=[('BASIS-CURRENCY','DOCUMENTARY_PROVENANCE','STALE_INPUT','002',S+':19-25','The SOW explicitly pins revision1.3/11a494e9a; current references/decomposition are revision1.4. Historical pin remains valid as provenance, not current pointer. Ordinary SCA004 currency is already complete.'),('LIFECYCLE','LIFECYCLE','ALIGNED','',D+'_STATUS.md:3','Current State INITIALIZED. No lifecycle act or product completion inferred.'),('REMAINING-COVERAGE','REMAINING_EVIDENCE','UNKNOWN','001',D+'_STATUS.md','No Remaining section exists; unknown behavior/verification prevents warranted NONE.'),('TM005-SEAM','AUTHORITY_ROUTING','UNKNOWN','004',E+'_Coordination/_TaskManagement/REGISTER.csv#TM-PEC-005','TM005 OPEN; limitation inventory/home/rendering decisions remain owner-routed. DEL04-05 CLM014/CON002..004 and local REQ009/010 separate semantics from carriage; no direct seam edge is invented.')]
for local,cls,disp,res,loc,note in extras:
 row=rows[0].copy();evidence=base_ev+[E+'_Decomposition/_LATEST.md',D+'_REFERENCES.md',E+'_Coordination/PEC_CURRENCY_REPAIR_CLOSEOUT_2026-08-09/HANDOFF_STATE.md',E+'_Coordination/_TaskManagement/REGISTER.csv',L+'ScopeOfWork.md',L+'Dependencies.csv']
 row.update(ClaimID='DEL-08-03::'+local,ClaimClass=cls,DeclaredSource=loc,CurrentState=note,ImplementationEvidence='Source-level documentary observation; no behavior or completion assertion.',VerificationEvidence='Exact source and register comparison in OBSERVATIONS.json; no product test claimed.',Disposition=disp,ProposedResidualID='DEL-08-03-REM-'+res if res else '',ProposedResidualText=resdefs[res][0] if res else '',ExactGate=resdefs[res][1] if res else gate,SourceHashes=json.dumps({p:hashes[p] for p in sorted(set(evidence))},sort_keys=True),EvidenceReferences='; '.join(sorted(set(evidence))),Notes='Run-local ID for material unnumbered claim; does not create source scope. '+note+' '+pre)
 rows.append(row)
resrows=[]
for rid,(proposed,g,closure) in resdefs.items():
 full='DEL-08-03-REM-'+rid;links=[x['ClaimID'] for x in rows if x['ProposedResidualID']==full];assert links
 resrows.append(dict(ResidualID=full,DeliverableID='DEL-08-03',ClaimIDs=';'.join(links),ProposedText=proposed,Depends='NONE',ExactGate=g,ClosureEvidence=closure,AuthorityNeeded='PEC owner exact application; owning contract/source/REVIEW/SCOPE_CHANGE instrument as needed',Selectability=select,Notes='Evidence/owner-routing proposal; no live Remaining application. '+pre))
for name,fields,data in [('CLAIMS.csv',CH,rows),('RESIDUALS.csv',RH,resrows)]:
 with (O/name).open('w',newline='') as f:
  w=csv.DictWriter(f,fields,lineterminator='\n');w.writeheader();w.writerows(data)
counts=dict(collections.Counter(x['Disposition'] for x in rows)); localcounts=dict(collections.Counter(x[0].split('-')[0] for x in defs))
(O/'COVERAGE.md').write_text('# DEL-08-03 coverage\n\nSource basis '+BASE+'; D81 accepted conventions and D82 effective reporting. Canonical root '+str(R)+'.\n\nAll 71 own-voice local definitions covered exactly once: '+json.dumps(localcounts)+'. REQ13 + AC14 + VER13 =40; all other31 covered. Four material unnumbered claims are additionally mapped by exact source locus. Total75. Quoted upstream IDs, matrix cross-references, E/DEP/SOW/OBJ IDs are contextual references rather than local definitions. The earlier worker message claiming81 was an arithmetic error, corrected before artifact finalization; no upstream quote IDs enter the census.\n\nDisposition counts '+json.dumps(counts)+'. Summary ASSESSED_UNKNOWN; no warranted NONE. Four residual proposals, all Depends NONE and NON_SELECTABLE_PENDING_OWNER_APPLICATION. Finite methods have UNKNOWN execution, not fictional PASS. Truthful TBD and unresolved readings are documentary ALIGNED, not completed production.\n\nScopeOfWork.md exists; no missing-SOW fallback required. Mapping: ScopeLedger.csv line44 SOW-043 -> DEL-08-03 -> OBJ-001, quoted statement `Return compact, machine-first, citation-bearing responses`; quote SHA256 '+sha(scope['ScopeItemStatement'].encode())+'. Scope source file hash '+hashes[E+'_Decomposition/ScopeLedger.csv']+'.\n\nEvidence inventory covers10 local files and35 current v2 files. Production modules are loop registry ports/adapters; generic upstream request/response schema and its five accepted bytes reproduce D74. This does not prove repository-wide serializer absence with TBD artifact locations. No service, mutation CLI, or test suite was run. Historical INIT/REVISE validator passes are not current human REVIEW or serializer results. Current _STATUS has no Remaining section; INITIALIZED is preserved.\n\nCLM004/006 and AX006/007 retain dated provenance; their present-use limitation is routed conditionally, without automatically repairing frozen text. SOW revision1.3 is a historical pin; accepted decomposition/reference basis is1.4. The August9 ordinary currency completion is not reopened. TM005 remains owner routing; no invented DEL04-05 edge. TM022 remains deferred; TM023 dedicated mapping hold creates no unrelated gate. PRDv2.3/D79 adopted-not-applied and all CHECKING/ISSUED states remain unchanged.\n\n'+pre+'\n\nPREFLIGHT.json records actual candidate-validation ALLOW for10 exact project-relative files. Every read-source hash and base equality is in READ_MANIFEST; run-local instructions/derivatives are identified separately as non-product authority. Summary closure is worker evidence ready for independent verification only, not product/Remaining closure.\n')
assert all((R/p).read_bytes()==b for p,b in contents.items())
checks.append(dict(command='Validate exact CSV schemas,71 local IDs +4 supplemental, reciprocal residual links, gate markers, Depends, LF, sources unchanged',cwd=str(R),environment={},exit_code=0,result={'counts':counts,'local_counts':localcounts,'claims':len(rows),'residuals':len(resrows),'source_unchanged':True}))
manifest=dict(source_commit=BASE,hashes=hashes,historical_sources=[],checks=checks,source_unchanged=True)
(O/'READ_MANIFEST.json').write_text(json.dumps(manifest,indent=2)+'\n')
for name,expected in [('CLAIMS.csv',CH),('RESIDUALS.csv',RH)]:
 b=(O/name).read_bytes();assert b'\r' not in b
 with (O/name).open() as f:assert next(csv.reader(f))==expected
for row in rows:
 assert row['Depends'] and row['ExactGate'].startswith(('(gated:','(stage-gated:','NOT_SELECTABLE_UNTIL:'))
for x in resrows:
 assert set(x['ClaimIDs'].split(';'))=={a['ClaimID'] for a in rows if a['ProposedResidualID']==x['ResidualID']}
outputs={p.name:sha(p.read_bytes()) for p in O.iterdir() if p.is_file() and p.name!='RETURN.md'}
(O/'RETURN.md').write_text('# DEL-08-03 terminal return\n\nStatus: COMPLETE_FOR_WORKER_REPORT / ASSESSED_UNKNOWN. Role: sealed ephemeral Agent2; delegated-harness-native; instruction-asserted, role not mechanically enforced. No delegation.\n\n71/71 local IDs and4 material supplemental claims:75 total; '+json.dumps(counts)+'. Four nonselectable residual proposals: current evidence mapping, conditional documentary currency routing, human REVIEW evidence, TM005 owner seam routing. No NONE.\n\nSource '+BASE+'; accepted D81 conventions and D82 continuation are upstream authority; this packet is derivative evidence only. 10 exact hold preflights ALLOW,75-row exact schema/ID/link/gate checks PASS, all read product sources base-equal and unchanged. No serializer test PASS or repository-wide implementation absence claimed.\n\nSource/lifecycle/Remaining/dependency/PRD/TM/Root writes: none. Sole write allowlist '+PACK+'WORKERS/DEL-08-03/**. No Git mutation, service or product mutation.\n\nIndependent package verifier and manager fan-in remain required. Rerun affected rows on source/hash/hold/owner changes, new artifact location, REVIEW or seam disposition; fresh corrections go to separate derivative trees. No product closure, lifecycle reversal, issuance, release or reliance.\n\nOutput SHA256 manifest (RETURN self-excluded):\n\n```json\n'+json.dumps(outputs,indent=2)+'\n```\n')
print(json.dumps({'claims':len(rows),'local':len(defs),'counts':counts,'residuals':len(resrows),'read_sources':len(hashes),'runlocal_sources':len(runlocal),'write_root':str(O)},indent=2))
