import fs from 'node:fs/promises'; import path from 'node:path'; import assert from 'node:assert/strict'; import {spawn} from 'node:child_process'; import readline from 'node:readline'; import {fileURLToPath} from 'node:url'; import {_electron} from '/Users/ryan/.npm/_npx/e41f203b7505f1fb/node_modules/playwright/index.mjs';
const out=path.dirname(fileURLToPath(import.meta.url)), repo=process.cwd(), frontend=path.join(repo,'projects/chirality-app-dev/frontend');
const cfg=JSON.parse(await fs.readFile(path.join(out,'ISOLATION_PREPARATION.json'),'utf8')); const isolated=JSON.parse(await fs.readFile(path.join(out,'ISOLATED_ENVIRONMENT_v2.json'),'utf8'));
const env=Object.fromEntries(isolated.inheritAllowlist.filter(k=>process.env[k]!==undefined).map(k=>[k,process.env[k]])); Object.assign(env,isolated.sharedElectronAndOwnedServerEnvironment,{CHIRALITY_INSTRUCTION_ROOT:repo,ELECTRON_RENDERER_URL:'http://127.0.0.1:3197'});
const results=[]; let app,page,server; const log=async()=>fs.writeFile(path.join(out,'EXECUTION_v5.json'),JSON.stringify({env,results},null,2)+'\n');
try {
for(const p of [env.CHIRALITY_RUNTIME_SOCKET_PATH,env.CHIRALITY_RUNTIME_TOKEN_FILE,env.CHIRALITY_RUNTIME_OPERATOR_TOKEN_FILE,path.join(env.HOME,'Library/LaunchAgents',env.CHIRALITY_RUNTIME_LAUNCH_AGENT_LABEL+'.plist')]) assert.equal(await fs.lstat(p).then(()=>true,()=>false),false);
server=spawn(process.execPath,['node_modules/next/dist/bin/next','start','-H','127.0.0.1','-p','3197'],{cwd:frontend,env,stdio:['ignore','pipe','pipe']}); server.stdout.on('data',d=>fs.appendFile(path.join(out,'server.stdout'),d));server.stderr.on('data',d=>fs.appendFile(path.join(out,'server.stderr'),d));
let ready=false;for(let n=0;n<80;n++){try{if((await fetch(env.ELECTRON_RENDERER_URL)).ok){ready=true;break;}}catch{} await new Promise(r=>setTimeout(r,250));}
assert(ready,'Owned production server did not start');app=await _electron.launch({executablePath:path.join(cfg.bundlePath,'Contents/MacOS/Electron'),args:[path.join(frontend,'dist-electron/main.js')],cwd:frontend,env});
page=await app.firstWindow(); await page.context().route('**/api/harness/**',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify(r.request().url().endsWith('/agents')?{agents:[]}:{sessions:[]})}));await page.reload({waitUntil:'networkidle'}); await page.locator('[data-chat-input="primary"]').waitFor();
const identity=await app.evaluate(({app})=>({pid:process.pid,packaged:app.isPackaged,userData:app.getPath('userData'),versions:process.versions,env:Object.fromEntries(Object.entries(process.env).filter(([k])=>k.startsWith('CHIRALITY_')))}));assert(!identity.packaged); results.push({identity,serverPid:server.pid});await page.screenshot({path:path.join(out,'offline-first-v5.png')}); await log(); console.log(JSON.stringify({ready:true,identity,body:await page.locator('body').innerText()}));
for await(const line of readline.createInterface({input:process.stdin,terminal:false})){const c=JSON.parse(line); if(c.action==='finish')break;let result; try{if(c.action==='page')result=await page.evaluate(c.code);else if(c.action==='main')result=await app.evaluate(c.code);else if(c.action==='click')result=await page.getByRole(c.role||'button',{name:c.name,exact:true}).click();else if(c.action==='fill')result=await page.getByLabel(c.name,{exact:true}).fill(c.value);else if(c.action==='shot'){await page.screenshot({path:path.join(out,c.name+'.png')});result=await page.locator('body').innerText();}else throw Error('unknown action');results.push({command:c,result,status:'PASS'});console.log(JSON.stringify({result}));}catch(e){results.push({command:c,status:'FAIL',error:String(e)});console.log(JSON.stringify({error:String(e)}));}await log();}
} catch(e){results.push({status:'FAIL',error:String(e)});console.error(e);process.exitCode=1;}finally{if(app)await app.close().catch(()=>{});if(server && server.exitCode===null){server.kill('SIGTERM');await new Promise(r=>server.once('exit',r));}results.push({cleanup:'owned app and server closed'});await log();}
