from pathlib import Path
import json,subprocess,os,datetime,hashlib,sys
out=Path(__file__).parent;arc=json.loads((out/'ARCHIVE.json').read_text());root=Path(arc['archive']);h='projects/chirality-piping/core/solver/performance_harness';env={**os.environ,'GIT_OPTIONAL_LOCKS':'0','RUSTUP_AUTO_INSTALL':'0','CARGO_NET_OFFLINE':'true','CARGO_INCREMENTAL':'0','CARGO_TARGET_DIR':arc['target']}; overrides={k:env[k] for k in ['GIT_OPTIONAL_LOCKS','RUSTUP_AUTO_INSTALL','CARGO_NET_OFFLINE','CARGO_INCREMENTAL','CARGO_TARGET_DIR']}
argv=['/Users/ryan/.cargo/bin/rustup','run','1.97.1','cargo','test','--manifest-path',h+'/Cargo.toml','--release','--locked','--offline','-j','4','--test','k6c_envelope','--test','rv33_reference','--','--test-threads=2']
metadata={'argv':argv,'cwd':str(root),'environment_overrides':overrides,'start_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'guard':subprocess.check_output(['ps','-p','5387','-o','pid=,etime=,command='],text=True),'rustc':subprocess.check_output(['/Users/ryan/.cargo/bin/rustup','run','1.97.1','rustc','-vV'],env=env,text=True),'cargo':subprocess.check_output(['/Users/ryan/.cargo/bin/rustup','run','1.97.1','cargo','-V'],env=env,text=True)}
assert 'memguard.sh' in metadata['guard']
(out/'BUILD_COMMAND.json').write_text(json.dumps(metadata,indent=2)+'\n')
with (out/'BUILD.log').open('w') as f: proc=subprocess.run(argv,cwd=root,env=env,stdout=f,stderr=subprocess.STDOUT)
metadata.update(exit_code=proc.returncode,end_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),archive_files_unchanged=all(hashlib.sha256((root/x['path']).read_bytes()).hexdigest()==x['sha256'] for x in arc['files']),binaries=[{'path':str(p),'sha256':hashlib.sha256(p.read_bytes()).hexdigest()} for p in (Path(arc['target'])/'release/deps').iterdir() if (p.name.startswith('rv33_reference-') or p.name.startswith('k6c_envelope-')) and p.suffix=='' and p.is_file()])
(out/'BUILD_COMMAND.json').write_text(json.dumps(metadata,indent=2)+'\n');print(json.dumps({k:metadata[k] for k in ['exit_code','end_utc','archive_files_unchanged']}));print((out/'BUILD.log').read_text()[-3500:]);sys.exit(proc.returncode)
