from pathlib import Path
import csv,json,hashlib,subprocess,re
O=Path(__file__).resolve().parent; ROOT=Path.cwd(); M=json.loads((O/'READ_MANIFEST.json').read_text()); H=M['hashes']; D='DEL-06-05'; B=M['source_commit']; P='projects/pec/execution/PKG-06_Presence_Git_Observation/1_Working/DEL-06-05_TTL_heartbeat_discipline_citation_exclusion'; S='projects/pec/execution/_Decomposition/ScopeLedger.csv'; R='projects/pec/execution/_Decomposition/Deliverables.csv'; DEC='projects/pec/execution/_Decomposition/SOFTWARE_DECOMP.md'; DAG='projects/pec/execution/_Coordination/PLAN_2026-07-25_project_setup_dag_gate.md'; C4='projects/pec/execution/PKG-04_Orientation_Services/1_Working/DEL-04-03_Citation_freshness_stamping/ScopeOfWork.md'; D62='projects/pec/execution/_Coordination/_DECISIONS/D-PEC-62_project_setup_scaffold_and_local_dependency_registers.md'
C='ClaimID,DeliverableID,ClaimClass,NormativeSource,ScopeItemIDs,DeclaredSource,CurrentState,ImplementationEvidence,VerificationEvidence,ValidationOrProvenanceEvidence,LifecycleEvidence,ExistingRemaining,Disposition,ProposedResidualID,ProposedResidualText,Depends,ExactGate,AuthorityNeeded,Selectability,SourceCommit,SourceHashes,EvidenceReferences,Notes'.split(','); RC='ResidualID,DeliverableID,ClaimIDs,ProposedText,Depends,ExactGate,ClosureEvidence,AuthorityNeeded,Selectability,Notes'.split(',')
gate='(gated: owner accepts exact Remaining application; any production requires separately ruled exact source/write scope and WORKING_ITEMS activation; preserve runtime ownership and content-minimal restrictions)'
texts=['Establish source-bound implementation and verification evidence for accepted DEL-06-05 TTL, heartbeat-age, liveness-honesty and presence-store citation-exclusion obligations and anticipated tests; return unknowns for owner disposition before deciding production scope.','Route C-02 split-exclusion phase/acceptance question through package synthesis to its owning authority; preserve undeclared direction and non-gating status without assigning citation-production work to DEL-06-05.']
rows=[]
def add(local,cls,scope,state,disp,src,locus,quote='',res=None,depends='NONE',notes=''):
 refs=[src,P+'/_STATUS.md',R,S]; refs=list(dict.fromkeys(refs)); sh={p:H[p] for p in refs}; q='; quote='+quote+'; quote_sha256='+hashlib.sha256(quote.encode()).hexdigest() if quote else ''
 row=dict.fromkeys(C,'');row.update(ClaimID=D+'::'+local,DeliverableID=D,ClaimClass=cls,NormativeSource=src+' '+locus+q,ScopeItemIDs=scope,DeclaredSource=P+'/_CONTEXT.md',CurrentState=state,ImplementationEvidence='UNKNOWN: bounded current v2 source inventory/search supplies no claim-bound implementation proof; no absence inference' if disp=='UNKNOWN' else 'Not a behavior assertion',VerificationEvidence='No claim-bound DEL-06-05 test execution or REVIEW acceptance established; no product suite rerun' if disp=='UNKNOWN' else 'Documentary comparison only; no product test pass claimed',ValidationOrProvenanceEvidence='Accepted revision 1.4 ScopeLedger/Deliverables mapping; common source SHA equality; exact-file candidate-validation preflights',LifecycleEvidence=P+'/_STATUS.md: OPEN, 2026-07-25 PREPARATION; preserved',ExistingRemaining='No ## Remaining section; not warranted NONE',Disposition=disp,ProposedResidualID=f'{D}-REM-{res:03}' if res else '',ProposedResidualText=texts[res-1] if res else '',Depends=depends,ExactGate=gate if res==1 else '(gated: owner separately resolves C-02 phase/acceptance question; C-02 remains non-gating and direction undeclared)' if res==2 else 'NONE',AuthorityNeeded='Exact owner application/source grant; observations do not confer runtime session authority' if res==1 else 'Owner boundary ruling through HELP_HUMAN synthesis; no new blocking edge' if res==2 else 'NONE for documentary observation',Selectability='NON_SELECTABLE_PENDING_OWNER_APPLICATION',SourceCommit=B,SourceHashes=json.dumps(sh,sort_keys=True),EvidenceReferences=';'.join(refs),Notes=notes);rows.append(row)
s30='Carry TTLs and last-heartbeat age on presence records; never assert liveness beyond last heartbeat';s32='Exclude presence data from record-tier citations (enforced separation)'
for local,description in [('SOW-030.TTL','Presence records carry TTLs'),('SOW-030.AGE','Presence records carry last-heartbeat age'),('SOW-030.LIVENESS','Liveness is never asserted beyond last heartbeat')]:add(local,'observed behavior','SOW-030',description+'; implementation/verification UNKNOWN','UNKNOWN',S,'row SOW-030',s30,1,'DEL-06-01','Evidence-gap candidate, not DOCUMENTED_UNIMPLEMENTED or implementation authorization. DEP-06-05-004 remains ACTIVE PREREQUISITE/PENDING; only applies when this exact target is named by executable work.')
add('SOW-032.GUARD','observed behavior','SOW-032','Presence-store guard excludes presence facts from record-tier citations; implementation/verification UNKNOWN','UNKNOWN',S,'row SOW-032',s32,1,'DEL-06-01','Evidence-gap candidate for guard only. Citation production belongs to DEL-04-03 REQ-006; C-02 is not a prerequisite.')
add('ARTIFACTS.TESTS','finite test method','SOW-030;SOW-032','Anticipated tests are accepted artifact scope; no defined local VER IDs or executed finite method established','UNKNOWN',R,'row DEL-06-05 AnticipatedArtifacts','TTL machinery + exclusion guard + tests',1,'DEL-06-01','Evidence-gap candidate. No kill/crash test obligation imported from DEL-10-07; future finite results must state limits.')
add('BOUNDARY.SPLIT','documentary alignment','SOW-032','Accepted split matches local description: guard here; producer exclusion in DEL-04-03 tests','ALIGNED',R,'row DEL-06-05 Description','The exclusion is two-sided: the presence-store guard lands here; the citation-production side is asserted in DEL-04-03\'s tests (declared dependency edge, DL-14).',notes='No residual: documentary split only; independently checked DEL-04-03 REQ-006/CON-001. PKG04_COORDINATION is attributed relay, not authority.')
add('BOUNDARY.C02','human acceptance','SOW-032','C-02 phase/acceptance settlement UNKNOWN; accepted annotation remains unresolved/non-gating','UNKNOWN',D62,'§1(4) flags-as-flags',res=2,notes='HELD_ROUTING_AUTHORITY_QUESTION; not recommended executable product Remaining. Exact C-02 in DAG §4.2 and DEL-04-03 CON-001 retain P1/P3 phase tension. No direction invented.')
add('DEPENDENCY.004','documentary alignment','SOW-030','DEP-06-05-004 names DEL-06-01 ACTIVE PREREQUISITE/PENDING; no satisfaction update inferred','ALIGNED',P+'/Dependencies.csv','DEP-06-05-004',depends='DEL-06-01',notes='No residual: existing production prerequisite reported; discovery allowed. PROPOSAL provenance does not change owner-accepted register semantics. Other constraints order or annotate only.')
add('ASSIGNMENT.TBD','documentary alignment','SOW-030;SOW-032','ResponsibleParty remains truthful TBD pending WORKING_ITEMS activation','ALIGNED',R,'row DEL-06-05 ResponsibleParty',notes='No administrative mirror or invented product task; accepted DL-13(c) permits TBD.')
add('LIFECYCLE.OPEN','lifecycle','SOW-030;SOW-032','Current OPEN and PREPARATION history preserved; no lifecycle advance or reversal asserted','ALIGNED',P+'/_STATUS.md','Current State and History',notes='ALIGNED means faithful lifecycle reporting only, not readiness or completion. No release/admin residual.')
add('SCOPE.MAPPING','documentary alignment','SOW-030;SOW-032','Missing local ScopeOfWork.md; accepted row maps SOW-030/SOW-032 to DEL-06-05/PKG-06/OBJ-003 with M envelope and P3 metadata','ALIGNED',R,'row DEL-06-05',notes='No local REQ/AC/VER definitions found in exact local file inventory; run-local fallback IDs above are explicit, not a fabricated contract. Source-search absence does not prove product absence.')
res=[]
for i,text in enumerate(texts,1):
 linked=[r for r in rows if r['ProposedResidualID']==f'{D}-REM-{i:03}'];res.append(dict(zip(RC,[f'{D}-REM-{i:03}',D,';'.join(r['ClaimID'] for r in linked),text,'DEL-06-01' if i==1 else 'NONE',linked[0]['ExactGate'],'Source-bound implementation/test evidence and owner disposition of remaining unknowns' if i==1 else 'Exact accepted owner boundary ruling recorded without implied dependency mutation',linked[0]['AuthorityNeeded'],'NON_SELECTABLE_PENDING_OWNER_APPLICATION','RECOMMENDED_EVIDENCE_CANDIDATE; accepted obligation, implementation unknown; no automatic production/contract-writing selection' if i==1 else 'HELD_ROUTING_AUTHORITY_QUESTION; coordinate with DEL-04-03, not a blanket downstream blocker'])))
for name,head,data in [('CLAIMS.csv',C,rows),('RESIDUALS.csv',RC,res)]:
 with (O/name).open('w',newline='') as f:w=csv.DictWriter(f,fieldnames=head,lineterminator='\n');w.writeheader();w.writerows(data)
(O/'COVERAGE.md').write_text('# DEL-06-05 coverage\n\n11 claims: 5 ALIGNED (documentary/lifecycle only), 6 UNKNOWN; 2 proposals (1 evidence candidate, 1 held authority-routing question). Summary ASSESSED_UNKNOWN; NONE not warranted.\n\nExact local inventory has no ScopeOfWork.md and no locally defined REQ/AC/VER IDs. Fallback claim mapping uses accepted ScopeLedger row SOW-030 atomized into TTL, age and liveness; SOW-032 maps the guard. Each mapping carries exact quote and SHA in CLAIMS.csv. Accepted Deliverables row binds ownership, anticipated tests, assignment, metadata and objective. Dependency anchors are traceability nonclaims; DEP-06-05-004 is separately assessed. Empty _SEMANTIC.md defines no claims. Anticipated artifact names do not prove production absence.\n\nThe current v2 file inventory was byte-hashed and bounded text searched for presence/heartbeat/ttl/citation; no claim-bound implementation or test evidence was established. Inventory is not semantic review of every unrelated implementation. The only deliverable run record read records dependency-evidence repair, not product implementation or test acceptance. No local REVIEW evidence is present in that inventory; wider acceptance continuity remains unknown. Frozen implementation-does-not-exist prose is not current proof.\n\nCross-package split is independently bound to Deliverables.csv description, DEL-04-03 ScopeOfWork REQ-006/CON-001, DAG C-02 and D-PEC-62 §1(4). Citation production is not reassigned here. C-02 direction remains undeclared/non-gating; P1/P3 assertion/acceptance tension is owner routing only. DEP-06-05-004 remains the exact production predecessor; read-only discovery does not satisfy it. Runtime sessions remain daemon-owned; PEC is observation-only and content-minimal.\n\nAll evidence files are derivatives of accepted revision1.4 and D81/D82 at the frozen base; no pointer/source/status/Remaining changed. Ordinary SCA004 currency is not reopened from older _LATEST prose. Required next derivative is independent package verification and fan-in; no product closure claimed.\n')
(O/'RETURN.md').write_text('# DEL-06-05 bounded return\n\nCOMPLETE_FOR_MANAGER_VERIFICATION / ASSESSED_UNKNOWN. 11 claims, 5 ALIGNED, 6 UNKNOWN; 2 residual proposals, 1 recommended evidence candidate and 1 held C-02 routing concern. No warranted NONE.\n\nOutputs: CLAIMS.csv, RESIDUALS.csv, COVERAGE.md, READ_MANIFEST.json, VALIDATION.json. Accepted upstream D81 calibration/D82, revision1.4 decomposition, base '+B+'. Derivative report only; independent package verification pending. No claim of product, Remaining, lifecycle or release closure.\n\nPreserved DEL-04-03 producer / DEL-06-05 store-guard split, C-02 undeclared non-gating phase question, DEL-06-01 pending prerequisite, owner application/source/runtime/content boundaries. Unknown current implementation/tests and phase acceptance require source-bound evidence/owner routing. Rerun on source or hold drift, changed scope/acceptance, or new implementation evidence.\n\nActual role: ephemeral Agent2 via delegated-harness-native, instruction-asserted and not mechanically enforced. No delegation or model assertion. Only worker subtree writes; read-only shell and scoped report generation; no Git mutation, network, services or source edits. Tests not gratuitously rerun.\n')
assert all(hashlib.sha256((ROOT/p).read_bytes()).hexdigest()==h for p,h in H.items())
cmd=['python3',str(O.parent.parent/'validate_package.py'),str(O)];q=subprocess.run(cmd,capture_output=True,text=True);(O/'VALIDATION.json').write_text(q.stdout);assert q.returncode==0,q.stdout+q.stderr
M['checks'].append(dict(command='python3 '+str((O.parent.parent/'validate_package.py').relative_to(ROOT))+' '+str(O.relative_to(ROOT)),cwd='.',environment={'PYTHONDONTWRITEBYTECODE':'1'},exit_code=q.returncode,result=json.loads(q.stdout)));M['checks'].append(dict(command='bounded current v2 inventory and rg presence|heartbeat|ttl|citation; exact local file inventory',cwd='.',environment={},exit_code=0,result='ScopeOfWork.md absent; no local REQ/AC/VER definitions; product behavior remains UNKNOWN; all recorded source hashes unchanged'))
(O/'READ_MANIFEST.json').write_text(json.dumps(M,indent=2)+'\n');print(q.stdout)
