#!/usr/bin/env python3
"""Fill gen_d101_k4.template.py's pinned block from a git-archive export of the preimage commit.

Usage: python3 build_gen_d101_k4.py <export_root> <template> <out>

The export must be `git archive` of origin/main aca930622ba167689881416044ba0feaee3ef003.
Fails (assertion) unless the census is exactly 61 CTX_STD + 2 CTX_D93 + 3 A2 mirrors
contexts and 66 revision-1.5 references over 66 deliverable folders.
"""
import glob
import hashlib
import sys
from pathlib import Path

root, tpl, out = Path(sys.argv[1]), Path(sys.argv[2]), Path(sys.argv[3])
EX = "projects/pec/execution"


def sha(p):
    return hashlib.sha256((root / p).read_bytes()).hexdigest()


def text(p):
    return (root / p).read_text(encoding="utf-8")


def rel(pattern):
    return sorted((str(Path(p).relative_to(root)) for p in glob.glob(str(root / EX / pattern))),
                  key=lambda s: s.encode("utf-8"))


folders = [p for p in rel("PKG-*/1_Working/DEL-*") if (root / p).is_dir()]
contexts = rel("PKG-*/1_Working/DEL-*/_CONTEXT.md")
references = rel("PKG-*/1_Working/DEL-*/_REFERENCES.md")
STD = "then by revision 1.5 (`current_basis`, SCA-005 successor).\n"
MIRROR = "then by revision 1.6 (`current_basis`, SCA-006 successor).\n"
ctx_std = [p for p in contexts if STD in text(p)]
mirrors = [p for p in contexts if MIRROR in text(p)]
ctx_d93 = {}
for p in contexts:
    for anum in ("A-19", "A-20"):
        if f"SCA-005 successor; deliverable added by {anum}). Fields templated\n" in text(p):
            ctx_d93[p] = anum
ref = [p for p in references
       if "- `execution/_Decomposition/SOFTWARE_DECOMP.md` (revision 1.5, accepted `current_basis`; SCA-005 successor)\n"
       in text(p) and "- `docs/PRD.md` v2.3 (accepted source corpus; see SourceRef column of the ledger)\n" in text(p)]
assert (len(folders), len(contexts), len(references)) == (66, 66, 66), (len(folders), len(contexts), len(references))
assert (len(ctx_std), len(ctx_d93), len(mirrors), len(ref)) == (61, 2, 3, 66), \
    (len(ctx_std), len(ctx_d93), len(mirrors), len(ref))
assert set(ctx_std) | set(ctx_d93) | set(mirrors) == set(contexts)
assert not (set(ctx_std) & set(ctx_d93)) and not (set(ctx_std) & set(mirrors)) and not (set(ctx_d93) & set(mirrors))
assert sorted(Path(p).parent.name[:9] for p in ctx_d93) == ["DEL-02-08", "DEL-02-09"]
assert sorted(Path(p).parent.name[:9] for p in mirrors) == ["DEL-04-03", "DEL-08-01", "DEL-08-03"]
basis = ["projects/pec/docs/PRD.md", f"{EX}/_Decomposition/SOFTWARE_DECOMP.md",
         f"{EX}/_Decomposition/Deliverables.csv", f"{EX}/_Decomposition/ScopeLedger.csv"] + mirrors
targets = sorted(ctx_std + list(ctx_d93) + ref, key=lambda s: s.encode("utf-8"))
lines = ["# Pinned at origin/main aca930622ba167689881416044ba0feaee3ef003 (generated by build_gen_d101_k4.py).",
         "# BASIS_PATHS are read-only (PRD.md, SOFTWARE_DECOMP.md, Deliverables.csv, ScopeLedger.csv and the",
         "# three SCA-006 A2-mirror contexts). Every other PREIMAGES entry is a write target (129).",
         "PREIMAGES = {"]
for p in basis + targets:
    lines.append(f'    "{p}": "{sha(p)}",')
lines.append("}")
for name, ps in (("BASIS_PATHS", basis), ("MIRROR_PATHS", mirrors), ("CTX_STD_PATHS", ctx_std), ("REF_PATHS", ref)):
    lines.append(f"{name} = [")
    lines += [f'    "{p}",' for p in ps]
    lines.append("]")
lines.append("CTX_D93_PATHS = {")
lines += [f'    "{p}": "{a}",' for p, a in sorted(ctx_d93.items())]
lines.append("}")
src = tpl.read_text(encoding="utf-8")
assert src.count("# @@PINNED@@") == 1
out.write_text(src.replace("# @@PINNED@@", "\n".join(lines)), encoding="utf-8")
print(out, hashlib.sha256(out.read_bytes()).hexdigest())
