#!/usr/bin/env python3
"""Provisional D-PEC-101 part K4 exact generator: revision-1.6 re-pin of deliverable metadata.

Deterministic. Stdlib only. Slot-free: no date or other varying value appears
in any postimage, so there is no --act-date and no local-date check. Run from
any directory against a repository root whose bytes equal origin/main
aca930622ba167689881416044ba0feaee3ef003 for every path listed in PREIMAGES.
Every postimage is computed and every check passes before the first byte is
written; on any failure it exits 1, prints FAIL on stderr and writes nothing.
A second run exits 1 (the targets no longer match their pinned preimages).

Acts (anchor lines only; each anchor must occur exactly once in its file):
  * CTX_STD (61 _CONTEXT.md): the final provenance clause for revision 1.5
    gains a comma and a following revision-1.6 clause;
  * CTX_D93 (2 _CONTEXT.md, DEL-02-08 / DEL-02-09): the D-PEC-93 provenance
    line gains the revision-1.6 clause before "Fields templated";
  * references (66 _REFERENCES.md): the SOFTWARE_DECOMP.md bullet moves to
    revision 1.6 (SCA-006 successor) and the PRD bullet to v2.4;
  * add-on C (--covers): the ScopeLedger bullet of DEL-04-03 and DEL-08-03
    carries the revision-1.6 covers list, asserted equal to the
    Deliverables.csv CoversScopeItems cell. Same files, different postimages.

Fail-closed checks before any write:
  * every PREIMAGES path hashes to its pinned SHA-256 (129 targets and 7
    read-only basis files: PRD.md, SOFTWARE_DECOMP.md, Deliverables.csv,
    ScopeLedger.csv and the three SCA-006 A2-mirror _CONTEXT.md);
  * PRD.md names version 2.4 and SOFTWARE_DECOMP.md names revision 1.6 as
    current (pinned literal anchors, each exactly once);
  * population (globbed at run time): every deliverable _CONTEXT.md is a
    pinned target, a pinned A2 mirror, or already ends its provenance at
    revision 1.6 (SCA-006) without a pending revision-1.5 anchor; every
    _REFERENCES.md is a pinned target or already names revision 1.6 and PRD
    v2.4 without the revision-1.5 or PRD v2.3 bullet. The tolerance lets K4
    run before or after the separately rulable K1 part (new folders born at
    revision 1.6 / PRD v2.4);
  * every anchor occurs exactly once; all postimages rendered;
  * post-state (rendered): every context ends its provenance at revision 1.6
    (SCA-006); every reference names revision 1.6 and PRD v2.4 and neither
    revision 1.5 nor PRD v2.3; the 61 CTX_STD postimages and the 3 mirrors
    share one byte-identical provenance block;
  * the write set equals the grant (the 129 pinned targets, for either flag
    set).
The report also carries, report-only, whether each reference's covers list
equals its Deliverables.csv cell (a blank cell agrees with the D-PEC-95
add-on R "none — retired under SCA-005, formerly SOW-0NN" form).

Usage:
  python3 gen_d101_k4.py --repo <REPO_ROOT> [--covers] [--check-only]

stdout: a TSV report (only on success) with READ, CHECK, RENDER (check-only)
or WRITE rows: kind, subject, value 1, value 2.
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import re
import sys
from pathlib import Path

PEC = "projects/pec"
EX = f"{PEC}/execution"
PRD = f"{PEC}/docs/PRD.md"
DECOMP = f"{EX}/_Decomposition/SOFTWARE_DECOMP.md"
DELIVERABLES = f"{EX}/_Decomposition/Deliverables.csv"
LEDGER = f"{EX}/_Decomposition/ScopeLedger.csv"

# Pinned at origin/main aca930622ba167689881416044ba0feaee3ef003 (generated by build_gen_d101_k4.py).
# BASIS_PATHS are read-only (PRD.md, SOFTWARE_DECOMP.md, Deliverables.csv, ScopeLedger.csv and the
# three SCA-006 A2-mirror contexts). Every other PREIMAGES entry is a write target (129).
PREIMAGES = {
    "projects/pec/docs/PRD.md": "ae49b8065698f003001b2183f550b814cded5cd5ea06f940b81dd5c287483fbe",
    "projects/pec/execution/_Decomposition/SOFTWARE_DECOMP.md": "9374c21fb87b02e5f842af9407caf65690d73f3067f86ce6c7dba0a3a7908eb1",
    "projects/pec/execution/_Decomposition/Deliverables.csv": "94ee5d182ae99092324505a72bf2f3b0581f85c0bae6c693214cfef709179805",
    "projects/pec/execution/_Decomposition/ScopeLedger.csv": "1d24a4b86f05dc6fd57028c08e202d33f9f317b148821f9c61246c6e91ee916e",
    "projects/pec/execution/PKG-04_Orientation_Services/1_Working/DEL-04-03_Citation_freshness_stamping/_CONTEXT.md": "b28ada4674662515ed7f975cb59c1ee2c2f9cac3c4bcf0d919ced22af79a7b22",
    "projects/pec/execution/PKG-08_API_Access/1_Working/DEL-08-01_Unix_socket_server_token_scoped_access/_CONTEXT.md": "74b12e7358a71000b8cd544f2db8a736289e7ca4b1e3f94dbadbf98154292d22",
    "projects/pec/execution/PKG-08_API_Access/1_Working/DEL-08-03_Compact_citation_bearing_response_format/_CONTEXT.md": "95fa815a31a38e59c001dd3596bc47053508cd3ff59c9d3eae67d64ba9d037b5",
    "projects/pec/execution/PKG-00_Architecture_Runway_Contracts/1_Working/DEL-00-01_v2_first_ADRs_core_isolation_carried_postures/_CONTEXT.md": "2fe92b000bc2829d4bc3dc69d01d64044ada2db28b11ba70e22118a95ab05e75",
    "projects/pec/execution/PKG-00_Architecture_Runway_Contracts/1_Working/DEL-00-01_v2_first_ADRs_core_isolation_carried_postures/_REFERENCES.md": "db32c618c8beab8d418805c69f6a3d53871a01981f6e063ca1c414c33f401f7c",
    "projects/pec/execution/PKG-00_Architecture_Runway_Contracts/1_Working/DEL-00-02_Event_contract_schema_v1/_CONTEXT.md": "beafd08c5112cf5f5b8edb81ecbfdb98128441b8c407eb7e1dc0ec07fe46bb58",
    "projects/pec/execution/PKG-00_Architecture_Runway_Contracts/1_Working/DEL-00-02_Event_contract_schema_v1/_REFERENCES.md": "005aac9b9612ce10bfc06c9a2ccf256f9c06ababc192724a55cb592cf5c732dc",
    "projects/pec/execution/PKG-00_Architecture_Runway_Contracts/1_Working/DEL-00-03_v2_SPEC_seed/_CONTEXT.md": "05a2e5d08fa5366c21f7ebfe52e7c80503e484fecb2f582bf8d302214346e578",
    "projects/pec/execution/PKG-00_Architecture_Runway_Contracts/1_Working/DEL-00-03_v2_SPEC_seed/_REFERENCES.md": "21b2110208b72467d01dde4460ef7b16fbf41afe11d101a69f8f7b0fe320534d",
    "projects/pec/execution/PKG-01_Service_Core_Store/1_Working/DEL-01-01_Record_tier_schema_entity_model/_CONTEXT.md": "cab17da6dbdd6e086426813406fffa4b478f1607daf8c716ff38e2effb343975",
    "projects/pec/execution/PKG-01_Service_Core_Store/1_Working/DEL-01-01_Record_tier_schema_entity_model/_REFERENCES.md": "8f67568f44f9c386cfcfdb3230899b5e84924527991d351e2c9b936743f32205",
    "projects/pec/execution/PKG-01_Service_Core_Store/1_Working/DEL-01-02_Presence_tier_schema_entity_model/_CONTEXT.md": "53f11105266638f39f1f1601f9a7c72fc0bff245bb4f722be6798e8b5effa16e",
    "projects/pec/execution/PKG-01_Service_Core_Store/1_Working/DEL-01-02_Presence_tier_schema_entity_model/_REFERENCES.md": "cf3eabd186c5b2186c60845c975b827d1b5003c060d1cb2c0a223e36e4f7ffe7",
    "projects/pec/execution/PKG-01_Service_Core_Store/1_Working/DEL-01-03_Store_bootstrap_content_minimal_guard/_CONTEXT.md": "e97e3c07b999f2fb5a6f13176dfe2a7c3f58403308554d02da876e93cf26e77b",
    "projects/pec/execution/PKG-01_Service_Core_Store/1_Working/DEL-01-03_Store_bootstrap_content_minimal_guard/_REFERENCES.md": "8f0dfcd7b1664bcc1173d4f099a7e74ca0b5b4f10755d53bb90cf022171b9400",
    "projects/pec/execution/PKG-01_Service_Core_Store/1_Working/DEL-01-04_Self_observability_logging/_CONTEXT.md": "52a4d9337e7551bf154bec549bfdcaa76ae94c96dccbf37959bd9eeaacba969a",
    "projects/pec/execution/PKG-01_Service_Core_Store/1_Working/DEL-01-04_Self_observability_logging/_REFERENCES.md": "f503808a708413cfdbf0020a0b3f3116c5aeb242a0355e083077f20101f1216f",
    "projects/pec/execution/PKG-01_Service_Core_Store/1_Working/DEL-01-05_Zero_dependency_locality_enforcement/_CONTEXT.md": "a687ad1f91bcfa82c24fc08c5577435b79e56d4884936e2903f0f6633f2675f5",
    "projects/pec/execution/PKG-01_Service_Core_Store/1_Working/DEL-01-05_Zero_dependency_locality_enforcement/_REFERENCES.md": "20d344699830c43b00464ca0e41efcf3e415c695d38427ba0b8e81f28342e2c3",
    "projects/pec/execution/PKG-01_Service_Core_Store/1_Working/DEL-01-06_Loop_registry_local_config_default/_CONTEXT.md": "1362ed668436b5af79fe54dd5f7ab660dac9ddd29dad2a0d1b0adebb01ad5919",
    "projects/pec/execution/PKG-01_Service_Core_Store/1_Working/DEL-01-06_Loop_registry_local_config_default/_REFERENCES.md": "6e640cf84b3beb619c7503c7702017d786b80da237ae1be8ea01275c6d9c63b1",
    "projects/pec/execution/PKG-02_File_Truth_Parsers/1_Working/DEL-02-01_STATUS_md_parser/_CONTEXT.md": "7b4132ab8be4e6b5fa7a2956563fd8148967bc6fede9beba6df41b96a638c92e",
    "projects/pec/execution/PKG-02_File_Truth_Parsers/1_Working/DEL-02-01_STATUS_md_parser/_REFERENCES.md": "370181a2da1f92b6672fcc424d263fa567a1a35c5e8f795f52a0591cc964bdc1",
    "projects/pec/execution/PKG-02_File_Truth_Parsers/1_Working/DEL-02-02_Decision_register_packet_parser/_CONTEXT.md": "3c1e856db52c85de42a7e794b7a4110387a9dc2316851061f0f21f054eb26125",
    "projects/pec/execution/PKG-02_File_Truth_Parsers/1_Working/DEL-02-02_Decision_register_packet_parser/_REFERENCES.md": "152c6af2b22f60414ac215240207518d794a2869b6e4639b3ebb396d96c81acb",
    "projects/pec/execution/PKG-02_File_Truth_Parsers/1_Working/DEL-02-03_Receipts_ledger_parser_per_loop_grammars/_CONTEXT.md": "aafac18687dae3703e2ea0e903fc790df5123ea78cbba5682a532b54422f1d12",
    "projects/pec/execution/PKG-02_File_Truth_Parsers/1_Working/DEL-02-03_Receipts_ledger_parser_per_loop_grammars/_REFERENCES.md": "e3962d35eac198dadc0c666b08a668da881500f59006966ef5e9d1bf1efde9bc",
    "projects/pec/execution/PKG-02_File_Truth_Parsers/1_Working/DEL-02-04_Run_evidence_JSON_parser/_CONTEXT.md": "7f72f6d7304254cb05cf22eb941341627ea2372e549426722311da13595666c2",
    "projects/pec/execution/PKG-02_File_Truth_Parsers/1_Working/DEL-02-04_Run_evidence_JSON_parser/_REFERENCES.md": "bec637be26e4875954acb67ba346120f497ed9b94555932c18577e434a091796",
    "projects/pec/execution/PKG-02_File_Truth_Parsers/1_Working/DEL-02-05_Dependency_register_parser/_CONTEXT.md": "6c3ffcff5cb13773bbac24b821ac7d0e101f99ee414b1806a5bd6006b5e38899",
    "projects/pec/execution/PKG-02_File_Truth_Parsers/1_Working/DEL-02-05_Dependency_register_parser/_REFERENCES.md": "9d83d55b306857b70ebd608dbf473a916c99626c48a7642011a75281b7b4cd3e",
    "projects/pec/execution/PKG-02_File_Truth_Parsers/1_Working/DEL-02-06_Workplan_LOOP_INIT_parser/_CONTEXT.md": "3a09d9792f1a025f807ca63239b7a7c9622226880bb9706a62a10d6e093c1ec1",
    "projects/pec/execution/PKG-02_File_Truth_Parsers/1_Working/DEL-02-06_Workplan_LOOP_INIT_parser/_REFERENCES.md": "1000ff3dd8ce0ec7ad23ec5f658994000a1ab512eaa6a323a295b74a98c1a4a7",
    "projects/pec/execution/PKG-02_File_Truth_Parsers/1_Working/DEL-02-07_adapter_yaml_feed_manifest_consumer/_CONTEXT.md": "fdad5d912567281dabcc61713175a75bed477e225507310f7458b72d698f04c8",
    "projects/pec/execution/PKG-02_File_Truth_Parsers/1_Working/DEL-02-07_adapter_yaml_feed_manifest_consumer/_REFERENCES.md": "15c7018e01f4acb32e319fd93c48331139e8fea5c23c9d9410737e029a590861",
    "projects/pec/execution/PKG-02_File_Truth_Parsers/1_Working/DEL-02-08_Work_graph_parser/_CONTEXT.md": "721a9807211b1330b0cd124139d37fdb9b2f9167b9edc461f218bb4570f34d20",
    "projects/pec/execution/PKG-02_File_Truth_Parsers/1_Working/DEL-02-08_Work_graph_parser/_REFERENCES.md": "87f95d423851a800651c6e01c4b04a7434b5f56f3476b5512075da556563840b",
    "projects/pec/execution/PKG-02_File_Truth_Parsers/1_Working/DEL-02-09_MEMORY_run_index_parser/_CONTEXT.md": "2413b5c0b241eb44c9e53401499729ca3b84e23860692b63f09104af56640502",
    "projects/pec/execution/PKG-02_File_Truth_Parsers/1_Working/DEL-02-09_MEMORY_run_index_parser/_REFERENCES.md": "211cb59ce46a7399ba56775fa57024f018322ebf2f50ecaf0887eb419d06073f",
    "projects/pec/execution/PKG-03_Reconciliation_Parity/1_Working/DEL-03-01_Full_rebuild_reconciler_one_command/_CONTEXT.md": "8a5874c2e46ac1c5519ea2a3123be618754f5c0989084dfed1cc562d7ac508f5",
    "projects/pec/execution/PKG-03_Reconciliation_Parity/1_Working/DEL-03-01_Full_rebuild_reconciler_one_command/_REFERENCES.md": "a7886e3cc64c79c9ccfb099fdafb829736b69368af76d62b6183ffea5a6995e6",
    "projects/pec/execution/PKG-03_Reconciliation_Parity/1_Working/DEL-03-02_Incremental_reconcile_on_Git_delta/_CONTEXT.md": "415a4a4252978e4617236cc67adf37b59d50ddc6eb08270a06398d359137c996",
    "projects/pec/execution/PKG-03_Reconciliation_Parity/1_Working/DEL-03-02_Incremental_reconcile_on_Git_delta/_REFERENCES.md": "09975b4636056f878aca7574142379d0573d58bc85fda28e8cbe482865bf7ebc",
    "projects/pec/execution/PKG-03_Reconciliation_Parity/1_Working/DEL-03-03_Drift_classification/_CONTEXT.md": "0181f52d5a1c4199f3a29eb61c286d4fb916c91833d47f1a5c90c026d6d08a4b",
    "projects/pec/execution/PKG-03_Reconciliation_Parity/1_Working/DEL-03-03_Drift_classification/_REFERENCES.md": "f11685f717abe03d25b92bc183d67e40264d6f317471ce9b13db3d4f9697ca73",
    "projects/pec/execution/PKG-03_Reconciliation_Parity/1_Working/DEL-03-04_Practitioner_harness_parity_diff/_CONTEXT.md": "2407e64f042e0c7da7e8f2ae7aabfbab59c23976d4f7c954d541daf6ae524bf7",
    "projects/pec/execution/PKG-03_Reconciliation_Parity/1_Working/DEL-03-04_Practitioner_harness_parity_diff/_REFERENCES.md": "9366b6ed7867aa339766765a48d4bf3ba64e703cd9a74bd964bbf2546160fd4f",
    "projects/pec/execution/PKG-03_Reconciliation_Parity/1_Working/DEL-03-05_Stream_loss_recovery_guarantee/_CONTEXT.md": "4e89162e0c483b34afc4a0e954263c9929ef333a228f656075638c93a7116a17",
    "projects/pec/execution/PKG-03_Reconciliation_Parity/1_Working/DEL-03-05_Stream_loss_recovery_guarantee/_REFERENCES.md": "dd731f5d56f40bf42d20a6a60c35e5e31ff55d8291dfcbc28cf653a11eed4f8f",
    "projects/pec/execution/PKG-03_Reconciliation_Parity/1_Working/DEL-03-06_Rebuild_performance_bounds/_CONTEXT.md": "5502601cfe9f1c469b0df2474943f870d6e57f9514d6df830f7f6d9e32356470",
    "projects/pec/execution/PKG-03_Reconciliation_Parity/1_Working/DEL-03-06_Rebuild_performance_bounds/_REFERENCES.md": "9e8ef0044e7232699c7c8f39d45aecf3d4063dfa93cd9558d03b5713a61b68d5",
    "projects/pec/execution/PKG-04_Orientation_Services/1_Working/DEL-04-01_Loop_orientation_return/_CONTEXT.md": "107a293ff8de3b127d2ee2c8c2c71171ee1578ca0d1aaa36842e9c90314aa85f",
    "projects/pec/execution/PKG-04_Orientation_Services/1_Working/DEL-04-01_Loop_orientation_return/_REFERENCES.md": "334caab42cab5e50e41397f2c00540fbded70ab30d33c7a3eb68469ad2c417b6",
    "projects/pec/execution/PKG-04_Orientation_Services/1_Working/DEL-04-02_Delta_service_since_SHA/_CONTEXT.md": "1374dc7d81acf021e85404615097207948d96106ddcea9bd24b0e6823fdbdbe0",
    "projects/pec/execution/PKG-04_Orientation_Services/1_Working/DEL-04-02_Delta_service_since_SHA/_REFERENCES.md": "b039d6736b01f5399d87dd09f07cbcb13a6d94f343f7b935cc6405efd9cc194b",
    "projects/pec/execution/PKG-04_Orientation_Services/1_Working/DEL-04-03_Citation_freshness_stamping/_REFERENCES.md": "81b7f2cf5f5d7a61448ceade15edfab416ecb77eb7185b9156d3abc1d458acd6",
    "projects/pec/execution/PKG-04_Orientation_Services/1_Working/DEL-04-04_Scope_parameterization/_CONTEXT.md": "cdcc030c868471ecf0a4bf13f315b171a9fab990fa1b1140d4f060bfa1d6294f",
    "projects/pec/execution/PKG-04_Orientation_Services/1_Working/DEL-04-04_Scope_parameterization/_REFERENCES.md": "d96e4e4c608cb552f1ceb71daf46d6772f573efc09e6161270ff8cbdfc5ed003",
    "projects/pec/execution/PKG-04_Orientation_Services/1_Working/DEL-04-05_Measurement_limitation_honesty/_CONTEXT.md": "4c1cb297d34552e03fab61f08f0105a5b04779a8e71755a2bbcea584ab902112",
    "projects/pec/execution/PKG-04_Orientation_Services/1_Working/DEL-04-05_Measurement_limitation_honesty/_REFERENCES.md": "cbcfd50a884e507e06f55b017df463348bd61368389270e9b9acd35b1959793d",
    "projects/pec/execution/PKG-05_Gate_Evaluation_Decision_Slate/1_Working/DEL-05-01_Gate_precondition_evaluators_Explain_shaped/_CONTEXT.md": "142528619a8d497437fbd0232b0bda28d3c720a9356b180455265f325b8cbe15",
    "projects/pec/execution/PKG-05_Gate_Evaluation_Decision_Slate/1_Working/DEL-05-01_Gate_precondition_evaluators_Explain_shaped/_REFERENCES.md": "787380f88ec5e753548f5a4c8c842a94fd238b8eebe045dca9a007e4816fa1f1",
    "projects/pec/execution/PKG-05_Gate_Evaluation_Decision_Slate/1_Working/DEL-05-02_Cross_loop_decision_slate/_CONTEXT.md": "a0eea793cf9f871f0c6c7fdcbab87a352b60fe800fa36e693f25357529c2126d",
    "projects/pec/execution/PKG-05_Gate_Evaluation_Decision_Slate/1_Working/DEL-05-02_Cross_loop_decision_slate/_REFERENCES.md": "f32444f02048580d05cbe58aabc3e660987edad6861092aae4e9736081172e80",
    "projects/pec/execution/PKG-06_Presence_Git_Observation/1_Working/DEL-06-01_Session_presence_records/_CONTEXT.md": "c9dbe25c44ab78d4e970a94c792865f5b028a905c789111a2c80c9759350d412",
    "projects/pec/execution/PKG-06_Presence_Git_Observation/1_Working/DEL-06-01_Session_presence_records/_REFERENCES.md": "cbec466b9054bc22206c2ffc2c295a218eebb49b7fe9d9283c5f085e71017382",
    "projects/pec/execution/PKG-06_Presence_Git_Observation/1_Working/DEL-06-02_Git_worktree_scanner/_CONTEXT.md": "9338cf5592fcaa103fe8a5fc8245d4d6e2e1d533b88a97cd28f031a12874fe99",
    "projects/pec/execution/PKG-06_Presence_Git_Observation/1_Working/DEL-06-02_Git_worktree_scanner/_REFERENCES.md": "a92d69179a62cbc2d327547c4729cabf9f44a2a44d45dbef2fa654d4623b4438",
    "projects/pec/execution/PKG-06_Presence_Git_Observation/1_Working/DEL-06-03_Session_worktree_scope_correlation/_CONTEXT.md": "b117fac353aa4f043e2cedc07c7cf393c3e7cb41b519bac7ae753cf3a03e1470",
    "projects/pec/execution/PKG-06_Presence_Git_Observation/1_Working/DEL-06-03_Session_worktree_scope_correlation/_REFERENCES.md": "4e6a306004fef85ff35606ee38ee4ffc08686e4495e3e69f98b97abaca28d945",
    "projects/pec/execution/PKG-06_Presence_Git_Observation/1_Working/DEL-06-04_Live_hierarchy_edges/_CONTEXT.md": "a0aee56bc26a769f3ef617ed2f836050c8634b4b7ca3df14554ecee33b47fc30",
    "projects/pec/execution/PKG-06_Presence_Git_Observation/1_Working/DEL-06-04_Live_hierarchy_edges/_REFERENCES.md": "ca03c93f1ab4cdacf2bca1390fcb59308c12e655798c21fb522b8176f97fce18",
    "projects/pec/execution/PKG-06_Presence_Git_Observation/1_Working/DEL-06-05_TTL_heartbeat_discipline_citation_exclusion/_CONTEXT.md": "a8e76d8999dbd8e3f9ce32f42823736789905576e6678679b1d320d6c81e66e8",
    "projects/pec/execution/PKG-06_Presence_Git_Observation/1_Working/DEL-06-05_TTL_heartbeat_discipline_citation_exclusion/_REFERENCES.md": "bcb24a8424d3b8157342dd7aeb0b5852cfcb86bc1a9517ea89f11823faca51d4",
    "projects/pec/execution/PKG-06_Presence_Git_Observation/1_Working/DEL-06-06_Advisory_overlap_detection/_CONTEXT.md": "9717a0a2500a193136cb162d90275615fc87eb8cfdc477decf7b06424be73a48",
    "projects/pec/execution/PKG-06_Presence_Git_Observation/1_Working/DEL-06-06_Advisory_overlap_detection/_REFERENCES.md": "21fc6146c658b6f1e793a0b7c84b8a7d9a0b420787edb7a2b978ced9e4a0134c",
    "projects/pec/execution/PKG-07_Event_Ingest_Bridges/1_Working/DEL-07-01_Idempotent_event_ingest_durable_message_store/_CONTEXT.md": "f84331ff03d83f5f1ac2116907e3fbae8358fbc4e5f56a40cc6debaa0568e02d",
    "projects/pec/execution/PKG-07_Event_Ingest_Bridges/1_Working/DEL-07-01_Idempotent_event_ingest_durable_message_store/_REFERENCES.md": "d7cddbe827d48097a614492aabe7c6a14ec914a98071529e324b9ba83b5ccf49",
    "projects/pec/execution/PKG-07_Event_Ingest_Bridges/1_Working/DEL-07-02_Daemon_SSE_subscriber_bridge/_CONTEXT.md": "0bb820ded2fe598b8484ee37ae11ae35a81720f8088b490e5c438725cf6af3f0",
    "projects/pec/execution/PKG-07_Event_Ingest_Bridges/1_Working/DEL-07-02_Daemon_SSE_subscriber_bridge/_REFERENCES.md": "de57dac815c281c09ce079ac8ec7b24f60956a20cf4631fe002f947f827c6ce0",
    "projects/pec/execution/PKG-07_Event_Ingest_Bridges/1_Working/DEL-07-03_Hooks_CLI_bridge/_CONTEXT.md": "508bd1de276c4235ecadadb2261ed7be470c78e87bdf2c32d45f774103215431",
    "projects/pec/execution/PKG-07_Event_Ingest_Bridges/1_Working/DEL-07-03_Hooks_CLI_bridge/_REFERENCES.md": "2530101559e367c8ac390c3e9279f72ce1bd4c2d8ef53f637d92aeab9ee11376",
    "projects/pec/execution/PKG-07_Event_Ingest_Bridges/1_Working/DEL-07-04_cmux_socket_adapter_optional/_CONTEXT.md": "5ac0787f665f6603fdc461e5816681584431715019937f292f26c9242dc81b43",
    "projects/pec/execution/PKG-07_Event_Ingest_Bridges/1_Working/DEL-07-04_cmux_socket_adapter_optional/_REFERENCES.md": "da78383887097c25858fdf531362d9f64604ca682d1ff909d7663f3bbe9a8869",
    "projects/pec/execution/PKG-07_Event_Ingest_Bridges/1_Working/DEL-07-05_Shared_runtime_client_seam_v2/_CONTEXT.md": "1adc79cd3779b756d80ff681e975adb52e776d612081e52bd0ad5acc618de12e",
    "projects/pec/execution/PKG-07_Event_Ingest_Bridges/1_Working/DEL-07-05_Shared_runtime_client_seam_v2/_REFERENCES.md": "c6a7a19512730fa3b255b4855e03aadbe02e4f4b71171805df9fe8972cccf57d",
    "projects/pec/execution/PKG-08_API_Access/1_Working/DEL-08-01_Unix_socket_server_token_scoped_access/_REFERENCES.md": "482b9f05504719abbc30ae38cdd8ef7a6b4b62d47b9042bbf8c9311a9a440bf2",
    "projects/pec/execution/PKG-08_API_Access/1_Working/DEL-08-02_Versioned_additive_API_schema/_CONTEXT.md": "38acdd6c8a7d812ba61387f91a751db7ffab723813546910cba3f5c23e52307d",
    "projects/pec/execution/PKG-08_API_Access/1_Working/DEL-08-02_Versioned_additive_API_schema/_REFERENCES.md": "4b9071df7e447bfd122d240588e6ea2238b7c537cdf04a199df9228f755d06c0",
    "projects/pec/execution/PKG-08_API_Access/1_Working/DEL-08-03_Compact_citation_bearing_response_format/_REFERENCES.md": "f5610e5c224662cc7df0b1fc5475893f75388fe17e503beb0db870c5264f0f4c",
    "projects/pec/execution/PKG-08_API_Access/1_Working/DEL-08-04_Orientation_latency_budget_p95_100_ms/_CONTEXT.md": "f5dd9ea168be0fc6fb6bd74dbf680f1e218867844bb619510e8c4bbd90df4634",
    "projects/pec/execution/PKG-08_API_Access/1_Working/DEL-08-04_Orientation_latency_budget_p95_100_ms/_REFERENCES.md": "1bfa6baf155e153f1e9607be9b8e57e3ee6d31f04e4ec40e0220f8201c8f873b",
    "projects/pec/execution/PKG-08_API_Access/1_Working/DEL-08-05_SSE_delta_presence_subscription/_CONTEXT.md": "ba3f7d6e10d52c9b6fc1185538d891ccad0833afea16107fd1b060d5cd4ae31d",
    "projects/pec/execution/PKG-08_API_Access/1_Working/DEL-08-05_SSE_delta_presence_subscription/_REFERENCES.md": "95fd692f88487d6f72c887512fcf618c7bb1ab4109a29650491a7bbaf470d6f1",
    "projects/pec/execution/PKG-09_Dashboards/1_Working/DEL-09-01_Overview_dashboard/_CONTEXT.md": "0a82ce9ef981ebab381b2897d6f42873dc80aad57ebc37bd695f6faeddc96131",
    "projects/pec/execution/PKG-09_Dashboards/1_Working/DEL-09-01_Overview_dashboard/_REFERENCES.md": "8ff66a8b3896cde83f907737b630fc6fc45b5e8e53acad646906b3dd22f14147",
    "projects/pec/execution/PKG-09_Dashboards/1_Working/DEL-09-02_Lifecycle_census_dashboard/_CONTEXT.md": "d9a623d6c6bc1a8651a84447b9e1cf85804aa26effecb95573acb253af6159c4",
    "projects/pec/execution/PKG-09_Dashboards/1_Working/DEL-09-02_Lifecycle_census_dashboard/_REFERENCES.md": "298ccd42e5fc6dabf85193cd14dba1c998f3056ff52bbb048387068c009170e8",
    "projects/pec/execution/PKG-09_Dashboards/1_Working/DEL-09-03_Register_views/_CONTEXT.md": "899954af31d1be0b19fb6cdfb94acfde72fbcddbc2519ebecc107dfe155089de",
    "projects/pec/execution/PKG-09_Dashboards/1_Working/DEL-09-03_Register_views/_REFERENCES.md": "c3905be1b42cef9e9965d486e0e8573bb82fdfa672afbe14aa68dce8b8a3130a",
    "projects/pec/execution/PKG-09_Dashboards/1_Working/DEL-09-04_Decision_slate_view_waiting_on_you/_CONTEXT.md": "a84fdb13b87ac8ac761898430bbe6d37b26d61f5db9db99b98e893f496c2773b",
    "projects/pec/execution/PKG-09_Dashboards/1_Working/DEL-09-04_Decision_slate_view_waiting_on_you/_REFERENCES.md": "37f5f6e22af354d35de5c7ab5023a627582d6c36b262e226abc9ce8776532538",
    "projects/pec/execution/PKG-09_Dashboards/1_Working/DEL-09-05_Presence_board/_CONTEXT.md": "cd2b2f6b4e14c2b47d9ee98f545cdc27f006275c92d3b01ef1d3142c6b52cab9",
    "projects/pec/execution/PKG-09_Dashboards/1_Working/DEL-09-05_Presence_board/_REFERENCES.md": "9a64f20affd93c89e895414b64f79aed500be6cf39c16c44854dea6bc70c3f2f",
    "projects/pec/execution/PKG-09_Dashboards/1_Working/DEL-09-06_Universal_drill_down_to_cited_source/_CONTEXT.md": "16157838aabf1d7b3acbd11d378df77975bdb086b23829dd4cd095803e5b99ce",
    "projects/pec/execution/PKG-09_Dashboards/1_Working/DEL-09-06_Universal_drill_down_to_cited_source/_REFERENCES.md": "971473698783d8eddbd6781b15c94d709bfdc7b8de5390a63f49bdacae855c22",
    "projects/pec/execution/PKG-09_Dashboards/1_Working/DEL-09-07_Explain_shaped_pressure_rules/_CONTEXT.md": "d7f98897834c9c8308c30f62a767912143dcf52d59731f796de62058958c38d5",
    "projects/pec/execution/PKG-09_Dashboards/1_Working/DEL-09-07_Explain_shaped_pressure_rules/_REFERENCES.md": "9adf8d8f56e53a08452a6aadc5f866a2c1d646a02235b7bff9b302cd2bfddef3",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-01_Step_0_cost_baseline_pre_P1/_CONTEXT.md": "94c93a624a2c84e1433d4c72712e5067e7e31fe1ed37cbad11d114bb4fdedbe5",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-01_Step_0_cost_baseline_pre_P1/_REFERENCES.md": "7b831447e279d9e296b9fecebe07fa3552b63a751ea5f750fa34ebe1b4ffe438",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-02_Kill_test_standing_release_gate/_CONTEXT.md": "da16ba796b54e3615d85f275b923d838f40140a216707e4a5a26427af28bd9de",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-02_Kill_test_standing_release_gate/_REFERENCES.md": "90ceb3a244b5b67d71f1ed350325c99eb92f190fbb8f2004b27c571b966256c8",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-03_No_ruling_write_verification/_CONTEXT.md": "2042fecf8c1c4c2b2ab993ba1170d6205ec07592e1dadaff2d7be6a30f760044",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-03_No_ruling_write_verification/_REFERENCES.md": "53469876f8fa7478b693ae399797335b00d2e38584feec99a4ca1a148450a5f8",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-04_Orientation_defect_rate_spot_check/_CONTEXT.md": "50afd95f55c1b82298ca132c2b28da65c4f7524e3b0f262236591eaa1124cd72",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-04_Orientation_defect_rate_spot_check/_REFERENCES.md": "2e63822889ea6445a1c14ebc3f485f2ebc31972ff9f0a7b9f17d1553b4cbaa17",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-05_Owner_consultation_logging/_CONTEXT.md": "23962c3bed576f73d9847c6cf486584d71ae8bdca8f07338af122c8ceaf5f204",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-05_Owner_consultation_logging/_REFERENCES.md": "401555caaba8bd84d864d842553cfcd539a8aab1871ea46e11fc60151d4d0788",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-06_Seeded_conflict_overlap_test/_CONTEXT.md": "fce20f41e538794ef2e281b7d946e7956daa5ef9b915887fc0cf8a34faaf8129",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-06_Seeded_conflict_overlap_test/_REFERENCES.md": "7fa66b924fd5c2c3b372037c4a7a58bb1a7f37803335511ba908341209890c59",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-07_Presence_TTL_honesty_tests/_CONTEXT.md": "695088ed3e70385121e22f31825b33efb2fd68e9452f41b500bc7d1d85eb7597",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-07_Presence_TTL_honesty_tests/_REFERENCES.md": "c1bdc4ea35a1ecfa98037b9465bf4bc7457e62b6a67ee5b3dce27078a26a2a3c",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-08_Stream_loss_recovery_demonstration/_CONTEXT.md": "d08c2b9050b93b1ca0581b5b08b39334c129e2dc47ad2b72bad9485ab6ae18d0",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-08_Stream_loss_recovery_demonstration/_REFERENCES.md": "c33e13a6782af6218edebe4a8c72b07bee0d82f1c60e730af616459af09ee874",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-09_Collision_incident_measurement/_CONTEXT.md": "6ff57483f8c75a268ea990c8dcc077e13169d78496c377aadec9007bdc55ac9a",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-09_Collision_incident_measurement/_REFERENCES.md": "a07e02eef7fa4256aa47ee80d1003ca82d7f891d9a6fe040246938c854fa00fa",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-10_Directed_bootstrap_self_ingest_validation/_CONTEXT.md": "7f3d7035d5760ce4f6636212f4b7932c5daff5170c3089bc0414a1372dde7c09",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-10_Directed_bootstrap_self_ingest_validation/_REFERENCES.md": "f9ce0996b74fb257b8a312652f940b12369ad169b8170bcff778e817b4967f7d",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-11_Parity_metric_DriftFindings_per_reconcile/_CONTEXT.md": "cda340e681a8ee5c7d2b005b5a703988ba37dcdebd6f18a1d3f8c8d6591d945e",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-11_Parity_metric_DriftFindings_per_reconcile/_REFERENCES.md": "e2dfd94a6dfd78ab6f9b28a2c2b4eae7e630a80562f8a8001b6c1a77f4a42c23",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-12_Poll_adoption_measurement/_CONTEXT.md": "23ce69245e66b4ad5104b9ed2189ae49b09e30df69f2f0aef0d03cd535cbba05",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-12_Poll_adoption_measurement/_REFERENCES.md": "cdd04184fcd742061e2d568120f14a34830827b753e559fc10d646cbd5a13983",
}
BASIS_PATHS = [
    "projects/pec/docs/PRD.md",
    "projects/pec/execution/_Decomposition/SOFTWARE_DECOMP.md",
    "projects/pec/execution/_Decomposition/Deliverables.csv",
    "projects/pec/execution/_Decomposition/ScopeLedger.csv",
    "projects/pec/execution/PKG-04_Orientation_Services/1_Working/DEL-04-03_Citation_freshness_stamping/_CONTEXT.md",
    "projects/pec/execution/PKG-08_API_Access/1_Working/DEL-08-01_Unix_socket_server_token_scoped_access/_CONTEXT.md",
    "projects/pec/execution/PKG-08_API_Access/1_Working/DEL-08-03_Compact_citation_bearing_response_format/_CONTEXT.md",
]
MIRROR_PATHS = [
    "projects/pec/execution/PKG-04_Orientation_Services/1_Working/DEL-04-03_Citation_freshness_stamping/_CONTEXT.md",
    "projects/pec/execution/PKG-08_API_Access/1_Working/DEL-08-01_Unix_socket_server_token_scoped_access/_CONTEXT.md",
    "projects/pec/execution/PKG-08_API_Access/1_Working/DEL-08-03_Compact_citation_bearing_response_format/_CONTEXT.md",
]
CTX_STD_PATHS = [
    "projects/pec/execution/PKG-00_Architecture_Runway_Contracts/1_Working/DEL-00-01_v2_first_ADRs_core_isolation_carried_postures/_CONTEXT.md",
    "projects/pec/execution/PKG-00_Architecture_Runway_Contracts/1_Working/DEL-00-02_Event_contract_schema_v1/_CONTEXT.md",
    "projects/pec/execution/PKG-00_Architecture_Runway_Contracts/1_Working/DEL-00-03_v2_SPEC_seed/_CONTEXT.md",
    "projects/pec/execution/PKG-01_Service_Core_Store/1_Working/DEL-01-01_Record_tier_schema_entity_model/_CONTEXT.md",
    "projects/pec/execution/PKG-01_Service_Core_Store/1_Working/DEL-01-02_Presence_tier_schema_entity_model/_CONTEXT.md",
    "projects/pec/execution/PKG-01_Service_Core_Store/1_Working/DEL-01-03_Store_bootstrap_content_minimal_guard/_CONTEXT.md",
    "projects/pec/execution/PKG-01_Service_Core_Store/1_Working/DEL-01-04_Self_observability_logging/_CONTEXT.md",
    "projects/pec/execution/PKG-01_Service_Core_Store/1_Working/DEL-01-05_Zero_dependency_locality_enforcement/_CONTEXT.md",
    "projects/pec/execution/PKG-01_Service_Core_Store/1_Working/DEL-01-06_Loop_registry_local_config_default/_CONTEXT.md",
    "projects/pec/execution/PKG-02_File_Truth_Parsers/1_Working/DEL-02-01_STATUS_md_parser/_CONTEXT.md",
    "projects/pec/execution/PKG-02_File_Truth_Parsers/1_Working/DEL-02-02_Decision_register_packet_parser/_CONTEXT.md",
    "projects/pec/execution/PKG-02_File_Truth_Parsers/1_Working/DEL-02-03_Receipts_ledger_parser_per_loop_grammars/_CONTEXT.md",
    "projects/pec/execution/PKG-02_File_Truth_Parsers/1_Working/DEL-02-04_Run_evidence_JSON_parser/_CONTEXT.md",
    "projects/pec/execution/PKG-02_File_Truth_Parsers/1_Working/DEL-02-05_Dependency_register_parser/_CONTEXT.md",
    "projects/pec/execution/PKG-02_File_Truth_Parsers/1_Working/DEL-02-06_Workplan_LOOP_INIT_parser/_CONTEXT.md",
    "projects/pec/execution/PKG-02_File_Truth_Parsers/1_Working/DEL-02-07_adapter_yaml_feed_manifest_consumer/_CONTEXT.md",
    "projects/pec/execution/PKG-03_Reconciliation_Parity/1_Working/DEL-03-01_Full_rebuild_reconciler_one_command/_CONTEXT.md",
    "projects/pec/execution/PKG-03_Reconciliation_Parity/1_Working/DEL-03-02_Incremental_reconcile_on_Git_delta/_CONTEXT.md",
    "projects/pec/execution/PKG-03_Reconciliation_Parity/1_Working/DEL-03-03_Drift_classification/_CONTEXT.md",
    "projects/pec/execution/PKG-03_Reconciliation_Parity/1_Working/DEL-03-04_Practitioner_harness_parity_diff/_CONTEXT.md",
    "projects/pec/execution/PKG-03_Reconciliation_Parity/1_Working/DEL-03-05_Stream_loss_recovery_guarantee/_CONTEXT.md",
    "projects/pec/execution/PKG-03_Reconciliation_Parity/1_Working/DEL-03-06_Rebuild_performance_bounds/_CONTEXT.md",
    "projects/pec/execution/PKG-04_Orientation_Services/1_Working/DEL-04-01_Loop_orientation_return/_CONTEXT.md",
    "projects/pec/execution/PKG-04_Orientation_Services/1_Working/DEL-04-02_Delta_service_since_SHA/_CONTEXT.md",
    "projects/pec/execution/PKG-04_Orientation_Services/1_Working/DEL-04-04_Scope_parameterization/_CONTEXT.md",
    "projects/pec/execution/PKG-04_Orientation_Services/1_Working/DEL-04-05_Measurement_limitation_honesty/_CONTEXT.md",
    "projects/pec/execution/PKG-05_Gate_Evaluation_Decision_Slate/1_Working/DEL-05-01_Gate_precondition_evaluators_Explain_shaped/_CONTEXT.md",
    "projects/pec/execution/PKG-05_Gate_Evaluation_Decision_Slate/1_Working/DEL-05-02_Cross_loop_decision_slate/_CONTEXT.md",
    "projects/pec/execution/PKG-06_Presence_Git_Observation/1_Working/DEL-06-01_Session_presence_records/_CONTEXT.md",
    "projects/pec/execution/PKG-06_Presence_Git_Observation/1_Working/DEL-06-02_Git_worktree_scanner/_CONTEXT.md",
    "projects/pec/execution/PKG-06_Presence_Git_Observation/1_Working/DEL-06-03_Session_worktree_scope_correlation/_CONTEXT.md",
    "projects/pec/execution/PKG-06_Presence_Git_Observation/1_Working/DEL-06-04_Live_hierarchy_edges/_CONTEXT.md",
    "projects/pec/execution/PKG-06_Presence_Git_Observation/1_Working/DEL-06-05_TTL_heartbeat_discipline_citation_exclusion/_CONTEXT.md",
    "projects/pec/execution/PKG-06_Presence_Git_Observation/1_Working/DEL-06-06_Advisory_overlap_detection/_CONTEXT.md",
    "projects/pec/execution/PKG-07_Event_Ingest_Bridges/1_Working/DEL-07-01_Idempotent_event_ingest_durable_message_store/_CONTEXT.md",
    "projects/pec/execution/PKG-07_Event_Ingest_Bridges/1_Working/DEL-07-02_Daemon_SSE_subscriber_bridge/_CONTEXT.md",
    "projects/pec/execution/PKG-07_Event_Ingest_Bridges/1_Working/DEL-07-03_Hooks_CLI_bridge/_CONTEXT.md",
    "projects/pec/execution/PKG-07_Event_Ingest_Bridges/1_Working/DEL-07-04_cmux_socket_adapter_optional/_CONTEXT.md",
    "projects/pec/execution/PKG-07_Event_Ingest_Bridges/1_Working/DEL-07-05_Shared_runtime_client_seam_v2/_CONTEXT.md",
    "projects/pec/execution/PKG-08_API_Access/1_Working/DEL-08-02_Versioned_additive_API_schema/_CONTEXT.md",
    "projects/pec/execution/PKG-08_API_Access/1_Working/DEL-08-04_Orientation_latency_budget_p95_100_ms/_CONTEXT.md",
    "projects/pec/execution/PKG-08_API_Access/1_Working/DEL-08-05_SSE_delta_presence_subscription/_CONTEXT.md",
    "projects/pec/execution/PKG-09_Dashboards/1_Working/DEL-09-01_Overview_dashboard/_CONTEXT.md",
    "projects/pec/execution/PKG-09_Dashboards/1_Working/DEL-09-02_Lifecycle_census_dashboard/_CONTEXT.md",
    "projects/pec/execution/PKG-09_Dashboards/1_Working/DEL-09-03_Register_views/_CONTEXT.md",
    "projects/pec/execution/PKG-09_Dashboards/1_Working/DEL-09-04_Decision_slate_view_waiting_on_you/_CONTEXT.md",
    "projects/pec/execution/PKG-09_Dashboards/1_Working/DEL-09-05_Presence_board/_CONTEXT.md",
    "projects/pec/execution/PKG-09_Dashboards/1_Working/DEL-09-06_Universal_drill_down_to_cited_source/_CONTEXT.md",
    "projects/pec/execution/PKG-09_Dashboards/1_Working/DEL-09-07_Explain_shaped_pressure_rules/_CONTEXT.md",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-01_Step_0_cost_baseline_pre_P1/_CONTEXT.md",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-02_Kill_test_standing_release_gate/_CONTEXT.md",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-03_No_ruling_write_verification/_CONTEXT.md",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-04_Orientation_defect_rate_spot_check/_CONTEXT.md",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-05_Owner_consultation_logging/_CONTEXT.md",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-06_Seeded_conflict_overlap_test/_CONTEXT.md",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-07_Presence_TTL_honesty_tests/_CONTEXT.md",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-08_Stream_loss_recovery_demonstration/_CONTEXT.md",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-09_Collision_incident_measurement/_CONTEXT.md",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-10_Directed_bootstrap_self_ingest_validation/_CONTEXT.md",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-11_Parity_metric_DriftFindings_per_reconcile/_CONTEXT.md",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-12_Poll_adoption_measurement/_CONTEXT.md",
]
REF_PATHS = [
    "projects/pec/execution/PKG-00_Architecture_Runway_Contracts/1_Working/DEL-00-01_v2_first_ADRs_core_isolation_carried_postures/_REFERENCES.md",
    "projects/pec/execution/PKG-00_Architecture_Runway_Contracts/1_Working/DEL-00-02_Event_contract_schema_v1/_REFERENCES.md",
    "projects/pec/execution/PKG-00_Architecture_Runway_Contracts/1_Working/DEL-00-03_v2_SPEC_seed/_REFERENCES.md",
    "projects/pec/execution/PKG-01_Service_Core_Store/1_Working/DEL-01-01_Record_tier_schema_entity_model/_REFERENCES.md",
    "projects/pec/execution/PKG-01_Service_Core_Store/1_Working/DEL-01-02_Presence_tier_schema_entity_model/_REFERENCES.md",
    "projects/pec/execution/PKG-01_Service_Core_Store/1_Working/DEL-01-03_Store_bootstrap_content_minimal_guard/_REFERENCES.md",
    "projects/pec/execution/PKG-01_Service_Core_Store/1_Working/DEL-01-04_Self_observability_logging/_REFERENCES.md",
    "projects/pec/execution/PKG-01_Service_Core_Store/1_Working/DEL-01-05_Zero_dependency_locality_enforcement/_REFERENCES.md",
    "projects/pec/execution/PKG-01_Service_Core_Store/1_Working/DEL-01-06_Loop_registry_local_config_default/_REFERENCES.md",
    "projects/pec/execution/PKG-02_File_Truth_Parsers/1_Working/DEL-02-01_STATUS_md_parser/_REFERENCES.md",
    "projects/pec/execution/PKG-02_File_Truth_Parsers/1_Working/DEL-02-02_Decision_register_packet_parser/_REFERENCES.md",
    "projects/pec/execution/PKG-02_File_Truth_Parsers/1_Working/DEL-02-03_Receipts_ledger_parser_per_loop_grammars/_REFERENCES.md",
    "projects/pec/execution/PKG-02_File_Truth_Parsers/1_Working/DEL-02-04_Run_evidence_JSON_parser/_REFERENCES.md",
    "projects/pec/execution/PKG-02_File_Truth_Parsers/1_Working/DEL-02-05_Dependency_register_parser/_REFERENCES.md",
    "projects/pec/execution/PKG-02_File_Truth_Parsers/1_Working/DEL-02-06_Workplan_LOOP_INIT_parser/_REFERENCES.md",
    "projects/pec/execution/PKG-02_File_Truth_Parsers/1_Working/DEL-02-07_adapter_yaml_feed_manifest_consumer/_REFERENCES.md",
    "projects/pec/execution/PKG-02_File_Truth_Parsers/1_Working/DEL-02-08_Work_graph_parser/_REFERENCES.md",
    "projects/pec/execution/PKG-02_File_Truth_Parsers/1_Working/DEL-02-09_MEMORY_run_index_parser/_REFERENCES.md",
    "projects/pec/execution/PKG-03_Reconciliation_Parity/1_Working/DEL-03-01_Full_rebuild_reconciler_one_command/_REFERENCES.md",
    "projects/pec/execution/PKG-03_Reconciliation_Parity/1_Working/DEL-03-02_Incremental_reconcile_on_Git_delta/_REFERENCES.md",
    "projects/pec/execution/PKG-03_Reconciliation_Parity/1_Working/DEL-03-03_Drift_classification/_REFERENCES.md",
    "projects/pec/execution/PKG-03_Reconciliation_Parity/1_Working/DEL-03-04_Practitioner_harness_parity_diff/_REFERENCES.md",
    "projects/pec/execution/PKG-03_Reconciliation_Parity/1_Working/DEL-03-05_Stream_loss_recovery_guarantee/_REFERENCES.md",
    "projects/pec/execution/PKG-03_Reconciliation_Parity/1_Working/DEL-03-06_Rebuild_performance_bounds/_REFERENCES.md",
    "projects/pec/execution/PKG-04_Orientation_Services/1_Working/DEL-04-01_Loop_orientation_return/_REFERENCES.md",
    "projects/pec/execution/PKG-04_Orientation_Services/1_Working/DEL-04-02_Delta_service_since_SHA/_REFERENCES.md",
    "projects/pec/execution/PKG-04_Orientation_Services/1_Working/DEL-04-03_Citation_freshness_stamping/_REFERENCES.md",
    "projects/pec/execution/PKG-04_Orientation_Services/1_Working/DEL-04-04_Scope_parameterization/_REFERENCES.md",
    "projects/pec/execution/PKG-04_Orientation_Services/1_Working/DEL-04-05_Measurement_limitation_honesty/_REFERENCES.md",
    "projects/pec/execution/PKG-05_Gate_Evaluation_Decision_Slate/1_Working/DEL-05-01_Gate_precondition_evaluators_Explain_shaped/_REFERENCES.md",
    "projects/pec/execution/PKG-05_Gate_Evaluation_Decision_Slate/1_Working/DEL-05-02_Cross_loop_decision_slate/_REFERENCES.md",
    "projects/pec/execution/PKG-06_Presence_Git_Observation/1_Working/DEL-06-01_Session_presence_records/_REFERENCES.md",
    "projects/pec/execution/PKG-06_Presence_Git_Observation/1_Working/DEL-06-02_Git_worktree_scanner/_REFERENCES.md",
    "projects/pec/execution/PKG-06_Presence_Git_Observation/1_Working/DEL-06-03_Session_worktree_scope_correlation/_REFERENCES.md",
    "projects/pec/execution/PKG-06_Presence_Git_Observation/1_Working/DEL-06-04_Live_hierarchy_edges/_REFERENCES.md",
    "projects/pec/execution/PKG-06_Presence_Git_Observation/1_Working/DEL-06-05_TTL_heartbeat_discipline_citation_exclusion/_REFERENCES.md",
    "projects/pec/execution/PKG-06_Presence_Git_Observation/1_Working/DEL-06-06_Advisory_overlap_detection/_REFERENCES.md",
    "projects/pec/execution/PKG-07_Event_Ingest_Bridges/1_Working/DEL-07-01_Idempotent_event_ingest_durable_message_store/_REFERENCES.md",
    "projects/pec/execution/PKG-07_Event_Ingest_Bridges/1_Working/DEL-07-02_Daemon_SSE_subscriber_bridge/_REFERENCES.md",
    "projects/pec/execution/PKG-07_Event_Ingest_Bridges/1_Working/DEL-07-03_Hooks_CLI_bridge/_REFERENCES.md",
    "projects/pec/execution/PKG-07_Event_Ingest_Bridges/1_Working/DEL-07-04_cmux_socket_adapter_optional/_REFERENCES.md",
    "projects/pec/execution/PKG-07_Event_Ingest_Bridges/1_Working/DEL-07-05_Shared_runtime_client_seam_v2/_REFERENCES.md",
    "projects/pec/execution/PKG-08_API_Access/1_Working/DEL-08-01_Unix_socket_server_token_scoped_access/_REFERENCES.md",
    "projects/pec/execution/PKG-08_API_Access/1_Working/DEL-08-02_Versioned_additive_API_schema/_REFERENCES.md",
    "projects/pec/execution/PKG-08_API_Access/1_Working/DEL-08-03_Compact_citation_bearing_response_format/_REFERENCES.md",
    "projects/pec/execution/PKG-08_API_Access/1_Working/DEL-08-04_Orientation_latency_budget_p95_100_ms/_REFERENCES.md",
    "projects/pec/execution/PKG-08_API_Access/1_Working/DEL-08-05_SSE_delta_presence_subscription/_REFERENCES.md",
    "projects/pec/execution/PKG-09_Dashboards/1_Working/DEL-09-01_Overview_dashboard/_REFERENCES.md",
    "projects/pec/execution/PKG-09_Dashboards/1_Working/DEL-09-02_Lifecycle_census_dashboard/_REFERENCES.md",
    "projects/pec/execution/PKG-09_Dashboards/1_Working/DEL-09-03_Register_views/_REFERENCES.md",
    "projects/pec/execution/PKG-09_Dashboards/1_Working/DEL-09-04_Decision_slate_view_waiting_on_you/_REFERENCES.md",
    "projects/pec/execution/PKG-09_Dashboards/1_Working/DEL-09-05_Presence_board/_REFERENCES.md",
    "projects/pec/execution/PKG-09_Dashboards/1_Working/DEL-09-06_Universal_drill_down_to_cited_source/_REFERENCES.md",
    "projects/pec/execution/PKG-09_Dashboards/1_Working/DEL-09-07_Explain_shaped_pressure_rules/_REFERENCES.md",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-01_Step_0_cost_baseline_pre_P1/_REFERENCES.md",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-02_Kill_test_standing_release_gate/_REFERENCES.md",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-03_No_ruling_write_verification/_REFERENCES.md",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-04_Orientation_defect_rate_spot_check/_REFERENCES.md",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-05_Owner_consultation_logging/_REFERENCES.md",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-06_Seeded_conflict_overlap_test/_REFERENCES.md",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-07_Presence_TTL_honesty_tests/_REFERENCES.md",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-08_Stream_loss_recovery_demonstration/_REFERENCES.md",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-09_Collision_incident_measurement/_REFERENCES.md",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-10_Directed_bootstrap_self_ingest_validation/_REFERENCES.md",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-11_Parity_metric_DriftFindings_per_reconcile/_REFERENCES.md",
    "projects/pec/execution/PKG-10_Validation_Measurement/1_Working/DEL-10-12_Poll_adoption_measurement/_REFERENCES.md",
]
CTX_D93_PATHS = {
    "projects/pec/execution/PKG-02_File_Truth_Parsers/1_Working/DEL-02-08_Work_graph_parser/_CONTEXT.md": "A-19",
    "projects/pec/execution/PKG-02_File_Truth_Parsers/1_Working/DEL-02-09_MEMORY_run_index_parser/_CONTEXT.md": "A-20",
}

# Basis currency anchors (each must occur exactly once).
PRD_VERSION_ANCHOR = "\n| **Version** | 2.4 |\n"
DECOMP_VERSION_ANCHORS = ['\nrevision: "1.6"\n', "\n| Revision | 1.6, 2026-09-26 (SCA-006) |\n"]

CTX_STD_OLD = "then by revision 1.5 (`current_basis`, SCA-005 successor).\n"
CTX_STD_NEW = ("then by revision 1.5 (`current_basis`, SCA-005 successor),\n"
               "then by revision 1.6 (`current_basis`, SCA-006 successor).\n")
CTX_D93_OLD = "SCA-005 successor; deliverable added by {A}). Fields templated\n"
CTX_D93_NEW = ("SCA-005 successor; deliverable added by {A}),\n"
               "then by revision 1.6 (`current_basis`, SCA-006 successor). Fields templated\n")
REF_PAIRS = [
    ("- `execution/_Decomposition/SOFTWARE_DECOMP.md` (revision 1.5, accepted `current_basis`; SCA-005 successor)\n",
     "- `execution/_Decomposition/SOFTWARE_DECOMP.md` (revision 1.6, accepted `current_basis`; SCA-006 successor)\n"),
    ("- `docs/PRD.md` v2.3 (accepted source corpus; see SourceRef column of the ledger)\n",
     "- `docs/PRD.md` v2.4 (accepted source corpus; see SourceRef column of the ledger)\n"),
]
COVERS_LINE = "- `execution/_Decomposition/ScopeLedger.csv` (SOW→PKG→DEL→OBJ ledger; covers {S})\n"
COVERS_RE = re.compile(r"^- `execution/_Decomposition/ScopeLedger\.csv` \(SOW→PKG→DEL→OBJ ledger; covers (.*)\)$",
                       re.M)
RETIRED_COVERS_RE = re.compile(r"none — retired under SCA-005, formerly SOW-\d{3}")
# Add-on C: revision 1.6 added SOW-097 to DEL-04-03 and SOW-098 to DEL-08-03.
COVERS_ADDON = {
    "DEL-04-03": ("SOW-006;SOW-007", "SOW-006;SOW-007;SOW-097", "SOW-097"),
    "DEL-08-03": ("SOW-043", "SOW-043;SOW-098", "SOW-098"),
}
# The final "revision X.Y (`current_basis`, SCA-NNN successor" clause of a provenance block.
REV_CLAUSE_RE = re.compile(r"revision (\d+\.\d+) \(`current_basis`,\s+(SCA-\d{3}) successor")


class Fail(Exception):
    pass


def sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def replace_once(text: str, old: str, new: str, where: str) -> str:
    n = text.count(old)
    if n != 1:
        raise Fail(f"anchor count {n} != 1 in {where}: {old[:80]!r}")
    return text.replace(old, new)


def provenance(text: str, where: str) -> str:
    """The `## Provenance` block: from its heading to the next level-2 heading or EOF."""
    if text.count("\n## Provenance\n") != 1:
        raise Fail(f"{where}: `## Provenance` heading count != 1")
    block = "## Provenance\n" + text.split("\n## Provenance\n", 1)[1]
    nxt = block.find("\n## ", 1)
    return block if nxt < 0 else block[: nxt + 1]


def final_clause(text: str, where: str) -> tuple[str, str] | None:
    found = REV_CLAUSE_RE.findall(provenance(text, where))
    return found[-1] if found else None


def ctx_current(text: str, where: str) -> bool:
    return final_clause(text, where) == ("1.6", "SCA-006")


def ref_current(text: str) -> bool:
    return (REF_PAIRS[0][1] in text and REF_PAIRS[1][1] in text
            and REF_PAIRS[0][0] not in text and REF_PAIRS[1][0] not in text)


def del_id(rel: str) -> str:
    return Path(rel).parent.name.split("_")[0]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", required=True, type=Path)
    ap.add_argument("--covers", action="store_true", help="add-on C (DEL-04-03 / DEL-08-03 covers lists)")
    ap.add_argument("--check-only", action="store_true", help="render and check; write nothing")
    a = ap.parse_args()
    repo = a.repo.resolve()
    report: list[tuple[str, str, str, str]] = []
    try:
        # 0. preimages (targets and basis)
        for rel, want in PREIMAGES.items():
            p = repo / rel
            if not p.is_file():
                raise Fail(f"pinned path missing: {rel}")
            got = sha(p.read_bytes())
            if got != want:
                raise Fail(f"preimage mismatch {rel}: {got} != {want}")
            report.append(("READ", rel, got, "basis" if rel in BASIS_PATHS else "target"))
        prd_text = (repo / PRD).read_text(encoding="utf-8")
        if prd_text.count(PRD_VERSION_ANCHOR) != 1:
            raise Fail("PRD.md does not name version 2.4 exactly once at the pinned anchor")
        decomp_text = (repo / DECOMP).read_text(encoding="utf-8")
        for anchor in DECOMP_VERSION_ANCHORS:
            if decomp_text.count(anchor) != 1:
                raise Fail(f"SOFTWARE_DECOMP.md anchor {anchor.strip()!r} count != 1")
        report.append(("CHECK", "basis_versions", "PRD 2.4", "SOFTWARE_DECOMP 1.6"))
        with open(repo / DELIVERABLES, newline="", encoding="utf-8") as f:
            dels = {r["DeliverableID"]: r for r in csv.DictReader(f)}

        # 1. population (globbed at run time; fail closed on anything unexpected)
        work = repo / EX
        all_ctx = sorted(str(p.relative_to(repo)) for p in work.glob("PKG-*/1_Working/DEL-*/_CONTEXT.md"))
        all_ref = sorted(str(p.relative_to(repo)) for p in work.glob("PKG-*/1_Working/DEL-*/_REFERENCES.md"))
        folders = sorted(str(p.relative_to(repo)) for p in work.glob("PKG-*/1_Working/DEL-*") if p.is_dir())
        ctext = {p: (repo / p).read_text(encoding="utf-8") for p in all_ctx}
        rtext = {p: (repo / p).read_text(encoding="utf-8") for p in all_ref}
        pinned_ctx = set(CTX_STD_PATHS) | set(CTX_D93_PATHS)
        extra_ctx, extra_ref = [], []
        for p in all_ctx:
            if p in pinned_ctx or p in MIRROR_PATHS:
                continue
            t = ctext[p]
            if not ctx_current(t, p) or CTX_STD_OLD in t or "SCA-005 successor; deliverable added by" in t:
                raise Fail(f"unpinned context is not already at revision 1.6: {p}")
            extra_ctx.append(p)
        for p in all_ref:
            if p in REF_PATHS:
                continue
            if not ref_current(rtext[p]):
                raise Fail(f"unpinned reference packet is not already at revision 1.6 / PRD v2.4: {p}")
            extra_ref.append(p)
        missing = sorted((pinned_ctx | set(MIRROR_PATHS) | set(REF_PATHS)) - set(all_ctx) - set(all_ref))
        if missing:
            raise Fail(f"pinned paths outside the globbed population: {missing[:3]}")
        report.append(("CHECK", "population_folders", str(len(folders)), f"{len(extra_ctx)} contexts / "
                       f"{len(extra_ref)} references already at 1.6 beyond the pins"))

        # 2. render
        writes: dict[str, bytes] = {}
        for p in CTX_STD_PATHS:
            writes[p] = replace_once(ctext[p], CTX_STD_OLD, CTX_STD_NEW, p).encode("utf-8")
        for p, anum in CTX_D93_PATHS.items():
            writes[p] = replace_once(ctext[p], CTX_D93_OLD.replace("{A}", anum),
                                     CTX_D93_NEW.replace("{A}", anum), p).encode("utf-8")
        for p in REF_PATHS:
            t = rtext[p]
            for old, new in REF_PAIRS:
                t = replace_once(t, old, new, p)
            d = del_id(p)
            if a.covers and d in COVERS_ADDON:
                old_s, new_s, sow = COVERS_ADDON[d]
                if dels[d]["CoversScopeItems"] != new_s:
                    raise Fail(f"{d}: Deliverables.csv CoversScopeItems {dels[d]['CoversScopeItems']!r} != {new_s!r}")
                t = replace_once(t, COVERS_LINE.replace("{S}", old_s), COVERS_LINE.replace("{S}", new_s), p)
                report.append(("CHECK", f"covers_addon {d}", new_s, "equals Deliverables.csv cell"))
            writes[p] = t.encode("utf-8")

        # 3. post-state checks on the rendered corpus
        post_c = {p: (writes[p].decode("utf-8") if p in writes else ctext[p]) for p in all_ctx}
        post_r = {p: (writes[p].decode("utf-8") if p in writes else rtext[p]) for p in all_ref}
        stale_c = [p for p in all_ctx if not ctx_current(post_c[p], p)]
        if stale_c:
            raise Fail(f"after rendering, contexts not ending at revision 1.6: {stale_c[:3]}")
        report.append(("CHECK", "contexts_final_clause_revision_1.6", str(len(all_ctx) - len(stale_c)),
                       str(len(all_ctx))))
        stale_r = [p for p in all_ref if not ref_current(post_r[p])]
        if stale_r:
            raise Fail(f"after rendering, references not at revision 1.6 / PRD v2.4: {stale_r[:3]}")
        report.append(("CHECK", "references_revision_1.6_prd_2.4", str(len(all_ref) - len(stale_r)),
                       str(len(all_ref))))
        blocks = {provenance(post_c[p], p) for p in list(CTX_STD_PATHS) + list(MIRROR_PATHS)}
        if len(blocks) != 1:
            raise Fail(f"{len(blocks)} distinct provenance blocks across the 61 re-pinned contexts and 3 mirrors")
        report.append(("CHECK", "provenance_block_identity", str(len(CTX_STD_PATHS) + len(MIRROR_PATHS)),
                       sha(next(iter(blocks)).encode("utf-8"))))
        # report-only: covers list versus register cell, every reference
        agree, disagree = 0, []
        for p in all_ref:
            m = COVERS_RE.findall(post_r[p])
            cell = dels.get(del_id(p), {}).get("CoversScopeItems")
            ok = len(m) == 1 and cell is not None and (
                m[0] == cell or (cell == "" and RETIRED_COVERS_RE.fullmatch(m[0]) is not None))
            if ok:
                agree += 1
            else:
                disagree.append(del_id(p))
        report.append(("CHECK", "covers_equal_register_report_only", f"{agree}/{len(all_ref)}",
                       ";".join(disagree) if disagree else "none differ"))

        # 4. grant
        expected = set(CTX_STD_PATHS) | set(CTX_D93_PATHS) | set(REF_PATHS)
        if set(writes) != expected or len(writes) != 129:
            raise Fail(f"write set differs from the grant: {sorted(set(writes) ^ expected)[:5]}")
        for rel in writes:
            if rel not in PREIMAGES or rel in BASIS_PATHS:
                raise Fail(f"write target without a pinned target preimage: {rel}")

        # 5. write (every postimage computed and checked above)
        agg_pre, agg_post = hashlib.sha256(), hashlib.sha256()
        order = sorted(writes, key=lambda r: r.encode("utf-8"))
        for rel in order:
            pre = (repo / rel).read_bytes()
            agg_pre.update(pre)
            agg_post.update(writes[rel])
            report.append(("RENDER" if a.check_only else "WRITE", rel, sha(pre), sha(writes[rel])))
        if not a.check_only:
            for rel in order:
                (repo / rel).write_bytes(writes[rel])
        tag = "A+C" if a.covers else "A"
        paths = "".join(r + "\n" for r in order).encode("utf-8")
        report.append(("CHECK", f"aggregate flags={tag} files={len(writes)}", agg_pre.hexdigest(),
                       agg_post.hexdigest()))
        report.append(("CHECK", f"pathlist flags={tag}", sha(paths), "newline-terminated, bytewise-sorted"))
    except Fail as exc:
        print(f"FAIL: {exc}", file=sys.stderr)
        return 1
    for row in report:
        print("\t".join(row))
    return 0


if __name__ == "__main__":
    sys.exit(main())
